### ISSUE TITLE
貸出の表示画面に「利用者番号」を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1007]
- [x] 確認
- [ ] マニュアル #1066 

（貸出期間の延長→表示でたどった先の画面）

「現在の利用者」　のあたりに「利用者番号」を表示してほしい

![image](https://cloud.githubusercontent.com/assets/1328499/11804788/b76e6046-a349-11e5-99e0-a4eb5c1252f6.png)

以下のようなかんじで。

* 現在の貸出利用者
    * ユーザ名：user10
    * 利用者番号:100010

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
利用者番号を表示するようにしました。
http://dev.next-l.jp/checkouts/52

![fireshot capture 21 - - - next-l enju leaf - http___dev next-l jp_checkouts_52](https://cloud.githubusercontent.com/assets/11428/11912381/d91ce06e-a67d-11e5-9dbb-d109e964d37a.png)

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。
マニュアルはあとで修正します。
（気付いたけど、右メニューの　「貸出の一覧に戻る」がなくなってしまってますね。）

![image](https://cloud.githubusercontent.com/assets/1328499/11999728/7981593e-ab08-11e5-8b81-4ced106a5faf.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 7ca6e04)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 b6ba55b)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
