### ISSUE TITLE
貸出の編集画面に「利用者番号」を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1008]
#1007 と関連、類似です。 #1002 とも関連します。

（貸出期間の延長をたどった先の画面）

「現在の利用者」といっしょに「利用者番号」を表示してほしい

![image](https://cloud.githubusercontent.com/assets/1328499/11804879/95fbcb96-a34a-11e5-9a21-849e69c276b4.png)

以下のようなかんじで。
- 現在の貸出利用者
  - ユーザ名：user10
  - 利用者番号:100010

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.0 afc4ce5)
- enju_event (0.1.17 f886ee3)
- enju_flower (0.1.0)
- enju_leaf (1.1.1 917e0e9)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0 78c4280)
- enju_subject (0.1.0)

**Comment by nabeta** [comment]
以下のように、貸出利用者のユーザ名と利用者番号を表示するようにしました。
https://enju.next-l.jp/checkouts/180/edit

<img width="392" alt="スクリーンショット 2019-05-01 7 28 48" src="https://user-images.githubusercontent.com/11428/56997448-c7c70280-6be2-11e9-9255-1ee52ad8deae.png">

**Comment by masao** [comment]
修正を確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/57978197-17128d00-7a43-11e9-9608-a98b9c6ed53c.png)
