### ISSUE TITLE
[貸出期間延長] の時の「更新回数」はどういう動きを想定しているか教えてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1009]
#1005 に関連

バグならバグで1.1系のマニュアル（ #891 ）に書いておきたい

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by masao** [comment]
管理者が更新するときは手動更新、一般ユーザは一回更新するごとにインクリメント、というような挙動ではなかったかと思います。

**Comment by yegusa** [comment]
そもそも、「更新回数」はなにを意味したいのかがわからなく。。。

**Comment by masao** [comment]
更新回数は、「貸出延長」の回数のことです。貸出期間を超えて、もう1・2回期間延長をできるサービスを多くの図書館で導入していますが、これの回数を数えておいて、更新回数の期限設定になっているかをチェックする必要があります。
http://next-l.github.io/manual/enju_setup_3.html#section3-6 にも「貸出更新回数の上限」として説明があります。

**Comment by yegusa** [comment]
なるほど。図書館職員が操作した場合、更新回数を少なくして、あらかじめ設定された更新回数上限を超えないようにしようと思えばできるってことですよね?

あと、仕様では、ここで0と入力しておくと1になるという理解でよいでしょうか?

**Comment by masao** [comment]
いや、それはおかしな仕様ですね。普通は自分で変更可能なら、そのまま保存されるようにしないと直感に反する挙動ですね。バグではないでしょうか。

**Comment by masao** [comment]
普通は編集メニューを表示した瞬間にインクリメントした値が入力されていて、それを編集可能にする。

つまり、はじめての貸出のとき：

> 期限日： 2015-12-19, 更新回数： 0

となっている貸出情報を図書館員が編集しようと編集画面を開くと、

> 期限日： 2015-12-26, 更新回数: 1

と期限日の延長と更新回数のインクリメントがされた状態で編集できる画面となるのがよいのではないかと思います。

**Comment by yegusa** [comment]
確かに、そう、ですよね。

**Comment by yegusa** [comment]
じゃあ、そういう想定のもとにマニュアルを書きます。
そして、 #1005 のバグもそういう前提で修正かけると。

というわけでこちらはクローズします。

**Comment by yegusa** [comment]
クローズした後に @masao さんと議論したのですが、

* 更新回数を生でいじるようにするのは違和感
* 更新回数を増やさない　といったチェックを付けるという案がでた
* そもそも、Librarian権限以上では更新回数を増やす必要はなく、返却期限だけを延ばせるようにしておくとよいのではないか
* [返却期間の延長]　クリックした先の更新回数の挙動について検討する必要がある

などの話になりました。

1.2系ではこの辺の挙動は見直しましょう。

ひとまずはメモまで。

**Comment by yegusa** [comment]
1.1系のマニュアルでは、librarian権限では「更新回数」が編集できるように見えるが実際には修正できない旨を書くこととします。
