### ISSUE TITLE
予約の一覧のTSVダウンロードに「利用者番号」「manifestation_id」「受け取り館」「著者」「出版者」「出版年」を出力するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1011]
#1010 、 #1000 に関連します。
- 利用者番号・・・あったほうが便利じゃないかなとおもう。（ユーザ名があるので）
- manifestation_id ・・・予約の一覧に合わせて（書誌詳細へのリンクがあるので）
- 受け取り館・・・予約の一覧に合わせて
- 著者・・・予約の一覧に合わせて
- 出版者・・・予約の一覧に合わせて
- 出版年・・・予約の一覧に合わせて

を出力するようにしてほしい

http://localhost:8080/reserves.txt?locale=ja

<pre>
id  title   isbn    item_identifier call_number username    created_at  expired_at  state
11  "わたしをみつけて"  9784591145579           user06  2015-12-14 23:51:23 +0900       受付済み
10  "はじめてのRuby on Rails : 話題の「Webアプリケーション・フレームワーク」が使える! : instant rails"    9784777512324           user01  2015-12-14 23:50:35 +0900       受付済み
9   "ハリー・ポッターと不死鳥の騎士団"  9784915512674           user01  2015-12-14 23:50:03 +0900       受付済み
8   "ハリー・ポッターと不死鳥の騎士団"  9784915512674           user02  2015-12-14 23:49:47 +0900       受付済み
7   "ハリー・ポッターと賢者の石"   9784915512490           user01  2015-12-14 22:57:34 +0900       取消済み
6   "Ajax on Rails : build dynamic Web applications with Ruby"  9784873113326   909095  547|レ|1   user02  2015-12-14 22:29:07 +0900       取置済み
5   "ハリー・ポッターと賢者の石"   9784915512490   700001      user02  2015-12-12 10:43:41 +0900       取置済み
4   "図書館情報資源概論"   9784762023040   808080      user02  2015-12-11 17:06:27 +0900       取置済み
3   "図書館情報資源概論"   9784762023040           enjuadmin   2015-12-11 16:36:07 +0900       受付済み
2   "レッスン"  9784582831351           enjuadmin   2015-12-10 01:42:21 +0900       受付済み
1   "Ruby on Rails環境構築ガイド : ソース管理から公開までを徹底解説 : 定番ツールを使いこなして今日から即戦力!"    9784844333753           user01  2015-12-08 17:33:21 +0900       受付済み
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.0 afc4ce5)
- enju_event (0.1.17 f886ee3)
- enju_flower (0.1.0)
- enju_leaf (1.1.1 917e0e9)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0 78c4280)
- enju_subject (0.1.0)

**Comment by nabeta** [comment]
> - 利用者番号・・・あったほうが便利じゃないかなとおもう。（ユーザ名があるので）
> - manifestation_id ・・・予約の一覧に合わせて（書誌詳細へのリンクがあるので）
> - 受け取り館・・・予約の一覧に合わせて
> - 著者・・・予約の一覧に合わせて
> - 出版者・・・予約の一覧に合わせて
> - 出版年・・・予約の一覧に合わせて

それぞれすべて出力するようにしました。受け取り館名はひとまず表示名ではなくnameの出力としています。
https://enju.next-l.jp/reserves.txt?locale=ja

**Comment by masao** [comment]
user_numberが出力されていないようです。
![image](https://user-images.githubusercontent.com/38825/57978137-e5e58d00-7a41-11e9-8d34-7eaba9962895.png)

**Comment by nabeta** [comment]
> user_numberが出力されていないようです。

これは修正済みです。

**Comment by masao** [comment]
出力されることを確認しました。クローズします。

**Comment by yegusa** [comment]
今気づいたんだけど、TSV出力が変わっていますね。

- state が以前は、 「受付済み」「取置済み」だったのが「requested」「retained」になっている。
- stateの出現位置が、最後（9番目）だったのが2番目に出力されるように

**Comment by yegusa** [comment]
あと、 .text になるようになってますね。こちらは直したほうがいいとおもうので、issueに登録しておきました。 → #1601
