### ISSUE TITLE
予約の受け取り館を予約者の図書館を標準にしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1015]
a) 一般ユーザーがログインして予約した場合は、ログインユーザーの図書館を標準で出すようにする
![image](https://cloud.githubusercontent.com/assets/1328499/11815580/aa9585b6-a38f-11e5-924b-1330e18153f7.png)

b) Librarian　権限以上のログインユーザーが他者の利用者の予約の場合はどうするか?
![image](https://cloud.githubusercontent.com/assets/1328499/11815671/2429868e-a390-11e5-9041-9d3d577fc1dd.png)

利用者番号をいれたら、受け取り館を決めるというようにするといいだろうか。

a) だけでもしておいたほうがいいとおもう。
まずはディスカッションしたい。

**Comment by masao** [comment]
デフォルトが利用者側の設定となっていることを確認しました。クローズします。
