### ISSUE TITLE
仮想マシンWebサーバーの設定方法（書誌のTSVインポートで大きなファイルの場合エラーがでてできない）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1021]
大きなファイルをTSVインポートすると次のようなエラーがでてできません。
Enjuのバグというよりは、仮想マシンのWebサーバーの設定じゃないかなとおもいます。
設定方法を教えてもらえるとうれしいです。

<pre>
413 Request Entity Too Large
nginx/1.4.6 (Ubuntu)
</pre>

### 試したファイル：

$ du -sk misc.txt
2868    misc.txt

$ wc -l misc.txt
15227 misc.txt

### 大きめなファイルを指定してインポート
![image](https://cloud.githubusercontent.com/assets/1328499/11859443/47a63fd4-a4ae-11e5-8b23-b1d38687f8fa.png)

### エラーがでてできない
![image](https://cloud.githubusercontent.com/assets/1328499/11859452/63a387a0-a4ae-11e5-82d4-23d5373de647.png)

仮想マシンを1.1.2beta にあげたものでためしました

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_subject (0.1.0)

**Comment by masao** [comment]
http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size かな。

/etc/nginx/nginx.conf の中の
```
http {
...
}
```
の中に、
```
client_max_body_size 20M
```
みたいにサイズ上限を大き目の数字で指定してみたらいかがでしょうか。

**Comment by masao** [comment]
nginx のデフォルトの指定値は 1MB みたいなので、簡単にオーバーしてしまいそうです。

**Comment by yegusa** [comment]
セミコロンがいりました。

```
client_max_body_size 20M;
```

あと、nginxを再起動すればできるようになりました!

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo /etc/init.d/nginx restart
　　* Restarting nginx nginx                                                [ OK ]
```

ありがとうございます。

**Comment by yegusa** [comment]
あとで #891 のマニュアルに書いておきますね。

**Comment by yegusa** [comment]
マニュアルに書いておきました。
