### ISSUE TITLE
バグ?TSVインポートをするとSQLite3::BusyException: database is lockedといったエラーで失敗になる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1023]
すっぴんの1.1.0でおきました。

![image](https://cloud.githubusercontent.com/assets/1328499/11862273/5ef1aa48-a4cc-11e5-8aef-5c54f102a3f6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.0)
- enju_event (0.1.17)
- enju_flower (0.1.0)
- enju_leaf (1.1.0)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_subject (0.1.0)

**Comment by scivola** [comment]
データベース接続のタイムアウトでしょうか。
既定では 5000 ms（ミリ秒）になっています。

enju/config/databse.yml（抜粋）

```yaml
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
```

とりあえずこれを増やして Enju を再起動するとどうなりますか。

SQLite3 は書き込むときにデータベース全体がロックされてしまうので，その間ほかの書き込みが一切できません。インポートに時間がかかるようだと，それはそれで対策をとらないといけなさそうな。

**Comment by yegusa** [comment]
なるほど。そうですか。ちょっとやってみます。

**Comment by nabeta** [comment]
@yegusa ひとまずenju_leaf-1.2.0.beta.3で試していただけますか。

**Comment by yegusa** [comment]
とりあえず、1.1系はいいとして、1.2.0.beta.3で起きるかどうか確かめてみます。

**Comment by nabeta** [comment]
@yegusa 1.3でも起きますか、と聞こうとしたのですが、配布中の仮想マシンがPostgreSQLになったので、検証が難しくなっていますね。今後はPostgreSQL推奨ということもあり、wontfixにしてよいでしょうか。

**Comment by yegusa** [comment]
すっぴんの1.1.0で使うこともないですし，wontfixでクローズで良いです。クローズしておきます。同様のことが出てきたら，新規issueを立てることにします。
