### ISSUE TITLE
「条件を詳しく指定して検索」の画面の修正方法をおしえてください

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1024]
いらない検索項目を削除したいというニーズがあります。

![image](https://cloud.githubusercontent.com/assets/1328499/11863530/e9a6c5f0-a4d7-11e5-89e2-5a96f3c18d9c.png)

enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.1
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0

**Comment by masao** [comment]
https://github.com/next-l/enju_leaf/issues/987#issuecomment-164114508 とほぼ同様です。

1.1系では https://github.com/next-l/enju_leaf/blob/1.1/app/views/page/advanced_search.html.erb のファイルを enju/app/views ディレクトリーにコピーしてきて、適宜編集してカスタマイズします。

**Comment by yegusa** [comment]
ありがとうございます!
思ったよりも、難しく、試せてませんが、まずはクローズします。

**Comment by yegusa** [comment]
後で、マニュアルに書いておきますね。( #891 )

**Comment by scivola** [comment]
ビューファイル（advanced_search.html.erb のようなファイル）をカスタマイズするために必要な知識をどこかに簡単にメモしておきましょうか？
どこに書けばいいでしょう？
マニュアルに入れるかどうかは別にして。（入れるとしてもその前段階のメモとして）

**Comment by yegusa** [comment]
ありがたいです!

まずは、ここに書いてもらうといいと思います。

**Comment by yegusa** [comment]
まずはどのファイルを直せばいいか等の所だけは、1.1 系のマニュアルに書いておきました。

**Comment by scivola** [comment]
# Enju のビューテンプレートを知る第一歩

対象読者：Rails アプリの開発者ではないが，Enju のビューテンプレートファイルを変更するにやぶさかでなく，HTML の基本的な知識があり，「ローカル変数」とか「メソッド」「引数」「制御構造」と聞いてもビビらない人。

目標：Enju のビューテンプレートファイルを見てなんとなく意味が分かり，簡単な修正ならできるようになる。

いいわけ：多少間違ってるかもしれません。とくに用語は正確でないものが混じっているかもしれません。

## はじめに

ビューテンプレートは HTML（の断片）を生成するためのテンプレートです。
Enju ではテンプレートとして，eRuby 形式と Slim 形式の少なくとも 2 種類が使われています。
テンプレートの形式は拡張子で判別します。eRuby 形式は「.erb」が，Slim 形式は「.slim」がファイル名の末尾に付きます。

## eRuby 形式

eRuby（イールビー；embedded Ruby より）は HTML の中に Ruby のコードを埋め込んだものです。

埋め込み方は大まかにいって `<% %>` 形式と `<%= %>` 形式の 2 種類があります。（それぞれバリエーションがあります。）

イコールの付いた `<%= %>` の形式は，埋め込まれた Ruby の式を評価して，その結果を文字列化したものをその場所に埋め込みます。たとえば

```erb
今年は<%= Date.today.year %>年です
```

は，実行した年に応じて「今年は2016年です」のような文字列になります。
（`Date.today` は今日の日付を返します。`year` は日付から年を取り出します）

ちゃんと理解するには，Ruby の式について知らねばなりません。

イコールの無い `<% %>` の形式は，条件判断や繰り返しなどの構文に使います。
例えば

```erb
<% if Date.today.year == 2015 %>
今年は Enju Leaf 1.1 が出た年だ。
<% else %>
今年は Enju Leaf 1.1 が出た年じゃない。
<% end %>
```
は Ruby のプログラムで書けばおおむね

```rb
if Date.today.year == 2015
  "今年は Enju Leaf 1.1 が出た年だ。"
else
  "今年は Enju Leaf 1.1 が出た年じゃない。"
end
```

のようになります。

ちゃんと理解するには，Ruby の構文を知らねばなりません。

eRuby を処理するためのライブラリーには，Ruby 標準添付の [erb](http://docs.ruby-lang.org/ja/2.2.0/library/erb.html) のほか，外部ライブラリーとして [erubis](http://www.kuwata-lab.com/erubis/)（エルビス）があります。現在の Rails では erubis が使われています。（eRuby の書き方や動作に若干の相違があります）

### 埋め込み形式をもう少し詳しく

イコール付きのバリエーションとして，`<%== %>` のようにイコールが二つ連なったものもあります。

違いは，`<%= %>` が評価結果を HTML エスケープして埋め込むのに対し，`<%== %>` はエスケープしないことです。（覚え方：イコールが二つもあると〈そのまんま〉感が強い）

例えば，`<%= "Q&A" %>` は `Q&amp;A` にしてくれます。

一方，`<%== "<em>Yeah!</em>" %>` はタグがそのまま生きて `<em>Yeah!</em>` になります。

※ややこしいことに，Rails には〈エスケープされない文字列〉という概念もあり，それを `<%= %>` に入れてもエスケープされません。（詳細は割愛）

さて，イコールの付かないほうのバリエーションとしては，`<%- %>` とか `<% -%>` とか `<%- -%>` のようにマイナス記号の付いたものがあります。

これは，もともとは（ハイフンがついた側の）余計な空白・改行を抑制してくれるものでした。
しかし現在の Rails ではハイフンを付けなくても抑制してくれるはずです。
（このあたり，やや自信無し。Rails の設定にも依るはずです。現在の仕様を調べようとしましたが，確かなことはすぐには分かりませんでした）

## Slim 形式

[Slim](http://slim-lang.com/) は eRuby と違い，HTML の要素の階層構造（入れ子構造）をインデントで表します。できあがった HTML と元になった Slim 形式の見た目はまったく違います。
たとえば Slim の

```slim
header
  h1.pagetitle 件名一覧
```

は

```html
<header><h1 class="pagetitle">件名一覧</h1></header>
```

となります。

この例で分かるように，クラスをピリオドで表すことができます（CSS セレクターの記法と同じ）。
同様に

```slim
p#alert えらいこっちゃ
```

は

```html
<p id="alert">えらいこっちゃ</p>
```

のようになります。これも CSS セレクターの書き方と同じです。

Slim は初期の学習コストが高いのですが，記述量が少なくてすみ，メンテナンスしやすいテンプレートです。

式の評価値の埋め込みは `=` で，制御構造などは `-` で表します。
たとえば，

```slim
- (1..3).each do |n|
  div = n
```

は

```html
<div>1</div><div>2</div><div>3</div>
```

になります。

## ヘルパーメソッド

テンプレート中に埋め込んで HTML の一部を生成する Ruby のメソッドをヘルパーメソッドと呼びます。ビューの生成を助けるメソッドだからです。

たとえば eRuby テンプレート中に

```erb
<%= text_field_tag 'isbn' %>
```

とあれば，その部分に

```html
<input type="text" name="isbn" id="isbn" />
```

という input タグが埋め込まれます。

この `text_field_tag` がヘルパーメソッドです。

```rb
text_field_tag 'isbn'
```
は，'isbn' という文字列を引数（ひきすう）として `text_field_tag` というメソッドを呼び出しています。

Ruby ではメソッドの呼び出しも式の一種です。メソッドが返す値が式の評価値になります。

名前が '_tag' で終わるヘルパーメソッドはすべてタグを生成するものです。

## 多言語化のためのヘルパーメソッド

`t` は多言語化のためのヘルパーメソッドです。t はたぶん translate に由来するのでしょう。

たとえば，

```rb
t('page.title')
```

は `'page.title'` という文字列を引数にして `t` というメソッドを呼び出しています（この括弧は省略できます）。

このメソッドは，ロケールに応じて日本語や英語などの文言を返します。どの訳文を呼び出すかを引数で指定します。

訳文は config/locales/translalation_ja.yml などの YAML 形式のファイルに書かれています。

詳細は略しますが，訳文は階層的なキーの下に書かれています。たとえば，`page` というキーの下に `title` というキーがあり，その下に一つの訳文が書かれています。それを呼び出すのがさきほどの `t('page.title')` です。

## Ruby のメソッド呼出しの形式

Ruby のメソッド呼出しの書き方は非常に柔軟性に富み，多様なので，詳述するとたいへんな分量になります。
ここでは基本的なことだけを記述します。

次の例を見ましょう。

```rb
"Ruby".downcase
```

これは `"Ruby"` という文字列に対し，`downcase` という小文字化メソッドを呼び出しているところです。引数はありません。
結果として `"ruby"` という文字列が返ります。

この例で，メソッドの対象となる `"Ruby"` という文字列をこのメソッド呼出しの「レシーバー」と呼びます。

Ruby のメソッド呼出しは，基本的にレシーバーのあとにピリオド，そしてメソッド名を続け，必要ならそのあとに引数を書く，という形式です。

### レシーバーの省略

しかし，レシーバー（とピリオド）を略してよい場合があります。例えば


```rb
t('page.title')
```

の例では，メソッド `t` のレシーバーは書かれていません。この場合，〈その文脈における暗黙のレシーバー〉に対するメソッド呼出しとなります。

メソッド `t` の場合，ビューのテンプレートの中ではレシーバーを略すことができます。（そもそも `t` はレシーバーが何であるか知る必要の無いメソッドです）

### メソッド呼出しの連鎖

`Date.today` は `Date` という日付のお世話をするものに対し，`today` というメソッドを呼び出しています。その返り値は今日の日付です。日付を表すデータに対して `year` というメソッドを呼び出すと，その日付の年を表す整数が返ります。

`Date.today.year` は，まず `Date` の `today` を呼出し，その返り値である日付の `year` を呼び出しています。このように，いくらでもメソッド呼出しをつなげることができます。

### メソッドの引数

メソッドに与える引数は，`t` の例で見たように，`( )` の中に入れます。しかし，この括弧は省略できます。
括弧が省略できないのは，そのあとにメソッドをさらに続ける場合や，省略すると解釈に曖昧さが出てくる場合などです。

### ブロック付きのメソッド呼出し

メソッドには，引数のほか，ブロックというものを与える場合があります。

----

ふうう，ここで力尽きました。ちょっと休憩。メソッドのブロックと eRuby 中でのブロックの扱いはどうしても書かないといけませんが，またのちほど。
