### ISSUE TITLE
検索結果一覧の「；」が変なときにでてきます。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1025]
![image](https://cloud.githubusercontent.com/assets/1328499/11863556/2acef3fe-a4d8-11e5-8871-2976457014f0.png)

タイトルと分類だけいれたときには少なくとも。

enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.1
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0

**Comment by nabeta** [comment]
これは著者・出版社と分類の区切りになる文字です。現状では分類が1件以上登録されていると、著者・出版社の登録がなくても区切り文字が出てきますが、そもそも区切り文字自体なくてもいいんじゃないかと思います。

**Comment by yegusa** [comment]
そうね。区切り文字自体がなくてもいいかと思います。

**Comment by nabeta** [comment]
分類の前の";"を削除しました。開発サーバに反映済みです。
http://dev.next-l.jp/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2

**Comment by yegusa** [comment]
どのレコードみても ; がなくても不自然じゃないし、これでよいとおもいます。
確認しましたのでクローズします。マニュアルは後で書きます。

![image](https://cloud.githubusercontent.com/assets/1328499/11994481/90039054-aa82-11e5-9ca7-13b56df68833.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
