### ISSUE TITLE
要望：書誌のTSVエクスポートで分類を出力するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1026]
まずは、インポートとおなじ方式でよいのでできるようにしてほしい。

**Comment by yegusa** [comment]
個人的にはこれが一番やってほしい。

**Comment by nabeta** [comment]
分類情報をJSONでエクスポートするようにしました。
http://dev.next-l.jp/resource_export_files/72

**Comment by yegusa** [comment]
インポートとエクスポートで違うのつらい。。。

**Comment by yegusa** [comment]
> インポート形式にあわせるべく、ひとまずYAMLで出力できるようにします。
https://github.com/next-l/enju_leaf/issues/844#issuecomment-147692039

って言ってたし、インポート形式に合わせて、YAMLにしてほしいです。

**Comment by nabeta** [comment]
あれ、ぼくが見たインポート用ファイルはJSONで書いてあって、「YAMLって書いてあるのにJSONで書いてあるじゃん、あとで指摘しなきゃ」と思いながらコミットしたのですが…。ともかくYAMLに直します。

**Comment by yegusa** [comment]
ほう、これ、jsonだったんだ
じゃあ、マニュアルなおすから、開発しないで!

**Comment by yegusa** [comment]
重要なのは、インポート形式とエクスポート形式があっていること!なのです。　YAML でも　JSON でもいいです。そろってれば。ひとまずは。

**Comment by yegusa** [comment]
マニュアルではやっぱYAMLであってました。マニュアルのとおりでインポートできるのは確認しています。
https://next-l.github.io/manual/enju_operation_4.html#tsv_classification

というわけですので、エクスポートもそろえて、YAML形式がいいのじゃないかな。

**Comment by nabeta** [comment]
単にto_yamlを呼ぶだけでいいかなと思ったのですが、そうではないようです。

```ruby
> c = YAML.load("{ndc: '007', ddc: ['003', '004']}")
=> {"ndc"=>"007", "ddc"=>["003", "004"]}
> c.to_yaml
=> "---\nndc: '007'\nddc:\n- '003'\n- '004'\n"
```

**Comment by nabeta** [comment]
手間がかかりそうなので、とりあえず to_json を呼ぶようにしました。

**Comment by nabeta** [comment]
#1096 で"//"で区切る形式に変更しました。

**Comment by yegusa** [comment]
できるようになったことを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12078393/804d7f70-b253-11e5-88c1-02034e579c44.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e40e80e)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
