### ISSUE TITLE
要望：書誌のTSVエクスポートで責任表示を出力するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1027]
- [x] 確認
- [ ] マニュアル #1066

**Comment by nabeta** [comment]
statement_of_responsibilityを出力するようにしました。
https://dev.next-l.jp/resource_export_files/76

**Comment by yegusa** [comment]
できることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12003816/7166c670-ab72-11e5-8f4e-2d6d8bb6cac9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12003819/8d7b3b8e-ab72-11e5-8fb6-5d87d63b5d39.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
