### ISSUE TITLE
要望：書誌のTSVエクスポートで注記を出力するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1029]
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
出力するようにしました。開発サーバに反映済みです。

**Comment by yegusa** [comment]
開発サーバーで失敗します。

http://dev.next-l.jp/resource_export_files

**Comment by yegusa** [comment]
私の仮想マシンの環境では処理待ちからかわりません

![image](https://cloud.githubusercontent.com/assets/1328499/11989709/f2c4dd20-aa45-11e5-8bd7-85d28d56df67.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list |grep nju
  * enju_biblio (0.2.0.beta.1 66feec1)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 968b3e2)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
もう一度bundle updateして試していただけますか。

**Comment by yegusa** [comment]
かわりません。別のissueをたてます。

**Comment by yegusa** [comment]
できることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12003719/d47f1cb6-ab6e-11e5-8473-07bdac7af3fc.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12003714/b96b8b26-ab6e-11e5-8033-fadda1387e61.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
