### ISSUE TITLE
取り置き済みの所蔵がある書誌に対して、新規の所蔵を作ろうとするとWe're sorryになる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1030]
- [ ] 確認
- [ ] マニュアル修正 #1191 

デモサーバーで起きました。手元の1.1.2beta でもおきました。

取り置き済みの書誌に対して、新規の所蔵を作ろうとする
![image](https://cloud.githubusercontent.com/assets/1328499/11914046/cd1215ce-a6b8-11e5-8fb9-6119fff0e5b4.png)

所蔵情報を入れて、登録しようとする
![image](https://cloud.githubusercontent.com/assets/1328499/11914051/074f015c-a6b9-11e5-9974-5eab5a84f475.png)

We're sorry になる
![image](https://cloud.githubusercontent.com/assets/1328499/11914057/28fba846-a6b9-11e5-9824-9da499d49fe5.png)

が、所蔵はできているよう
![image](https://cloud.githubusercontent.com/assets/1328499/11914082/7305b288-a6b9-11e5-8ca1-1cf7aef4b2cc.png)

enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.1
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0

**Comment by masao** [comment]
取り置き済み状態のものは予約待ち状態として認識されないように変更修正しました。ご確認ください。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しましたのでクローズします。

取り置き済み資料に新規所蔵情報を追加しようとする
![image](https://cloud.githubusercontent.com/assets/1328499/18813020/0ac9d44a-8324-11e6-87a0-b8332bd83fa1.png)

新規所蔵情報を入力
![image](https://cloud.githubusercontent.com/assets/1328499/18813028/5098e88a-8324-11e6-9326-4b506d07a34e.png)

所蔵情報が作成された
![image](https://cloud.githubusercontent.com/assets/1328499/18813032/6ee9fa86-8324-11e6-8a8d-62af1a497122.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
