### ISSUE TITLE
仮想マシンのnginx設定：client_max_body_size上限をあげたい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1034]
- [x] markdownのマニュアルには修正必要ないことを確認 #1191

#1021 などで出ているように、ちょっとまとまった量の移行データ処理しようとするとエラーになるので、配布版の仮想マシンでは、この上限値をあげた設定にしておくとよいように思います。

**Comment by nabeta** [comment]
画像のアップロードなどと共通の設定になりますので、10MBくらいにしますかね。

**Comment by yegusa** [comment]
まあ、10MBでいいと思いますよ。

**Comment by nabeta** [comment]
1.2系の仮想マシン作成用スクリプトで、client_max_body_size を10MBに設定しました。
https://gist.github.com/nabeta/f521066870964d85c3d81bfdd49a8848#file-enju_leaf_script_ubuntu-xenial-sh-L73

**Comment by masao** [comment]
確認したいので、仮想マシンを作成してみていただけますか。beta4リリース時でも構いませんが。

**Comment by nabeta** [comment]
以下にあります。
http://www.next-l.jp/download/vm/enju_leaf_1.2.0.beta.3.virtualbox_64bit.zip

**Comment by masao** [comment]
上記の仮想マシンが起動できませんでした。以下のエラーになります：
```
RawFile#0 failed to create the raw output file /Users/kosuke/enju_leaf_vm/ubuntu-xenial-16.04-cloudimg-console.log (VERR_PATH_NOT_FOUND).
```

![image](https://cloud.githubusercontent.com/assets/38825/18039986/2b01836c-6de3-11e6-87f7-545fcb74eafc.png)

**Comment by nabeta** [comment]
Ubuntu 14.04で仮想マシンを作り直しました。手元のWindows10の環境で起動することを確認しています。
URLは同じです。
http://www.next-l.jp/download/vm/enju_leaf_1.2.0.beta.3.virtualbox_64bit.zip

**Comment by masao** [comment]
上記の仮想マシンで 9.2MB のテキストファイルをアップロードできることを確認しました。クローズします。
