### ISSUE TITLE
ユーザインポートで利用者番号に不正な文字を含む場合にアカウント情報だけが作られてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1036]
ユーザ情報のインポート時に、以下のように、不正な文字列を含む利用者番号があると、Userだけが作られ、Profileが作られない状態になってしまい、処置できない状態になる。

```
user_number	username	email
001あ	test008	test@example.jp
```

ユーザインポート自体もエラーだった旨が表示される：

![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11916639/c8de3108-a722-11e5-9d20-bf59d28bc13e.png)

しかしながら、実はユーザアカウントは作られてしまっている：

```
$ rails c
irb(main):001:0> User.last
  User Load (0.7ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
=> #<User id: 23, email: "test@example.jp", encrypted_password: "...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2015-12-18 12:50:38", updated_at: "2015-12-18 12:50:38", username: "test008", deleted_at: nil, expired_at: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, confirmed_at: nil, save_checkout_history: false, checkout_icalendar_token: nil>
irb(main):002:0> User.last.profile
  User Load (1.8ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  Profile Load (0.3ms)  SELECT  "profiles".* FROM "profiles" WHERE "profiles"."user_id" = ? LIMIT 1  [["user_id", 23]]
=> nil
```

ユーザアカウントが保存されているにもかかわらず、プロフィール情報が作られていない不完全な状態であるため、ユーザ一覧にも表示されず、現在のUI上から削除することもできない。

※参考・コンソール上からユーザアカウントを削除しておく方法：
```
irb(main):009:0> User.last.delete
  User Load (1.4ms)  SELECT  "users".* FROM "users"  ORDER BY "users"."id" DESC LIMIT 1
  SQL (9.3ms)  DELETE FROM "users" WHERE "users"."id" = ?  [["id", 23]]
=> #<User id: 23, email: "test@example.jp", encrypted_password: "...", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2015-12-18 12:50:38", updated_at: "2015-12-18 12:50:38", username: "test008", deleted_at: nil, expired_at: nil, failed_attempts: 0, unlock_token: nil, locked_at: nil, confirmed_at: nil, save_checkout_history: false, checkout_icalendar_token: nil>
```

**Comment by nabeta** [comment]
利用者情報(Profile)が正しくない（利用者番号に不正な文字が入っている、重複しているなど）場合、ログインアカウント情報(User)を作成しないようにしました。開発サーバに反映済みです。

**Comment by nabeta** [comment]
これは1.1系にも含めたほうがよいのでは？ @yegusa

**Comment by masao** [comment]
確認してみました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11916919/972c58c4-a731-11e5-840d-f252a14942ec.png)
ユーザアカウントの問題はなくなっているようですが、エラーメッセージが出ないですね。

**Comment by yegusa** [comment]
いいと思います。issueを別にたてておきます。　#1039

**Comment by nabeta** [comment]
エラーメッセージの表示を修正しました。開発サーバに反映済みです。

**Comment by nabeta** [comment]
1.1系にも反映済みです。

**Comment by nabeta** [comment]
エラーメッセージの表示をさらに修正し、途中でエラーがあった行を表示するとともに、もしエラーがあったら状態を「失敗」とするようにしました。
http://dev.next-l.jp/user_import_files/40

**Comment by nabeta** [comment]
しかし、このインポート結果の表はもうちょっと工夫のしようがありそうです。1.2以降でよいと思いますが。

**Comment by yegusa** [comment]
1.1系のコミットログは、1,1系のほうのissueにしてほしかったなあ。。。

**Comment by yegusa** [comment]
不正なユーザーができているかどうかは調べる方法が分からないので、
本当のところはチェックできてないですが、まあ、できていると仮定して一旦クローズします。


3行目に不正な利用者番号のある行がある
<pre>
"user_number"	"username"	"email"	"password"
"100226"	"user2206"	"user2206@sample.jp"	"habanera"
"100227あ"	"user2207"	"user2207@sample.jp"	"habanera1"
"100228"	"user2208"	"user2208@sample.jp"	"habanera2"
"100229"	"user2209"	"user2209@sample.jp"	"habanera3"
</pre>

* 状態が：失敗
* 3行目にエラー
* 3行目がユーザーがつくられていない
* 他の行はつくられている

![image](https://cloud.githubusercontent.com/assets/1328499/12004093/7ac25d20-ab80-11e5-85ed-4dca9ff9a2ab.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

注：マニュアルにはTSVインポート時の動作がかわっている旨注意のこと
