### ISSUE TITLE
「貸出期限切れの資料の一覧」画面で「予約」のフィルタのリンク先がおかしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1037]
「貸出期限切れの資料の一覧」画面、右の予約「あり（２）」をクリック
http://localhost:8080/checkouts?view=overdue
![image](https://cloud.githubusercontent.com/assets/1328499/11916809/e984fdca-a72b-11e5-9bbc-56eda495516e.png)

×　9件が表示される（返却済みなども表示される）　→　○　貸出期限がすぎている2件が表示される
http://localhost:8080/checkouts?days_overdue=1&reserved=true
![image](https://cloud.githubusercontent.com/assets/1328499/11916813/0a2930c8-a72c-11e5-8a4a-cfc73c639b88.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
1.1 系のマニュアルには、うまく機能しない旨かいておきました。

**Comment by masao** [comment]
1.2系の最新では直っているようですので、クローズします。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/14062684/a8b6440e-f3eb-11e5-8670-094c2a6f472a.png)
