### ISSUE TITLE
ユーザインポートで利用者番号に不正な文字を含む場合にアカウント情報だけが作られてしまう （1.1系）

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1038]
#1036 と同じです。

- [ ] マニュアル

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
1.1系に反映済みです。

**Comment by yegusa** [comment]
利用者番号が不正な場合は、userが作成されていないことは確認しました。
ただ、ワーニングも、エラーもでてないのは困ります。→ほかのissueに挙げておきますが、
とりあえず、これはクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/11917337/733b25a2-a746-11e5-9510-669bebfacfed.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 cd28c42)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアルにはあとで反映させておきます。

**Comment by yegusa** [comment]
ごめん、リオープンする。1.1 では、エラーメッセージでません。

**Comment by yegusa** [comment]
不正なみえないユーザーができなくなるようにするバグフィックスと一緒に、いままでは失敗だったのに、失敗じゃなくて、完了で、その行をとばすような、仕様変更が起きると、マニュアルを変えなくちゃいけないので、それは困るなあ。
まあとにかく、

* a) エラーメッセージが出るようにするか
* b) 今までのように失敗になるようにするか

になっていないと困るなあと思います。

**Comment by nabeta** [comment]
1.1系に取り込みました。上記のaとbの両方を実装しています。

**Comment by yegusa** [comment]
ところでまた、仕様が変わってますね。。。まいいや、とりあえず、現在実装されている方法でマニュアルには書いておきます。

**Comment by yegusa** [comment]
エラーメッセージでません
失敗にもなりません

![image](https://cloud.githubusercontent.com/assets/1328499/11931961/21e05ec6-a835-11e5-9262-65ac3092e25d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f929848)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 3e6ec8e)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
あ、リスタートするの忘れてたかも。少々お待ちください。

**Comment by yegusa** [comment]
できていることを確認しました。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/11932366/5229aca6-a838-11e5-98fd-4ecf49556688.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 5ae5b61)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f929848)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 3e6ec8e)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアルに追記しておきました。
