### ISSUE TITLE
「貸出期限切れの資料の一覧」のTSVのヘッダを出力してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1040]
http://localhost:8080/checkouts.txt?locale=ja&view=overdue
<pre>
Overdue items (created_at: 2015-12-20 06:31:02 +0000)
"enjuadmin"    "909092"    "Ruby on Rails環境構築ガイド : ソース管理から公開までを徹底解説 : 定番ツールを使いこなして今日から即戦力!"    "2015-12-06 17:34:13 +0900"    "2015-12-16 23:59:59 +0900"
"user01"    "300003"    "はじめてのRuby on Rails2 : 最新の「Webアプリケーション・フレームワーク」が使える!"    "2015-12-05 12:52:28 +0900"    "2015-12-15 23:59:59 +0900"
"user02"    "300002"    "レッスン"    "2015-12-05 12:37:52 +0900"    "2015-12-15 23:59:59 +0900"
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
#1043 で追加済みです。

**Comment by masao** [comment]
ヘッダが追加されていることを確認しました。クローズします。
![image](https://cloud.githubusercontent.com/assets/38825/17829932/65454fe0-66f9-11e6-90aa-63bda78f976c.png)
