### ISSUE TITLE
貸出履歴のTSVにヘッダを出力してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1043]
「貸出期限切れの資料の一覧」のTSVのヘッダを出力してほしい #1040 
と同じかもしれませんが。一応。

http://localhost:8080/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/11917197/f9b60b6c-a73f-11e5-846a-510c5a7908c4.png)

http://localhost:8080/checkouts.txt?locale=ja
![image](https://cloud.githubusercontent.com/assets/1328499/11917199/09e90cf0-a740-11e5-8844-cbfda958fd55.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
ヘッダを追加しました。

**Comment by masao** [comment]
ヘッダが追加されていることを確認しました。
クローズします。
![image](https://cloud.githubusercontent.com/assets/38825/17829795/a0646a0c-66f4-11e6-998b-25fa3530a9f4.png)
