### ISSUE TITLE
要望：{資料|利用者}インポートの結果の右メニューのTSVの1行目と2行目を統合してほしい　1.1.2用

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1044]
#217　とおなじです。

**Comment by nabeta** [comment]
1.1系にも取り込みました。
https://github.com/next-l/enju_leaf/commit/3e6ec8e64560c9e6df9c461b8304200d13317de9
https://github.com/next-l/enju_biblio/commit/5ae5b614aeb9b43f94bd1eaece94e5d29f8e7475

**Comment by yegusa** [comment]
できてません。

http://localhost:8080/user_import_results.txt?locale=ja

</pre>
username
""	user_number	username	email	password
"user05"	100005	user05	user05@sample.jp	habanera
""	user_number	username	email	password
"user06"	100006	user06	user06@sample.jp	habanera
""	100007あ	user07	user07@sample.jp	habanera1
""	user_number	username	email	password
"user806"	800006	user806	user806@sample.jp	habanera
""	800007あ	user807	user807@sample.jp	habanera1
"user808"	800008	user808	user808@sample.jp	habanera2
"user809"	800009	user809	user809@sample.jp	habanera3
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f929848)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 3e6ec8e)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
あ、ごめん、restart するのわすれてた。ちょっとおまちください。

**Comment by yegusa** [comment]
利用者情報について：できていることを確認しました。

<pre>
""	user_number	username	email	password
"user05"	100005	user05	user05@sample.jp	habanera
""	user_number	username	email	password
"user06"	100006	user06	user06@sample.jp	habanera
""	100007あ	user07	user07@sample.jp	habanera1
""	user_number	username	email	password
"user806"	800006	user806	user806@sample.jp	habanera
""	800007あ	user807	user807@sample.jp	habanera1
"user808"	800008	user808	user808@sample.jp	habanera2
"user809"	800009	user809	user809@sample.jp	habanera3
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 5ae5b61)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f929848)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 3e6ec8e)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
書誌・所蔵情報についてできることを確認しました
http://localhost:8080/resource_import_results.txt
<pre>
		isbn	item_identifier	circulation_status	use_restriction	call_number
20	23	9784839902872	554001	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|テ
22	24	9784774142043	554002	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|ヤ
21	25	9784946553196	554003	Available On Shelf	Limited Circulation, Normal Loan Period	375.1|シ
		manifestation_id	item_identifier	circulation_status	use_restriction	call_number
20	26	20	554004	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|テ
22	27	22	554005	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|ヤ
21	28	21	554006	Available On Shelf	Limited Circulation, Normal Loan Period	375.1|シ
		manifestation_id	circulation_status	use_restriction	call_number
20		20	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|テa
</pre>

enju_leaf start/running
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 5ae5b61)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f929848)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 3e6ec8e)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。
（マニュアルには書いていないので、マニュアルの改訂は必要なし）

**Comment by yegusa** [comment]
できていることを確認したつもりになったのですが、これ、よくみたら変ですね。
複数のタスク分がでています。

ヘッダが「""  user_number username    email   password」　3回出てるでしょ?

そもそも、画面も、複数タスクが全部でてるしね。

<pre>
""  user_number username    email   password
"user05"    100005  user05  user05@sample.jp    habanera
""  user_number username    email   password
"user06"    100006  user06  user06@sample.jp    habanera
""  100007あ   user07  user07@sample.jp    habanera1
""  user_number username    email   password
"user806"   800006  user806 user806@sample.jp   habanera
""  800007あ   user807 user807@sample.jp   habanera1
"user808"   800008  user808 user808@sample.jp   habanera2
"user809"   800009  user809 user809@sample.jp   habanera3
</pre>

画面遷移もかわっちゃってるきがするし。

でもまあ、もう、いいや。とりあえず、1.1系はこれで。

一回リオープンしたけど、またクローズします。
