### ISSUE TITLE
所蔵の新規作成の右メニューの「戻る」のリンク先が戻るではない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1045]
- [x] 確認
- [ ] マニュアル #1066
 
新規作成　リンクをクリック

http://localhost:8080/manifestations/17
![image](https://cloud.githubusercontent.com/assets/1328499/11917702/9659d0ba-a755-11e5-8f2c-a0dc98676a40.png)

戻る　をクリック
http://localhost:8080/items/new?manifestation_id=17
![image](https://cloud.githubusercontent.com/assets/1328499/11917705/b2c24f66-a755-11e5-86bc-48b4e621234e.png)

×　前の画面じゃない画面が表示される　
http://localhost:8080/items?manifestation_id=17
![image](https://cloud.githubusercontent.com/assets/1328499/11917709/d2e224a6-a755-11e5-8652-4c081c96dd0c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 cd28c42)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
修正しました。開発サーバに反映済みです。

なお、この部分に限らず、「戻る」リンクは一覧に戻る場合と前のページに戻る場合（「戻る」ボタンと同様）が混在していましたが、いったん前のページに戻る動作に統一しました。

**Comment by yegusa** [comment]
え、これ以外も変えたのね。。。

**Comment by yegusa** [comment]
[戻る]リンクがブラウザの戻るボタンと同様な動作であることを確認しました。
クローズします。

### 検索結果一覧から「所蔵情報の新規作成」
![image](https://cloud.githubusercontent.com/assets/1328499/12003958/14a91d82-ab79-11e5-8eff-6edcff3d2231.png)

「戻る」
![image](https://cloud.githubusercontent.com/assets/1328499/12003961/2f85c9de-ab79-11e5-9f54-1682d7b5b511.png)

検索結果一覧　に戻る
![image](https://cloud.githubusercontent.com/assets/1328499/12003963/43f699de-ab79-11e5-89ad-421e0bd7cbbb.png)

### 資料の詳細の(新規作成)
![image](https://cloud.githubusercontent.com/assets/1328499/12003969/79d3e624-ab79-11e5-89f7-b644cc3aaf40.png)

「戻る」
![image](https://cloud.githubusercontent.com/assets/1328499/12003970/90a0013a-ab79-11e5-995f-001f5f3749f0.png)

資料の詳細に戻る
![image](https://cloud.githubusercontent.com/assets/1328499/12003975/a81f84ca-ab79-11e5-81f8-7f6580d09d7e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
