### ISSUE TITLE
ある所蔵の表示のメニューの[貸出規則の一覧]をクリックした先が変

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1046]
ある所蔵の表示の右メニューの[貸出規則の一覧]をクリックする
http://localhost:8080/items/21
![image](https://cloud.githubusercontent.com/assets/1328499/11917746/2cdf8d02-a758-11e5-9105-8c64ee2cc33e.png)

×　全貸出規則の一覧がでる
http://localhost:8080/lending_policies?item_id=21
![image](https://cloud.githubusercontent.com/assets/1328499/11917754/5556b99a-a758-11e5-9d11-1741e7efd208.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 cd28c42)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
所蔵に関連づけられた貸出規則のみを表示するように修正しました。
http://dev.next-l.jp/lending_policies?item_id=17410

**Comment by yegusa** [comment]
できているようですのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12004076/5e872754-ab7f-11e5-8a84-0a9a5dfe0396.png)

○　この所蔵に関係するだけの貸出規則が表示されている
![image](https://cloud.githubusercontent.com/assets/1328499/12004079/75c22752-ab7f-11e5-9df9-d7d6978f72ce.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
