### ISSUE TITLE
[貸出規則の一覧]　?　これ、何ですか?　後、システム設定のどこかにあったほうがよさそう。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1047]
- [ ] マニュアル修正 #1191

マニュアル書いてて気づいたのですが、
[貸出規則の一覧]　って、これ、何ですか?　　（#1046 に関連）

個別の所蔵からしかたどれないのは変なので、
システム設定のどこかからかたどれるとか、
貸出履歴からたどれるとか必要そう。

まずは、
- 何なのか、
- なぜここにしかリンクがないのか、他にリンクあるならその在り処
- なぜここにリンクが必要なのか、

わかるひと教えて下さい。

参考：
ある所蔵の表示の右メニューの[貸出規則の一覧]をクリックする
http://localhost:8080/items/21
![image](https://cloud.githubusercontent.com/assets/1328499/11917746/2cdf8d02-a758-11e5-9105-8c64ee2cc33e.png)

全貸出規則の一覧がでる
http://localhost:8080/lending_policies?item_id=21
![image](https://cloud.githubusercontent.com/assets/1328499/11917754/5556b99a-a758-11e5-9d11-1741e7efd208.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.1 caa363f)
- enju_event (0.1.17 f886ee3)
- enju_flower (0.1.0)
- enju_leaf (1.1.2 cd28c42)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0 78c4280)
- enju_subject (0.1.0)

**Comment by nabeta** [comment]
これは1.4.0で削除予定です。
https://github.com/next-l/enju_leaf/pull/1626

**Comment by nabeta** [comment]
削除済みのため、クローズします。
