### ISSUE TITLE
所蔵の詳細表示の右メニューでUser権限でアクセスできないリンク[貸出規則の一覧]と[貸出履歴]が表示される

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1048]
http://localhost:8080/items/21
![image](https://cloud.githubusercontent.com/assets/1328499/11917798/381b9830-a75a-11e5-9239-c3b2ac1090ca.png)

http://localhost:8080/lending_policies?item_id=21
![image](https://cloud.githubusercontent.com/assets/1328499/11917804/8d36d7b2-a75a-11e5-94d9-c642c5c1cf03.png)

http://localhost:8080/checkouts?item_id=21
![image](https://cloud.githubusercontent.com/assets/1328499/11917809/aa550eae-a75a-11e5-845e-b85bdce4f2df.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 cd28c42)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
貸出規則はLibrarian、貸出履歴はUserでそれぞれ表示されるようにしました。開発サーバに反映済みです。

**Comment by yegusa** [comment]
できることを確認しましたのでクローズします。

### User権限で所蔵を表示したところ 1 返却済みのパターン

○ [貸出規則の一覧]が表示されない、　○[貸出履歴]が表示される　　[貸出履歴]リンクをクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/12005408/3c721d78-abe7-11e5-98e8-66bc11ee3ca2.png)

自分の貸出履歴だけが表示される（返却済みの履歴）
![image](https://cloud.githubusercontent.com/assets/1328499/12005412/91395024-abe7-11e5-8af7-dce7e043ab33.png)

### User権限で所蔵を表示したところ 2 貸出中のパターン

○ [貸出規則の一覧]が表示されない、　○[貸出履歴]が表示される　　[貸出履歴]リンクをクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/12005420/0257a878-abe8-11e5-9b31-69060f21b50d.png)

自分の貸出履歴だけが表示される（貸出中のもの）
![image](https://cloud.githubusercontent.com/assets/1328499/12005423/1ce344f4-abe8-11e5-8af6-6f108119b00d.png)

### Librarian権限以上の場合で所蔵を表示したところ （ある利用者の返却済み、ある利用者が貸出中）

○[貸出履歴]が表示される　　[貸出履歴]リンクをクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/12005455/03a289c2-abe9-11e5-9be5-502fa76b6910.png)

全員分の貸出履歴が表示される（貸出中のもの、返却後のものも）
![image](https://cloud.githubusercontent.com/assets/1328499/12005458/3988fa12-abe9-11e5-89c6-fc23c430a4c4.png)

○ [貸出規則の一覧]が表示される　[貸出規則の一覧]リンクをクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/12005454/eb6ac496-abe8-11e5-87b5-170080f52400.png)

貸出規則の一覧が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/12005457/1942a668-abe9-11e5-9e71-10a45753c472.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0948f53)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
