### ISSUE TITLE
既にある書誌に、所蔵を追加するTSVインポートをする場合に「item_identifier」がない場合は作成されない→請求記号がある場合は作成する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1053]
- [ ] マニュアル修正 #1066 

#1019 (書誌と所蔵を同時に登録する際に、item_ideitifierがないと登録できない)とも関連する。

所蔵情報IDはなく、請求記号だけ追加するということもあるので、
所蔵情報ID（item_identifier）なしのばあいTSVインポートで所蔵が追加できないのは困る。

例：
<pre>
manifestation_identifier	circulation_status	use_restriction	call_number
http://iss.ndl.go.jp/books/R100000002-I000003018903-00	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|テaa
http://iss.ndl.go.jp/books/R100000002-I000010835920-00	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|ヤbb
http://iss.ndl.go.jp/books/R100000002-I000007549561-00	Available On Shelf	Limited Circulation, Normal Loan Period	375.1|シcc
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/11918327/7cd46096-a76f-11e5-88c4-cd6b9e6fbaef.png)

----

参考：　item_identifier があれば、ちゃんと所蔵が追加される　

<pre>
manifestation_identifier	item_identifier	circulation_status	use_restriction	call_number
http://iss.ndl.go.jp/books/R100000002-I000003018903-00	554101	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|テp
http://iss.ndl.go.jp/books/R100000002-I000010835920-00	554102	Available On Shelf	Limited Circulation, Normal Loan Period	547.483|ヤp
http://iss.ndl.go.jp/books/R100000002-I000007549561-00	554103	Available On Shelf	Limited Circulation, Normal Loan Period	375.1|シp
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/11918288/2d397fd6-a76e-11e5-85e0-8a0d68fef79d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 cd28c42)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
shelf列がある場合、item_identifierがなくても所蔵情報を作成するようにしました。shelf列がない場合は今までと同様に作成されません。

**Comment by yegusa** [comment]
所蔵情報の列があれば追加するっていうようにつくるのは大変?
今までのshelf がないとインポート画面で選んだものをつけるってのと
矛盾するのでちょっとなあと。

**Comment by nabeta** [comment]
たしかにそうですね。ただ、所蔵情報の列といってもたくさんあるので、どれかひとつかふたつに絞れないでしょうか。

**Comment by nabeta** [comment]
#1019 では請求記号が問題になっていますので、請求記号があれば所蔵情報が入力されているとみなしてインポートするのでいかがでしょうか。

**Comment by yegusa** [comment]
ん～、じゃあ、

* 所蔵情報ID
* 請求記号
* 本棚
* 受入日

この4つのどれかに値があったら、
所蔵情報があるとみなして、所蔵の新規作成を行うってのはどうでしょうか?

**Comment by yegusa** [comment]
まずは請求記号だけはやるとEnju WSで決めた。
ほかの方式はまた考える。

**Comment by nabeta** [comment]
shelf列がない場合は、インポート時に指定したデフォルトのshelfが入るのでよいのですよね？

**Comment by yegusa** [comment]
> shelf列がない場合は、インポート時に指定したデフォルトのshelfが入るのでよいのですよね？

そうです。

**Comment by masao** [comment]
請求記号列だけが指定されている状態でも所蔵レコードが作られるように修正しました。

**Comment by yegusa** [comment]
現在のステータス：確認してクローズするのみ（私でもできそう）

**Comment by yegusa** [comment]
なんかなぞな注意メッセージでるけど、できることを確認しました。
いったんクローズします。マニュアルはあとで修正します。

（注メッセージがでたのは、もともと1件も所蔵がなかった書誌に所蔵を追加したほう）

```
isbn	call_number	item_note
9784890523849	345.67|12	test1
9784798012032	456.89	test2
```

![image](https://cloud.githubusercontent.com/assets/1328499/14765346/88ae93da-0a18-11e6-8289-9bdc195f9bfe.png)


![image](https://cloud.githubusercontent.com/assets/1328499/14765362/034bd0f8-0a19-11e6-8eb1-f869c7cf2d11.png)

![image](https://cloud.githubusercontent.com/assets/1328499/14765365/278fd4b4-0a19-11e6-9c29-c4acb1d00084.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a366e5d)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 d5e2c12)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

**Comment by yegusa** [comment]
所蔵情報のTSVインポートで、請求記号のみでの新規追加できることが
わかるようにマニュアルを修正。

4-3-4 TSVファイルを読み込んで登録する
https://next-l.github.io/manual/1.2/enju_operation_4.html#section4-3-4
