### ISSUE TITLE
戻るリンクをブラウザの戻るボタンと同様に変更を元に戻してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1054]
#1045 から派生です。

> なお、この部分に限らず、「戻る」リンクは一覧に戻る場合と前のページに戻る場合（「戻る」ボタンと同様）が混在していましたが、いったん前のページに戻る動作に統一しました。
> https://github.com/next-l/enju_leaf/issues/1045#issuecomment-166256589 by @nabeta 

- [x] 確認
- [x] マニュアル　（もとに戻したのでとくに修正箇所なし）

**Comment by yegusa** [comment]
@nabeta チェックするので開発サーバーの該当URLへのリンクをリストしてください。

**Comment by yegusa** [comment]
@nabeta さん、

プログラムの変更履歴をみると
* 33箇所 https://github.com/next-l/enju_biblio/commit/65314d004d67f8820ad6d3f53e3bf14efb0cd3bc
* 34箇所 https://github.com/next-l/enju_biblio/commit/0f6e7568c3a8ebfbbafc927f59d2b32a3316884e

とあまりにも大量に変えているのですね。

影響範囲が大きすぎます。
確認作業も、マニュアル修正も追いつきません。

一度元にもどして欲しいです。
一度に全部変えるのではなく、一つづつissue に挙げてから、変えて欲しいです。

**Comment by nabeta** [comment]
enju_biblioについて、 #1045 以外の変更を元に戻しました。
https://github.com/next-l/enju_biblio/commit/915fb87862a01ffe38d98e16bce5174a03134a42

**Comment by yegusa** [comment]
@nabeta さん、さっそくありがとう。

**Comment by yegusa** [comment]
ソースを見比べた感じだと戻っているようなので一端クローズします。

**Comment by yegusa** [comment]
ごめん、やっぱり、リオープンします。

何か、「戻る」アンカーに変わってしまったものが増えている気がします。

**Comment by yegusa** [comment]
例：
![image](https://cloud.githubusercontent.com/assets/1328499/11994519/4e18be5c-aa83-11e5-992d-bbc778abc325.png)

**Comment by yegusa** [comment]
参考：　1.1.0のときの画面では　「戻る」ではない。

http://localhost:8080/events/1
![image](https://cloud.githubusercontent.com/assets/1328499/11614084/94750520-9c7a-11e5-8dec-ff391a47390c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
ああ、でも event は https://github.com/next-l/enju_biblio/commit/915fb87862a01ffe38d98e16bce5174a03134a42 
の中にはないね。

なんだろう。。。また別件で修正した?

**Comment by yegusa** [comment]
![image](https://cloud.githubusercontent.com/assets/1328499/12000471/961bc496-ab1a-11e5-8018-adc620b161f7.png)

となっていた場合、

app/views/agent_import_files/new.html.erb
→ http://localhost:8080/agent_import_files/new　をチェックすればいいんだよね?

![image](https://cloud.githubusercontent.com/assets/1328499/12000493/1b8bf09c-ab1b-11e5-80e0-4080bab50f6d.png)

**Comment by nabeta** [comment]
そうです。

**Comment by yegusa** [comment]
- [ ]  http://localhost:8080/agent_import_files/new
- [ ]  http://localhost:8080/agent_import_files/1
- [ ]  http://localhost:8080/agent_import_results/1
- [ ]  http://localhost:8080/agent_merge_lists/1
- [ ]  http://localhost:8080/agent_merges/1
- [ ]  http://localhost:8080/agent_relationship_types/1
- [ ]  http://localhost:8080/agent_relationships/1
- [ ]  http://localhost:8080/agent_types/1
- [ ]  http://localhost:8080/agents/1
- [ ]  http://localhost:8080/carrier_types/1
- [ ]  http://localhost:8080/content_types/1
- [ ]  http://localhost:8080/countries/1
- [ ]  http://localhost:8080/create_types/1
- [ ]  http://localhost:8080/donates/1
- [ ]  http://localhost:8080/form_of_works/1
- [ ]  http://localhost:8080/frequencies/1
- [ ]  http://localhost:8080/identifier_types/1
- [ ]  http://localhost:8080/import_requests/1
- [ ]  http://localhost:8080/languages/1
- [ ]  http://localhost:8080/licenses/1
- [ ]  http://localhost:8080/manifestation_relationship_types/1
- [ ]  http://localhost:8080/manifestation_relationships/1
- [ ]  http://localhost:8080/medium_of_performances/1
- [ ]  http://localhost:8080/produce_types/1
- [ ]  http://localhost:8080/realize_types/1
- [ ]  http://localhost:8080/resource_export_files/1
- [ ]  http://localhost:8080/resource_import_files/new
- [ ]  http://localhost:8080/resource_import_files/1
- [ ]  http://localhost:8080/resource_import_results/1
- [ ]  http://localhost:8080/series_statement_merge_lists/1
- [ ]  http://localhost:8080/series_statement_merges/1
- [ ]  http://localhost:8080/series_statements/1

**Comment by yegusa** [comment]
まあ、全部みたわけじゃないけど、↑のチェックはいったのは大丈夫なことを確認しましたので、
一旦クローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 d5b8c05)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 6a07d2f)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
