### ISSUE TITLE
バグ：NDLサーチインポートで雑誌タイトルをインポートした場合に、検索結果にあらわれない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1057]
#884 で判明したバグです。

- [x] 確認
- [x] マニュアル

こちらは、大変こまるので、優先度を高くさせてください。

現在 1件だけ雑誌がある。
（インポート機能を使わずに、手動で登録した場合は、ちゃんと検索結果にあらわれる。）
![image](https://cloud.githubusercontent.com/assets/1328499/11928889/45f029c4-a81a-11e5-81dd-c7069ba36728.png)

「情報処理」をNDLインポートする。　00011609
http://iss.ndl.go.jp/books/R100000002-I000000011527-00
![image](https://cloud.githubusercontent.com/assets/1328499/11928911/68f51100-a81a-11e5-91ec-49c091db993c.png)

正常に作成されました　http://localhost:8080/manifestations?parent_id=29
![image](https://cloud.githubusercontent.com/assets/1328499/11928924/846a5486-a81a-11e5-90ba-9adcd02e368f.png)

雑誌・定期刊行物を選択する
![image](https://cloud.githubusercontent.com/assets/1328499/11928942/ad65e1ca-a81a-11e5-98d9-f9d6d63a2aa1.png)

表示されない。
![image](https://cloud.githubusercontent.com/assets/1328499/11928959/c711ddd6-a81a-11e5-98a3-c461c155fc02.png)

情報処理で検索しても、ヒットしない
http://localhost:8080/manifestations?utf8=%E2%9C%93&query=%E6%83%85%E5%A0%B1%E5%87%A6%E7%90%86&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/11928977/e5b4c7c6-a81a-11e5-8fc3-8bef379c957a.png)

ヒットしないが、ちゃんとあることはある：
http://localhost:8080/manifestations?parent_id=29
![image](https://cloud.githubusercontent.com/assets/1328499/11929011/221a89da-a81b-11e5-9c65-30553f57801c.png)

**Comment by nabeta** [comment]
修正し、開発サーバで動作確認済みです。
http://dev.next-l.jp/manifestations?parent_id=24427&query=

**Comment by yegusa** [comment]
うごくことを、確認しました。

専門図書館をNDLインポート
![image](https://cloud.githubusercontent.com/assets/1328499/11992876/5a730e24-aa6e-11e5-89bd-3cf5473c32d5.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11992880/72ff89ae-aa6e-11e5-828c-645b116630bc.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11992891/874b7ad0-aa6e-11e5-93b9-96995441fc26.png)

雑誌・定期刊行物で表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11992899/97a784dc-aa6e-11e5-9d69-ee3e4602bad1.png)

図書館で検索しても表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11992910/ad56496c-aa6e-11e5-83ec-4c464290f9d3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by yegusa** [comment]
動作確認とマニュアル更新が終了したのでクローズします。
