### ISSUE TITLE
雑誌の「資料が見つかりませんでした」は「資料がまだ登録されていません」に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1058]
- [ ] マニュアル #1066 

#884 から派生した issue です

個別の雑誌の巻が登録されていないときのメッセージが変
![image](https://cloud.githubusercontent.com/assets/1328499/11929110/aa01ff86-a81b-11e5-92d6-1301f9b95874.png)

「資料がまだ登録されていません」

にしてはどうか?　by @nabeta

----
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a42b53d)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 3024559)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)

**Comment by masao** [comment]
雑誌書誌の場合には提案の表示ラベルとなるように修正しました。

**Comment by yegusa** [comment]
確認しましたのでクローズします。

http://localhost:8080/manifestations?parent_id=29&query=
![image](https://cloud.githubusercontent.com/assets/1328499/12871048/9e0f947e-cda8-11e5-9820-7b6ac949fbeb.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 8c1aee2)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 3024559)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)

**Comment by yegusa** [comment]
マニュアルを修正しました。

スクリーンショットの差し替え。
https://next-l.github.io/manual/1.2/enju_operation_5.html#section5-1-1
https://next-l.github.io/manual/1.2/enju_operation_5.html#section5-1-2
