### ISSUE TITLE
検索のフィード　は書き出しの下じゃないですか?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1059]
### 画面案

![image](https://cloud.githubusercontent.com/assets/1328499/11947527/7769e364-a8ab-11e5-8dae-729abb4125f9.png)
### 現在

![image](https://cloud.githubusercontent.com/assets/1328499/11947498/10fb7016-a8ab-11e5-81c4-663ed1c469d2.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1 5ae5b61)
- enju_circulation (0.1.1 caa363f)
- enju_event (0.1.17 430dfb2)
- enju_flower (0.1.0)
- enju_leaf (1.1.2 fc30d7f)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0 78c4280)
- enju_subject (0.1.0)

**Comment by yegusa** [comment]
あー、「検索結果のフィード」は最初の10件だけなので、意味がちがうのか。
他の（RDF/XML, MODS,TSV）はこの画面の結果のレコードね。

どうしたらわかりやすいかな。

ただ、少なくとも、今のは、くっつきすぎてて変なのと、予約のフィルタとまぎらわしいからなんとかしたい。

**Comment by nabeta** [comment]
> くっつきすぎてて変なのと

スペースが詰まってるのを直せばよさそうだと思いました。

**Comment by yegusa** [comment]
↑　じゃあ、直してほしいです。

**Comment by masao** [comment]
検索結果のフィードの場所を 「合計: X」の下の行に置くことにする：
![image](https://user-images.githubusercontent.com/38825/174469000-e918b8f2-2bf8-42f1-8fd3-35c9696387d2.png)
