### ISSUE TITLE
「図書館全体の設定」は「システム全体の設定」にしませんか?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1062]
- [ ] 確認
- [ ] マニュアル #1066

ずっと違和感だったんですよね。
そのほうが直感的だと思うのです。

![image](https://cloud.githubusercontent.com/assets/1328499/11973511/7bd59490-a99e-11e5-822d-ddcb16f08cb9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11973530/c6dfb39e-a99e-11e5-8ec6-884924e651a8.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11973538/d98cb1d6-a99e-11e5-94dc-cf2ef86f0c44.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11973556/ec68f5d0-a99e-11e5-9c70-b45ee4084a64.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 5ae5b61)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 430dfb2)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 fc30d7f)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
「システムの設定」でもいいと思います。

**Comment by yegusa** [comment]
はい、「システムの設定」でもいいと思います。

**Comment by yegusa** [comment]
「Enju システムの設定」でもいいかなあ。

**Comment by nabeta** [comment]
開発サーバは「システムの設定」としました。
http://dev.next-l.jp/page/configuration

**Comment by yegusa** [comment]
皆さん、システムの設定でいい?

**Comment by masao** [comment]
「システムの設定」はナビゲーションメニューにある文字列と同じになるので、やめたほうが良いと思います。どちらの話をしているのかわからなくなりますので。

**Comment by yegusa** [comment]
たしかにそうですね。

じゃあ、「システム全体の設定」でよいかしら?

みなさんどうでしょう?

**Comment by nabeta** [comment]
よいと思います。

**Comment by scivola** [comment]
（「図書館の管理」のサブメニューの）「システムの設定」の下に「システム全体の設定」って，言葉からは何だかよく分からないです。
うっかり「全体じゃないほうは部分（システムの一部の設定）なのか？」などと考えてしまうと，ドツボに。

そもそも「図書館の管理」のサブメニューの「システムの設定」がよく理解できません。
「件名」とか「人物・団体の種類」とか「画像ファイル」とかって，設定なんでしょうか？

もっと遡って，「図書館の管理」のサブメニューに「人物・団体の管理」があるのも理解できません。これって「図書館の管理」でしょうか？

**Comment by yegusa** [comment]
今のメニューがいけてないというのはおっしゃる通りなのですが、
なかなかよい案がみつけられないのでこうなっているという現状です。

少しでもわかりやすくしたいというのが主旨ですので、
代替案を提示してもらえるとありがたいです。

**Comment by nabeta** [comment]
「システム全体の設定」としました。

<img width="190" alt="2015-12-31 21 20 18" src="https://cloud.githubusercontent.com/assets/11428/12064358/62b98d42-b004-11e5-89fa-f07c10fecd39.png">

**Comment by yegusa** [comment]
確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12065837/c90717f0-b021-11e5-9032-7f4d105bb72f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12065844/dbf4b91c-b021-11e5-900d-9bdd8deca843.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12065850/eeed7536-b021-11e5-8518-da14cc175a91.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
