### ISSUE TITLE
「図書館全体の設定の一覧」はいらないのでは?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1063]
- [ ] 確認
- [ ] マニュアル

#### 1. [図書館全体の設定]　をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11973580/38c1a846-a99f-11e5-98bc-4edc57c92758.png)

#### 2. 表示画面が表示、 [編集]をクリック

※ Librarian権限だと表示はできても、編集はできないのでいきなり編集画面に移るのはうまくないため。

![image](https://cloud.githubusercontent.com/assets/1328499/11973678/fa59cab0-a99f-11e5-99a1-8f4f7fd3d7b8.png)

#### 3. 編集画面が表示
![image](https://cloud.githubusercontent.com/assets/1328499/11973699/2f078d6a-a9a0-11e5-9d32-b46196569813.png)

#### 1. [図書館全体の設定]　をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11973580/38c1a846-a99f-11e5-98bc-4edc57c92758.png)

#### 2. 図書館全体の設定の一覧が表示 　[編集]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11973630/9617ade2-a99f-11e5-8005-70bd44f95259.png)

#### 3. 編集画面が表示
![image](https://cloud.githubusercontent.com/assets/1328499/11973642/b94fbee4-a99f-11e5-92a3-516e34733bb6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 5ae5b61)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 430dfb2)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 fc30d7f)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

関連 #1062

**Comment by nabeta** [comment]
開発サーバは上記の動作になるようにしました。
http://dev.next-l.jp/page/configuration

**Comment by yegusa** [comment]
できることを確認しましたのでクローズします。
マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/11981447/033b9870-a9e6-11e5-96f3-91d03916e062.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11981451/107100e8-a9e6-11e5-82b3-e81bb10399d3.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11981457/2097b598-a9e6-11e5-8aad-9423a9538e1b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 13948dc)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 968b3e2)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
