### ISSUE TITLE
逐次刊行物の書誌編集でシリーズマスタのフラグが正しく処理されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1065]
以下のような逐次刊行物の親書誌を作成する。

- 「逐次刊行物」にチェックを入れる
- 「シリーズ情報」の「マスタ」にチェックを入れる

この書誌の表示は逐次刊行物向けの画面となる。

<img width="712" alt="2015-12-24 2 20 02" src="https://cloud.githubusercontent.com/assets/11428/11981364/395cc84e-a9e5-11e5-8868-54029945f19f.png">

ところが、この書誌の「シリーズ情報」を編集（タイトルなど）すると、「逐次刊行物」と「シリーズ情報」の「マスタ」にチェックが入っているにもかかわらず、通常の書誌表示の画面になってしまう。

<img width="712" alt="2015-12-24 2 20 58" src="https://cloud.githubusercontent.com/assets/11428/11981367/3fb889b2-a9e5-11e5-85b5-ff03b38629b0.png">

**Comment by nabeta** [comment]
#1057 に関連する問題で、以下のコミットで修正済みです。
https://github.com/next-l/enju_biblio/commit/75c4c8d915b6245547b068f7378d6d6c4d8dfcd2

1.2系にも反映し、開発サーバで動作を確認しています。

**Comment by yegusa** [comment]
まずは、デモサーバーで現象を確認しました。
たしかになりますね。

手動で資料を登録する
![image](https://cloud.githubusercontent.com/assets/1328499/11993110/eb74aed0-aa70-11e5-93fb-84948a3625bd.png)

雑誌を登録する
![image](https://cloud.githubusercontent.com/assets/1328499/11993124/12fcaa5c-aa71-11e5-92da-741efdc3182d.png)

雑誌として正常に登録された（雑誌の画面になっている）
![image](https://cloud.githubusercontent.com/assets/1328499/11993153/4e65db2c-aa71-11e5-87b0-1de50c8512c3.png)

シリーズ名に「ばばば」を追記（他はいじらない）、更新する
![image](https://cloud.githubusercontent.com/assets/1328499/11993184/83a11450-aa71-11e5-8b02-dd78cf33bc2d.png)

図書（not 雑誌）の表示になってしまっている。
![image](https://cloud.githubusercontent.com/assets/1328499/11993202/a3167ab4-aa71-11e5-980a-509536dca367.png)

enju_biblio: 0.1.1
enju_circulation: 0.1.1
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.2
enju_library: 0.1.0

**Comment by yegusa** [comment]
できることを確認しました。マニュアルは変更する必要がないことも確認ずみです。
クローズします。

雑誌として登録
![image](https://cloud.githubusercontent.com/assets/1328499/11993296/90c5f10e-aa72-11e5-9463-ec6fb1c2741e.png)

雑誌の表示
![image](https://cloud.githubusercontent.com/assets/1328499/11993316/c6013374-aa72-11e5-95dd-73f00496c262.png)

シリーズ名を修正
![image](https://cloud.githubusercontent.com/assets/1328499/11993332/e189ca70-aa72-11e5-8939-e163df8e08b2.png)

○ 雑誌の表示
![image](https://cloud.githubusercontent.com/assets/1328499/11993343/07e558f6-aa73-11e5-9a7a-d4578538e385.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 e0c25e6)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 430dfb2)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 fc30d7f)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)
