### ISSUE TITLE
NDLサーチインポートで雑誌タイトルをインポートした場合に、検索結果にあらわれない （1.1系）

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1067]
#1057 と同じ。

- [x] 確認
- [x] マニュアル

**Comment by nabeta** [comment]
こちらも修正済みです。

**Comment by yegusa** [comment]
動くことを確認しました。

「専門図書館」をJP番号で NDLインポート
![image](https://cloud.githubusercontent.com/assets/1328499/11992674/1a694764-aa6c-11e5-8c2f-123956a82164.png)

正常に作成されました
http://localhost:8080/manifestations?parent_id=31
![image](https://cloud.githubusercontent.com/assets/1328499/11992682/348b0c18-aa6c-11e5-9a98-714b00793b00.png)

雑誌・定期刊行物を選択する
![image](https://cloud.githubusercontent.com/assets/1328499/11992687/56aef87c-aa6c-11e5-8d70-323f2bb242b2.png)

○　表示されている
![image](https://cloud.githubusercontent.com/assets/1328499/11992693/688d63bc-aa6c-11e5-8ad1-29af35224ec1.png)

○　図書館で検索→検索結果に表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11992705/7f9d2a06-aa6c-11e5-882d-d2607175a1fe.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 e0c25e6)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 430dfb2)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 fc30d7f)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
動作確認とマニュアル修正が終了したのでクローズします。
