### ISSUE TITLE
資料のエクスポートで編者(contributor)が出力されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1069]
1.1系、1.2系の両方で確認。
https://enju.next-l.jp/resource_export_files/56

**Comment by nabeta** [comment]
contributorを出力するようにしました。

**Comment by yegusa** [comment]
できることを確認しました。マニュアルの修正は必要ないかとおもいます。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/11996569/08bc33cc-aaa9-11e5-9ac6-321f6fd6eecd.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11996577/26b759d8-aaa9-11e5-990c-3ded47b645ac.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1 687588e)
  * enju_circulation (0.1.1 caa363f)
  * enju_event (0.1.17 430dfb2)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.2 fc30d7f)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアル修正必要ないかと思ったけど、これ、バグじゃなくて enhancementだよね? 1.1.0時点ではcontributorはもともと出すようにしてなかったよね。
マニュアル修正しておきます。

**Comment by yegusa** [comment]
参考：　1.1.0時点のTSVエクスポート結果

<pre>
manifestation_id	original_title	creator	publisher	pub_date	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	isbn	iss_itemno	jpno	item_id	item_identifier	call_number	item_price	acquired_at	accepted_at	bookstore	budget_type	circulation_status	shelf	library	item_created_at	item_updated_at
1	はじめてのRuby on Rails : 話題の「Webアプリケーション・フレームワーク」が使える! : instant rails	清水, 美樹	工学社	2006-08	2300	2015-11-29 12:05:32 +0900	2015-12-06 17:41:07 +0900	http://iss.ndl.go.jp/books/R100000002-I000008276603-00	9784777512324	R100000002-I000008276603-00	21095296	5	909093							Available On Shelf	first_shelf	yours	2015-12-06 17:40:43 +0900	2015-12-06 17:41:07 +0900
2	レッスン	Pearson, Carol Lynn//灰島, かり, 1950-//ささめや, ゆき, 1943-	平凡社	2002-12	1400	2015-11-29 12:08:23 +0900	2015-12-15 20:33:44 +0900	http://iss.ndl.go.jp/books/R100000002-I000004040061-00	9784582831351	R100000002-I000004040061-00	20364486	2	300002							Available On Shelf	first_shelf	yours	2015-12-05 12:36:28 +0900	2015-12-15 20:33:44 +0900
3	Rails of Ruby on Rails : Case of Locusandwonders.com	清水, 智雄//Plan de Sens	毎日コミュニケーションズ	2008-05	3200	2015-12-05 12:34:42 +0900	2015-12-06 17:33:23 +0900	http://iss.ndl.go.jp/books/R100000002-I000009366581-00	9784839922214	R100000002-I000009366581-00	21434454	1	300001							Available On Shelf	first_shelf	yours	2015-12-05 12:35:12 +0900	2015-12-06 17:33:23 +0900
4	はじめてのRuby on Rails2 : 最新の「Webアプリケーション・フレームワーク」が使える!	清水, 美樹	工学社	2008-04	2300	2015-12-05 12:49:32 +0900	2015-12-15 20:38:10 +0900	http://iss.ndl.go.jp/books/R100000002-I000009331867-00	9784777513536	R100000002-I000009331867-00	21407507	3	300003							On Loan	first_shelf	yours	2015-12-05 12:50:01 +0900	2015-12-05 12:52:28 +0900
5	Ruby on Rails環境構築ガイド : ソース管理から公開までを徹底解説 : 定番ツールを使いこなして今日から即戦力!	黒田, 努	インプレスジャパン//インプレスコミュニケーションズ	2013-03	2800	2015-12-06 12:30:03 +0900	2015-12-15 20:38:07 +0900	http://iss.ndl.go.jp/books/R100000002-I024310898-00	9784844333753	R100000002-I024310898-00	22220800	4	909092							On Loan	first_shelf	yours	2015-12-06 17:33:57 +0900	2015-12-06 17:34:13 +0900
6	図書館情報資源概論	伊藤, 民雄, 1967-//大串, 夏身, 1948-//金沢, みどり, 1959-	学文社	2012-09	1800	2015-12-07 19:10:32 +0900	2015-12-07 19:10:43 +0900	http://iss.ndl.go.jp/books/R100000002-I023951143-00	9784762023040	R100000002-I023951143-00	22156874
7	はじめてのGrails : 「Ruby on Rails」風の「フレームワーク」をJavaで使いこなす!	清水, 美樹	工学社	2009-11	2300	2015-12-15 20:38:03 +0900	2015-12-15 20:38:47 +0900	http://iss.ndl.go.jp/books/R100000002-I000010622509-00	9784777514847	R100000002-I000010622509-00	21683240	6	600001							Available On Shelf	first_shelf	yours	2015-12-15 20:38:30 +0900	2015-12-15 20:38:30 +0900

</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアルに書いておきました。
