### ISSUE TITLE
ISBNハイフン付きでキーワード検索するとヒットしない　→ これは仕様?　それともバグ?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1071]
- [ ] 確認
- [ ] マニュアル　#1066

ハイフン付きでキーワード検索するとヒットしない　→ これは仕様?　それともバグ?

#881 でハイフン付きで表示するようにしたので、
キーワード検索できるようにしておいたほうがよいと思いますが
どうでしょうか。
（詳細検索でISBNならハイフンありでもできる）

![image](https://cloud.githubusercontent.com/assets/1328499/11994206/ea8e0b58-aa7d-11e5-9bdf-813ee66979fa.png)

### それ以外はOK
○ハイフンなしでキーワード検索するとヒットする
![image](https://cloud.githubusercontent.com/assets/1328499/11994214/0773165a-aa7e-11e5-926c-181668d2a650.png)

○ハイフンなしで細検索のISBN検索で検索するとヒットする
![image](https://cloud.githubusercontent.com/assets/1328499/11994260/ab17ac76-aa7e-11e5-88d8-dfcbf1812077.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994265/bd69b2fc-aa7e-11e5-9e32-e4acd3e78615.png)

○　ハイフン付きで詳細検索のISBN検索で検索するとヒットする
![image](https://cloud.githubusercontent.com/assets/1328499/11994248/8277532a-aa7e-11e5-87d0-ac873d6a60bd.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994240/61b97c08-aa7e-11e5-9332-c5b9016643b2.png)

○　ハイフン付きで表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11994178/a1e9bbea-aa7d-11e5-81c1-da7f544ab25a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
特に仕様というわけではありません。検索できるようにしておきます。

**Comment by nabeta** [comment]
検索できるようにしました。
http://dev.next-l.jp/manifestations?utf8=%E2%9C%93&query=978-4-535-06715-8&commit=%E6%A4%9C%E7%B4%A2

**Comment by yegusa** [comment]
reindex いる?　bundle update だけでいいの?

**Comment by nabeta** [comment]
再インデックスが必要です。

```sh
$ bundle exec rake sunspot:reindex RAILS_ENV=production
```

**Comment by yegusa** [comment]
できることを確認しました。（マニュアルは後で書きます。）
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/11995814/df59bb34-aa9a-11e5-9ca7-15b4777bf8e4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 83e10f4)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 7ee381d)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
