### ISSUE TITLE
Librarian権限以上でログインすると「所蔵の新規作成」が検索結果一覧に必ず表示される

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1072]
- [ ] 確認
- [ ] マニュアル #1066 

そんな仕様変更なかったですよね?

![image](https://cloud.githubusercontent.com/assets/1328499/11994671/08576dde-aa86-11e5-84b1-7c95d1543034.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

1.1系の場合

![image](https://cloud.githubusercontent.com/assets/1328499/11994694/53a0867c-aa86-11e5-8de5-6e9ebed84440.png)

**Comment by nabeta** [comment]
「所蔵」リンクも反応しなくなっていますね。ちょっと調べます。

**Comment by yegusa** [comment]
私は「所蔵」リンク反応しますよ。

**Comment by yegusa** [comment]
後、赤四角の所に、これに関連して、
常に「所蔵新規作成」（もしくは「所蔵作成」）ってあっていいのかもと思い始めた。
雑誌で「新規受入」があるんだしと。

![image](https://cloud.githubusercontent.com/assets/1328499/12006389/0a1ec502-ac18-11e5-8f18-8a7453c05416.png)

**Comment by nabeta** [comment]
ひとまず1.1と同じ動作にしました。開発サーバに反映済みです。

**Comment by nabeta** [comment]
> 後、赤四角の所に、これに関連して、
> 常に「所蔵新規作成」（もしくは「所蔵作成」）ってあっていいのかもと思い始めた。

賛成です。

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。　（マニュアル修正の必要はありません）

![image](https://cloud.githubusercontent.com/assets/1328499/12034199/0d76d3e2-ae71-11e5-96d0-4b3e028bd7db.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 ba2c861)
  * enju_circulation (0.2.0.beta.1 c8989b0)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 dd5b39f)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 a8c5424)
