### ISSUE TITLE
「貸出の表示」画面に、右メニューの「貸出の一覧に戻る」がなくなってしまっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1074]
#1007 の確認で気づきました。

- [ ] 確認
- [ ] マニュアル #1066 

（貸出期間の延長→表示でたどった先の画面）

右メニューの「貸出の一覧に戻る」がなくなってしまっている
![image](https://cloud.githubusercontent.com/assets/1328499/11999791/d4c462d6-ab09-11e5-935a-a61deff63767.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 7ca6e04)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 b6ba55b)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

参考：以前　1.1.1
![image](https://cloud.githubusercontent.com/assets/1328499/11804788/b76e6046-a349-11e5-99e0-a4eb5c1252f6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
以下のコミットで元に戻しているので、bundle updateを実行してください。
https://github.com/next-l/enju_circulation/commit/998b7c385d75dff0f3ea08cb71c6945bc2457f68

**Comment by yegusa** [comment]
@nabeta さん、 さっそく対応ありがとうございます。

元に戻してるってことは、どっかで変えたのでしょうか。

次回からは、マニュアルにも影響するので、変えた場合は、
一言、issueにて報告しておいてもらえると助かります。
（報告あったのに、見逃してたらごめんなさい）

というか、 issueにあげずに、画面の遷移が変わる、インタフェースが変わる等の開発を
するのはしないでくれると助かります。（細かなスペルミスの修正とかはともかく）

使い勝手が変わることがありますし、おもわぬ影響がでることも考えられます。

いきなり開発する前に、一旦issueに挙げて、
議論したり、他の人の意見も聞ける場を設けてほしいです。

よろしくおねがいします。

**Comment by yegusa** [comment]
bundle update, Enju再移動してみましたが、
リンクがでてません。

![image](https://cloud.githubusercontent.com/assets/1328499/12001891/ee5818d8-ab35-11e5-8da2-2cc8faccd983.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 d5b8c05)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 1329d66)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
この変更は #995 によるものですが、「貸出の一覧に戻る」と「戻る」をいっしょにするのかと思っていました（「戻る」が2個あるのは変なため）。ラベルを「戻る」と「貸出の一覧」にするのでどうでしょうか。

**Comment by yegusa** [comment]
そうでしたか。
#955 の時は、[戻る]リンクの動作バグを指摘し、[戻る]リンクの動作だけを修正というつもりでした。
[貸出の一覧に戻る]をいじる意識はありませんでした。

まあ、「貸出の一覧に戻る」の「に戻る」は文言的に変だなあとは少し思っていたので
右メニューは

* [編集]・・・貸出の編集画面へ行く　（アンカー名は[貸出の編集]　でもいいかもしれない）
* [戻る] ・・・ブラウザの戻るボタンとほぼ同じ動作
* [貸出の一覧]・・・貸出の一覧へ行く

でいいんじゃないでしょうか。

ここからは、コメント：
別issueを立てるつもりですが、
右メニューの[戻る]というアンカーがついたリンクは、将来的には消していきたいなと。
なんらかの意味のあるリンク（○○の一覧など）に付け替えていくといいのじゃないかなと思っています。
画面ごとに、ひとつひとつ、動作や影響を吟味しながらが必要かと思いますが。

**Comment by masao** [comment]
ひとまず、先に @nabeta さんが提案されたとおり、「戻る」と「貸出の一覧」の2つのリンクを残すよう修正しました（1.1の仕様にもどったはず）。

**Comment by yegusa** [comment]
仮想マシンで確認しました。

* [編集]・・・貸出の編集画面へ行く　
* [戻る] ・・・ブラウザの戻るボタンとほぼ同じ動作
* [貸出の一覧]・・・貸出の一覧へ行く

となることを確認しましたのでクローズします。

http://localhost:8080/checkouts/23
![image](https://cloud.githubusercontent.com/assets/1328499/12553758/87425bdc-c3bc-11e5-9865-f6d38fb7b2eb.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 47e3a3a)
  * enju_circulation (0.2.0.beta.1 d2bbdb9)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 25c8ca5)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 b797995)
