### ISSUE TITLE
エクスポートされたTSVがRubyのCSVパーサ(TSV対応)で読めない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1075]
https://travis-ci.org/next-l/enju_biblio/jobs/98699914

**Comment by nabeta** [comment]
すみません、これはテストが誤っていました。以下のようにタブ区切りであることを指定する必要がありました。

```ruby
CSV.parse(lines, col_sep: "\t")
```

**Comment by yegusa** [comment]
念のため確認だけど、

Ruby の CSVパーサーをつかって \t を指定して、TSVを読んでいるのではあるんでしょうけど、
Enju で、CSVをエクスポートすることないよね?　全部TSVだよね?

なので、issueのタイトル変えておきますよ。

**Comment by yegusa** [comment]
wontfixならクローズしちゃっていいのかな

**Comment by nabeta** [comment]
クローズします。
