### ISSUE TITLE
開催日と催し物の表示の右メニューに[開館日と催し物の一覧]リンクがない・[戻る]リンクがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1076]
- [ ] [開館日と催し物の一覧]リンクを付ける（前はあった）
- [ ] [戻る]リンクを消す（前はなかった）
- [ ] 確認
- [ ] マニュアル #1066 

関連 #1054 

例：
![image](https://cloud.githubusercontent.com/assets/1328499/11994519/4e18be5c-aa83-11e5-992d-bbc778abc325.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

参考：　1.1.0のときの画面では　「戻る」ではない。

http://localhost:8080/events/1
![image](https://cloud.githubusercontent.com/assets/1328499/11614084/94750520-9c7a-11e5-8dec-ff391a47390c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
以下のコミットで元に戻しています。
https://github.com/next-l/enju_event/commit/7ee381d138378975f70b76271a9ad8c0afd8cefa

開発サーバに反映済みです。
http://dev.next-l.jp/events/21

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12003661/6727749e-ab6c-11e5-907e-7ea8e7d4fd88.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
