### ISSUE TITLE
[利用者インポートの結果の一覧]リンクが[戻る]になってしまっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1078]
#217 をチェックしようとしてみつけました

http://localhost:8080/user_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/12001109/2cee0ca8-ab25-11e5-9bd7-ba6ac3aace2e.png)

http://localhost:8080/user_import_files/4
![image](https://cloud.githubusercontent.com/assets/1328499/12001111/488a7d02-ab25-11e5-9c19-344196cba324.png)

× 戻る →　○ [利用者インポートの結果の一覧]
http://localhost:8080/user_import_results/12 
![image](https://cloud.githubusercontent.com/assets/1328499/12001123/734649c2-ab25-11e5-951b-6ebd579dcce7.png)

----

### 1.1.1 の場合

http://localhost:8080/user_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/12001189/f9dca5a2-ab26-11e5-9d6b-13415a6b8f21.png)

http://localhost:8080/user_import_files/4
![image](https://cloud.githubusercontent.com/assets/1328499/12001193/0c63dee8-ab27-11e5-9f76-62d35bee179b.png)

○ [利用者インポートの結果の一覧]リンクをクリック
http://localhost:8080/user_import_results/12
![image](https://cloud.githubusercontent.com/assets/1328499/12001210/2f51d5c2-ab27-11e5-9bb1-d49d8b501193.png)

http://localhost:8080/user_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/12001212/4023722a-ab27-11e5-97a8-bf3f49abeded.png)

http://localhost:8080/user_import_results.txt?locale=ja
<pre>
""	user_number	username	email	password
"user05"	100005	user05	user05@sample.jp	habanera
""	user_number	username	email	password
"user06"	100006	user06	user06@sample.jp	habanera
""	100007あ	user07	user07@sample.jp	habanera1
""	user_number	username	email	password
"user806"	800006	user806	user806@sample.jp	habanera
""	800007あ	user807	user807@sample.jp	habanera1
"user808"	800008	user808	user808@sample.jp	habanera2
"user809"	800009	user809	user809@sample.jp	habanera3
</pre>

**Comment by nabeta** [comment]
以下のコミットで元に戻しています。
https://github.com/next-l/enju_leaf/commit/f1f8c593c4f4c9d665fdbe5df1515420ed296419

開発サーバに反映済みです。
http://dev.next-l.jp/user_import_results/136

**Comment by yegusa** [comment]
できていることを確認したのでクローズします。

http://localhost:8080/user_import_results/12
![image](https://cloud.githubusercontent.com/assets/1328499/12003648/b0acb54e-ab6b-11e5-9ffb-ef9ca4b41075.png)

http://localhost:8080/user_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/12003649/c21453aa-ab6b-11e5-9bbe-5239bcaf8198.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
