### ISSUE TITLE
利用者インポート結果の一覧のTSVでヘッダが何度も出力されている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1079]
× ヘッダ（""   user_number username    email   password）が何度も出力されている
http://localhost:8080/user_import_results.txt?locale=ja

<pre>
""  user_number username    email   password
"user05"    100005  user05  user05@sample.jp    habanera
""  user_number username    email   password
"user06"    100006  user06  user06@sample.jp    habanera
""  100007あ   user07  user07@sample.jp    habanera1
""  user_number username    email   password
"user806"   800006  user806 user806@sample.jp   habanera
""  800007あ   user807 user807@sample.jp   habanera1
"user808"   800008  user808 user808@sample.jp   habanera2
"user809"   800009  user809 user809@sample.jp   habanera3
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.2.0.beta.1 d5b8c05)
- enju_circulation (0.2.0.beta.1 b41b3ba)
- enju_event (0.2.0.beta.1 3ecd86c)
- enju_leaf (1.2.0.beta.1 6a07d2f)
- enju_library (0.2.0.beta.1 9588750)
- enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
- enju_message (0.2.0.beta.1 7b9d120)
- enju_ndl (0.2.0.beta.1 8f66dba)
- enju_purchase_request (0.1.0 bc500c6)
- enju_subject (0.2.0.beta.1 49905da)
#1078 に関連

参考：この画面への行き方
http://localhost:8080/user_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/12001671/a6c586b8-ab30-11e5-8a6f-8d513859e871.png)

http://localhost:8080/user_import_files/4
![image](https://cloud.githubusercontent.com/assets/1328499/12001676/b864bd4e-ab30-11e5-813f-a949245782e5.png)

(#1078 のバグが修正されると　[利用者インポートの結果の一覧]のリンクがあるはず）
http://localhost:8080/user_import_results/12
![image](https://cloud.githubusercontent.com/assets/1328499/12001689/06073b08-ab31-11e5-8422-ed9e85b24bee.png)

http://localhost:8080/user_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/12001601/cdc7665c-ab2e-11e5-863b-61414bc41c8d.png)

**Comment by nabeta** [comment]
これは、以下のようにインポートしたファイルのIDを指定していないためです。
http://dev.next-l.jp/user_import_results.txt?user_import_file_id=40

以下の画面で、結果の表の近くにTSVファイルへのリンクを追加すればよいと思いますが、いかがでしょうか。
http://dev.next-l.jp/user_import_files/40

**Comment by yegusa** [comment]
つまり、なんどもヘッダがでてしまうのは仕様で、これを直すことはしないってことでしょうか。
それなら、何度もヘッダがでるのはおかしいので、↓のTSVへのリンクは消せばいいんじゃないでしょうか?
あまり使用用途もおもいあたりませんし。
http://localhost:8080/user_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/12001601/cdc7665c-ab2e-11e5-863b-61414bc41c8d.png)

じゃあ、↓の赤四角あたりに、インポートしたファイルのIDを指定したTSVファイルへのリンクを追加すればいいのじゃないかと。
http://dev.next-l.jp/user_import_files/40
![image](https://cloud.githubusercontent.com/assets/1328499/12073772/c1a729f2-b173-11e5-85cf-6a9e2395374e.png)

**Comment by nabeta** [comment]
> それなら、何度もヘッダがでるのはおかしいので、↓のTSVへのリンクは消せばいいんじゃないでしょうか?
> あまり使用用途もおもいあたりませんし。
> http://localhost:8080/user_import_results

/user_import_results にあったインポート結果のTSVファイルへのリンクは削除しました。
https://enju.next-l.jp/user_import_results
<img width="931" alt="スクリーンショット 2019-12-22 12 52 04" src="https://user-images.githubusercontent.com/11428/71316804-f1a69f80-24b9-11ea-8352-30bf560d0eb2.png">

> じゃあ、↓の赤四角あたりに、インポートしたファイルのIDを指定したTSVファイルへのリンクを追加すればいいのじゃないかと。
> http://dev.next-l.jp/user_import_files/40

https://enju.next-l.jp/user_import_files/49
/user_import_files/{id} にインポート結果のTSVファイルへのリンクを追加しました。
<img width="354" alt="スクリーンショット 2019-12-22 12 48 59" src="https://user-images.githubusercontent.com/11428/71316813-29154c00-24ba-11ea-82cc-d7da7a274235.png">

**Comment by masao** [comment]
出力結果を確認しました。クローズします。
