### ISSUE TITLE
資料インポート結果の一覧のTSVでヘッダが何度も出力されている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1080]
#1079 の資料版

×ヘッダ（""    user_number username    email   password）が何度も出力されている

http://localhost:8080/user_import_results.txt?locale=ja

<pre>
""  user_number username    email   password
"user05"    100005  user05  user05@sample.jp    habanera
""  user_number username    email   password
"user06"    100006  user06  user06@sample.jp    habanera
""  100007あ   user07  user07@sample.jp    habanera1
""  user_number username    email   password
"user806"   800006  user806 user806@sample.jp   habanera
""  800007あ   user807 user807@sample.jp   habanera1
"user808"   800008  user808 user808@sample.jp   habanera2
"user809"   800009  user809 user809@sample.jp   habanera3
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.2.0.beta.1 d5b8c05)
- enju_circulation (0.2.0.beta.1 b41b3ba)
- enju_event (0.2.0.beta.1 3ecd86c)
- enju_leaf (1.2.0.beta.1 6a07d2f)
- enju_library (0.2.0.beta.1 9588750)
- enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
- enju_message (0.2.0.beta.1 7b9d120)
- enju_ndl (0.2.0.beta.1 8f66dba)
- enju_purchase_request (0.1.0 bc500c6)
- enju_subject (0.2.0.beta.1 49905da)

参考：この画面への生き方

http://localhost:8080/resource_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/12001743/61ac5b4a-ab32-11e5-85dd-5bec100815c5.png)

http://localhost:8080/resource_import_files/7
![image](https://cloud.githubusercontent.com/assets/1328499/12001747/85e4ad32-ab32-11e5-857d-c4152cedf099.png)

http://localhost:8080/resource_import_results/25
![image](https://cloud.githubusercontent.com/assets/1328499/12001750/a48e60b6-ab32-11e5-8a44-6ec43fc71a6c.png)

http://localhost:8080/resource_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/12001752/b92900f8-ab32-11e5-8b3f-a5c7570a48e8.png)

**Comment by nabeta** [comment]
こちらも next-l/enju_leaf#1079 同様、TSVファイルへのリンクを移動しました。
https://enju.next-l.jp/resource_import_results
<img width="925" alt="スクリーンショット 2019-12-22 14 27 18" src="https://user-images.githubusercontent.com/11428/71317602-34bb3f80-24c7-11ea-8345-ebb1f2211d87.png">

https://enju.next-l.jp/resource_import_files/238
<img width="732" alt="スクリーンショット 2019-12-22 14 27 05" src="https://user-images.githubusercontent.com/11428/71317605-384ec680-24c7-11ea-9a84-53864096b276.png">

**Comment by masao** [comment]
個別のインポート結果のTSVですが。
2点あります。

1. 最初の2列分のヘッダに何か列名を入れておきませんか?
たぶん manifestation_id と item_id ではないかと思うのですが。。。

2. ページネイションの関係と思うのですが、10件以上のインポートファイルの結果を見ようとしても、最初の10行分しかTSV出力されないようです。これはたぶんここだけでなく、利用者インポートなども同様ではないかと想像されます。。

![image](https://user-images.githubusercontent.com/38825/74599439-218eaf80-50c5-11ea-8c13-e6ac1ea79cbf.png)

**Comment by masao** [comment]
TSVダウンロードのリンクが消えていますね。

**Comment by masao** [comment]
なるほど、https://github.com/next-l/enju_leaf/issues/1080#issuecomment-568234058 からリンクしている場所を変えたんですね。ひとまず
imported_manifestation_id \t imported_item_id というヘッダが追加されていることを確認しました。
