### ISSUE TITLE
編集画面にすでに登録された識別子が表示されない（識別子が修正できない）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1081]
ISBNなどが登録されている　[編集]リンクをクリック
![image](https://cloud.githubusercontent.com/assets/1328499/12005122/98e81e30-abd4-11e5-88c9-8678df3c0f5d.png)

「識別子」にはなにも表示されてない（なので既入力の識別子を修正できない）　[更新]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/12005124/cd59832a-abd4-11e5-83bc-58d275762dbe.png)

↑でない状態で更新したとしても、識別子はのこってはいる
![image](https://cloud.githubusercontent.com/assets/1328499/12005126/4ab23bfa-abd5-11e5-8cd2-fb2c64438eb4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0e4604a)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

参考： 1.1系では表示されている
![image](https://cloud.githubusercontent.com/assets/1328499/12005130/cc5fad22-abd5-11e5-8ebb-861ec6b53158.png)

**Comment by masao** [comment]
cocoonライブラリへの移行時の修正時にテンプレートの追加し忘れがあったようです。 cf. https://github.com/next-l/enju_biblio/commit/2e0f230b55271f8ae19f257ee0b104153e0380d1
修正してみましたのでご確認ください。

**Comment by yegusa** [comment]
できることを確認しました。クローズします。（マニュアルの修正は必要ないです）

![image](https://cloud.githubusercontent.com/assets/1328499/12005189/1f1bbdae-abda-11e5-8cff-6a04a9f5e32e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12005190/3372e78c-abda-11e5-998f-88ce76a0db03.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 b89ee3f)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
