### ISSUE TITLE
「図書館全体の設定」の表示画面がGuestやUser権限で見えてしまう。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1083]
#988　からの派生です。

ログインしていない（Guest）やUser権限のときはアクセス拒否になるべき。

http://localhost:8080/library_groups/1
![image](https://cloud.githubusercontent.com/assets/1328499/12009345/22f188ae-acb7-11e5-839a-8919cf677461.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12009349/43c7a68a-acb7-11e5-8643-bc815172c8aa.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 6cf1bd7)
  * enju_circulation (0.2.0.beta.1 db02222)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 0882d26)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
修正しました。開発サーバに反映済みです。

**Comment by yegusa** [comment]
a) ログインしていないときの挙動（ログイン画面に飛ぶ、ログイン後はトップへ）は想定通りなんですよね?
b) User権限でログインしているときは「アクセス拒否」になるのは、想定どおりな気がします。

### a) ログインしていないとき　→ ○?　ログイン画面に行く
![image](https://cloud.githubusercontent.com/assets/1328499/12010523/72724522-aced-11e5-93fb-28c78f9b1fa1.png)

ログインすると、トップ画面へ
![image](https://cloud.githubusercontent.com/assets/1328499/12010534/ad132638-aced-11e5-9881-273b9c73bcc4.png)

### b) User 権限でアクセスしたとき →　○ アクセスは拒否されました　とでる。　
![image](https://cloud.githubusercontent.com/assets/1328499/12010507/093c61d2-aced-11e5-9d5e-1a132fd05f81.png)



vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 6cf1bd7)
  * enju_circulation (0.2.0.beta.1 db02222)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 9362590)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
> ログインしていないときの挙動（ログイン画面に飛ぶ、ログイン後はトップへ）は想定通りなんですよね?

はい、そうです。

**Comment by yegusa** [comment]
じゃあ、クローズします。
