### ISSUE TITLE
要望：同じメールアドレスのユーザを登録できるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1084]
現在：同じメールアドレスのユーザが登録できません

家族でメールアドレスを共有しているなど、
複数の利用者が同じメールアドレスを使用したいことはあるとおもいます。

ワーニングを出すのは会ってもいいですが、
それでも登録するといった機能が欲しいと思います。

![image](https://cloud.githubusercontent.com/assets/1328499/12014291/02403e3c-ad6d-11e5-85e8-29b7bfe4bcc6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.2.0.beta.1 6cf1bd7)
- enju_circulation (0.2.0.beta.1 db02222)
- enju_event (0.2.0.beta.1 1483293)
- enju_leaf (1.2.0.beta.1 0a9aed9)
- enju_library (0.2.0.beta.1 9362590)
- enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
- enju_message (0.2.0.beta.1 498ec1d)
- enju_ndl (0.2.0.beta.1 ce80288)
- enju_purchase_request (0.1.0 c3600e2)
- enju_subject (0.2.0.beta.1 49905da)

**Comment by nabeta** [comment]
@yegusa これは、ユーザ識別用のメールアドレスとは別の、連絡用メールアドレスを追加することで対応できないかと思います。

**Comment by nabeta** [comment]
@yegusa パスワード忘れの対応が難しいため、対応なしとさせてください。
