### ISSUE TITLE
件名標目の種類と分類の種類の表示名の大文字／小文字を正確に→初期投入データにLCSH,NDC8を追加する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1086]
- [x] 確認
- [ ] マニュアル #1066

プリセット値がどうなっているか分からないのですが，デモサーバー，開発用サーバー
http://dev.next-l.jp/subject_heading_types
http://dev.next-l.jp/classification_types
http://enju.next-l.jp/subject_heading_types
http://localhost:8081/classification_types
を見ると，件名標目の種類や分類の種類の表示名が「ndlsh」とか「ndc8」のように小文字のものが入っています。
「BSH」「NDLSH」「LCSH」「NDC」「NDLC」「DDC」「LCC」「NLMC」については，表示名は大文字が妥当ではないでしょうか。
また，開発用サーバーに「NLM」があります。もし「米国国立医学図書館分類法」のことなら，「NLMC」が妥当ではないでしょうか。

**Comment by nabeta** [comment]
件名標目などのマスタデータには、name（検索などで内部的に使用）とdisplay_name（画面表示で使用）のふたつの項目があります。nameで使えるのは小文字のみです。また、nameは必須ですが、display_nameは必須ではなく、display_nameが空で新しいデータが作成された場合、nameがそのままコピーされます。

新規作成時のdisplay_nameをデフォルトで大文字に変換してもよいかどうかは、意見を聞きたいと思います。

**Comment by scivola** [comment]
プリセット値はとくに無いんですね？

私が見た dev.next-l.jp や enju.next-l.jp で小文字になってたやつは，display_name を入力しなかったためにそうなっただけなんですね？　使う人が正しく入力すれば済む話と？

それなら現状のママでいいと思います。

むしろ勝手に大文字にしてはいけないでしょう。MeSH（Medical Subject Headings）の例もあります。

**Comment by masao** [comment]
途中で個別に追加されたデータという意味では、画面上から編集してもらって表示名を適切なものに変えてもらうのがよいとは思います。

ただ、初期投入データに関しては、現状のインストールスクリプトだと、以下は投入しますので、これにいくつか追加しておくとよいと思います。

* 件名標目の種類 (/subject_heading_types): NDLSH, BSH
* 分類の種類 (/classification_types): NDC9, DDC

すくなくとも enju_ndl, enju_loc などが対応している LCSH, NDC8 は追加しておく必要がありそうです。

**Comment by nabeta** [comment]
インストールスクリプトでLCSHとNDC8を追加するようにしました。

**Comment by yegusa** [comment]
1.2系を新規インストールして、確認しました。

* 件名標目の種類 (/subject_heading_types): NDLSH, BSH, <b>LCSH</b>
* 分類の種類 (/classification_types): NDC9, DDC, <b>NDC8</b>

件名：
![image](https://cloud.githubusercontent.com/assets/1328499/12078939/3aef1a5e-b269-11e5-9e99-8451bcead787.png)

分類：
![image](https://cloud.githubusercontent.com/assets/1328499/12078945/4fea3362-b269-11e5-96dd-83340c9708dc.png)

bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e40e80e)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_subject (0.2.0.beta.1 237251b)

**Comment by yegusa** [comment]
プリセット値を正しいものにするという主旨は、修正されたかと思いますので、クローズしますね。もしなにかあれば、リオープンください。→ @scivola さん。

**Comment by scivola** [comment]
はい，解決ですね。
