### ISSUE TITLE
詳細検索の出版日・受入日・ページ数欄で「~」を使う

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1087]
- [ ] 確認
- [ ] マニュアル #1066 

詳細検索の「出版日」「受入日」「ページ数」はいずれも範囲を入力しますが，始点・終点（上限・下限）のいずれか一方でも構わないようになっています。

現状では
［　　］から［　　］
のようになっていますが，上限だけ入力して
［　　］から［100］
だと日本語にならず，違和感があります。

そこで添付の画像のように，「まで」を付け，かつ始点・終点の間をあけるとよいのではないかと思います。

あるいは現状の「から」を「～」にしちゃうのでもいいかもしれません。
![from-to](https://cloud.githubusercontent.com/assets/294125/12015362/955bdc6a-ad7e-11e5-93fb-d902a634239e.png)

**Comment by nabeta** [comment]
「まで」の表記がないのは、英語画面の扱いが理由です。日本語の場合、「2001 から 2015 まで」と、出版年のあとに文字が来るのですが、英語だと"From 2001 to 2015"と、出版年の前に文字が来ます。これがうまくひとつのテンプレートで扱えないため、現状のようになっています。

> あるいは現状の「から」を「～」にしちゃうのでもいいかもしれません。

これならよさそうです。

**Comment by scivola** [comment]
あー，こういうことなのですね：
https://github.com/next-l/enju_leaf/blob/1.1/config/locales/translation_ja.yml#L290

英語だと from [　] to [　] で，日本語だと from を空にして to に「から」を当てる，と。

それなら，末尾にもう一つ文字列を追加して，英語は空に，日本語は「まで」にすれば一応どうにかできますね。

しかし，いずれにしてもあまり素直とは言えませんね。かといって言語によって場合分けするのもなんだか。

簡潔でかつ不自然でない表記として「〜」ですかね。
ただ，英語はどうすればいいでしょう？　英語で範囲を表すのに「〜」は使えません。正しくは en dash（U+2013; &amp;ndash;）ですが，英語でウェブのフォームの入力欄を U+2013 でつなぐのって普通なんでしょうか？

**Comment by nabeta** [comment]
英語は「～」を使わず"from [    ] to  [   ]"にして、日本語を「[    ] ～ [    ]」にするというのはどうでしょう。

**Comment by scivola** [comment]
とりあえずそれでもいいと思います。

**Comment by yegusa** [comment]
> 英語は「～」を使わず"from [ ] to [ ]"にして、日本語を「[ ] ～ [ ]」にするというのはどうでしょう。

わたしもそれでよいと思います。

**Comment by nabeta** [comment]
「〜」を使うように変更しました。
http://dev.next-l.jp/page/advanced_search

**Comment by yegusa** [comment]
確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12065963/78a973a0-b023-11e5-9320-9a67f55146d7.png)

参考：　英語
![image](https://cloud.githubusercontent.com/assets/1328499/12065970/9970a0ae-b023-11e5-8969-6b24eb8a9c0e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
