### ISSUE TITLE
検索結果一覧の表の最右の列に常に「所蔵新規作成」（もしくは「所蔵作成」）リンクを付ける

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1092]
- [x] 確認
- [ ] マニュアル #1066 

#1072 からの派生です。

赤四角のあたりに、常に「所蔵新規作成」（もしくは「所蔵作成」）リンクを付ける

![image](https://cloud.githubusercontent.com/assets/1328499/12034235/8b21449e-ae71-11e5-9f7e-bf6b1d736561.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 ba2c861)
  * enju_circulation (0.2.0.beta.1 c8989b0)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 dd5b39f)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 a8c5424)

**Comment by nabeta** [comment]
「所蔵作成」のリンクを一覧右側に移動しました。

![fireshot capture 31 - - next-l enju leaf_ - http___dev next-l jp_manifestations](https://cloud.githubusercontent.com/assets/11428/12036954/08520dce-ae8e-11e5-8b91-9d0a0943aabd.png)

**Comment by yegusa** [comment]
確認しましたので、クローズします。

[所蔵作成]リンクをクリック
![image](https://cloud.githubusercontent.com/assets/1328499/12065899/84ae5d56-b022-11e5-9964-e248205e9f84.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12065905/a4394672-b022-11e5-84ed-25e7ed59dc2d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
