### ISSUE TITLE
書誌編集画面のタイトル等の入力欄の幅を広く（長く）する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1094]
- [ ] マニュアル修正 #1066 

今さらなのですが、書誌編集画面のタイトルの入力欄が短いです。画面幅いっぱいまで広げたほうがよいのではないでしょうか。
https://dev.next-l.jp/manifestations/24424/edit

**Comment by scivola** [comment]
```
width: 100%;
box-sizing: border-box;
```
ですよね（[box-sizing は IE8 でも OK](https://developer.mozilla.org/ja/docs/Web/CSS/box-sizing) ）

タイトルに限らず，ある程度以上長くすべき入力欄は横幅いっぱいがいいと思います。

タイトルを横幅いっぱいにすると，日本最長のタイトル（出版当時）
http://iss.ndl.go.jp/books/R100000002-I000001399909-00
もなんとか入ります。

出版社も「ユニバーサル・シェル・プログラミング研究所」くらいは余裕で入る長さが必要だと思います。

著者も短いですね。

**Comment by scivola** [comment]
件名も「 日本文学―歴史―昭和時代（1945年以後） 」くらいは入ったほうが。

ローカル識別子も
http://iss.ndl.go.jp/books/R100000002-I000009307826-00
とか入ってないですね。

**Comment by yegusa** [comment]
別issueにしたほうがいいか悩みますが、広げたほうがよいのは、以下の項目あたりでしょうか。

* 原題
* タイトルのヨミ
* 代替タイトル
* 責任表示
* シリーズ名
* シリーズ名のヨミ
* シリーズ著者
* 著者
* 協力者・編者
* 出版者
* 出版地
* ローカル識別子
* 件名



![image](https://cloud.githubusercontent.com/assets/1328499/12060382/866d123e-afb1-11e5-9172-0133b4167973.png)

enju_biblio: 0.2.0.beta.1
enju_circulation: 0.2.0.beta.1
enju_event: 0.2.0.beta.1
enju_leaf: 1.2.0.beta.1
enju_library: 0.2.0.beta.1
enju_manifestation_viewer: 0.2.0.beta.1
enju_message: 0.2.0.beta.1
enju_ndl: 0.2.0.beta.1
enju_purchase_request: 0.1.0
enju_subject: 0.2.0.beta.1

**Comment by nabeta** [comment]
アクセスアドレス(URL)も長くなることがありますね。あと、説明・注記も右側にスペースがあるので、画面いっぱいまで広げてよいと思います。

**Comment by nabeta** [comment]
まず影響が出なさそうな、タイトル（よみなど含む）・著者・編者・出版者・アクセスアドレス・説明・注記について、表示幅を広げました。
http://dev.next-l.jp/manifestations/new

**Comment by yegusa** [comment]
開発：
- [ ] 原題
- [ ] タイトルのヨミ
- [ ] 代替タイトル
- [ ] 責任表示
- [ ] シリーズ名
- [ ] シリーズ名のヨミ
- [ ] シリーズ著者
- [ ] 著者
- [ ] 協力者・編者
- [ ] 出版者
- [ ] 出版地
- [ ] ローカル識別子
- [ ] 件名
- [ ] アクセスアドレス　（追加）
- [ ] 説明（追加）
- [ ] 注記（追加）

確認：
- [ ] 原題
- [ ] タイトルのヨミ
- [ ] 代替タイトル
- [ ] 責任表示
- [ ] シリーズ名
- [ ] シリーズ名のヨミ
- [ ] シリーズ著者
- [ ] 著者
- [ ] 協力者・編者
- [ ] 出版者
- [ ] 出版地
- [ ] ローカル識別子
- [ ] 件名
- [ ] アクセスアドレス　（追加）
- [ ] 説明（追加）
- [ ] 注記（追加）

**Comment by nabeta** [comment]
出版地ってそんなに長いのあります？

**Comment by yegusa** [comment]
英語ならあり得るのじゃない?
具体例はしらないけど。

**Comment by yegusa** [comment]
長めな例：
Sri Jayawardenepura Kotte
https://ja.wikipedia.org/wiki/%E3%82%B9%E3%83%AA%E3%82%B8%E3%83%A3%E3%83%A4%E3%83%AF%E3%83%AB%E3%83%80%E3%83%8A%E3%83%97%E3%83%A9%E3%82%B3%E3%83%83%E3%83%86

**Comment by scivola** [comment]
仮名表記だとスリー・ジャヤワルダナプラ・コーッテ。
もっとも正式名称はあまり使わなくて単に「コーッテ」（仮名表記としてはコッテとも）がふつうみたいです。

タイのバンコクは正式名称が「クルンテープマハナコーン・アモーンラッタナコーシン・マヒンタラアユッタヤー・マハーディロッカポップ・ノッパラッタラーチャタニーブリーロム・ウドムラーチャニウェートマハーサターン・アモーンピマーンアワターンサティット・サッカタットティヤウィサヌカムプラスィット」だそうですが，ふつうは「クルンテープ」（またはバンコク）ですね。

**Comment by nabeta** [comment]
スペースに限りがあるわけではないので、広げておきます。

**Comment by yegusa** [comment]
とりあえず、この時点で、クローズし、残りは検討課題として、ほかのissueにしようとおもいますけど、いいですか？
それとも、まだ開発中ですか？ → @nabeta

**Comment by yegusa** [comment]
Enju WS で @nabeta に 確認しました。残りのものもやる予定はあるがまだ終わっていないとのこと。

**Comment by nabeta** [comment]
シリーズ著者・出版地・ローカル識別子・件名・分類（これも加えました）について、フォームの幅を広げました。
http://dev.next-l.jp/manifestations/new

**Comment by yegusa** [comment]
手元の仮想マシンでは広くなっていないものがあります。すくなくとも赤四角でかこったのは
狭いようなきがします。

![image](https://cloud.githubusercontent.com/assets/1328499/13251153/d6503138-da71-11e5-83b2-918609fb9d7f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a8fc822)
  * enju_circulation (0.2.0.beta.1 2a3c92e)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 caf679d)
  * enju_library (0.2.0.beta.1 1805417)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 9f89fe6)

**Comment by nabeta** [comment]
スタイルシートに変更があったので、以下のコマンドを実行してください。

```sh
$ bundle exec rake assets:precompile
```

**Comment by masao** [comment]
おおよそ確認したのでひとまずクローズします。
![next l enju leaf_2](https://cloud.githubusercontent.com/assets/38825/13378727/7728a82c-de52-11e5-9ce1-5717bdf8cfaf.png)

**Comment by yegusa** [comment]
マニュアルを修正しました。

4-2-7 手動で資料を登録する
https://next-l.github.io/manual/1.2/enju_operation_4.html#section4-2-7
のスクリーンショットを変更

4-2-8 図書の書誌を編集（修正）する
https://next-l.github.io/manual/1.2/enju_operation_4.html#section4-2-8
のスクリーンショットを変更
