### ISSUE TITLE
要望：分類のTSVエクスポートの方式をヘッダで区別するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1096]
#408 の分類のTSVインポートとセットということで、 1.2.0でお願いします。
（件名は #407 ）（ #1095 と類似）

**Comment by nabeta** [comment]
分類のエクスポートの形式を変更しました。以下に例があります。
http://dev.next-l.jp/resource_export_files/79

**Comment by yegusa** [comment]
できるようになったことを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12078393/804d7f70-b253-11e5-88c1-02034e579c44.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e40e80e)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
