### ISSUE TITLE
1.2系の新規インストールで、書誌詳細を見ようとするとWe're sorry に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1097]
#1091 で作成した環境で、
NDL サーチでインポートしようとしたら We're sorry になりました。
手動で登録しても、同様でした。
（ #1061 にも関連? ）

![image](https://cloud.githubusercontent.com/assets/1328499/12069776/bce04f60-b08e-11e5-8c67-c20b348a1b0f.png)

としたら We're sorry something wrong に。
![image](https://cloud.githubusercontent.com/assets/1328499/12069781/dbe570e8-b08e-11e5-8406-d3fe7b177008.png)

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 4c1d88b)
  * enju_circulation (0.2.0.beta.1 c8989b0)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 dd5b39f)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_subject (0.2.0.beta.1 f67cf88)

**Comment by yegusa** [comment]
エラーログの一部です。

<pre>
s)
I, [2016-01-01T04:56:57.694274 #1266]  INFO -- : Completed 200 OK in 1446ms (Views: 198.2ms | ActiveRecord: 21.3ms | Solr: 1150.0ms)
I, [2016-01-01T04:57:11.647611 #1266]  INFO -- : Started GET "/manifestations/2" for 127.0.0.1 at 2016-01-01 04:57:11 +0000
I, [2016-01-01T04:57:11.651019 #1266]  INFO -- : Processing by ManifestationsController#show as HTML
I, [2016-01-01T04:57:11.651197 #1266]  INFO -- :   Parameters: {"id"=>"2"}
D, [2016-01-01T04:57:11.667638 #1266] DEBUG -- :   ESC[1mESC[35mUser Load (0.9ms)ESC[0m  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "
users"."id" ASC LIMIT 1  [["id", 2]]
D, [2016-01-01T04:57:11.678098 #1266] DEBUG -- :   ESC[1mESC[36mLibraryGroup Load (1.2ms)ESC[0m  ESC[1mSELECT  "library_groups".* FROM "library_groups" WHE
RE "library_groups"."id" = $1 LIMIT 1ESC[0m  [["id", 1]]
D, [2016-01-01T04:57:11.684891 #1266] DEBUG -- :   ESC[1mESC[35mManifestation Load (1.7ms)ESC[0m  SELECT  "manifestations".* FROM "manifestations" WHERE "m
anifestations"."id" = $1 LIMIT 1  [["id", 2]]
D, [2016-01-01T04:57:11.698307 #1266] DEBUG -- :   ESC[1mESC[36mRole Load (1.2ms)ESC[0m  ESC[1mSELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" O
N "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = $1 LIMIT 1ESC[0m  [["user_id", 2]]
D, [2016-01-01T04:57:11.708990 #1266] DEBUG -- :   ESC[1mESC[35mSeriesStatement Load (0.7ms)ESC[0m  SELECT  "series_statements".* FROM "series_statements"
WHERE "series_statements"."manifestation_id" = $1 AND "series_statements"."root_manifestation_id" = $2  ORDER BY "series_statements"."id" ASC LIMIT 1  [["m
anifestation_id", 2], ["root_manifestation_id", 2]]
D, [2016-01-01T04:57:11.737045 #1266] DEBUG -- :   ESC[1mESC[36m (2.7ms)ESC[0m  ESC[1mSELECT COUNT(*) FROM "reserves" LEFT OUTER JOIN reserve_transitions m
ost_recent_reserve_transition
             ON most_recent_reserve_transition.reserve_id =
                  reserves.id LEFT OUTER JOIN reserve_transitions other_reserve_transition
             ON other_reserve_transition.reserve_id =
                  reserves.id
             AND other_reserve_transition.sort_key >
                   most_recent_reserve_transition.sort_key WHERE (NOT (most_recent_reserve_transition.to_state IN ('completed','expired') AND most_recent_r
eserve_transition.to_state IS NOT NULL)) AND "other_reserve_transition"."id" IS NULL AND (canceled_at IS NULL AND (expired_at > '2016-01-01 04:57:11.726961
' OR expired_at IS NULL)) AND "reserves"."manifestation_id" = $1 AND "reserves"."checked_out_at" IS NULLESC[0m  [["manifestation_id", 2]]
I, [2016-01-01T04:57:11.746488 #1266]  INFO -- : Completed 500 Internal Server Error in 93ms (ActiveRecord: 19.3ms)
F, [2016-01-01T04:57:11.760253 #1266] FATAL -- :
NoMethodError (undefined method `reserves' for #<User:0x0000000b92a710>):
  activemodel (4.2.5) lib/active_model/attribute_methods.rb:433:in `method_missing'
  /home/vagrant/.bundler/ruby/2.2.0/enju_biblio-4c1d88b3fa70/app/controllers/manifestations_controller.rb:322:in `show'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'

</pre>

**Comment by nabeta** [comment]
config/initializers/enju_leaf.rb に以下の行があるかどうかを確認し、なければその行を追加してください。なお、このファイルは1.2で新しく使用するようになりました。

```ruby
Manifestation.include(EnjuCirculation::EnjuManifestation)
CarrierType.include(EnjuCirculation::EnjuCarrierType)
Item.include(EnjuCirculation::EnjuItem)
Accept.include(EnjuCirculation::EnjuAccept)
Basket.include(EnjuCirculation::EnjuBasket)
Profile.include(EnjuCirculation::EnjuProfile)
UserGroup.include(EnjuCirculation::EnjuUserGroup)
Withdraw.include(EnjuCirculation::EnjuWithdraw)
Item.include(EnjuLibrary::EnjuItem)
```

**Comment by nabeta** [comment]
あと、app/models/user.rb が以下のようになっているかどうかも確認してください。

```ruby
class User < ActiveRecord::Base
  # 中略
  include EnjuLeaf::EnjuUser
  include EnjuMessage::EnjuUser
  include EnjuCirculation::EnjuUser
end
```

**Comment by yegusa** [comment]
参考：


vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ cat config/initializers/enju_leaf.rb

```ruby
Item.include(EnjuLibrary::EnjuItem)
Accept.include(EnjuCirculation::EnjuAccept)
Basket.include(EnjuCirculation::EnjuBasket)
CarrierType.include(EnjuCirculation::EnjuCarrierType)
Manifestation.include(EnjuCirculation::EnjuManifestation)
Item.include(EnjuCirculation::EnjuItem)
Profile.include(EnjuCirculation::EnjuProfile)
UserGroup.include(EnjuCirculation::EnjuUserGroup)
Withdraw.include(EnjuCirculation::EnjuWithdraw)
```

**Comment by masao** [comment]
インストールスクリプトを修正しました。インストール手順をやり直すか、以下コマンドだけ実行しなおして再起動してください。
```
rails g enju_leaf:quick_install
```

**Comment by yegusa** [comment]
参考：

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ cat app/models/user.rb

```
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :trackable, #:validatable,
      :lockable, :lock_strategy => :none, :unlock_strategy => :none
  include EnjuLeaf::EnjuUser

end
```

**Comment by yegusa** [comment]
```sh
$ bundle update
$ rails g enju_leaf:quick_install
$ bundle exec foreman start
```

として、できるようになったことを確認しましたのでクローズします。

### NDLサーチインポート

NDLサーチでインポート
![image](https://cloud.githubusercontent.com/assets/1328499/12069930/644acd0e-b097-11e5-8aa2-076788f2c6cb.png)

○　We're sorry にならずに、正常にインポート結果が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/12069932/7519d918-b097-11e5-8375-ce1076486829.png)

### 検索、表示

検索結果が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/12069934/93a511a4-b097-11e5-94de-653713db4d6c.png)

We're sorry にならずに、正常に表示される
![image](https://cloud.githubusercontent.com/assets/1328499/12069935/a24a4062-b097-11e5-98bf-01c5dde9e431.png)

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 237a2e5)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_subject (0.2.0.beta.1 237251b)
