### ISSUE TITLE
「システム全体の設定の編集」画面の「色」に[追加]、[削除]リンクがついている→[[追加][削除]はいらない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1098]
- [ ] マニュアル修正（スクリーンショットの撮り直し？） #1248 

「システム全体の設定の編集」画面に[追加]　[削除]リンクがある
http://localhost:8080/library_groups/1/edit
![image](https://cloud.githubusercontent.com/assets/1328499/12071070/185ae926-b0db-11e5-9b65-2f77ccf4e21d.png)

現在：
[追加]リンクをクリックすると
![image](https://cloud.githubusercontent.com/assets/1328499/12071060/78ed1cce-b0da-11e5-84dd-7e72c6fe21f8.png)

空のフォームが追加される（グレーのところは修正できない）、[削除]リンクをクリックすると
![image](https://cloud.githubusercontent.com/assets/1328499/12071061/8196a2be-b0da-11e5-945d-a96278873386.png)

本当に実行しますか、OK、とすると、
![image](https://cloud.githubusercontent.com/assets/1328499/12071075/70a4fb62-b0db-11e5-91ae-034cb714ee15.png)

フォームが削除される
![image](https://cloud.githubusercontent.com/assets/1328499/12071077/8eeec882-b0db-11e5-8985-2b42068747f5.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.2.0.beta.1 9ebdf6f)
- enju_circulation (0.2.0.beta.1 7994f3b)
- enju_event (0.2.0.beta.1 1483293)
- enju_leaf (1.2.0.beta.1 ac6500e)
- enju_library (0.2.0.beta.1 d6e53e6)
- enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
- enju_message (0.2.0.beta.1 498ec1d)
- enju_ndl (0.2.0.beta.1 ce80288)
- enju_purchase_request (0.2.0.beta.1 ab17d9f)
- enju_subject (0.2.0.beta.1 237251b)

参考： 1.1系
![image](https://cloud.githubusercontent.com/assets/1328499/12071066/e4b8b97c-b0da-11e5-9c35-5700dd958dba.png)

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
削除も追加もなくなっていることを確認しました
クローズします


![next l enju leaf 1](https://cloud.githubusercontent.com/assets/1328499/26782554/1eaec916-4a2f-11e7-8b42-fbdefbfd3e04.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
