### ISSUE TITLE
Solr で漢字の異体字セレクターを無視する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1101]
検索の際にいわゆる異体字セレクター（variation selector）を無視する必要があります。
#904 と関係しますが，独立しているのでこちらのみ先行実装することも可能です。
## 異体字セレクターについて

「葛」（くず）という字は左下が「ヒ」になった字体と「兦」になった字体がありますが，Unicode ではそれらを **包摂** して一つのコードポイント U+845B を与えています。
（奈良県葛城（かつらぎ）市は「ヒ」型，東京都葛飾区は「兦」型を通常使っているようです）

異体字セレクターは，包摂によって区別されなくなった細かな字体・字形の差を区別する仕組みで，親文字の直後に配置し，どの字体かを指定する特殊な〈文字〉です。

漢字の異体字セレクターは特に IVS: Ideographic Variation Selector と呼ばれ，コードポイントは U+E0100～U+E01EF です。
ここでは IVS のみを考えることにします。

たとえば，U+845B U+E0102 だと「ヒ」型，U+845B U+E0103 だと「兦」型になります。
ただし，表示するシステムとフォントがいずれも IVS に対応している必要があります。（主要ブラウザーは IE も含めて対応しており，これと IPAmj明朝の組み合わせなら上記の例は区別して表示される）

ところで厄介なことに，一つの字体がルーツの違いにより別のセレクターとして重複登録されていることがあります。
「葛」の場合，「ヒ」型と「兦」型は，「Adobe-Japan1」では U+E0100 と U+E0101 を使いますが， 「汎用電子情報交換環境整備プログラム」では U+E0102 と U+E0103 を使います。
両者に相互運用性は無く，IPAmj明朝で Adobe-Japan1 のほうを使っても無視され，同じ字体で表示されます。
悪夢としか思えない技術です。

いずれにしても，検索に際しては IVS を単純に削除するのがよさそうです。

なお，親文字と Ideographic Variation Selector の並びのことを Ideographic Variation Sequence といい，こちらも IVS と略します。
## Solr での対応
#904 と同じ考え方でやってみたらうまくいきました。つまり，すべての IVS を空文字列にマッピングします。

そのようなマッピングファイルを生成する Ruby スクリプトを貼っておきます。

``` rb
filename = "neglect-ideographic-variation-selectors.txt"

open filename, "w:utf-8" do |f|
  f.puts <<-EOT
# Neglect Ideographic Variation Selectors (U+E0100..U+E01EF)
#
# [CAUTION]
# Do not edit this file manually.
# Left-hand-side strings are not empty.
  EOT
  f.puts
  (0xE0100..0xE01EF).each do |c|
    f.puts "# U+%X" % c
    f.puts %|"#{c.chr(Encoding::UTF_8)}"=>""|
  end
end
```

マッピングファイルでなく生成スクリプトを提出するのは，正しいことが確認できるようにするためです。
マッピングファイル自体は目で見ても分かりません。（IVS が BMP 外なので，\uXXXX の形式で書けない）
## 動作検証

まず，『葛城市歴史読本』とか『目で見る葛飾区の100年』とかを NDL から持ってきて，それぞれの「葛」の後ろにそれぞれの IVS を入れました。

次に，IVS 無しの「葛城市」「葛飾区」で検索してヒットしないこと，それぞれの IVS を入れた検索語で検索すると，それぞれがヒットすることを確認しました。

次に，上記のマッピングファイルをセットし，Enju を再起動しました。

それから，それぞれの書誌情報を更新しました。（書誌情報を更新しなくても Solr のインデクシングをやり直す方法って無いんでしょうか？）

この状態で，IVS ありと IVS 無しの「葛城市」「葛飾区」で検索し，あっても無くてもそれぞれがヒットすることを確認しました。
## 必要性について

ある種の申込フォームをいくつも運用してきた経験からいうと，ウェブフォームに IVS 付きの文字が入ってくるのは「意外に多い」という印象です。
ワープロなどからコピペで持ってきたときに付いてくるのかもしれません。

地域資料など自館作成の書誌情報はワープロや Excel などからのコピペが多いでしょうから，書誌情報自体に IVS が含まれる可能性もあります。
## よその OPAC ではどうか

NDL Search は IVS の処理を行っていないらしく，IVS 付きで検索すると何もヒットしません。

いくつかの公共図書館で試しましたが，IVS の処理を行っているシステムは見つけられませんでした。

Books.or.jp はそもそも BMP 外の文字を含めて検索するとシステムがエラーを起こすので，当然 IVS 付きの検索はエラーになります。

Unicode で異体字セレクターが提案されたとき，「検索時は無視すりゃいいんだから」って話だったのに！
ぷんぷん！

**Comment by masao** [comment]
ありがとうございます。ちなみに本筋のご指摘とは関係ないのですが、Solrの再インデックスは enju ディレクトリ上で以下のコマンドを実行することにより、すべての情報を再インデックスします：
```
bundle exec rake sunspot:reindex RAILS_ENV=production
```

**Comment by scivola** [comment]
ありがとうございます。その方法で再インデックスしたら反映されました。
この手順はインストールマニュアル第6章に加筆する必要があると思いますので，別 issue 立てました。
https://github.com/next-l/manual/issues/68

**Comment by yegusa** [comment]
1年以上たちましたし、こちら問題なさそうなので、クローズします。
