### ISSUE TITLE
Enju Leaf 1.1.0 32 bit 版の VM を

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1102]
Enju Leaf 1.1.0 64 bit 版 の VM が提供されていますが，もし可能なら 32 bit 版も出してもらえないでしょうか。

64 bit 版だと「[VT機能が無効になっているというメッセージ](https://next-l.github.io/manual/1.1/enju_install_vm_11.html#q-vt)」が出ます。
そこで，「BIOS のセットアップ画面」をかなり丹念に調べたのですが，「Virtualization Technology 機能を有効に」する設定はありませんでした。
仕方ないので，手許では古い Enju Leaf で動作確認をしています。

HP Compaq Elite 8300 USDT
Intel Core i5-3470S
64 ビットオペレーティングシステム
Windows 7 Professional Service Pack 1

**Comment by yegusa** [comment]
> 仕方ないので，手許では古い Enju Leaf で動作確認をしています。

ちなみに　↑はどの仮想マシンを使われたのですか?

**Comment by scivola** [comment]
VM の名前が

enju_leaf_vm_default_1440173177228_21425

となっているのですが，これで分かりますか？

そして，起動して Enju の画面を見ると，下部に

Next-L Enju Leaf 1.1.0.rc21 + Next-L Enju Flower 0.1.0.pre23

とありました。

**Comment by yegusa** [comment]
直接的な答えではないのですが、新しいEnjuを試したいということでしたら
すでに動いてるenjuをupdateするという方法もあるかと。

#### 1. 念のためバックアップ（クローン）を作成

やり方：　参照： https://next-l.github.io/manual/1.1/enju_install_vm_9.html#section9-1 ）

アップデートは、作成したクローンをつかって試してみると良いと思います。
アップデートに失敗してうごかなくなったとしても安心です。

#### 2. アップデート

アップデート方法は、以下を参照ください。

https://github.com/next-l/enju_leaf/wiki/Update

の「updating to 1.1」の章を参照すればよいかとおもいます（お使いのが 1.1.0.rc21なので）。

----
> enju_leaf_vm_default_1440173177228_21425

仮想マシンでそれに相当するものがみあたらず。。。

すでに仮想マシンが使えているなら、
> 64 bit 版だと「VT機能が無効になっているというメッセージ」が出ます。

このメッセージでないはずなんですけどね。。。

**Comment by scivola** [comment]
ありがとうございました。その手順で Enju Leaf 1.1.2 に上げることができました。

ただ，アップデート手順でちょっと気になることが。

「updating to 1.1」に従って，

```bsh
bundle update
```

までやると，現時点では 1.1.2 まで行きます。
それはいいのですが，「updating to 1.1.2」をどの段階でやるのかが，Rails を知ってる人でないと分からないと思います。
たぶん，config/initializers/assets.rb を加工した後で

```bsh
bundle exec rake assets:precompile
```

をしなければいけないのだと思うのですが，いかがでしょうか。

---

> 仮想マシンでそれに相当するものがみあたらず。。。

どこに置いてあったのかもはや分かりません。

> このメッセージでないはずなんですけどね。。。

記憶が正しければ，同じ 1.1.0.rc21 でも，32 bit 版だと出なくて 64 bit 版だと出るのだったと記憶しています。

**Comment by yegusa** [comment]
@nabeta or @masao さん当たり、

> 「updating to 1.1」に従って，
> 
> bundle update
> までやると，現時点では 1.1.2 まで行きます。

↑　についてフォローよろしく。

別 issue にしたほうがいいかも。

**Comment by nabeta** [comment]
32bit版の仮想マシンを作成しました。64bit版と同様、Ubuntu 14.04を使用しています。
http://www.next-l.jp/?page=VM

**Comment by scivola** [comment]
ありがとうございました。32 bit 版の動作を確認しましたので，クローズします。

Enju を 1.1.x に上げる方法の記述については，別 issue #1104 にしました。

**Comment by nabeta** [comment]
@scivola ちなみに、BIOSの設定を検索したところ以下のページが見つかりましたが、この方法を試されましたでしょうか？
http://h20564.www2.hp.com/hpsc/doc/public/display?docId=emr_na-c03544192&lang=ja&cc=JP

**Comment by yegusa** [comment]
参考：

> enju_leaf_vm_default_1440173177228_21425

1440173177228　がunix時間な気がするので、
ということは、2015年8月25日に作成した仮想マシンみたいですね。

**Comment by scivola** [comment]
@nabeta さん，それに従って BIOS 設定画面を探したら仮想化技術の設定項目が見つかりました。
まさかセキュリティーのところにあったとは。
関係なさそうなところも含め，全設定画面を端から順に何度も丁寧に見たつもりだったのですが，見落としてたんですね。

で，これを有効化すると 64 bit 版 VM も動きました。お騒がせしました。
