### ISSUE TITLE
400 Bad Request Request / Header Or Cookie Too Large

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1103]
- [x] マニュアル修正 #1066 （修正必要なし）

VirtualBox で Enju 1.1.2 を動かしていると，しばしば

> 400 Bad Request Request
> Header Or Cookie Too Large

が出ます。サーバー側で出ているエラーです。クッキー が大きすぎるようです。
そこで，Firefox で localhost の _enju_session クッキーを観察しながら Enju を操作してどの時点でどうなるかを調べました。
すると，通常 500 バイトくらいのクッキーが，2 キロバイトを越えた直後にどこかのページにアクセスするとこのエラーが出ることが分かりました。
タイミングとしては，「条件を詳しく指定して検索」を実行した直後にクッキーが大きくなるように思われました。
クッキーを削除すると正常に表示できますが，すぐにまたエラーが出るようになります。

気の付いたこと：
- enju.next-l.jp や dev.next-l.jp ではこのような現象に遭ったことがない
- VirtualBox の 1.1.0.rc21 でもそうだったし，そこから 1.1.2 にアップデートしても同じ
- 単純なページ遷移では起こらない気がする。
- 「条件を詳しく指定して検索」の直後にクッキーが巨大化している気がする。
- Firefox 43.0.4 で動作確認。
- VirtualBox でのみ遭遇したということは Nginx の設定ではないかという気がする。

_enju_session のクッキーが 2 キロバイトを超えること自体は正常なのでしょうか？

**Comment by nabeta** [comment]
enju.next-l.jp, dev.next-l.jp とも、セッションをCookieに保存しています。ちなみにセッションの保存先の設定は config/initializers/session_store.rb にあります。

```
Rails.application.config.session_store :cookie_store, key: '_enju_leaf_11_session'
```

セッションがそこまで大きくなる状況はちょっと思い当たらないのですが、中身になにが入っているかはわかりますでしょうか。

**Comment by scivola** [comment]
異常なとき（次のリクエストで 400 が出るケース）の cookie の中身は，長さが長いだけで，見た目は正常なときと変わらず，英数字などがランダムに並んだようなものです。
異常なときの長さですが，毎回微妙に違うものの，2 kB を少し越えたあたり，ということは共通しています。つまり（正確に覚えていませんが）2091 字とかのあたりです。

config/initializers/session_store.rb は enju_leaf のリポジトリーには見当たらないですが，どこを見ればいいですか？

それと，件の環境では，cookie のキーは _enju_leaf_11_session ではなく _enju_session でした。

**Comment by nabeta** [comment]
config/initializers/session_store.rb はRailsアプリケーションを作成したとき、つまりrails newを実行したときに自動的に作成されるファイルです。
Cookieのキーはrails newを実行したときに指定したアプリケーション名になります。たとえば、 rails new enju123 としたとき、_enju123_session となります。

**Comment by nabeta** [comment]
あと、enju.next-l.jpはApacheで、dev.next-l.jpはnginxで動作しています。

**Comment by nabeta** [comment]
根本的な解決ではないのですが、セッションをCookie以外に保存するという手もあります。以下はmemcachedとdalli（memcachedのクライアント）を使用する例です。
https://github.com/petergoldstein/dalli#usage-with-rails-3x-and-4x

```
Rails.application.config.session_store ActionDispatch::Session::CacheStore, :expire_after => 20.minutes
```

**Comment by masao** [comment]
本件、Enju 1.1系でも1.2系でも再現するようです。
Enjuは検索時に検索結果に戻る等の場合に備え、クエリをセッションに保存しますので、クエリー情報が長くなる場合、クッキーサイズを肥大化させてしまうようです。現在のデモサーバには図書館が12個つくられていますから、詳細検索から図書館をすべて選択して検索すると、必ずRailsエラーになるようです。

手元の仮想マシン（developmentモード）でも、図書館を多めに作ると以下のようにエラーになります：
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/12216891/647c570a-b733-11e5-969e-5bf21f0982bd.png)

**Comment by scivola** [comment]
> config/initializers/session_store.rb はRailsアプリケーションを作成したとき、つまりrails newを実行したときに自動的に作成されるファイルです。リポジトリの中にはありません。

リポジトリーに何が入っているかについて，基本的なところで勘違いしていました。てっきり，rails new したあとのファイル群にいろいろ追加・修正をしていったものが入っているのかと。
VirtualBox 版しか動かしたことがないので，ゼロからインストールしないと理解できなさそう。
とはいえ Windows では動かせないし。

いずれにしても cookie が肥大化した原因が分かってよかったです。クエリーをセッションに入れないようにすればいいんですね。

**Comment by masao** [comment]
開発ワークショップのなかで確認したところ、セッション内へのパラメータ保存は「検索結果の一覧に戻る」リンクの生成にのみ使われており、これ以外には使われていないため、この機能をオフにすればよさそうです。

cf. https://github.com/next-l/enju_biblio/blob/1.2/app/helpers/manifestations_helper.rb#L16

**Comment by nabeta** [comment]
検索実行時のパラメータを、オブジェクトのままCookieに保存していたのをやめて、URL文字列をSessionStorageに保存するようにしました。

**Comment by masao** [comment]
手元で20個くらい図書館を作成して詳細検索を試したところエラーにならなくなりましたので、ひとまずクローズします。
