### ISSUE TITLE
1.1.2 へのアップデート方法の説明を修正する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1104]
#1102 より。

Wiki の「[アップデート方法](https://github.com/next-l/enju_leaf/wiki/Update)」について，「updating to 1.1.2」の記述に修正の必要があると思います。

まず，この項が「updating to 1.1」とは独立になっていますが，「updating to 1.1」の手順を踏むと現時点で 1.1.2 までいっちゃいます。「updating to 1.1.2」は「updating to 1.1」の中の節であるべきではないでしょうか。

それから，config/initializers/assets.rb の編集をどのタイミングで行うのか書く必要があると思います。
プリコンパイルするアセットを追加しているので，たぶん

``` shell
$ bundle exec rake assets:precompile
```

の前に行うのだと思いますが。
また，1.1.x から 1.1.2 に上げるだけのときも，assets.rb を編集した後でこれ（と Enju の再起動）をやらないといけないことを書かなくてはならないと思います。

**Comment by masao** [comment]
ご指摘ありがとうございます。開発WSで議論しました。
バージョン間の関係が混乱しているようなので、セクションタイトルの記述を修正しました。

なお、Gem更新の問題上、特定のバージョン間の更新手順（rc18 => 1.1.1）をするだけでもその時点での最新版（1.1.2）まで更新されてしまいます。
これを個別に更新手順として書き残すのは大変なので、そこは目をつむっていただいて、その時点の最新版まで必ず更新していただくことを前提としましょう。

asset:precompileの手順も追記しました。

**Comment by yegusa** [comment]
1年以上たちましたし、こちらも、特に問題なさそうなので、いったんクローズします。
