### ISSUE TITLE
雑誌の各号単位の書誌情報に入力した説明情報が検索でヒットしない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1105]
- [x] マニュアル修正 #1191 （修正の必要なし　記述ないので）

雑誌の各号単位の書誌情報内の説明フィールドに、雑誌の各号単位の情報説明を追記しておいても、それが簡易検索のキーワードからヒットしません。

手元の環境でも再現しますし、デモサーバでも以下のように入力された雑誌の各号単位の書誌情報
http://enju.next-l.jp/manifestations/12000
に入れられた文字列「enju」をトップから検索しても、ヒットがありません。
http://enju.next-l.jp/manifestations?query=enju

以下のように、雑誌ではない普通の単行本の書誌情報の説明フィールドでしたらヒットします：
http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=%E8%A8%98%E6%86%B6%E3%81%AE%E3%81%8B%E3%81%91%E3%82%89&commit=%E6%A4%9C%E7%B4%A2

インデックスまたは検索対応時のバグではないかと思われます。

**Comment by masao** [comment]
雑誌書誌の検索時に、各号単位の書誌情報の以下のフィールドをヒット対象に加えるように修正しました。

* 全文情報
* 注記
* 説明
* 著者
* 出版者
* 訳者
* 責任表示

**Comment by yegusa** [comment]
* 「訳者」ってどこでいれられますか？　見当たりません。
* 「全文情報」ってどれですか？ファイルを添付した時のファイルの中身？少なくとも、ファイルを添付で、添付したファイルの中身では検索できませんでした。

少なくとも、以下は検索できることを確認しました。

* 注記
* 説明
* 著者
* 出版者
* 責任表示

「ばばば」検索してヒット
![image](https://cloud.githubusercontent.com/assets/1328499/18813225/ce050f5c-832d-11e6-8a35-2fc177520e14.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813233/fdf1c20a-832d-11e6-8a5f-feeef19ff343.png)

×「オープン」でヒットしない（添付ファイル中に　オープンがある）
![image](https://cloud.githubusercontent.com/assets/1328499/18813246/8bcc3056-832e-11e6-8919-1965c10025ce.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813240/3c76b044-832e-11e6-8d01-5fd8772dca47.png)

**Comment by yegusa** [comment]
すみません、著者もだめだったかも。もう一回、ひとつづつ確かめてみますね。

**Comment by masao** [comment]
添付ファイルの全文検索は #556 の設定をしておく必要がありますね。

**Comment by nabeta** [comment]
著者、協力者・編者、全文の検索はそれぞれ別issueとして確認。

**Comment by yegusa** [comment]
> 著者、協力者・編者、全文の検索はそれぞれ別issueとして確認。

それぞれ、別 issue として登録しておきました。

**Comment by yegusa** [comment]
（「編集」ではできない件、いくつかの項目では別issueにしましたが、「責任表示」「出版者」は作っていないですが、まあ、いいですよね）
