### ISSUE TITLE
雑誌の各号単位の情報に入力されたISBNが表示されない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1106]
- [ ] マニュアル #1066 

「ず・ぼん」
http://enju.next-l.jp/manifestations/12000 のようにISBNも持っている書誌情報ですが、ISBNを入力しても詳細表示画面に出てきません。
確認や同定に不便ですので、表示したほうがよいと思います。

**Comment by masao** [comment]
修正を確認したのでクローズします。
![15 next l enju leaf](https://cloud.githubusercontent.com/assets/38825/13378585/3336bf22-de4e-11e5-88b1-14deb68b7462.png)

**Comment by yegusa** [comment]
当該ISBNが表示されるようなスクリーンショットや説明がマニュアルになかったので特に修正の必要ないことを確認済み　ref. 5-2 個々の雑誌を登録する https://next-l.github.io/manual/1.2/enju_operation_5.html#section5-2
