### ISSUE TITLE
「ISBNインポートのリクエストの新規作成」の入力欄が狭い

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1107]
「ISBNインポートのリクエストの新規作成」
http://enju.next-l.jp/import_requests/new
の ISBN 入力欄が狭く，13 桁 ISBN が入りきりません。

**Comment by nabeta** [comment]
幅を20emとしました。
http://dev.next-l.jp/import_requests/new

**Comment by scivola** [comment]
確認しました。

**Comment by yegusa** [comment]
記録のため追記：

1.1.2時点
http://enju.next-l.jp/import_requests/new
![image](https://cloud.githubusercontent.com/assets/1328499/12553922/56df7f82-c3bd-11e5-89e1-8967e7293afc.png)
enju_biblio: 0.1.2
enju_circulation: 0.1.1
enju_event: 0.1.18
enju_flower: 0.1.1
enju_leaf: 1.1.2
enju_library: 0.1.1
enju_manifestation_viewer: 0.1.1
enju_message: 0.1.15
enju_ndl: 0.1.1
enju_purchase_request: 0.1.1
enju_subject: 0.1.1

修正後：
![image](https://cloud.githubusercontent.com/assets/1328499/12553959/89654f54-c3bd-11e5-84d5-fe16ffcb46a4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 47e3a3a)
  * enju_circulation (0.2.0.beta.1 d2bbdb9)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 25c8ca5)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 b797995)
