### ISSUE TITLE
(当面の暫定で)フッターに画像を含む文章を書く方法，画像をアップロードする場所などについてマニュアルに記載して欲しい

### ISSUE THREAD

**Issue by ineku** [next-l/enju_leaf#1118]
- [x] マニュアル #1066

追記：
画像の置き場については #1114 でやることにします。

**Comment by scivola** [comment]
フッターのカスタマイズ方法自体は  #987 で済んでいるみたいですね。
ん？　マニュアルのどこに書いてあるのか見つけられませんでした。
画面のカスタマイズは [インストールマニュアル第10章](https://next-l.github.io/manual/1.1/enju_install_vm_10.html) にいくつか書かれていますが，フッターについては無いですね。

テンプレート（*.erb および *.slim）の書き方の一般論は，いずれマニュアルに取り込まれると思いますが，https://github.com/next-l/enju_leaf/issues/1024#issuecomment-165978231 に少し書かせていただきました。

**Comment by yegusa** [comment]
フッターの変え方については、以下に書いています。
（わかりにくい場所ですみません。）

設定マニュアル：3-1-3 フッタの内容を変更する
https://next-l.github.io/manual/1.1/enju_setup_3.html#sction3-1-3

**Comment by scivola** [comment]
分かりました。
ビューのカスタマイズは一箇所に集めるといいと思うので，別 issue 立てました。
https://github.com/next-l/manual/issues/70

**Comment by yegusa** [comment]
画像ファイルをどこに置けばよいかは、マニュアルにないですね。
どこに置けばいいんでしょうかね。

**Comment by yegusa** [comment]
考えてみたら、これ、1.1系の話ですね。
1.2系であれば、画像はともかくフッターは修正できる（ようになるはずな）ので（参照： #988 ）。

1.1系のマニュアルの修正もしておきました。

**Comment by yegusa** [comment]
1.1系の場合：
* [10-3 フッターをカスタマイズする](http://next-l.github.io/manual/1.1/enju_install_vm_10.html#section10-3)
* [10-2 トップ画面やヘルプなどに表示する画像を置く](http://next-l.github.io/manual/1.1/enju_install_vm_10.html#section10-2)

1.2系の場合：
* [3-1 システム全体の設定をする](http://localhost:8080/~vagrant/manual/_site/1.2/enju_setup_3.html#section3-1)
* [10-5 トップ画面やヘルプなどに表示する画像を置く](http://next-l.github.io/manual/1.2/enju_install_vm_10.html#section10-5)

**Comment by yegusa** [comment]
マニュアルを修正したので、どなたかマニュアルを確認してクローズしてください。

**Comment by masao** [comment]
確認しましたのでクローズします。
