### ISSUE TITLE
書誌情報検索の結果を適合度順ソートしたい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1121]
- [ ] マニュアル修正 #1066 

Solrで関連度スコアがとれるはずなので、そのスコア順での表示順序変更もサポートできるとうれしい。

**Comment by nabeta** [comment]
Solrのスコア順でのソートを追加しました。ラベルなどは適当に変更してください。
開発サーバにも反映済みです。

Sunspotでのスコア順でのソート方法は、以下を参照してください。
https://github.com/sunspot/sunspot#ordering

**Comment by masao** [comment]
適合度ソートに関しては逆順のソートは要らない気がしますね。

**Comment by yegusa** [comment]
残り作業：
「スコアの適合度逆順」を削除する

![image](https://cloud.githubusercontent.com/assets/1328499/13250884/f4e15480-da6f-11e5-9296-d32979542f6f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a8fc822)
  * enju_circulation (0.2.0.beta.1 2a3c92e)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 caf679d)
  * enju_library (0.2.0.beta.1 1805417)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 9f89fe6)

**Comment by masao** [comment]
スコアの逆順をはずすよう修正しました。確認ください。

**Comment by yegusa** [comment]
現在のステータスメモ：　確認してクローズするだけ（江草でもできそう）

**Comment by yegusa** [comment]
「スコアの適合度逆順」がない（スコアの適合度順のみある）ことを確認しましたので、クローズします。
マニュアルは後で書きます。

![image](https://cloud.githubusercontent.com/assets/1328499/14765099/d37f9244-0a0c-11e6-8fb5-ef3adda12a3c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a366e5d)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 d5e2c12)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

（スクリーンショットつけてないですが、ソート項目全部ひととおりやってみて、だいたいできているようにみえるのを確認もした）

**Comment by yegusa** [comment]
書誌情報検索の結果を適合度順ソート（昇順のみ）ができることを追記
該当箇所：利用者マニュアル 1章5節
https://next-l.github.io/manual/1.2/enju_user_1.html#section1-5

「検索結果一覧の表示順序のソート方法を変更することができます。 

書誌作成日の新しさ、出版日の新しさ、適合度（昇順のみ）、タイトルの五十音で、 ソート方法を変更することができます。」

としました
