### ISSUE TITLE
1.2.0.beta を新規インストールしようとしてbundle -j4のところでエラーがでてできない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1126]
手元の仮想マシン（enju_leaf_vm_default_1447225364001_72894）で、
新規インストールをためしてみました。

https://github.com/next-l/enju_leaf/wiki/Install

の手順の通りにすすめて、
bundle -j4のところで以下のエラーになりできません。

```sh
vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ bundle -j4
Fetching git://github.com/next-l/enju_leaf.git
Fetching git://github.com/next-l/enju_biblio.git
Fetching git://github.com/next-l/enju_library.git
Fetching git://github.com/next-l/enju_manifestation_viewer.git
Fetching git://github.com/next-l/enju_ndl.git
Fetching git://github.com/next-l/enju_circulation.git
Fetching git://github.com/next-l/enju_subject.git
Fetching git://github.com/next-l/enju_message.git
Fetching git://github.com/next-l/enju_event.git
Fetching gem metadata from https://rubygems.org/..........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies....
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    enju_leaf (~> 1.2.0.beta.1) ruby depends on
      rails (~> 4.2.5) ruby

    rails (= 4.2.4) ruby

```

**Comment by scivola** [comment]
そのバージョンの enju_leaf が [rails 4.2.5 を要求している](https://github.com/next-l/enju_leaf/blob/master/enju_leaf.gemspec#L22) のに，rails 4.2.4 が入ってるってことかな。
どうすればいいんだろう？
Gemfile.lock をいったん消してみるとどうなりますか。

**Comment by yegusa** [comment]
```sh

vagrant@vagrant-ubuntu-trusty-64:~/your_enju$ diff Gemfile.old Gemfile
5c5
< gem 'rails', '4.2.4'
---
> gem 'rails', '4.2.5'

```

こんなかんじで、4.2.4となっていたところを 4.2.5を変えるとできるようになりました

なので、デフォルトのGemifleが ちゃんと 4.2.5になるように修正する必要があると思います。

**Comment by nabeta** [comment]
rails new で生成されるGemfileでのrailsのバージョンは、 rails new を実行したときにインストールされているrailsのバージョンになります。また、rails new でのGemfileの生成はRailsが行うものであり、Enjuで行われているものではありません。
Wikiの例はrailsを新規でインストールする例ですが、すでにrailsがインストール済みの場合、まず gem install rails でrailsをアップデートすることになります。

**Comment by masao** [comment]
Enju側をRails 4.2.5以上に固定しているのはなにか理由がありましたっけ？

**Comment by scivola** [comment]
enju_leaf 側で Rails のバージョンを制限しているのであれば，開発者向けインストールマニュアルに以下の加筆修正を施すとよいのではないでしょうか。

- enju_leaf が必要とする Rails のバージョンを確認する手段を書く（例：`~> 4.2.5`）
- 「Railsのインストール」を，Rails のバージョンを指定するやり方に変更<br>（`gem install rails -v "~> 4.2.5"`）
- メッセージから実際にインストールされた Rails のバージョンを知る方法を書く
- 「Enju Leaf本体のインストール」を，Rails のバージョンを指定するやり方に変更<br>（`rails _4.2.6_ new 云々`）

参考：「`~> 4.2.5`」は「4.2.5 以上，4.3 未満」の意。

**Comment by yegusa** [comment]
あー、私がこのissueを登録したときにどうして最新のrailsになっていないかはわかりました。

https://github.com/next-l/enju_leaf/wiki/Install

の手順で、 

 # 必要に応じてsudoを追加
 $ gem install rails

のときに、 sudo をつけなかったので、rails のインストールができていなかった。
しかし、わたしはうまくインストールできていないことに気づいていなかった。
そのため、このような状況になったみたいです。
railsインストールが失敗したときのメッセージや、成功したときのメッセージを入れておいたほうがいいですかねえ
（でもそうするとマニュアルがなんかながくなっちゃいますよねえ）

とりあえず、解決したのでクローズしますが、

> Enju側をRails 4.2.5以上に固定しているのはなにか理由がありましたっけ？

↑については別のissueを立てることにします。
