### ISSUE TITLE
(当面の暫定で)ヘッダーに画像を含む文章を書く方法，画像をアップロードする場所などについてマニュアルに記載して欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1131]
- [x] マニュアル #1066 

(当面の暫定で)フッターに画像を含む文章を書く方法，画像をアップロードする場所などについてマニュアルに記載して欲しい #1118

のヘッダー版です。

* 画像の置き方、参照の仕方については、 #1144 を参照してください。

**Comment by yegusa** [comment]
関連：　ヘッダーも編集できるようにして欲しい #1112

**Comment by yegusa** [comment]
たとえば、バナー画像： http://enju.next-l.jp/assets/logo.png をタイトルの代わりに張りたいとしたら、

https://raw.githubusercontent.com/next-l/enju_leaf/1.2/app/views/page/_header.html.erb の

```
<h1 class="resource_title"><%= link_to LibraryGroup.system_name(@locale), root_path, title: LibraryGroup.system_name(@locale) %></h1>
```

↑をかえればよいのだとおもうのだけど、
どう変えればよいのか教えてくれるとマニュアルがかけそうです。

**Comment by yegusa** [comment]
バナーの貼り方以外はマニュアルにかきました。
参照： http://next-l.github.io/manual/1.2/enju_install_vm_10.html#sction10-3

**Comment by masao** [comment]
先に質問のあった箇所は下記のような記述で書き換えられます：
```html
      <h1><%= link_to image_tag('custom/logo.png'), root_path %></h1>
```

当該記述でロゴ画像に差し替えた例：
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/13378663/b7055b90-de50-11e5-9039-e0cbbb8b10d3.png)

**Comment by scivola** [comment]
`div#header_left` が `float: left` になっているので，ある程度高さのある画像だとメニューに重なっちゃいますね。

**Comment by yegusa** [comment]
現在のステータスメモ：

- 確かめてクローズするだけ（江草でもできそう）

**Comment by yegusa** [comment]
画像が、でかすぎるとはみ出してしまうんですね。
640x65px のサイズの画像だとちょうどよいようです。

確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/14058820/4e6fbf0a-f370-11e5-8388-b3051c1c4ba0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 f8ccc4c)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 8243b36)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

**Comment by yegusa** [comment]
まあ、とりあえず、 @scivola さんの指摘は、高さが小さ目の画像を作ってもらうことで回避するということで、いったんはクローズします。

マニュアルも書きました。

10-6 ヘッダーをカスタマイズする
http://next-l.github.io/manual/1.2/enju_install_vm_10.html#section10-6

**Comment by scivola** [comment]
クローズされたので本来別 issue を立てるべきかもしれませんが，とりあえずここにメモします。

大きなヘッダー画像を置くとマズいのは，`float: left` だからというよりも，div#library_system_name と div#header_left のサイズががっつり固定されているからでした（下記参照）。

https://github.com/next-l/enju_leaf/blob/master/app/assets/stylesheets/enju.css#L55
https://github.com/next-l/enju_leaf/blob/master/app/assets/stylesheets/enju.css#L65

「天地 65px の画像がちょうどよい」というのは，div#header_left の height が 65px だからでしょう。

とりあえず，両者の height を auto にすればメニューと重ならなくなるようです。
（ここまで調べて力尽きました）
