### ISSUE TITLE
検索結果一覧のソートの「次の項目で並べ替える:」ラベルを消して、右寄せにする（英語対応のため）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1135]
- [ ] 開発
- [ ] 確認
- [ ] マニュアル #1066 

#570 からの派生で、英語のインターフェースとしてはバグ風なのでunder developmentにさせてください。

現在は、英語のほうはちょっと変になってしまっています（Sort byがちょっと変な感じ）
なので、いっそのことラベルをとってしまうといいのじゃないかと。
ラベルがなくても通じるし、そうすれば英語でも変じゃないので。

表示順序を変えることのほうが頻繁にあって、表示ボタンのとなりにあるのが自然に思うから
表示順序を変えるメニューと「表示」ボタンをくっつけたい＝「10件ずつ表示」は、左になる
というのも理由にあります。

現在：日本語
![image](https://cloud.githubusercontent.com/assets/1328499/12555100/dfa2791e-c3c2-11e5-9120-aceedde56dc4.png)

現在：英語
![image](https://cloud.githubusercontent.com/assets/1328499/12555125/f747bb74-c3c2-11e5-8360-4c9cec0028cb.png)

提案：日本語
![image](https://cloud.githubusercontent.com/assets/1328499/12555236/8411f2f4-c3c3-11e5-82f1-ead774c4c5ae.png)

提案：英語
![image](https://cloud.githubusercontent.com/assets/1328499/12555191/4db273f0-c3c3-11e5-9e41-faac94ce2ae0.png)

※提案のメニューのレイアウト（右寄せ）やラベルなしの方式は、CiNiiのまねっこです。

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
```sh
$ cd enju
$ bundle update
$ rake assets:precompile
$ sudo restart enju_leaf
```

して確かめました。できることを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12702313/c86d205a-c868-11e5-88c6-388245106da3.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12702314/e661de66-c868-11e5-800d-acd94ccc61e6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e7e1ab8)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 5b409a6)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)
