### ISSUE TITLE
新規インストールのときにrailsが最新でないと動かない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1137]
#1126 からの派生です

1.2系の新規インストールのときは、最新のrailsでないと動かないようです。
詳細は #1126 を参照。

最新のrails以外でも動くようにする必要があるかと思います。

すくなくとも最新のrails以外でも動かす方法をインストールマニュアルに書く必要があると思います。

**Comment by nabeta** [comment]
以前のバージョンまでテストできないので、最新のものだけで動作するようにしたいのですが、いかがでしょうか。

**Comment by masao** [comment]
以前に合意したRoadmapと話が変わっている気がします。Roadmapを変更したいという提案でしょうか。

さらに、提案は具体的にお願いします。最新の系列という意味なら分かりますが、最新のものだけというのは意味がないと思います。Rails5が出たら、Rails4のサポートを即座に切るという意味ですか？それは現実的でないと思います。
リリースされてからテストできるようになるまでに時間が必要ですし、最新のみというのは逆に難しいのでは？逆に言うと、最新以外の古いバージョンは開発の過程でテストをかけられるのではないでしょうか。

**Comment by nabeta** [comment]
> Rails5が出たら、Rails4のサポートを即座に切るという意味ですか？

いいえ、そうではありません。最新のものというのは、たとえば4.1系、4.2系の最新という意味です。

**Comment by masao** [comment]
4.2系で動作するようにバージョンチェックを緩和する（第46回開発ワークショップでの議論より）。

**Comment by nabeta** [comment]
4.2.5以上だったのを4.2以上としました。

**Comment by yegusa** [comment]
確かめるために、新規インストールして、Gemfileを修正して、 rails 4.2.4 を指定してやってみました。

インストールできました。

のでクローズします。

**Comment by yegusa** [comment]
ちなみに、

　#942 の以下をやってインストールできたのを確認しています。

> 手元では .env ファイルに以下を追加することで起動できるようになりました：
> SOLR_HEAP=256M
