### ISSUE TITLE
librarian権限で貸出規則の一覧の[編集]リンクをクリックすると「アクセスが拒否された」となります

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1138]
- [ ] マニュアル修正 #1066 
- [ ] マニュアル修正 バグがなおった旨を書く

関連：　#1046 #1047 #1139
librariann権限のユーザーが[編集]リンクをクリック
![image](https://cloud.githubusercontent.com/assets/1328499/12695285/f40d18a0-c78c-11e5-9228-88cc872bcadd.png)

アクセスが拒否されたとなる
![image](https://cloud.githubusercontent.com/assets/1328499/12695295/3419cd6c-c78d-11e5-9190-eb61ac1ce40a.png)

もともと、この貸出規則の一覧の画面の意味があまりわかってないので
なんともいえないのですが、

* アクセスが拒否される[編集]リンクをなくす
* アクセス拒否しないようにする

のどちらかが必要かと思います。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 d9c66e1)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 25c8ca5)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 cc55ce1)

**Comment by nabeta** [comment]
修正しました。

**Comment by yegusa** [comment]
表示リンクだけになっていることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/19416321/e65ce7ae-93c8-11e6-8670-2994a93c37f3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 1dfb459)
  * enju_circulation (0.2.0.beta.3 9beab43)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 bf2a940)
  * enju_library (0.2.0.beta.9 aac73f4)
  * enju_loc (0.2.0.beta.3 795d91e)
  * enju_manifestation_viewer (0.2.0.beta.4 fb76dd9)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 748493b)
  * enju_nii (0.2.0.beta.3 9225546)
  * enju_oai (0.2.0.beta.4 cdeba20)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
