### ISSUE TITLE
著者情報をもつ書誌情報を編集ができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1140]
- [ ] マニュアル修正 #1066 

#935 の影響と思われますが、1.2系の先端にて著者情報を登録してある書誌情報の内容を編集せずにそのまま更新するだけでRailsエラーになります。
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/12696258/faaa9efa-c7a8-11e5-8e96-e2233a264626.png)

**Comment by nabeta** [comment]
ひとまずエラーにはならないようにしました。

**Comment by yegusa** [comment]
現在のステータスメモ：

- 単純なチェックまち。江草でもできそう。
  - 確かめ方法：著者情報が入っている書誌をひらいて、なにもせずに保存して、保存できるかどうかたしかめればよい。

**Comment by yegusa** [comment]
手元の仮想マシンでできることを確認したのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/14058628/ec3f2da8-f369-11e5-8c69-ffdf38cbe8a1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/14058637/3bc22506-f36a-11e5-9c53-a66533a5aa48.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 f8ccc4c)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 8243b36)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)
