### ISSUE TITLE
雑誌のタイトルレベルのレコードに「所蔵作成」リンクがでてしまっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1142]
雑誌のタイトルレベルのレコードに所蔵をつけてはいけないので。

#1092 の副作用です。なのでunder developmentにさせてください。

タイトルレベルのレコードに「所蔵作成」リンクがでてしまっているのはNG
http://localhost:8080/manifestations?commit=%E6%A4%9C%E7%B4%A2&page=2&query=&utf8=%E2%9C%93
![image](https://cloud.githubusercontent.com/assets/1328499/12703024/a7756d4a-c87b-11e5-8574-3912f9854f32.png)

タイトルレベルのレコードに「所蔵作成」リンクがでてしまっているのはNG
http://localhost:8080/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/12703008/1d9c9df0-c87b-11e5-8602-e66cb1bfafb0.png)

個々の巻号のレコードには[所蔵作成]リンクがでているのはOK
![image](https://cloud.githubusercontent.com/assets/1328499/12703040/fa29f9d4-c87b-11e5-882f-249b5b2e7e56.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e7e1ab8)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 5b409a6)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)

**Comment by masao** [comment]
所蔵作成リンクを消し、仮に直接URL指定されても逐次刊行物の書誌一覧ページへのリダイレクトになるように修正しました。

**Comment by yegusa** [comment]
できることを確認しましたのでクローズします。

検索結果一覧　　雑誌タイトルレベル 「所蔵作成」が出てない　→ OK
![image](https://cloud.githubusercontent.com/assets/1328499/12864289/6fae22ba-ccc9-11e5-830c-5f832663e6de.png)

雑誌・定期刊行物の画面　雑誌タイトルレベル 「所蔵作成」がでていない　→　OK
![image](https://cloud.githubusercontent.com/assets/1328499/12864298/a1e3d0ae-ccc9-11e5-8815-4e149561830d.png)

雑誌タイトルレベルの画面　個々の巻号　「所蔵作成」がでている → OK
![image](https://cloud.githubusercontent.com/assets/1328499/12864305/c6c3d0e0-ccc9-11e5-8c4d-c61cda3e4378.png)

スクリーンショットとりずらいのでとってませんが、「仮に直接URL指定されても逐次刊行物の書誌一覧ページへのリダイレクトになる」も、できることを確認しました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a42b53d)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 3024559)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)
