### ISSUE TITLE
（当面をしのぐため）画像の置き場は enju/public/assets/以下でよいですか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1144]
- [x] マニュアル #1066 

enju/public/assets/　に画像ファイルを直接おいてしまえばよいでしょうか？

例えば、こんなかんじ。

* logo.png を　enju/public/assets/ 以下に置く。
* 参照するときは、こんな感じのURL http://localhost:8080/assets/log.png

このissueの作成経緯：

#1113 ができれば、このカスタマイズはいらないのですが、
#1113 の開発が終わるまでに、当面しのぐために、
カスタマイズで、画像を置く方法を教えてほしいです。
（#1131 #1118 の画像についてのみ抜き出したissueでもあります。）

**Comment by yegusa** [comment]
10-5 トップ画面やヘルプなどに表示する画像を置く
https://next-l.github.io/manual/1.2/enju_install_vm_10.html#section10-5

を書きました。

これでよいなら、どなたか確認してクローズしてください。

**Comment by scivola** [comment]
Rails の仕組み上は /enju/public/assets に置けばいいはずですが，2 点検討すべきことがあります。

一つは Capistrano を使ってデプロイする場合，その場所に置いたものは持ってってくれないらしいこと。（私はよく分かりません）
参考：
http://qiita.com/wadako111/items/03bc00d914e62243a511#2-4
Capistrano が使われる可能性が無いか，もしくは Capistrano でデプロイする人は自分で適切な位置を考えて画像が置けると仮定できるか，いずれかであれば杞憂なのですが。

もう一つはテキトーな場所に画像を置いちゃって，将来 Enju をアップデートしたときに画像のパスが衝突する可能性を避けたい，ということです。
こちらについては，/public/assets の下にカスタマイズ用アセット置き場となるディレクトリーを一つ作っちゃって，そこに入れとけばぶつからないよ，とするのがよいのではないかと。

**Comment by nabeta** [comment]
画像ファイルは app/assets/images/ に置いた後、以下のコマンドを実行してください。

```sh
$ bundle exec rake assets:precompile
```

例として、app/assets/images/example.png に保存した画像ファイルは、http://localhost:3000/assets/example.png でアクセスできます。
同様に、app/assets/images/test/example.png は、http://localhost:3000/assets/test/example.png  でアクセスできます。

**Comment by yegusa** [comment]
@nabeta さんのやりかたなら、 @scivola さんの懸念点は解消されますよね？

マニュアルは、修正しておきました。

**Comment by scivola** [comment]
@nabeta さん，Rails 4 で production 環境のときはそれだとアクセスできないのではなかったでしたっけ？
 http://qiita.com/wadako111/items/03bc00d914e62243a511
試してはいませんが。

**Comment by nabeta** [comment]
説明が抜けていてすみません。Rails4のデフォルトの設定ではご指摘のとおり、生成される画像ファイルがダイジェストを含んだファイル名になってしまうため、example.pngではアクセスできません。このため、enju_leafでは、ダイジェストを含まないファイル名で画像ファイルを生成するgemを読み込むようにしています。
https://github.com/alexspeller/non-stupid-digest-assets
https://gist.github.com/nabeta/5357321#file-enju_leaf_template-rb-L17

**Comment by scivola** [comment]
そんな gem があるのですね。でしたら大丈夫ですね。

二つ目の懸念はどうでしょう。app/assets/images の下に自由にファイルを置かせるのではなく，カスタマイズのためのファイルを置くディレクトリーをこの下に一つ切ったほうが良いかと思いますが。

**Comment by nabeta** [comment]
app/assets/images はenju_leafなどのgemにある（たとえば以下）だけでなく、rails newを実行したときにローカルに作成されます。
https://github.com/next-l/enju_leaf/tree/master/app/assets/images

このローカルに作成された app/assets/images の中に、app/assets/images/nims など、各自でカスタマイズ用のディレクトリを作るのが簡単だと思います。

ちなみに、同名のファイルを作ると、gemで使用しているデフォルトの画像を置き換えることができます。たとえば、ローカルに app/assets/images/unknown_resource.png を置いて rake assets:precompile を実行すると、デフォルトの書影画像（以下）を置き換えることができます。
https://github.com/next-l/enju_leaf/blob/master/app/assets/images/unknown_resource.png

**Comment by yegusa** [comment]
つまりマニュアルでは、フォルダを掘って入れとくのが無難だよって感じで書いておくといいということですかね？

**Comment by scivola** [comment]
@nabeta さん，よく分かりました。
で，私の提案は，カスタマイズ用のディレクトリーの名前を一つ決めちゃってはどうか，ということです。
このディレクトリーの下に入れれば Enju が用意した画像とパスがぶつかることは（将来にわたっても）絶対に無いよ，ということが保証されているディレクトリーを一つ用意してはどうか，ということです。

**Comment by masao** [comment]
では、カスタマイズ用のフォルダとして、「custom」フォルダとし、 app/assets/images/custom/ 以下に各アプリ用の独自画像等をおくことにする（第46回開発ワークショップでの議論より）。

**Comment by yegusa** [comment]
マニュアルを更新しました。

10-5 トップ画面やヘルプなどに表示する画像を置く
https://next-l.github.io/manual/1.2/enju_install_vm_10.html#section10-5

**Comment by yegusa** [comment]
どなたか確認してクローズください。

**Comment by masao** [comment]
確認したのでクローズします。
