### ISSUE TITLE
正しいURL教えてください（マニュアルリンク切れURLについて）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1145]
- [x] マニュアル #1066

以下の正しいURLおしえてください。

1.1系
https://github.com/next-l/enju_leaf/blob/1.1/app/views/manifestations/_index_form.html.erb

1.2系
https://github.com/next-l/enju_leaf/blob/1.2/app/views/manifestations/_index_form.html.erb

以下のマニュアル中のURLです。 
* https://next-l.github.io/manual/1.1/enju_install_vm_10.html
* https://next-l.github.io/manual/1.2/enju_install_vm_10.html

**Comment by nabeta** [comment]
- 1.1系: https://github.com/next-l/enju_flower/blob/1.1/app/views/manifestations/_index_form.html.erb
- 1.2系: https://github.com/next-l/enju_biblio/blob/1.2/app/views/manifestations/_index_form.html.erb

**Comment by yegusa** [comment]
ありがとうございます。修正しました。クローズします。
