### ISSUE TITLE
マニュアル：目次に四角がついちゃってる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1146]
1.1系、1.2系ともにです。

http://next-l.github.io/manual/1.2/
![image](https://cloud.githubusercontent.com/assets/1328499/12738463/4d17d34a-c9a4-11e5-9eb1-dcca7378b9de.png)

手元の作業ファイルでは四角がないのですが。
http://localhost:8080/~vagrant/manual/_site/1.2/
![image](https://cloud.githubusercontent.com/assets/1328499/12738483/788ea580-c9a4-11e5-8bf7-b1e5fa508cde.png)

**Comment by scivola** [comment]
トップページだけ `ul.toc` のクラス名を変えるのがいいですかね。

**Comment by masao** [comment]
HTML生成につかっているJekyllがバージョン3.0.0にあがったことによる影響だったようです。具体的には、生成ファイル名を示す変数のデフォルト値が変わったことによるもののようです。 jekyll/jekyll#4145 に述べられている回避策で対応しました。
現在は直っているかと思います。

**Comment by yegusa** [comment]
直っているのを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12740712/310a53a2-c9b9-11e5-8066-73fa58782582.png)
