### ISSUE TITLE
検索結果一覧や書誌詳細のTSVエクスポートで利用者向けにださないほうがよい項目（Librarian権限以上のときにだけ出す項目）があるかも？（例：書店、予算種別、購入価格など）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1147]
- [ ] マニュアル #1066 
- [x] Guest 検索結果一覧で、書店、予算種別、購入価格が表示されない
- [x] Guest 検索結果詳細で、書店、予算種別、購入価格が表示されない
- [x] User 検索結果一覧で、書店、予算種別、購入価格が表示されない
- [x] User 検索結果詳細で、書店、予算種別、購入価格が表示されない

#857 #854 で、検索結果一覧のエクスポート、検索結果詳細のTSVエクスポート、
書誌と所蔵の全件TSVエクスポート、の出力項目をそろえたのですが、
利用者向けにはださないほうがいい項目（Librarian権限以上の場合だけだす項目）が
ある気がします。

例えば、

*  書店 bookstore
* 予算種別 budget_type
*  購入価格 item_price （注　別に「販売価格」があるがこちらははあっていいと思う）

とかは、利用者むけには出さないほうがよさそうな気がします。

どうでしょう？

※1.2.0で追加される機能（ #857 #854 ）によるdiscussionなので、
とりあえず、under development にしています。

### 参考： 1.2.0現在 の　書誌と所蔵のTSVエクスポート出力項目

* manifestation_id: 書誌ID
* original_title: 原題
* creator: 著者
* contributor: 協力者・編者
* publisher: 出版者
* pub_date: 出版日
* statement_of_responsibility: 責任表示
* manifestation_price: 販売価格
* manifestation_created_at: 書誌情報作成日（エクスポートのみの項目）
* manifestation_updated_at: 書誌情報更新日（エクスポートのみの項目）
* manifestation_identifier：ローカル識別子
* access_address: アクセスアドレス
* note: 注記
* isbn： ISBN
* subject:unknown: 件名（unknown）※入力データによっては出力されないこともありま
す。
* subject:ndlsh: 件名（NDLSH）※入力データによっては出力されないこともあります。
* （入力データによってはほかにも subject:　からはじまるものがあります）
* classification:ndc9: 分類（NDC）※入力データによっては出力されないこともありま
す。
* （入力データによってはほかにも classification:　からはじまるものがあります）
* item_id: 所蔵データID(自動付与）
* item_identifier: 所蔵情報ID
* call_number: 請求記号
* item_price: 購入価格
* acquired_at: 受入日
* accepted_at: 検収日（エクスポートのみの項目）
* bookstore: 書店
* budget_type: 予算種別
* circulation_status: 貸出状態
* shelf: 本棚
* library: 図書館
* item_created_at: 所蔵情報作成日（エクスポートのみの項目）
* item_updated_at: 所蔵情報更新日（エクスポートのみの項目）

※1 その他、書誌に登録されている識別子（例：jpno,ncid）は全て出力されます。

※2 分類や件名で複数あるものは//で区切られて出力されます。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a42b53d)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 3024559)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)

**Comment by nabeta** [comment]
エクスポート用のメソッドに、実行権限を引数として指定できるようにする予定です。
https://github.com/next-l/enju_biblio/blob/master/app/models/manifestation.rb#L535

**Comment by yegusa** [comment]
すくなくとも、

* 書店
* 予算種別
* 購入価格 （注　別に「販売価格」があるがこちらははあっていいと思う）

は利用者権限では出力しないということもEnju WS で合意。

**Comment by masao** [comment]
ログイン中のアカウント権限を反映して、上記にある3種類の所蔵情報項目の出力の可否を切り替えるよう実装を行いました。確認いただければと思います。

**Comment by yegusa** [comment]
現在のステータス：確認してクローズするのみ（私でもできそう）

**Comment by yegusa** [comment]
確認できたので、クローズします。マニュアルはあとで修正します。

検索結果一覧のTSV　エクスポートで、 bookstore, budget_type, item_price が、Guest, Userでは表示されない、Admin, Librarianでは表示されることを以下で確認。
http://localhost:8080/manifestations.txt?commit=%E6%A4%9C%E7%B4%A2&query=&utf8=%E2%9C%93

検索結果一覧のTSV　エクスポートで、 bookstore, budget_type, item_price が、Guest, Userでは表示されない、Admin, Librarianでは表示されることを以下で確認。
http://localhost:8080/manifestations/58.txt

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a366e5d)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 d5e2c12)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

**Comment by yegusa** [comment]
マニュアル修正しました。

「1-1-3 書誌と所蔵のTSVの項目」を修正し、3項目（書店、予算種別、購入価格）について、
「（Administrator権限、Librarian権限のときのみ出力）」を追加。
http://localhost:8080/~vagrant/_site/1.2/enju_webapi_1.html#bib_tsv_export
