### ISSUE TITLE
雑誌のタイトルレベルの表示で[削除]リンクが表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1149]
#1058 の副作用？　という気もするので、 under developmentにしています。
http://localhost:8080/manifestations?parent_id=62
![image](https://cloud.githubusercontent.com/assets/1328499/12872802/22deb6a2-cdf0-11e5-8fb2-4fbd42809788.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 8c1aee2)
  * enju_circulation (0.2.0.beta.1 dac29be)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 3024559)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)

----
1.1.2

![image](https://cloud.githubusercontent.com/assets/1328499/12872813/76f3a8d8-cdf0-11e5-83d0-c5fd85aa3e4f.png)

enju_biblio: 0.1.2
enju_circulation: 0.1.1
enju_event: 0.1.18
enju_flower: 0.1.1
enju_leaf: 1.1.2
enju_library: 0.1.1
enju_manifestation_viewer: 0.1.1
enju_message: 0.1.15
enju_ndl: 0.1.1
enju_purchase_request: 0.1.1
enju_subject: 0.1.1

**Comment by masao** [comment]
権限管理ポリシーが貸出予約モジュール enju_circulation と多重に定義されていて、逐次刊行物の場合の削除要件を正しく指定できていませんでしたので、修正しました。

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。

削除リンクが表示されていることを確認しました。

また、スクリーンショットはとってないですが、削除リンクをクリックして、レコードが削除されることも
確認ずみです。

![image](https://cloud.githubusercontent.com/assets/1328499/13194741/72fcca58-d7e0-11e5-936e-732c3f77e0b4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 5359a52)
  * enju_circulation (0.2.0.beta.1 2a3c92e)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 bc7dfea)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 3904168)
