### ISSUE TITLE
アイコンの vertical-align を適切に

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1150]
- [x] スクリーンショット差し替えするほどもないと思うので、マニュアル修正しないことにした #1191 

添付図左のようにアイコン画像が上に浮き上がったようになって，きれいな並びになりません。

これは，あらゆる要素に `vertical-align: baseline` が効いているためです。
アイコン画像の `img` 要素は適当なクラスを付けて，`vertical-align: middle` にするとよいのではないでしょうか。
そうやってみたものが添付図右です。

![icon-vertical-align](https://cloud.githubusercontent.com/assets/294125/13241755/67e22566-da31-11e5-9fb6-c8324f69751f.png)

**Comment by nabeta** [comment]
> これは，あらゆる要素に vertical-align: baseline が効いているためです。

ありがとうございます。気にはなっていたのですが、どうすればよいのかわからずそのままにしていました。ちょっとやってみます。

**Comment by scivola** [comment]
ちなみに今回のようにテキストに img が混在した場合の画像の上下位置は，（vertical-align が同じでも）ブラウザーやフォントによってけっこう違ったりするようです。（最近のブラウザーに限定すればそれほど違わないかも？）
なので改善したかどうかのチェックはなるべくいろんな環境で行ったほうがいいと思います。

**Comment by nabeta** [comment]
各モジュールのアイコンの image_tag に enju_icon クラスを設定し、 vertical-align: middle を指定しました。

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/18813283/18b03d4a-8330-11e6-9268-4cb36731e27f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813288/298beaa6-8330-11e6-8294-689f0776948a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
