### ISSUE TITLE
Ubuntu 16.04対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1153]
Ubuntu 16.04に移行すると Ruby 標準が 2.3.0 に更新されたので、VMのデフォルトをこちらに更新するとよいかも。
第48回開発WSでの議論: http://www.slideshare.net/nabeta/nextl-enju-48

**Comment by kouamano** [comment]
$ uname -a
Linux kamano-VirtualBox 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ ruby -v
ruby 2.3.0p0 (2015-12-25) [x86_64-linux-gnu]

$ sqlite3 --version
3.11.0 2016-02-15 17:29:24 3d862f207e3adc00f78066799ac5a8c282430a5f

**Comment by nabeta** [comment]
Vagrantの仮想マシン作成スクリプトはUbuntu 16.04を使用するようにしました。
https://gist.github.com/nabeta/f521066870964d85c3d81bfdd49a8848

なお、この仮想マシンはSQLite3ではなくPostgreSQLを使用しています。

**Comment by nabeta** [comment]
Ubuntu 16.04でvagrant sshができない問題があるため、いったん14.04に戻しています。

**Comment by masao** [comment]
16.04では upstart から systemd が標準環境に変わったため、そのままでは起動スクリプト周りが設定できない模様。

**Comment by masao** [comment]
起動スクリプトに関しては #1241 を参照のこと。

**Comment by nabeta** [comment]
仮想マシンの作成と起動まで確認できたので、closeできると思います。
https://gist.github.com/nabeta/f521066870964d85c3d81bfdd49a8848

**Comment by masao** [comment]
仮想マシンが起動できることを確認したのでクローズします。
