### ISSUE TITLE
dotenv-rails 2.1.0 でエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1155]
1.1系、1.2系双方でおきるエラー。
enju_leaf起動時にエラーになって起動しない。要修正。

**Comment by nabeta** [comment]
まだ原因はよくわかりませんが、回避策として、Gemfileでdotenv-railsのある行を以下のように変更してください。

```ruby
gem 'dotenv-rails', '~> 2.0.2'
```

**Comment by masao** [comment]
手元では同様のエラーが再現しなくなっている。
```
    dotenv (2.1.1)
    dotenv-rails (2.1.1)
```

**Comment by nabeta** [comment]
私の環境やデモサーバでも再現しなくなりました。原因がよくわからないのは気持ち悪いですが、仮想マシンの作成スクリプトで再現しなければcloseしましょう。

**Comment by nabeta** [comment]
原因がわかりました。springが関係しているようで、Gemfileからspringを削除すると問題が発生しなくなりました。
https://github.com/rails/spring

springはrails newをしたときに含まれるので、dotenv-railsを2.0.2に固定するのでよいと思います。

**Comment by nabeta** [comment]
2.0.2に固定して回避する方法でひとまずcloseします。
