### ISSUE TITLE
検索結果詳細のTSVエクスポートでWe're sorry になる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1156]
#1147 確認中に遭遇。

http://localhost:8080/manifestations/58.txt
とやるとWe're sorry になる

以下、ログ。

![image](https://cloud.githubusercontent.com/assets/1328499/14760001/96ce92fa-0971-11e6-82f6-cd32527a94b3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 66e3b0e)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 cff4d4c)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

**Comment by masao** [comment]
この箇所だけ実装漏れでした。修正したのでご確認ください。

**Comment by yegusa** [comment]
http://localhost:8080/manifestations/58.txt

admin, librarian,user,guest すべての権限で↑のものが、We're sorry にならずに表示できたので、
クローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a366e5d)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 d5e2c12)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)
