### ISSUE TITLE
任意の識別子登録

### ISSUE THREAD

**Issue by kouamano** [next-l/enju_leaf#1157]
「資料の新規作成」の「識別子」の種類をwebサービス画面から新しく登録できないか。

**Comment by nabeta** [comment]
1.1系でも「システムの設定」→「識別子の種類」で種類の追加はできます。
http://enju.next-l.jp/identifier_types

ただ、この方法だとバリデーション（値の書式など）をどうするかが問題になります。できれば識別子は新しくテーブルを作り、モデルを定義してほしいです。

**Comment by yegusa** [comment]
すでに、Webサービス画面から新しく登録できますよ。

↓マニュアルもありますので、参考にしてください。

https://next-l.github.io/manual/1.1/enju_setup_6.html

@kuamano さん、いかがでしょうか？

**Comment by yegusa** [comment]
こちらも、1年以上たちましたし、いったんクローズします。
また、問題があるようでしたら、新規にissueを立ち上げたいとおもいます。
