### ISSUE TITLE
異体字をつかった検索についてのマニュアルにreindex についての記述を追加する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1158]
6-1-1-4 Enju の再起動
https://next-l.github.io/manual/1.2/enju_install_vm_6.html#section6-1-1-4

↑のこの下に、reindex がいることを追加する。

$ bundle exec rake sunspot:reindex RAILS_ENV=production

がいることを追加する。

Enju WS にて、判明

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
こちら、確認しましたので、クローズします。
