### ISSUE TITLE
不具合：資料の受入→ISBNを入力する→ISBNを入力して[登録]とするとエラーになることがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#116]
資料の受入→ISBNを入力する→ISBNを入力して[登録]とする

We're sorry, but something went wrong.

となるときがありました。

2014-05-29 12:20頃
最新の仮想マシンと、Enjuのデモサイトで同じ現象を確認しました。

数分おいてから、同じISBNでためしたところ、
仮想マシンのときは、「ISBNインポートのリクエストは正常に作成されました。」とうまくできたようです。

原因を調査してもらえるとうれしいです。

以下の2件のISBNで現象を確認しました。

9784890855278
9784523261711

原因がわかったら、
we are... ではなく、なにか別のメッセージをだすようにできたらなと思います。

**Comment by yegusa** [comment]
これ、タイムアウトとプロキシ経由のエラー画面に行くようにするという別issueをたてることにして、このissueはいったんクローズにします。

**Comment by nabeta** [comment]
> 現在のNDLサーチからのインポートは、Rubyのopen-uriを用いています。

2015年4月時点では、Faradayを使用しています。
https://github.com/next-l/enju_ndl/blob/1.1/lib/enju_ndl/ndl_search.rb#L246
