### ISSUE TITLE
リリースプロセスの文書化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1160]

**Comment by nabeta** [comment]
以下にまとめました。
https://github.com/next-l/enju_leaf/wiki/HowToRelease

**Comment by yegusa** [comment]
じゃあ、確かめも含めて、 @nabeta さん以外が、 1.2.0.beta.4でやってみる感じ？

**Comment by nabeta** [comment]
そうですね。次回ワークショップでやってみましょうか。

**Comment by yegusa** [comment]
チェックは、 @tmasao おねがい～。

**Comment by masao** [comment]
確認しながら、半分以上のモジュールをリリースしてみたので、ひとまずクローズします。
