### ISSUE TITLE
リリースプロセスの簡便化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1161]
- [x] markdown のマニュアル修正の必要ない #1191

現状のモジュールのリリースプロセスがかなり複雑なので、もう少し簡単にできるように改善したい。

**Comment by nabeta** [comment]
1.1系では各モジュールが相互に依存している場合がありましたが(enju_biblioとenju_libraryなど）、1.2系ではそのような依存関係を大幅に整理し、一方向の依存関係となるようにしました。
https://github.com/next-l/enju_leaf/wiki/HowToRelease

**Comment by yegusa** [comment]
チェックは、 @masao よろしく～。実際に、次のリリースをやってみるといいのかな。

**Comment by masao** [comment]
一通りリリース作業してだいぶ問題なくなっているような気もするのでいったんクローズします
