### ISSUE TITLE
提案：米国議会図書館検索インポートの画面に同じキーワードで同サービスを探すリンクをつけてはいかが？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1162]
- [ ] 確認
- [ ] マニュアル修正 #1191

#818 の LC版です。

**Comment by masao** [comment]
修正を加えました。ご確認ください。
![loc next l enju leaf](https://cloud.githubusercontent.com/assets/38825/16175583/f68d8cee-362d-11e6-9529-5a5463d24a46.png)

**Comment by yegusa** [comment]
手元の仮想マシンでできることを確認しました。のでクローズします。マニュアルはあとで修正します。

Harry Potter で検索したところ、右の赤四角中のリンクをたどる
![image](https://cloud.githubusercontent.com/assets/1328499/18806758/f2707fec-8270-11e6-8beb-1b8630164b1e.png)

LC のサイトで、Harry Potter で検索した結果がでている
![image](https://cloud.githubusercontent.com/assets/1328499/18806774/6fe5a222-8271-11e6-95ec-9f983dd2f531.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.3)
  * enju_circulation (0.2.0.beta.3)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3)
  * enju_library (0.2.0.beta.9)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
