### ISSUE TITLE
提案：CiNiiBooksインポートの画面に同じキーワードで同サービスを探すリンクをつけてはいかが？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1163]
- [ ] 確認
- [ ] マニュアル修正 #1191

#818 のCiNii版です

**Comment by masao** [comment]
機能を追加してみました。ご確認ください。
![cinii books](https://cloud.githubusercontent.com/assets/38825/15627395/8d2bb40e-251d-11e6-96f0-38e04f69d144.png)

**Comment by yegusa** [comment]
手元の仮想マシンでできることを確認しました。ので、クローズします。マニュアルはあとで修正します。

Harry Potter で検索したところ、右の赤四角で囲まれたリンクをクリック
![image](https://cloud.githubusercontent.com/assets/1328499/18806826/0c313bb8-8273-11e6-84b3-c281117c03d9.png)

Harry Potter で検索したCiNii Books の結果が表示
![image](https://cloud.githubusercontent.com/assets/1328499/18806830/32ceec5c-8273-11e6-9ee5-4fe12265bbb9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.3)
  * enju_circulation (0.2.0.beta.3)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3)
  * enju_library (0.2.0.beta.9)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
vagrant@vagrant-ubuntu-trusty-64:~/enju$
