### ISSUE TITLE
SyntaxError in BasketsController#new

### ISSUE THREAD

**Issue by kamei-at-nims** [next-l/enju_leaf#1164]
![20160509_1](https://cloud.githubusercontent.com/assets/18201545/15103707/9b6fd4ac-15e9-11e6-9495-3babd6ee2352.png)
t('page.new') の ) が不要

**Comment by nabeta** [comment]
以下のコミットで修正しました。
https://github.com/next-l/enju_library/commit/e0b60e4ac057e2ac92866b018515c8fb27243719

**Comment by nabeta** [comment]
修正済みのためcloseします。

**Comment by yegusa** [comment]
https://github.com/next-l/enju_leaf/releases/tag/v1.2.0.beta.1 が直近なので，ここでは修正されていたはずということですね。一応，現時点での1.3.2のマイルストーンをつけておきます。
