### ISSUE TITLE
ArgumentError in Events#show

### ISSUE THREAD

**Issue by kamei-at-nims** [next-l/enju_leaf#1165]
![20160509_2](https://cloud.githubusercontent.com/assets/18201545/15103749/28781c06-15ea-11e6-8be8-7402c306752a.png)
, format が不要

**Comment by nabeta** [comment]
このエラーは現時点では表示されません。
https://enju.next-l.jp/events/7

**Comment by masao** [comment]
ひとまずクローズします。
