### ISSUE TITLE
カレンダー表示時に文字が切れてしまう

### ISSUE THREAD

**Issue by YoshieHASEHIRA** [next-l/enju_leaf#1170]
イベントを入力した際に、カレンダー表示される部分の文字が切れてしまいます。折り返して表示するように出来ないでしょうか？

**Comment by YoshieHASEHIRA** [comment]
![image](https://cloud.githubusercontent.com/assets/19513082/15452505/86f714d0-202b-11e6-9586-a5abd0e03e53.png)

**Comment by nabeta** [comment]
このカレンダーはFullCalendarを使って表示しているのですが、ここの例でも折り返しができていないようですね。CSSで調節できるかどうか試してみます。
http://fullcalendar.io/js/fullcalendar-2.7.3/demos/languages.html

**Comment by nabeta** [comment]
以下のように表示されるように修正しました。
![image](https://user-images.githubusercontent.com/11428/184888107-95b70fc6-11a9-4223-aee0-6066321efed8.png)

**Comment by nabeta** [comment]
修正済みのため、クローズします。
