### ISSUE TITLE
モジュール追加方法の修正: enju_bookmark

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1172]
- [ ] マニュアル修正 #1191

app/models/user.rb および app/controllers/application_controller.rb への設定方法が変更になっているのでマニュアルを修正する必要がある。

**Comment by yegusa** [comment]
確かめる方法：
5-5 [enju_bookmark]モジュール（ブックマーク機能）
https://next-l.github.io/manual/1.2/enju_install_vm_5.html#section5-5

この通りにやってで、当該モジュールが追加できるかどうか確かめる。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。一応、できるようですのでクローズします。
マニュアル修正はあとでします。

> rake enju_bookmark_engine:install:migrations 
> rake db:migrate RAILS_ENV=production

は、以下のようにする必要がありました。

bundle exec rake enju_bookmark_engine:install:migrations  
bundle exec rake db:migrate RAILS_ENV=production

このマニュアル修正はあとでします。

いちおう、モジュールの追加はできました。
起動もしました。

![image](https://cloud.githubusercontent.com/assets/1328499/18813785/1fa99770-8341-11e6-9f2f-a7922c70fc16.png)

ただ、ちゃんと動くかどうかは、マニュアルもないし、確かめようがないので、
確かめてません。
