### ISSUE TITLE
upstartエラーについて文書化する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1173]
配布仮想マシンでは、設定誤り等により upstart 段階で落ちている場合、通常の log/production.log にはエラーが出てこないので注意が必要。

/var/log/upstart 以下を確認すること。

**Comment by masao** [comment]
ざっくりと書いておいたので確認願います。

http://next-l.github.io/manual/1.2/enju_install_vm_11.html#q-504-gateway-timeout-

**Comment by nabeta** [comment]
ありがとうございます。あとはよくあるエラーとその対応方法の追加でしょうか。
「Gemfileが解決できていない」以外になにかありますかね。

**Comment by nabeta** [comment]
Ubuntu 16.04で作る仮想マシンは上記の手順をsystemdでの手順に書き換える。

**Comment by masao** [comment]
#1277 を作ったので、こちらはひとまずクローズします。
