### ISSUE TITLE
検収機能で「在架」状態にしても所蔵資料検索でのファセットに反映されない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1174]
- [ ] マニュアル修正 #1191 

ひとまずデモサーバ（1.1系）のみで確認してます。1.2系でも再現できる気がします。

再現手順：
1) 任意の所蔵情報を1件作成する： ex. http://enju.next-l.jp/items/7195
2) 検収機能で在架状態にする： ex. http://enju.next-l.jp/accepts/31
3) 所蔵情報一覧画面にて「作業中」ファセットを選択：
http://enju.next-l.jp/items?circulation_status=In+Process

上記で在架状態になっている所蔵情報が表示されてしまう。
おそらく検収機能での変更が、所蔵情報のファセットインデックスには反映されていないのではないかと思われます。

**Comment by masao** [comment]
検索ファセットに反映するように、研修完了時に所蔵資料情報のインデックスを更新するように修正しました。

**Comment by yegusa** [comment]
手元の仮想マシンでできていることを確認しました。クローズします。バグつぶしなのでマニュアル修正はないです。

![image](https://cloud.githubusercontent.com/assets/1328499/18813464/aa805e6c-8335-11e6-9aa8-1fd8c2630ef9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813466/c2e2f73a-8335-11e6-829e-ff7b27ff3cb6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813467/d64ab772-8335-11e6-9771-7ed2d950c650.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813470/eefffc00-8335-11e6-94dc-56fc8be5ccc3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
vagrant@vagrant-ubuntu-trusty-64:~/enju$
