### ISSUE TITLE
TSVインポートファイルのexampleで全項目を揃えたものを作る

### ISSUE THREAD

**Issue by kouamano** [next-l/enju_leaf#1177]
https://github.com/next-l/enju_biblio/tree/master/examples/
配下に全項目を揃えた
resource_import_file_sample_complete.tsv
を作ってください。

**Comment by yegusa** [comment]
マニュアルと見比べてみたら、以下の項目がありませんでした

- [ ] access_address
- [ ] acquired_at
- [ ] checkout_type
- [ ] circulation_status
- [ ] contributor
- [ ] contributor_transcription
- [ ] description
- [ ] fulltext_content
- [ ] item_id
- [ ] ncid
- [ ] periodical
- [ ] required_role
- [ ] required_role_name
- [ ] title_alternative_transcription
- [ ] use_restriction

**Comment by nabeta** [comment]
#332 と重複しているため、closeします。
