### ISSUE TITLE
書誌TSVインポートのサンプルからseries_statement_identifierを削除する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1178]
- [x] markdownのマニュアルを修正しない #1348

- このissueでは、TSVのサンプルファイル（テストでも使う？）から、series_statement_identifier を削除するissueとします。
- serialのTSVインポートについてのマニュアルについては別issue #1410 で扱うこととします。
- 副シリーズタイトル、読み： series_title_subseries, series_title_subseries_transcription については、 #367 で扱います

----

#### 以下、以前のissue の記述

書誌・所蔵インポートTSVファイルのサンプル
https://github.com/next-l/enju_biblio/tree/master/examples/
resource_import_file_sample_complete.tsv

にあるが、マニュアルに書いていないものがあります。
それぞれ、どういうものか教えてください。
もし、現在はつかってないものがあるのなら、削除おねがいします。
まずは、おしえてください。

TSVファイルのサンプルにあるが、マニュアルに書いていないもの：
- serial
- series_statement_identifier
- series_title_subseries
- series_title_subseries_transcription
#1177 の逆バージョンです。

**Comment by yegusa** [comment]
- serial は、　逐次刊行物のフラグ　なので、 真偽値をいれる
- series_statement_identifier　昔つかってたけど、今はつかってない

以下の2つについては、

- series_title_subseries ・・・副シリーズタイトル
- series_title_subseries_transcription・・・副シリーズタイトルの読み

シリーズ情報：
http://localhost:8080/series_statements

で編集・表示は可能。

で、おなじようなことを2年前に議論してますね。

#367 ですね。おなじようなことをいってますね。

**Comment by yegusa** [comment]
マニュアルには、「シリーズ情報」のこところに保存されるので、そこで、編集、閲覧が可能ということは記述しておく。
あと、別件でシリーズ情報で検索できるようになっていたほうがよいというのがでたので、それは、別のissueにする。

このissueは、

- series_title_subseries ・・・副シリーズタイトル
- series_title_subseries_transcription・・・副シリーズタイトルの読み

について、書誌のTSVインポートのところに書く

- series_statement_identifier  これは使ってないので、TSVから削除する
→　これは、じゃあ、@nabeta さんよろしく

- serial は書誌のTSVインポートのところにマニュアルに書く

をやったらクローズすることにする

**Comment by yegusa** [comment]
簡単なのでやる。　　Enju WS 2018-06-10 の議論より

**Comment by nabeta** [comment]
サンプルファイルからseries_statement_identifierを削除しました。

**Comment by yegusa** [comment]
#367 を見たら詳細はわかりますが、マニュアルにどう書くか悩ましい。。。

a) series_title_subseries ・・・副シリーズタイトル
b) series_title_subseries_transcription・・・副シリーズタイトルの読み
c) serial 

a), b) の2つは、書誌詳細や、書誌の編集画面では表示されない、中途半端な状況ですね。
TSVで入れることはできるが、現在、中途半端な状況であるというような内容を書くのがいいのだろうか。。。

c) も、TRUE にして見ましたが、逐次刊行物扱いにならないような？

ちょっと、マニュアルの書き方など、アイデア求む。

**Comment by yegusa** [comment]
a), b) については、以下のような注を書くのであろうか？

注：series_title_subseries（副シリーズタイトル）、series_title_subseries_transcription（副シリーズタイトルの読み）は、インポートできる項目ではあるが、書誌詳細や書誌の編集画面では表示されない項目である（詳細： #1178 ）

c) は使い方がわからないので書けないです。

**Comment by yegusa** [comment]
以下は series_statement_identifier がないことを確認しました。
https://github.com/next-l/enju_biblio/blob/master/examples/resource_import_file_sample1.tsv
https://github.com/next-l/enju_biblio/blob/master/examples/resource_import_file_sample2.tsv
https://github.com/next-l/enju_biblio/blob/master/examples/resource_import_file_sample3.tsv

https://github.com/next-l/enju_biblio/tree/master/examples/ の他のは見てませんが、まあ、いいよね。

ですので、クローズします。
