### ISSUE TITLE
貸出・返却のAjaxが正しく動作しない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1181]
貸出・返却の際に所蔵IDを入力しても、貸出中・返却済みの一覧表示が更新されない。
一覧表示のAjaxの処理が正常に動作していないと思われる。1.1, 1,2の両方で確認。

**Comment by nabeta** [comment]
turbolinksが5.0.0にアップデートされているのが原因で、2.5.3に戻すかGemfileから削除すると、正常に動作するようになった。

```ruby
以下のように変更
# gem 'turbolinks'
```

**Comment by nabeta** [comment]
enju_leafのgemspecで、turbolinks 2.5.3への依存関係を指定するようにしました。

**Comment by masao** [comment]
手元で1.1.4にあげてみて確認しました。
貸出や検収の画面にてAjaxが動くことを確認しました。
クローズします。
