### ISSUE TITLE
ManifestationsControllerにてRailsエラー：undefined local variable or method `store_location' 

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1183]
1.2最新版の新規インストール直後に、検索結果一覧画面に移動しようとしたところで、Railsエラーが出ます。

![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/17268623/8c261e04-566a-11e6-8aad-44e7c27b86af.png)

**Comment by nabeta** [comment]
これはログイン動作にログイン直前のURLにリダイレクトするための仕組みですが、Devise 4.0の書式にあわせるように修正しました。
https://github.com/plataformatec/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update

該当の箇所は以下です。
https://github.com/next-l/enju_library/blob/1.2/app/controllers/concerns/enju_library/controller.rb#L221

**Comment by masao** [comment]
現時点で問題なくなったことを確認したのでクローズします。
