### ISSUE TITLE
所蔵情報の一覧においてファセット選択と受入日絞り込みを同時に行えない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1195]
http://enju.next-l.jp/items?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2&acquired_from=2012-01-01&acquired_until=

受入日で絞り込んだ状態の所蔵情報の一覧において、右側のファセットから貸出状態での絞り込みを行っても、受入日の絞り込み情報が引き継がれないバグあり。

**Comment by masao** [comment]
修正しました。enju_circulationを更新してから確認いただければ幸いです。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。できているようですのでクローズします。

受入日を指定して検索した結果　　ここで、右の「除籍済み」リンクをクリック
![image](https://cloud.githubusercontent.com/assets/1328499/19018323/19257c92-8897-11e6-97ca-ab0818c8a05e.png)

ちゃんとしぼりこめた
![image](https://cloud.githubusercontent.com/assets/1328499/19018324/38105866-8897-11e6-996f-318af3e87e3a.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_oai (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
