### ISSUE TITLE
複数のファセットを同時に選択した絞り込み検索が行えない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1196]
- [ ] バグ修正なので、マニュアル修正関係なし

#1195 からの派生。所蔵検索だけでなく、書誌検索でも同様に、複数の検索ファセットを選択できない。

ひとつ選択しなおすと以前に選択していたファセットが選択解除されてしまう。

**Comment by masao** [comment]
@nabeta さん、おそらく下記修正による影響だと思うのですが、この修正の意図は何かありますか？
https://github.com/next-l/enju_biblio/commit/277fbab01e8d6c0ccfd1ae6dfee5ab44d6f37259

**Comment by nabeta** [comment]
@masao これはRail5でパラメータのチェックが厳しくなったことによるものです。
http://eileencodes.com/posts/actioncontroller-parameters-now-returns-an-object-instead-of-a-hash/

以下のコミットでファセットの部分は修正しましたが、他のモジュールでparams.mergeという表現を使っている部分も直さなければなりません。
https://github.com/next-l/enju_biblio/commit/17987f0f5e236197f733bea022940db1816d96be

**Comment by masao** [comment]
queryパラメータが抜けていたのを修正しました

**Comment by yegusa** [comment]
できたことをかくにんしたので、クローズします。

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0 2ea9b7e)
  * enju_circulation (0.2.1 1a10413)
  * enju_event (0.2.0)
  * enju_leaf (1.2.0)
  * enju_library (0.2.1)
  * enju_manifestation_viewer (0.2.0)
  * enju_message (0.2.0)
  * enju_ndl (0.2.0)
  * enju_seed (0.2.0)
  * enju_subject (0.2.0)


何もしてないところ、出版日のファセットを選び
![next l enju leaf](https://cloud.githubusercontent.com/assets/1328499/25561996/f8d46efe-2db3-11e7-9816-5b1f7fe9fb9c.png)

３件に絞られたところ、さらに、不明を選び
![next l enju leaf 2](https://cloud.githubusercontent.com/assets/1328499/25562005/429f675a-2db4-11e7-9f67-a4ee7c2c6855.png)

１件にしぼられたところ
![next l enju leaf 3](https://cloud.githubusercontent.com/assets/1328499/25562014/8688e036-2db4-11e7-9374-91a21037da02.png)
