### ISSUE TITLE
本棚の並びの変更ができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1197]
本棚の一覧 /shelves において、個別の棚情報の上下を変更することができなくなっている。
↑↓の矢印アイコンが出なくなっているため：
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/18805666/f75595be-824e-11e6-82ab-b6e4bd1b3610.png)

**Comment by nabeta** [comment]
書棚の並べ替えは図書館ごとに行うので、図書館が指定されていない状態だと並べ替えはできません。
http://enju.next-l.jp/shelves

図書館を指定すると並べ替えができるようになります。
http://enju.next-l.jp/shelves?library_id=2

**Comment by masao** [comment]
なるほど、図書館を選択する必要があることに気づきませんでした。UI上のどこかに注意喚起のメッセージをいれましょうか。

**Comment by masao** [comment]
うーん、図書館を選択して並べ替えても整合性がない状態になってしまいますね。。。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/18813965/29b6947e-8347-11e6-841a-029c74f632e3.png)

**Comment by nabeta** [comment]
ソート項目が正しく指定されていなかったのを修正しました。

**Comment by masao** [comment]
修正を確認しましたのでクローズします。
