### ISSUE TITLE
NDLサーチ検索書誌インポートで、ページ数（extent）を記録するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1202]
#333 からの派生です。

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
手元の仮想マシンで確かめました。できることを確認しましたので、クローズします。あとでマニュアルを修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/19018369/2839f1b6-8899-11e6-9cea-c459fc956788.png)

![image](https://cloud.githubusercontent.com/assets/1328499/19018375/5ba78590-8899-11e6-8688-eb3f2fbf5f3e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2)
  * enju_oai (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
