### ISSUE TITLE
書誌詳細の「ページ数と大きさ」について、間に「 ; 」を入れてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1206]
- [ ] マニュアルの修正 #1191 

現在：
	xx, 802p, 図版 [8] p. 22cm

提案：
	xx, 802p, 図版 [8] p. ; 22cm

#333 からの派生です。

![image](https://cloud.githubusercontent.com/assets/1328499/18807217/776a3994-827c-11e6-8d2a-d24c94f2e932.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18807222/97424374-827c-11e6-9aef-7393541b64ef.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 dfc3604)
  * enju_circulation (0.2.0.beta.3)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3)
  * enju_library (0.2.0.beta.9)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
vagrant@vagrant-ubuntu-trusty-64:~/enju$

**Comment by masao** [comment]
修正を加えました。確認願います。

**Comment by yegusa** [comment]
手元の仮想マシンでできていることを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/18815138/51765286-8362-11e6-90a2-d862ef76b7d3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 700fbac)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
