### ISSUE TITLE
米国議会図書館検索書誌インポートで、大きさ(dimensions）を記録するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1208]
#368 からの派生です。

**Comment by masao** [comment]
https://github.com/next-l/enju_loc/commit/8261f80de845fecb6603add0eb2cae1dcaeab226 にて修正しました。ご確認ください。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しましたので、クローズします。マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/19018451/6ce2dca8-889c-11e6-8524-130007b88b1a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/19018453/95c734ac-889c-11e6-84d4-074356f7aabe.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2)
  * enju_oai (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
