### ISSUE TITLE
CiNii Books 検索書誌インポートで、大きさ(dimensions）を記録するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1209]
#368 からの派生です。

**Comment by masao** [comment]
インポートするように変更しました。ご確認ください。
※ちなみに、この要素はCiNii Books側でも2015年11月から対応を開始したものです。
https://support.nii.ac.jp/ja/cib/api/b_rdf#revision_history

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/19018491/7d9b355c-889e-11e6-9588-b620c0bda2b5.png)

![image](https://cloud.githubusercontent.com/assets/1328499/19018497/a1fa56f8-889e-11e6-980e-cde3572bf12f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2 0515196)
  * enju_oai (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
