### ISSUE TITLE
TSV書誌インポートで、大きさ(dimensions）を記録するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1210]
#368 からの派生

- [ ] 確認
- [ ] マニュアルに追記  #1279

**Comment by yegusa** [comment]
これ、中途半端に、TSVインポートだけできないので、早々に開発してほしい。

**Comment by masao** [comment]
これ、実は1.2.0に追加された時点で、機能としてはできるようになっていたっぽいです。テストだけ追加しました。確認願います。

**Comment by yegusa** [comment]
original_title	dimensions
テストな書名	20cm

というデータをインポートしてみたら、ちゃんとできていることを確認しました
のでクローズします。

![next l enju leaf](https://user-images.githubusercontent.com/1328499/27768230-1e90dac6-5f49-11e7-865b-b00efe0a7668.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2)
  * enju_circulation (0.2.2)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_nii (0.2.0)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
