### ISSUE TITLE
OAI-PMH: DC-NDL対応のマニュアルがない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1211]
#691 に関連

#691 を確認しようとして、確認の仕方がわかりませんでした。そもそも、マニュアルがないと、チェクできないかなと。

**Comment by masao** [comment]
マニュアルを追加しました。
→ http://next-l.github.io/manual/1.2/enju_webapi_3.html

**Comment by yegusa** [comment]
このマニュアル通りにできることを確認しました（全部じゃないですが）。いいと思います。クローズします。
