### ISSUE TITLE
OAI-PMH: ListRecordsリクエストのfrom/until指定が効かない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1215]
#1211 のOAI-PMHマニュアルを書いていて気づきましたが、 from/until指定が効いていないようですね。

**Comment by masao** [comment]
修正を行いました。ご確認ください。
cf. http://next-l.github.io/manual/1.2/enju_webapi_3.html#section3-5 にあるようなタイプのリクエストで確認可能です。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。クローズします。

2016-09-01 から 2016-10-30 にしたら 15件ヒット
![image](https://cloud.githubusercontent.com/assets/1328499/19018700/081d6868-88a8-11e6-8ac9-7157598d2d3f.png)

2016-10-02 から　2016-10-30 にしたら　9件ヒット
![image](https://cloud.githubusercontent.com/assets/1328499/19018707/319e5e36-88a8-11e6-85d3-9f006510975d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2 0515196)
  * enju_oai (0.2.0.beta.3 c9faf19)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
