### ISSUE TITLE
マニュアルの記述が古くインストールが行えない

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#1216]
- [x] markdown のほうのマニュアル修正必要なし #1279 

Installing_on_Herokuの
「Solrの設定ファイルを、EC2上のサーバにコピーします。」以降が現状に即しておらず、インストールが行えません。
1） アプリ名/solr/conf/  が存在しない。アプリ名/solr/configsets/sunspot/conf/ のことか？
2）http://ftp.riken.jp/net/apache/lucene/solr/4.10.4/solr-4.10.4.tgz が配布されていない
Apacheのアーカイブでダウンロードしたが、以降の設定通りでもEC2上のSolrがCollection1 is not avaiableとなる
3）heroku config:set BUILDPACK_URL=https://github.com/HireFrederick/heroku-buildpack-ruby.git が存在しない。あとBuildpackのセットを先に行う必要がある？

**Comment by adamasharpe** [comment]
solrのエラーメッセージです
 {msg=SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1: Plugin init failure for [schema.xml] fieldType "daterange": Error loading class 'solr.DateRangeField'. Schema file is /usr/share/tomcat7/solr/collection1/conf/schema.xml,trace=org.apache.solr.common.SolrException: SolrCore 'collection1' is not available due to init failure: Could not load conf for core collection1: Plugin init failure for [schema.xml] fieldType "daterange": Error loading class 'solr.DateRangeField'. Schema file is /usr/share/tomcat7/solr/collection1/conf/schema.xml at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:745) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:307) at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:218) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103) at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:956) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:442) at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1082) at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:623) at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:745) Caused by: org.apache.solr.common.SolrException: Could not load conf for core collection1: Plugin init failure for [schema.xml] fieldType "daterange": Error loading class 'solr.DateRangeField'. Schema file is /usr/share/tomcat7/solr/collection1/conf/schema.xml at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66) at org.apache.solr.core.CoreContainer.create(CoreContainer.java:489) at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255) at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249) at java.util.concurrent.FutureTask.run(FutureTask.java:262) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) ... 1 more Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "daterange": Error loading class 'solr.DateRangeField'. Schema file is /usr/share/tomcat7/solr/collection1/conf/schema.xml at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:595) at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166) at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55) at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69) at org.apache.solr.core.ConfigSetService.createIndexSchema(ConfigSetService.java:90) at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:62) ... 7 more Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "daterange": Error loading class 'solr.DateRangeField' at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:177) at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:486) ... 12 more Caused by: org.apache.solr.common.SolrException: Error loading class 'solr.DateRangeField' at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:490) at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:521) at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:517) at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:81) at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:43) at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:151) ... 13 more Caused by: java.lang.ClassNotFoundException: solr.DateRangeField at java.net.URLClassLoader$1.run(URLClassLoader.java:366) at java.net.URLClassLoader$1.run(URLClassLoader.java:355) at java.security.AccessController.doPrivileged(Native Method) at java.net.URLClassLoader.findClass(URLClassLoader.java:354) at java.lang.ClassLoader.loadClass(ClassLoader.java:425) at java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:793) at java.lang.ClassLoader.loadClass(ClassLoader.java:358) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:278) at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:474) ... 18 more ,code=500}

**Comment by nabeta** [comment]
Solrは4.10.4ということですね。手順を再度確認しますので、しばらくお待ちください。

**Comment by adamasharpe** [comment]
この件はどうなっているのでしょうか。EC2にコピーする/solr/conf/に相当するフォルダと内容はどこでしょうか。

**Comment by nabeta** [comment]
Herokuへのインストールを書き直しています。sunspot_solrにあわせて、Solrのバージョンを5.xに上げています。
https://github.com/next-l/enju_leaf/wiki/Installing_on_Heroku

ただ、現時点ではSolrへの認証がなく、またHerokuのIPアドレスを特定できないため、IPアドレスによるアクセス制限もかけられないという問題があります。設定方法のマニュアルはあるのですが、まだ手元の環境で動作させられていません。
https://cwiki.apache.org/confluence/display/solr/Basic+Authentication+Plugin

**Comment by adamasharpe** [comment]
git push heroku master
でエラーになります

**Comment by nabeta** [comment]
@adamasharpe エラーログを見せていただけますか？

**Comment by nabeta** [comment]
2018年6月の段階でもう一度ドキュメントを確認する。

**Comment by yegusa** [comment]
@masao がドキュメント通りにやってできるかどうか確認するとなりました。 Enju WS 2018-06-10の議論より

**Comment by yegusa** [comment]
時間も立ったことですし，まずは，一旦クローズします。また同様の問題が起こるようでしたら，再オープン願います。
