### ISSUE TITLE
NDLからのインポート時にエラー（InvalidURI）

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1217]
http://iss.ndl.go.jp/books/R100000002-I000003523406-00 の書誌データの分類の箇所、DDCに [E] という値がはいっています。

このレコードを登録しようとすると、以下のようなエラーになります：
```
An URI::InvalidURIError occurred in ndl_books#create:

  bad URI(is not URI?): http://dewey.info/class/[E]/about
```

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/19018544/22415954-88a1-11e6-8965-7e9c93bbb854.png)

![image](https://cloud.githubusercontent.com/assets/1328499/19018547/4f33409e-88a1-11e6-84a8-3d142f1da89a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_oai (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
