### ISSUE TITLE
書誌データTSVエクスポートにおいてextent, dimensionsを出力する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1220]
#333 & #368 からの派生。

**Comment by masao** [comment]
extent, dimensionsをTSVエクスポート出力するように追加しました。

**Comment by yegusa** [comment]
手元の仮想マシンで、できることを確認しました。のでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/19414969/865b563e-939a-11e6-96b7-44c4aff8c3f5.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 b09de7e)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 bf2a940)
  * enju_library (0.2.0.beta.9 7bbffc5)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3 48764d8)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2 845c20f)
  * enju_oai (0.2.0.beta.3 ff2717c)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
