### ISSUE TITLE
マニュアルが古くインストールが行えない（Amazon EC2へのインストール）

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#1234]
記述のまま進めると
１）redisが入らない
２）railsのバージョンが合わない
３）PostgresqlにPeer authentication failed でログインできずrakeが通らない
など

**Comment by adamasharpe** [comment]
>３）PostgresqlにPeer authentication failed でログインできずrakeが通らない
に関しては、応急でアプリ名とDBのユーザ名を同一にすると回避できました。

**Comment by nabeta** [comment]
書き直しました。
https://github.com/next-l/enju_leaf/wiki/Installing_on_Amazon_EC2

**Comment by adamasharpe** [comment]
現在のマニュアルでは、最後の
RAILS_ENV=production foreman start
で foreman コマンドが見つからず、インストールが完了しません

そして、EC2上にインストールした場合
１）/users/sign_outがThe page you were looking for doesn't exist.
２）スタイルシートが効いていない
３）Javascriptが動作していない（ため、書誌の新規作成で著者などの追加ボタンが動作しない）

**Comment by nabeta** [comment]
以下を試していただけますか。

```sh
$ cd /path/to/enju
$ vi .env
```

```
# .envファイルを以下の内容で作成
RAILS_SERVE_STATIC_FILES=true
```

```sh
$ RAILS_ENV=production bundle exec foreman start
```

**Comment by adamasharpe** [comment]
EC2上で/pathが存在せず、sudo viでも作成できません。

**Comment by nabeta** [comment]
/path/to/enju は、Enjuが実際にインストールしてあるディレクトリに適宜読み替えてください。
Wikiの手順ですと、以下のようになります。

```
$ cd ~/enju_ec2/
```

**Comment by adamasharpe** [comment]
アクセスしても何も出なくなります。

https://github.com/next-l/enju_leaf/wiki/Installing_on_Amazon_EC2/d0d842bf48f44c1e3578f7401cd9e9181d137bc3
の手順で
最後に -b 0.0.0.0オプションを付けて起動しアクセスすると
Missing `secret_token` and `secret_key_base` for 'production' environment, set these values in `config/secrets.yml`
が出るのでトークンを設定する必要があります。
その後アクセスすると
１）/users/sign_outがThe page you were looking for doesn't exist.
２）スタイルシートが効いていない
３）Javascriptが動作していない（ため、書誌の新規作成で著者などの追加ボタンが動作しない）
です。何も解決しません。

**Comment by nabeta** [comment]
以下のコマンドを実行した後、サーバを起動するとどうなりますか。

```sh
$ bundle exec rake assets:precompile
$ echo RAILS_ENV=production >> .env
$ echo SECRET_KEY_BASE=`bundle exec rake secret` >> .env
$ echo RAILS_SERVE_STATIC_FILES=true >> .env
```

また、古いバージョンのページを見ているようです。
https://github.com/next-l/enju_leaf/wiki/Installing_on_Amazon_EC2

**Comment by nabeta** [comment]
#1301 と重複のためcloseします。
