### ISSUE TITLE
デモサーバがエラー

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#1235]
http://dev.next-l.jp/
http://enju.herokuapp.com/
が表示されない

http://enju.next-l.jp/
が書誌の新規作成が出来ない

**Comment by nabeta** [comment]
> http://enju.next-l.jp/
> が書誌の新規作成が出来ない

まずこちらを修正しました。

**Comment by nabeta** [comment]
古いissueのため、closeします。
