### ISSUE TITLE
foremanのエラーでどの手段でもインストール・起動が行えない

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#1236]
ローカルへのインストール最後の手順
bundle exec foreman start
などのforemanで何かあるらしくそれぞれこの段階でエラーになります

**Comment by nabeta** [comment]
@adamasharpe エラーログを見せていただけますか？

**Comment by masao** [comment]
だいぶ前の質問ですので、ひとまずクローズします。最新の安定版で再発するようでしたらまたコメントいただければ幸いです。
