### ISSUE TITLE
フッターのバージョン表記の方法を文書化する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1239]
- [x] マニュアル修正 #1248 

#988 でフッターの文字列をカスタマイズできるようになったが、enju_leafのバージョン文字列（1.2.0など）をそのまま入力しているため、enju_leafを更新しても、バージョンが更新されていないように見える。

**Comment by masao** [comment]
フッタにバージョン番号を表示するのをやめる方向で検討する。
ただし、一般利用者権限でもバージョン番号がわかるとよいので、 /page/about にてバージョン番号を追記する方向で検討すること。
（第55回Enju開発ワークショップでの議論より）

**Comment by masao** [comment]
フッタのMarkdown記法内で  「__VERSION__」 は自動的にバージョン番号に書き換える部分はすでに実装済み。

**Comment by masao** [comment]
標準で、インストール時点のバージョン番号を書き込んでしまうバグがあったため、 __VERSION__ を使うように修正しました。

**Comment by yegusa** [comment]
できることを確認し、マニュアル修正しましたので、クローズします。
