### ISSUE TITLE
init登録　Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by kouamano** [next-l/enju_leaf#1241]
Ubuntu 16.04 LTS 用の起動用スクリプト作成・登録。
正確には、systemd。

**Comment by nabeta** [comment]
以下のコマンドで、ユーザenjuでインストールしている場合のスクリプトが作成されます。

```
$ foreman export systemd --app enju_leaf --user enju /etc/systemd/system/
```

以下のコマンドで起動します。stopで停止、restartで再起動です。

```
$ sudo systemctl start enju_leaf.target
```

**Comment by kouamano** [comment]
環境変数が渡らない?

**Comment by kouamano** [comment]
journalctl -f

12月 18 17:18:08 kamano-VirtualBox sudo[7127]:   kamano : TTY=pts/18 ; PWD=/etc/systemd/system ; USER=root ; COMMAND=/bin/systemctl start enju_leaf.target
12月 18 17:18:08 kamano-VirtualBox sudo[7127]: pam_unix(sudo:session): session opened for user root by kamano(uid=0)
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-solr@5000.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-resque-1.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-resque@5100.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Reached target enju_leaf-resque.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-web-1.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-web@5200.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Reached target enju_leaf-web.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Started enju_leaf-solr-1.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Reached target enju_leaf-solr.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Reached target enju_leaf.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf.target: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped target enju_leaf.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-solr.target: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-resque.target: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-web.target: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-web.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-web-1.service: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-web-1.service...
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-web@5200.service...
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-resque.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-resque-1.service: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-resque-1.service...
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-resque@5100.service...
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-solr.target.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: enju_leaf-solr-1.service: Unit not needed anymore. Stopping.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-solr-1.service...
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopping enju_leaf-solr@5000.service...
12月 18 17:18:08 kamano-VirtualBox sudo[7127]: pam_unix(sudo:session): session closed for user root
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-solr-1.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-solr@5000.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-resque@5100.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-web@5200.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-resque-1.service.
12月 18 17:18:08 kamano-VirtualBox systemd[1]: Stopped enju_leaf-web-1.service.

**Comment by nabeta** [comment]
/var/log/syslog になにかエラーが出ていますか？

**Comment by kouamano** [comment]
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-resque@5100.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-solr-1.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-resque-1.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Reached target enju_leaf-resque.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-web@5200.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-solr@5000.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Reached target enju_leaf-solr.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Started enju_leaf-web-1.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Reached target enju_leaf-web.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Reached target enju_leaf.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf.target: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped target enju_leaf.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-resque.target: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-solr.target: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-web.target: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-web.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-web-1.service: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-web-1.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-web@5200.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-solr.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-solr-1.service: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-solr-1.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-solr@5000.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped target enju_leaf-resque.target.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: enju_leaf-resque-1.service: Unit not needed anymore. Stopping.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-resque-1.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopping enju_leaf-resque@5100.service...
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-resque-1.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-resque@5100.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-solr-1.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-solr@5000.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-web@5200.service.
Jan 28 12:15:36 kamano-VirtualBox systemd[1]: Stopped enju_leaf-web-1.service.

**Comment by kouamano** [comment]
起動許可のために以下を行う
```
$ sudo systemctl enable enju_leaf.target
```

**Comment by nabeta** [comment]
以下にUbuntu 16.04とsystemdを使用するVagrantfileを掲載しました。
https://gist.github.com/nabeta/f521066870964d85c3d81bfdd49a8848

**Comment by masao** [comment]
1.2系仮想マシンの構築を確認しました。クローズします。
