### ISSUE TITLE
デフォルトのインストールテンプレートで mailers キューを指定していない。

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1242]
cf. #1190 
また、インストールマニュアルも記載が必要： https://github.com/next-l/enju_leaf/wiki/Install

**Comment by nabeta** [comment]
仮想マシンの設定スクリプトを修正しました。
https://gist.github.com/nabeta/f521066870964d85c3d81bfdd49a8848#file-enju_leaf_script_ubuntu-xenial-sh-L58

**Comment by nabeta** [comment]
マニュアルのProcfileの設定も修正済みです。
https://github.com/next-l/enju_leaf/wiki/Install#enju-leafの初期設定

**Comment by masao** [comment]
確認しました。クローズします。
