### ISSUE TITLE
書誌の検索結果一覧や詳細表示で登録した資料形態のアイコンを表示できるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1243]
#522 からの派生issue です。

新しく画像ファイルで登録した「資料の形態」のアイコンが、書誌の検索結果一覧で表示したり、書誌詳細で表示したりできるようにする

書誌の検索結果一覧：
![image](https://cloud.githubusercontent.com/assets/1328499/21292110/579e148e-c53c-11e6-9144-7eb72760059a.png)

書誌の詳細表示：
![image](https://cloud.githubusercontent.com/assets/1328499/21292118/85eb2232-c53c-11e6-9102-07671f3a21a7.png)

**Comment by masao** [comment]
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/22394927/790f9566-e571-11e6-9737-8905bbb7873e.png)
検索結果一覧画面でエラーになります。

**Comment by masao** [comment]
表示できるようになったことを確認したのでクローズします。
