### ISSUE TITLE
「資料の形態の表示」（詳細）画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1244]
#522 からの派生issueです。

以下の、個々の資料の形態の表示の詳細画面で、赤四角あたりに、実際のアイコンの画像を表示する（ファイル名だけでなく）

![image](https://cloud.githubusercontent.com/assets/1328499/21292130/fba7a1ee-c53c-11e6-87af-3eba3c54f368.png)

**Comment by masao** [comment]
アイコン画像を追加しました。確認願います。

**Comment by yegusa** [comment]
できたことを確認しましたのでクローズします

![next l enju leaf 3](https://user-images.githubusercontent.com/1328499/34637523-fd019cd2-f2fb-11e7-91b5-240dfdf5824b.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.3 4c47b5d)
  * enju_circulation (0.2.3)
  * enju_event (0.2.1)
  * enju_leaf (1.2.2 f06bff4)
  * enju_library (0.2.3 d0f2371)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.2)
  * enju_ndl (0.2.3)
  * enju_nii (0.2.1)
  * enju_seed (0.2.2)
  * enju_subject (0.2.2)
