### ISSUE TITLE
「資料の形態の一覧」画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1245]
#522 から派生したissue です。

以下の、赤四角のあたりに、アイコンを表示する。

![image](https://cloud.githubusercontent.com/assets/1328499/21292151/bcb2d0c0-c53d-11e6-8212-7001b6dbeed6.png)

**Comment by masao** [comment]
一覧にアイコンが表示されるようになったことを確認したのでクローズします。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/26759808/5fa900b2-4944-11e7-95f0-2a47d3bd9e04.png)
