### ISSUE TITLE
すでに登録された資料の形態のアイコン画像がある場合は、「選択されていません」ではなく、ファイル名を表示

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1246]
#522 から派生です。

すでに登録された資料の形態のアイコン画像がある場合は、「選択されていません」ではなく、
「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像のファイル名を表示するようにする

既に登録している：
![image](https://cloud.githubusercontent.com/assets/1328499/21292191/4246c830-c53f-11e6-8361-95ac2919b4a2.png)

↑の場合、以下の、赤四角は、「選択されていません」ではなく、画像のファイル名を表示する：

![image](https://cloud.githubusercontent.com/assets/1328499/21292187/158b7552-c53f-11e6-94bc-55f6659f8eae.png)

**Comment by nabeta** [comment]
#598 と同様、現在登録されているファイル名の表示、ならびにファイルの削除機能を追加しました。
https://dev.next-l.jp/carrier_types/1/edit
![image](https://user-images.githubusercontent.com/11428/163710534-9edf0a4c-e395-4e61-ae5c-c6fc50b50d2e.png)

**Comment by yegusa** [comment]
できているように見えるのでクローズします。

![資料の形態-えんじゅ図書館-Next-L-Enju-Leaf](https://user-images.githubusercontent.com/1328499/174470817-211b3708-6f08-46e8-a584-1451e528e262.png)
