### ISSUE TITLE
新規インストール時に、フッターは __VERSION__ を使うようになっているか確認・なっていなければそうなるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1247]
#988 でフッターの文字列をカスタマイズできるようになったが、enju_leafのバージョン文字列（1.2.0など）をそのまま入力していた場合は、enju_leafを更新しても、バージョンが更新されていないように見えるので、少なくとも新規インストールの場合は、 __VERSION__ を使うようにする。

#1239 に関連。

**Comment by masao** [comment]
この件、1.2.0系のインストールスクリプトを間違えて固定文字列（その時点のバージョン文字列）を埋め込むようにしていたので、この修正を改修した分として、できれば早めに1.2.1を出してしまいたい。。。

**Comment by yegusa** [comment]
開発版を新規インストールしてみましたが、1.2.0 が埋め込まれており、 __VERSION__ はみあたりませんでした。

**Comment by masao** [comment]
新規インストール時に修正すべきファイルが直っていなかったようです。再度、要確認。

**Comment by nabeta** [comment]
1.2系の開発版の新規インストールで、意図する表示になっていることを確認しました。

![next l enju leaf](https://cloud.githubusercontent.com/assets/11428/25562781/b3d6228c-2dc9-11e7-9c0e-a61cad8fe2dd.png)
