### ISSUE TITLE
openBD 対応

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#1249]
https://openbd.jp/

書影が取れるのが大きいと思います。

**Comment by nabeta** [comment]
まず1月23日のセミナーに出席するのが早そうです。昼間なので、年休の申請をしておきますかね。
https://openbd.jp/#event

**Comment by scivola** [comment]
私も行けそうなら行きます

**Comment by nabeta** [comment]
既刊の出版物に対する書影登録のカバー範囲がGoogle Booksなどよりも狭いと思われますので、openBDとGoogle Booksなど、書影の取得元を複数使用できるようにする必要がありそうです。

**Comment by masao** [comment]
書影表示を実装しました。

**Comment by yegusa** [comment]
クローズします

![next l enju leaf](https://cloud.githubusercontent.com/assets/1328499/26759724/8f03d7fe-4941-11e7-8a76-ca69064020a0.png)
openBDに設定して、書影が出ることを確認しました。

![6 1 next l enju leaf](https://cloud.githubusercontent.com/assets/1328499/26759715/556911a8-4941-11e7-9748-f707de8294af.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
