### ISSUE TITLE
書棚の一覧で削除リンクが表示されないことがある

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1250]
書棚の一覧では、その書棚に紐付く所蔵が0件の場合、「削除」リンクが表示される。
http://enju.next-l.jp/shelves

ところが、所蔵が0件にもかかわらず、「削除」リンクが表示されない場合がある。

**Comment by nabeta** [comment]
書棚の削除リンクの表示には、「その棚の所蔵件数が空であること」としており、Enjuではこの条件を、以下のように"itemsがemptyであること"と表現している。
https://github.com/next-l/enju_library/blob/1.1/app/models/enju_library/ability.rb#L20

この条件をコンソールで確認してみたところ、以下のような挙動を示す。

```ruby
irb(main):006:0> shelf = Shelf.find(8) # 所蔵が0件と表示されている棚の情報を取得
=> #<Shelf id: 8, name: "stock_3", display_name: "一般書ロータリー3(歌津）", note: "", library_id: 2, items_count: -325, position: 6, created_at: "2012-06-14 05:48:05", updated_at: "2012-12-26 03:14:54", deleted_at: nil, closed: true, shelf_type_id: 1>
irb(main):007:0> shelf.items.empty? # 所蔵が空かを問い合わせる
=> false # 空ではないと返ってくる???
irb(main):008:0> shelf.items.count # 所蔵件数を取得
=> 0 # しかし0件
irb(main):010:0> shelf.items # 実際の所蔵を取得
=> #<ActiveRecord::Associations::CollectionProxy []> # 空
irb(main):011:0> shelf.items.empty? # 再度所蔵が空かを問い合わせる
=> true # 今度は正しく空だと返ってくる
irb(main):012:0> shelf.items.count # 再度所蔵件数を取得
=> 0 # やはり0件
```

所蔵が0件にもかかわらず、shelf.items.empty? がfalseを返すため、削除リンクが表示されないと思われる。

**Comment by nabeta** [comment]
この件はおそらくRailsのcounter_cacheが影響しているのではないかと思われる。
http://railsdoc.com/references/counter_cache

Enjuでは書架一覧で所蔵件数を表示するために、この機能を使って書棚の件数をキャッシュしている。development環境を使って調べてみること。
https://github.com/next-l/enju_library/blob/1.1/db/migrate/069_create_shelves.rb#L8

なお、この問題は1.1系で報告されたが、1.2系でも削除リンク表示の判定条件は同じ表現をしているため、同様の問題があると思われる。
https://github.com/next-l/enju_library/blob/1.2/app/policies/shelf_policy.rb#L20

**Comment by nabeta** [comment]
南三陸町向けに追加した修正をこちらにも取り込みました。

**Comment by masao** [comment]
一応、手元でいくつかテストしてみましたが、問題ないようなのでひとまずクローズします。
