### ISSUE TITLE
資料種別(carrier_type)をエクスポート出力する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1251]
- [ ] #1248 マニュアル修正

#404 からの派生。書誌・所蔵のエクスポートにおいて、資料種別項目（carrier_type）がエクスポートされていないので、出力できるようにしたい。

**Comment by masao** [comment]
エクスポート項目に加えました。

**Comment by yegusa** [comment]
手元の仮想マシンでできることを確認しました。
のでクローズします。マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/22394392/5f540f3e-e563-11e6-9c7c-c7443ca8519a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0 002806a)
  * enju_bookmark (0.2.0)
  * enju_circulation (0.2.0 9daf9cb)
  * enju_event (0.2.0)
  * enju_leaf (1.2.0 a25e1bf)
  * enju_library (0.2.1 c75a94a)
  * enju_loc (0.2.0 071f2b3)
  * enju_manifestation_viewer (0.2.0 f1fddb6)
  * enju_message (0.2.0)
  * enju_ndl (0.2.0 da6beb7)
  * enju_nii (0.2.0 03c3dc4)
  * enju_oai (0.2.0 6e5cd6d)
  * enju_purchase_request (0.2.0)
  * enju_seed (0.2.0)
  * enju_subject (0.2.0)
