### ISSUE TITLE
TSVエクスポートで、書誌情報にこれまでの貸出回数（累計）を出力して欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1254]
- [ ] マニュアル修正 #1248 

#877 より派生です。

南三陸町案件です。

**Comment by masao** [comment]
実装しました。確認願います。

**Comment by yegusa** [comment]
total_checkouts に貸し出し回数が表示されることを確認しました。
クローズします。

![2017-06-05 20 31 33](https://cloud.githubusercontent.com/assets/1328499/26782441/9748d9bc-4a2e-11e7-99ed-3fcee6ed8494.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
