### ISSUE TITLE
「資料の形態」の既存アイコンの保存場所を変更する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1256]
#522 に関連。現在はデフォルトの「資料の形態」（volumeなど）は静的画像ファイルを表示しており、「編集」画面でアップロードしたファイルが表示されていない。1.2.1へのアップデートスクリプトで既存のファイルの保存場所を移動すること。

**Comment by nabeta** [comment]
以下のコマンドでアイコンの移行を行います。

```sh
$ rake enju_biblio:upgrade RAILS_ENV=production
```

**Comment by masao** [comment]
修正を確認しました。クローズします。
