### ISSUE TITLE
ライブラリアンが貸出期間の延長時に誤った日付を入力するとRailsエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1257]
貸出期間の延長画面でライブラリアン権限だと、任意の日付を入力できますが、この際に誤った日付を入れるとRailsエラーになります。エラーメッセージを表示して修正を促すべきと思います。
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/23240940/8c83de6c-f9b3-11e6-8e4d-93b017d06243.png)

**Comment by nabeta** [comment]
上記の例だと"2017-03-151"が入力されているのですね。調べてみます。

**Comment by nabeta** [comment]
バリデーションによるエラーを表示するように修正しました。テストも書いています。

**Comment by masao** [comment]
エラー画面に飛ばなくなりましたが、エラーメッセージを追加する必要がありそうです。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/24327008/f029e1aa-11ff-11e7-8196-dbab6954ee69.png)

**Comment by nabeta** [comment]
エラーメッセージを修正しました。ただ、現時点では誤って入力された値がエラー画面で消えてしまいます。

<img width="490" alt="2017-04-09 0 55 39" src="https://cloud.githubusercontent.com/assets/11428/24830341/4d5c0d7a-1cbf-11e7-8c37-59b2eea04f8c.png">

**Comment by masao** [comment]
エラーメッセージの修正を確認しました。ひとまずクローズします。
