### ISSUE TITLE
図書館全体のメールアドレスの設定

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1260]
- [x] マニュアルの修正 #1066

図書館の全体のメールアドレスの設定は、enju_leaf-1.2.0で「利用者の管理」から「図書館全体の設定」に移動している。移動の経緯を書くこと。

**Comment by masao** [comment]
編集画面: http://enju.next-l.jp/library_groups/1/edit

**Comment by yegusa** [comment]
2016-08-14 の編集ですね。

**Comment by yegusa** [comment]
https://github.com/next-l/enju_library/releases v0.2.0.beta.8 が 2016-08-14 14:36 JST  

https://github.com/next-l/enju_leaf/releases Next-L Enju Leaf 1.2.0.beta.3 が 2016-08-14 21:56JST ですね。

**Comment by yegusa** [comment]
田辺さんの会話から察するに、ちょうど、このころ、利用者へのリマインダーや、図書館へのリマインダーを頻繁にしたいというニーズがNIMSであったようで、そのときに、お知らせで使うメールアドレスを変えやすくしたいというニーズから、「図書館全体の設定」の画面で完結して、メールアドレスを変更できたほうがよいと判断したのではないかとのこと。

**Comment by yegusa** [comment]
どのような仕様変更であるかの江草の理解

1.1 系では、「図書館全体の設定」ではメールは「編集」リンクとなっており、

1.1系の「図書館全体の設定」
![image](https://cloud.githubusercontent.com/assets/1328499/23329205/fa60ba26-fb76-11e6-99fc-53d54570b519.png)

1.1系の「図書館全体」の「メールアドレス」はsysytemユーザ画面でのみ編集可能
![image](https://cloud.githubusercontent.com/assets/1328499/23329211/3a80c29a-fb77-11e6-8782-fc9fe9c7e4e2.png)

それを、1.2系では「図書館全体の設定」の画面のみで「メールアドレス」を修正できるように変更。
（また、systemユーザ画面で編集も可能で、こちらの編集画面にも反映される）

1.2系の「図書館全体の設定」
![image](https://cloud.githubusercontent.com/assets/1328499/23329216/73013fd2-fb77-11e6-81ce-6ace6bfe37a9.png)

**Comment by yegusa** [comment]
マニュアルを修正済み。

**Comment by yegusa** [comment]
メールアドレスが修正できることもかくにん済み。マニュアルも修正したので、クローズする。
