### ISSUE TITLE
複数の利用者情報が同一ユーザに紐付いてしまう

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1261]
利用者情報(Profile)はユーザ(User)にbelongs_to関係で紐付けられている。
https://github.com/next-l/enju_seed/blob/1.2/app/models/profile.rb#L6

しかし、profilesテーブルのuser_idにユニーク制約がないため、複数の利用者情報を同一ユーザに紐付けられてしまう。以下が例。

<img width="500" alt="2017-02-25 15 19 41" src="https://cloud.githubusercontent.com/assets/11428/23328809/e0e200fe-fb6d-11e6-89cf-e1dacba5dc97.png">

**Comment by nabeta** [comment]
現時点ではバリデーションを追加している。
https://github.com/next-l/enju_seed/blob/1.2/app/models/profile.rb#L15

**Comment by masao** [comment]
特にGUI挙動としてはチェックしようもなさそうなので、ひとまずクローズします。
