### ISSUE TITLE
既存の資料の形態アイコンが表示できない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1265]
#1256 からの派生。資料の形態アイコンがアップロードする方式に変更されたため、既存のアイコン群を新方式に移行する必要がある。
移行の方式を文書化すること。または、移行スクリプトとしてまとめること。

**Comment by nabeta** [comment]
移行スクリプトを追加しました。
https://github.com/next-l/enju_leaf/issues/1256#issuecomment-298215515

**Comment by nabeta** [comment]
画像の移行スクリプトに誤りがありました。enju_biblio-0.2.2で修正予定です。

**Comment by masao** [comment]
移行スクリプトを含めて修正を確認したのでクローズします。
