### ISSUE TITLE
未ログイン状態で資料の形態アイコンが表示できない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1266]
#1256 からの派生。資料の形態全体(/carrier_types以下)が、図書館員権限以上を必要とするようになっているため、未ログインユーザからはアイコンが表示されなくなっている。

**Comment by nabeta** [comment]
アイコンのみ非ログイン状態でもアクセスできるようにしました。テストも記述済みです。

**Comment by masao** [comment]
アイコン表示がエラーになるようです。ログイン状態・非ログイン状態いずれでも。
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/24327042/d23bb758-1200-11e7-8ea3-ac9162d175a9.png)

**Comment by nabeta** [comment]
こちらも修正済みです。
http://enju.next-l.jp/carrier_types/1.download

**Comment by masao** [comment]
修正を確認したのでクローズします。
