### ISSUE TITLE
イベント一覧画面で絞り込み検索が動作しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1267]
#1196 と同様。イベント一覧画面 (/events) は以下のパラメータで絞り込みが可能ですが、複数のパラメータを使ったファセット絞り込みが動作しません：
・検索語
・過去・現在の区分
・図書館

**Comment by nabeta** [comment]
絞り込みのリンクを修正しました。デモサーバに反映済みです。
https://enju.next-l.jp/events?utf8=%E2%9C%93&query=%E5%85%A5%E5%8A%9B&commit=%E6%A4%9C%E7%B4%A2

**Comment by masao** [comment]
修正を確認しました。クローズします。
