### ISSUE TITLE
予約一覧画面にて絞り込み検索が動作しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1268]
#1196 と同様。予約一覧画面 (/reserves) は以下のパラメータで絞り込みが可能ですが、複数のパラメータを使ったファセット絞り込みが動作しません：
・検索語
・予約時刻（from - to）
・予約状態

**Comment by nabeta** [comment]
絞り込みのリンクを修正しました。
https://enju.next-l.jp/reserves?utf8=✓&query=&reserved_from=&reserved_until=&commit=検索

**Comment by masao** [comment]
修正を確認しました。クローズします。
