### ISSUE TITLE
貸出の一覧画面にて絞り込み検索が動作しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1269]
#1196 と同様。
（図書館員権限の場合）貸出履歴一覧画面（/checkouts）では、以下のパラメータでファセット絞り込み等がを行えるが、これら複数のパラメータを用いた絞り込みが行えない：
・自分の貸出
・延滞
・予約の有無

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
できているようなのでクローズします

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0 7364cad)
  * enju_circulation (0.2.1 5556e7d)
  * enju_event (0.2.0)
  * enju_leaf (1.2.0)
  * enju_library (0.2.1)
  * enju_manifestation_viewer (0.2.0)
  * enju_message (0.2.0)
  * enju_ndl (0.2.0)
  * enju_seed (0.2.0)
  * enju_subject (0.2.0)


自分の貸し出しの方は確かめました

貸出履歴を見ているところ、「自分の貸出」をクリック
![next l enju leaf](https://cloud.githubusercontent.com/assets/1328499/25562406/6ac89e16-2dc0-11e7-9f84-b3cdf5e5cad8.png)

自分の貸出だけが表示される、予約の「いいえ」をクリック
![next l enju leaf 1](https://cloud.githubusercontent.com/assets/1328499/25562407/710edeb6-2dc0-11e7-8855-39e99e61f385.png)

自分の貸し出しの予約が「いいえ」のものだけが表示される
![next l enju leaf 2](https://cloud.githubusercontent.com/assets/1328499/25562408/78c8e6a6-2dc0-11e7-8a01-ac9f6b89ca7d.png)
