### ISSUE TITLE
ファセット検索後にソート方式を切り替えた場合、絞り込み条件を引き継がない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1270]
- [x] バグ修正なのでマニュアル修正関係ない #1248

ファセット絞り込み検索したあとの画面で、ソート方式を切り替えると、ファセット絞り込み条件を反映しないバグがあるようです。
#1196 とは別の現象と思われるので、別Issueとします。

**Comment by masao** [comment]
enju_biblio を修正しました。確認願います。

**Comment by yegusa** [comment]
確認しました。クローズします。

ファセットで、英語を選んだところ
![next l enju leaf 4](https://cloud.githubusercontent.com/assets/1328499/26781734/1ac1145c-4a2b-11e7-8c35-a609c0669264.png)

ここで、ソート方法を変えて見たところ
![next l enju leaf 5](https://cloud.githubusercontent.com/assets/1328499/26781820/6066998c-4a2b-11e7-8397-d7f10f15c350.png)

ファセットでの絞り込みを引き継ぎつつ、ソートもちゃんとできているのを確認しました。

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
