### ISSUE TITLE
公式サイトの1.2.0のVirtualBoxでbundle updateしたら起動できなくなった(production環境)

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1271]
- [x] 解決方法判明
- [ ] wikiにドキュメントを書く

Gemifile はこの2行を書き換えて

<pre>
49a50
> gem 'enju_biblio', github:'next-l/enju_biblio', branch:'1.2'
51c52,53
< gem 'enju_circulation', '~> 0.2.0'
---
> #gem 'enju_circulation', '~> 0.2.0'
> gem 'enju_circulation', github:'next-l/enju_circulation', branch:'1.2'
</pre>

$ bundle update

したら、502 Bad Gateway になるようになりました。

コンソールを立ち上げようとした時のメッセージは以下の通りです

<pre>
vagrant@vagrant:~/enju$ rails c production
/home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.2/lib/active_support/cache/redis_store.rb:38:in `dup': can't dup NilClass (TypeError)
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.2/lib/active_support/cache/redis_store.rb:38:in `map'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/redis-activesupport-5.0.2/lib/active_support/cache/redis_store.rb:38:in `initialize'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:60:in `new'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/cache.rb:60:in `lookup_store'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application/bootstrap.rb:76:in `block in <module:Bootstrap>'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
	from /home/vagrant/enju/config/environment.rb:5:in `<top (required)>'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:328:in `require_environment!'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/railties-4.2.8/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
</pre>

**Comment by nabeta** [comment]
@yegusa config/environments/production.rb に config.cache_store という行があると思うのですが、その行を見せてもらえますか。

**Comment by yegusa** [comment]
# Use a different cache store in production.
  config.cache_store = :redis_store, ENV['REDIS_URL'], { expires_in: 1.day }

**Comment by nabeta** [comment]
環境変数REDIS_URLを明示的に設定しないといけなくなったようです。

1. .env ファイルに以下を記入してください。

```
REDIS_URL=redis://127.0.0.1/enju_leaf
```

2. 以下のコマンドを実行してください。

```
$ sudo foreman export systemd /etc/systemd/system -u vagrant -a enju_leaf
$ sudo systemctl daemon-reload
$ sudo systemctl restart enju_leaf.target
```

**Comment by yegusa** [comment]
立ち上がりました！

wikiにも書いておいてください。

**Comment by nabeta** [comment]
Updateに記入しました。
https://github.com/next-l/enju_leaf/wiki/Update

**Comment by masao** [comment]
修正を確認したのでクローズします
