### ISSUE TITLE
systemdエラーについて文書化する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1277]
#1173 からの派生。systemdの起動時エラーが起きた場合に確認すべきログファイルの場所等について文書化したい。

**Comment by nabeta** [comment]
Ubuntu 16.04の場合、ログは /var/log/syslog 以下に出力されます。

**Comment by nabeta** [comment]
1.4.0以降ではDockerによる配布を行うため、対応なしとさせてください。
