### ISSUE TITLE
目次，内容細目などを追加することができるようにデータベースを拡張して欲しい

### ISSUE THREAD

**Issue by ineku** [next-l/enju_leaf#1284]
既にOpenBDが提供するほか，日外アソシエーツが提供するものや，NIIが提供するもの，NDLサーチが提供するものなどを記録できるようにして欲しい

**Comment by masao** [comment]
#296 目次フィールドについてはLCからの書誌データ取り込み時に提案済みです。
これは次期バージョンに追加してしまいましょう。

**Comment by nabeta** [comment]
#296 と重複とみなしてcloseします。
