### ISSUE TITLE
Enjuくんのファビコンを設定する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1293]
- [x] makrdown のマニュアル修正の必要なし #1279

**Comment by nabeta** [comment]
@yegusa これはEnjuの仮想マシンに同梱するという話でしょうか？

**Comment by yegusa** [comment]
そんなイメージです　→ @nabeta

**Comment by nabeta** [comment]
favicon.ico もヘッダーのバナーの保存コマンドでコピーするようにしました。public/favicon.ico にコピーされます。

```sh
$ rake enju_leaf:load_asset_files RAILS_ENV=production
```

アイコンのファイルは以下にあります。
https://github.com/next-l/enju_leaf/blob/1.2/app/assets/images/enju_leaf/favicon.ico

**Comment by yegusa** [comment]
1.2.2の仮想マシンのファビコンができていることを確認しましたのでクローズします

![2018-01-08 17 55 05](https://user-images.githubusercontent.com/1328499/34664572-dd308094-f49f-11e7-8d70-8fb03a8f106c.png)
