### ISSUE TITLE
Enjuくんのバナーをフッターかヘッダーに設定する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1294]

**Comment by nabeta** [comment]
これをフッターの右側に追加する。

![enju-logo-yoko-without-white](https://user-images.githubusercontent.com/11428/31573518-926856da-b0f8-11e7-87b1-6da492124367.png)

**Comment by masao** [comment]
この機能、事前の設定（DBマイグレーション？）が必要でしょうか。

**Comment by masao** [comment]
下記のようなエラーになります。
環境は以下の通り：
  * enju_biblio (0.2.3)
  * enju_circulation (0.2.3 44b669c)
  * enju_event (0.2.1)
  * enju_grid (0.2.0)
  * enju_leaf (1.2.2 60d76ef)
  * enju_library (0.2.3 cf17937)
  * enju_loc (0.2.0 9115035)
  * enju_manifestation_viewer (0.2.1 62d410a)
  * enju_message (0.2.2)
  * enju_ndl (0.2.3 7cda0a6)
  * enju_nii (0.2.1 f6de2a1)
  * enju_oai (0.2.0 778ffe2)
  * enju_seed (0.2.2 f7545ec)
  * enju_subject (0.2.2)

![action controller exception caught 3](https://user-images.githubusercontent.com/38825/34635194-5d8c522c-f2cf-11e7-8ab3-4efd5b33c41b.png)

**Comment by nabeta** [comment]
@masao はい、必要です。

```
$ rake enju_library_engine:install:migrations
$ rake db:migrate
```

**Comment by masao** [comment]
一応、エラーは出なくなりました。
https://github.com/next-l/enju_leaf/wiki/Update への記載もお願いします。

**Comment by nabeta** [comment]
以下に追加しました。
https://github.com/next-l/enju_leaf/wiki/Update#121から122へのアップデート手順

**Comment by nabeta** [comment]
以下のコマンドで、Enjuくんをヘッダーに設定します。RAILS_ENVは適宜設定してください。

```sh
$ rake enju_leaf:load_asset_files RAILS_ENV=production
```

このコマンドは新規インストール時にも実行されます。

**Comment by nabeta** [comment]
ヘッダーにアップロードされたファイルは、縦80ピクセルにリサイズされます。

**Comment by yegusa** [comment]
確認しましたので、クローズします。

rake enju_library_engine:install:migrations
rake db:migrate
rake db:migrate RAILS_ENV=production
rake enju_leaf:load_asset_files RAILS_ENV=production
sudo systemctl restart enju_leaf.target

で、できることを確認しました。

![next l enju leaf 14](https://user-images.githubusercontent.com/1328499/34646609-1a83dcf2-f3b0-11e7-90e0-400a21eddf27.png)
