### ISSUE TITLE
書誌と所蔵のTSVエクスポートの注記や説明の改行をエスケープする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1296]
書誌と所蔵のTSVエクスポートの注記や説明の改行がはいっているとそのまま入っている。

そのため、TSVをExcelなどで読み込んだときに、違う行になってしまってこまるので、
改行は「空白に変える」or 「 \n にする」など、エスケープすべき

- [x] 書誌：注記
- [x] 書誌：説明
- [x] 所蔵：注記

（南三陸町図書館の依頼によって、蔵書リストを作成しようとして気づいた）
（南三陸町図書館案件）

確認した環境：
Ruby: ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux]
Environment: production
enju_biblio: 0.2.2
enju_circulation: 0.2.2
enju_event: 0.2.1
enju_leaf: 1.2.1
enju_library: 0.2.2
enju_manifestation_viewer: 0.2.1
enju_message: 0.2.1
enju_ndl: 0.2.1
enju_seed: 0.2.1
enju_subject: 0.2.1

**Comment by masao** [comment]
一通り実装しました。改行コードはすべて「\n」に置換されて出力されます。

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。

```
manifestation_id	original_title	title_transcription	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	description	note	extent	dimensions	carrier_type	edition	edition_string	volume_number	volume_number_string	issue_number	issue_number_string	serial_number	isbn	issn	jpno	doi	iss_itemno	lccn	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:ndc8	classification:ndc10	item_id	item_identifier	call_number	item_note	item_price	acquired_at	accepted_at	bookstore	budget_type	total_checkouts	circulation_status	shelf	library	item_created_at	item_updated_at
12	タイトル読みと版のテスト	タイトルよみとはんのてすと					""		2018-01-06 15:29:24 +0900	2018-01-07 11:27:57 +0900		""	bababa\nbububu\nzzzz	tetete\nhohoho\nbububu	""	""	volume	3	三		""		""																6	888777		ばばば\nぶぶぶ\nべべべ						0	Available On Shelf	first_shelf	kasuga	2018-01-07 11:27:57 +0900	2018-01-07 11:27:57 +0900
```

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.3 ce3788c)
  * enju_circulation (0.2.3)
  * enju_event (0.2.1)
  * enju_leaf (1.2.2 c4530a4)
  * enju_library (0.2.3 6e1638a)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.2)
  * enju_ndl (0.2.3)
  * enju_nii (0.2.1)
  * enju_seed (0.2.2)
  * enju_subject (0.2.2)
