### ISSUE TITLE
パスワード変更が機能しない

### ISSUE THREAD

**Issue by masagtj** [next-l/enju_leaf#1297]
- [x] markdown のマニュアルを修正する必要なし #1279

v1.2.1 
デモサーバで確認

再現手順
ログイン後 アカウント→パスワード変更
http://enju.next-l.jp/users/edit

表示メッセージ
> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

**Comment by nabeta** [comment]
@masagtj お知らせありがとうございます。修正し、デモサーバに反映済みです。

なお、 app/models/user.rb を以下のように修正する必要があります。

変更前:

```
devise :database_authenticatable, #:registerable,
```

変更後:

```
devise :database_authenticatable, :registerable,
```

**Comment by tuyoshia** [comment]
新規インストール状態でパスワードの変更ができることを確認しました。

**Comment by nabeta** [comment]
1.3.0に修正が取り込まれていませんでしたので、reopenします。

**Comment by nabeta** [comment]
すでに1.3をインストールしている環境では、 app/models/user.rb に以下の変更を行ってください。
https://github.com/next-l/enju_leaf/issues/1297#issuecomment-335015051

**Comment by masao** [comment]
修正を確認しました。クローズします。
