### ISSUE TITLE
例によってインストールがマニュアル通りでは行えない

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#1301]
Amazon EC2でのインストールがマニュアル通りに勧めてもエラーになります

**Comment by masao** [comment]
手元では再現しませんね。マニュアル通りにしても実行していっても起動します:
http://52.193.210.202:3000/

ちなみに、エラーメッセージはどんな内容でしょうか？

なお、途中で以下のような PG ライブラリの警告がでますが、これは今のところ、無視してよいようです：
```
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/ec2-user/enju_ec2/vendor/bundle/ruby/2.3/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
```

ただし、上記画面でもわかるかもしれませんが、EC2インストールマニュアルのrailsテンプレートが 1.1系のままですね。。。
```
$ rails new enju_ec2 -m https://gist.github.com/5357321.txt -d postgresql --skip-bundle
```
cf. https://gist.github.com/nabeta/5357321 これはさすがに更新したいですね。

**Comment by adamasharpe** [comment]
起動するように書き直しました。
https://github.com/next-l/enju_leaf/wiki/Installing_on_Amazon_EC2/dcb8a0eaa1ab577805553795f478d1786569cc87
旧バージョンと見比べてもらえれば分かります。

**Comment by masao** [comment]
ありがとうございます。確認しました。クローズします。
