### ISSUE TITLE
「版」を書誌TSV一括インポートできるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1302]

**Comment by masao** [comment]
一応、版情報はすでにインポートできるようになっていたようです。テストを追加しました。

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。

![image](https://user-images.githubusercontent.com/1328499/34637394-087ffa0c-f2f9-11e7-8d9d-8717779f32e4.png)

![next l enju leaf 1](https://user-images.githubusercontent.com/1328499/34637395-0e6ca2ee-f2f9-11e7-8717-7359bf7dcf41.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.3 4c47b5d)
  * enju_circulation (0.2.3)
  * enju_event (0.2.1)
  * enju_leaf (1.2.2 f06bff4)
  * enju_library (0.2.3 d0f2371)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.2)
  * enju_ndl (0.2.3)
  * enju_nii (0.2.1)
  * enju_seed (0.2.2)
  * enju_subject (0.2.2)
