### ISSUE TITLE
「版」を書誌TSVエクスポートできるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1303]
#1302 と対です

**Comment by masao** [comment]
edition（数値）および edition（文字列）の2つをエクスポート出力するように機能追加しました。
それぞれ edition, edition_string というフィールド名です。

**Comment by yegusa** [comment]
版の数値と文字列両方がエクスポートできることをかくにんしました
ので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/34636986-d31617e2-f2ef-11e7-9d4d-45d53a33d927.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.3 b0432f5)
  * enju_circulation (0.2.3)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.3)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.2)
  * enju_ndl (0.2.3)
  * enju_nii (0.2.0)
  * enju_seed (0.2.2)
  * enju_subject (0.2.2)
