### ISSUE TITLE
貸出状態の返却期限に初回の貸出期限が表示される

### ISSUE THREAD

**Issue by masagtj** [next-l/enju_leaf#1307]
資料の検索→所蔵を表示

確認手順
1.One piece 巻1を10/13まで貸出
2.One piece 巻1を返却
3.One piece 巻1を10/16まで貸出

資料の検索→所蔵を表示で貸出状態に10/13が期限と表示される

**Comment by nabeta** [comment]
@masagtj お知らせありがとうございます。修正しました。
https://enju.next-l.jp/manifestations/12467

**Comment by masao** [comment]
修正を確認しました。クローズします。
もし再度問題等ありましたら、ご連絡いただければ幸いです
