### ISSUE TITLE
Web-API(JSON)にISBNが含まれないケースがある

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1309]
http://minamisanriku.next-l.jp/manifestations.json?utf8=%E2%9C%93&query=%E5%8D%97%E4%B8%89%E9%99%B8&commit=%E6%A4%9C%E7%B4%A2

HTMLの場合は表示されるISBNがJSONに表示されない

**Comment by nabeta** [comment]
JSON出力は実は公式にはサポートしていないので、この際新規でまともに作り直したほうがよいのですが、どんなフォーマットがいいですかね。 @ryuuji @masao 

- JSON-LD
- NDLサーチ準拠  http://iss.ndl.go.jp/information/wp-content/uploads/2017/03/json_format_ver1.2_20170322.pdf

**Comment by masao** [comment]
#1451 にてISBN情報も出力されるようになりました。
https://enju.next-l.jp/manifestations.json

**Comment by masao** [comment]
こちらも出力はできているようなのでひとまずクローズします。

**Comment by yegusa** [comment]
こちらも、1.3.4なのではないか？
