### ISSUE TITLE
Web-API(JSON)に出版者を追加してほしい

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1310]
http://minamisanriku.next-l.jp/manifestations.json?utf8=%E2%9C%93&query=%E5%8D%97%E4%B8%89%E9%99%B8&commit=%E6%A4%9C%E7%B4%A2

基本情報として出版者を追加したい。
出版地は表示されている。

**Comment by yegusa** [comment]
#1322 で議論した後に、検討することになりました。 Enju WS 2018-06-10 の議論より。

**Comment by masao** [comment]
#1451 にて出版者情報も追加されるようになりました。より標準準拠のJSON形式は難しそうなので、ペンディングで。

**Comment by masao** [comment]
ひとます出力はされているようなので、クローズします。

**Comment by yegusa** [comment]
これ、1.3.4じゃないの？ #1451 は1.3.4だよ？
