### ISSUE TITLE
ISBNの検索がハイフン厳密になっている

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1311]
- [x] バグなのでマニュアル修正の必要なし #1279

#1071 と関連すると思われるが
南三陸で運用されているNext-L Enju Leaf 1.2.1でも解消されていないため念のため報告します

**Comment by masao** [comment]
こちら、一時的な現象でしょうか?
現時点では、以下のように、ハイフン有無・10/13桁のいずれでもヒットするようになっているようです。

（デモサーバ）
* https://enju.next-l.jp/manifestations?isbn=978-4-8122-1553-1
* https://enju.next-l.jp/manifestations?isbn=9784812215531
* https://enju.next-l.jp/manifestations?isbn=4-8122-1553-6
* https://enju.next-l.jp/manifestations?isbn=4812215536

（南三陸町）
* http://minamisanriku.next-l.jp/manifestations?isbn=4062598620
* http://minamisanriku.next-l.jp/manifestations?isbn=4-06-259862-0
* http://minamisanriku.next-l.jp/manifestations?isbn=9784062598620
* http://minamisanriku.next-l.jp/manifestations?isbn=978-4-06-259862-0

**Comment by masao** [comment]
ひとまず、現時点では問題が解決しているようなので、クローズします。
