### ISSUE TITLE
10桁・13桁を考慮したISBN検索

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1312]
- [x] バグなのでマニュアル修正の必要なし #1279 

現在は、書誌データに入力されている桁数のISBNしか検索にヒットしませんが、
10桁の場合は暗黙的に978として13桁も検索するようにならないでしょうか。

**Comment by nabeta** [comment]
検索インデックスは10桁と13桁の両方で作成しているので、
https://github.com/next-l/enju_biblio/blob/1.2/app/models/manifestation.rb#L752-L763

以下のように両方ヒットするはずです。
https://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=isbn_sm%3A4499281660&commit=%E6%A4%9C%E7%B4%A2
https://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=isbn_sm%3A9784499281669&commit=%E6%A4%9C%E7%B4%A2

もしヒットしない例がありましたら、教えていただけますでしょうか。

**Comment by masao** [comment]
こちらもひとまず、現時点で問題が再現できないようなので、クローズします。
