### ISSUE TITLE
Web-API(TSV)に巻号を追加してほしい

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1313]
Web-APIのTSVについて、巻号が書誌同定のために不足するため、標準で追加してほしい

**Comment by yegusa** [comment]
コードを読むと、巻= volume しかできない気が？
号もできます？

**Comment by yegusa** [comment]
- [ ] 巻：volume_number_string
- [ ] 巻（数字）：volume_number
- [ ] 号：issue_number_string
- [ ] 号（数字）issue_number

**Comment by yegusa** [comment]
全てできていることを確認しました。クローズします。

テストデータ

original_title	dimensions	volume_number_string	volume_number	issue_number_string	issue_number	serial_number
テストな書名2	20cm	1kann	1	2gou	2	3

インポート結果：
![2 next l enju leaf](https://user-images.githubusercontent.com/1328499/33241943-640fc054-d310-11e7-9e21-f36161b35a2d.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2)
  * enju_circulation (0.2.1)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_loc (0.2.0)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.3)
  * enju_nii (0.2.0)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)

**Comment by yegusa** [comment]
ごめん、勘違い。インポートのことかと思った。理オープンします。。。

**Comment by nabeta** [comment]
巻・号・通号をエクスポートするようにしました。
http://dev.next-l.jp/manifestations.txt?utf8=✓&query=&commit=検索

以下の書誌が含まれています。
http://dev.next-l.jp/manifestations/24464

**Comment by masao** [comment]
出力されるようになったことを確認しました。クローズします。
