### ISSUE TITLE
Web-API(TSV)における項目数の不足

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1314]
- [x] バグなのでマニュアルの修正必要なし #1279

http://minamisanriku.next-l.jp/manifestations.txt?publisher=&advanced_search=true&isbn=&classification=&creator=&title=&classification_type=2&pub_date_from=&pub_date_until=&query=%E5%8D%97%E4%B8%89%E9%99%B8&page=4

上記サンプルの
manifestation_idが19903において、
manifestation_updated_at以降の項目が表示されていない。
（個別の問題か運用上の問題かは未検証）

**Comment by nabeta** [comment]
遅くなってすみません。
すでに上記のクエリでmanifestation_idが19903のものがヒットしなくなっているので、別のクエリで調べてみたのですが、現象が再現できませんでした。なにか別の本でしょうか？
http://minamisanriku.next-l.jp/manifestations.txt?utf8=✓&query=ヒマラヤの高峰&commit=検索

**Comment by masao** [comment]
手元で再現できないようなので、クローズします。
また再現するようでしたら、お手数ですが、またご連絡いただければ助かります。よろしくお願いします。
