### ISSUE TITLE
Blacklight対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1321]
ディスカバリ機能（ #1316 ）の実現のための一方策として検討する。BlacklightにEnjuデータを取り込ませる、検索可能とする機能を検討する。

cf. https://github.com/projectblacklight/spotlight

#1315 からの派生。2017年11月Enjuワークショップにて議論。

**Comment by nabeta** [comment]
現状でsunspotに強く依存していること、また将来Elasticsearchへの移行を想定していることを考えると、対応は難しいと考えています。クローズしてよいと思います。
