### ISSUE TITLE
bundle update できません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1335]
Gemfileで、enju_biblioだけ、
gem 'enju_biblio', github: "next-l/enju_biblio", branch: "1.2"
にして、bundle update してみたところです

vagrant@vagrant:~/enju$ bundle update
The git source `git://github.com/next-l/enju_biblio.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/next-l/enju_biblio.git
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
The latest bundler is 1.16.0, but you are currently running 1.15.1.
To update, run `gem install bundler`
Bundler could not find compatible versions for gem "globalize":
  In Gemfile:
    globalize (~> 5.0.1)

    enju_biblio was resolved to 0.2.3, which depends on
      enju_library (~> 0.2.3) was resolved to 0.2.3, which depends on
        enju_seed (~> 0.2.2) was resolved to 0.2.2, which depends on
          globalize (~> 5.1.0.beta2)

**Comment by yegusa** [comment]
Gemfile で、 globalize をコメントアウトしたら、bundle update が通ったので、ひとまず、クローズします。

**Comment by masao** [comment]
https://gist.githubusercontent.com/nabeta/8024918f41242a16719796c962ed2af1/raw
インストールスクリプトの設定を直さないとダメではないかと思います。
再オープンしときます。

**Comment by nabeta** [comment]
globalize-5.1.0.beta2を使用するように修正しました。
https://gist.githubusercontent.com/nabeta/8024918f41242a16719796c962ed2af1/raw

**Comment by masao** [comment]
@nabeta この依存関係、enju_seed とアプリケーション側の2箇所で指定しておく必要はありますか？どちらか1箇所にしておかないと、再度同様の問題が起きそうに思うのですが。。。

**Comment by nabeta** [comment]
@masao たしかにないかもしれません。enju_seedでの指定のみにして確認してみます。

**Comment by nabeta** [comment]
インストール用のスクリプトからglobalizeの記述を削除しました。
https://gist.githubusercontent.com/nabeta/8024918f41242a16719796c962ed2af1/raw

enju_seedでの指定のみとしています。
https://github.com/next-l/enju_seed/blob/1.2/enju_seed.gemspec#L37-L38
