### ISSUE TITLE
CiNii BooksのSSL化に伴う改変

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1337]
CiNii BooksのSSL化に伴い、CiNii Books検索からの取り込み機能が動かなくなったようです。
https://support.nii.ac.jp/ja/news/cinii/20171205

たぶん、リダイレクトされることを想定してないのかな。あまり中身は見てませんが、取り急ぎ報告まで。

**Comment by masao** [comment]
![action controller exception caught 2](https://user-images.githubusercontent.com/38825/34034468-06cdbe80-e1c2-11e7-8969-18073909ddcd.png)

**Comment by nabeta** [comment]
少し調べてみたのですが、faraday（enju_niiで使用しているHTTPクライアント）はリダイレクト先を自動的に取得しないため、少し書き方を変える必要がありそうです。
https://qiita.com/ikm/items/93a8044acee0a47194c8

**Comment by nabeta** [comment]
上記コミットで対応させました。

**Comment by masao** [comment]
うまく動いていることを確認しました。クローズします。
