### ISSUE TITLE
フッターのMarkdownが解釈されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1338]
1.2ブランチの最新版の新規インストールで、添付の画像のように、フッターのMarkdownが解釈されないまま表示される。

<img width="700" alt="2017-12-30 21 29 19" src="https://user-images.githubusercontent.com/11428/34454157-87ddf1d8-eda8-11e7-8454-8ee483c0c371.png">

**Comment by nabeta** [comment]
デフォルトのフッターの文字列から <div> を削除したところ、正常に動作するようになりました。

**Comment by masao** [comment]
新規インストールでうまく表示できることを確認しました。クローズします。
![next l enju leaf 1](https://user-images.githubusercontent.com/38825/34648017-08b45252-f3d5-11e7-89e9-3bfe12891e53.png)
