### ISSUE TITLE
所蔵の「注記」の表示方法

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1342]
- [x] markdownのマニュアル修正必要なし #1348 （当該スクリーンショットがないため）

#1341 で気づきました

「所蔵情報の表示」画面では、改行がスペースになっています。

表示（改行がスペースになっている）：
![next l enju leaf 1](https://user-images.githubusercontent.com/1328499/34646036-0fb67a82-f3a1-11e7-82bf-1933704112c0.png)

編集（改行が入っている）
![next l enju leaf](https://user-images.githubusercontent.com/1328499/34646040-153c41b2-f3a1-11e7-89d0-8629e54a5575.png)

**Comment by nabeta** [comment]
simple_formatヘルパーを使って、入力された改行を表示に反映するようにしました。

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。

![next l enju leaf 2](https://user-images.githubusercontent.com/1328499/48307199-3bb91400-e58b-11e8-97da-b33915d6b21c.png)

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0
