### ISSUE TITLE
デモサーバーのヘッダーにEnjuくんロゴをいれる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1345]
https://enju.next-l.jp/

**Comment by nabeta** [comment]
先ほど追加しました。
https://enju.next-l.jp

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://user-images.githubusercontent.com/1328499/34661424-f5b23c4c-f48c-11e7-87fc-9e5770653d2c.png)
