### ISSUE TITLE
資料の形態の表示のファイル登録したのに編集画面では登録していませんとなる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1349]
#1244 のマニュアルを書いていて気づいたのですが、
ファイルを登録しているのにも関わらず、
編集の画面で、ファイルを選択していませんとなります。

ファイルは登録済み：
![next l enju leaf 5](https://user-images.githubusercontent.com/1328499/34679995-1003d77e-f4db-11e7-9187-cb2b918f3674.png)

ファイルは登録されていませんとなる：
![next l enju leaf 6](https://user-images.githubusercontent.com/1328499/34680000-12b34b62-f4db-11e7-89e4-00013a139180.png)

**Comment by nabeta** [comment]
「選択されていません」と表示されるのはブラウザのフォームの仕様だと思いますが、ここも #869 と同様、登録されている画像のサムネイルか、せめてファイル名を表示したほうがよいかもしれません。

**Comment by yegusa** [comment]
> 登録されている画像のサムネイルか、せめてファイル名を表示

そうですね。せめてそれくらいは欲しいところです。

もう少し，スマートなUIにしたいところですが。

**Comment by nabeta** [comment]
上記のコミットは別のissueを指しており、現時点では未着手。

**Comment by nabeta** [comment]
#1246 と重複しているため、こちらはクローズします。
