### ISSUE TITLE
call_numberをログイン前かログイン直後の画面に表示したい

### ISSUE THREAD

**Issue by yut148** [next-l/enju_leaf#1353]
call_numberの最高値を表示したいのですが、インスタンス変数にどの様なselect結果を入れればよろしいでしょうか。
目的としては、書籍の受け入れ前に、実際に書籍に貼る請求番号を容易に知る事が出来ます。
実際に機能追加のお願いではなく、自分でコントローラーに記入して使います。

**Comment by masao** [comment]
請求記号を連番で付けている場合でしょうか？通常の図書館的な運用ですと「分類記号＋著者記号＋シリーズ番号」のような付け方をしますが、小さめの規模のところだと、単純に受け入れ順で請求記号を作るところもありますので、そういうケースですね。

単に以下を書くだけでいけそうです：

```ruby
Item.maximum(:call_number)
```

請求記号ではなく、所蔵番号という場合でもほぼ同様に、 call_number のところを item_identifier でいけるかと。

**Comment by yut148** [comment]
回答ありがとうございます。
Item.maximum(:call_number)で求められる事をrails consoleから確認しました。
意図した値です。
これを画面に表示したいので、試しに
app/controllers/application_controller.rb 
の先頭行に@call
class ApplicationController < ActionController::Base
  @call = Item.maximum(:call_number)
として
app/views/page/_search_form.html.erb 
に<%= @call %>
を追加しました。
これでは動作しない様です。
正しい方法があれば御教示いただけますと幸いです。

**Comment by yut148** [comment]
本件、自己解決しました。
app/views/page/_search_form.html.erb
に
<%= Item.maximum(:call_number) %>
と記載しても、意図した動作となる事を確認しました。
お時間いただきありがとうございました。

本件closeしていただいて問題ありません。

( foremanで起動していたので、viewがすぐに反映されない為、誤認識しており確認が遅れました。）

**Comment by masao** [comment]
ご連絡ありがとうございます。了解しました。こちらはひとまずクローズします。
また何かありましたらご連絡くださいませ。
