### ISSUE TITLE
タイトル表示部分のスペースを広げる

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1355]
Enjuくんのロゴがデフォルトで追加されたため、タイトル表示部分が狭くなり、タイトルが1行に収まりきらないことがある。以下の部分を削ってタイトル表示部分を捻出する。
https://github.com/next-l/enju_leaf/blob/1.2/app/views/page/_header.html.erb#L9

**Comment by nabeta** [comment]
以下も検討すること。

- タイトル部分を折り返して表示
- タイトル部分にロゴのみを表示できるようにする（現在は図書館名が必須）

**Comment by nabeta** [comment]
ひとまずタイトルの幅を640pxまで広げました。

**Comment by masao** [comment]
ひとまず手元の環境で、全角19文字までおさまることは確認しました。20文字目は次の行と重なりますが。。。
![image](https://user-images.githubusercontent.com/38825/39670747-72121a62-5146-11e8-8644-8a410f6c4770.png)

ひとまずクローズします。
