### ISSUE TITLE
ウェブサイトに新ロゴを置く

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1364]
http://next-l.jp/?page=Logo

**Comment by yegusa** [comment]
やりました。

（ライセンス表示は、著者に確認してから書きます。）

**Comment by nabeta** [comment]
@yegusa これは結局ライセンスはなんでしたっけ。

**Comment by yegusa** [comment]
なんでしたっけねえ。確認しておきます。

**Comment by nabeta** [comment]
CC BY-NDということでよいんでしょうか。CCだとBY（表示）は必ず含まれるはず。

**Comment by masao** [comment]
それでよいと思います。プロジェクトとしてグッズ等を作成する際には表示は不要との了解をもらっています、との意です。

**Comment by nabeta** [comment]
@masao ありがとうございます。Webサイトにも"CC BY-ND 3.0"と追記しました。
https://next-l.jp/?page=Logo
