### ISSUE TITLE
エクスポートの項目に「利用制限」(use_restriction)を追加(Librarian,Administratorのみ)

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1366]
- [x] マニュアル 修正 #1348 ver 1.3.0 にて修正  利用制限が表示されることについて追加
- [ ] マニュアル 修正 #1348 ver 1.3.1 にて修正　Librarian,Administratorのみで出力されるようになったように修正

エクスポートの項目に「利用制限」(use_restriction)を追加する

（南三陸町図書館より要望あり、カスタマイズなくすためにも本家にもいれること）

**Comment by nabeta** [comment]
enju_circulationに追加しておきます。

**Comment by nabeta** [comment]
追加しました。
http://dev.next-l.jp/resource_export_files/83

**Comment by masao** [comment]
use_restrictionフィールドが追加されていることを確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/39670723-b4da11a2-5145-11e8-8c08-306038b28354.png)

**Comment by yegusa** [comment]
#### 具体例を修正：
Web API 1-1-2 書誌と所蔵のTSVの例
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_example
```
manifestation_id	original_title	title_transcription	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	description	note	extent	dimensions	carrier_type	edition	edition_string	volume_number	volume_number_string	issue_number	issue_number_string	serial_number	jpno	isbn	iss_itemno	issn	lccn	doi	issn_l	loc_identifier	subject:ndlsh	subject:lcsh	subject:unknown	subject:admin	classification:unknown	classification:ndc9	classification:nlm	classification:ddc	classification:ndlc	classification:ndc8	classification:clno	classification:janl1	classification:ndc10	item_id	item_identifier	call_number	item_note	item_price	acquired_at	accepted_at	bookstore	budget_type	total_checkouts	circulation_status	use_restriction	shelf	library	item_created_at	item_updated_at
12643	Ruby on Rails携帯サイト開発技法	""							2018-11-12 13:15:50 +0900	2018-11-17 20:32:09 +0900							volume								""	9784908829086//9784797358780	""	""	""	""	""	""														7324	002111		""						0	In Process	Not For Loan	second_floor	tachibana	2018-11-17 20:32:09 +0900	2018-11-17 20:32:09 +0900
12642	Ruby on Rails 3アプリケーションプログラミング	Ruby on Rails 3 アプリケーション プログラミング	山田, 祥寛		技術評論社	2011-06	山田祥寛 著	3500	2018-11-11 22:18:44 +0900	2018-11-13 18:57:01 +0900	http://iss.ndl.go.jp/books/R100000002-I000011183573-00				469p	23cm	volume								21925726	9784774146638	R100000002-I000011183573-00	""	""	""	""	""	ウェブアプリケーション	""	""	""	""	547.483	""	""	""	""	""	""	""	7323	A660001		""						0	Available On Shelf	Limited Circulation, Normal Loan Period	first_shelf	tachibana	2018-11-12 16:03:27 +0900	2018-11-13 18:57:01 +0900
12641	1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで!	1リ デ ツクル Ruby on Rails 3 アプリケーション : Web アプリケーション ノ カイハツ カラ コウカイ マデ	堀, 正義, 1982-		工学社	2011-12	堀正義 著	1900	2018-11-11 22:18:37 +0900	2018-11-11 22:18:44 +0900	http://iss.ndl.go.jp/books/R100000002-I023214634-00				207p	21cm	volume								22029180	9784777516513	R100000002-I023214634-00	""	""	""	""	""					""	547.483	""	""	""	""	""	""	""
```

#### 項目説明を追加：
Web API 1-1-3 書誌と所蔵のTSVの項目
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export

利用制限: use_restriction（shelfの前に追加）

#### 見方（初期設定マニュアル 5-4 利用制限を編集する）：https://next-l.github.io/manual/1.3/enju_setup_5.html#section5-4

**Comment by yegusa** [comment]
ログインなしでも、use_restriction が表示さているようですので、リオープンします。
デモサーバーで現象を確認しました。

https://enju.next-l.jp/manifestations.txt?query=ruby

manifestation_id | original_title | title_transcription | creator | contributor | publisher | pub_date | statement_of_responsibility | manifestation_price | manifestation_created_at | manifestation_updated_at | manifestation_identifier | access_address | description | note | extent | dimensions | carrier_type | edition | edition_string | volume_number | volume_number_string | issue_number | issue_number_string | serial_number | jpno | isbn | iss_itemno | issn | lccn | doi | issn_l | loc_identifier | subject:ndlsh | subject:lcsh | subject:unknown | subject:admin | classification:unknown | classification:ndc9 | classification:nlm | classification:ddc | classification:ndlc | classification:ndc8 | classification:clno | classification:janl1 | classification:ndc10 | item_id | item_identifier | call_number | item_note | acquired_at | accepted_at | circulation_status | use_restriction | shelf | library | item_created_at | item_updated_at
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
12643 | Ruby on Rails携帯サイト開発技法 |   |   |   |   |   |   |   | 2018-11-12 13:15:50 +0900 | 2018-11-17 20:32:09 +0900 |   |   |   |   |   |   | volume |   |   |   |   |   |   |   |   | 9784908829086//9784797358780 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 7324 | 002111 |   |   |   |   | In Process | Not For Loan | second_floor | tachibana | 2018-11-17 20:32:09 +0900 | 2018-11-17 20:32:09 +0900
12642 | Ruby on Rails 3アプリケーションプログラミング | Ruby on Rails 3 アプリケーション プログラミング | 山田, 祥寛 |   | 技術評論社 | 2011-06 | 山田祥寛 著 | 3500 | 2018-11-11 22:18:44 +0900 | 2018-11-13 18:57:01 +0900 | http://iss.ndl.go.jp/books/R100000002-I000011183573-00 |   |   |   | 469p | 23cm | volume |   |   |   |   |   |   |   | 21925726 | 9784774146638 | R100000002-I000011183573-00 |   |   |   |   |   | ウェブアプリケーション |   |   |   |   | 547.483 |   |   |   |   |   |   |   | 7323 | A660001 |   |   |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | first_shelf | tachibana | 2018-11-12 16:03:27 +0900 | 2018-11-13 18:57:01 +0900
12641 | 1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで! | 1リ デ ツクル Ruby on Rails 3 アプリケーション : Web アプリケーション ノ カイハツ カラ   コウカイ マデ | 堀, 正義, 1982- |   | 工学社 | 2011-12 | 堀正義 著 | 1900 | 2018-11-11 22:18:37 +0900 | 2018-11-11 22:18:44 +0900 | http://iss.ndl.go.jp/books/R100000002-I023214634-00 |   |   |   | 207p | 21cm | volume |   |   |   |   |   |   |   | 22029180 | 9784777516513 | R100000002-I023214634-00 |   |   |   |   |   |   |   |   |   |   | 547.483 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  
12571 | Ruby on Rails 5.0初級 | Ruby on Rails 5.0 ショキュウ | 黒田, 努 |   | オイアクス | 2016-08 | 黒田努 著 | 900 | 2018-03-13 00:50:25 +0900 | 2018-08-17 20:35:26 +0900 | http://iss.ndl.go.jp/books/R100000002-I027755088-00 |   |   |   | 12, 134p | 24cm | volume |   |   | 1 | 1 |   |   |   | 22826047 | 9784908829062 | R100000002-I027755088-00 |   |   |   |   |   |   |   |   |   |   | 547.483 |   |   |   |   |   |   |   | 7305 | 0987654321 |   |   |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | second_floor | tachibana | 2018-03-13 00:51:44 +0900 | 2018-05-06 01:01:42 +0900
12413 | Ruby on Rails 5.0インストール手順書 | Ruby on Rails 5.0 インストール テジュンショ | 黒田, 努 |   | オイアクス | 2016-08 | 黒田努 著 | 800 | 2017-09-18 18:35:54 +0900 | 2018-03-13 00:50:46 +0900 | http://iss.ndl.go.jp/books/R100000002-I027755114-00 | http://www.sample.com/ | 1行目：書誌にも改行入りの説明をいれてみる\n2行目：書誌の説明の2行目こんなかんじ | 1行目：書誌にも改行入りの注をいれてみる\n2行目：書誌の注記の2行目、こんなかんじ | 8, 106p | 24cm | volume |   |   |   |   |   |   |   | 22826046 | 9784908829024 | R100000002-I027755114-00 |   |   |   |   |   |   |   |   |   |   | 547.483 |   |   |   |   |   |   |   | 7268 | 876123 | 547\|ク | 1行目：改行の注（所蔵のほう）\n2行目：所蔵の注記の2行目 |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | second_floor | tachibana | 2017-09-18 18:38:00 +0900 | 2017-09-18 18:39:52 +0900
12024 | ルビィのぼうけん : こんにちは!プログラミング | ルビィ ノ ボウケン : コンニチハ プログラミング | Liukas, Linda//鳥井, 雪 |   | 翔泳社 | 2016-05 | リンダ・リウカス 作; 鳥井雪 訳 | 1800 | 2016-06-30 16:29:54 +0900 | 2016-06-30 16:29:58 +0900 | http://iss.ndl.go.jp/books/R100000002-I027282794-00 |   |   |   |   |   | volume |   |   |   |   |   |   |   | 22730713 | 9784798143491 | R100000002-I027282794-00 |   |   |   |   |   | プログラミング(コンピュータ) |   |   |   |   | 007.64 |   |   |   |   |   |   |   | 7199 | 3101 |   |   |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | shelfa | praclib | 2016-06-30 16:29:57 +0900 | 2016-06-30 16:29:58 +0900
11989 | 入門Redmine : Linux/Windows対応 : issue tracking system on   "Ruby on Rails" | ニュウモン Redmine : Linux Windows タイオウ | 前田, 剛 |   | 秀和システム | 2008-12 | 前田剛 著 | 2000 | 2015-12-17 14:08:51 +0900 | 2016-03-16 12:42:02 +0900 | http://iss.ndl.go.jp/books/R100000002-I000009981560-00 |   |   |   |   |   | volume |   |   |   |   |   |   |   | 21525630 | 9784798021379 | R100000002-I000009981560-00 |   |   |   |   |   | プロジェクト管理--データ処理 |   |   |   |   | 007.61 |   |   |   |   | コンピュータ |   |   |   |   |   |   |   |   |   |   |   |   |   |  
6166 | 基礎Ruby on Rails : 入門からゆっくりとステップアップ | キソ ルビー オン レイルズ : ニュウモン カラ ユックリ ト ステップ アップ | 黒田, 努//佐藤, 和人, 1967-//オイアクス |   | インプレス | 2015-05 | 黒田努, 佐藤和人 共著; オイアクス 監修 | 3400 | 2015-12-06 15:56:30 +0900 | 2017-01-20 11:53:57 +0900 | http://iss.ndl.go.jp/books/R100000002-I026372940-00 |   |   |   |   |   | volume |   |   |   |   |   |   |   | 22592282 | 9784844338154 | R100000002-I026372940-00 |   |   |   |   |   |   |   |   |   |   | 547.483 |   |   |   |   |   |   |   | 1385 | 909091 |   |   |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | second_floor | tachibana | 2015-12-06 15:56:52 +0900 | 2017-01-20 11:53:57 +0900
6165 | 入門Redmine : Issue Tracking System on"Ruby on Rails" | ニュウモン レッドマイン : イシュー トラッキング システム オン ルビー オン レイルズ |   |   | 秀和システム | 2012-08 | 前田剛 著 | 2200 | 2015-12-06 15:52:11 +0900 | 2016-03-04 10:37:01 +0900 | http://iss.ndl.go.jp/books/R100000002-I023825749-00 |   |   |   |   |   | volume |   |   |   |   |   |   |   | 22108568 | 9784798034409 | R100000002-I023825749-00 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   | 1384 | 909090 |   |   |   |   | Available On Shelf | Limited Circulation, Normal Loan Period | first_shelf | tachibana | 2015-12-06 15:52:40 +0900 | 2015-12-06 15:53:48 +0900
4849 | 10日でおぼえるRuby on Rails入門教室 | 10ニチ デ オボエル Ruby on Rails ニュウモン キョウシツ | arton |   | 翔泳社 | 2008-04 | arton 著 | 2800 | 2014-10-26 00:26:24 +0900 | 2015-05-11 13:07:48 +0900 | http://iss.ndl.go.jp/books/R100000002-I000009329100-00 |   |   |   |   |   | volume |   |   |   |   |   |   |   | 21417797 | 9784798114729 | R100000002-I000009329100-00 |   |   |   |   |   |   |   |   |   |   | 547.483 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  



Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Environment: production
Gems:
actioncable: 5.1.6
actionmailer: 5.1.6
actionpack: 5.1.6
actionview: 5.1.6
activejob: 5.1.6
activemodel: 5.1.6
activerecord: 5.1.6
activesupport: 5.1.6
acts_as_list: 0.9.17
addressable: 2.5.2
arel: 8.0.0
awesome_nested_set: 3.1.4
bcrypt: 3.1.12
bindex: 0.5.0
browser: 2.5.3
builder: 3.2.3
bundler: 1.17.0
byebug: 10.0.2
capybara: 2.18.0
charlock_holmes: 0.7.6
childprocess: 0.9.0
climate_control: 0.2.0
cocoon: 1.2.12
coffee-rails: 4.2.2
coffee-script: 2.4.1
coffee-script-source: 1.12.2
concurrent-ruby: 1.1.3
crass: 1.0.4
devise: 4.5.0
dotenv: 2.5.0
dotenv-rails: 2.5.0
dynamic_form: 1.1.4
enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0
erubi: 1.7.1
erubis: 2.7.0
exception_notification: 4.2.2
execjs: 2.7.0
faraday: 0.15.3
ffi: 1.9.25
fix_microsoft_links: 0.1.6
friendly_id: 5.2.4
geocoder: 1.5.0
globalid: 0.4.1
globalize: 5.1.0
globalize-accessors: 0.2.1
highline: 2.0.0
i18n: 1.1.1
jbuilder: 2.8.0
jquery-rails: 4.3.3
jquery-ui-rails: 4.2.1
kaminari: 1.1.1
kaminari-actionview: 1.1.1
kaminari-activerecord: 1.1.1
kaminari-core: 1.1.1
kramdown: 1.17.0
library_stdnums: 1.6.0
lisbn: 0.2.4
listen: 3.1.5
loofah: 2.2.3
mail: 2.7.1
marc: 1.0.2
method_source: 0.9.2
mime-types: 3.2.2
mime-types-data: 3.2018.0812
mimemagic: 0.3.2
mini_mime: 1.0.1
mini_portile2: 2.3.0
minitest: 5.11.3
mono_logger: 1.1.0
multi_json: 1.13.1
multipart-post: 2.0.0
mustermann: 1.0.3
nio4r: 2.3.1
nokogiri: 1.8.5
non-stupid-digest-assets: 1.0.9
nori: 2.6.0
options: 2.3.2
orm_adapter: 0.5.0
paper_trail: 10.0.1
paperclip: 5.3.0
paperclip-meta: 3.1.0
pg: 1.1.3
pr_geohash: 1.0.0
progress_bar: 1.3.0
public_suffix: 3.0.3
puma: 3.12.0
pundit: 2.0.0
rack: 2.0.6
rack-protection: 2.0.4
rack-test: 1.1.0
rails: 5.1.6
rails-dom-testing: 2.0.3
rails-html-sanitizer: 1.0.4
rails_autolink: 1.1.6
railties: 5.1.6
rake: 12.3.1
rb-fsevent: 0.10.3
rb-inotify: 0.9.10
redis: 4.0.3
redis-actionpack: 5.0.2
redis-activesupport: 5.0.7
redis-namespace: 1.6.0
redis-rack: 2.0.5
redis-rails: 5.0.2
redis-store: 1.6.0
request_store: 1.4.1
responders: 2.4.0
resque: 2.0.0
ri_cal: 0.8.8
rsolr: 2.2.1
ruby_dep: 1.5.0
rubyzip: 1.2.2
sass: 3.7.2
sass-listen: 4.0.0
sass-rails: 5.0.7
scrub_rb: 1.0.1
selenium-webdriver: 3.141.0
simple_form: 4.0.1
sinatra: 2.0.4
sitemap_generator: 6.0.1
spring: 2.0.2
spring-watcher-listen: 2.0.1
sprockets: 3.7.2
sprockets-rails: 3.2.1
statesman: 3.5.0
strip_attributes: 1.8.0
sunspot: 2.3.0
sunspot_rails: 2.3.0
sunspot_solr: 2.3.0
terrapin: 0.6.0
thor: 0.20.3
thread_safe: 0.3.6
tilt: 2.0.8
timeliness: 0.3.8
tzinfo: 1.2.5
uglifier: 4.1.19
unf: 0.1.4
unf_ext: 0.0.7.5
validates_timeliness: 4.0.2
vegas: 0.1.11
warden: 1.2.7
web-console: 3.7.0
websocket-driver: 0.6.5
websocket-extensions: 0.1.3
xpath: 3.2.0
Languages:
en: English
ja: 日本語 (既定の言語)

**Comment by yegusa** [comment]
マニュアルで、guestでも表示されてしまうこと込みで、修正しておきました。

https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export

- use_restriction: 利用制限（Administrator権限、Librarian権限のときのみ出力 注：1.3.0現在guestアカウントでも出力されます）（参照： issue #1366）

と記録しておくので、Administrator権限、Librarian権限のときのみ出力されるようになったら

- use_restriction: 利用制限（Administrator権限、Librarian権限のときのみ出力）

に直しておくこと。

**Comment by masao** [comment]
ユーザ権限を確認して、管理者または図書館員権限のときだけ出力するようにしました。

**Comment by yegusa** [comment]
- [x] ユーザ権限では列ごと表示されない
- [x] librarian権限では表示される
- [x] administer権限では表示される

Enju の仮想マシン
https://www.next-l.jp/download/vm/enju_leaf_1.3.1.virtualbox_64bit.zip
ファイル名：enju_leaf_vm_default_1542922236264_27605.vbox

で動作を確認しましたのクローズします。 

enju_biblio: 0.3.1
enju_circulation: 0.3.1
enju_event: 0.3.1
enju_leaf: 1.3.1
enju_library: 0.3.1
enju_manifestation_viewer: 0.3.1
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

**Comment by yegusa** [comment]
* use_restriction: 利用制限（Administrator権限、Librarian権限のときのみ出力 注：バージョン 1.3.0以前ではguestアカウントでも出力されます。バージョン 1.3.1からは修正されています。）（参照： [issue #1366](https://github.com/next-l/enju_leaf/issues/1366)）

https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export
というようにマニュアルに追加。
