### ISSUE TITLE
現在の貸出データ（今までの累計ではなく、今現在の貸し出し状況）を抽出したい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1367]
コンソールコマンド（？）でよいので、やり方を知りたいです。

教えてください。

（注：南三陸町図書館で実際に要望があったため、ここでも共有）

**Comment by nabeta** [comment]
南三陸町向けに以下のようなrake taskを作ったので、これを本家に取り込むことになります。

```sh
$ heroku run rake minamisanriku:export:checkout -a minamisanriku > checkout_20180326.txt
```

**Comment by nabeta** [comment]
rake taskを追加しました。以下のコマンドで現時点の貸出TSVを出力します。

```
$ rake enju_circulation:export:checkout
```

**Comment by yegusa** [comment]
$ rake enju_circulation:export:checkout RAILS_ENV=production > output.txt

というように、**RAILS_ENV=production** をつける必要がありました。
また、私の環境（enju_leaf_vm_default_1515391250583_71336.vboxにenju_circulation, enju_bibloを開発バージョンにしたもの）では、以下のようにエラーが出ました。


```
$ rake enju_circulation:export:checkout RAILS_ENV=production
checked_out_at	checked_in_at	item_identifier	call_number	shelf	carrier_type	title	username	full_name
The PGconn, PGresult, and PGError constants are deprecated, and will be
removed as of version 1.0.

You should use PG::Connection, PG::Result, and PG::Error instead, respectively.

Called from /home/vagrant/enju/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
2018-06-10 16:23:13 +0900		001002	007|ま	first_shelf	volume	入門Redmine : Linux/Windows対応 : issue tracking system on "Ruby on Rails"	002
```

- username（ログインID）だけでなく、利用者番号も出力したほうがいい
- checked_in_atは必ず空になるので出力しなくてもいいかも？

とは思いますが、とりあえずできることは確かめました。

以下、確認例。
1件だけ貸し出しがある例：
$ rake enju_circulation:export:checkout RAILS_ENV=production > output.txt


checked_out_at | checked_in_at | item_identifier | call_number | shelf | carrier_type | title | username | full_name
-- | -- | -- | -- | -- | -- | -- | -- | --
2018-06-10   16:23:13 +0900 |   | 001002 | 007\|ま | first_shelf | volume | 入門Redmine :   Linux/Windows対応 : issue tracking system on "Ruby on Rails" | 002 |

**Comment by yegusa** [comment]
「返却期限」の方があったほうがいいかも。

**Comment by yegusa** [comment]
- username（ログインID）だけでなく、利用者番号を出力してほしい
- 「返却期限」を出力してほしい
- ( checked_in_atは必ず空になるので出力しなくてもいいかも？）

**Comment by yegusa** [comment]
ま、いいや、別issueにして、一旦、こちらのissueはクローズにします。

**Comment by yegusa** [comment]
マニュアル案：

6-1-3 貸出履歴を表示する　の後ろに挿入する
https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-1-3

【Column】現在の貸出データを抽出する

現在の貸出データ（今までの累計ではなく、今現在の貸し出し状況）を抽出する方法です。
現在、Webブラウザから操作して現在の貸出データをまとめて出力する機能がないため、代替機能として、コンソールにログインしてコマンドで出力する方法を紹介しておきます。

 $ rake enju_circulation:export:checkout RAILS_ENV=production > output.txt

とすると、output.txt ファイルに出力されます。
（RAILS_ENV=production は、RAILS_ENV=development など必要に応じて修正してください）

以下の項目が出力されます。

- checked_out_at
- checked_in_at
- item_identifier
- call_number
- shelf
- carrier_type
- title
- username
- full_name

**Comment by yegusa** [comment]
マニュアル追加しました。
https://next-l.github.io/manual/1.3/enju_operation_6.html#column
