### ISSUE TITLE
インストール手順で postgresql-setup でコマンド無しとなる

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#1370]
CentOS 6.9 にて[インストール手順](https://github.com/next-l/enju_leaf/wiki/Install
)通り進めたところ、コマンドなしのエラーとなる。
```
# postgresql-setup initdb
-bash: postgresql-setup: コマンドが見つかりません
```
CentOS 7.2であればエラーとならない。
CentOS 6.9 が PostgreSQL 8.4系、CentOS 7.2 が PostgreSQL 9.2系が対象のためと思われる。

**Comment by nabeta** [comment]
CentOS6のSCLリポジトリを使用する場合は以下のコマンドでいけるようです。

```
#  yum install centos-release-scl
# service postgresql92-postgresql initdb
```

**Comment by nakamura-akifumi** [comment]
#1371  にも記載しましたが、リポジトリの有効化後に以下のコマンドで出来ました。
```
# yum update
# yum install postgresql92
# service postgresql92-postgresql initdb
```
