### ISSUE TITLE
「貸出の一覧」のTSV出力に「返却済み」かわかる列を入れて欲しい（画面では表示されている）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1377]
- [ ] マニュアル #1348

#1367 からの派生。　#1367 をこれで実現することができる（ただし、500件分のみ）

今は、返却済みかどうかは、TSVではわからない。

「返却済み」かどうかわかるフラグをつける
もしくは、check_in_date を入れるのでもいいかも。

貸出の一覧
http://localhost:8080/checkouts

![next l enju leaf 3](https://user-images.githubusercontent.com/1328499/41199762-923a6b30-6cd2-11e8-84f7-591c66263568.png)

以下は、TSV

username | item_identifier | title | checked_out_at | due_date | Checkout items (created_at:   2018-06-10 08:21:16 +0000)
-- | -- | -- | -- | -- | --
user01 | 001003 | 情報検索演習 | 2018-06-10 16:49:44 +0900 | 2018-06-24 23:59:59 +0900 |  
002 | 001002 | 入門Redmine : Linux/Windows対応 : issue tracking system on   &quot;Ruby on Rails&quot; | 2018-06-10 16:23:13 +0900 | 2018-06-24 23:59:59 +0900 |  
  | 001001 | はじめようRuby on Rails | 2018-06-10 16:22:56 +0900 | 2018-06-24 23:59:59 +0900 |

**Comment by nabeta** [comment]
checked_in_at 列を追加しました。
http://dev.next-l.jp/checkouts.txt?locale=ja

**Comment by yegusa** [comment]
開発サーバーで cheack_in_at 列が追加されて、
返却済みとわかるようになっていることを確認しました。

![2018-08-19 16 42 26](https://user-images.githubusercontent.com/1328499/44306683-e7105d80-a3ce-11e8-97da-720c4c46e8ea.png)

**Comment by yegusa** [comment]
すっぴんのVM  (enju_leaf_vm_default_1540858394676_97776.vbox) で確かめました。
unsername が表示されません。

1件は借りている、1件は返却ずみ

username | item_identifier | title | checked_out_at | due_date | checked_in_at | (created_at: 2018-11-12 13:37:24   +0900)
-- | -- | -- | -- | -- | -- | --
  | 001002 | 1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで! | 2018-11-12 13:36:41 +0900 | 2018-11-26 23:59:59 +0900 | 2018-11-12 13:36:54 +0900 |  
  | 001001 | 10日でおぼえるRuby on Rails入門教室 | 2018-11-12 13:35:54 +0900 | 2018-11-26 23:59:59 +0900 |   |

**Comment by yegusa** [comment]
check_in_at（返却日）が表示されることを
公式1.3.0VM（enju_leaf_vm_default_1540858394676_97776.vbox）で確認したので、
usernameが表示されない件は、別issue にして、ひとまず、こちらはクローズします。

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

**Comment by yegusa** [comment]
マニュアル案：

https://next-l.github.io/manual/1.3/enju_operation_6.html#columntsv
の例を差し替え、注を追加。

<pre>
username	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2018-11-17 22:04:05 +0900)
"user01"	"001002"	"パーフェクトRuby on Rails"	"2017-06-07 22:05:55 +0900"	"2017-06-21 23:59:59 +0900"
"user01"	"001001"	"Ruby on Rails入門 : 優しいRailsの育て方"	"2017-06-07 21:51:22 +0900"	"2017-06-21 23:59:59 +0900"	"2017-06-10 22:25:22 +0900"
</pre>

注） バージョン 1.3.0 より、checked_in_at（返却日）が追加されました
