### ISSUE TITLE
Librarian権限のユーザでも書籍を貸出できますでしょうか？

### ISSUE THREAD

**Issue by yut148** [next-l/enju_leaf#1378]
Librarian権限のユーザでも書籍を貸出できますでしょうか？
現行仕様としては技術的に困難が伴うものでしょうか？
率直にUser権限で他に1名作成した方が望ましいでしょうか。

Next-L Enju Leaf 1.2.1を利用しています。

ちなみに過去のissuesでもあったようですが。
https://github.com/next-l/enju_leaf/issues/672

**Comment by yegusa** [comment]
Librarian権限のユーザーでも、貸し出しはできますよ。

もし、できなかったらご連絡ください。

**Comment by yut148** [comment]
回答ありがとうございます。
貸出資料の新規作成画面
/checked_items/new?basket_id=16
にて
所蔵情報ID:
右のテキストボックス内に所蔵IDを入力し
さらに右の
読み込み
ボタンをクリックすると。

貸出資料にエラーが発生しました。
次の項目を確認してください。
この利用者種別でのこの資料の貸出はできません。

と表示されてしまいます。

所蔵情報は貸出状態、在架である事を確認しています。

**Comment by masao** [comment]
貸出可能な状態になっていないような気配ですね。

システム設定で特に、利用者グループと貸出区分の関係、資料の形態と貸出区分の関係のそれぞれの関連付けが完了しているか確認してみていただけますか。
初期設定マニュアルの 3-6 / 3-7 及びその前後をご確認いただければ：
http://next-l.github.io/manual/1.2/enju_setup_3.html

そのうえで、該当の貸出対象ユーザの利用者区分と対象資料の資料区分をご確認いただくのがよいかと思います。

**Comment by yut148** [comment]
御指南いただいた、
>初期設定マニュアルの 3-6 / 3-7
http://next-l.github.io/manual/1.2/enju_setup_3.html
にて
Librarian権限のユーザでも書籍を貸出できました。

解決しました。
ありがとうございます。

機能上問題等がありましたら再度issuesの記載をします。
本件closeで差し支えありません。

**Comment by masao** [comment]
確認ありがとうございます。
では、こちらのIssueはクローズしますね。
