### ISSUE TITLE
コンソール上からのTSVファイルを利用したユーザ登録について

### ISSUE THREAD

**Issue by yut148** [next-l/enju_leaf#1380]
TSVファイルからの利用者情報をインポートできますが、こちらはsshコンソール上からは実行できないものでしょうか。
その際、TSVファイルは事前にサーバにアップロード済とします。

rails console上からでもいいので、ワンライナーで実行出来る方法がありますと大変助かります。

**Comment by nabeta** [comment]
コマンドラインでインポートを実行するには、以下の方法があります。

1. TSVファイルをWebブラウザでアップロードする。このとき、アップロードしたファイルについたIDを控えておく。たとえば、次の場合は50 https://enju.next-l.jp/user_import_files/50
2. Railsコンソールを起動する
```sh
$ cd /path/to/enju
$ rails c production
```
3. ファイルの情報を取得し、UserImportFile#import_startメソッドでインポートを実行する
```ruby
> file = UserImportFile.find(50)
> file.import_start
```
4. なんらかの理由でインポートが失敗し、もう一度実行する場合、以下のコマンドでインポートの状態をリセットする
```ruby
> file.user_import_file_transitions.destroy_all
> file.reload
> file.import_start
```

ワンライナーで実行する場合は、以下のようになります。

```sh
$ rails runner -e production 'UserImportFile.find(50).import_start'
```

**Comment by yut148** [comment]
回答ありがとうございます。

TSVファイルをブラウザからアップロードするしかユーザ登録の方法はないのでしょうか。

TSVとは異なりますが、ユーザ登録の際に

newuser = User.new
newuser.id = User.maximum(:id)+1
newuser.email="test@example.com"
newuser.username = "test"
newuser.created_at = Time.now
newuser.updated_at = Time.now
newuser.save!
としてもテーブル上問題ありませんでしょうか。
（ユーザ追加の際に、他のモデルへの入力が必要となりますでしょうか。）

他、フィールド上に必要な値はsave前に入力します。

**Comment by nabeta** [comment]
> TSVファイルをブラウザからアップロードするしかユーザ登録の方法はないのでしょうか。

TSVファイルが /home/example/user.tsv にアップロードしてあり、アップロードを実行するユーザをlibrarian1とした場合の例です。

```ruby
> tsv = File.open('/home/example/user.tsv')
> file = UserImportFile.new
> file.user = User.find_by(username: 'librarian1')
> file.user_import = tsv
> file.save
> file.import_start
> tsv.close
```

**Comment by nabeta** [comment]
> （ユーザ追加の際に、他のモデルへの入力が必要となりますでしょうか。）

UserにはProfile・Roleモデルが関連し、またProfileモデルにLibrary・UserGroupの各モデルが関連するので、これらの入力が必要になります。また、user_number（利用者番号）や初期パスワードの設定も必要です。idやcreated_atはデータベースに保存時に自動的に追加されます。

以下が実行例になります。

```ruby
> profile = Profile.new(user_group_id: 1, library_id: 1, user_number: '112233', locale: 'ja')
> profile.user = User.new(username: 'newuser1', password: 'newpassword')
> profile.user.role = Role.find_by(name: 'User') # Librarian, Admistratorも指定可能
> profile.user.save!
```

**Comment by yut148** [comment]
早急な回答とフォローありがとうございます。
TSVでの登録と実現したい事がかけ離れてきてしまっていますので、お答えいただいた情報を基に試行錯誤してみます。
本件一度クローズで差し支えありません。
ありがとうございました。

**Comment by nabeta** [comment]
不明な点がありましたら、お気軽におたずねください。
