### ISSUE TITLE
deviseによる一時ログインとその後のユーザ自身のアカウント登録

### ISSUE THREAD

**Issue by yut148** [next-l/enju_leaf#1381]
お世話になっております。

enjuではdeviseが使われていますが、devise_ldap_authenticatableに対応させる事は可能でしょうか。

ただ、devise_ldap_authenticatableでログインできてもenju上の各機能は利用できない状態にあると思います。
そこで、任意に新たなページを作りそこで、ログインしたユーザ自身がenju上のユーザ登録を済ませる事を想定しています。

流れとしては
ActiveDirectoryに登録済みのユーザが一時的に特定ページへ新規ログインします。
特定のページへログインしたユーザが自らがenju上のユーザ登録を済ませます。
enju上へ一度ユーザ登録が終われば、ActiveDirectoryのユーザ名と同一のenjuアカウントを用いてログインできます。

ActiveDirectoryのユーザ名は一時的なenjuへのログインの為に用います。
ActiveDirectoryのユーザ名とenju上ユーザ名は同一の物とします。
ユーザの種別はLibrarianで問題ないものとします。
（重複等の対応は別のAdminユーザで管理します。）

実現にあたり、任意のページ作成に難儀しております。
任意のcontroller、viewを持たせる事は難しいでしょうか？

確認したい事としましては2点となります。

１）devise_ldap_authenticatable に対応可能でしょうか。
　ActiveDirectoryのユーザを認証するにあたりユーザ登録ページだけを認証の適応範囲としてもいいです。

２）任意のcontroller、viewを持たせたい。
　（ユーザー登録をしたい。）

**Comment by nabeta** [comment]
devise_ldap_authenticatableでのLDAP認証は動作実績がありますが、利用者が自分でサインアップしようとすると少し工夫がいりそうですね。もともと図書館で利用者登録を作るときに図書館員がユーザ情報を作成する、という想定なので。
ちょっと手元の環境で試してみます。

**Comment by yut148** [comment]
LDAP対応のenjuを手がけていらした事業社さんがいらした様ですが2015年でその事業を止めてしまった様でして。
お手数おかけします。

**Comment by yut148** [comment]
app/views/devise/registrations/edit.html.erb のファイルありがとうございます。
気が付かず、反応が遅れてしまいました。
config/route.rbの記載と理想的な仕様を検討しています。

直接関わり合いが薄く申し訳ないのですが、
>devise_ldap_authenticatableでのLDAP認証は動作実績
というとどのような実績となりますでしょうか。

例えばLDAP上のメールアドレスをEnju側のアカウントに紐づけて使うことは可能ですが、LDAP上でユーザを任意の都合で削除したとします。この時Enju側でもいつかのタイミングでEnju側のアカウントを消す必要があるかと思います。
端的いえば、LDAPとEnjuでアカウントの部分的な2重管理が生じます。
これを以前の実績ではどの様に解決していたのでしょうか？
>devise_ldap_authenticatableでのLDAP認証
では解決できていたのでしょうか？

**Comment by yut148** [comment]
https://github.com/next-l/enju_leaf/commit/40302cbdd14cecc2ed218a501e1e650e0ea5617b
として記載いただいた、new.html.erb をリネームして
app/views/devise/registrations/reg.html.erb
としました。(new.html.erbは./vendor/bundle/ruby/2.3.0/gems/devise-4.4.3/app/controllers/devise/registrations_controller.rbでnewが使われていたためよく使われそうなのでregにしました。)

route.rbは仕様上ふさわしいかわかりませんが、deviseで使いたいのでas:user do直下にregを書き足しました。
  as :user do
    get 'users/reg' => 'devise/registrations#reg'

末尾、<%= render "devise/shared/links" %>は冗長と感じました。(上部にもログイン項目があるため)

御教示いただきたいのですが、記載いただいた、
resource, as: resource_name
url: registration_path(resource_name)
にてformでresourceモデルとurlを送れば動作するものなのでしょうか。

また、上記の私の推測が合っていれば、rake routesで見た時の
user_session POST   /users/sign_in(.:format)  devise/sessions#create
でcreateに対するPOSTでユーザ登録ができるという理解で合っていますでしょうか。

まだ手元の環境ではLDAPと連携できてはいないので最終的な完成には至らないのですが、先行して動作を確認できればと思います。
LDAP連携は先になりそうなので、formで任意の値をユーザ登録でもできればと考えております。

**Comment by nabeta** [comment]
> 直接関わり合いが薄く申し訳ないのですが、
> >devise_ldap_authenticatableでのLDAP認証は動作実績
> というとどのような実績となりますでしょうか。

把握している例として、以下があります。

- LDAPサーバにユーザ情報を登録
- Enju上に日次バッチで職員情報を登録（このとき、UserモデルにLDAPのユーザ名を保存）
- ログイン時にUserモデル上のユーザ名と入力されたパスワードを用いて、LDAPサーバで認証を行う

つまりこの例では、LDAPでの登録とEnjuでの登録には、最大1日の差があります。

> 例えばLDAP上のメールアドレスをEnju側のアカウントに紐づけて使うことは可能ですが、LDAP上でユーザを任意の都合で削除したとします。この時Enju側でもいつかのタイミングでEnju側のアカウントを消す必要があるかと思います。

上述の例では、Enju上のユーザ情報は削除せず、単に無効化する（アカウントの有効期限を設定する）のみとしています。これは、過去の貸出状況を把握したいというニーズによるものです。

**Comment by nabeta** [comment]
ひとまずLDAPではなくローカルでの認証の例ですが、ユーザ自身にEnjuのサインアップを行わせる方法を紹介します。

1. Deviseのコントローラをカスタマイズするため、コントローラのファイルを作成します。app/controllers/users/ 以下にファイルが作成されます。
    ```sh
    $ rails g devise:controllers users
    ```

1. app/controllers/users/registrations_controller.rb の after_sign_up_path_for メソッドのコメントを解除し、以下のように変更します。
    ```ruby
      def after_sign_up_path_for(resource)
        resource.profile = Profile.create!(
        # デフォルトの所属館と所属グループを指定する。適宜変更可
        # 利用者番号(user_number)もここで設定できるが、生成ルールが不明のため、
        # ここではまだ指定していない
          library: Library.first,
          user_group: UserGroup.first,
          # user_number: '112233'
        )
    # デフォルトのユーザ権限。利用者番号を手動で入力するためにLibrarian権限としているが、
    # ユーザ作成時に利用者番号を自動的に設定できればUser権限に変更可能
        resource.role = Role.find_by(name: 'Librarian')
        resource.save!
        edit_my_account_url
      end
    ```

1. config/routes.rb を以下のように変更します。
    ```ruby
    #as :user do
    #  get 'users/edit' => 'devise/registrations#edit', as: 'edit_user_registration'
    #  put 'users' => 'devise/registrations#update', as: 'user_registration'
    #end
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
    ```

1. WebブラウザでEnjuの /users/sign_up を開きます。サインアップ画面が開きますので、ユーザ名とパスワードを入力すると、Enju上にアカウントが作成され、利用者情報の編集画面に遷移します。

あとはサインアップ画面のカスタマイズが必要になると思います。Enju上で app/views/devise/registrations/new.html.erb を作ることになりますが、 @yut148 さんの場合、 app/views/devise/registrations/reg.html.erb を new.html.erb としてコピーすればよいはずです。

ユーザ登録の流れはこれで要望を満たしますでしょうか。

**Comment by nabeta** [comment]
> 出力されたTSVファイルを用いて、Enju上に日次バッチで職員情報を登録（このとき、UserモデルにLDAPのユーザ名を保存）

ちなみに、devise_ldap_authenticatable には、アプリケーション側（Enju）にアカウントがなくても、ログインフォームに入力されたユーザ名とパスワードで認証が成功すれば、自動的にアプリケーション側にアカウントを作成する機能があります。ですので、特に理由がなければ、あらかじめEnju上にアカウントを作っておく必要はないかもしれません。

devise_ldap_authenticatableでのユーザの自動作成は、 app/models/user.rb と config/initializers/devise.rb に設定が必要です。
https://github.com/cschiewek/devise_ldap_authenticatable#querying-ldap

**Comment by yut148** [comment]
いろいろ御指南ありがとうございます。
だいぶ時間があいてしまいましたが御教示いただいた内容で、概ねUserモデルに任意のユーザ名を書き込む事ができました。
結局、app/views/devise/registrations/new.html.erbにしました。
ユーザ名はformでユーザからの入力とはせず
<%= f.hidden_field :username, :value => username %>
として書き込む事にして正常動作しました。
合わせてUserモデルにemailも書き込みたいと考えております。
<%= f.hidden_field :email, :value => email %>
では書き込む事ができませんでした。
emailの項目はnew.html.erbでは書き込めないものでしょうか。

**Comment by yut148** [comment]
だいぶ時間が空いてしまい恐縮です。

紆余屈折あり、googleアカウントでサインインして利用する機能を実装しました。
お知らせ頂いた情報には大変に感謝しております。
ActiveDirectoryでのログインという事では、コードを書いておりません。

まだ細かい箇所を直している状況ですが、このIssueとはかけ離れてしまいましたのでクローズいただければと思います。
よろしくお願い申し上げます。
