### ISSUE TITLE
標準インストール時に言語設定がされない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1384]
- [x] markdownのマニュアル修正必要なし #1348

1.3系にて、標準インストールすると、必ずロケール設定が英語モードで起動する。

原因は config/application.rb に対するパッチ当てが効かなくなったため。
ほか、タイムゾーン設定なども無効になっている。

**Comment by nabeta** [comment]
インストール時のスクリプトを修正しました。

**Comment by masao** [comment]
修正を確認したのでクローズします。
