### ISSUE TITLE
jsonフォーマットでの返却処理の戻り値について

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#1387]
またお願いですが...

画面上で未貸出の所蔵番号を返却処理をすると
「この資料は未貸出の資料です。」と表示されます。

jsonフォーマットの場合には、flash[:message] が戻されないので判定が出来ません。
また、basket の情報も返却されないかと思います。似たようにすると助かります。

https://github.com/next-l/enju_circulation/blob/1.2/app/controllers/checkins_controller.rb#L80

**Comment by nakamura-akifumi** [comment]
私の方で作ってみてPR投げます。

**Comment by nabeta** [comment]
以下のpull requestをマージしました。
https://github.com/next-l/enju_circulation/pull/2

**Comment by masao** [comment]
確認が面倒なので、ひとまずチェックはできていませんが、クローズします。
また何かありましたら再オープンしてくださいませ。
