### ISSUE TITLE
現在の貸出データ（今までの累計ではなく、今現在の貸し出し状況）を抽出したい part 2

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1393]
#1367 の派生。

- [x] markdownのマニュアルを修正する #1348
- <s>username（ログインID）だけでなく、「利用者番号」を出力してほしい</s>
- [x] 「返却期限」を出力してほしい
- <s>checked_in_atは必ず空になるので出力しない</s>

**Comment by masao** [comment]
user_number および due_date 列を追加しました。
checked_in_at は削除しました。

**Comment by yegusa** [comment]
- **NG: user_number（利用者番号） を表示**
- OK: due_date（返却期限） を表示
- OK: checked_in_at（返却日） の削除　改め　cheked_in_at の値を表示　( #1377 による )


1.3.0の公式VM(enju_leaf_vm_default_1540858394676_97776.vbox)で確認しました。

enjuadminでログイン、「貸出・返却・予約」-->貸出履歴--> 「TSV」
http://localhost:8080/checkouts.txt?locale=ja

（username:yegusa user_number:100001 、一つは返却済み、一つは貸出中）
![next l enju leaf 5](https://user-images.githubusercontent.com/1328499/48328810-21fdf680-e689-11e8-82a1-0349b1cb1753.png)

```
username	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2018-11-12 14:43:02 +0900)
	001002	1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで!	2018-11-12 13:36:41 +0900	2018-11-26 23:59:59 +0900	2018-11-12 13:36:54 +0900
	001001	10日でおぼえるRuby on Rails入門教室	2018-11-12 13:35:54 +0900	2018-11-26 23:59:59 +0900	
```

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

参考（縦横逆にして、日本語ラベルをつけたもの）：

列名|日本語ラベル|レコード1|レコード2
-- | -- | -- | --
username | 利用者アカウント |   |  
item_identifier | 所蔵情報ID | 001002 | 001001
title | 原題 | 1人でつくるRuby   on Rails3アプリケーション : Webアプリケーションの開発から公開まで! | 10日でおぼえるRuby   on Rails入門教室
checked_out_at | 貸出日 | 2018-11-12   13:36:41 +0900 | 2018-11-12   13:35:54 +0900
due_date | 返却期限 | 2018-11-26   23:59:59 +0900 | 2018-11-26   23:59:59 +0900
checked_in_at | 返却日 | 2018-11-12   13:36:54 +0900 |  
(created_at: 2018-11-12 13:37:24 +0900) | （貸出の一覧のTSV出力日時） |   |  

参考. 1.2.2ではusernameは表示されていたようです( #1377 より )

**Comment by yegusa** [comment]
すみません、1.3.0はリリースされているので、できてないところ（NG: user_number（利用者番号） を表示）は、1.3.1用のissueとして別に立ち上げておきますね。

ので、こちらは、一旦クローズします。


OK: due_date（返却期限） を表示
OK: checked_in_at（返却日） の削除　改め　cheked_in_at の値を表示　( #1377 による )

1.3.0の公式VM(enju_leaf_vm_default_1540858394676_97776.vbox)で確認しました。

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

**Comment by yegusa** [comment]
マニュアルの修正案：

https://next-l.github.io/manual/1.3/enju_operation_6.html#columntsv

- 現在：注） バージョン 1.3.0 より、checked_in_at（返却日）が追加されました
- 修正：注） バージョン 1.3.0 より、due_date（返却期限）、checked_in_at（返却日）が追加されました

**Comment by yegusa** [comment]
マニュアルに追加しました。

**Comment by yegusa** [comment]
すみません、勘違いです。
コマンドでTSVを出力することについてのissueだったのですね。一から確認し直しますので、一旦理オープンします。

**Comment by yegusa** [comment]
確かめること：
事前準備：　書誌を2件登録する、所蔵を2件登録する、貸出をする　2件、返却をする　1件

$ rake enju_circulation:export:checkout RAILS_ENV=production > output.txt

を実行

- [ ] 1件だけ貸出レコードがある
- [ ] user_number（利用者番号） を表示
- [ ] due_date（返却期限） を表示
- [ ] 空のchecked_in_at（返却日） の削除

**Comment by yegusa** [comment]
できていることを確認したのでクローズします。
VM( enju_leaf_vm_default_1542300056037_65648.vbox )で確認しました。

TSV
<pre>
checked_out_at	due_date	item_identifier	call_number	shelf	carrier_type	title	username	full_name	user_number
2018-11-18 14:36:18 +0900	2018-12-02 23:59:59 +0900	001002	547|ビ	first_shelf	volume	JRuby on Rails実践開発ガイド	yegusa	江草由佳	100001
</pre>

縦・横回転、日本語ラベル付与、表形式にしたもの

日本語ラベル | 項目名 | 値
-- | -- | --
貸出日 | checked_out_at | 2018-11-18 14:36:18 +0900
返却期限 | due_date | 2018-12-02 23:59:59 +0900
所蔵情報ID | item_identifier | 1002
請求記号 | call_number | 547\|ビ
本棚 | shelf | first_shelf
資料の形態 | carrier_type | volume
現題 | title | JRuby on Rails実践開発ガイド
ユーザ名 | username | yegusa
フルネーム | full_name | 江草由佳
利用者番号 | user_number | 100001

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.1
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

**Comment by yegusa** [comment]
マニュアル修正案：

https://next-l.github.io/manual/1.3/enju_operation_6.html#column

で、以下のように修正する

checked_out_at
<s>checked_in_at</s>　：削除する
due_date ：追加する
item_identifier
call_number
shelf
carrier_type
title
username
full_name
user_number：追加する

**Comment by yegusa** [comment]
マニュアル修正しました。
