### ISSUE TITLE
初期設定がおかしい（「図書館」の設定の住所にIbaraki, Tsukubaが入っている）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1400]
- [x] markdownのマニュアル修正必要なし #1348

仮想マシン：
http://www.next-l.jp/download/vm/enju_leaf_1.3.0.virtualbox_64bit.zip

をダウンロードして、起動してみたところ、
「図書館」の設定で、デフォルトの図書館の住所に、
- 都道府県：Ibaraki
- 市町村：Tsukuba

が入っていました。

例： http://localhost:8080/libraries/yours/edit
![next l enju leaf](https://user-images.githubusercontent.com/1328499/48307066-838a6c00-e588-11e8-8e25-92d796550031.png)

ひょっとして、この件以外にも、何かテストの設定ファイルが入れ込んだ状態で、仮想マシンのファイルを作っちゃってるのかもしれませんので、もう一度確認の上、作り直す必要があるかと思います。

**Comment by nabeta** [comment]
これは少なくとも1.2からそうだったはずです。1.3での変更は行っていません。

**Comment by yegusa** [comment]
じゃあ、1.2でもダメだったんでしょう。それとも、初期値に入れておかないとまずいとかあります？

**Comment by nabeta** [comment]
まあ架空の住所というのも難しいですしね。空にしますか。

**Comment by yegusa** [comment]
はい、空にしてください。

**Comment by yegusa** [comment]
これ、1.3.0? 1.3.1?

**Comment by yegusa** [comment]
これって、

- a) 仮想マシンの作り方の話？
- b) インストールした時の初期値の話？

なんとなく、b) な気がするので、 1.3.0 じゃなくて、　1.3.1 になる？

**Comment by yegusa** [comment]
ちなみに enju_leaf_vm_default_1542300056037_65648.vbox でも、まだ、Ibaraki, Tsukuba は残っていました。

**Comment by yegusa** [comment]
というわけで、1.3.1にマイルストーンを変えておきます。

**Comment by masao** [comment]
住所項目が空になっていることを確認しました。
