### ISSUE TITLE
公式サイトからダウンロードした1.3.0 64bit 仮想マシンにsshでログインできない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1401]
- [x] markdownのマニュアル修正必要なし #1348 

#1400 とも関連しているかも。

仮想マシン：
http://www.next-l.jp/download/vm/enju_leaf_1.3.0.virtualbox_64bit.zip

をダウンロードして、sshでログインしようとしてみたところ、

$ ssh vagrant@localhost -p 2222
vagrant@localhost: Permission denied (publickey).

となってしまって、sshでログインできません。

仮想マシンの作り直しが必要かも？

**Comment by nabeta** [comment]
以前あった、Ubuntuの提供するVagrant boxでログインができないという問題が解決していたので、再度UbuntuのVagrant box (ubuntu/xenial64)を使うようにしました。
https://github.com/next-l/enju_leaf/issues/1238#issuecomment-406865179

ただ、これはvagrant sshコマンドでないとログインできないかもしれません。作り直したほうがよさそうです。

**Comment by nabeta** [comment]
仮想マシンを再作成してアップロードしました。
https://www.next-l.jp/?page=VM

**Comment by yegusa** [comment]
以下のような感じでsshログインできることを確認しましたので、クローズします。

ところで、 @nabeta .vobxのファイル名もダウンロードページに書いておいてもらえると助かります（あとで、識別に使えることがあるので）

$ ssh vagrant@localhost -p 2222
The authenticity of host '[localhost]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
vagrant@localhost's password: 
Welcome to Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-116-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

2 packages can be updated.
0 updates are security updates.


Last login: Sat Nov 17 08:36:34 2018
vagrant@vagrant:~$ 


注：一部 xxxx で伏字にしています。
