### ISSUE TITLE
催し物が紐付いているカテゴリーを削除できないようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1402]
- [ ] 催し物が紐付いているカテゴリーは削除できないようにする

**Comment by yegusa** [comment]
#1272 を確かめようとして遭遇。

**Comment by nabeta** [comment]
一部の催し物のカテゴリーが削除されていました。催し物が紐付いているカテゴリーは削除できないようにする必要があります。

**Comment by nabeta** [comment]
催し物が紐付いているカテゴリーを削除できないようにしました。dev.next-l.jpには反映済みです。

**Comment by yegusa** [comment]
デモサーバーでできてるのかと思って試しちゃいました。
dev.next-l.jp の方だったんですね。そして、デモサーバーがまた、we're sorry になるようになっちゃいました。すまん。

https://enju.next-l.jp/events
![next l enju leaf 5](https://user-images.githubusercontent.com/1328499/48746234-fa72e380-ecb1-11e8-8af0-2eda9e3f441d.png)

https://enju.next-l.jp/event_categories
![next l enju leaf 1](https://user-images.githubusercontent.com/1328499/48746243-ff379780-ecb1-11e8-82bd-ad4ccd43750d.png)

**Comment by yegusa** [comment]
２つの異なることが一つのissueにあると辛いので、こちらは、

催し物が紐付いているカテゴリーを削除できないようにする

の方だけのissueにしておきます（ @nabeta がコミットに紐付けちゃったので）

もう一方はあたらにissueを立ち上げました #1420

**Comment by nabeta** [comment]
enju.next-l.jpにも反映させました。

**Comment by masao** [comment]
なお、closed（休館日）とunknown（不明）の標準カテゴリ2つだけは、イベント情報と結びついていなくとも、削除できない設定となっています。

**Comment by masao** [comment]
修正を確認しました。クローズします。
