### ISSUE TITLE
デモサーバーで「貸出の一覧」のTSV出力がエラー

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1404]
- [x] markdownのマニュアル修正必要なし #1348 （デモサーバーの障害のため）

#1377 の確認をしようとして気づきました。<s>デモサーバーだけの問題なのか、1.3.0の問題なのかのきりわけはやってません。</s> 

adminでログイン、「貸出・返却・予約」--> 貸出履歴 --> 「TSV」
https://enju.next-l.jp/checkouts.txt?locale=ja
We're sorry, but something went wrong.
となります。

**Comment by yegusa** [comment]
公式1.3.0VM版(enju_leaf_vm_default_1540858394676_97776.vbox)ではエラーが出なかったのを確かめましたので、デモサーバーの問題のようです。

**Comment by nabeta** [comment]
古いEnjuでは貸出のあった個別資料のレコードを削除できてしまっていたため、そのレコードの個別資料番号を表示しようとしてエラーになっていました。
ひとまずエラーにしないようにしますが、貸出のあった個別資料の削除は、Enjuではなくデータベース側で参照制約をつけて防ぐようにすべきだと思います。

**Comment by yegusa** [comment]
動くようになったのを確認したのでクローズします。

「貸出のあった個別資料の削除は、Enjuではなくデータベース側で参照制約をつけて防ぐように」は、
別issue #1412 であつかうこととします。
