### ISSUE TITLE
貸出履歴のTSVでusernameが出力されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1405]
#1377 を調べていて気づきました。

1.3.0の公式VM(enju_leaf_vm_default_1540858394676_97776.vbox)で現象を確認しました。

enjuadminでログイン、「貸出・返却・予約」-->貸出履歴--> 「TSV」
http://localhost:8080/checkouts.txt?locale=ja

（username:yegusa 一つは返却済み、一つは貸出中）
![next l enju leaf 5](https://user-images.githubusercontent.com/1328499/48328810-21fdf680-e689-11e8-82a1-0349b1cb1753.png)

```
username	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2018-11-12 14:43:02 +0900)
	001002	1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで!	2018-11-12 13:36:41 +0900	2018-11-26 23:59:59 +0900	2018-11-12 13:36:54 +0900
	001001	10日でおぼえるRuby on Rails入門教室	2018-11-12 13:35:54 +0900	2018-11-26 23:59:59 +0900	
```

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

参考（縦横逆にして、日本語ラベルをつけたもの）：

列名|日本語ラベル|レコード1|レコード2
-- | -- | -- | --
username | 利用者アカウント |   |  
（user_number） | （利用者番号）　（現在列ごとない） |   | 
item_identifier | 所蔵情報ID | 001002 | 001001
title | 原題 | 1人でつくるRuby   on Rails3アプリケーション : Webアプリケーションの開発から公開まで! | 10日でおぼえるRuby   on Rails入門教室
checked_out_at | 貸出日 | 2018-11-12   13:36:41 +0900 | 2018-11-12   13:35:54 +0900
due_date | 返却期限 | 2018-11-26   23:59:59 +0900 | 2018-11-26   23:59:59 +0900
checked_in_at | 返却日 | 2018-11-12   13:36:54 +0900 |  
(created_at: 2018-11-12 13:37:24 +0900) | （貸出の一覧のTSV出力日時） |   |  

参考. 1.2.2ではusernameは表示されていたようです( #1377 より )

**Comment by yegusa** [comment]
まとめ：
- NG: username が表示される
- NG: user_numberが表示される
（現在、user_numberは列そのものがない）

**Comment by nabeta** [comment]
該当ユーザの貸出履歴が保存されない設定になっていませんでしょうか？ 以下のページでの「貸出の履歴を保存する」という項目になります。
https://enju.next-l.jp/my_account/edit

**Comment by nabeta** [comment]
user_numberを表示するように修正しました。
https://enju.next-l.jp/checkouts.txt?locale=ja

**Comment by masao** [comment]
username列とそのデータが追加されたことを確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/49336322-01e7a480-f643-11e8-8927-f9ba46f3a10e.png)

**Comment by yegusa** [comment]
マニュアルとしては，1.3.1からは正しくusernameが表示されるようになった旨を必要なら書く。
