### ISSUE TITLE
貸出履歴のTSVでuser_numberを出力してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1406]
- [ ] user_number（利用者番号）列を表示
( username 利用者アカウントの表示の方は #1405 で )

<s>version 1.3.0 の #1367 でできていたはずなのですが、  user_numberが列ごと表示されていないようですので、派生issue として立ち上げておきます。
 #1377 を調べていて気づきました。</s>

#1393 のと合わせて、user_numberが列があったほうがいいと思いますので、あげておきます。

1.3.0の公式VM(enju_leaf_vm_default_1540858394676_97776.vbox)で現象を確認しました。

enjuadminでログイン、「貸出・返却・予約」-->貸出履歴--> 「TSV」
http://localhost:8080/checkouts.txt?locale=ja

（username:yegusa, user_number:100001,  一つは返却済み、一つは貸出中）
![next l enju leaf 6](https://user-images.githubusercontent.com/1328499/48329460-4a3b2480-e68c-11e8-9c17-91af42bd3a6d.png)

```
username	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2018-11-12 14:43:02 +0900)
	001002	1人でつくるRuby on Rails3アプリケーション : Webアプリケーションの開発から公開まで!	2018-11-12 13:36:41 +0900	2018-11-26 23:59:59 +0900	2018-11-12 13:36:54 +0900
	001001	10日でおぼえるRuby on Rails入門教室	2018-11-12 13:35:54 +0900	2018-11-26 23:59:59 +0900	
```

enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0

参考（縦横逆にして、日本語ラベルをつけたもの）：

列名|日本語ラベル|レコード1|レコード2
-- | -- | -- | --
username | 利用者アカウント |   |  
（user_number） | （利用者番号）　（現在列ごとない） |   | 
item_identifier | 所蔵情報ID | 001002 | 001001
title | 原題 | 1人でつくるRuby   on Rails3アプリケーション : Webアプリケーションの開発から公開まで! | 10日でおぼえるRuby   on Rails入門教室
checked_out_at | 貸出日 | 2018-11-12   13:36:41 +0900 | 2018-11-12   13:35:54 +0900
due_date | 返却期限 | 2018-11-26   23:59:59 +0900 | 2018-11-26   23:59:59 +0900
checked_in_at | 返却日 | 2018-11-12   13:36:54 +0900 |  
(created_at: 2018-11-12 13:37:24 +0900) | （貸出の一覧のTSV出力日時） |   |

**Comment by nabeta** [comment]
user_numberを出力するように修正しました。
https://enju.next-l.jp/checkouts.txt?locale=ja

**Comment by masao** [comment]
user_number 列は追加されましたが、実際のユーザ番号が出力されていません。
![image](https://user-images.githubusercontent.com/38825/49336313-d8c71400-f642-11e8-9bad-c7fb93493f7e.png)

**Comment by nabeta** [comment]
修正済みです。

**Comment by masao** [comment]
確認しました。クローズします。

```
username	user_number	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2019-03-24 14:26:29 +0900)
enjuadmin	0	001	Social Isolationのメカニズムに関する臨床社会心理学的研究	2019-03-24 14:26:00 +0900	2019-04-03 23:59:59 +0900	
```

**Comment by yegusa** [comment]
マニュアルで修正が必要な箇所

運用マニュアルの貸出履歴のTSV
https://next-l.github.io/manual/1.2/enju_operation_6.html#columntsv

```text
username	user_number	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2020-01-11 14:56:04 +0900)
zuser01	z123	110333796	基本件名標目表	2020-01-11 14:55:44 +0900	2020-02-10 23:59:59 +0900	2020-01-11 14:55:51 +0900
20020044	20020044	876123	Ruby on Rails 5.0インストール手順書	2019-12-19 14:59:23 +0900	2020-01-18 23:59:59 +0900	
		156106009970	図書館の問題利用者 : 前向きに対応するためのハンドブック	2019-10-03 11:50:06 +0900	2019-11-02 23:59:59 +0900	2019-10-03 12:09:56 +0900
```

利用者の貸出履歴のTSV出力
https://next-l.github.io/manual/1.2/enju_user_5.html#3-tsv%E3%81%8C%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%BE%E3%81%99

```text
username	user_number	item_identifier	title	checked_out_at	due_date	checked_in_at	(created_at: 2020-01-11 15:07:50 +0900)
zuser01	z123	011645041	イェルサレムのアイヒマン : 悪の陳腐さについての報告	2020-01-11 15:06:24 +0900	2020-02-10 23:59:59 +0900	
zuser01	z123	110333796	基本件名標目表	2020-01-11 14:55:44 +0900	2020-02-10 23:59:59 +0900	2020-01-11 14:55:51 +0900
```
