### ISSUE TITLE
1.3 系マニュアルのサイト内検索を1.2から1.3に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1408]
- [ ] markdownのマニュアルを修正することそのもののissue #1418

https://next-l.github.io/manual/1.3/

この赤四角の部分です。

![enju leaf 1](https://user-images.githubusercontent.com/1328499/48331963-7018f700-e695-11e8-9f61-1caf477c71e9.png)

**Comment by nabeta** [comment]
現状だとGoogleの検索フォームは1.1と1.2で共通のものを使っているので、検索結果には1.1と1.2が混在して出てきています。1.3のみにする場合、別途検索フォームを定義する必要がありそうです。

**Comment by yegusa** [comment]
もしくは、1.1, 1.2, 1.3 を対象とするようにするというのでもあり。

**Comment by masao** [comment]
一応、ファセットで絞り込めるように変更しました。
![image](https://user-images.githubusercontent.com/38825/49336905-e5049e80-f64d-11e8-90dd-ec79f1f50ef2.png)

**Comment by yegusa** [comment]
確認しました。いいですね！
クローズします。
