### ISSUE TITLE
貸出の時に貸出する資料が表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1409]
- [x] markdownのマニュアル修正必要なし（バグ修正のため） #1348

致命的なバグなので、早々に修正して緊急リリースすべきように思います。
1.3.0 公式VM(enju_leaf_vm_default_1540858394676_97776.vbox)で現象を確認しました。
デモサーバーでも同様な現象を確認しました。

貸出の時に貸出する資料が所蔵情報ID（バーコード）
を入力して読み込みとしても表示されません。
表示されないまま、貸出処理に進むことはできました。

詳細：
1. ［貸出・返却・予約］メニューから［貸出］を選択
2. 利用者番号を入力し［読み込み］ボタンをクリック
3. 所蔵IDを入力し、［読み込み］ボタンをクリック

1.3.0 現状：
- NG: 貸し出す予定の本の情報が表示される
- NG:「貸出セッションは正常に作成されました」が消える
![next l enju leaf 2](https://user-images.githubusercontent.com/1328499/48332782-6349d280-e698-11e8-8a8e-4708d11eaa2c.png)

正しい動作例：
- OK: 貸し出す予定の本の情報が表示される
- OK:「貸出セッションは正常に作成されました」が消える
![image](https://user-images.githubusercontent.com/1328499/48332837-9d1ad900-e698-11e8-8d0c-34b222a3e4da.png)

参考：マニュアル　6-1-1 資料を貸し出す
https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-1

Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
Environment: production
Gems:
actioncable: 5.1.6
actionmailer: 5.1.6
actionpack: 5.1.6
actionview: 5.1.6
activejob: 5.1.6
activemodel: 5.1.6
activerecord: 5.1.6
activesupport: 5.1.6
acts_as_list: 0.9.17
addressable: 2.5.2
arel: 8.0.0
awesome_nested_set: 3.1.4
bcrypt: 3.1.12
bindex: 0.5.0
browser: 2.5.3
builder: 3.2.3
bundler: 1.17.1
byebug: 10.0.2
capybara: 2.18.0
charlock_holmes: 0.7.6
childprocess: 0.9.0
climate_control: 0.2.0
cocoon: 1.2.12
coffee-rails: 4.2.2
coffee-script: 2.4.1
coffee-script-source: 1.12.2
concurrent-ruby: 1.0.5
crass: 1.0.4
devise: 4.5.0
dotenv: 2.5.0
dotenv-rails: 2.5.0
dynamic_form: 1.1.4
enju_biblio: 0.3.0
enju_circulation: 0.3.0
enju_event: 0.3.0
enju_leaf: 1.3.0
enju_library: 0.3.0
enju_manifestation_viewer: 0.3.0
enju_message: 0.3.0
enju_ndl: 0.3.0
enju_seed: 0.3.0
enju_subject: 0.3.0
erubi: 1.7.1
erubis: 2.7.0
exception_notification: 4.2.2
execjs: 2.7.0
faraday: 0.15.3
ffi: 1.9.25
fix_microsoft_links: 0.1.6
friendly_id: 5.2.4
geocoder: 1.5.0
globalid: 0.4.1
globalize: 5.1.0
globalize-accessors: 0.2.1
highline: 2.0.0
i18n: 1.1.1
jbuilder: 2.7.0
jquery-rails: 4.3.3
jquery-ui-rails: 4.2.1
kaminari: 1.1.1
kaminari-actionview: 1.1.1
kaminari-activerecord: 1.1.1
kaminari-core: 1.1.1
kramdown: 1.17.0
library_stdnums: 1.6.0
lisbn: 0.2.4
listen: 3.1.5
loofah: 2.2.2
mail: 2.7.1
marc: 1.0.2
method_source: 0.9.0
mime-types: 3.2.2
mime-types-data: 3.2018.0812
mimemagic: 0.3.2
mini_mime: 1.0.1
mini_portile2: 2.3.0
minitest: 5.11.3
mono_logger: 1.1.0
multi_json: 1.13.1
multipart-post: 2.0.0
mustermann: 1.0.3
nio4r: 2.3.1
nokogiri: 1.8.5
non-stupid-digest-assets: 1.0.9
nori: 2.6.0
options: 2.3.2
orm_adapter: 0.5.0
paper_trail: 10.0.1
paperclip: 5.3.0
paperclip-meta: 3.1.0
pg: 1.1.3
pr_geohash: 1.0.0
progress_bar: 1.3.0
public_suffix: 3.0.3
puma: 3.12.0
pundit: 2.0.0
rack: 2.0.5
rack-protection: 2.0.4
rack-test: 1.1.0
rails: 5.1.6
rails-dom-testing: 2.0.3
rails-html-sanitizer: 1.0.4
rails_autolink: 1.1.6
railties: 5.1.6
rake: 12.3.1
rb-fsevent: 0.10.3
rb-inotify: 0.9.10
redis: 4.0.2
redis-actionpack: 5.0.2
redis-activesupport: 5.0.7
redis-namespace: 1.6.0
redis-rack: 2.0.4
redis-rails: 5.0.2
redis-store: 1.6.0
request_store: 1.4.1
responders: 2.4.0
resque: 1.27.4
ri_cal: 0.8.8
rsolr: 2.2.1
ruby_dep: 1.5.0
rubyzip: 1.2.2
sass: 3.6.0
sass-listen: 4.0.0
sass-rails: 5.0.7
scrub_rb: 1.0.1
selenium-webdriver: 3.14.1
simple_form: 4.0.1
sinatra: 2.0.4
sitemap_generator: 6.0.1
spring: 2.0.2
spring-watcher-listen: 2.0.1
sprockets: 3.7.2
sprockets-rails: 3.2.1
statesman: 3.4.1
strip_attributes: 1.8.0
sunspot: 2.3.0
sunspot_rails: 2.3.0
sunspot_solr: 2.3.0
terrapin: 0.6.0
thor: 0.20.0
thread_safe: 0.3.6
tilt: 2.0.8
timeliness: 0.3.8
turbolinks: 5.2.0
turbolinks-source: 5.2.0
tzinfo: 1.2.5
uglifier: 4.1.19
unf: 0.1.4
unf_ext: 0.0.7.5
validates_timeliness: 4.0.2
vegas: 0.1.11
warden: 1.2.7
web-console: 3.7.0
websocket-driver: 0.6.5
websocket-extensions: 0.1.3
xpath: 3.2.0
Languages:
en: English
ja: 日本語 (既定の言語)

**Comment by nabeta** [comment]
turbolinksを無効にする必要がありそうです。Gemfileを以下のように編集したあと、

```
# gem 'turbolinks', '~> 5'
```

bundle updateを実行し、Enjuを再起動します。

```sh
$ bundle update
```

- デモサーバは設定を変更しました。
- Wikiの新規インストール手順で、turbolinksを有効にしないようにしました。rails new を実行するときに --skip-turbolinks オプションを追加しています。
- Enju関係のgemの問題ではないため、gemの再リリースは不要です。仮想マシンは再作成を行います。

**Comment by yegusa** [comment]
ってことは、これは、マイルストーンは 1.3.0 の方がいいのかな？

**Comment by masao** [comment]
1.3系の更新手順文書を用意しないとダメだと思います。。
cf. https://github.com/next-l/enju_leaf/wiki/Update

**Comment by yegusa** [comment]
公式　1.3.0 VM enju_leaf_vm_default_1542300056037_65648.vbox でできることを確認しました。

ドキュメント修正よろしく

**Comment by yegusa** [comment]
うーん、1.3.1なのか、1.3.0なのかようわからんが。。。ま、いっか。
ドキュメントの修正も確認したのでクローズします。

https://github.com/next-l/enju_leaf/wiki/Update/_compare/b725fa29ec94d3fbd573ad5db892f7f91de89c07
