### ISSUE TITLE
マニュアルサイトでHTTPSのみを使用する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1414]
ブラウザでのHTTP接続時の警告も厳しくなりましたし、HTTPSのみにしてよいと思います。
GitHub Pagesの設定で「Enforce HTTPS」のチェックを有効にすればよいようです。
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by masao** [comment]
はい、よいように思います。

**Comment by nabeta** [comment]
有効化しました。

**Comment by nabeta** [comment]
HTTPからHTTPSの転送は自動的に行われます。また、設定画面は以下です。
https://github.com/next-l/manual/settings

**Comment by masao** [comment]
確認の際に気になった jquery の呼び先を "https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" を直接みるようにしました。
cf. https://github.com/next-l/manual/commit/223e3592fe3377bfc1906eff2359dd7f72d4bce3

ひとまずクローズします。
