### ISSUE TITLE
foreman起動時のポート変更?

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1415]
1.3系列を新規インストールしてみたところ、HTTP webはポート3000番ではなく、5200番をみるように変わっている（development環境）。

インストールマニュアルを変更する必要ありか？

**Comment by masao** [comment]
了解です。インストールマニュアルの記述を修正しました。

**Comment by yegusa** [comment]
どこの変更？確認しようとしたけどわからんかった。

**Comment by masao** [comment]
https://github.com/next-l/enju_leaf/wiki/Install#enju-leaf%E3%81%AE%E5%88%9D%E6%9C%9F%E8%A8%AD%E5%AE%9A にて、Procfile 内で具体的なポート番号 3000 を指定している箇所が追加になっています（-p 3000）。

**Comment by yegusa** [comment]
確認しました。クローズします。
