### ISSUE TITLE
個別モジュールのテスト用Solrが起動しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1417]
個別モジュールのテスト時にはテスト用Solrサーバを起動する必要がある。

個別のモジュールディレクトリに移動した後で以下のコマンドを実行すること：
```
RAILS_ENV=test rake app:sunspot:solr:start
```

**Comment by nabeta** [comment]
Wikiに内容を移した後にcloseします。

**Comment by nabeta** [comment]
以下のページに内容を転記しました。closeします。
https://github.com/next-l/enju_leaf/wiki/ModuleDevelopment
