### ISSUE TITLE
利用者グループ画面における貸出区分との関係追加が機能していない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1424]
対応づく貸出区分が表示されていない。
更新ボタンを押しても関係情報は記録されていない状態です。
おそらく実装が中途半端な状態と思われます。
![next l enju leaf](https://user-images.githubusercontent.com/38825/49336242-b8e32080-f641-11e8-9a30-836f5994d740.png)

**Comment by nabeta** [comment]
この画面での貸出区分のフォームをいったん削除しました。

**Comment by masao** [comment]
確認しました。クローズします。
