### ISSUE TITLE
Rails 5.2対応

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1426]

**Comment by nabeta** [comment]
enju_leaf-1.3.0リリース時にRails 5.2未対応だったglobalizeが現時点では対応しているので、1.3系でもRails 5.2への対応は可能ですが、どうしましょうかね。 @masao

**Comment by nabeta** [comment]
Rails 5.1から設定ファイルの書き換えなしで動くようであれば、enju_leaf-1.3.2の仮想マシンはRails 5.2で作成する。

**Comment by nabeta** [comment]
Rails 5.2で作成済み。
https://www.next-l.jp/?page=VM

**Comment by yegusa** [comment]
私は確認のやり方わからんので，確認， @masao さんよろしく。

**Comment by masao** [comment]
https://github.com/next-l/enju_leaf/wiki/Install インストール手順がまだ 5.1 系ですね。

**Comment by masao** [comment]
5.2系で動くことは確認しました。

**Comment by masao** [comment]
ひとまずこちらはクローズします。
