### ISSUE TITLE
不具合：除籍済み資料がログインしていない状態で表示されてしまいます

### ISSUE THREAD

**Issue by Stomaru** [next-l/enju_leaf#1428]
除籍済み資料がログアウト状態でも表示されてしまいます。
運用上、除籍した資料は利用者から検索できない方が望ましいです。
職員以外は検索できないように変更をお願いします。

**Comment by yegusa** [comment]
以前はできていたので，バグですね。

参考：4-5-4 除籍済みの検索結果一覧での表示のされ方
https://next-l.github.io/manual/1.1/enju_operation_4.html#section4-5-4

**Comment by yegusa** [comment]
このissueでできていた時代はあるようです（除籍じゃなくて作業中だけど，同じはず）。 1.1.0.rc10の時。
https://github.com/next-l/enju_leaf/issues/207

**Comment by nabeta** [comment]
「除籍」メニューから除籍したものは表示されないはずです。
所蔵の編集画面で「除籍済み」を選んでも、除籍したことにはなりません。むしろこの動作に問題がありそうです。

**Comment by nabeta** [comment]
「除籍済み」の所属がLibrarian権限のない状態で表示されないことを確認しました。
https://enju.next-l.jp/manifestations/12698

**Comment by masao** [comment]
利用者権限で表示されないことを手元の1.3.2でも確認しました。クローズします。
