### ISSUE TITLE
出版日付情報のNDL取り込みの精緻化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1429]
NDLサーチからの書誌情報における出版日付は
http://iss.ndl.go.jp/books/R100000002-I000008282661-00 にあるように、dcterms:date 要素は任意の文字列なので、 dcterms:issued 要素があればそちらを優先したほうがよいと思われます。

cf. http://www.ndl.go.jp/jp/dlib/standards/meta/2011/12/application-profile.pdf#page=40

**Comment by nabeta** [comment]
むしろdcterms:issuedのみを見るほうがよいのかなあ、と思いました。masterブランチはそのように修正しています。

**Comment by nabeta** [comment]
1.3ブランチもテストつきで修正済みです。

**Comment by masao** [comment]
ISBN「0262220733」取り込み時にエラーが出ます。

![image](https://user-images.githubusercontent.com/38825/54875269-12fd3100-4e3f-11e9-9875-f646a74940ae.png)

**Comment by nabeta** [comment]
rspecでも開発サーバでも試してみましたが、正常にインポートが行えています。
https://dev.next-l.jp/manifestations/24465

**Comment by masao** [comment]
確認しました。再度実行したら動いたので、古いバージョンが動いたままだったのかもしれません。ひとまず、クローズします。
