### ISSUE TITLE
閲覧制限が外れている

### ISSUE THREAD

**Issue by taniaikayoko** [next-l/enju_leaf#1430]
所蔵情報の閲覧制限が効いていない。
書誌・所蔵ともに、非公開項目を作るべき。

**Comment by nabeta** [comment]
レコードごとの閲覧制限はあるが、項目ごとの制限はないため、どの項目を非表示にするかをまとめる必要があります。なにか現時点でまとまっているものはありますでしょうか。 @yegusa

**Comment by yegusa** [comment]
TSV出力の方を参考にしたらどうでしょうか？

1-1-3 書誌と所蔵のTSVの項目
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export

**Comment by masao** [comment]
一通り実装できていることを確認しました。クローズします。

**Comment by yegusa** [comment]
マニュアルにはすでに閲覧権限は追記ずみなので、システム出戻り？だったっぽいので、マニュアル修正の必要はなし。
