### ISSUE TITLE
書誌/所蔵「業務メモ」項目があるといいかも？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1432]
業務担当者のみに共有したい項目として。 Enju WS 2019-01-26にて

**Comment by nabeta** [comment]
項目名（カラム名）を決めましょうか。memoとか？

**Comment by nabeta** [comment]
「他の職員への伝達事項」という意味で、memoでよさそう。
https://dictionary.cambridge.org/ja/dictionary/english/memo

**Comment by nabeta** [comment]
デモサーバに反映済みです。
https://enju.next-l.jp/manifestations/4169/edit

![image](https://user-images.githubusercontent.com/11428/70379135-2835d380-196c-11ea-9e09-b80d9d597f93.png)

**Comment by masao** [comment]
追加されたことを確認しました。クローズします。

**Comment by yegusa** [comment]
- [ ] マニュアル　書誌の「業務メモ」項目説明 enju_operation_4.html/4-2-0節（新設）
- [ ] マニュアル　所蔵の「業務メモ」項目説明 enju_operation_4.html/4-3-0節（新設）
