### ISSUE TITLE
資料検索の結果表示項目のカスタマイズについて

### ISSUE THREAD

**Issue by yut148** [next-l/enju_leaf#1435]
お世話になります。
検索後資料があった場合、一覧表示となりますが、ここに表示項目を追加したい場合どの様に追加すればいいでしょうか。
具体的には件名subject.termを追加できればと思います。
enju_biblio/app/views/manifestations/index.html.erb
内にて以下の
<table class="table table-striped index" id="manifestation_list">
   <%= render @manifestations %>
</table>
@manifestationsで表示しているところまでは理解できたのですが、@manifestations内の各項目例えば@manifestations[0]にsubject.termを追加したい場合はどの様に改修すればよろしいでしょうか。
以下の図で赤丸の箇所となります。

![-](https://user-images.githubusercontent.com/1026761/51959561-4a330f80-2498-11e9-9a53-27f2e04755b6.PNG)

**Comment by yegusa** [comment]
マニュアルは，インストールの10章あたりに追加が良いと思います。 @masao マニュアル追加よろしくお願いします。
