### ISSUE TITLE
マニュアル追加：iPadで書影を簡単に追加できる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1439]
マニュアル追加：iPadで書影を簡単に追加できる方法に追加する。

**Comment by yegusa** [comment]
利用ケース：
ISBNでNDLから書誌が引っ張って来れなかった場合などに，
とりあえず，書影だけでも写真に撮って登録して，
貸出や返却に使えるようにするなど。

**Comment by yegusa** [comment]
https://next-l.github.io/manual/1.3/enju_operation_4.html#4-%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E9%81%B8%E6%8A%9E%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%97%E3%81%A6%E3%82%A2%E3%83%83%E3%83%97%E3%81%97%E3%81%9F%E3%81%84%E7%94%BB%E5%83%8F%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E9%81%B8%E6%8A%9E%E3%81%97%E3%81%BE%E3%81%99

4. ［ファイルを選択］ボタンをクリックしてアップしたい画像ファイルを選択します。
-->
4. ［ファイルを選択］ボタンをクリックしてアップしたい画像ファイルを選択するか、写真を撮ります（例：iPadやiPhoneでは［ファイルを選択］ボタンをクリックすると「写真またはビデオを撮る」が選択して撮影できます）。

というような修正をする。

**Comment by yegusa** [comment]
追加しました。

**Comment by yegusa** [comment]
確認誰かやってください。

**Comment by masao** [comment]
マニュアル文書を確認しました。
https://next-l.github.io/manual/1.3/enju_operation_4.html#section4-8
問題無いかと思います。クローズします。
