### ISSUE TITLE
資料の表示で「タイトルのヨミ」を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1442]
小学生ややさしい日本語のみが理解できる人向けにあったほうが良いと思います。

**Comment by nabeta** [comment]
表示部分はどこにしましょうか？

**Comment by yegusa** [comment]
シリーズ情報や価格とかと同様な感じで，

タイトルのヨミ: ヒト ガ シナナイ ボウサイ

を入れる感じで。

つまり，以下の赤四角の部分。

![えんじゅ図書館   人が死なない防災   Next L Enju Leaf](https://user-images.githubusercontent.com/1328499/54880454-0f41cc80-4e88-11e9-90bf-ad8165326c4d.png)

**Comment by nabeta** [comment]
以下のように追加しました。
https://enju.next-l.jp/manifestations/12692
![image](https://user-images.githubusercontent.com/11428/55287796-ae1a7b80-53e8-11e9-9b2b-2af35ab64d92.png)

**Comment by yegusa** [comment]
enju のデモサーバーでできていることを確認しましたので，クローズします。

![えんじゅ図書館   キーワードで学ぶ最新情報トピックス 2019   Next L Enju Leaf](https://user-images.githubusercontent.com/1328499/57582166-52b9ce00-74fc-11e9-9b8c-4db2afedc252.png)

Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Environment: production
enju_biblio: 0.3.2
enju_circulation: 0.3.3
enju_event: 0.3.2
enju_leaf: 1.3.2
enju_library: 0.3.3
enju_manifestation_viewer: 0.3.2
enju_message: 0.3.1
enju_ndl: 0.3.1
enju_seed: 0.3.2
enju_subject: 0.3.1
