### ISSUE TITLE
1.3.1 で貸出履歴の貸出ずみの行の削除リンクをクリックしたらWe're sorryになった

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1444]
![image](https://user-images.githubusercontent.com/1328499/54876522-ca507280-4e54-11e9-901d-8f80492ded16.png)

adminでログインしているときに，一般ユーザーyukaの返却ずみの貸出履歴レコード行の削除をクリックしたところ，We're Sorryに。

1.3.1 の公式仮想マシン enju_leaf_vm_default_1542922236264_27605.vbox にて
現象を確認

**Comment by nabeta** [comment]
ここでの貸出履歴の削除は、実際にはユーザの情報のみを削除するようになっているのですが、すでにユーザの情報が削除された履歴にも「削除」リンクが表示されていました。表示されないように修正しました（以下の図の2行目が例）。
<img width="712" alt="スクリーンショット 2019-04-30 14 20 50" src="https://user-images.githubusercontent.com/11428/56942037-2f357180-6b53-11e9-803a-181f469495b5.png">

**Comment by nabeta** [comment]
enju_circulation-0.3.3で修正済みです。

**Comment by yegusa** [comment]
- adminで貸出履歴のページに行く
- 削除をクリックする ![貸出   えんじゅ図書館   Next L Enju Leaf (9)](https://user-images.githubusercontent.com/1328499/57569892-b5e12d00-7436-11e9-9b0a-1f298bb53543.png)
- その行の「ユーザー情報」のみが消える ![貸出   えんじゅ図書館   Next L Enju Leaf (10)](https://user-images.githubusercontent.com/1328499/57569927-2425ef80-7437-11e9-8a7a-9310916d2860.png)

ってことなんですね。了解です。

また，利用者情報がないものは，「削除」リンクが表示されていないのも確認しました。
![貸出   えんじゅ図書館   Next L Enju Leaf (11)](https://user-images.githubusercontent.com/1328499/57569943-63ecd700-7437-11e9-897d-69e3dc874ccb.png)

デモサーバーで確認しました。

Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
Environment: production
enju_biblio: 0.3.2
enju_circulation: 0.3.3
enju_event: 0.3.2
enju_leaf: 1.3.2
enju_library: 0.3.3
enju_manifestation_viewer: 0.3.2
enju_message: 0.3.1
enju_ndl: 0.3.1
enju_seed: 0.3.2
enju_subject: 0.3.1

クローズします。

**Comment by yegusa** [comment]
マニュアルの修正必要：

### 削除リンクについて説明をつける

https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-1-3 の 2 のMemoに

- 削除リンクをクリックすると，ユーザー情報のみが削除される。貸出履歴自体は削除されない。
- （すでにユーザー情報が削除された貸出履歴には削除リンクは表示されない）

を追加する。

### 画像の修正　image_operation_181.png

https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-1-3 の 2の画像：
https://next-l.github.io/manual/assets/images/1.1/image_operation_181.png

を修正して，

→ 1.3フォルダに登録
![image_operation_181](https://user-images.githubusercontent.com/1328499/57570193-7b798f00-743a-11e9-89cb-5c1db8c2643a.png)

### 画像の修正
https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-1-4 の2の画像

(まだあるかも，とりあえず。)

**Comment by yegusa** [comment]
https://next-l.github.io/manual/1.3/enju_operation_6.html#section6-4 2の画像

https://next-l.github.io/manual/assets/images/1.1/image_operation_207.png
これを修正する

![image_operation_207](https://user-images.githubusercontent.com/1328499/57579835-d499ff00-74dc-11e9-983c-aa0f128bca74.png)

**Comment by yegusa** [comment]
修正しました
