### ISSUE TITLE
書誌に画像追加するときのボタンを[ファイルを選択]ではなくて[画像を選択]に変えてはどうか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1446]
#1439 で気づいたのですが，iPad などでは，直接カメラで撮影できますので，[ファイルを選択]ではなくて[画像を選択]に変えてはどうか？

**Comment by masao** [comment]
[ファイルを選択] 部分のラベルはブラウザ側の仕様で、コンテンツページ側からは指定できない仕様です。これは原理的に無理なので、wont fix としてクローズしてしまおうと思われます。

**Comment by yegusa** [comment]
なるど，了解です。

**Comment by yegusa** [comment]
思ったのだけど，ブラウザデフォルトじゃなくて，こちらで用意したボタンを使うようにするって方向はないでしょうか？

**Comment by yegusa** [comment]
なので，一旦，ラベルをwontfix から discussion に変更します。

**Comment by nabeta** [comment]
個人的には変えなくてもいいのではと思うのですが、CSSで変更することは可能なようです。たとえばこんな感じですかね。
http://creator.dena.jp/archives/43699692.html

**Comment by yegusa** [comment]
Enju WS 2019-05-19 の議論の結果，やはりwontfix で良いことにします。
