### ISSUE TITLE
デモサーバー：利用者情報のエクスポートが「失敗」になります

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1447]
デモサーバーで確認した現象です。
1.3.1公式仮想マシンでは起きなかったことを確認しています。

利用者情報のエクスポートをしようとしたところ，「失敗」となりました
https://enju.next-l.jp/user_export_files

**Comment by nabeta** [comment]
message_transitions テーブルと message_request_transitions テーブルに、それぞれ created_at と updated_at カラムがなかったため、エラーになっていました。アップデート時の作業に抜けがあったと思われます。
現在は正常に動作しています。
https://enju.next-l.jp/user_export_files/43

**Comment by yegusa** [comment]
できることを確認しましたので，クローズします。
