### ISSUE TITLE
プロジェクトのトップページのお知らせ表示を改善する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1450]
現在のトップページの「お知らせ」には、Facebookページのタイムラインを埋め込んでいるが、直近の更新しか表示されない。このため、次々回のワークショップの情報が表示されてしまう。

![image](https://user-images.githubusercontent.com/11428/56843491-8bdb2700-68dc-11e9-986e-73ad0b89d180.png)

ワークショップ開催日が近づいたら手動で更新し直すのもよいが、更新を忘れることが多いと見込まれるため、Google CalendarにFacebookのイベント情報をエクスポートして埋め込み表示を行うことを考える。

**Comment by nabeta** [comment]
2段組の表示とした。
![image](https://user-images.githubusercontent.com/11428/56843687-bded8880-68de-11e9-8a05-6fa1ff9f5236.png)

編集は以下のページで行う。
https://www.next-l.jp/?page=Facebook

**Comment by nabeta** [comment]
FRBR&RDA勉強会のページも追加して3列表示にしたい。ただし、これはFacebookページではなくFacebookグループのため、埋め込みURLを変えるだけでは動作しなかった。

**Comment by nabeta** [comment]
見出しやヘッダの縮小表示を追加した。
<img width="920" alt="トップページ" src="https://user-images.githubusercontent.com/11428/56944167-52651e80-6b5d-11e9-888a-420449dbe028.png">

HTMLは以下のようになっている。
```html
<div style="float: left">
プロジェクトからのお知らせ<br />
<div class="fb-page" data-href="https://www.facebook.com/projectnextl/" data-tabs="timeline" data-width="450" data-height="600" data-small-header="true" data-adapt-container-width="false" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/projectnextl/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/projectnextl/">Project Next-L</a></blockquote></div>
</div>
<div>
次回ワークショップ開催案内<br />
<div class="fb-page" data-href="https://www.facebook.com/projectnextl" data-tabs="events" data-width="450" data-height="500" data-small-header="true" data-adapt-container-width="true" data-hide-cover="true" data-show-facepile="false"><blockquote cite="https://www.facebook.com/projectnextl" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/projectnextl">Project Next-L</a></blockquote></div>
</div>
<div style="clear: left"></div>
```

**Comment by yegusa** [comment]
FRBR勉強会を出すんじゃなかったっけ？

**Comment by nabeta** [comment]
@yegusa FRBR勉強会はFacebookページではなくグループのため、同じ方法での埋め込みが使えないのです。
https://developers.facebook.com/docs/plugins/page-plugin

グループ用の埋め込みは参加ボタンしかつけられないようです。
https://developers.facebook.com/docs/plugins/group-plugin

**Comment by yegusa** [comment]
じゃあ，しょうがないですね。私は良いと思います。

**Comment by nabeta** [comment]
ほかに特に追加や要望がなければcloseしてください。

**Comment by yegusa** [comment]
一旦クローズします。また，なんかあったら新規に立ち上げましょう。
