### ISSUE TITLE
検索結果のJSONレスポンスにヒット数を含める

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1451]
NDC検索(#1448)で使用したい。現状のレスポンスは以下。
https://enju.next-l.jp/manifestations.json

**Comment by nabeta** [comment]
#1309, #1310 とあわせてフォーマットを考えるのがよいかもしれない。

**Comment by nabeta** [comment]
検索結果のJSONテンプレートファイルを追加しました。フォーマットはまだ適当で、JSON-LDにはなっていません。
https://enju.next-l.jp/manifestations.json

**Comment by masao** [comment]
検索結果が500件（表示の上限）となってしまうのを修正する。

**Comment by nabeta** [comment]
> 検索結果が500件（表示の上限）となってしまうのを修正する。

現時点では以下のように、検索のヒット総数を表示するようにしています。
https://dev.next-l.jp/manifestations.json

![image](https://user-images.githubusercontent.com/11428/69896058-18236000-137e-11ea-8d25-3499e04486d3.png)

**Comment by masao** [comment]
表示されることを確認しました。クローズします。

**Comment by yegusa** [comment]
これも、1.3.4なのではないか？

**Comment by yegusa** [comment]
あ、間違いコメントです。
