### ISSUE TITLE
テスト用のIIIFサーバを開発用サーバに用意する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1452]
IIIFのテストのため、Lorisをdev.next-l.jpにインストールする。
https://github.com/loris-imageserver/loris

**Comment by nabeta** [comment]
Doclerイメージを使って起動しました。
https://github.com/loris-imageserver/loris-docker

以下のURLで動作しています。画像のディレクトリは /opt/loris です。
http://dev.next-l.jp:5004/books.jpg/full/500,/90/default.jpg

**Comment by nabeta** [comment]
起動方法は以下です。どのディレクトリからでも実行可能です。
画像ファイルは dev.next-l.jpの /opt/loris 以下に保存してください。

```
$ sudo docker run -d -v /opt/loris:/opt/loris/tests/img -p 5004:5004 lorisimageserver/loris
```

**Comment by yegusa** [comment]
ベースURI
http://dev.next-l.jp:5004/books.jpg

基本情報
http://dev.next-l.jp:5004/books.jpg/info.json

**Comment by masao** [comment]
HTTPS上のサービス・ビューアから、上記のJSONを呼び出そうとするとブロックされるため、HTTPS系から提供した方が良いかもしれません。ご参考まで。

**Comment by nabeta** [comment]
dev.next-l.jp/iiif/ のようなサブディレクトリ以下でイメージサーバを動作させるのは面倒そうです。 iiif.next-l.jp みたいに別ホスト名を設定して、そこでHTTPSで動作させるのが楽だと思います。

**Comment by nabeta** [comment]
iiif.next-l.jp を設定しました。これで試していただけますか。 @yegusa 
https://iiif.next-l.jp/grape.jpg/full/500,/90/default.jpg

**Comment by yegusa** [comment]
https://iiif.next-l.jp/grape.jpg/info.json

**Comment by yegusa** [comment]
うーん，頻繁に，504 Gateway Time-out　になっちゃってダメな感じです。

目標としては，

IIIF マニフェストエディタ https://digital.bodleian.ox.ac.uk/manifest-editor/ に読み込めるようなものになることです。現在は，ぐるぐるなってしまってできません。

参考： https://qiita.com/yegusa/items/9ffbe130a475f1d1aec1

**Comment by yegusa** [comment]
今日やってみたらできました！

画像基本情報を使って設定してみた。
https://iiif.next-l.jp/grape.jpg/info.json

![スクリーンショット 2019-05-20 19 23 37](https://user-images.githubusercontent.com/1328499/58014860-c5e2c600-7b34-11e9-9873-937fe2ad03ee.png)

**Comment by yegusa** [comment]
参考：
標準画像 https://iiif.next-l.jp/grape.jpg/full/full/0/default.jpg

**Comment by yegusa** [comment]
id が http://dev.next-l.jp:5004 になっていますね。
https://iiif.next-l.jp にしないと変ですね。

https://iiif.next-l.jp/grape.jpg/info.json
```
"@id": "http://dev.next-l.jp:5004/grape.jpg"
```

**Comment by nabeta** [comment]
このissueはIIIFのテストとして作成したものですが、IIIF関連の機能（サーバ・クライアント）をEnjuの標準機能に含めるかどうか迷っています。あってもいいような気もしますが。

**Comment by nabeta** [comment]
Dockerで使えるIIIFのサーバを探したのですが、Cantaloupeがよさそうです。
https://cantaloupe-project.github.io/
https://hub.docker.com/r/uclalibrary/cantaloupe

**Comment by nabeta** [comment]
デモサーバに https://github.com/next-l/enju_leaf/pull/1721 を反映させました。また、 https://iiif.next-l.jp はCantaloupeを指すようにしています。

PictureFileとしてアップロードされたものが対象です。たとえば、以下の画像は、
https://enju.next-l.jp/picture_files/1

それぞれ以下のように提供されます。
- https://iiif.next-l.jp/iiif/3/1/info.json
- https://iiif.next-l.jp/iiif/3/1/full/256,/0/default.jpg

**Comment by nabeta** [comment]
マージ済みのため、クローズします。
