### ISSUE TITLE
蔵書点検モジュール(enju_inventory)を既定で同梱する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1455]

**Comment by yegusa** [comment]
1.3.3からやるのじゃないの？一応，1.3.3としておいたけど，どういうつもりか，どういう状況か教えてください。→ @nabeta

**Comment by nabeta** [comment]
はい、1.3.3のリリース時からの予定です。インストール時のテンプレートには追加済みです。
https://gist.github.com/nabeta/6c56f0edf5cc1c80d9c655c2660a9c59

**Comment by yegusa** [comment]
そういうつもりなら，マイルストーンは，1.3.3にすべきかと思いますので，次回からは同様の場合は，マイルストーンの修正もお願いしますね。あと，マニュアルも追加したいので，あとで使い方を教えてください。

**Comment by nabeta** [comment]
enju_leaf-1.3.4以降では、``rails g enju_leaf:quick_install``の実行時に、enju_inventoryのインストールを行うようにしました。

**Comment by masao** [comment]
インストールされるようになったことを確認しました。クローズします。

**Comment by yegusa** [comment]
@nabeta 使い方を、ここに書いておいてください。それを見て、mdマニュアルを更新します。

**Comment by yegusa** [comment]
@nabeta 使い方おしえてください。マニュアルに書きたいです。

**Comment by yegusa** [comment]
2022-03-07 に @nabeta にやり方を聞きながら、 @yegusa が動かしてみたが、本蔵書点検の機能は、中途半端な実装であり、利用できる状況になかったことを確認。
