### ISSUE TITLE
ゼロ件ヒットした時に，NDL Searchへ行くリンクやボタンをhttps対応にする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1456]
NDLサーチのWebAPIの呼び出しにHTTPSを使用する #1438 に関連

例：
https://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=NIER&commit=%E6%A4%9C%E7%B4%A2

![えんじゅ図書館   Next L Enju Leaf (16)](https://user-images.githubusercontent.com/1328499/57582735-35d4c900-7503-11e9-84f5-b94edac48575.png)

リンク先がhttpになってる：
http://iss.ndl.go.jp/

**Comment by nabeta** [comment]
「図書館の管理」→「システムの設定」→「図書館」→「検索エンジン」を選んだ後、
![image](https://user-images.githubusercontent.com/11428/57976972-3d76ff00-7a28-11e9-8f6f-d9459afd8690.png)

「URL」と「Base URL」のURLを修正してください。URLはラベル("NDL Search")のリンク、Base URLは実際に検索に使用するURLです。
![image](https://user-images.githubusercontent.com/11428/57976969-29330200-7a28-11e9-84c5-707228a68664.png)

**Comment by nabeta** [comment]
ところで、現在の新規インストールでは、これらの検索エンジンはひとつも登録されないようになっています。NDLサーチくらいはデフォルトで追加しておいたほうがよいかもしれません。

**Comment by yegusa** [comment]
マニュアルを修正する。

3-12-2 設定方法 https://next-l.github.io/manual/1.3/enju_setup_3.html#section3-12-2
5. 以下はその他の検索エンジンの設定例です。
の部分を修正する。

**Comment by nabeta** [comment]
マニュアル中のURLをhttpsに修正しました。スクリーンショットも更新しますか？ @yegusa 
https://github.com/next-l/manual/commit/e2e49699ac8dd29be0cd540cca04c4196f6b7cdf

**Comment by masao** [comment]
マニュアル修正を確認しました。ひとまずクローズします。

なお、標準設定については #941 で（なぜか2.0系のみですが）。
