### ISSUE TITLE
インストール手順のRails 5.2対応化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1457]
#1426 からの派生。インストール手順を Rails 5.2 対応にする。

**Comment by nabeta** [comment]
WikiのほうはRails 5.2系を使用する手順としています。
https://github.com/next-l/enju_leaf/wiki/Install#rails%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

**Comment by masao** [comment]
修正を確認しました。クローズします。
