### ISSUE TITLE
新規予約にアクセスすると「アクセス拒否」になる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1458]
一般ユーザにて、新規予約のページにアクセスすると、「アクセスが拒否されました」とエラーになる。

例: https://enju.next-l.jp/reserves/new?manifestation_id=12691

**Comment by nabeta** [comment]
デモサーバ上ではどのユーザで実行していますでしょうか？

**Comment by masao** [comment]
https://enju.next-l.jp/profiles/228 ユーザ権限 User, ユーザグループ 学生 ですね。

**Comment by nabeta** [comment]
利用者番号がないユーザは予約が行えないようになっています。ただ、現状ではそういうユーザも予約リンクが表示されます。
https://github.com/next-l/enju_circulation/blob/1.3/app/policies/reserve_policy.rb#L18

こちらで利用者番号を追加したので、別の本で予約をして試してもらえますか。
https://enju.next-l.jp/profiles/228

**Comment by masao** [comment]
なるほど、利用者番号を入れたら、予約できるようになりました。
![image](https://user-images.githubusercontent.com/38825/57978152-30ffa000-7a42-11e9-8a6d-11bea4dc9951.png)

ひとまずクローズします。
