### ISSUE TITLE
Docker Containerの作成に失敗する

### ISSUE THREAD

**Issue by evakichi** [next-l/enju_leaf#1461]
<pre>
$  sudo docker-compose run web rails g enju_leaf:seed
Starting enjuleafdocker_db_1 ... done
Running via Spring preloader in process 21
        rake  db:migrate
        rake  enju_leaf:setup
initial fixture files loaded.
        rake  enju_circulation:setup
initial fixture files loaded.
        rake  enju_subject:setup
initial fixture files loaded.
        rake  db:seed
rake aborted!
ActiveRecord::RecordInvalid: バリデーションに失敗しました。 Required roletranslation missing: ja.activerecord.errors.models.profile.attributes.required_role.required
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/validations.rb:52:in `save!'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `block in save!'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:212:in `transaction'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/transactions.rb:315:in `save!'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/suppressor.rb:48:in `save!'
/enju/db/seeds.rb:37:in `<main>'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/local/bundle/gems/bootsnap-1.4.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:54:in `load'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `block in load'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:257:in `load_dependency'
/usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/dependencies.rb:285:in `load'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/engine.rb:551:in `block in load_seed'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/engine.rb:666:in `with_inline_jobs'
/usr/local/bundle/gems/railties-5.2.3/lib/rails/engine.rb:551:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/tasks/database_tasks.rb:281:in `load_seed'
/usr/local/bundle/gems/activerecord-5.2.3/lib/active_record/railties/databases.rake:194:in `block (2 levels) in <main>'
/usr/local/bundle/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
        rake  enju_leaf:load_asset_files
enju_leaf: Default asset file(s) are loaded successfully.
</pre>

**Comment by nabeta** [comment]
お知らせありがとうございます。rolesテーブルの初期データの読み込みを修正したので、再度コンテナを作り直していただけますでしょうか。

**Comment by evakichi** [comment]
確認しましたので、Closeします。
