### ISSUE TITLE
貸し出し画面で存在しない利用者番号を入力すると警告メッセージにtranslation missingがでる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1475]
1.3系にて標記のとおりの現象が発生します。
![image](https://user-images.githubusercontent.com/38825/60955449-d268eb00-a33b-11e9-95fa-82e7683c2785.png)

**Comment by nabeta** [comment]
エラーメッセージは rails-i18 gem のものをデフォルトで使うようにしました。
https://github.com/svenfuchs/rails-i18n

Gemfileに以下の追加が必要です。

```
gem 'rails-i18n'
```

**Comment by nabeta** [comment]
日付と時刻の表記について、「年・月」のみのフォーマットがrails-i18nにないため、
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml#L201-L206

enju_leaf側で定義している。
https://github.com/next-l/enju_leaf/blob/master/config/locales/ja.yml#L4

**Comment by masao** [comment]
おそらく、Update手順にも修正が必要と思います。

**Comment by masao** [comment]
標記のエラーが出なくなったことを確認しました。ひとまずクローズします。
![image](https://user-images.githubusercontent.com/38825/62750893-9fca2380-ba9c-11e9-89a7-636019bd0ad2.png)

**Comment by yegusa** [comment]
参考

上のコメントは、利用者を入力してくださいが出てますね。

今、デモサイトでやって見たら、ちゃんと利用者は一回でしたね。

![スクリーンショット 2020-02-16 17 27 10](https://user-images.githubusercontent.com/1328499/74601419-9d96f080-50e1-11ea-87db-f293b3147a2d.png)
