### ISSUE TITLE
書誌と所蔵にカスタム項目を追加する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1476]
管理用途として図書館員が書誌と所蔵に任意の項目とその値を入力できるような、カスタム項目を追加する。

- それぞれ5個程度を想定
- 項目ラベルは設定可能
- 入力した項目はすべてLibrarian権限のみ参照可能
- TSVでのインポートをサポートする
    - 項目名はmanifestation_custom1, item_custom1...

**Comment by yegusa** [comment]
これは，最優先でやること！

**Comment by nabeta** [comment]
現在は入力とエクスポートができる状態で、インポートがまだです。

TSVでのエクスポートは以下のような仕様です。

- ヘッダ: 書誌のカスタム項目は`manifestation_custom_property_{n}`, 所蔵のカスタム項目は`item_custom_property_{n}`
- データ本体: "項目名: 値"のフォーマット

|manifestation_custom_property_1|manifestation_custom_property_2|item_custom_property_1|
|---|---|---|
|対象1: 小学生|対象2: 中学生|電子化予定: 2020年度|

**Comment by nabeta** [comment]
デモサーバに反映させました。
https://enju.next-l.jp/manifestations/12887

![image](https://user-images.githubusercontent.com/11428/71541029-22914380-2996-11ea-9f49-65a991674fe8.png)

![image](https://user-images.githubusercontent.com/11428/71541023-173e1800-2996-11ea-90fc-6f63a596a45b.png)

**Comment by masao** [comment]
キャッシュにより、更新が反映されないバグあり。

**Comment by masao** [comment]
なお、カスタム項目は、一度設定メニューから設定するかたちで使用し、設定した項目名称を個別の編集画面で入力しなおす必要はないようにした方が良いと思います。

**Comment by nabeta** [comment]
カスタム項目のラベルはシステム全体で設定し、変更したらすでに設定された項目のラベルも追随して変更される必要がある。現状の実装では、項目のラベルも書誌・所蔵ごとに設定できるようになっているが、これは期待された実装ではない。

**Comment by nabeta** [comment]
項目名をシステム全体で共通にしました。以下の画面で設定します。
https://dev.next-l.jp/manifestation_custom_properties

入力例は以下になります。
https://dev.next-l.jp/manifestations/24467

**Comment by nabeta** [comment]
4月26日のワークショップで以下を確認。

- UIや動作としてはOK
- 入力された値は検索対象にしない（データ移行のための保存項目という前提のため）

残りはテストの記述、TSVファイルへのエクスポート、1.3系への反映。

**Comment by nabeta** [comment]
以下のコミットで、書誌・所蔵のカスタム項目のインポートを行えるようにしました。
https://github.com/next-l/enju_biblio/commit/e85ba6387120c39f1121ed9fe8b0fd0002920d56

テストは以下になります。
https://github.com/next-l/enju_biblio/blob/e85ba6387120c39f1121ed9fe8b0fd0002920d56/spec/models/resource_import_file_spec.rb#L159

**Comment by nabeta** [comment]
以下のコミットで、カスタム項目のインポートを1.3系に追加しました。
https://github.com/next-l/enju_biblio/commit/2c877115f9a46f7a6c7730e41e9e829407383f24

**Comment by masao** [comment]
カスタム項目の設定画面の表示が崩れているようです。
![image](https://user-images.githubusercontent.com/38825/82137033-17f51f00-984f-11ea-86e3-ae3a0a94fa18.png)

**Comment by nabeta** [comment]
以下のコミットで修正しています。
https://github.com/next-l/enju_biblio/commit/13471584b4d3584a0bd760ca2e6c12daf895f6ac

![image](https://user-images.githubusercontent.com/11428/82345153-e2f3f280-9a2f-11ea-8abb-d57bb7175ced.png)

**Comment by masao** [comment]
ひとまず機能的には完成しているようですので、クローズします。

**Comment by yegusa** [comment]
マニュアルは 初期設定マニュアルに 6-2 を 新設して追加する感じで移いこうと思います。
