### ISSUE TITLE
「利用制限」が「貸出不可」の場合のみ検索結果一覧で表示する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1478]
- [ ] mdマニュアルを修正する

**貸出不可**（禁帯出）の場合のみ，このこの緑の部分を，二行にして

在架（利用可能）
貸出不可

と表示するように，Enju 本体の修正をする

![image](https://user-images.githubusercontent.com/1328499/62009494-cc2b9900-b19a-11e9-880a-80f69107ec36.png)

**Comment by nabeta** [comment]
以下のように表示されるようにしました。
https://enju.next-l.jp/manifestations/12835
![image](https://user-images.githubusercontent.com/11428/62834263-bc28b480-bc84-11e9-812a-6097028cd382.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。

**Comment by yegusa** [comment]
作業中
貸出不可

の場合は表示されましたが、

在架（利用可能）
貸出不可

が表示されませんでした。

のでリオープンします。

例：
![image](https://user-images.githubusercontent.com/1328499/156871506-83fd23c7-44d8-4981-9014-f811fdca5158.png)

**Comment by nabeta** [comment]
@yegusa ログインしているのユーザの権限を教えてください。

**Comment by yegusa** [comment]
enjuadminです

**Comment by yegusa** [comment]
デモサーバーで確認しました。

出力されることを確認しましたのでクローズします。

![image](https://user-images.githubusercontent.com/1328499/157348223-69902038-7ed2-4f31-a328-c62a86ccc7e6.png)
