### ISSUE TITLE
カスタム識別子を検索できるようにする

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1479]
以下のPull requestに対応するissue。
https://github.com/next-l/enju_biblio/pull/5

**Comment by masao** [comment]
先ほど pr のほうにも書きましたが、 text ではなく、 string にしませんか。
また、Update手順に reindex が必要ですので、追加しておいていただけますか。
それ以外はOKと思います。

**Comment by nabeta** [comment]
textにしないと、そのままフォームに値を入れても検索にヒットしなかった気がします。

**Comment by masao** [comment]
ヒットするようになったことを確認しました。クローズします。

**Comment by yegusa** [comment]
たとえば、NCID の　BB15702181　で検索したら出てくるというイメージ。

カスタム識別子は、以下で登録できる

識別子の種類の一覧
https://enju.next-l.jp/identifier_types

マニュアルの関連部分：
https://next-l.github.io/manual/1.3/enju_setup_6.html
