### ISSUE TITLE
リリース前のパッケージを使用している場合に「システムの基本的な情報の表示」でコミットのハッシュを表示

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1480]
以下のPull requestに対応するissue。
https://github.com/next-l/enju_leaf/pull/1465

**Comment by masao** [comment]
修正を確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/63219228-2d49f980-c1a8-11e9-9930-7444654be25d.png)

**Comment by yegusa** [comment]
マニュアル修正については、
https://next-l.github.io/manual/1.3/enju_setup_7.html#section7-1 の図
https://next-l.github.io/manual/assets/images/1.1/image_initial_systemdisp03.png

を修正する。

図は、上のコメントのを使えば良いだろう。
