### ISSUE TITLE
JavaScriptのインストールにyarnを使用する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1483]
最近のRailsで使用しているJavaScriptのパッケージ管理ツール。
https://yarnpkg.com/lang/ja/

現在jQueryなどのJavaScriptはgemでインストールしているが、順次こちらに切り替える。

**Comment by nabeta** [comment]
Ubuntuでは以下の手順でyarnをインストールする。

```
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
$ sudo apt update
$ sudo apt install yarn
```

また、1.3から2.0へのアップデート時には、以下の手順でJavaScriptのライブラリをインストールする必要がある。

```
$ cd /path/to/enju
$ yarn add jquery-migrate jquery-colorbox jquery-powertip
$ yarn install
```

新規インストール時にはテンプレートの以下の部分で、``rails new``の際に実行される。
https://gist.github.com/nabeta/7effc916c91549e3c5a518960df4bd0e#file-enju_leaf_20_template-rb-L23

**Comment by nabeta** [comment]
jquery-powertipが古いバージョンのjQuery UIと互換性のないjQuery 3.4をインストールするため、2.0系ではjQueryはjquery-railsパッケージのものを使用している。

**Comment by masao** [comment]
更新手順の文書には上記の手順が見当たらないのですが、不要でしょうか? 
https://github.com/next-l/enju_leaf/wiki/Update OR 
https://github.com/next-l/enju_leaf/wiki/Update-to-1.3

**Comment by nabeta** [comment]
2.0系でBootstrapを使用する際には必要となりますが、1.3系では不要です。

**Comment by nabeta** [comment]
1.4系でMiradorをインストールする際に、yarnの実行を必要とします。Dockerコンテナを使用する場合は、 `docker compose build` を実行する際にコンテナ内で実行されるので、別途インストールと実行を行う必要はありません。
https://github.com/next-l/enju_leaf/blob/main/Dockerfile#L10

なお、開発者向けのインストールには以下のように記載しています。
https://github.com/next-l/enju_leaf/wiki/DevelopmentInstall

```sh
# yarnを実行
$ yarn install

# development環境の場合は不要
$ bundle exec rake assets:precompile
```

**Comment by nabeta** [comment]
Dockerでのインストールが標準になっているため、クローズします。
