### ISSUE TITLE
返却期限日の表示が変

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1484]
#1475 からの派生。
おそらく、日付書式の再定義が必要。
![AwesomeScreenshot-localhost-manifestations-2019-08-18_11_47](https://user-images.githubusercontent.com/38825/63219500-0db5cf80-c1ae-11e9-8817-495bedf246ab.png)

**Comment by nabeta** [comment]
このフォーマットは少なくともenju_leaf-1.2.0時点から変わっていません。
https://github.com/next-l/enju_leaf/blob/1.2/config/locales/ja.yml#L193

時刻まで表示する必要はないと思いますので、日付のみの表示にすることにします。

**Comment by nabeta** [comment]
日付のみを表示するように修正しました。
![image](https://user-images.githubusercontent.com/11428/63221480-6304d780-c1d4-11e9-82d5-095e92e5197f.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
