### ISSUE TITLE
translation missing: ja.activerecord.errors.template.body

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1488]
標記のエラーが発生します。
おそらく #1475 からの派生。

![image](https://user-images.githubusercontent.com/38825/63220586-000c4400-c1c6-11e9-9aed-0e6a17972b03.png)

**Comment by nabeta** [comment]
修正済みです。なお、この問題は1.3ブランチのみに存在します。
![image](https://user-images.githubusercontent.com/11428/63221440-f12c8e00-c1d3-11e9-8798-bb5b6daf035e.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
