### ISSUE TITLE
地図表示にOpenStreetMapを使用する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1494]
以下のライブラリが使えそう。
https://github.com/axyjo/leaflet-rails

**Comment by nabeta** [comment]
以下のコミットで、地図の表示にOSMを使用するようにしました。masterと2.x系には反映していますが、1.3系はどうしましょうかね。
https://github.com/next-l/enju_library/commit/70b58917ed0e0f7ce38ecfe969251d31f6ccc511

**Comment by masao** [comment]
1.3系にも反映しましょう。

**Comment by nabeta** [comment]
では、Google MapsでのHTTPSの使用 #1460 はcloseします。

**Comment by nabeta** [comment]
1.3系に反映したのですが、以下のように地図が小さく表示されてしまいます。
https://enju.next-l.jp/libraries/tachibana

![image](https://user-images.githubusercontent.com/11428/80273376-7295d200-870c-11ea-8b90-f883815255e3.png)

masterブランチでは以下のように正しく表示されます。なにかCSSが悪さをしているのかもしれません。
https://enju.next-l.jp/libraries/tachibana

![image](https://user-images.githubusercontent.com/11428/80273401-a4a73400-870c-11ea-8e3a-7a57a43d9a1e.png)

**Comment by nabeta** [comment]
類似の事例があり、invalidateSizeメソッドを呼ぶことで、地図全体が表示されない問題は回避できた。
https://teratail.com/questions/170453

マーカーとポップアップがずれている件と関係がありそうに見えますが、ひとまずOSMへの移行自体は完了したものとします。

![image](https://user-images.githubusercontent.com/11428/80579228-a2164880-8a44-11ea-9cc1-dfad47106791.png)

**Comment by masao** [comment]
こちら住所を入れても有効になりませんが、何か設定が必要ですか? 
![image](https://user-images.githubusercontent.com/38825/82138732-a375ac80-985d-11ea-9966-7873c1c40b06.png)

**Comment by nabeta** [comment]
geocodingの機能に問題があるようですね。ちょっと見てみます。

**Comment by nabeta** [comment]
対応策として、緯度・経度を手動で入力するフォームを追加しました。
https://enju.next-l.jp/libraries/tachibana/edit

![image](https://user-images.githubusercontent.com/11428/82323566-360b7c80-9a13-11ea-95a5-636b032498ea.png)

**Comment by masao** [comment]
ポップアップがずれているのは気になりますが、ひとまずOSMへの移行そのものは問題ないことにしましょう。クローズします。
![image](https://user-images.githubusercontent.com/38825/87868129-0d314480-c9ce-11ea-908f-4faa66d15576.png)

**Comment by yegusa** [comment]
OpenStreetMapとは言及しなかったが、Googleマップの削除と緯度経度について追加。
