### ISSUE TITLE
マニュアル内の各サイトのURLをhttpsに更新する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1495]
www.next-l.jp, iss.ndl.go.jp, ci.nii.ac.jpなど。

**Comment by nabeta** [comment]
以下のコミットで実施済みです。
https://github.com/next-l/manual/commit/e4f01d48dc40215d205fce7c2847de92af504bed

**Comment by masao** [comment]
確認しました（一部をさらに追記済みです）。 ひとまずクローズします。
