### ISSUE TITLE
特に改行のエスケープについて：TSV出力方法の変更によるマニュアル修正

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1501]
- [x] mdマニュアルの修正必要 #1506

1.3.4.rc.1では、TSV出力にRubyのCSVライブラリの ``Array#to_csv``を使用するように変更している。
https://github.com/next-l/enju_biblio/blob/1.3/app/models/manifestation.rb#L644

このため、TSVのエスケープ方法に変更が生じている。これをマニュアルに追記すること。

**Comment by yegusa** [comment]
改行が以前は、 \n にされていたのが、されなくなったのが大きな変更点である旨をマニュアルに書きますね。

**Comment by yegusa** [comment]
修正したのでクローズします。

**Comment by yegusa** [comment]
関連して、これ、インポートも同様ですよね？
