### ISSUE TITLE
検索結果の書き出しメニューへのJSON形式の追加

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1502]
#1451 からの派生。せっかくなので、「書き出し」メニューのところにリンクを追加するとよいように思います。
![image](https://user-images.githubusercontent.com/38825/72200699-df53cc00-348f-11ea-8c2f-f4619c707d41.png)

**Comment by nabeta** [comment]
以下のように追加しました。
https://dev.next-l.jp/manifestations?query=&commit=検索

<img width="200" alt="スクリーンショット 2020-05-06 4 57 24" src="https://user-images.githubusercontent.com/11428/81110189-2c374300-8f56-11ea-8110-bff4f97adcc0.png">

**Comment by masao** [comment]
うーん、見当たりません。
![image](https://user-images.githubusercontent.com/38825/82137191-c8afee00-9850-11ea-8414-28e01f825aab.png)

**Comment by nabeta** [comment]
1.3系に追加しました。
https://enju.next-l.jp/manifestations/12887

**Comment by masao** [comment]
確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/87867987-f4745f00-c9cc-11ea-8e77-6c9811b4ff33.png)

**Comment by yegusa** [comment]
マニュアルは

https://next-l.github.io/manual/1.3/enju_user_1.html#section1-8-3

これの後ろに 1-8-4 として追加するとよさそう
