### ISSUE TITLE
マニュアル修正：資料検索の結果表示項目のカスタマイズについて

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1504]
- [x] マニュアルを修正する #1445 （インストールの10章あたりに）

資料検索の結果表示項目のカスタマイズについて #1435 のマニュアルを修正する。

@masao さんよろしく。

**Comment by masao** [comment]
https://next-l.github.io/manual/1.3/enju_install_vm_10.html#section10-5 に追加しました。

**Comment by yegusa** [comment]
確認しましたのでクローズします。
