### ISSUE TITLE
購入リクエストの一覧がエラーになる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1505]
1.3系の先端にて、購入リクエスト機能をテストしようとすると、Railsエラーになります:
```
undefined method `get_order_list' for #<PurchaseRequestsController:0x00007fdc9101f340> Did you mean? get_version
```
![image](https://user-images.githubusercontent.com/38825/74599933-425b0300-50cd-11ea-8c97-844deddbfeae.png)

**Comment by nabeta** [comment]
app/controllers/application_controller.rb に以下の行は追加されていますでしょうか。

```ruby
  include EnjuCirculation::Controller
  include EnjuPurchaseRequest:Controller # この行
  after_action :verify_authorized
```

**Comment by masao** [comment]
おっと、この情報見落としてました。
https://next-l.github.io/manual/1.3/enju_install_vm_5.html#section5-4 にある手順ですね。。。

クローズします。
