### ISSUE TITLE
発注リストの新規作成でエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1507]
#926 の確認中に発生しました。

発注リストの新規作成画面へ遷移するとエラーになります。
http://localhost:3000/order_lists/new

![image](https://user-images.githubusercontent.com/38825/77243901-899b5d00-6c52-11ea-848c-0641e73c0880.png)

**Comment by nabeta** [comment]
1.3ブランチで修正済みです。

**Comment by masao** [comment]
修正を確認しました。クローズします。
