### ISSUE TITLE
画面遷移の不具合（Debian）

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1511]
本番の蔵書管理システムをRaspberry Pi 4で構築する計画です。まずはVirtualBox上にRaspbian OSをインストールした Debian 10.3 の環境に、[インストール / How to install Next-L Enju Leaf](https://github.com/next-l/enju_leaf/wiki/Install)に従ってEnju Leaf 1.3.3.1をインストールしました。

無事起動できたのですが、ISBNインポートのリクエストの新規作成（/import_requests/new）でISBNを入力すると、次の画面（/import_requests）でエラーメッセージ（We're sorry, but something went wrong. If you are the application owner check the logs for more information.）が表示されます。

回避方法がお分かりになりましたらご教示ください。よろしくお願いいたします。

**Comment by miyatatk** [comment]
自己レスです。

資料の受入を「TSVファイルからのインポート」で行ったところ、以下のエラーメッセージが出ました。

`SSL_connect returned=1 errno=0 state=error: dh key too small`

これを調べてみたところ、[OpenSSLのセキュリティレベルの変更](http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-list/50812)のように、Debianのバージョンが9 (Stretch)から10 (Buster) に上がった際に、 OpenSSL のデフォルトのセキュリティレベルが上がったことが原因で、サイトによってはSSLエラーを起こすことがわかりました。

以下のとおり、/etc/ssl/openssl.cnf の

`[system_default_sect]`
`MinProtocol = TLSv1.2`
`CipherString = DEFAULT@SECLEVEL=2`

を、

`[system_default_sect]`
`MinProtocol = None`
`CipherString = DEFAULT`

と書き換えることで、エラーは発生しなくなりました。お騒がせしました。

**Comment by nabeta** [comment]
@miyatatk お知らせありがとうございました。NDLサーチではTLSのバージョンの記述がないのですが、TLS1.2自体には対応しているようなので、
https://iss.ndl.go.jp/information/2020/03/03_api/

以下の行の変更だけでよいかもしれません。こちらでも環境を作って試してみます。

```
CipherString = DEFAULT
```

curlでの確認結果は以下です。

```
$ curl --tlsv1.2 https://iss.ndl.go.jp
（中略）
<div id="footer" class="footer">
<p class="guidance"><img alt="以下、フッターです" height="1" src="/images/ndl/spacer.png?1515071548" width="1" /></p>
<ul>
<li id="home"><a href="https://www.ndl.go.jp/">国立国会図書館ホーム</a></li>
<li><a href="https://ndlonline.ndl.go.jp/">国立国会図書館オンライン</a></li>
<li><a href="/children/top">国際子ども図書館 子どもOPAC</a></li>
<li><a href="https://id.ndl.go.jp/auth/ndla" title="国立国会図書館典拠データ検索・提供サービス">Web NDL Authorities</a></li>

<li><a href="https://iss.ndl.go.jp/information/outline/">国立国会図書館サーチについて</a></li>
<li><a href="https://www.ndl.go.jp/jp/service/contact/index.html">お問い合わせ</a></li>
</ul>
<p class="guidance"><a href="#header">ページトップに戻る</a></p>
</div>

<address>Copyright &copy; 2012 National Diet Library. All Rights Reserved.</address>
<p class="guidance"><img alt="フッター　ここまで" height="1" src="/images/ndl/spacer.png?1515071548" width="1" /></p>



</body>
</html>
```

**Comment by miyatatk** [comment]
@nabeta お返事ありがとうございました。当方の環境で

`CipherString = DEFAULT`

とだけ変更したところ、TLSv1.2のままでも、ISBN入力、NDLサーチ検索、CiNii Books検索、米国議会図書館検索、TSVファイルからのインポートのいずれでもエラーは発生しなくなりました。
