### ISSUE TITLE
代理ログイン機能が欲しい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1515]
Admin限定でよいので、一般ユーザになりきって操作ができる、任意の一般ユーザにログインしなおせる機能があると、テストがだいぶ楽になります。いまは個別のアカウントのパスワード再発行をしてはログインしなおしてを繰り返しているので、一般ユーザ権限のテストをするのに4～6ステップくらいかけていて煩雑で疲れる。。。

**Comment by nabeta** [comment]
ログイン用のライブラリにdeviseを使用しているのですが、他のユーザにスイッチする方法が以下にまとめられています。これを参考に機能を追加すればよさそうです。
https://github.com/heartcombo/devise/wiki/How-To:-Sign-in-as-another-user-if-you-are-an-admin
