### ISSUE TITLE
書誌のエクスポートTSVに著者の役割が出力されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1516]
https://github.com/next-l/enju_biblio/blob/master/examples/resource_import_file_sample1.tsv

``test||author//test1||illustrator``の``author``や``illustrator``の部分が出力されない。

**Comment by nabeta** [comment]
以下のコミットで修正済み。1.3系にも反映している。
https://github.com/next-l/enju_biblio/commit/056f53c11504b0d53171ac8a0431ee49b32fc8cd

**Comment by masao** [comment]
確認しました。ひとまずクローズします。

**Comment by yegusa** [comment]
一括インポート、エクスポートできるが、
書誌の詳細などで表示されない・編集できないので注意。

**Comment by yegusa** [comment]
マニュアルに書くこと：
「著者の関係の一覧」で設定された項目が指定できる。
新しく、設定したい場合は、その画面で追加などする。

「著者の関係の一覧」
https://enju.next-l.jp/create_types

**Comment by yegusa** [comment]
https://github.com/next-l/enju_biblio/blob/1.3/examples/resource_import_file_sample1.tsv

creator 列の値の
test||author//test1||illustrator
とかね。

**Comment by yegusa** [comment]
マニュアルインポートの形式
https://next-l.github.io/manual/1.3/enju_operation_4.html#tsv_creator

**Comment by yegusa** [comment]
マニュアル　エクスポートの形式
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export
