### ISSUE TITLE
favicon.ico の設定

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1518]
独自のロゴ、アイコン等を作ってEnjuに設定しています。

`apple-touch-icon.png` は `public` ディレクトリの下に置いて問題なく動作しました。一方、 `favicon.ico` は `public` ディレクトリの下に置いても、これまでと同様に Enjuのデフォルトのfaviconが出ます。

どのように設定すればよいでしょうか。ご教示ください。

**Comment by nabeta** [comment]
@miyatatk favicon.icoもpublicディレクトリに直接保存することで、置き換えることができます。

<img width="386" alt="スクリーンショット 2020-05-30 20 33 40" src="https://user-images.githubusercontent.com/11428/83327170-e3ed1580-a2b4-11ea-8d1b-cf7b451cd5b4.png">

おそらく、faviconのキャッシュを更新する必要がありそうです。Macでの例が以下の記事にありますが、他のOSでも同様だと思われます。
https://qiita.com/qoAop/items/5b76bb09e4cab83dbc87

**Comment by miyatatk** [comment]
@nabeta お返事ありがとうございます。Firefoxを使っており、Faviconのキャッシュも削除したのですが、相変わらずデフォルトのFaviconが表示されています。
でも、場所はpublicディレクトリで正しかったのですね。安心しました。しばらく様子を見てみます。

**Comment by nabeta** [comment]
本件、まだ同様の問題が出ていましたらお知らせください。

**Comment by miyatatk** [comment]
@nabeta ご配慮ありがとうございます。このところ多忙で離れていましたが、また皆さんの議論についていきます。
Firefox使用時、タブの左側のFaviconが表示されていますが、ブックマークに登録しても地球マークのままです。
Edgeでは問題なくお気に入りにFaviconが表示されています。
