### ISSUE TITLE
Enju公式ページの内容を更新する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1519]
https://next-l.jp/?page=Next%2DL+Enju 

特に、バージョン情報とアイコン。

**Comment by nabeta** [comment]
ひとまず、バージョン情報の更新とURLのhttpsへの変更を行いました。

**Comment by nabeta** [comment]
ロゴは現行のもの（Enjuくん）に差し替えました。バージョン情報も1.3.6としています。
https://www.next-l.jp/?page=Next%2DL+Enju

その他の古い項目の更新は #902 で扱うこととして、こちらはクローズします。
