### ISSUE TITLE
カスタム項目の編集欄の表示修正

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1521]
#1476 の派生。
カスタム項目が複数ある場合に、表示欄が改行で区切られていないため、表示が崩れたような形になっています。

![image](https://user-images.githubusercontent.com/38825/87868569-20deaa00-c9d2-11ea-9ced-9be636b1127d.png)

**Comment by nabeta** [comment]
以下のように修正しました。

![image](https://user-images.githubusercontent.com/11428/180770335-5b124a1c-5aa2-4d00-bc55-ed078d91e330.png)

**Comment by nabeta** [comment]
1.4.0で修正済みのため、クローズします。
