### ISSUE TITLE
2.0系起動時にエラー: undefined method `stylesheet_pack_tag’

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1525]
初期起動で http://localhost:3000 にアクセスした際に以下のエラーが出ます:
```
undefined method `stylesheet_pack_tag' for #<#<Class:0x00007f52b095f768>:0x00007f52b80a2dc0>
```

![image](https://user-images.githubusercontent.com/38825/90972304-d90fed00-e552-11ea-9682-87c7e7d29ed7.png)

**Comment by nabeta** [comment]
2.0系の開発とリリースは仕切り直しとするため、クローズします。
