### ISSUE TITLE
要確認: SRUでの個別フィールドの権限対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1532]
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export にある要参照権限項目が出力されていないか、要チェック。

**Comment by nabeta** [comment]
これは以下のPRで、SRUインターフェース自体を削除しました。
https://github.com/next-l/enju_biblio/pull/13

**Comment by masao** [comment]
機能除去にて対応したことを確認しました。クローズします。
