### ISSUE TITLE
要確認：items 出力における個別フィールドの要参照権限項目

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1537]
https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export にある要参照権限項目が出力されているようなので、要対応。

**Comment by nabeta** [comment]
明示的に以下の項目のみを出力するようにしました。
https://github.com/next-l/enju_biblio/commit/ff9577bd415768583eea8479a0aa9a2905a382ea

- id
- item_identifier
- call_number
- item_note
- acquired_at
- circulation_status
- shelf
- created_at
- updated_at

デモサーバには反映済みです。
https://enju.next-l.jp/items.json
https://enju.next-l.jp/items/7450.json

**Comment by masao** [comment]
出力内容が限定されていることを確認しました。クローズします。
