### ISSUE TITLE
OAI-PMHインターフェースでresumptionTokenが表示されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1538]
ListIdentifiersやListRecordsを実行しても、resumptionTokenが空になる。以下はデモサーバの例で、1万件以上書誌があり、デフォルトでは500件ずつの取得になるのでresumptionTokenが表示されるはずだが、実際にはされていない。
https://enju.next-l.jp/oai/provider.xml?verb=ListIdentifiers&metadataPrefix=oai_dc
![image](https://user-images.githubusercontent.com/11428/109397097-5d1ab580-7978-11eb-8157-65f4768ad199.png)

**Comment by nabeta** [comment]
@masao こちら、resumptionTokenが表示されるように修正しました。

**Comment by yegusa** [comment]
resumptionTokenが表示されるようになっているようですのでクローズします。

https://enju.next-l.jp/oai/provider.xml?verb=ListIdentifiers&metadataPrefix=oai_dc
```
<header>
<identifier>oai:localhost:manifestations-1</identifier>
<datestamp>2021-11-23T08:01:21Z</datestamp>
<setSpec>1</setSpec>
</header>
<resumptionToken completeListSize="88">AoJ4hon0pf0CL01hbmlmZXN0YXRpb24gMQ%3D%3D</resumptionToken>
</ListIdentifiers>
</OAI-PMH>
```
