### ISSUE TITLE
フッターの「不具合を報告する」のリンク先をDiscussionsに変更する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1541]
GitHubにDiscussionsという機能が追加され、Next-Lでも有効にした。
https://github.com/next-l/enju_leaf/discussions

現時点では、Enjuのフッターには「不具合を報告する」というラベルでIssuesへのリンクが設定されているが、利用者の問い合わせの対応にはDiscussionsが適していると思われるので、このリンクをDiscussionsに変更するのがよいのではないか。
ラベルも「質問する」に変えたようがよいかもしれない。

**Comment by masao** [comment]
リンク先を切り替えるのは賛成です。
ただラベルはちょっとそのままでも良いかもしれません。運用している図書館宛の質問が来ないような文言を考えないといけない気がします。

**Comment by nabeta** [comment]
ひとまずリンク先だけ変更しました。2.x系に含めています。
https://github.com/next-l/enju_library/commit/e6b6845d314b430dbaab34621c7ad7c62f1bf0ca
