### ISSUE TITLE
【質問】書誌登録できる Web API はありませんか？

### ISSUE THREAD

**Issue by mnaruse** [next-l/enju_leaf#1549]
Next-L Enju Web APIマニュアル(バージョン1.3) (https://next-l.github.io/manual/1.3/enju_webapi.html) を拝見しました。
すでに登録済みの書誌情報を取得する API があることは確認できたのですが、
新しい書誌を登録するための API は確認できませんでした。
新しい書誌を登録するための API はまだ存在しないのでしょうか。

すでに開発済み、あるいは開発中であれば、詳細を教えていただけませんでしょうか。
一方、未開発、開発の予定なしであれば、代替方法として何が考えられるか、アドバイスいただけると、大変ありがたく存じます。
ちなみに今のところ、代替方法としては、ブラウザ自動操作ツールである「Selenium」が使えるかもしれないねと友人と話しています。

**Comment by masao** [comment]
今のところ、書誌情報登録用のAPIは無いですね。まとまったデータを一括して登録するためのやり方には、TSV（タブ区切りテキスト）形式での一括インポートによる登録をお勧めしています。
https://next-l.github.io/manual/1.3/enju_operation_4.html#section4-2

**Comment by mnaruse** [comment]
早速ご回答ありがとうございます！
承知いたしました。おすすめ方法のご提示もありがとうございます。
おすすめの方法をみてみます。

解決済みとしてクローズいたします。
