### ISSUE TITLE
Ubuntu へのインストール

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1553]
@nabeta さん、お久しぶりです。新しいUbuntu Server (20.04.2 LTS) にEnjuをインストールしています。

[Install](https://github.com/next-l/enju_leaf/wiki/Install) に従って進んだところ、[Railsのインストール](https://github.com/next-l/enju_leaf/wiki/Install#rails%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB) で躓いています。この前段までは順調にインストールできました。
```
$ sudo gem install rails -v 5.2.4
ERROR:  Could not find a valid gem 'rails' (= 5.2.4), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)
```
とエラーが出力され、railsがインストールできません。5.2.x シリーズ最新の 5.2.5 でも同じ結果になります。
お分かりになりましたらご教示ください。

（この機会に Install というラベルを作ってくださればありがたいです。）

**Comment by nabeta** [comment]
@miyatatk こちらで試したところ、特に問題なくインストールできました。rubygems.org側の問題と思われますので、もう一度試してみてください。

**Comment by miyatatk** [comment]
@nabeta さん、お返事ありがとうございます。何度やっても駄目です。
`$ ping rubygems.org` や `$ ping www.google.co.jp` で反応しないので、名前解決の問題かと思いました。
しかし、`$ curl -sS https://www.google.co.jp` では正しく読みに行っていますので、名前解決はできています。
ネームサーバーは `/etc/netplan/99-cloud-init.yaml` に設定しています。

[rubygem が反応しなくなったら](http://jimiprg.blog.shinobi.jp/ruby/rubygem%20%E3%81%8C%E5%8F%8D%E5%BF%9C%E3%81%97%E3%81%AA%E3%81%8F%E3%81%AA%E3%81%A3%E3%81%9F%E3%82%89)
ここに書いてあることも一通り試しましたが、改善しませんでした。
原因がわからないため Ubuntu Server 20.04.2 LTS はいったんやめて、Raspberry Pi OS にインストールしてみます。

**Comment by miyatatk** [comment]
Raspberry Pi OS では問題なく動きました。

**Comment by nabeta** [comment]
Enju本体の問題ではなさそうですので、クローズします。
