### ISSUE TITLE
所蔵情報IDの文字制限を緩和したい

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1559]
@nabeta 所蔵情報ID (item_identifier) には半角の数値とアルファベットのみが入力できることになっていますが、長いIDは読みにくいため、ハイフンなどの記号を入れられるようにしたいと思います。

例: 123-456-7890、a123.45.67 など

どのソースコードを書き換えれば文字制限を緩和できますか？

**Comment by nabeta** [comment]
@miyatatk ``Item#item_identifier``のバリデーションを修正することになります。以下の部分で定義しています。
https://github.com/next-l/enju_biblio/blob/1.3/app/models/item.rb#L30-L31

**Comment by miyatatk** [comment]
@nabeta ありがとうございました。正しいやり方かどうかわかりませんが、
```
~/enju_leaf_13/vendor/bundle/ruby/2.5.0/gems/enju_biblio-0.3.12/app/models/item.rb
```
を直接編集しました。

所蔵情報IDの命名規則を正規表現で指定し、Enjuを再起動したところ、問題なく動きました。

**Comment by nabeta** [comment]
この方法でも動作しますが、gemがアップデートされると再度変更が必要になるので、 ``~/enju_leaf_13/app/models/item.rb``に移動することをおすすめします。

なお、カスタマイズの方法については、現状のようにそもそもgemの中身を修正するのは少し手間がかかるため、別の方法を検討しています。

**Comment by miyatatk** [comment]
@nabeta ありがとうございます。

`item.rb`を`~/enju_leaf_13/app/models/`に移動して、正しく動作していることを確認できました。

それにしても、`~/enju_leaf_13/vendor/bundle/`配下にファイルがあっても、`~/enju_leaf_13/`直下の`app`等が優先されるのですね。このような基礎知識が不十分だったため、勉強になりました。
