### ISSUE TITLE
提案：表の表示内容にもっと改善の余地あり（利用者インポートの結果の一覧）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#156]
バグ？：表の表示内容にもっと改善の余地あり（利用者インポートの結果の一覧）

利用者インポートの結果の一覧
http://xxxxxxxxxx/user_import_files/(n)/user_import_results

![issue_user_import_result2](https://cloud.githubusercontent.com/assets/1328499/3235508/5aaf4dd6-f0d3-11e3-9481-f755e66f2124.png)

この表の意味がよくわかりません。
TSVインポートしたファイルの各行を表しているようですが。。。
とくに一列目は全部同じ表現になっていますし。

TSVインポートしたファイルの各行を表すのであれば、
例えば、以下のようにしたらどうでしょうか？

![image](https://cloud.githubusercontent.com/assets/1328499/3235569/27aa88be-f0d4-11e3-9c07-f9c4341e6f59.png)

**Comment by masao** [comment]
提案のように修正を加えました。行数表示はDB保存していないので、仮表示ですが。。。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10118705/28d0182a-64ba-11e5-9b62-0980606c3e28.png)

**Comment by yegusa** [comment]
> 行数表示はDB保存していないので、仮表示ですが。。。

ひょっとしたらずれるかも？ってことですよね。
とりあえず、この例ではずれてないようですが。
ま、とりあえず、いいことにしましょうか。

仮想マシンで確認しました。よいと思います。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10118762/6560e728-64bb-11e5-8b0b-a713369db713.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by masao** [comment]
クローズしてしまいましたが、2ページ目に移っても、1～10行目として表示されてしまうバグがあったのを直してあります。念のため。
