### ISSUE TITLE
Enjuの全システム・データのバックアップとリストア、移行について

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1562]
@nabeta いつもお世話になっております。Enjuに初めて出会ってから約1年、Enjuの奥の深さにすっかり魅せられて、少しずつテストを重ね、ようやく専用サーバマシンを購入して本格運用にこぎ着けました。

そこで、お時間のある時に教えてください。Enjuを本格運用する際にデータのバックアップは非常に大切ですが、**バックアップ方法として最も適切というか、Enjuで推奨される方法**がありましたら、このGithubに簡単に**マニュアル化**してまとめていただけると幸いです。同様に、**推奨されるリストアの方法**もご教示ください。

また、**これらの知識は、別のマシンで環境を構築して新たなマシンにデータを移行したり、本格運用を開始したりする場合にも必要**になりますので、同じことかと思いますが、**マニュアル化**していただけると大変ありがたく存じます。

別途Ruby on Railsの本なども読んで勉強していますが、何ぶんにもRails初心者なもので、本格運用をしながらデータを壊してしまうことが最も不安ですので、ご教示いただければありがたく存じます。

お忙しいところ恐縮ですが、これからEnjuにたどり着く方々のためにも、ぜひともよろしくお願いいたします。

**Comment by nabeta** [comment]
バックアップの必要があるのは、データベース（PostgreSQLなど）とアプリケーションのディレクトリ（インストール時にrails newで作成したもの）です。以下にまとめています。  
https://github.com/next-l/enju_leaf/wiki/Backup

**Comment by miyatatk** [comment]
@nabeta ありがとうございます。ここにまとめてありましたか。

これは仮想マシンバージョンのEnjuで、サービスが自動起動しているため、バックアップ前に`stop enju_leaf`コマンドでEnjuを停止できます。

一方、私のようにソースコードからLinuxにインストールした場合には、コマンドラインで`foreman start`とタイプし、稼働中はシェルを開けたままにして、終了時には`Ctrl+C`を押しています。このような運用では、`cron`で定期的にEnjuを停止し、自動的にバックアップを作成するようなことができませんので、下記のようにEnjuをサービス化してみました。

**サービス設定ファイル**
```
# /lib/systemd/system/enju_leaf.service

[Unit]
Description=Next-L Enju Leaf Integrated Library System
After=postgresql.service
After=redis-server.service
After=nginx.service
Documentation=https://www.next-l.jp/

[Service]
Type=simple
User=USER
WorkingDirectory=/home/USER/enju_leaf_13/
ExecStart=/usr/local/bin/foreman start

[Install]
WantedBy=multi-user.target
```
これなら、`systemctl stop enju_leaf`でサービスを止め、バックアップを行い、再び`systemctl restart enju_leaf`でサービスを起動するまでの一連の処理を自動実行できると思います。

ただ、`stop`時にきちんとEnju関係の全ファイルが退避されているか自信がありません。

今のところ動いていますが、もし間違いがあればご教示ください。よろしくお願いいたします。

**Comment by nabeta** [comment]
@miyatatk コメントが遅くなりましてすみません。停止する順序としては、Webサーバ(nginx) -> Enju -> PostgreSQLとするのが安全です。Webサーバを止めて、アクセスがEnjuに来なくなっていることを確認してから、Enjuを停止してください。

**Comment by miyatatk** [comment]
@nabeta ありがとうございます。承知しました。
