### ISSUE TITLE
Enjuを80番ポート、443番ポートで運用できるか

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1563]
@nabeta 再び初心者の質問です。Enjuを[インストール](https://github.com/next-l/enju_leaf/wiki/Install)に従ってインストールすると、Railsは3000番ポートで起動します。そこで、`Procfile`の`-p 3000`を次のように`-p 4000`と書き換えると、4000番で起動するようですが、`-p 80`と書き換えてもEnjuが起動できず、異常終了します。
```
solr: bundle exec rake sunspot:solr:run
resque: bundle exec rake environment resque:work QUEUE=enju_leaf,mailers TERM_CHILD=1
web: bundle exec rails s -p 4000
```
ポート3000番で運用するとアドレスに :3000 がつきますので、通常の80番ポートのHTTPで運用することはできますか。また、それをすると何か不都合がありますでしょうか。

また、別途SSLを挿入する必要があるのかもしれませんが、443番ポートで運用することはできますか。

急ぎませんので、お時間のある時にお教えください。よろしくお願いいたします。

**Comment by nabeta** [comment]
@miyatatk 通常はnginxやApacheをリバースプロキシとして設定します。
https://guides.rubyonrails.org/v5.2/configuring.html#using-a-reverse-proxy

"rails nginx"などで検索すると、設定方法がたくさん出てきますので、参考にしてみてください。

なお、GitHubのDiscussion機能を有効にしましたので、使い方の質問は今後こちらにお寄せください。
https://github.com/next-l/enju_leaf/discussions

**Comment by miyatatk** [comment]
@nabeta 遅くなりましたが、お返事誠にありがとうございます。大変勉強になりました。

サーバに NGINX をインストールし、以下のとおりリバースプロキシの設定を行ったところ、`https://library.example.com/` でEnjuのトップページにアクセスできるようになりました。快適に動作しています。何か問題があればご教示ください。

**NGINXの設定**
```
# /etc/nginx/conf.d/default-ssl.conf

server {
    ssl on;

    listen      443 ssl;
    server_name library.example.com;

    ssl_certificate     /etc/letsencrypt/live/example.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem;

    location / {
        proxy_pass http://library.example.com:3000/;
        proxy_redirect                      off;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-Host   $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
    }
}
```
**Enjuの設定** (SSLを強制)
```
# ~/enju_leaf_13/config/environments/production.rb

  # Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
  config.force_ssl = true
```
