### ISSUE TITLE
識別子を削除しても「資料の表示」画面に反映されない

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1564]
@nabeta  お世話になっております。

「資料の編集」画面で識別子を追加して入力し、「更新する」をクリック。「資料の表示」画面には追加した識別子が表示されます。

しかし、その後「資料の編集」画面で識別子を削除して「更新する」をクリックして、もう一度「資料の表示」画面を見ると、削除したはずの識別子が表示されています。時間を置いてEnjuを再起動しても状況は変わりません。

ちなみにこの識別子は、システムの設定→資料→識別子の種類 で追加した独自のものです。

おそらくバグと思われますので、ご確認をお願いいたします。

**Comment by miyatatk** [comment]
これ、しばらく経って確認したら消えていました。反映には時間がかかるものなのでしょうか。

**Comment by nabeta** [comment]
識別子の削除時に、「資料の表示」画面表示のキャッシュが消えていませんでした。修正済みで、次回のリリースに反映予定です。

**Comment by miyatatk** [comment]
@nabeta ご対応ありがとうございました。

キャッシュが原因とのことですので、たまたま`redis-server`を再起動することがあったため、このタイミングで消えたのかもしれません。

**Comment by nabeta** [comment]
上記、1.3.6リリース時点ではまだ修正されていません。1.4.0では本体で修正予定、1.3系はenju_biblioのアップデートで対応予定です。

**Comment by masao** [comment]
1.4系で修正を確認しました。ひとまずクローズします。
