### ISSUE TITLE
新しい資料の形態を作成したときにアイコンを登録しておかないと表示が崩れる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1565]
アイコン登録が無い物であっても表示上は問題ないようにしておくべきと思います。

![image](https://user-images.githubusercontent.com/38825/121625082-ba60ef80-caad-11eb-92a5-4365ac7a0086.png)

関連: #326

**Comment by nabeta** [comment]
@masao デフォルトのアイコンを設定するのがよいと思いますが、どれにしましょうか。
http://www.famfamfam.com/lab/icons/silk/previews/index_abc.png
