### ISSUE TITLE
「書き出し」リンクがpageパラメータを反映しない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1568]
所属検索の「書き出し」リンクが、pageパラメータを反映していない。
https://enju.next-l.jp/manifestations?page=5&query= を表示しても、リンク先が https://enju.next-l.jp/manifestations.txt?query= になっている。

![image](https://user-images.githubusercontent.com/11428/127732468-70e3ee35-595c-4ee0-ba7c-6d357ec93b5c.png)

**Comment by nabeta** [comment]
以下のコミットで修正しました。
https://github.com/next-l/enju_biblio/commit/ece9a9755a0adac47a104de9bb8a90a59f299e0d

pageパラメータを反映するようになっています。
https://dev.next-l.jp/manifestations?page=2&query=
![image](https://user-images.githubusercontent.com/11428/128622333-284b9b7c-f3d7-4541-9e45-7dffd968428c.png)

**Comment by yegusa** [comment]
デモサーバーで確認しました。

31件～40件の場合

https://enju.next-l.jp/manifestations.json?page=4&query=

page=4が入っていて、結果も、
こんな感じで、ちゃんと該当のものができていることを確認しましたのでクローズします。
(json以外もtsvなどほかも確認した)
