### ISSUE TITLE
提案：「利用者インポートの結果の表示」改善の余地あり

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#157]
#156 にも関連しますが。 #156の[表示]を辿ったさきの画面ですが、
http://xxxxxxxxxxxxxxx/user_import_results/(n)

* 行数を表示してはどうでしょうか？　（例：　　1行目）
* 「本文」　ではなくて、「内容」にしてはどうでしょうか？
* タブだとブラウザ上で表示したときは、なんのこっちゃかわかりにくいので、 せめて　\t に変換してはどうでしょうか？

こんなかんじで→ 内容 username \t email \t role

![issue_user_import_result3](https://cloud.githubusercontent.com/assets/1328499/3235687/2361d586-f0d5-11e3-8819-256ad3fff5f6.png)

**Comment by masao** [comment]
行数を表示するのだけはDB構造を変更する必要があるため、1.1.0以降に持ち越しましょう。
それ以外は変更しました。cf. 5e3d2932d618fbe7f8ce8659bfdb9de21b95bb89

**Comment by yegusa** [comment]
![image](https://cloud.githubusercontent.com/assets/1328499/10118599/3de0dd06-64b7-11e5-89a0-b644bdc00675.png)

* 行数を表示してはどうでしょうか？　（例：　　1行目）  → 1.1.0　より上に持越しということで、別issueをたてます。
* 「本文」　ではなくて、「内容」にしてはどうでしょうか？ → OK
* タブだとブラウザ上で表示したときは、なんのこっちゃかわかりにくいので、 せめて　\t に変換してはどうでしょうか？ → OK

ということで、クローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5e3d293)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)
