### ISSUE TITLE
CiNii Books検索ができない

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1570]
@nabeta お世話になります。

資料の受入 > CiNii Books検索によるインポート の画面が正常に作動しません（以前は動作していました）。以下のエラーが出ます。

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```
`enju_nii: 0.3.1` は正しくインストールされています。「システムの基本的な情報の表示」に表示されます。

解決方法をご教示ください。よろしくお願いいたします。

**Comment by miyatatk** [comment]
@nabeta 自己レスです。
#1511 と同様に、OpenSSLの設定を直したところ、CiNiiで検索できるようになりました。

/etc/ssl/openssl.cnf
```
[system_default_sect]
# CipherString = DEFAULT@SECLEVEL=2
CipherString = DEFAULT
```
前回と異なりNDLサーチではエラーが出ないものの、CiNiiだけでエラーが出るようになり、理由がわかりませんでした。
お騒がせいたしました。

**Comment by nabeta** [comment]
CiNiiもTLS1.2以上を使用するようにとの記述がありますね。
https://support.nii.ac.jp/ja/cinii/cinii_outline

ちなみにOSはなんでしょうか。

**Comment by miyatatk** [comment]
@nabeta ありがとうございます。
OSは **Debian 10.10** です。

**Comment by ryuuji** [comment]
カーリルの吉本です。CiNii BooksのサーバーはDH_KEY_TOO_SMALLエラーが発生します。これはディストリビューションによってOpenSSLの標準設定のセキュリティレベルが上がっているためなので、 @nabeta  さんの対応で問題なさそうです。
ただ、本当はOSデフォルトのセキュリティレベルを下げるのは望ましくないので、アクセス時のSSLコンテキストのCIPHERSに弱いDH鍵の許可を追加するほうがよいのかもしれません。
NII向けのアクセスでいつもハマります。

Pythonだとこのあたりの話です。
https://tagosuck.cocolog-nifty.com/tagolog/2020/07/post-d99d01.html

**Comment by nabeta** [comment]
> CiNii BooksのサーバーはDH_KEY_TOO_SMALLエラーが発生します。

@ryuuji @miyatatk 本件、NIIのサポートに問い合わせを送ってみました。ちなみに、CiNii Researchはこの問題がないようです。

**Comment by nabeta** [comment]
こちら、2022年4月に対応予定とのことです。

**Comment by nabeta** [comment]
開発中のenju_leaf-1.4のDocker環境(Debian 11.3)で、OpenSSLの設定の変更なしに、CiNii Booksからのインポートができることを確認しています。
https://dev.next-l.jp/manifestations/99

OpenSSLの設定は以下のようになっています。

```
enju@d26ec39bdf09:/enju$ tail /etc/ssl/openssl.cnf 
				# identifier (optional, default: sha1)
[default_conf]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```
