### ISSUE TITLE
Debian11 (bullseye) でsunspot同梱のSolrを使用できない

### ISSUE THREAD

**Issue by yufushiro** [next-l/enju_leaf#1572]
Enju Leaf インストール手順には OpenJDK の要件について「Java9以上では動作しません」と記載されていますが、Debian の現行の安定版である Debian 11 (bullseye) には openjdk-8-jre-headless パッケージが存在しないため、手順通りにインストールできない状態になっています。

> - Java SE / OpenJDK 8（Java9以上では動作しません）

https://github.com/next-l/enju_leaf/wiki/Install/c641a4d6a6954ac3f9aad1d86bb5314151486e44#%E3%82%B5%E3%83%BC%E3%83%90%E5%81%B4

sunspot に同梱されている Solr 5.3.1 (2015/9/24) は長らくアップデートされていないため、もし可能であれば Enju Leaf インストール手順は sunspot 同梱のバージョンを使わずにより新しいバージョンの Solr をインストールする手順に変更した方が良いと思います。
（関連Issue: #1368）

**Comment by nabeta** [comment]
@yufushiro お知らせありがとうございます。Debian 11の場合、AdoptOpenJDKを使用することになると思います。手元の環境で、``adoptopenjdk-8-hotspot-jre``パッケージで起動することは確認しました。
https://adoptopenjdk.net/installation.html#linux-pkg

将来はDockerでのインストールを中心にする予定ですが、もうしばらく時間がかかりそうです。

**Comment by yufushiro** [comment]
ありがとうございます。AdoptOpenJDK を使うことで無事にインストールを完了できました。
標題の Debian 11 で Solr 5.3.1 が動作しない問題についてはこれでしばらくは回避できそうなのでクローズします。
