### ISSUE TITLE
デモサーバ上で新規ユーザを作成すると，所蔵登録ができない

### ISSUE THREAD

**Issue by harumukanon** [next-l/enju_leaf#1574]
1. デモサーバに管理者権限でログイン
2. 新規利用者を登録（Librarian権限）
3. 新規登録したアカウントとパスワードでログイン
4. ISBNで書誌をインポート
5. 所蔵登録

しようとすると，1~4まではできますが，5ができず，「We're sorry, but something went wrong.
If you are the application owner check the logs for more information.」の画面が出ます。

**Comment by harumukanon** [comment]
「でもサーバ上で新規ユーザを作成すると」としていましたが，enjuadminでも新規所蔵登録はできないことを確認しました。

**Comment by nabeta** [comment]
> 「でもサーバ上で新規ユーザを作成すると」としていましたが，enjuadminでも新規所蔵登録はできないことを確認しました。

@harumukanon お返事が遅くなりましてすみません。ひとまずenjuadminで出ている所蔵登録のエラーを修正しました。
新規ユーザについては確認中です。

**Comment by harumukanon** [comment]
ご対応ありがとうございました！

**Comment by yegusa** [comment]
クローズします。
