### ISSUE TITLE
VMにインストールした発注リストの新規作成画面を開くとエラーになる

### ISSUE THREAD

**Issue by haruka8307** [next-l/enju_leaf#1578]
お世話になります。

最新版のVMにEnju1.3のマニュアルに沿って発注リスト機能のモジュールをインストールしました。
https://next-l.github.io/manual/1.3/enju_install_vm_5.html

図書館の管理＞発注リスト＞発注リストの新規作成 の順に発注リストの新規作成画面を開いたときに
次のようなメッセージが表示され先に進むことができません。

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```
「システムの基本的な情報の表示」には下記の通り表示されインストールはできているようです。
`enju_purchase_request: 0.3.1`

解決方法や必要なログなどご教示いただけるでしょうか。
どうぞよろしくお願いいたします。

**Comment by haruka8307** [comment]
度々お世話になります。

Enju leafの「発注リスト作成機能」を使ってみたい，単純にどんな機能なのか試してみたいというところで，手順通りに当該モジュールのインストールをインストールしました。
しかし発注リストの新規作成画面を開いたときにエラーメッセージが出てしまって試しに使ってみることがでできません……。

発売直後の新刊のの書誌ができるまでの間，何かしら記録を残すのに使えるのかなと思っているのですが，デモで体験できればそれでもいいのかなと思っています。

過去のスレッドでは同様の問題は解決しているとのことですが，
https://github.com/next-l/enju_leaf/issues/1507

自分の環境だと#1578の通りで進むことができません。
どうやったら問題が解消するのか，どう対応するのがいいのかご教示いただけますと幸いです。

環境はさくらのVPS（OSはUbuntu server 20.04）で，次のページを参考に基本的な環境は構築しています。
https://github.com/next-l/enju_leaf/wiki/Install

把握できている情報が不十分で，頓珍漢な質問かもしれずご迷惑をおかけします。
「できるんだったら発注リスト機能を使ってみたい」（個人で使うレベルだったら不要かもしれないけれど）ので，何卒よろしくお願いいたします。

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/issues/1507 の修正を、enju_purchase_request-0.3.2としてリリースしました。
#1610 と重複しているので、こちらはクローズします。
