### ISSUE TITLE
「ブックマーク機能」のモジュールをインストールすると資料の検索ができない

### ISSUE THREAD

**Issue by haruka8307** [next-l/enju_leaf#1579]
#1578と同じように
最新版のVMにEnju1.3のマニュアルに沿ってブックマーク機能のモジュールをインストールしました。

何件か資料を登録してからトップページにある「新着資料」や「資料の検索」を開こうとすると
次のエラーメッセージが表示されてしまい資料の検索ができません。

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
```

「システムの基本的な情報の表示」には下記の通り表示されインストールはできているようです。
`enju_bookmark: 0.3.1 `

解決方法や必要なログなどご教示いただけるでしょうか。
どうぞよろしくお願いいたします。

**Comment by nabeta** [comment]
@haruka8307 お返事が遅くなりましてごめんなさい。現在、ブックマークモジュールはEnju本体の開発に追随できていない状態です。修正までしばらくお待ちいただけますでしょうか。

**Comment by haruka8307** [comment]
ありがとうございます。
承知しました。

**Comment by nabeta** [comment]
@haruka8307 ブックマークモジュールについて修正を行っていますので、よろしければ最新版で試してみてください。
https://github.com/next-l/enju_bookmark/wiki

**Comment by haruka8307** [comment]
ご対応いただきありがとうございました。
試してみます。

**Comment by haruka8307** [comment]
無事動くようになりました。
ありがとうございました。
