### ISSUE TITLE
要望：利用者情報のTSVインポート：localeに設定できる値をWebインタフェースで提示したい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#158]
#149 から派生したものです。

利用者情報のTSVインポートにおいて設定できるlocaleについての機能です。

localeに設定できる値や、デフォルトで設定される値は、
サーバーにログインしないとわかりません。

これをWebインタフェースで提示したいと思います。

案1：
「図書館の管理」→「システムの設定」の画面で、
「システム」のところに「使用言語」のリンクを追加して、
そのリンクをたどると

名前　表示名　　
ja 日本語　　（デフォルト使用言語）
en 英語

という表がでる。

というようなのでもいいかも。

**Comment by masao** [comment]
少し違うような気もしますが、システム基本情報の末尾に出力するようにしてみました。
「システムの設定」→「システムの基本的な情報の表示」で確認ください。
ついでに、Rubygemsの表示をアルファベット順に並べるように、Rubyバージョンの出力等の機能も追加してあります。
![next l enju leaf_2](https://cloud.githubusercontent.com/assets/38825/10104356/479dbbda-63e4-11e5-8c58-ce153706f337.png)

**Comment by yegusa** [comment]
いいですね～。

仮想マシンでできることを確認しました。クローズします。
（マニュアルにはまだ書いてません）

![image](https://cloud.githubusercontent.com/assets/1328499/10114893/6336b086-6434-11e5-8e4c-1421ad444dd9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5568542)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by yegusa** [comment]
マニュアルの関連した部分の修正も完了しました。
