### ISSUE TITLE
図書館内の本棚の順序が、所蔵の新規作成のときに反映されていない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1580]
#355 に関連

#355 のやりかたで、本棚の順序を変えた。zzz01のほうが上になっているのがわかる。

![image](https://user-images.githubusercontent.com/1328499/139572508-d1283bbb-e370-4a2d-b633-9c1d847c5412.png)

しかし、図書館のページの「本棚」タブをみてると、zzz01のほうが上になっていない。
（正しくは、zzz01になっているはず）

![image](https://user-images.githubusercontent.com/1328499/139572488-999d2e52-c06d-41f6-a339-407ae012c92d.png)

P.S.
やりたいことは、新しい所蔵を追加したいとき、
新規所蔵作成の画面に遷移した後に、
図書館を選ぶと（ここでは「既定の図書館02」を選んだ）
本棚の順番が、先ほど順序を変えたのに反映しておいてほしい
（ここの例では本棚が「zzz01」になっているのが望まれる結果）

![image](https://user-images.githubusercontent.com/1328499/139572598-c02847eb-58aa-4c9d-b7f6-353655a6c3fa.png)

**Comment by nabeta** [comment]
開発サーバで修正済みです。
https://dev.next-l.jp/shelves?library_id=yours
