### ISSUE TITLE
XLSX形式でのデータエクスポート

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1581]
エクスポートしたデータをエクセルで操作するスースケースが多いが、TSV形式の取り扱いは難しいため、XLSX形式で直接エクスポートできるとよい。
XLSX形式の場合は、セルのデータ型なども定義できるため、日付型や数値型に自動変換されることによるデータ破損のリスクを軽減できる。

**Comment by yegusa** [comment]
2021-12-04 Enju WS で、どのライブラリがよいかまずは調べてみようやってみよう！　となりました。

**Comment by nabeta** [comment]
caxlsx/caxlsx_railsを使用する予定です。
https://github.com/caxlsx/caxlsx_rails

**Comment by nabeta** [comment]
XLSXファイルもTSVファイルと同じ内容を出力するようにしました。また、リンクを追加しました。
https://dev.next-l.jp/manifestations
![image](https://user-images.githubusercontent.com/11428/162787704-73424d23-550a-469a-8be0-2cda0151d830.png)

**Comment by nabeta** [comment]
詳細画面にもXLSXファイルのリンクを追加しています。
https://dev.next-l.jp/manifestations/89
