### ISSUE TITLE
検索結果一覧のTSVエクスポートを .txt (.textではなく）とするように戻してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1582]
まだリリースされてないようですが、検索結果一覧のTSVエクスポートで、.textとなるように変更されているようです。

https://github.com/next-l/enju_biblio/commit/a21baf8ada8ca4229094ed3d1935b4d7da78c795

コミュニティの合意なく実装されたため、なぜそのような変更がなされたのかわかりませんが、一般的ではないと思いますし、大変戸惑います。

いったん、.txt に戻すようお願いします。

現象：
検索結果一覧の「TSV」の上で「名前を付けてリンク先を保存」とすると、 
デフォルトのファイル名の拡張子が.text となる。

検索結果一覧で、「TSV」リンクの上で、「名前を付けてリンク先を保存」を使用としているところ
![image](https://user-images.githubusercontent.com/1328499/143738832-9a0adc62-8ed9-4273-944c-8e21cf4a9a2a.png)

ファイル名が「manifestations.text」と　拡張子が .text となっているところ
![image](https://user-images.githubusercontent.com/1328499/143737674-c7b21f61-d60b-448d-8ba8-e116667b4189.png)

**Comment by nabeta** [comment]
@yegusa 説明なしの作業で申し訳ありません。本来Railsでは、テキストのテンプレートは、拡張子が`txt`でも`text`でも動作するようになっているのですが、Enjuでは大昔に、拡張子の設定を誤って上書きしてしまっていました。これを直そうとして途中になっていました。

以下のコミットで修正しました。デモサーバにも反映済みです。
https://github.com/next-l/enju_leaf/commit/e9d265be88293a170bd465e595f9c52352382b78

**Comment by yegusa** [comment]
デモサーバーで、.txtで保存できることを確認しましたのでクローズします。
