### ISSUE TITLE
書籍に対する登録項目について

### ISSUE THREAD

**Issue by jippless3024** [next-l/enju_leaf#1588]
Enjuを個人での書籍整理のために利用させていただいております。
図書館管理のための利用でないため、各書籍の登録時に変更したい項目があります。
具体的には下記のようなものです。

- カスタム項目によって追加した項目に関して、ソートの有効化、ドロップリスト等の入力方法の選択、数字のみ等の入力値の制限(具体的には書籍の評価値などを考えています)

- 登録時に利用予定のない項目の非表示

これらのカスタマイズに関してはコードを修正するしかないとは予想しておりますが、もしも機能として存在していれば、と思い確認させてください。
また、コードを修正する場合はマニュアルの「第10章 その他（カスタマイズなど）」に記載されている画面のカスタマイズの応用で実現できると予想しておりますが、認識に相違ありませんでしょうか？

お手数をおかけいたしますが、上記ご教示いただくことは可能でしょうか？

**Comment by nabeta** [comment]
@jippless3024 遅くなってすみません。現時点で存在するのは独自の書誌・所蔵項目の追加のみとなっており、それ以上についてはプログラム側の修正が必要になります。
https://enju.next-l.jp/manifestation_custom_properties
https://enju.next-l.jp/item_custom_properties

> また、コードを修正する場合はマニュアルの「第10章 その他（カスタマイズなど）」に記載されている画面のカスタマイズの応用で実現できると予想しておりますが、認識に相違ありませんでしょうか？

はい、そのようになります。
