### ISSUE TITLE
wikiの記載に関する要望

### ISSUE THREAD

**Issue by jippless3024** [next-l/enju_leaf#1589]
- [x] mdマニュアル修正の必要なし #1609

wikiを読んでいる際、気になった点がありますので下記に記載いたします。

1. wikiからマニュアルへのリンク先が404となっている。
https://github.com/next-l/enju_leaf/wiki の「マニュアル (manual)」→「マニュアル一覧」のリンクが404となっています。

2. モジュールの概要が分からない
マニュアルにてモジュールの導入方法が確認でき、https://github.com/next-l/enju_leaf/wiki/CI にてモジュールの一覧を見ることはできるのですが、各モジュールの概要が分からないため、導入の検討が行えません。
どのような機能かの概要と、画面上どのような動きになるのかについて記載があると助かると思いました。

**Comment by nabeta** [comment]
@jippless3024 お知らせありがとうございます！ 取り急ぎ、マニュアルのリンク先は修正しました。
他にいただいたコメントは追ってお返事しますので、しばらくお待ちください。

**Comment by jippless3024** [comment]
@nabeta ご確認ありがとうございます！
マニュアルのリンクですが、今度はそもそもリンクが設定されていないようです。
繰り返しのご連絡になり申し訳ありませんが、もう一度ご確認いただけると幸いです。

**Comment by nabeta** [comment]
@jippless3024 すみません、タイプミスでした。先ほど修正しました。

**Comment by jippless3024** [comment]
@nabeta ご対応ありがとうございます！
五月雨となり申し訳ありませんが、[Next-L Enju マニュアル](https://www.next-l.jp/?page=manual)についても「Next-L Enju 初期設定マニュアル」「Next-L Enju 運用マニュアル」のリンクが404となっているようです。
別経路などから辿りつけるため、優先度は低いとは思いますが、気がついたので記載しておきます。

**Comment by masao** [comment]
ご連絡ありがとうございます。リンク切れについては修正しました。

**Comment by nabeta** [comment]
> モジュールの概要が分からない

1.4系ではモジュールの追加はサポートしていないため、クローズします。
