### ISSUE TITLE
書誌の目次データのTSVのエクスポート・インポート

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1590]
#296 から派生　（#296 で1件づつなら入力・編集できる）

できるようにしてほしい。

改行はどうするのか　が注意と思われる。

**Comment by nabeta** [comment]
エクスポートは以下のコミットで追加しました。
https://github.com/next-l/enju_biblio/commit/ebc7481c454b2fc266791eee252cc25c77ee2df6

デモサーバにも反映済みです。
https://enju.next-l.jp/manifestations/84.txt

**Comment by yegusa** [comment]
インポートが実装されてませんよね？

**Comment by nabeta** [comment]
インポートは以下で実装しています。
https://github.com/next-l/enju_leaf/commit/15f273c160fddbf4994337e2771a3f71aedc67d7

**Comment by yegusa** [comment]
全件の書誌・所蔵データのエクスポートにabstract の列がないです。

**Comment by nabeta** [comment]
エクスポートはデモサーバで未反映でした。インポートは以下のコミットで追加しています。
https://github.com/next-l/enju_biblio/commit/f025a148a9885ef0c38e86c07766d05d7c4c02e6

**Comment by yegusa** [comment]
文字化けしたけど、インポートはできた。
https://enju.next-l.jp/resource_import_files/6

**Comment by yegusa** [comment]
デモサーバーで
- インポート
- 検索結果一覧のエクスポート
- 全書誌・所蔵情報のエクスポート

ができることを確認したのでクローズします。

**Comment by yegusa** [comment]
ヘッダは、 abstract ですね。

- [ ] マニュアル インポートファイルの書き方 https://next-l.github.io/manual/1.3/enju_operation_4.html#section4-2-10
- [ ] マニュアル エクスポートの項目の説明 https://next-l.github.io/manual/1.3/enju_webapi_1.html#bib_tsv_export
