### ISSUE TITLE
translation missing: ja.enju_ndl.import_from_ndl_search

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1591]
1.4系でEnju Leafを立ち上げた際に、NDLサーチからの検索取り込みのメニューが翻訳を認識していない状態です：

![enju-ndl-translation-missing](https://user-images.githubusercontent.com/38825/156868643-d1ecf6a8-0edc-481e-8ccf-55b789f1093e.png)

**Comment by nabeta** [comment]
以下のコミットで追加しました。
https://github.com/next-l/enju_leaf/commit/73f9661e1b003219f0c83b72e5c6ad6f1995c2c2
