### ISSUE TITLE
デモサーバーで検索結果一覧の「（所蔵）」リンクをクリックしたときに何も起きない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1594]

**Comment by nabeta** [comment]
この現象は、1.4系の新規インストールでは確認できませんでした。デモサーバの問題と思われます。

**Comment by nabeta** [comment]
所蔵表示のリンクをクリックした際、本来JavaScriptのテンプレートを読み込むようになっているのですが、HTMLのテンプレートを読み込んでいました。

本来読むべきファイル(show.js.erb):
https://github.com/next-l/enju_biblio/blob/1.3/app/views/manifestations/show.js.erb

実際に読み込まれていたファイル(show.html.erb):
https://github.com/next-l/enju_biblio/blob/1.3/app/views/manifestations/show.html.erb

以下のコミットで、show.js.erbを明示的に読み込むようにしました。
https://github.com/next-l/enju_biblio/commit/51674a497f55b1f7bde50ede78da9a9956c0041b

**Comment by nabeta** [comment]
@yegusa デモサーバに反映済みなので、確認をお願いします。

**Comment by yegusa** [comment]
できていることを確認したのでクローズします。
