### ISSUE TITLE
質問：VirtualBoxでプロキシ環境でもISBNを使ったインポートができる方法をおしえてください

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#160]
VirtualBoxでプロキシ環境でも
ISBNを使ったインポートやNDL検索を使ったインポートができる方法をおしえてください

**Comment by yegusa** [comment]
以下の環境で、 #160 にある設定をしましたが、

504 Gateway Time-out
nginx/1.4.6 (Ubuntu)

とでて、できません。　bundle update はできました。
ので、再オープンします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by yegusa** [comment]
### 1.  enju/.env に、以下の2行を追加

http_proxy=http://proxy.example.com:8080
https_proxy=http://proxy.example.com:8080

### 2. enju を再起動

$ sudo restart enju_leaf

とすればできるようになりましたので、クローズします。

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)

**Comment by nabeta** [comment]
以上の方法で問題ありません。
