### ISSUE TITLE
デモサーバーの催し物がwe're sorryになります

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1603]
https://enju.next-l.jp/events?mode=calendar

がwe're sorryになります

**Comment by nabeta** [comment]
TSVファイルの拡張子の修正漏れで、以下のコミットで修正しました。
https://github.com/next-l/enju_event/commit/f5ef2fb29de884b35bebb29f17995ed45ea16888

**Comment by yegusa** [comment]
そう。今、動いているのを確認したのでクローズします。
