### ISSUE TITLE
催し物の一覧の「tsv」のファイル名の拡張子を.text からtxtに変更

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1605]
#1601 と類似

![image](https://user-images.githubusercontent.com/1328499/156992239-7d18aed9-fe3e-4c0d-9519-490d7fe57032.png)

**Comment by nabeta** [comment]
以下のコミットで修正済みです。
https://github.com/next-l/enju_event/commit/f5ef2fb29de884b35bebb29f17995ed45ea16888

デモサーバにも反映しました。

**Comment by yegusa** [comment]
デモサーバーでtxtになっていることを確認しましたのでクローズします。

**Comment by yegusa** [comment]
マニュアルについて　バグ修正であり、とくに、.txt である旨に関係するマニュアル該当部分はなかったので修正なしとする。
