### ISSUE TITLE
発注リスト機能モジュール

### ISSUE THREAD

**Issue by haruka8307** [next-l/enju_leaf#1610]
度々お世話になります。
以前#1578で投稿したものですが，

さくらのVPS（OSはUbuntu server 20.04）で，次のページを参考に基本的な環境を構築した上で。
https://github.com/next-l/enju_leaf/wiki/Install

[enju_purchase_request]モジュール（発注リスト作成機能）を単純にどんな機能なのか試してみたいというところで，手順通りに当該モジュールのインストールをインストールしました。
しかし発注リストの新規作成画面を開いたときにエラーメッセージが出てしまって先に進むことがでできません……。

発売直後の新刊のの書誌ができるまでの間，何かしら記録を残すのに使えるのかなと思っているのですが。
デモサーバでも体験できればそれでもいいのかなと思っています。

過去のスレッドでは同様の問題？は解決しているとのことですが，
https://github.com/next-l/enju_leaf/issues/1507

どうやったら問題が解消するのか，どう対応するのがいいのかご教示いただけますと幸いです。

把握できている情報が不十分で，頓珍漢な質問かもしれずご迷惑をおかけします。
「できるんだったら発注リスト機能を使ってみたい」（個人で使うレベルだったら不要かもしれないけれど）というところですが，何卒よろしくお願いいたします。

**Comment by nabeta** [comment]
@haruka8307 遅くなってすみません。このモジュールはかんたんに言うと、ブックマークモジュールで集めた資料の情報の一覧をTSVで出力するというものです。このTSVファイルを発注リストとして、書店に提出することを想定していました。
（それで業務が回るのかと疑問に思われるかもしれませんが、当時図書館の仕事をしていた私は、そういう一覧出力ができる機能だけでもほしかったのです）

今後このモジュールの積極的な開発は行わない予定ですが、とりあえずインストールだけはできるようにしておこうと思いますので、しばらくお待ちください。

**Comment by haruka8307** [comment]
ありがとうございます。
やっぱり使える機能はいろいろと試してみたいなと思っているので，どうかよろしくお願いいたします。

**Comment by nabeta** [comment]
@haruka8307 enju_purchase_request-0.3.2で、発注リストの新規作成画面のエラーを修正しました。また、Wikiにインストールマニュアルを追加しました。
https://github.com/next-l/enju_purchase_request/wiki

**Comment by haruka8307** [comment]
ご対応ありがとうございます。
問題なく発注リストの新規作成ができるようになりました。
