### ISSUE TITLE
書誌・所蔵エクスポートにlibraryが出力されていない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1611]
#1584 でチェックしていて気づいた。

- [ ] 全書誌データエクスポートでlibrary を出力する
- [ ] 検索結果一覧のエクスポートでlibrary を出力する

テストもかいてください。
以前は出力されていた形跡があるのに、Enju Leaf 1.3.6では少なくとも出力されていないので修正が必要。

**Comment by nabeta** [comment]
`library`を出力に追加しました。デモサーバに反映済みです。
https://enju.next-l.jp/manifestations.txt
![image](https://user-images.githubusercontent.com/11428/161410037-d95c3379-e598-42b7-87e4-c98bfca13e8d.png)

**Comment by masao** [comment]
libraryが出力されていることを確認しました。クローズします。
