### ISSUE TITLE
書誌・所蔵エクスポートにmanifestation_priceが出力されていない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1612]
#1584 でチェックしていて気づいた。

- [ ] 全書誌データエクスポートでlibrary を出力する
- [ ] 検索結果一覧のエクスポートでlibrary を出力する

テストもかいてください。
以前は出力されていた形跡があるのに、Enju Leaf 1.3.6では少なくとも出力されていないので修正が必要。

**Comment by yegusa** [comment]
注：Enju Leaf 1.3.6では、 price となっているっぽい。
manifestation_pricenにすべき。

**Comment by nabeta** [comment]
`manifestation_price`として出力するようにしました。デモサーバに反映済みです。
https://enju.next-l.jp/manifestations.txt
![image](https://user-images.githubusercontent.com/11428/161410037-d95c3379-e598-42b7-87e4-c98bfca13e8d.png)

**Comment by masao** [comment]
項目が追加されていることを確認したのでクローズします。
![image](https://user-images.githubusercontent.com/38825/168411262-8ac62497-4094-4e08-8212-2a71054f08b8.png)
