### ISSUE TITLE
複数のJavaバージョンの共存

### ISSUE THREAD

**Issue by miyatatk** [next-l/enju_leaf#1616]
@nabeta お世話になります。
もともとEnju用のマシンにはOpenJDK 8をインストールし、新しいJavaをアンインストールしていました。しかし、このたび他のアプリの都合でOpenJDK 11をインストールすることになり、共存の必要が生じました。
```
$ update-java-alternatives --list
java-1.11.0-openjdk-arm64      1111       /usr/lib/jvm/java-1.11.0-openjdk-arm64
java-1.8.0-openjdk-arm64       1081       /usr/lib/jvm/java-1.8.0-openjdk-arm64
```
後から11をインストールすると11が優先され、Enjuが動作しなくなりました。そこで、明示的にEnjuではOpenJDK 8を選ぶようにしたいのですが、どのような設定をすればよいでしょうか。

ちなみにEnjuのバージョンは1.3.5のままです。（まだDocker版は怖くてアップデートできていません。）

**Comment by nabeta** [comment]
@miyatatk EnjuでJavaを使用するのはSolrなので、SolrをJava8で起動するようにすればよいです。
`/etc/default/solr.in.sh`の`SOLR_JAVA_HOME`を以下のように指定して、Solrを再起動してください。

```
SOLR_JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
```

**Comment by miyatatk** [comment]
@nabeta お返事ありがとうございます。

私のDebian環境では `/etc/default` に `solr.in.sh` は存在せず、

`~/enju/vendor/bundle/ruby/2.5.0/gems/sunspot_solr-2.5.0/solr/bin/solr.in.sh`

にありましたので、こちらを修正しました。

Enjuは元通り動くようになりましたが、`/etc/default` にも `solr.in.sh` をコピーしておいた方が良いでしょうか？

**Comment by nabeta** [comment]
@miyatatk ああ、sunspot_solrでの起動だったのですね。現在sunspot_solrの起動コマンドはどのように実行されていますか？

**Comment by miyatatk** [comment]
@nabeta お世話になります。以下のようにサービス化して、`foreman start` で起動しています。
```
# /lib/systemd/system/enju_leaf.service

[Unit]
Description=Next-L Enju Leaf Integrated Library System
After=postgresql.service
After=redis-server.service
After=nginx.service
Documentation=https://www.next-l.jp/

[Service]
Type=simple
User=USER
WorkingDirectory=/home/USER/enju/
ExecStart=/usr/local/bin/foreman start

[Install]
WantedBy=multi-user.target
```

**Comment by nabeta** [comment]
@miyatatk foremanでのアプリケーション起動時に、環境変数`JAVA_HOME`を渡せばよさそうです。
https://qiita.com/sayama0402/items/9b95b4a3d70c72f5fa5c

`/home/USER/enju/.env`に以下の行を追加するといかがでしょうか。

```
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-arm64"
```

**Comment by miyatatk** [comment]
@nabeta ありがとうございます。こちらの方がスッキリしますね。

`solr.in.sh` の変更を戻して、
```
$ echo JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-arm64 >> .env
```
を実行して再起動したら、問題なくEnjuが動作しました。
