### ISSUE TITLE
Excel出力にてNDC等を文字列データとして保存する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1649]
#1581 で実装されたのxlsx出力にて、NDC 007.58 などが "7.58" となってしまう現象が出ますね。 

![image](https://user-images.githubusercontent.com/38825/164147582-412585a2-aac8-4b49-ab17-6dd1e167365b.png)

**Comment by nabeta** [comment]
TSVファイルでは正しく007.58と出力されており、XLSXファイルのみの問題ですね。

**Comment by nabeta** [comment]
マニュアルによると、出力時に明示的にデータ型を指定すればよいようです。
https://github.com/caxlsx/caxlsx/blob/master/examples/override_data_types_example.md

**Comment by masao** [comment]
修正されたことを確認しました。クローズします
