### ISSUE TITLE
ログイン後に「タグはついていません」という文字だけが表示される

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#1653]
1.4系での現象。再現方法は以下。

1. ログインしていない状態で、[書誌検索画面](https://dev.next-l.jp/manifestations?query=&commit=%E6%A4%9C%E7%B4%A2)を開く。
2. 画面上部のログインリンクからログインする。
3. 「タグはついていません。」という文字だけが表示される画面になる。

**Comment by yegusa** [comment]
そんながめんにならず、無事、普通にログインできました。
大丈夫そうなので、クローズします。

![えんじゅ図書館-Next-L-Enju-Leaf](https://user-images.githubusercontent.com/1328499/174469865-58ef37ad-81b7-47d7-aebd-f58813300680.png)
