### ISSUE TITLE
[Question / V1.4 ] 書籍をTSVファイルからインポート時の項目について

### ISSUE THREAD

**Issue by is984** [next-l/enju_leaf#1666]
## 質問 
- インポート時に項目「manifestation_required_role(表示権限)」が反映されません
  - この動作は意図した物でしょうか。

## 備考
マニュアルを読んでもこのあたりの挙動が書かれていないように見受けられましたので質問します。
インポート処理時のメッセージを見るにこの項目は無視されているようです。

**Comment by nabeta** [comment]
たしかに、required_roleがサンプルのファイルにもテストにもありませんね。確認します。

**Comment by is984** [comment]
後対応いただきありがとうございました。
このissueはクローズします。
