### ISSUE TITLE
solrのイメージプルにM1 Macで失敗する

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1669]
no matching manifest for linux/arm64/v8 in the manifest list entries
というエラーが発生します。

<img width="818" alt="スクリーンショット 2022-05-14 14 09 20" src="https://user-images.githubusercontent.com/166170/168411646-80a588ef-f081-4685-a69a-06bf59988bf5.png">

**Comment by nabeta** [comment]
@ryuuji お使いの環境はM1 Macですね。現在、Solrは`solr:6`イメージを使用しているのですが、amd64イメージしかないようです。  
https://hub.docker.com/layers/solr/library/solr/6/images/sha256-44f44e509c1ecb2de3c1b9810b646f4f9d410e2fff536de4aaf43e6992b21dfb?context=explore

`6-alpine`はarm64のイメージがあるので、docker-compose.ymlでのSolrのイメージ指定をこちらに切り替えると起動すると思います。
https://github.com/next-l/enju_leaf/blob/main/docker-compose.yml#L63=

ただ、更新が3年前となっているので、使用には注意が必要かもしれません。
https://hub.docker.com/layers/solr/library/solr/6-alpine/images/sha256-65d9d4888a136917518fd9f25dc9431e77935596ac7bdbf08b7d0dbb1c44582d?context=explore

**Comment by nabeta** [comment]
@ryuuji mainブランチで、Solrのイメージに`solr:8`を使用するようにしました。arm64でも利用できるはずです。
https://hub.docker.com/layers/solr/library/solr/8/images/sha256-c91f3a9298ef1d8fab5932c85a8d978ff47a944f92bb9f75e4d5b43e9b31ccb0?context=explore
