### ISSUE TITLE
貸出統計の新規作成画面にてRailsエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1670]
1.4系にて、貸出統計の新規作成画面に移ったときにエラーになる。
/manifestation_checkout_stats/new

![image](https://user-images.githubusercontent.com/38825/168413279-5cdfcd6d-9b3d-454c-a319-ff1108abef6e.png)

**Comment by nabeta** [comment]
@masao このメッセージは、rails-i18n gemに含まれているのですが、1.3系には入っていたところ、1.4系には入っていませんでした。修正します。
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml

**Comment by nabeta** [comment]
PRがマージされたので、クローズします。
