### ISSUE TITLE
ステータス監視用のエンドポイント

### ISSUE THREAD

**Issue by ryuuji** [next-l/enju_leaf#1672]
依存するコンポーネント（solr,redis等）の稼働状況を含めて、システム全体の健全性を返すエントポイントがあると、監視が容易になるのではないかと思います。

**Comment by nabeta** [comment]
Rails 7.1で、監視用のエンドポイントが標準機能になるようです。
https://github.com/rails/rails/pull/46936

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/pull/1901 でEnju本体のヘルスチェックエンドポイント `/up` を追加しました。

**Comment by nabeta** [comment]
Enjuのコンテナ以外の監視はEnjuとは別枠で行うこととして、クローズします。
