### ISSUE TITLE
言語切り替えに見慣れない言語の一覧が追加されてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1690]
Serbian, Turkish, Nepali, などなど、あまり使わない言語群が追加されているように見えます。
![image](https://user-images.githubusercontent.com/38825/174466987-d6931f96-c97d-4877-a2d9-13dafaa46bb9.png)

**Comment by nabeta** [comment]
@masao mainブランチをpullした上で、以下のコマンドでキャッシュを削除してください。

```
docker compose run --rm web rails c
> Rails.cache.clear
```

**Comment by masao** [comment]
修正されたことを確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/174469078-cffdad15-3b4e-451b-a7f7-1e761b1ed043.png)
