### ISSUE TITLE
新しいEnju構築時に図書館の一覧に初期設定分が出てこない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1703]
http://localhost:8080/libraries にて、存在するはずの Your library や World Wide Web が出てこない。

コマンドで明示的に reindex したら表示されるようになった

```sh
docker compose run --rm web rake sunspot:reindex
```

**Comment by masao** [comment]
別途作った図書館のみが表示されている例：
![image](https://user-images.githubusercontent.com/38825/174470908-25604388-f652-4e43-9c4d-f9bb3192a64d.png)

**Comment by nabeta** [comment]
インストール時にインデックス作成を明示的に実行するように、ドキュメントに追記しました。
https://github.com/next-l/enju_leaf/wiki/Docker#docker%E3%81%AB%E3%82%88%E3%82%8Benju%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E6%96%B9%E6%B3%95=

```sh
docker compose run --rm web rake sunspot:reindex
```
