### ISSUE TITLE
利用者情報のインポートができない

### ISSUE THREAD

**Issue by harumukanon** [next-l/enju_leaf#1768]
利用者情報をTSVファイルでインポートしようとすると，「We're sorry, but something went wrong.」というエラーメッセージが出て登録ができません。ただし，インポートしようとしたデータについて，「インポート用ファイルの一覧」からは処理待ちの状態で表示はされます。（処理待ちのまま登録はされません）。

**Comment by nabeta** [comment]
@harumukanon 以下のコマンドを実行した状態で、TSVファイルのアップロードを行ったときにどのようなエラーが出力されるか教えていただけますか。

```
$ cd enju_leaf
$ docker compose logs -f web
```

**Comment by harumukanon** [comment]
すみません，使っているのはデモサーバです。デモサーバでアップロードができないの意です。

**Comment by nabeta** [comment]
@harumukanon 再起動したので、もう一度試していただけますか。

**Comment by harumukanon** [comment]
今度はenjuadminでログインができなくなってしまいました。「The change you wanted was rejected.
Maybe you tried to change something you didn't have access to.」と出ます。

**Comment by nabeta** [comment]
@harumukanon すみません、これはデモサーバの設定ミスでした。現在はログインできるようになっています。

**Comment by harumukanon** [comment]
ありがとうございます。ログイン，インポートもできました。
