### ISSUE TITLE
バグ：右メニューにLibrarian権限でアクセス不可のページへのリンクがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#178]
Librarian権限でログインした場合についてですが、
右メニューのリンクのうち、
リンク先がAdministrator権限でしかみれないページとなっていて、このリンクをたどると
「アクセスが拒否されました」となります。

本来は、Administrator権限でログインした場合のみ見えているはずのリンクであり、
Librarian権限のアカウントでログインした場合は、表示されているべきでないリンクです。

このリンクを削除する必要があるかと思います。

例：「件名の種類の一覧」に[件名の種類の新規登録]リンクが表示されている
![「件名の種類の一覧」に[件名の種類の新規登録]リンクが表示](https://cloud.githubusercontent.com/assets/1328499/3280894/e6663304-f483-11e3-9380-616459f091e7.png)

例：「件名の種類の表示」の右メニューに[編集]リンクが表示されている
![「件名の種類の表示」の右メニューに[編集]が表示](https://cloud.githubusercontent.com/assets/1328499/3280887/bf4c9218-f483-11e3-9ecd-0e499a0ec8ed.png)

以下が該当します。

* [x] 件名　http://xxxx/subjects/(n) 編集、削除
* [x] 件名の種類 http://xxxx/subject_types　件名の新規作成
* [x] 件名の種類 http://xxxx/subject_types/(n)  編集
* [x] 件名標目の種類 http://xxxx/subject_heading_types 件名の種類の新規作成
* [x] 件名標目の種類 http://xxxx/subject_heading_types/(n) 編集	
* [x] 分類 http://xxxx/classification_types/(n) 編集
* [x] 分類の種類 http://xxxx/classification_types/(n) 編集
* [x] 著作の形態 http://xxxx/form_of_works/(n) 編集・・・リンクはないがアンカーがある
* [x] 資料の形態 http://xxxx/carrier_types/(n) 編集
* [x] 資料の内容の形態 http://xxxx/content_types/(n) 編集
* [x] 貸出状態 http://xxxx/circulation_statuses/(n) 編集
* [x] 利用制限 http://xxxx/use_restrictions/(n) 編集	
* [x] 人物・団体の種類 http://xxxx/agent_types　人物・団体の種類の新規作成
* [x] 人物・団体の種類 http://xxxx/agent_types/(n) 編集
* [x] 言語 http://xxxx/languages/(n) 編集
* [x] 国と地域 http://xxxx/countries　国と地域の新規作成
* [x] 国と地域 http://xxxx/countries/(n) 編集
* [x] 発行頻度 http://xxxx/frequencies/(n) 編集
* [x] 利用者グループ http://xxxx/user_groups　利用者グループの新規作成
* [x] 利用者グループ http://xxxx/user_groups/(n) 編集、貸出区分の新規作成
* [x] 貸出区分 http://xxxx/checkout_types　貸出区分の新規作成
* [x] 貸出区分 http://xxxx/checkout_types/(n) 編集、利用者グループと貸出区分の関係の新規作成
* [x] 利用者グループと貸出区分の関係 http://xxxx/user_group_has_checkout_types 利用者グループと貸出区分の関係の新規作成
* [x] 利用者グループと貸出区分の関係 http://xxxx/user_group_has_checkout_types/(n) 編集
* [x] 資料の形態と貸出区分の関係 http://xxxx/carrier_type_has_checkout_types　資料の形態と貸出区分の関係の新規作成
* [x] 催し物の種類 http://xxxx/event_categories/(n) 編集
* [x] 予算種別 http://xxxx/event_categories/(n) 予算種別の新規作成
* [x] 予算種別 http://xxxx/budget_types/(n) 編集
* [x] 書店 http://xxxx/bookstores/(n) 編集
* [x] メッセージテンプレート http://xxxx/message_templates メッセージテンプレートの新規作成	
* [x] メッセージテンプレート http://xxxx/message_templates/(n) 編集
* [x] 検索エンジン http://xxxx/search_engines 検索エンジンの新規作成
* [x] 検索エンジン http://xxxx/search_engines/(n) 編集
* [x] 識別子の種類 http://xxxx/identifier_types/(n)　編集
* [x] 図書館全体の設定 http://xxxx/library_groups/(1) 編集
* [x] 権限の設定 http://xxxx/roles 編集
* [x] 権限の設定 http://xxxx/roles/Guest 編集

参考：
```
vagrant@precise64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre53 a3d219e)
  * enju_bookmark (0.1.2.pre14)
  * enju_circulation (0.1.0.pre35)
  * enju_event (0.1.17.pre17)
  * enju_flower (0.1.0.pre15)
  * enju_leaf (1.1.0.rc10 23efe8b)
  * enju_library (0.1.0.pre32 0d9dde1)
  * enju_manifestation_viewer (0.1.0.pre13)
  * enju_message (0.1.14.pre13)
  * enju_ndl (0.1.0.pre31)
  * enju_purchase_request (0.1.0.pre9)
  * enju_seed (0.1.1.pre9)
  * enju_subject (0.1.0.pre24 89d9b28)

```

**Comment by masao** [comment]
enju_subject, enju_biblio, enju_circulation, enju_library, enju_leaf それぞれの編集リンクや新規作成リンクのチェックを追加するように修正しました。
残りは enju_event だけです（こちらは #614 に依存して修正できず…）。

**Comment by masao** [comment]
一通り修正しましたので、確認ねがいます。

**Comment by yegusa** [comment]
開発サーバー http://dev.next-l.jp/ でチェックしたらチェックする

* [ ] 件名　http://xxxx/subjects/(n) 編集、削除
* [ ] 件名の種類 http://xxxx/subject_types　件名の新規作成
* [ ] 件名の種類 http://xxxx/subject_types/(n)  編集
* [ ] 件名標目の種類 http://xxxx/subject_heading_types 件名の種類の新規作成
* [ ] 件名標目の種類 http://xxxx/subject_heading_types/(n) 編集	
* [ ] 分類 http://xxxx/classification_types/(n) 編集
* [ ] 分類の種類 http://xxxx/classification_types/(n) 編集
* [ ] 著作の形態 http://xxxx/form_of_works/(n) 編集・・・リンクはないがアンカーがある
* [ ] 資料の形態 http://xxxx/carrier_types/(n) 編集
* [ ] 資料の内容の形態 http://xxxx/content_types/(n) 編集
* [ ] 貸出状態 http://xxxx/circulation_statuses/(n) 編集
* [ ] 利用制限 http://xxxx/use_restrictions/(n) 編集	
* [ ] 人物・団体の種類 http://xxxx/agent_types　人物・団体の種類の新規作成
* [ ] 人物・団体の種類 http://xxxx/agent_types/(n) 編集
* [ ] 言語 http://xxxx/languages/(n) 編集
* [ ] 国と地域 http://xxxx/countries　国と地域の新規作成
* [ ] 国と地域 http://xxxx/countries/(n) 編集
* [ ] 発行頻度 http://xxxx/frequencies/(n) 編集
* [ ] 利用者グループ http://xxxx/user_groups　利用者グループの新規作成
* [ ] 利用者グループ http://xxxx/user_groups/(n) 編集、貸出区分の新規作成
* [ ] 貸出区分 http://xxxx/checkout_types　貸出区分の新規作成
* [ ] 貸出区分 http://xxxx/checkout_types/(n) 編集、利用者グループと貸出区分の関係の新規作成
* [ ] 利用者グループと貸出区分の関係 http://xxxx/user_group_has_checkout_types 利用者グループと貸出区分の関係の新規作成
* [ ] 利用者グループと貸出区分の関係 http://xxxx/user_group_has_checkout_types/(n) 編集
* [ ] 資料の形態と貸出区分の関係 http://xxxx/carrier_type_has_checkout_types　資料の形態と貸出区分の関係の新規作成
* [ ] 催し物の種類 http://xxxx/event_categories/(n) 編集
* [ ] 予算種別 http://xxxx/event_categories/(n) 予算種別の新規作成
* [ ] 予算種別 http://xxxx/budget_types/(n) 編集
* [ ] 書店 http://xxxx/bookstores/(n) 編集
* [ ] メッセージテンプレート http://xxxx/message_templates メッセージテンプレートの新規作成	
* [ ] メッセージテンプレート http://xxxx/message_templates/(n) 編集
* [ ] 検索エンジン http://xxxx/search_engines 検索エンジンの新規作成
* [ ] 検索エンジン http://xxxx/search_engines/(n) 編集
* [ ] 識別子の種類 http://xxxx/identifier_types/(n)　編集
* [ ] 図書館全体の設定 http://xxxx/library_groups/(1) 編集
* [ ] 権限の設定 http://xxxx/roles 編集
* [ ] 権限の設定 http://xxxx/roles/Guest 編集

**Comment by yegusa** [comment]
こちらで、チェックしたら、 x を入れてください
https://docs.google.com/spreadsheets/d/1aP1P6JOJwhN28K9Yt8ya0bgWRCWBCP-vWdwntKFE_BI/edit#gid=0

**Comment by yegusa** [comment]
Enju WS 2015-05-31の成果です！
みんなでチェックしました。
チェック完了したのでクローズします。
