### ISSUE TITLE
利用者グループと貸出区分の関係

### ISSUE THREAD

**Issue by t-machii** [next-l/enju_leaf#1783]
はじめまして、お世話になります。
1.4.1,にて
「利用者グループと貸出区分の関係」を登録すると
該当する「利用者グループ」を表示することが出来なくなる現象がございました。

- We're sorry, but something went wrong.
- If you are the application owner check the logs for more information.

このエラーはデモサーバ
https://enju.next-l.jp/
でも同様に発生しました。
よろしくお願い申し上げます。

**Comment by t-machii** [comment]
@nabeta 
ご対応ありがとうございました。
今気が付いたのですが、現在私のテスト環境にて、「CiNii Books検索によるインポート」も同様のエラーで表示できない状態です。
(現在、デモサーバーでは再現が出来ませんでした。)

また、書誌登録し、蔵書登録した本の「削除」が無くなる現象がございます。
これは上記のグループメンバーに貸し出したことと関係があるかもしれないなと思いました。
デモサーバーに所蔵番号00550088を作成して貸し出ししてみましたが、貸出していない本と違い削除の項目そのものが無くなっております。

どうぞよろしくお願い申し上げます。

**Comment by nabeta** [comment]
@t-machii 所蔵番号00550089ですが、エラーになっているのはインポートの画面でしょうか、それとも書誌詳細の画面でしょうか。

なお、一度貸出を行った所蔵は、削除ができないようになっています。ですので、「削除」リンクが表示されないのは意図した動作になります。

**Comment by t-machii** [comment]
@nabeta
つたない説明で申し訳ありません。
「CiNii Books検索によるインポート」にてNII書誌IDであるBA31086467を使用し、所蔵番号00550089を登録後、
「CiNii Books検索によるインポート」画面の検索ボタンをすることでエラーが発生するという報告でした。
現在はデモサーバーでも検索ができることを確認させていただきました。

「CiNii Books検索によるインポート」に何も入力せず検索ボタンだとやはりエラーが出ます。
私が入力したつもりで出来ていなかった可能性が無いか気になりましたが、再ビルドで解消との事で私も試してみようと思います。

貸し出しを行った所蔵の削除ができない仕様、承知いたしました。
ご対応ありがとうございました。

**Comment by t-machii** [comment]
再ビルドし、報告したかったのですが再ビルドが通らなくなってしまい、docker側でDNSなどを見直しています。
ひとまずcloseさせていただきます。有難うございました。
