### ISSUE TITLE
Enjuの要求スペックやスケールアウトについて

### ISSUE THREAD

**Issue by cold01water** [next-l/enju_leaf#1794]
現在、Enjuをdocker環境で構築して試用している者です。
単純に動作させるだけであれば、低スペックマシンでも動作可能なことはわかりました。

ただ、solrを使っている関係等で、登録する資料の数が多ければ多いほど、CPU/メモリの
要求が高くなるのでは？　と予想しています。
性能試験も行っていく予定ですが、いくつか情報がありましたら教えて頂きたく。

* 実運用・検証関わらず、どの程度の蔵書数で、どの程度のスペックが必要なのかという指標や例があれば
* 蔵書数以外にスペックに関連する処理があれば教えて頂きたいです

また、現在はシングルサーバのdocker composeで起動しているだけですが、
性能によってはスケールアウトも視野に入れています。

基本的には次のように考えていますが、推奨の方法などあれば教えてください

* フロントエンドを複数台立ててロードバランシング
* solrをクラスタリング
* DBはハードスペックを上げる

**Comment by nabeta** [comment]
@cold01water 私が管理している書誌10万件程度の実運用環境では、メモリ16GBのサーバでSolrとEnju本体、メモリ32GBのサーバでPostgreSQLを動作させています。ただし、DBサーバはEnju以外のアプリケーションでも使っており、Enju単体であればもっと少なくても問題ありません。
Solrの書き込みが操作感に大きく影響を及ぼすため、ここのディスクは速いものを使うのがおすすめです。

**Comment by cold01water** [comment]
ありがとうございます。

検証してみたところ、10万件程度なら、CPU4コア/メモリ8GB程度のマシン1台で、
充分うごくような感じがしています。SolrもディスクのIOPSが高ければ問題なさそうです。

検証により懸念が出てきたのは、同時アクセス数です。
コンテナのデフォルトの状態では、同時アクセスが30-40件になると、
長時間の待ちが発生するようになります。
内部で使われているpumaのプロセス数3に増やすと、秒間90程度まではぎりぎり使える感じです。

図書館システムなので、そこまでの多量のアクセスがあることは想定していないのですが、
問題となるのは、外部公開した場合の攻撃です。
大量アクセスをされると、すぐに貸出業務まで滞る状態になってしまいます。

これを防ぐ方法としては

1. FWでレートリミットをかける
2. WEBフロントエンドを内部系統と外部系統で分けてDBとSolrは同じもの、またはレプリカを参照する

という方法を思いつきました。

特に2の方法について、Enjuの仕様として、フロントエンドが数台並んでも稼働可能でしょうか？

**Comment by nabeta** [comment]
@cold01water お返事が遅くなりましてすみません。フロントエンド(nginx)が複数存在する環境でも、特に問題なく動作します。

**Comment by nabeta** [comment]
@cold01water 追加の質問がありましたら、Discussionsにお寄せください。
https://github.com/next-l/enju_leaf/discussions
