### ISSUE TITLE
利用者アカウントインポートエラー

### ISSUE THREAD

**Issue by harumukanon** [next-l/enju_leaf#1799]
enjuadminでログインし，TSVファイルから利用者アカウントをインポートしようとしたところ，エラー画面が表示されます。その後状態としては「処理待ち」になりましたが，登録が完了しません。

別件ですが，「9784091044259」というISBNで「ISBNインポートのリクエストの新規作成」をしようとすると，エラー画面となりました。

**Comment by nabeta** [comment]
@harumukanon お返事が遅くなりましてすみません。こちら、デモサーバのRedis（非同期処理サーバ）が停止しており、再起動して再インポートを実行したところ、ユーザがインポートされていることを確認しました。

**Comment by nabeta** [comment]
@harumukanon NDLサーチでISBN`9784091044259`を検索したところ、国会図書館の所蔵がありませんでした。エラーになっているのはこのためですが、エラーメッセージが適切に表示されていないので修正します。
https://iss.ndl.go.jp/books?ar=4e1f&rft.isbn=9784091044259&search_mode=advanced

**Comment by harumukanon** [comment]
ありがとうございます！インポートを確認しました。
