### ISSUE TITLE
書誌情報のXLSXエクスポートの際にNDC先頭のゼロが消える

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1838]
#1649 のレグレッションバグ。
![image](https://github.com/next-l/enju_leaf/assets/38825/7ec361c0-5208-4fef-94bc-70aa698a4310)

**Comment by nabeta** [comment]
@masao https://github.com/next-l/enju_leaf/pull/1839 で修正しました。 https://github.com/next-l/enju_leaf/issues/1649 は詳細の出力のみを修正しており、一覧の出力の修正を含んでいませんでした。

**Comment by masao** [comment]
修正を確認したのでクローズします
![image](https://github.com/next-l/enju_leaf/assets/38825/9b8aa04a-81cc-4564-b208-451ccc8b4c25)
