### ISSUE TITLE
NDLサーチインポートが動作しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#1846]
https://ndlsearch.ndl.go.jp/news/renkei_20240105
NDLサーチとNDLオンラインの統合にともない、APIエンドポイントが変更になっているからか、ISBNインポート・検索インポートともに動作しなくなっているようです。

**Comment by nabeta** [comment]
@masao NDLサーチのAPIの動作が変わっているようです。以前は以下のURLで書誌事項が取得できていたのですが（[テストコード](https://iss.ndl.go.jp/api/sru?maximumRecords=1&onlyBib=true&operation=searchRetrieve&query=(itemno=R100000002-I000010980901-00)&recordSchema=dcndl)）、
https://iss.ndl.go.jp/api/sru?maximumRecords=1&onlyBib=true&operation=searchRetrieve&query=(itemno=R100000002-I000010980901-00)&recordSchema=dcndl

ホスト名を変え、itemnoの末尾の00の有無を変更したのですが、いずれもRecord does not existエラーになります。
https://ndlsearch.ndl.go.jp/api/sru?maximumRecords=1&onlyBib=true&operation=searchRetrieve&query=(itemno=R100000002-I000010980901-00)&recordSchema=dcndl
https://ndlsearch.ndl.go.jp/api/sru?maximumRecords=1&onlyBib=true&operation=searchRetrieve&query=(itemno=R100000002-I000010980901)&recordSchema=dcndl

同じCQLでもISBNの指定では結果が帰ってくるので、itemnoの指定の問題のように見えますが、まだ原因がつかめていません。
https://ndlsearch.ndl.go.jp/api/sru?operation=searchRetrieve&recordSchema=dcndl&maximumRecords=1&query=(isbn=978-4-8399-3199-5)

**Comment by nabeta** [comment]
NDLに問い合わせたところ、itemnoには「（リポジトリ番号-アイテム番号）」のうちの「アイテム番号」を指定するとの回答がありました。ただ実際に指定するのは、`R100000002-I000010980901`のうち`I000010980901`から、さらに先頭のIを削除した`000010980901`となるようです。
https://ndlsearch.ndl.go.jp/api/sru?maximumRecords=1&onlyBib=true&operation=searchRetrieve&query=(itemno=000010980901)&recordSchema=dcndl

これはNDLサーチの詳細画面で「国立国会図書館書誌ID」として表示されている番号なのですが、APIドキュメントになぜそう書いていないのかはよくわかりません。
https://ndlsearch.ndl.go.jp/books/R100000002-I000010980901

また、現時点では`onlyBib=true`パラメータを指定しても、レスポンスに所蔵情報が含まれています。この点について、追加でNDLに問い合わせています。

**Comment by nabeta** [comment]
上記の動作はいずれも不具合で、修正予定とのこと。
https://ndlsearch.ndl.go.jp/news/renkei_20240105#sec5-2

> 修正予定の実装
　itemnoとして「リポジトリ番号-アイテム番号」を指定
https://ndlsearch.ndl.go.jp/api/sru?operation=searchRetrieve&version=1.2&query=itemno=R100000049-I032691189

> 現在、SRUのonlyBibの指定に不具合があることを確認しています。
onlyBibの指定によって書誌情報のみが取得できるよう修正を予定しています。

**Comment by nabeta** [comment]
1月21日の開発ワークショップで、ひとまずNDLサーチの対応を待つこととした。

**Comment by nabeta** [comment]
1月31日にこれらの不具合は修正済みとのことなので、これからEnju側の修正に入ります。
https://ndlsearch.ndl.go.jp/news/renkei_20240105#sec5-2

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/pull/1854, https://github.com/next-l/enju_leaf/pull/1857, https://github.com/next-l/enju_leaf/pull/1859 で対応済みのため、クローズします。
