### ISSUE TITLE
NDLサーチ検索によるインポートで図書資料以外の書誌がインポートできない

### ISSUE THREAD

**Issue by haruka8307** [next-l/enju_leaf#1858]
いうもお世話になっております。
1.4.4公開後にNDLサーチ検索によるインポート機能を試してみたところ，
逐次刊行物や視聴覚資料など図書以外の書誌データがインポートできなくなっているようです。

例えば雑誌であればタイトルの他にISSNや全国書誌番号などで検索しても検索に引っかからず検索件数0件となってしまう。
視聴覚資料の場合も同様でタイトルや発売番号などで以前は検索→インポートできていたのですが，現時点では検索に引っかからないのでインポートができない…といった具合です。

図書以外の資料を登録するときに便利に使わせていただいている機能なのでできれば修正していただけると助かります。
どうぞよろしくお願いいたします。

**Comment by nabeta** [comment]
@haruka8307 これはNDLサーチの`mediatype`の仕様変更によるもので、`mediatype=1`を指定していた部分を`mediatype=book`に置き換えているのですが、おそらく`mediatype=periodical`にする必要があるのだと思います。
https://ndlsearch.ndl.go.jp/news/renkei_20240105#sec5-1

仕様書だと`mediatype`は複数指定できそうなので、ちょっと見てみます。

**Comment by nabeta** [comment]
@haruka8307 NDLサーチの検索時のmediatypeに、books, periodicals, video, audio, scoresを指定するようにしました。以下は動作の例です。

![image](https://github.com/next-l/enju_leaf/assets/11428/b57e2c66-65af-4149-88be-03d88249372c)

electronicやonlineは何が入っているかまだ見てないのですが、今までに登録したものでそれらに該当しそうなものはありますでしょうか。

**Comment by haruka8307** [comment]
@nabeta
ありがとうございます。
1.4ブランチを更新して試してみましたが自分の環境では取得できませんでした。
（動作デモでも同様です）
mainブランチの方で試してみた方がいいでしょうか。
![スクリーンショット 2024-02-17 211157](https://github.com/next-l/enju_leaf/assets/90094824/2cacdfc0-cb16-4fe7-a46b-db5dc8045308)

ちなみにこれまでNDLサーチから登録した資料でelectronicやonlineに該当しそうなものはありません。

**Comment by haruka8307** [comment]
@nabeta 
さきほど1.4ブランチを更新して試してみたところ自分の環境でも検索して書誌をインポートできることを確認しました。
ご対応いただきありがとうございました。

> NDLサーチの検索時のmediatypeに、books, periodicals, video, audio, scoresを指定するようにしました。

リニューアル前のNDLサーチでどこまでカバーしていたのかは把握していないのですが，
おそらくこれだけ対応していれば十分かなと思います。
他にあるとしたら地図 …mapsかなと思ったものの…自分が使う上では登録することはあまりなさそうです。

それから一連のやりとりの過程で気づいたのですが，NDLサーチ検索によるインポート画面の右上にある
「[同じ検索語でNDLサーチを検索する」のリンクが機能していないようです。
特に困る…というほどではないかもしませんが…とりあえずご報告まで。

**Comment by nabeta** [comment]
> それから一連のやりとりの過程で気づいたのですが，NDLサーチ検索によるインポート画面の右上にある
「[同じ検索語でNDLサーチを検索する」のリンクが機能していないようです。

@haruka8307 https://github.com/next-l/enju_leaf/pull/1864 で修正しました。1.4ブランチに反映済みです。

なお、資料の検索結果が0件だった場合のリンクは、手動で修正する必要があります（新規インストールについては修正済み）。`/search_engines`からNDLサーチを選び、「編集」で以下のように入力してください。

* URL: https://ndlsearch.nims.go.jp
* ベースURL: https://ndlsearch.ndl.go.jp/search
* クエリパラメータ: `keyword`
* 追加のパラメータ:
    ```
    cs=bib
    f-ht=ndl
    display=panel
    ``` 

![image](https://github.com/next-l/enju_leaf/assets/11428/1f799365-0ffe-4753-873a-732bda107434)

**Comment by haruka8307** [comment]
@nabeta
ありがとうございます。
こちらの環境でも正しく動作することが確認できました。
検索エンジンの設定についてもありがとうございました。
