### ISSUE TITLE
main(1.5)での貸出処理のときに画面遷移してしまう。

### ISSUE THREAD

**Issue by shin1kt** [next-l/enju_leaf#1860]
## 概要

main(1.5)を使ってみていますが、貸出処理のときに画面遷移してしまいます。

- 貸出資料の新規作成画面で所蔵資料IDを入力して[読み込み]をクリック（もしくはEnterキー）を押すと、[貸出資料の一覧]という画面に遷移してしまいます。
- ブラウザバックを押すと「貸出資料の新規作成」画面に戻り、資料も読み込まれた状態になっています。
- バージョン1.4では、画面遷移せずにそのまま資料が読み込まれました。

こちらは不具合でしょうか。それとも仕様であり、当方の操作方法などの問題でしょうか。

## 画面
<img width="600" alt="image" src="https://github.com/next-l/enju_leaf/assets/10617182/56992608-ae72-4903-96c3-563f1dd15edb">

↓
画面遷移が発生してこの画面になります。

<img width="600" alt="image" src="https://github.com/next-l/enju_leaf/assets/10617182/7062024f-e691-4f48-8a72-0534a2d79b0c">

↓

ブラウザで戻ると資料が読み込まれた状態のまま戻ります。
<img width="600" alt="image" src="https://github.com/next-l/enju_leaf/assets/10617182/f36ae8ef-262f-4d2a-8cf3-d2f734bc13aa">

**Comment by nabeta** [comment]
@shin1kt お知らせありがとうございます。別ブランチで修正したので、試してみていただけますでしょうか。
https://github.com/next-l/enju_leaf/tree/fix-checked-item-form

**Comment by shin1kt** [comment]
@nabeta 
ありがとうございます。
修正いただいたブランチで正しく動作することを確認できました。

ただ、今度は（ひょっとしたら前からかもですが）、所蔵情報の新規作成画面から、作成ボタンをおしたときに元の画面に遷移しなくなりましたのでご報告しておきます。

<img width="600" alt="image" src="https://github.com/next-l/enju_leaf/assets/10617182/0f63fdd3-fa25-4878-ae41-f8c4da4dc388">

**Comment by nabeta** [comment]
@shin1kt こちらもひとまず修正しましたので、同じブランチでgit pullしたあと、以下のコマンドを実行して、コンテナを再起動してみていただけますか。

```sh
docker compose run --rm web rake assets:precompile
```

**Comment by shin1kt** [comment]
@nabeta 

ありがとうございます。
何度もすみません。

修正いただいたブランチを最新にしたうえで、教えていただいたコマンドを実行したのですが
```
Could not find pg-1.5.5, dotenv-rails-3.0.1, nori-2.7.0, dotenv-3.0.1 in locally installed gems
```
というエラーが出て終了してしまいました。
gemのライブラリなどが足りていないのかと思い、docker compose build で環境を再構築してみました。

すると、コマンドの実行はできたのですが、画面遷移の問題は解決していませんでした。

また、上記コマンドの際に、以下のようなログが出ました。

```
Sprockets::FileNotFound: couldn't find file 'mirador/dist/mirador.min' with type 'application/javascript' (Sprockets::FileNotFound)
Checked in these paths: 
  /enju/app/assets/config
  /enju/app/assets/images
  /enju/app/assets/javascripts
  /enju/app/assets/stylesheets
  /enju/vendor/assets/javascripts
  /enju/vendor/assets/stylesheets
  /usr/local/bundle/gems/jquery-rails-4.6.0/vendor/assets/javascripts
  /usr/local/bundle/gems/cocoon-1.2.15/app/assets/javascripts
  /usr/local/bundle/gems/jquery-ui-rails-4.2.1/app/assets/images
  /usr/local/bundle/gems/jquery-ui-rails-4.2.1/app/assets/javascripts
  /usr/local/bundle/gems/jquery-ui-rails-4.2.1/app/assets/stylesheets
  /usr/local/bundle/gems/actiontext-7.0.8/app/assets/javascripts
  /usr/local/bundle/gems/actiontext-7.0.8/app/assets/stylesheets
  /usr/local/bundle/gems/actioncable-7.0.8/app/assets/javascripts
  /usr/local/bundle/gems/activestorage-7.0.8/app/assets/javascripts
  /usr/local/bundle/gems/actionview-7.0.8/lib/assets/compiled
  /enju/node_modules
 ```

miradorが無いというエラーのようなので、今回の現象とは関係なさそうですが念の為報告いたします。

**Comment by nabeta** [comment]
@shin1kt お手数をおかけして申し訳ありません。JavaScriptの読み込み方法を修正したので、もう一度試していただけますでしょうか。

```sh
git pull
docker compose build
docker compose run --rm web yarn install
docker compose run --rm web rake assets:precompile
```

**Comment by shin1kt** [comment]
こちら、連絡が遅くなって申し訳ございませんでした。
不具合解消確認しております。（マージされたようですが、念の為報告でした。）
