### ISSUE TITLE
新方式で作成したマニュアルのPDFがAdobe Acrobatでは埋め込みフォントが読めない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1870]
以下のようなメッセージがでて、歯抜けのように表示される。
![image](https://github.com/next-l/enju_leaf/assets/1328499/198a9043-4ee3-4752-a69b-2b3f14ba5357)

例：

![image](https://github.com/next-l/enju_leaf/assets/1328499/087d8956-622a-48d6-9434-1cd444eb7766)

**Comment by yegusa** [comment]
どうやら、かなずなるわけではなく、ならない環境もあるらしい。

**Comment by yegusa** [comment]
Chromeの内臓のPDFビューアなら大丈夫。この現象はAdobe Acrobatのみ。

**Comment by yegusa** [comment]
これの問題らしい

https://community.adobe.com/t5/acrobat%E3%83%95%E3%82%A9%E3%83%BC%E3%83%A9%E3%83%A0-discussions/%E7%89%B9%E5%AE%9A%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E9%96%8B%E3%81%8F%E3%81%A8-%E3%83%95%E3%82%A9%E3%83%B3%E3%83%88%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%8C%E7%99%BA%E7%94%9F%E3%81%97%E4%B8%80%E9%83%A8%E3%81%AE%E6%96%87%E5%AD%97%E3%81%8C%E6%AD%A3%E3%81%97%E3%81%8F%E8%A1%A8%E7%A4%BA%E3%81%95%E3%82%8C%E3%81%AA%E3%81%84-acrobat/td-p/4788602?profile.language=ja

**Comment by yegusa** [comment]
環境によっては（少なくとも私の環境では）、Chromeの内臓のPDFビューアでもだめでした！

**Comment by yegusa** [comment]
回避策:

1. Google ChromeにてPDFを閲覧します。
2.  右クリックし、「Adobe Acrobat」もしくは印刷＞Adobe PDFからPDFを再作成します

これで回避されることがわかりました。
注：環境によっては、Gooogle Chromeでもうまく見れないものもあるようなので、ちゃんとみれる環境でやること。

**Comment by yegusa** [comment]
ひとまず：回避策をもちいて、PDFの再作成をおこなって、再度、Githubにアップロードするとことでたちまちの対策をすることにする。

できれば将来的には、フォントを指定するなどして、ちゃんとみれるPDFをつくるなどしたい。

**Comment by yegusa** [comment]
他試してみること：asciidocのバージョンを下げてみる、などでいけるかもしれない？

**Comment by masao** [comment]
https://github.com/next-l/documentation/commit/72d940d6e1a5883427fa8dc4a06c965362efdeb7 asciidoctor-pdf のバージョンを上げたら、問題が解消されたようです。

**Comment by yegusa** [comment]
確認しましたのでクローズします
