### ISSUE TITLE
所蔵冊数の整合性

### ISSUE THREAD

**Issue by t-machii** [next-l/enju_leaf#1871]
お世話になっております。現在、1.4.6を稼働させてみています。

システムの設定　内、図書館の情報の中で　地図　職員　本棚　開館日と催し物　システムの設定　のタブがあります。
この本棚の項目で、本棚毎の所蔵冊数が出るのですが、実際の冊数と会わない現象があります。
私の場合は実際の所蔵よりもはるかに多い数字が出てきてしまいました。

試しに、デモンストレーションサーバでエクスポートし、所蔵の結果を見ると、やはり本棚ごとの冊数と合わないように思います。
https://enju.next-l.jp/libraries/yours

何か見落としであれば申し訳ございませんが、宜しくお願い申し上げます。

**Comment by nabeta** [comment]
@t-machii お知らせありがとうございます。以前、この冊数は`counter_cache`オプションによってキャッシュされていたのですが、現在はこれを使わなくなっています。しかし、冊数表示は`counter_cache`を使っていたときのままになっているため、実際の冊数と合わなくなっていました。
https://railsguides.jp/association_basics.html#belongs-to%E3%81%AE%E3%82%AA%E3%83%97%E3%82%B7%E3%83%A7%E3%83%B3-counter-cache

https://github.com/next-l/enju_leaf/pull/1872 で修正し、次のリリースに反映させる予定です。

**Comment by t-machii** [comment]
@nabeta
お返事ありがとうございました。
いつも精力的な更新、感謝しております。
本件クローズさせていただきます。
