### ISSUE TITLE
著者の名前に生年が入る

### ISSUE THREAD

**Issue by scrwnl** [next-l/enju_leaf#1874]
v1.4.6のISBN入力で本をインポートすると、著者名に~~カンマや~~著者の生年が入ります (生年
は入らないこともあります)。
また、編集画面から修正しようとすると409エラーが発生します。
![image](https://github.com/next-l/enju_leaf/assets/63852665/37294b14-c8c6-4641-9908-1ed26717eef8)

**Comment by scrwnl** [comment]
訂正：カンマは著者標目の仕様でした。

**Comment by nabeta** [comment]
> また、編集画面から修正しようとすると409エラーが発生します。

@scrwnl 気づくのが遅れて申し訳ありません。こちら、デモサーバでも再現しますでしょうか。
https://enju.next-l.jp/

**Comment by scrwnl** [comment]
デモサーバーで同じ操作をすると成功しました。しかし、手元の環境(v1.4.7)で操作するとHTTP Error 429が出ます。
