### ISSUE TITLE
redisの役割について

### ISSUE THREAD

**Issue by shin1kt** [next-l/enju_leaf#1878]
@nabeta 
初歩的な質問ですみません。enjuをGCP上に構築したいと思っており、各コンテナの役割を調べているのですが、redisは、どのようなことに使用していますか？
具体的には、Memorystore for Redis で代用ができるか検討しております。

**Comment by nabeta** [comment]
@shin1kt Redisは、TSVインポートなどの非同期処理に使用しています。    
https://railsguides.jp/active_job_basics.html
https://github.com/resque/resque

GCPは経験がないのですが、Memorystore for Redisはデータの永続化が行われないとドキュメントにあり、インポートが失敗したときなどの情報が残らないかもしれません。

なお、現在のDocker版では使用していませんが、Redisはキャッシュの保存先に使用することもできます。  
https://railsguides.jp/caching_with_rails.html#activesupport-cache-rediscachestore

**Comment by shin1kt** [comment]
@nabeta 
ご丁寧な回答ありがとうございます。なるほどインポートが失敗して接続が切れたときに問題がでるかもしれないということですね。いただいたヒントを元に調査して判断していきたいと思います。

> Redisはキャッシュの保存先

ちなみに
```
docker compose run --rm web bundle exec rake sunspot:reindex
````
sunspotのreindexをするときにredisコンテナが起動しているようですが、solrのキャッシュをredisに保存しているというわけではないのでしょうか。

**Comment by shin1kt** [comment]
すみません。

**Comment by shin1kt** [comment]
すみません。webのdepends onにsolrが設定されているから起動しているだけで、sunspotと関係しているわけではないですね。失礼しました。

**Comment by nabeta** [comment]
@shin1kt Redisに保存されるキャッシュは、HTMLの一部になります。
https://railsguides.jp/caching_with_rails.html#%E3%83%95%E3%83%A9%E3%82%B0%E3%83%A1%E3%83%B3%E3%83%88%E3%82%AD%E3%83%A3%E3%83%83%E3%82%B7%E3%83%A5

**Comment by shin1kt** [comment]
@nabeta 
ありがとうございます。キャッシュについては引き続き確認して理解を深めたいと思います。
質問の意図としては返答いただけましたのでコメントを閉じさせていただきます。
