### ISSUE TITLE
インポート時の原題にダブルクォーテーション

### ISSUE THREAD

**Issue by t-machii** [next-l/enju_leaf#1879]
お世話になっております。

テキストで流し込む際に　original_title　にダブルクォーテーション　"　“　”　が含まれると　失敗　となる様子です。
同様の書籍をNCIDでインポートした場合には問題が起きませんでした。
恐れ入りますが、宜しくお願い申し上げます。

**Comment by t-machii** [comment]
なお、バージョンは1.4.6で、デモンストレーションサーバでも同様の現象を確認しております。

**Comment by nabeta** [comment]
@t-machii 参考までに、TSVファイルはどのソフトウェアで作成されていますでしょうか。

**Comment by t-machii** [comment]
@nabeta お返事ありがとうございます。
windowsのnotepadで作成しておりました…（スプレッドシートで編集したものを貼付け）

本件とはちょっとまた別件なのですが、tsvで入れられなかった書誌をNCIDなどで個別取得（まだ1.46を使用しているため）し、所蔵情報の新規作成をした際に　貸出区分　を変更できない現象がございました。（再度編集時には可能）
恐れ入りますがよろしくお願い申し上げます。

**Comment by t-machii** [comment]
改めて、スプレッドシートのエクスポートでtsvにした場合、同様にエラーでした。excelでタブ区切りのtxtで出力すると正常にインポートできました。
ダブルクォーテーション　"　“　”　が含まれると　失敗　となる　は間違いでした。
申し訳ございません。
