### ISSUE TITLE
定期刊行物の個別資料の書誌画面について

### ISSUE THREAD

**Issue by haruka8307** [next-l/enju_leaf#1880]
お世話になっております。
定期刊行物を登録していて気づいたのですが
個別資料の書誌を開いた際に表示される「この著作を含む資料」というタブについて
ログインしていない状態，またはUser権限のユーザでログインしているときに開くと
親書誌へのリンク（→登録済の巻号一覧）が表示されますが
Librarian権限以上のユーザでログインしている場合には何も表示されないようです。
（手元の1.4.7，デモサーバともに同様です）

https://enju.next-l.jp/manifestations/2482

お手数をおかけしますがご確認いただけるでしょうか。
よろしくお願いいたします。

**Comment by nabeta** [comment]
@haruka8307 お知らせありがとうございます。
テンプレートの読み込みに誤りがありました。次のリリースで修正します。

**Comment by haruka8307** [comment]
@nabeta 
ありがとうございました。
手元の環境でもリンクが表示されるようになりました。
