### ISSUE TITLE
新マニュアルのPDFのセクション階層が一段低い（目次も含む）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1903]
#1787 に関連

新マニュアルで
https://next-l.github.io/documentation/1.4/

新マニュアルのPDFのセクション階層が一段低い（目次も含む）

少なくとも、インストールマニュアルで現象を確認しました。

PDFの目次
1. Enju概要
2. 概要
3. Dockerについて
4. インストールの流れ
5. 動作環境を確認する
6. Dockerのダウンロードとインストール
7. ・・・・

となっていますが、正しくは、

正しい：
第1章 Enju概要
　Enju概要
第2章 Enjuを動作させる方法
　概要
第3章 動作環境の確認とDockerのインストール
　動作環境を確認する
　Dockerのダウンロードとインストール
第4章 Enjuのインストール
　Enjuの入手
　Dockerの起動
　Enjuの起動確認
　Enjuサーバの停止と再起動
第5章 モジュールの追加
第6章 検索エンジンの設定
第7章 他のコンピュータからの利用設定
第8章 Enjuのアップデート
第9章 データのバックアップ
第10章 その他（カスタマイズなど）
第11章 トラブルシューティング

なので、一階層おかしい。

**Comment by yegusa** [comment]
- x ：インストール
- 〇：初期設定
- ×： 運用マニュアル
- 〇：利用者
- 〇：WebAPI

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
- インストール：〇
- 初期設定：〇
- 運用マニュアル：×　なんか変　1章しかない、一個づらしたとしても30章もあるのはおかしい
- 利用者：〇
- WebAPI：〇

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
- インストール：〇
- 初期設定：〇
- 運用マニュアル：〇
- 利用者：〇
- WebAPI：〇

問題ないことを確認しましたのでクローズします。
