### ISSUE TITLE
新マニュアルPDF版：「画像のデータに不足があります」というエラー

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1907]
https://github.com/next-l/enju_leaf/issues/1787 に関連

新マニュアルで
https://next-l.github.io/documentation/1.4/

インストールマニュアルのPDF版をひらくと

「画像のデータに不足があります」というエラーがでます。

```md
**本マニュアルでは、「2. Dockerを用いる方法」について述べます。**

まず、第4章において、簡便にNext-L Enjuを利用する手法として、１台のコンピュータ上のみでNext-L Enjuを利用する(同じコンピュータ上でサーバとクライアントの両方を動作させる)方法について述べます。もちろん、使用するコンピュータはデスクトップではなくノートブックでも問題ありません。 

image::../assets/images/1.1/image_install_000.png[1台のコンピュータでEnjuを動作させる]
```

この画像がでてないっぽい

**Comment by masao** [comment]
出力可能な画像とそうでない画像との比較をしているうちに、PNGの色ビット数に違いがあることが分かりました：

* 出力できない： image_install_001.png: PNG image data, 827 x 692, 8-bit/color RGBA, non-interlaced
* 出力できる： image_install_002.png: PNG image data, 480 x 360, 16-bit/color RGB, non-interlaced

つまり、8bit色のPNG画像は出力できないようでした。
あらためてAsciidoctor-pdfのヘルプを検索してみると、

> In rare cases, GraphicsMagick (the backend library for prawn-gmagick) can misread the bit depth of certain PNG images. If this happens, you can instruct Asciidoctor PDF to not delegate to GraphicsMagick.

https://docs.asciidoctor.org/pdf-converter/latest/image-paths-and-formats/#unregister-prawn-gmagick

つまり、稀にPNG画像をダウングレード処理する際に失敗する画像があるとのことでした。
このヘルプのよれば、` -r asciidoctor/pdf/nogmagick  ` のオプション付きで実行すればよいとのこと。

**Comment by yegusa** [comment]
エラーが表示されない、画像が表示された　のを確認しましたのでクローズします。
