### ISSUE TITLE
バージョン 1.4.8 で502 Bad Gateway がでます。

### ISSUE THREAD

**Issue by impacthubkyoto** [next-l/enju_leaf#1913]
マニュアル通りにDebianとWSL2をインストールし、コンテナを立ち上げたところ以下のようなエラーが出ました。
対処法を教えていただきたいです。

 ```
        5: from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         4: from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
         3: from /enju/config/environments/production.rb:3:in `<main>'
         2: from /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `configure'
         1: from /usr/local/bundle/gems/railties-6.1.7.8/lib/rails/railtie.rb:234:in `instance_eval'
/enju/config/environments/production.rb:120:in `block in <main>': undefined method `to_sym' for nil:NilClass (NoMethodError)
```

**Comment by nabeta** [comment]
@impacthubkyoto `.env.template`は`.env`にコピーしていますでしょうか。コピーしている場合、以下のコマンドを実行して、出力される内容を教えていただけますか。

```sh
docker compose run --rm web bin/rails r "puts ENV['ENJU_LEAF_ACTION_MAILER_DELIVERY_METHOD']"
```

**Comment by impacthubkyoto** [comment]
末尾に以下のエラーが出力されます。

`/enju/app/models/oai_provider.rb:3:in `<class:OaiProvider>': undefined method `display_name' for nil:NilClass (NoMethodError)`

**Comment by nabeta** [comment]
@impacthubkyoto https://github.com/next-l/enju_leaf/issues/1911#issuecomment-2310496692 と状況が似ていますね。新規インストールであれば、 https://github.com/next-l/enju_leaf/issues/1911#issuecomment-2310517262 の手順を試していただけますか。

**Comment by nabeta** [comment]
なお、こちらのローカル環境では不具合を再現できていません。

**Comment by impacthubkyoto** [comment]
解決いたしました！ありがとうございます。

**Comment by nabeta** [comment]
複数の環境で同様の例が起きているのが気になりますが、とりあえずクローズします。
