### ISSUE TITLE
新マニュアル：「WebAPIマニュアル」リンクが二重にでている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#1916]
一つよけいな「WebAPIマニュアル」リンクがある
https://next-l.github.io/documentation/1.4/

赤四角のほうは削除したほうがよい
![image](https://github.com/user-attachments/assets/615e2802-97f3-4aa6-91a7-71b6da773733)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
修正を確認できたのでクローズします。
