### ISSUE TITLE
Bootstrapの導入

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#258]
現在のNext-L EnjuのHTMLやCSSは自前で書いていますが、これをBootstrapに切り替えてはどうかと考えています。以前にBootstrapを試したことがありますが、改めて提案です。
http://getbootstrap.com/

直接的な理由としては、現在メニューで使用しているjQuery UIのMenubarウィジェットの開発が止まってしまったというのがあります。ただ、Bootstrapは広く使われているフレームワークであり、すでに開発済みのBootstrapのテーマを採用してデザインを変更できる、また他の開発者がEnjuのカスタマイズに着手するのにとっつきやすい、というメリットは大きいのではないかと思います。

もちろん、現在のHTMLとの互換性や、「ほかのサイトと同じようなデザインになって逆にかっこ悪い」という問題もあるため、すぐには進めないつもりです。ご意見をいただければと思います。

**Comment by nabeta** [comment]
現在は1.1系と1.2系を平行して開発していますが、1.2系はもう切り替えたいと思います。
ドロップダウンメニューやタブが書きやすいので。
http://getbootstrap.com/components/#dropdowns

**Comment by yegusa** [comment]
2015-04-25 のWSでもためしにやってみました

**Comment by nabeta** [comment]
（転記）Bootstrap4でモックを作ってみる。

- [ ] トップページ
- [ ] 資料一覧
- [ ] 資料詳細

メニューの表示をどうしよう？

**Comment by nabeta** [comment]
第85回のワークショップ（2020年1月11日）で、Bootstrap4化は2.0で進めることとした。

**Comment by nabeta** [comment]
現状のモックアップに対して出ている案:

- メニューとヘッダの色を変える機能はそのまま引き継ぐ
- 画面左上は1.3では文字と画像が両方入るようになっているが、現在のモックでは画像は入らない。両方入れるようにするか、それとも画像（Enjuくん）はフッタに移動するか？

**Comment by nabeta** [comment]
作業は #1437 で行うこととして、こちらはクローズします。
