### ISSUE TITLE
Gem 側からEnjuのメニューに動的に追加したい。

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#278]
（第２９回ワークショップで上がっていた検討事項を issue としてあげます。）

Gem 側からEnjuのメニューに動的に追加したい。

事前にenju_leaf のメニューに、Gemで追加した機能のエントリーポイントを記載しておき、Gemのモジュール定数が存在するかによって表示非表示をコントロールしている。

この方法だと、Gem 新規作成時にメニューの実装を変更してもらう必要がある。
例えば、Gem enju_loc  を新規で開発し、画面のメニューに追加する場合は、enju_leaf の開発者である田辺さんに追加を依頼する必要があります。またGemによっては、必ずしも全員が必要が無い場合もあるかと思います。

これを Gem の登録時にGem側から動的に追加すると便利です。

実装ですが、例えば、メニュー表示用の変数を用意しておき、Gem 側の lib/<Gem名>/menu_config.rb を追加し、レンダリング時には、このメニュー表示用の変数を使います。

必ず表示する領域で、権限によっても、表示が変わりますので、速度的なことも考慮して検討する必要があるかと思います。

**Comment by nabeta** [comment]
1.4系では、各機能をgemで追加する形をやめて直接アプリケーションに追加する形になっているため、クローズします。
