### ISSUE TITLE
バグ：パスワードの自動生成が行われません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#294]
「パスワードの自動生成」にチェックをいれて更新するボタンを押しても、
自動生成したパスワードが表示されません
デモサーバーで現象を確認しました。

![pass](https://cloud.githubusercontent.com/assets/1328499/3909408/537dc40e-230d-11e4-9cf4-11f5536925fa.png)
![pass2](https://cloud.githubusercontent.com/assets/1328499/3909410/56307c46-230d-11e4-9743-1556a2814135.png)

**Comment by masao** [comment]
また同じ現象が発生しています。リセット後のパスワードが表示されません。再オープンします。

**Comment by nabeta** [comment]
1.1.10.rc17で再発したもので、修正済みです。

**Comment by yegusa** [comment]
再発しないようにテストを書いとけませんかね。。。

とりあえず、できることを確認しましたので、クローズします。
![image](https://cloud.githubusercontent.com/assets/1328499/5691015/ff864a2a-98f4-11e4-99ea-c89983cc7f8a.png)
