### ISSUE TITLE
書誌データに目次フィールドを追加

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#296]
書誌データに目次データを入力できるフィールドがあるとうれしいと思いました。

enju_locですと、多くの書誌レコードに目次データが埋め込まれていますが、これを活用できるとうれしいかな、と思います。descriptionに包摂させてもよいのですが、目次とは別に mods:abstract/summary があるので、別に記録できるとうれしいシーンもあるかなと思いました。
※優先順位は低でかまいません。

**Comment by nabeta** [comment]
現状でも実はabstractはデータベース上に存在するのですが、これを使うのでよいでしょうか。
https://github.com/next-l/enju_biblio/blob/1.2/db/migrate/20091012101112_add_dcndl_schema.rb#L6

**Comment by masao** [comment]
そうですね、ひとまず abstract にいれていきましょうか。
#650 の内容細目もここに入れればよいかなと。

**Comment by masao** [comment]
こちら checking になっていますが、表示・編集機能が存在しないようです。

**Comment by nabeta** [comment]
1.3系に追加しました。

![image](https://user-images.githubusercontent.com/11428/82138619-c6ec2780-985c-11ea-9e86-1b5d08f66af9.png)

![image](https://user-images.githubusercontent.com/11428/82138624-d23f5300-985c-11ea-939b-616b28cdcd68.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/87870232-f9430e00-c9e0-11ea-990f-a72574af1053.png)

**Comment by yegusa** [comment]
デモサーバーでためしたが、TSVエクスポートはされていなかった。
TSVインポートはためしていないができないよね？
