### ISSUE TITLE
バグ：librarian権限以上のログインユーザの購入一覧に自身の登録した購入リクエストしか表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#324]
バグ？：librarian権限以上のログインユーザの購入一覧に自身の登録した購入リクエストしか表示されない

http://enju.next-l.jp/purchase_requests

自分の購入リクエストしか一覧されないのでは、
発注業務ができないきがします。

例えば、
* admin: 購入リクエストを3件登録している
* librarian: 購入リクエストは登録していない
* user0816 購入リクエストを1件登録している

という場合の現在の状況と、理想的な振る舞いです。

a) ログインユーザ：admin
---------------------------

現在：adminが登録した3件のみが表示されている。
理想：4件表示する。全てのユーザのリクエストを表示する
![admin](https://cloud.githubusercontent.com/assets/1328499/3941362/27cced62-2524-11e4-8ff6-42374df25748.png)

b) ログインユーザ：librarian
-------------------------------

現在：なにも表示されていない、librarianが登録したもののみが表示されている。
理想：4件表示する。全てのユーザのリクエストを表示する
![librarian-1](https://cloud.githubusercontent.com/assets/1328499/3941361/2347a23c-2524-11e4-9681-4be2cc29ff09.png)

c) ログインユーザ：user0816
-----------------------------------

現在：自分が購入リクエストしたものだけが表示　→　理想どうり。
理想：自分が購入リクエストしたものだけが表示
![user0816](https://cloud.githubusercontent.com/assets/1328499/3941360/1eaf9a7c-2524-11e4-80c8-6069e7fbae39.png)

- [ ] 確認
- [ ] マニュアル修正

**Comment by nabeta** [comment]
Librarian権限以上でログインしている場合、すべての購入リクエストを表示するようにしました。1.1.2/1.2.0で反映されます。
http://dev.next-l.jp/purchase_requests

**Comment by masao** [comment]
修正を確認したのでクローズします。
