### ISSUE TITLE
LC検索：Content type/Carrier typeの変更への対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#328]
#300 #302 において導入された資料の内容種別と資料の形態に、LC検索インポートを対応させる。

**Comment by masao** [comment]
昨年8月時点のコミットで対応済みです。
cf. https://github.com/masao/enju_loc/commit/9a753c726c703633a51d07842d726328d264dde7

![20150418-enju_leaf_118_ advanced topics in information retrieval next l enju leaf](https://cloud.githubusercontent.com/assets/38825/7214691/e9078c9c-e5f1-11e4-962b-2343363d77c1.png)

**Comment by yegusa** [comment]
できているようなのでクローズします。
