### ISSUE TITLE
要望：manifestation_identifier　を資料の表示と入力フォームに表示してほしい（Librarian権限以上） 

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#372]
manifestation_identifierは入力者が明示的に指定できる書誌IDです。
（manifestaion_idはrailsが自動付与するid（連番）のため利用者が明示的に付与不可）

現在、TSVインポートやNDLサーチからのインポートでのみ入力できるようになっていますが、
利用者インタフェースで、表示や入力ができないため、利用者が認知できない入力項目となっています。

ですから、少なくともlibrarian権限以上で、このmanifestaion_identifierを、

* 資料の表示
* 書誌の編集画面へ入力フォーム

に追加する必要があります。

**Comment by nabeta** [comment]
フォームと表示を追加しました。また、項目名を「ローカル識別子」としました。
管理用のIDを想定しているため、Librarian権限以上での表示としています。
http://dev.next-l.jp/manifestations/4912

**Comment by masao** [comment]
ログアウトした状態でアクセスすると「500 Internal Server Error」になりますね。。。

**Comment by nabeta** [comment]
開発サーバに余分なファイルがあったのが原因でした。削除しました。

**Comment by masao** [comment]
1.1系は enju_flower 側を優先読み込みしているので、そちらにコミットしないと動作確認できないですね。

**Comment by nabeta** [comment]
そういえばそうでした。1.1系もenju_flowerを外してもよいかもしれません。

**Comment by masao** [comment]
enju_flowerをはずしてしまうのは大きな変更なので悩ましいです。1.1系の正式リリースをしてしまって、新しい機能追加の開発リソースを原則1.2系にうつしたほうが筋は良い気がしますね。

**Comment by nabeta** [comment]
enju_flowerに変更を反映しました。
http://dev.next-l.jp/manifestations/4912

**Comment by yegusa** [comment]
開発サーバーでできることを確認しましたので、クローズします。

表示： http://dev.next-l.jp/manifestations/4916
![image](https://cloud.githubusercontent.com/assets/1328499/8266188/5418ae32-175a-11e5-97b8-f08b525af31b.png)

編集： http://dev.next-l.jp/manifestations/4916/edit
![image](https://cloud.githubusercontent.com/assets/1328499/8266190/82f30036-175a-11e5-94ee-bf9579af93d8.png)
