### ISSUE TITLE
ブラウザの検索バーにEnjuを登録したときにアイコンを載せてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#390]
#375 から派生しました

以下の、赤い四角部分に enjuのアイコンが欲しい
![image](https://cloud.githubusercontent.com/assets/1328499/4023175/a2eb8f2e-2b7a-11e4-819b-340f2c330611.png)

アイコンは作ります。どんなサイズのどんなファイルフォーマットのがいるの？ファビコン形式？

**Comment by nabeta** [comment]
OpenSearch XMLで、favicon.icoで指定されている画像を読み込むようにしました。これはenju_leaf-1.3.2には含まれておらず、1.3.3に含める予定です。
![image](https://user-images.githubusercontent.com/11428/56949732-97458100-6b6e-11e9-9efe-c806ef599be5.png)

デモサーバで試してみてください。
https://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2

**Comment by masao** [comment]
アイコンが表示されることを確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/63220939-6a27e780-c1cc-11e9-8d3b-ebb842ce114b.png)
