### ISSUE TITLE
要望　ファビコンを設定してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#391]
#390 に関連

Enjuにファビコンを設定してほしい。

**Comment by nabeta** [comment]
関連するのですが、スマートフォンやタブレットでWebサイトをホーム画面に追加するときに apple-touch-icon.png という画像が使われるそうで、これもなにかデフォルトの画像を用意するのがよいと思います。
http://web-tan.forum.impressrd.jp/e/2010/06/15/8178

**Comment by nabeta** [comment]
@yegusa enju_leaf-1.3.0で、デフォルトでEnjuくんが設定されるようになっていますが、closeでよいでしょうか。
https://github.com/next-l/enju_leaf/tree/master/app/assets/images/enju_leaf

**Comment by nabeta** [comment]
closeしておきます。

**Comment by yegusa** [comment]
注：1.3.0で実装済みだが，　1.3.2のマイルストーンしか残ってなかったので，1.3.2として置く。
