### ISSUE TITLE
MacOSX+Homebrewでのbundle時のnokogiriのインストールエラー

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#395]
Building nokogiri using packaged libraries.

libiconv is missing.  please visit http://nokogiri.org/tutorials/installing_nokogiri.html for help with installing dependencies.

*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

以上のlibiconv不足によるエラーですが、公式チュートリアル
http://nokogiri.org/tutorials/installing_nokogiri.html
で解決しませんでした。
以下の
http://qiita.com/t_732_twit/items/a7956a170b1694f7ffc2
で一応はインストールできたのでとりあえず報告します。

**Comment by nabeta** [comment]
すでに時間がたっていますのでcloseしますが、もし問題があるようでしたらreopenしてください。
