### ISSUE TITLE
例外通知メールを飛ばしつつ詳細なエラーメッセージを表示する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#40]
nabeta> 詳細なエラーメッセージを表示するような、カスタマイズしたエラー画面を作ることもできるのですが、そうすると例外通知が飛ばなくなってしまいます。別途やり方があると思うのですが、まだ調べている途中です。

エラー画面例：
Railsの標準エラー画面（以下のようなもの）が出る。
http://www.tkrb.jp/guide/500.png

**Comment by nabeta** [comment]
古いissueのため、クローズします。なおエラーの捕捉と通知は、exception_notification gemによるメール送信のほかに、SentryやDatadogのような外部ツールで管理することを想定しています。
https://sentry.io/welcome/
https://www.datadoghq.com/ja/product/
