### ISSUE TITLE
バグ：認証付きプロキシへの対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#402]
Ruby本体では open-uri へ環境変数経由での設定は非対応なため、個別にProxyの認証設定を追加する必要がある。
参考：https://bugs.ruby-lang.org/issues/4388

``` ruby
open( uri, :proxy_http_basic_authentication => [ proxy_uri, proxy_user, proxy_pass] )
```

※優先度は低でかまいません。

**Comment by yegusa** [comment]
@nabeta さんが、来月から確認できる環境ができるらしいので、確認してクローズしてください。

**Comment by nabeta** [comment]
この件ですが、上記の確認を行う環境が用意できなくなったため、現時点では確認できません。

**Comment by yegusa** [comment]
現在のステータス：

- ひきつづき、環境をお持ちでチェックしてくれる方の募集中

**Comment by yegusa** [comment]
確認環境がなく、確認しようがないので、一年以上たちましたし、いったん、クローズします。
該当の環境をお持ちのかたで、動かないというのが出た場合は、また、新たにissueをたてることとします。
