### ISSUE TITLE
要望：件名のTSVインポートの方式をヘッダで区別するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#407]
件名のTSVインポートの方式をヘッダで区別するようにしてほしいです。

現在の方法（YAML形式で書く方法）は、結構つらいものがあります。
" のエスケープも発生して、さらにつらい。

現在：

	"ndlsh: ""ウェブアプリケーション"""
	"ndlsh: [""ウェブアプリケーション"", ""インターネット""]"	
	"{ ndlsh: ""ウェブアプリケーション"", lcsh: ""Internet"" }"
	"{ ndlsh: [""ウェブアプリケーション"", ""インターネット""], lcsh: ""Internet"" }"

以下のように、してはどうでしょうか？

提案：

    subject:ndlsh	subject:lcsh
    ウェブアプリケーション
    ウェブアプリケーション//インターネット
    ウェブアプリケーション	Internet
    ウェブアプリケーション//インターネット	Internet

1. TSVのヘッダで、どの件名標目の種類を区別する（subject:ndlshのように書く）
2. 複数の語は // で区切る

これでかなりわかりやすく、書きやすくなるとおもいます。
TSVの作成も楽です。

はまりポイントも減ります。
ぜひ、こうしてほしいです！

参考：マニュアル
https://next-l.github.io/manual/enju_operation_4.html#tsv_subject

( #408 と類似 )

**Comment by nabeta** [comment]
YAML形式をやめて、この形式にインポート・エクスポートともあわせるのでよいでしょうか。

**Comment by yegusa** [comment]
はい、それでよいです!

**Comment by yegusa** [comment]
件名だけでなく、分類とかも。

**Comment by nabeta** [comment]
まずインポートに対応しました。

**Comment by yegusa** [comment]
確認しましたのでクローズします。　エクスポート ( #1095 ) のほうもよろしくね!

### 新規作成

<pre>
original_title	subject:ndlsh	subject:lcsh
件名テスト1	ウェブアプリケーション	
件名テスト2	ウェブアプリケーション//インターネット	
件名テスト3	ウェブアプリケーション	Internet
件名テスト4	ウェブアプリケーション//インターネット	Internet
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/12069708/9e860578-b089-11e5-90f5-3202f40b33c0.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12069706/7b61944a-b089-11e5-93c9-61f9e0ffefd9.png)


### 更新

<pre>
manifestation_id	subject:ndlsh	subject:lcsh
44	ウェブアプリケーション	
45	ウェブアプリケーション//インターネット	
46	ウェブアプリケーション	Internet
47	ウェブアプリケーション//インターネット	Internet
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/12069702/e1fcd45e-b088-11e5-9a29-0fce4251e478.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12069701/cb0b6792-b088-11e5-8b45-20d27181b5ff.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
