### ISSUE TITLE
要望：分類のTSVインポートの方式をヘッダで区別するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#408]
#407 と同様です。
分類のTSVインポートの方式をヘッダで区別するようにしてほしいです。

現在の方法（YAML形式で書く方法）は、結構つらいものがあります。
" のエスケープも発生して、さらにつらい。

現在：

    "ndc9: ""007"""
    "ndlc: [""AZ-463"", ""AZ-418""]"
    "{ ndc9: ""212"", ndlc: ""AZ-463"" }"
    "{ ndc9: ""212"", ndlc: [""AZ-463"", ""AZ-418""] }"

以下のように、してはどうでしょうか？

提案：

    classification:ndc9	classification:ndlc
    007
    	AZ-463//AZ-418
    212	AZ-463
    212	AZ-463//AZ-418

1. TSVのヘッダで、どの件名標目の種類を区別する（classification:ndlcのように書く）
2. 複数の語は // で区切る

これでかなりわかりやすく、書きやすくなるとおもいます。
TSVの作成も楽です。

はまりポイントも減ります。
ぜひ、こうしてほしいです！

参考：マニュアル
https://next-l.github.io/manual/enju_operation_4.html#tsv_classification

**Comment by nabeta** [comment]
まずインポートに対応しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。エクスポートのほう #1096 もよろしく!

### 新規作成

<pre>
original_title	classification:ndc9	classification:clno
分類1	007//007.58	
分類2		AZ-463//AZ-418
分類3	212	AZ-463
分類4	212	AZ-463//AZ-418
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/12069686/cfe7c916-b085-11e5-8b12-a658dbbd5896.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12069685/aed61b92-b085-11e5-8abc-ff43497affde.png)

### 更新

<pre>
manifestation_id	classification:ndc9	classification:clno
44	008//008.58	
45		AZ-464//AZ-418
46	215	AZ-464
47	215	AZ-464//AZ-418
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/12069691/c4317a8a-b086-11e5-82bb-21c7d44cc86d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12069689/a9ba3372-b086-11e5-993c-749bcd912b0e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
