### ISSUE TITLE
質問：右メニューでファセットになっているものをリストアップしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#434]
#426　に関連します。

右メニューのファセットの出力順序について検討したいです。

現在のところ
・message 機能の未読、既読のファセットは未読→既読の順で固定
![image](https://cloud.githubusercontent.com/assets/1328499/4623932/eeb8d29e-5358-11e4-92df-6efb679458f0.png)

となっています。
他にはどんなものがあるかリストアップしてもらえるとうれしいです。
ひとつづつ、件数が多いもの順、などと決めて、マニュアルに書いたりしておきたいです。

**Comment by masao** [comment]
Solr標準のファセット検索機能を用いたものを、以下に示します（注がない限り、基本的に件数の降順に並びます）：

/manifestations （書誌一覧画面）
* 予約可能 - はい, いいえ
* 出版日 - 2010-2019, 2000-2009, ..., etc. ※出版年の降順 - 標準で10年ごとに分割したファセット
* 言語 - 日本語, 英語, etc.
* 図書館 - たちばな図書館, きり図書館, etc.
* 資料の形態 - 冊子体, オーディオディスク, etc.

/items （所蔵情報一覧）
* 貸出状態 - 在架（利用可能）, 貸出中, etc.

/reserves （予約一覧）
* 状態 - 受付済み, 完了, キャンセル, etc.

/checkouts （貸出一覧）
* 予約あり - いいえ, はい

/shelves （棚一覧）
* 図書館 - きり図書館, たちばな図書館, World Wide Web, etc.

/messages （メッセージ一覧）
* 未読, 既読 （順序固定）

単に以下のコマンドで調べただけですので取りこぼしはありそうですが、ご参考に。
```
find . -type f |xargs grep _facet
```

**Comment by yegusa** [comment]
ありがとうございます！たすかります！クローズします。
