### ISSUE TITLE
Can not setup/install 1.0.4 "production" environment 

### ISSUE THREAD

**Issue by chonan** [next-l/enju_leaf#44]
When trying to install 1.0.4 using "production" environment, "bundle install" fails.

Gemfile points git repository 'git://github.com/nabeta/vidibus-routing_error.git'  for 'vidibus-routing_error' gem, however it was not found.

Since this release is *STABLE* release, must keep 'vidibus-routing_error' repository until next stable release at least.

**Comment by yegusa** [comment]
close this issue because we have not been able to reproduce it.
Please reopen if you have the same problem.
