### ISSUE TITLE
一つの書誌に大量に間違えて所蔵をつけてしまった場合の修正方法

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#46]
一つの書誌に大量に間違えて所蔵をつけてしまった場合に、楽に修正する方法はないだろうか？
一括で修正する方法はあるか？

（注：南三陸町図書館支援の一環（書誌ID:4212））

**Comment by nabeta** [comment]
これはTSVファイルで修正できるようになっているため、クローズします。
