### ISSUE TITLE
所蔵情報の新規作成を行おうとすると、デフォルトの「貸出状態」「貸出種別」プルダウンメニューが空に

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#463]
rc16です。
所蔵情報の新規作成を行おうとすると、デフォルトの「貸出状態」「貸出種別」プルダウンメニューが空になっており、「貸出種別」は新規作成で事足りますが、「貸出状態」の新規作成メニューが表示されません。

![untitled](https://cloud.githubusercontent.com/assets/1538903/4913859/90b78010-64b9-11e4-9af9-11537a0205e2.jpg)

**Comment by masao** [comment]
手元のHeroku環境で実行してますが、再現はしていません。

**Comment by yegusa** [comment]
1.1.0.rc17 のHeroku環境で再現していないようですので、いったんクローズします。もし、再現するようでしたら再オープンお願いします。→ @adamasharpe さん。
