### ISSUE TITLE
「手動で資料を登録する」での登録時エラー

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#464]
「手動で資料を登録する」での登録時にアプリケーションエラーとなります。
rc16とrc17です。
完全な再現条件がよくわかりませんがご報告を。
1）基本的な書誌事項と「件名」と「分類」を一度に入力して「登録する」を選ぶとアプリケーションエラーになる。heroku版デモサーバでも確認。書誌事項のみならエラーにはならず、後から編集で主題は付与できる。
2）上記エラーからブラウザ（Firefoxで確認）の戻るで登録画面の ホスト/manifestations/new へ戻ると、「登録する」ボタンが押せなくなる。ページを再読み込みしても同じ。

**Comment by nabeta** [comment]
現時点で発生していないため、クローズします。
