### ISSUE TITLE
CiNii Booksの親書誌・子書誌への対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#469]
がんばって、シリーズ情報として登録できるようにすべき。
親書誌から子書誌への関連関係はAPI経由では得られない場合がある点に注意。
cf. http://ci.nii.ac.jp/ncid/BA47240340

**Comment by yegusa** [comment]
親書誌がある、子書誌の資料をインポートしてみました。
できることを確認したので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10099277/21b02abe-63c3-11e5-8b8f-8ea03dc94442.png)
![image](https://cloud.githubusercontent.com/assets/1328499/10099303/61853b52-63c3-11e5-918b-99698fdf1c00.png)
![image](https://cloud.githubusercontent.com/assets/1328499/10099315/8561f5e2-63c3-11e5-9193-1b49404da4c7.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)
