### ISSUE TITLE
CiNii Books 由来のデータ(ncidなど）についてTSVインポートできるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#472]
CiNii Books 由来のデータ(ncidなど）についてTSVインポート<s>やエクスポートで</s>できるようにする

* [x] ncid
* [x] 開発
* [ ] 確認
* [ ] マニュアル　http://next-l.github.io/manual/enju_operation_4.html#section4-2-9 に追記

他になにがありますか？ncidしか思いつかないのですが。

**Comment by yegusa** [comment]
これ、issueをわけます。こっちは、インポートにします。

**Comment by yegusa** [comment]
メモ：今のところ実装されていません。(ncid列を入れたところ）
![image](https://cloud.githubusercontent.com/assets/1328499/10156255/0532a1ba-66ba-11e5-9a3f-b6f3362d6f08.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 324409d)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
機能を追加しました。
ついでに、（新規作成時はあったのですが）、更新時には、資料インポートの結果の情報が保存されていなかったので、それを保存するように機能追加してあります。

**Comment by yegusa** [comment]
更新をしてみました。
更新は少なくとも、だめみたいです。

<pre>
manifestation_identifier	ncid
http://iss.ndl.go.jp/books/R100000002-I000011206807-00	BB05902366
</pre>

![image](https://cloud.githubusercontent.com/assets/1328499/10250709/7482c446-6967-11e5-8f4e-5b420709e4e0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 35b86f3)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
できるようになったことを確認しましたので、クローズします。

更新
![image](https://cloud.githubusercontent.com/assets/1328499/10261199/016e7594-69c7-11e5-9957-4878e7aa30a5.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10261206/b55262aa-69c7-11e5-9c7b-343107359e94.png)

新規
![image](https://cloud.githubusercontent.com/assets/1328499/10261202/72a6496c-69c7-11e5-9de4-0069c95a25e7.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10261203/8909472c-69c7-11e5-86f4-f39ba3181107.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9f33908)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
