### ISSUE TITLE
利用者ファイルがインポートできません

### ISSUE THREAD

**Issue by takashimatsumura** [next-l/enju_leaf#474]
利用者のインポート用ファイルの新規作成からファイル名を指定して、
インポートしました。
利用者用インポートファイルの一覧を見ると、「状態」は「完了」、
「ファイル名」の利用者データ20141104.txtをクリックすると、
エラーメッセージ: 次の列は無視されました。 local
以外はエラーらしき表示は有りません。
その後、「利用者の一覧」を見てもインポートしたはずの利用者名が
表示されません。
どの様にしたら利用者のインポート登録ができるのでしょうか?
![default](https://cloud.githubusercontent.com/assets/9793680/5064415/3e222660-6e4c-11e4-8b46-d6e726d126f8.jpg)

**Comment by yegusa** [comment]
@takashimatsumura さん、その後いかがでしょうか？
現在、rc19への準備がすすみつつあり、
アップデートすると現象は解決するかもしれません。

時間もたったことですし、一旦、クローズしたいと思います。
もし、また、現象が再現するようでしたら、
再度、オープンしていただくか、新規にissueを立ててもらえればと思います。

よろしくおねがいいたします。

というわけで、一反、クローズします。
