### ISSUE TITLE
利用者のTSVインポート/エクスポートで「利用不可」などができるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#475]
利用者情報でTSVインポート/エクスポートできない項目があります。
これをできるようにしてほしいです。

- [　] 利用不可
- [x] フルネーム
- [x] フルネーム（ヨミ）
- [x] 参照に必要な権限
- [x] キーワードリスト

![image](https://cloud.githubusercontent.com/assets/1328499/5067608/b04d5558-6e87-11e4-8599-4b2ffaa5c049.png)

**Comment by masao** [comment]
#718 の処理をした際に、できるようになったようです。確認願います。

**Comment by yegusa** [comment]
仮想マシンでできていることを確認しました。クローズします。

以下のようなTSVファイルでためしました。

<pre>
username	user_number	locked
u550008	550008	true
u550009	550009	
</pre>
![image](https://cloud.githubusercontent.com/assets/1328499/10094613/d9d277a4-639c-11e5-94a2-d9824e655ea9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10094622/f15fd024-639c-11e5-8467-856d1f2a9bbf.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)
