### ISSUE TITLE
バグ：利用者インポートでsave_search_historyがエラーになります。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#479]
#476 に関連しています。

エラーになります。

save_search_history

http://enju.next-l.jp/user_import_files/25

![image](https://cloud.githubusercontent.com/assets/1328499/5071824/11ec92e4-6eb8-11e4-9e04-78c7c791c5eb.png)

**Comment by masao** [comment]
この情報をインポートするには enju_search_log モジュールが必要です。マニュアルに追記しておくと良いと思います。

**Comment by yegusa** [comment]
バグじゃないのね。
モジュールインストールが必要なことを、マニュアルに追記したので、クローズします。
