### ISSUE TITLE
バグ：利用者情報のエクスポートでshare_bookmarks  save_search_history が空白になります

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#480]
バグ：利用者情報のエクスポートでshare_bookmarks  save_search_history が空白になります

（デモサーバーはまたちがうエラーがでてみれないので）
仮想マシンの以下の環境で現象を確認しています。

vagrant@precise64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre63)
  * enju_circulation (0.1.0.pre41)
  * enju_event (0.1.17.pre23)
  * enju_flower (0.1.0.pre20)
  * enju_leaf (1.1.0.rc17 2e53fb4)
  * enju_library (0.1.0.pre39)
  * enju_manifestation_viewer (0.1.0.pre16)
  * enju_message (0.1.14.pre21 52856ef)
  * enju_nii (0.1.0.pre11 3387776)
  * enju_seed (0.1.1.pre11)
  * enju_subject (0.1.0.pre28)

エクスポートデータ例：
http://localhost:8080/system/user_export_files/user_exports/000/000/002/original/user_export_file_20141117-1692-tnhyw4.txt?1416240644
<pre>
username	email	user_number	role	user_group	library	locale	created_at	updated_at	expired_at	keyword_list	note	checkout_icalendar_token	save_checkout_history	save_search_history	share_bookmarks
system	root@library.example.jp		Administrator	first_group	yours	ja	2014-10-28 11:10:07 +0900	2014-10-28 11:10:07 +0900					false		
enjuadmin	admin@example.jp	0	Administrator	first_group	yours	ja	2014-10-28 11:10:07 +0900	2014-11-15 08:08:55 +0900					false		
yegusa		000001	User	first_group	yours	ja	2014-11-17 14:23:29 +0900	2014-11-17 14:23:44 +0900					false		
</pre>

**Comment by masao** [comment]
バグ修正しました。確認願います。

**Comment by yegusa** [comment]
* share_bookmarks　→　モジュール enju_bookmark をインストールしないと意味ないもの
* save_search_history　→ モジュール　enju_search_log をインストールしないと意味ないもの

ということだったようですので、上記モジュールがインストールされていない場合は、
ヘッダおよびをエクスポートしないようにするほうが自然と思います。
（というか、モジュールいれてなけりゃあ、値はないはずですし）

そのように修正お願いします。 → @masao

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
マニュアルの方は、修正しておきました。

**Comment by yegusa** [comment]
確認しましたが、失敗となりました

![image](https://cloud.githubusercontent.com/assets/1328499/10096336/aae27462-63ab-11e5-875a-c20228250868.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10096319/8ca685a6-63ab-11e5-891f-8c64ba1c0847.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by masao** [comment]
enju_bookmark を読み込んでいない環境でのテストができていませんでした。読み込んでない環境でも実行できるように修正しました。

**Comment by yegusa** [comment]
* share_bookmarks　→　モジュール enju_bookmark をインストールしないと意味ないもの
* save_search_history　→ モジュール　enju_search_log をインストールしないと意味ないもの

↑の2つがヘッダも含めて出力されないことを確かめました

![image](https://cloud.githubusercontent.com/assets/1328499/10101270/aecc3c44-63d2-11e5-9cf2-13d082e39bd7.png)

それぞれのモジュールをインストールしたときに、ちゃんと出力されるかどうかは、テストしてないですが、
ま、めったに使わないモジュールだし、そのモジュールを使うことになったときに、調べる
ってことにして、とりあえずは、クローズします。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 eef0879)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 0a65823)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)
