### ISSUE TITLE
バグ：デモサーバー：利用者エクスポート結果TSVのリンク先でエラーがでます

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#481]
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

こんなエラーがでる。

例：
http://enju.next-l.jp/system/user_export_files/user_exports/000/000/023/original/user_export_file_20140928-29749-tpp4yj.txt?1411872914

![image](https://cloud.githubusercontent.com/assets/1328499/5072799/5f6b0174-6ec0-11e4-9771-3b5051b003b6.png)

**Comment by yegusa** [comment]
@nabeta さん、これは、関連するエラーは修正した（#477）って理解でOK? OKならクローズしてください。

**Comment by nabeta** [comment]
はい、それで正しいです。
