### ISSUE TITLE
バグ：本棚のソート順をかえたときのソート順をかえるアイコンがおかしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#483]
http://enju.next-l.jp/shelves?library_id=2

上の本棚で↓（赤四角）をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/5074578/26c9e696-6ecf-11e4-9472-fa4541aa4de8.png)

変な状況（緑四角）
![image](https://cloud.githubusercontent.com/assets/1328499/5074591/414e1834-6ecf-11e4-8342-8d27ebfa4d63.png)

**Comment by nabeta** [comment]
本棚の所属する図書館を変更すると、この問題が発生するようですね。修正します。

**Comment by nabeta** [comment]
修正しました。acts_as_list （並べ替え機能実装用のライブラリ）のメソッドを上書きしてしまっていました。
http://enju.next-l.jp/shelves?library_id=2

**Comment by nabeta** [comment]
確認待ち。

**Comment by yegusa** [comment]
http://enju.next-l.jp/shelves?library_id=2
この画面にいくと、以下のようになっていました。
一番上の行が↑↓となっているのはおかしいです。

![image](https://cloud.githubusercontent.com/assets/1328499/5989342/34cc7c52-a9c8-11e4-9fa7-efc79f0a77e5.png)

**Comment by nabeta** [comment]
再度修正しました。
http://enju.next-l.jp/shelves?library_id=2

**Comment by yegusa** [comment]
デモサーバーで、できていることを確認しました。クローズします。

http://enju.next-l.jp/shelves?library_id=2
元々：
![image](https://cloud.githubusercontent.com/assets/1328499/5992993/45c508fa-aa84-11e4-91dc-09b7175eb953.png)

↓をクリック後
![image](https://cloud.githubusercontent.com/assets/1328499/5992994/4b1e898e-aa84-11e4-8108-e81b5780609e.png)
