### ISSUE TITLE
要望：ログインなしで検索した場合に検索結果一覧に「予約」リンクを付与してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#488]
ログインしていれば、検索結果一覧に予約可能な資料は「予約」リンクがでます。

ログインしてて予約リンクが表示されされている例：
![image](https://cloud.githubusercontent.com/assets/1328499/5236984/4c535714-78a5-11e4-919c-7c8f44caf7e7.png)

ログインなしで検索した場合は「検索結果一覧」に「予約」リンクがでません。

ログインなしの場合（予約リンクが表示されない）：
![image](https://cloud.githubusercontent.com/assets/1328499/5236987/8616f870-78a5-11e4-98a6-a84b37cc7fd1.png)

この場合、ログインしない人は、予約ができることがアフォードされません。
また、ログインせずに検索した結果、予約したいと思ったときに面倒です。

そこで、提案する基本の動きは以下のとおりです。
1. ログインなしで検索した→検索結果一覧には予約リンクがでる。
2. 予約リンクをクリックすると「ログインする画面に行く」
3. id と　パスワードを入力するなどしてログインする
4. 予約のできる本であれば、予約する
   ・・・　あとは、ログイン済みの画面へ

そういう機能があった方がいいと思います。

**Comment by nabeta** [comment]
予約のできない本だった場合は、どういう画面にするのがよいでしょうか？
手っ取り早いのは 403 Forbidden として処理することですが。

**Comment by yegusa** [comment]
予約のできない本だったときは、従来通り、リンクを表示させなくてよいのではないのですか？

**Comment by masao** [comment]
わたしも、予約できない本にはリンク表示無しで良いと思います。
あれ、それとも利用者グループ等に応じて、予約の可否が変わってて判定は難しいということでしょうか。

**Comment by nabeta** [comment]
> あれ、それとも利用者グループ等に応じて、予約の可否が変わってて判定は難しいということでしょうか。とりあえず、「貸出不可」以外の資料については、ログインなしでも「予約」リンクを追加することにします。
https://dev.next-l.jp/use_restrictions

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/pull/1719 で実装しました。ログインしていない状態では以下のような画面になります。
![image](https://user-images.githubusercontent.com/11428/184898161-4687c6c3-70b2-4b61-bfcd-a483cfaac88b.png)

**Comment by yegusa** [comment]
確認しました。

1. ログインなしで検索した→検索結果一覧には予約リンクがでる。
2. 予約リンクをクリックすると「ログインする画面に行く」
3. id と　パスワードを入力するなどしてログインする
4. 予約のできる本であれば、予約する
5. ・・・　あとは、ログイン済みの画面へ

できているように思いますのでクローズします。
