### ISSUE TITLE
書誌詳細から予約の一覧にたどりたい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#495]
ある書誌情報にひもづいた予約情報の一覧にたどるルートが現在は無いように思います。
（予約全体の一覧から検索するしかない）

書誌詳細画面から、その書誌に対する予約者のリストを確認する機能があるとうれしいと思います（南三陸町運用におけるヒアリングより）。つまり、次の予約者をすぐにチェックできるとよいように思います。

**Comment by nabeta** [comment]
Librarian権限でログインしている場合、「n人の予約待ち」という部分に、予約一覧へのリンクを設定するようにしてみました。いかがでしょうか。
http://enju.next-l.jp/manifestations/4876

**Comment by yegusa** [comment]
いい感じだと思います。
@masao さん、どうです？

http://enju.next-l.jp/manifestations/4876
![image](https://cloud.githubusercontent.com/assets/1328499/5694524/5f5055ee-99a5-11e4-9bc6-0900c4ce8731.png)

http://enju.next-l.jp/reserves?query=manifestation_id_i%3A4876
![image](https://cloud.githubusercontent.com/assets/1328499/5694526/965cdca6-99a5-11e4-957b-5cba532665c0.png)

**Comment by masao** [comment]
そうですね。良さそうですね。

**Comment by nabeta** [comment]
コミットしました。

**Comment by nabeta** [comment]
なお、この変更に伴い、ReserveモデルのSolrのインデックスを再作成する必要があります。アップデートの手順 (#499) に含めるようにします。

**Comment by yegusa** [comment]
では、こちらは、クローズします。
