### ISSUE TITLE
所蔵に対する利用制限の編集ができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#496]
利用制限フィールドの編集して保存すると、エラーにならずに「所蔵情報は正常に更新されました。」と出るにもかかわらず、利用制限フォールドの内容が更新されていない。

デモサーバにて確認：
http://enju.next-l.jp/items/320/edit

**Comment by nabeta** [comment]
rc17の開発版で発生しているもので、修正し、デモサーバに反映済みです。

**Comment by masao** [comment]
念のために確認しておきたいのですが、このエラーは #493 による影響ですよね?
もしYesの場合、これと同様のエラーが発生しそうなフィールドはほかにもありますか?

**Comment by nabeta** [comment]
> このエラーは #493 による影響ですよね?

はい、そうです。該当しそうなところを現在調べています。

**Comment by yegusa** [comment]
デモサーバーで、所蔵情報の利用制限フィールドが変更できるようになったことを
確認しましたのでクローズします。

#493 に影響する別フィールドについては、別issueにしたほうがいいので、新しく立てました。 　
#509 に別issueをたてました。

----

元々： http://enju.next-l.jp/items/320/edit
![image](https://cloud.githubusercontent.com/assets/1328499/5730061/7f749288-9bba-11e4-80e8-e4cb352a1071.png)

----

変更する：http://enju.next-l.jp/items/320/edit
![image](https://cloud.githubusercontent.com/assets/1328499/5730116/f5358478-9bba-11e4-97b9-e49c921b8a08.png)

----

変更後
![image](https://cloud.githubusercontent.com/assets/1328499/5730134/16fd1616-9bbb-11e4-8343-b5bf5427e51b.png)
