### ISSUE TITLE
要望：利用者の氏名を利用者の検索結果一覧に表示するようにしてほしい。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#500]
南三陸町図書館からの要望です。
以前は、利用者の氏名を利用者の検索結果一覧に表示していたのに、現在はしなくなっている。

表示場所案：
![image](https://cloud.githubusercontent.com/assets/1328499/5694545/34a4e348-99a8-11e4-948d-c07290dae5de.png)

参考：以前の画面
https://github.com/next-l/manual/blob/ddea804d6aa7b1f5160bed8b49da66943d8bfc7f/assets/images/image_operation_015.jpg
![image](https://cloud.githubusercontent.com/assets/1328499/5694541/117b252c-99a7-11e4-92a7-341e83f67004.png)

**Comment by nabeta** [comment]
表示するようにしました。
http://enju.next-l.jp/profiles

**Comment by yegusa** [comment]
デモサーバーでできることを確認しましたので、クローズします。

http://enju.next-l.jp/profiles
![image](https://cloud.githubusercontent.com/assets/1328499/5721392/81a16e50-9b74-11e4-9df0-9e619bfc5c57.png)
