### ISSUE TITLE
貸出の履歴にチェックをいれても、返却済みの貸出情報が表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#501]
デモサーバーで確認しました。

貸出の履歴にチェクを入れている
![image](https://cloud.githubusercontent.com/assets/1328499/5695549/c7d662e2-99ec-11e4-9797-1c6626e2587c.png)

貸出中もののみ出ている
http://enju.next-l.jp/profiles/112
![image](https://cloud.githubusercontent.com/assets/1328499/5695485/68cedb64-99ea-11e4-8e11-9069a8ee8493.png)

本人（enjutaro）でログインしても出ない
http://enju.next-l.jp/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/5695538/3f34f58e-99ec-11e4-9e71-54785acc0a4f.png)

http://enju.next-l.jp/my_account
![image](https://cloud.githubusercontent.com/assets/1328499/5695545/a4cbff50-99ec-11e4-8bcd-9e7b08549cfa.png)

----
参考：ちなみに貸出直後に表示される画面には表示される　（これは、当日のみ？ずっと？）
http://enju.next-l.jp/checkouts?user_id=enjutaro
![image](https://cloud.githubusercontent.com/assets/1328499/5695536/11d5b330-99ec-11e4-8a24-409741705ae9.png)

**Comment by nabeta** [comment]
直したつもりなので、もう一度ユーザenjutaroで見ていただけますでしょうか。

なお、 http://enju.next-l.jp/checkouts は返却済みの資料も表示されますが、 http://enju.next-l.jp/profiles/112 は表示されない作りになっています。
そろえたほうがいいでしょうかね？ でも、ほとんど同じ内容のページがふたつできるのもいまいちのような。

**Comment by yegusa** [comment]
> なお、 http://enju.next-l.jp/checkouts は返却済みの資料も表示されますが、 http://enju.next-l.jp/profiles/112

そろえたほうがいいです。どちらも、表示されるようにおねがいします。
というか、  http://enju.next-l.jp/checkouts  の内容が、 http://enju.next-l.jp/profiles/112でも出るってつくりにするのでいいんじゃないかなあ。

**Comment by yegusa** [comment]
というか、

* http://enju.next-l.jp/profiles/112

こちらも、貸出済みのものも出してほしいというニーズです。

**Comment by yegusa** [comment]
まずは、現在の状況を整理ます。

今は、以下のような画面になっています。

----
### 現在の画面
a) admin でログインしたときに、利用者検索をして、利用者の詳細情報を表示した画面
例：http://enju.next-l.jp/profiles/112
![image](https://cloud.githubusercontent.com/assets/1328499/5731494/5d144190-9bc7-11e4-8b66-299c0b37d14f.png)

b) 一般ユーザー でログインしたときに、「アカウント」リンクをクリックした画面
例：http://enju.next-l.jp/my_account
![image](https://cloud.githubusercontent.com/assets/1328499/5731446/c3dc6f20-9bc6-11e4-8274-6a03f97ec4f1.png)

c) 一般ユーザーでログインしたときに、「貸出と予約」の「貸出履歴」で表示した画面
例：http://enju.next-l.jp/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/5731392/17799e24-9bc6-11e4-8bab-bab9c7d1885f.png)

d) adminでログインして、あるユーザーの貸出処理した直後の画面
例：http://enju.next-l.jp/checkouts?user_id=enjutaro
![image](https://cloud.githubusercontent.com/assets/1328499/5731520/ada01238-9bc7-11e4-9964-c08c45d91d7a.png)

**Comment by yegusa** [comment]
画面の案ですが、基本的には、貸出一覧の表は上のコメントのa)～d) で共通にしたらどうでしょう。
ということです。

* c), d) は貸出一覧の表は変更なし
* a), b) は変更する
    * 見出し：「貸出」→「貸出履歴」に変える
   * c)やd) の貸出一覧と同じものにする

![image](https://cloud.githubusercontent.com/assets/1328499/5731343/bf3b3858-9bc5-11e4-977a-3338b902537b.png)

**Comment by nabeta** [comment]
貸出一覧と利用者アカウントの表示で使用するテンプレートを共通化しました。
http://enju.next-l.jp/profiles/112
http://enju.next-l.jp/checkouts?user_id=enjutaro

**Comment by yegusa** [comment]
確認しましたので、クローズします。

a) admin でログインしたときに、利用者検索をして、利用者の詳細情報を表示した画面
例：http://enju.next-l.jp/profiles/112
![image](https://cloud.githubusercontent.com/assets/1328499/5829858/b058e89e-a15b-11e4-93a2-4e08927f0ba1.png)

b) 一般ユーザー でログインしたときに、「アカウント」リンクをクリックした画面
例：http://enju.next-l.jp/my_account
![image](https://cloud.githubusercontent.com/assets/1328499/5829904/2321daf2-a15c-11e4-9f47-9a4d1750c032.png)

c) 一般ユーザーでログインしたときに、「貸出と予約」の「貸出履歴」で表示した画面
例：http://enju.next-l.jp/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/5829915/3b6f7eca-a15c-11e4-8514-82f18e8e8af5.png)

d) adminでログインして、あるユーザーの貸出処理した直後の画面
例：http://enju.next-l.jp/checkouts?user_id=enjutaro
![image](https://cloud.githubusercontent.com/assets/1328499/5829886/f5681bf8-a15b-11e4-8b49-ef921f9f66f9.png)
