### ISSUE TITLE
要望：「資料別貸出統計の新規作成」の開始日、終了日の時刻は00:00 に固定してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#502]
要望：「資料別貸出統計の新規作成」の開始日、終了日の時刻は00:00 に固定してほしい

現在は、この画面を呼び出したときの時刻になっていますが、
普通は00:00を使うことが一番頻度が高いので、
開始日、終了日の時刻は00:00 に固定してほしい

http://enju.next-l.jp/manifestation_checkout_stats/new

![image](https://cloud.githubusercontent.com/assets/1328499/5695586/0ad6c954-99ef-11e4-8432-7e0cea7353d1.png)

**Comment by nabeta** [comment]
既定の時刻を00:00にするように変更し、デモサーバに反映させました。
http://enju.next-l.jp/manifestation_checkout_stats/new

**Comment by yegusa** [comment]
デモサーバーで、確認しましたのでクローズします。

http://enju.next-l.jp/manifestation_checkout_stats/new
![image](https://cloud.githubusercontent.com/assets/1328499/5721038/b83217f8-9b6f-11e4-8bd1-8442fc134afd.png)
