### ISSUE TITLE
要望：所蔵情報一覧　の、右メニューに、「貸出状態」　のファセットが欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#503]
所蔵情報一覧　の、右メニューに、「貸出状態」　のファセットが欲しい

（特に、除籍した本の一覧を出したいため；南三陸町図書館のニーズより）

貸出状態：
除籍(5)
在架（利用可能）(10025)
作業中(2)

ってかんじで。
所蔵情報一覧 http://enju.next-l.jp/items
![image](https://cloud.githubusercontent.com/assets/1328499/5695622/d9e7b06e-99ef-11e4-8ab5-b38a465025fb.png)

**Comment by nabeta** [comment]
追加しました。
http://enju.next-l.jp/items

テンプレートを共有している都合により、書誌詳細画面にある「所蔵を編集」リンクから移動できる所蔵一覧画面にも、ファセットが表示されます。
http://enju.next-l.jp/items?manifestation_id=4908

**Comment by yegusa** [comment]
「貸出状態」というタイトルが足りません。
http://enju.next-l.jp/items
![image](https://cloud.githubusercontent.com/assets/1328499/5733769/02560002-9bec-11e4-8c68-8cca11913fdd.png)


案：
![image](https://cloud.githubusercontent.com/assets/1328499/5733752/c72e9e58-9beb-11e4-9e8e-825bc4b49cc8.png)

**Comment by nabeta** [comment]
追加しました。
http://enju.next-l.jp/items

**Comment by yegusa** [comment]
デモサーバーで、確認しました。クローズします。

http://enju.next-l.jp/items
![image](https://cloud.githubusercontent.com/assets/1328499/5733859/4719ee8c-9bed-11e4-8730-a52e20200cd3.png)

http://enju.next-l.jp/items?manifestation_id=4908
![image](https://cloud.githubusercontent.com/assets/1328499/5733845/fd9660ce-9bec-11e4-809e-131633c964f1.png)
↑のは位置が微妙なきがしますが、それは、別issueにします。

**Comment by yegusa** [comment]
位置については、 #512 に 上げておきましたが、こちらも解決済み。記録のため書いておきます。

**Comment by yegusa** [comment]
マニュアルに説明追記済み。
