### ISSUE TITLE
バグ：書誌と所蔵のエクスポートのTSVで、ISSNの列のデータがない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#505]
ISSNのヘッダには列があるが、値の方は値がないので、ISSN以降は、ヘッダと値が一つづつずれてしまう。

**Comment by nabeta** [comment]
修正し、現行デモサーバでずれていないことを確認しました。

**Comment by yegusa** [comment]
デモザーバ―で、先ほど、新規にエクスポートし、ずれていないことを確認しました。
クローズします。

http://enju.next-l.jp/resource_export_files/44
![image](https://cloud.githubusercontent.com/assets/1328499/5729859/15df0e30-9bb9-11e4-8ac4-eb6f87c1494d.png)

エクスポートしたデータをExcel で読み込んだところ
![image](https://cloud.githubusercontent.com/assets/1328499/5729836/ddc0c7dc-9bb8-11e4-864e-43cf7259d41d.png)
