### ISSUE TITLE
たくさんの資料を一度に除籍する機能（検収の逆バージョン）の追加

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#506]
検収の除籍バージョンがあってもいいかも。

「図書館の管理」→「システムの設定」の

「資料」
　　・「除籍」

で、検収のメニューのように、ピッピできるといいかんじ。

**Comment by nabeta** [comment]
所蔵の除籍って英語でなんていうんでしょう？（モデル名で使用します）

**Comment by masao** [comment]
比較的広く使われていそうなのは weeding ですかね。
cf. http://www.ala.org/tools/libfactsheets/alalibraryfactsheet15

ほかには deselection, removal といった言い方もするようですが。

**Comment by masao** [comment]
一応、ひととおりの確認をしてみました。

結論から言うと、除籍という用語に対応するのは withdrawal のようです。
先にあげた weeding は開架から書庫に移すなどの作業も含む広めの言葉のようです。

* 『図書館情報学用語辞典』第4版, 2013
  * **除籍 withdrawal**　として立項あり。関連用語として **ウィーディング**, **廃棄**。
  * **ウィーディング weeding** には、不要資料選択としての説明あり。
  * **廃棄 discard**には除籍後に資料を廃棄することを指す用語、または除籍と同義との説明あり。
* 『図書館情報学ハンドブック』第2版, 1999
  * **7.3.3 蔵書管理**の節にてウィーディング（不要資料選択）の処理方法のひとつとして解説あり。ただし、対訳の英用語は示されていない。
* 『学術用語集：図書館情報学編』, 1997
  * **zyoseki 除籍 withdrawal**との対訳あり。
* 『ALA図書館情報学辞典』, 1988
  * **除籍簿 withdrawal record**, **除籍待ち資料 withdrawal**として立項あり。
  * ほか、**不要資料選択 weed**も「除籍あるいは保管場所に移す」との語義で立項されている。
* 『The ALA Glossary of Library and Information Science』 4th ed., 2013
  * **withdrawal**として立項あり。1) 除籍処理，2) 除籍待ち資料の2つの語義があるとの説明。
  * 関連して **withdrawal record** として除籍簿の項もあり。
  * **weed**は不要資料選択として除籍処理または保管場所への移動を指す用語として解説あり。
* 『Harrod's Librarians' Glossary』 Tenth Edition, 2005
  * **Weeding**を資料の廃棄を指す用語として立項。除架は**Pseudo-weeding**として解説。
  * 関連用語として**Stripping**（加除式ファイルからの廃棄）、**Withdrawal**（除籍レコード処理）も立項。
* 『Dictionary for Library and Information Science』, 2004
  * **withdrawal**を除籍処理（および除籍資料そのもの）を指す用語として解説。関連語に、**tracing**, **weeding**
  * **weeding**は不要処理選択のための用語として解説。関連語として**deselection**

**Comment by nabeta** [comment]
こんなに詳しく調べてくださいまして、ありがとうございます。
withdrawalとしましょう。

**Comment by nabeta** [comment]
ひとまず最初の段階を実装しました。
http://dev.next-l.jp/withdraws/new

現状ではほんとうに除籍してよいか（貸出中かどうかなど）のチェックをしていません。除籍してはいけない場合として、

- 貸出中
- 予約中

以外にどのような場合がありますでしょうか？

**Comment by yegusa** [comment]
他には思いつきません。

予約中には、2種類ありますよね。
* a) 「取置済み」：所蔵にステータス付く
* b) 「予約」してるだけ：所蔵にステータス付かない

まあ、最低限、貸出中( #790 ) と取置済み( #791 )だけでも、除籍できないようにする必要は
あると思います。

**Comment by yegusa** [comment]
開発サーバー http://dev.next-l.jp/ でできることを確認しました。
とりあえず、このissueはクローズしましょう。

![image](https://cloud.githubusercontent.com/assets/1328499/10127111/28119ffc-65d8-11e5-9160-3d0f4ba19833.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127118/3edacf06-65d8-11e5-8913-5d0482ca168c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127145/53b69590-65d8-11e5-895e-caa18535f4a2.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127151/6930bc7a-65d8-11e5-8739-ac352eff065f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127156/80e2fbc6-65d8-11e5-9d25-07ced56ea7be.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127170/9d69093e-65d8-11e5-9a82-34a8de1c334a.png)

enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33
