### ISSUE TITLE
バグ：資料の貸出統計の新規作成の開始日と終了日が違う日になっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#507]
バグ：資料の貸出統計の新規作成の開始日と終了日が違う日になっている

#502 のときに、終了日が開始日＋１日となるようになってしまいました。
![image](https://cloud.githubusercontent.com/assets/1328499/5721082/7627b830-9b70-11e4-8080-2e6448d46994.png)

以前のように、資料の貸出統計の新規作成の開始日と終了日は同じにしてほしいです。
参考：#502 　以前
![image](https://cloud.githubusercontent.com/assets/1328499/5721053/fe48e4b0-9b6f-11e4-8a8d-e95c0efffc4a.png)

**Comment by nabeta** [comment]
これは意図してそうしています。デフォルトのまま「集計を開始」を押してもなにも出ないのは、やさしくないと思うので。

**Comment by yegusa** [comment]
一理あるとはおもいますが、何も言わずに、勝手に仕様を変更するのはやめていただきたいです。たまたま気づいたからもとに戻してほしいと指摘したのですが。

また、個人的には、終了日が、次の日になってるって直感的じゃないのですが。。。あと、同じ日の時間だけかえたい、一月前、一年前にしたいとおもったときに、操作が増えるのもなんだかなあとと思っています。

**Comment by nabeta** [comment]
いったん開始日と終了日を同じ日に戻すので、開発ワークショップなどで議論しましょう。

**Comment by yegusa** [comment]
デモサーバーで、確認しましたので、クローズします。

http://enju.next-l.jp/manifestation_checkout_stats/new
![image](https://cloud.githubusercontent.com/assets/1328499/5729691/988a2434-9bb7-11e4-82bd-15366ae84211.png)

**Comment by yegusa** [comment]
初期値をどうするかは、Enju WSで議論しましょう。他のシステムはどうなっているかも参考にしたいですね。
