### ISSUE TITLE
バグ：strong_parametersへの移行に影響するフィールドを調査し、不具合を修正する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#509]
#493 strong_parametersへの移行と 
#496 所蔵に対する利用制限の編集ができない
から派生したissueです。

#496 のように 編集したさいに反映されないことがあるなどの
不具合がでる可能性があるので、
関連したフィールドを調査し、修正する。

- [x] 資料（書誌）の編集（シリーズ情報） http://enju.next-l.jp/manifestations/4876/edit
    * （シリーズ名、シリーズ名のヨミ、シリーズ巻号、シーリーズ著者、マスタ）
- [x] 資料（書誌）の編集（著者） http://enju.next-l.jp/manifestations/4876/edit 
- [x] 資料（書誌）の編集（編者）http://enju.next-l.jp/manifestations/4876/edit 
- [x] 資料（書誌）の編集（出版者）http://enju.next-l.jp/manifestations/4876/edit
- [x] 資料（書誌）の編集（識別子 http://enju.next-l.jp/manifestations/4876/edit 
    * 新規：#534 削除： #535 更新： #537
- [x] 資料（書誌）の編集（件名）http://enju.next-l.jp/manifestations/4876/edit 
- [x] 資料（書誌）の編集（分類）http://enju.next-l.jp/manifestations/4876/edit 
- [x] 資料の形態の編集 （貸出種別）http://enju.next-l.jp/carrier_types/1/edit 
- [x] 所蔵情報の編集（利用制限）http://enju.next-l.jp/items/318/edit 
- [x] 図書館全体の設定の編集（色）http://enju.next-l.jp/library_groups/1/edit 
- [x] プロフィールの編集（権限）http://enju.next-l.jp/profiles/112/edit

**Comment by nabeta** [comment]
一対多・多対多などの関連をひとつのフォームで扱っている場所（モデルでaccepts_nested_attributes_forを指定していた場所）に不具合が残っている可能性があります。
http://enju.next-l.jp/manifestations/4876/edit （シリーズ情報・著者・編者・出版者・識別子・件名・分類）
http://enju.next-l.jp/carrier_types/1/edit （貸出種別）
http://enju.next-l.jp/items/318/edit （利用制限）
http://enju.next-l.jp/library_groups/1/edit （色）
http://enju.next-l.jp/profiles/112/edit （権限）

**Comment by yegusa** [comment]
一通り確認作業しました。
確認したときのチェックリストを挙げておきます。
https://docs.google.com/spreadsheets/d/1CE681tlJINZISaMl761vcurgRD4iYzkYXGFYwz8pY-M/edit#gid=0

#542 #543 がクローズされればこれもクローズできると思います。

**Comment by nabeta** [comment]
すべて修正しましたので、closeできます。

**Comment by yegusa** [comment]
ですね。クローズします。
