### ISSUE TITLE
所蔵一覧・編集画面で書影が表示されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#511]
今気付いたのですが、書誌に対する所蔵一覧画面や所蔵詳細・編集画面で、書影が表示されません。所蔵編集中もどの書誌に対して操作しているかがわかるように、書影を表示させたいと思います。
http://enju.next-l.jp/items?manifestation_id=4902
http://enju.next-l.jp/items/321

なお、NIMS版では表示されています。
https://library.nims.go.jp/items?manifestation_id=103164

**Comment by yegusa** [comment]
そうですね。よいと思います。

**Comment by nabeta** [comment]
所蔵一覧・詳細・追加・編集画面で、書影を表示するようにしました。
http://enju.next-l.jp/items?manifestation_id=4902
http://enju.next-l.jp/items/321
http://enju.next-l.jp/items/new?manifestation_id=4902
http://enju.next-l.jp/items/321/edit

**Comment by yegusa** [comment]
確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/5739007/f0ea7438-9c36-11e4-8a82-712f09806208.png)

![image](https://cloud.githubusercontent.com/assets/1328499/5739013/00749ffa-9c37-11e4-8870-d65955075ec2.png)

![image](https://cloud.githubusercontent.com/assets/1328499/5739015/10f2e08a-9c37-11e4-8771-2184455815e4.png)

![image](https://cloud.githubusercontent.com/assets/1328499/5739021/2a66027c-9c37-11e4-9353-85d7837e0ed0.png)
