### ISSUE TITLE
書誌詳細画面にある「所蔵を編集」リンクから移動できる所蔵一覧画面にでる「貸出状態」のファセットを、「所蔵情報の新規作成」の下に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#512]
書誌詳細画面にある「所蔵を編集」リンクから移動できる所蔵一覧画面にでる「貸出状態」のファセットを、「所蔵情報の新規作成」の下に

今の位置だと、貸出状態のファセットと区別がない感じで変だし、ファセットが増えると、、「所蔵情報の新規作成」が下のほうにいってしまうため。

http://enju.next-l.jp/items?manifestation_id=4908

現在：
![image](https://cloud.githubusercontent.com/assets/1328499/5733869/8afbf5fa-9bed-11e4-9147-ffdb4b25903c.png)

案：
![image](https://cloud.githubusercontent.com/assets/1328499/5733907/015d8542-9bee-11e4-9544-c628dda04a57.png)

**Comment by nabeta** [comment]
移動しました。

**Comment by yegusa** [comment]
デモサーバーで、確認しました。クローズします。

http://enju.next-l.jp/items?manifestation_id=4908
![image](https://cloud.githubusercontent.com/assets/1328499/5738982/91dd5e56-9c36-11e4-8e39-e0262ea37b04.png)
