### ISSUE TITLE
シリーズマスタになっている書誌に削除リンクが表示されない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#514]
以下がその例。紐付いている書誌がないにもかかわらず、削除リンクが表示されない。
http://enju.next-l.jp/manifestations?parent_id=4909

**Comment by nabeta** [comment]
削除リンクを表示するようにしました。
http://enju.next-l.jp/manifestations?parent_id=4909

**Comment by yegusa** [comment]
確認待ち。

**Comment by yegusa** [comment]
http://enju.next-l.jp/manifestations?parent_id=4940
![image](https://cloud.githubusercontent.com/assets/1328499/5989321/675cf2c4-a9c7-11e4-9216-59e515769693.png)

削除リンクがでることを確認しました。

削除できることも確認しました。
クローズします。
