### ISSUE TITLE
外部キー制約の追加

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#515]
データベースを壊さないため。
http://ja.wikipedia.org/wiki/参照整合性

Rails 4.1以下ではforeigner gemを使用、Rails 4.2では標準でサポートされている。
https://github.com/matthuhiggins/foreigner
http://guides.rubyonrails.org/4_2_release_notes.html#foreign-key-support

**Comment by nabeta** [comment]
NIMSではいくつかの項目に手動で ALTER TABLE ADD FOREIGN KEY を実行しています。

**Comment by nabeta** [comment]
manifestationsとitemsなどのクリティカルな部分を中心に、1.1系でも導入する。

**Comment by nabeta** [comment]
enju_biblio-0.1.0.pre64で、manifestationsテーブルのitem_idに外部キー制約を追加しました。これはenju_leaf-1.1.0.rc17といっしょにリリースされます。
https://github.com/next-l/enju_biblio/blob/1.1/db/migrate/20150117111136_add_foreign_key_to_items_referencing_manifestations.rb

**Comment by masao** [comment]
rc17への更新を試しましたが、手元の開発環境ではdb:migrate時にエラーになりますね。

```
$ rake railties:install:migrations
Copied migration 20150227070527_add_foreign_key_to_items_referencing_manifestations.enju_biblio_engine.rb from enju_biblio_engine
Copied migration 20150227070528_add_settings_to_library_group.enju_library_engine.rb from enju_library_engine
Copied migration 20150227070529_create_demands.enju_circulation_engine.rb from enju_circulation_engine
$ bundle exec rake db:migrate
== 20150227070527 AddForeignKeyToItemsReferencingManifestations: migrating ====
-- add_foreign_key(:items, :manifestations)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `add_foreign_key' for #<AddForeignKeyToItemsReferencingManifestations:0x007fe681b37ad0>/home/vagrant/enju/db/migrate/20150227070527_add_foreign_key_to_items_referencing_manifestations.enju_biblio_engine.rb:4:in `change'
NoMethodError: undefined method `add_foreign_key' for #<AddForeignKeyToItemsReferencingManifestations:0x007fe681b37ad0>
/home/vagrant/enju/db/migrate/20150227070527_add_foreign_key_to_items_referencing_manifestations.enju_biblio_engine.rb:4:in `change'
```

**Comment by masao** [comment]
Gemfileに foreigner することでエラーとならなくなりましたが、Rails4.1環境であってもエラーを発声させないように依存関係を記述しておくことはできないでしょうか。

```ruby
gem "foreigner"
```

**Comment by nabeta** [comment]
どうもこのgemはRails 4.2に非対応のようです。手動でGemfileに追加するのでいかがでしょうか。

**Comment by masao** [comment]
SQLite3では外部キー制約はデフォルトではサポートしていない模様・・・。
動作確認、テストには MySQL / PostgreSQL などのデータベースを用いること。

**Comment by nabeta** [comment]
アップデート用のドキュメントを追加しました。
https://github.com/next-l/enju_leaf/wiki/Update#updating-to-110rc19

**Comment by masao** [comment]
ドキュメントおよびPostgreSQLでの制約追加を確認しました。クローズします。
