### ISSUE TITLE
アプリケーションの設定を環境変数から読み込むようにする

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#516]
http://12factor.net/config

現状では、APIキーなどのアプリケーションの設定は設定ファイル（config/appication.ymlなど）に記述しているが、Herokuなどのクラウドベンダーでは、アプリケーションの設定を環境変数を使用して行えるようになっている。クラウドへの配備を容易にするため、設定の記述を設定ファイルから環境変数に移動したい。

作業：
- [x] データベースの接続先（Railsで対応、DATABASE_URL）
- [x] cookie確認用の秘密鍵（Railsで対応、SECRET_KEY_BASE）
- [x] Solrの接続先（sunspotで対応、SOLR_URL）
- [x] AWSのAPIキー
- [x] Amazon S3のファイル保存先
- [x] Amazon S3のホスト名 （5月6日追記）
- [x] Redisの接続先（非同期処理に使用）
- [x] memcachedの接続先

確認（ @masao ）：
- [x] データベースの接続先: DATABASE_URL
- [ ] cookie確認用の秘密鍵: SECRET_KEY_BASE
- [x] Solrの接続先: SOLR_URL
- [ ] AWSアクセスキー: AWS_ACCESS_KEY_ID
- [ ] AWS秘密アクセスキー: AWS_SECRET_ACCESS_KEY
- [ ] Amazon S3のバケット名: S3_BUCKET_NAME
- [ ] Amazon S3 のホスト名: S3_HOST_NAME
- [x] Redisの接続先: REDIS_URL
- [ ] memcachedの接続先: MEMCACHE_SERVERS

なお、ファイルに設定値を記述したい場合、dotenvなどを使用する。
https://github.com/bkeepers/dotenv

**Comment by nabeta** [comment]
開発ワークショップで以下の意見あり。

- 設定値はWebブラウザで変更（DBに保存）した値を優先できるとよい
- 優先順位はDB -> 環境変数 -> 設定ファイル

**Comment by yegusa** [comment]
南三陸町図書館ではHeroku を使っているし、これができなければ、 エクスポート機能ができなそうなので、これを最優先issueとしたいと思います。

**Comment by nabeta** [comment]
以下の環境変数を読み込むようにしました。enju_leaf-1.1.0.rc18のリリースに含める予定です。

- AWSアクセスキー: AWS_ACCESS_KEY_ID
- AWS秘密アクセスキー: AWS_SECRET_ACCESS_KEY
- S3バケット名: S3_BUCKET_NAME

**Comment by nabeta** [comment]
以下の環境変数を読み込むようにしました。enju_leaf-1.1.0.rc18のリリースに含める予定です。
https://github.com/next-l/enju_leaf/commit/611cafa5287830a4ee96ab0396abc46dd2c8ca82

- Redisの接続先URL: REDIS_URL

redis://localhost:6379 という形式になります。

**Comment by yegusa** [comment]
残っている作業は、
* @nabeta による 「memcachedの接続先」の開発
* ↑が終わったら、 @masao もしくは、 @yegusa が確認

**Comment by nabeta** [comment]
memcachedの接続先ですが、接続に使用するライブラリのdalliが環境変数 MEMCACHE_SERVERS を読み込むようになっていました。
https://github.com/mperham/dalli/blob/fc70684e99bb8151038e2f4e4e0feaa53c61e097/lib/dalli/client.rb#L32

接続先の指定は localhost:11211 という形式になります。

**Comment by yegusa** [comment]
@masao さん、じゃあ、確認してください。よろしく。

**Comment by nabeta** [comment]
環境変数のまとめです。

- データベースの接続先: DATABASE_URL
- cookie確認用の秘密鍵: SECRET_KEY_BASE
- Solrの接続先: SOLR_URL
- AWSアクセスキー: AWS_ACCESS_KEY_ID
- AWS秘密アクセスキー: AWS_SECRET_ACCESS_KEY
- Amazon S3のバケット名: S3_BUCKET_NAME
- Redisの接続先: REDIS_URL
- memcachedの接続先: MEMCACHE_SERVERS

**Comment by yegusa** [comment]
こちら、Herokuじゃなくて、普通のUnix上で設定する方法をおしえてください→ @nabeta さん。
それで、確認ができるようになるかとおもいます。

**Comment by nabeta** [comment]
まずGemfileに以下の行を追加し、bundle updateを実行してください。

```ruby
gem 'dotenv-rails'
```

次に、.env ファイルをGemfileと同じディレクトリに作ってください。内容は以下のようになります。

```sh
DATABASE_URL=sqlite:///home/nabeta/enju/db/development.db
SECRET_KEY_BASE=somelongstringsomelongstringsomelongstring
SOLR_URL=http://localhost:8080/solr/development
REDIS_URL=redis://localhost:6379
MEMCACHE_SERVERS=localhost:11211
ENJU_STORAGE=s3
AWS_ACCESS_KEY_ID=yourawsaccesskey
AWS_SECRET_ACCESS_KEY=yourawssecretaccesskey
S3_BUCKET_NAME=your_enju_leaf_bucket
```

これでEnjuを再起動してください。

**Comment by masao** [comment]
DATABASE_URL, SOLR_URL, REDIS_URL については動作を確認しました。

なお、DATABASE_URLの SQLite3 への指定は以下のような書式のようです（絶対パスは指定不可）：
```
DATABASE_URL=sqlite3:db/development.sqlite3
```

**Comment by nabeta** [comment]
S3のバケットをアメリカ東海岸リージョン以外に作成する場合、S3のホスト名を指定する必要がありました。S3_HOST_NAME環境変数で設定できるようにしました。以下の例は東京リージョンを使用する場合です。

```sh
S3_HOST_NAME=s3-ap-northeast-1.amazonaws.com
```

**Comment by yegusa** [comment]
全部確認していないけど、確認していないやつは基本、Herokuしか関係ないし、いいことにして、とりあえず、クローズします。（Herokuは他のissue #607 #608 #609 などで確認するし ）
