### ISSUE TITLE
バグ：デモサーバーでadminでログインしても「システムの設定」メニューが空になっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#518]
バグ：デモサーバーでadminでログインしても「システムの設定」メニューが空になっている

http://enju.next-l.jp/
![image](https://cloud.githubusercontent.com/assets/1328499/5829321/cecc34d2-a153-11e4-8b04-e99e128e68bc.png)

admin なのに、システム設定メニューがでなくて、システム設定周りができなくて困っています。

**Comment by nabeta** [comment]
すみません、きのうの夜中に、エラー画面のチェック作業のために一時的に管理者権限を落としたのですが、完了前にそのまま寝てしまいました。先ほど元に戻しました。

**Comment by yegusa** [comment]
できていることを確かめましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/5829540/f6cc6f3a-a156-11e4-8063-baf035ae5e6a.png)
