### ISSUE TITLE
要望：雑誌の受入で、当該雑誌タイトルの横に「新規受け入れ」リンクを追加してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#519]
雑誌のある一号を受け入れた際に、書誌データと所蔵データの登録は、

1. 資料の受入→雑誌・定期刊行物
2. 該当する雑誌のタイトルのリンクをたどる
3. 右メニューの「資料の新規作成」をたどる
4. 当該雑誌の書誌データを作成する
5. 当該雑誌の所蔵データを作成する

となるわけですが、これを、

1. 資料の受入→雑誌・定期刊行物
2. 該当する雑誌のタイトルの横にある「新規受入」リンクをたどる
![image](https://cloud.githubusercontent.com/assets/1328499/5839064/fc14ffde-a1ce-11e4-8355-d1aec69047b9.png)
3. 当該雑誌の書誌データを作成する
4. 当該雑誌の所蔵データを作成する

とできるようにしたら、ずいぶん直感的になるきがします。

（南三陸町図書館でのニーズに対応した機能です）

**Comment by nabeta** [comment]
ひとまずデモサーバで実装しました。
http://enju.next-l.jp/manifestations?serial=true

現在不自然にスペースが空いているところは、「予約」リンクが表示される場所になっています。レイアウトの調整が必要かもしれません。

**Comment by yegusa** [comment]
動作確認しました。
動きはこれでよいとおもいます。

http://enju.next-l.jp/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/5849328/ccd6267c-a227-11e4-9ea0-38ac2b3581b2.png)

たしかに、レイアウトの調整は必要ですね。
* 「新規受入」の上の空行をどうにかする （予約が入る部分？）
* 表の2列目をもうすこし短くして、「新規受入」が一行になるようにする

あたりが必要かと。

**Comment by masao** [comment]
@yegusa 「予約」可能でないものは、一行空かないように修正を加えました。
確認をお願いします。

**Comment by yegusa** [comment]
開発サーバーで確認し、できていることを確認しましたので、クローズします。
http://dev.next-l.jp/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/8266175/3f2c930e-1759-11e5-9c2f-3a10a9c6b7f5.png)
