### ISSUE TITLE
不具合：デモサーバーで、雑誌のタイトルをクリックするとWe're sorry になります。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#520]
例：
http://enju.next-l.jp/manifestations?parent_id=4115&query=

**Comment by nabeta** [comment]
アクセス認可ルールの記述に誤りがありました。修正しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。
http://enju.next-l.jp/manifestations?parent_id=4115&query=
![image](https://cloud.githubusercontent.com/assets/1328499/5849526/e47e3de4-a229-11e4-93b5-33d9e102aea7.png)
