### ISSUE TITLE
不具合：書誌と所蔵のエクスポートに時間がかかりすぎる（対策：書誌と所蔵のエクスポートでManifestationを少しずつ取得するようにする）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#521]
書誌と所蔵のエクスポート方法が、Manifestationを一度に全件取得するようになっており、
2万件程度でも、メモリが豊富にないと、メモリを食いつぶしてしまい、4時間以上かかってしまう。

対策：Manifestationを少しずつ取得するように修正する。

参考：
> エクスポートの際、Manifestationを少しずつ取得するのではなく、一度に全件取得してしまっていますね。これでは一気に負荷がかかる上にメモリを食いつぶしてしまい、遅くなって当然です。
> https://github.com/next-l/enju_biblio/blob/master/app/models/manifestation.rb#L508
> by @nabeta

（ ※ 南三陸町図書館システムで起こった問題より）

**Comment by yegusa** [comment]
これって、どっかで解決してませんでしたっけ？　→ @nabeta

**Comment by masao** [comment]
南三陸町案件で解決しているので、これを取り込むだけでよいはず： https://github.com/next-l/minamisanriku/commit/f4c62a72691d85b3f9e2be3a8e1920e34af21344 (private)

**Comment by nabeta** [comment]
取り込みました。
https://github.com/next-l/enju_biblio/commit/7e09e7cb7c59bcfc77ab233bac346009f14122da

**Comment by yegusa** [comment]
開発サーバーで、
所蔵が2万件以上ある状態で、エクスポートしてみましたが、
1時間以内でエクスポートできましたので、
クローズします。

http://dev.next-l.jp/resource_export_files/61

（メモ：開始時刻だけでなく、終了時刻も表示されるようになっているといいかもですね。）
