### ISSUE TITLE
「資料の形態の編集」画面で、資料の形態のアイコン画像を登録できるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#522]
以下、すべてができたら、このissue をクローズします：

- [x] 「資料の形態の編集」画面で、画像ファイルを選択して、登録できるようにする
- [x] #1243 書誌の検索結果一覧や詳細表示で登録した資料形態のアイコンを表示できるようにする
- [ ] #1244 「資料の形態の表示」（詳細）画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする 
- [x] #1245 「資料の形態の一覧」画面に、「資料の形態の編集」画面で、登録した、資料の形態のアイコン画像を表示できるようにする

検索結果などに、資料の形態ごとにアイコンが表示されますが、
例：冊子体の場合
![image](https://cloud.githubusercontent.com/assets/1328499/5871256/d1b11b1a-a31d-11e4-8f51-540008018cea.png)

新しい資料の形態を登録したときに、アイコンを登録する機能がなく、
? になってしまいます。

編集画面で、アイコン画像が登録できるようになっているとよいかと思います。
例：http://enju.next-l.jp/carrier_types/3/edit これの赤四角のあたりで。
![image](https://cloud.githubusercontent.com/assets/1328499/5871225/63fb9e1a-a31d-11e4-9e61-200b108c7efd.png)

**Comment by nabeta** [comment]
ついでに書影がないときのアイコン（以下）も登録できるといいかもしれませんね。
https://github.com/next-l/enju_leaf/blob/master/app/assets/images/unknown_resource.png

**Comment by yegusa** [comment]
南三陸町で紙芝居のアイコンなどがでなかったときに、思いついたissueです。これが実現すれば、南三陸町図書館のシステムのカスタマイズ項目が一つ減ります。

また、既存のアイコンを無理に移行する必要なく、あらたに追加されたときはそちらをみるということで、リーズナブルに移行できそうとの @masao の案です。

**Comment by masao** [comment]
上記でCarrierTypeへの添付ファイルの追加があったようですが、これに移行するにはデータベースの更新が必要になります。また、手順の文書化も必要です。

**Comment by masao** [comment]
データベース更新は以下にて実行可能：

```
bundle exec rake railties:install:migrations
bundle exec rake db:migrate RAILS_ENV=production
```

**Comment by masao** [comment]
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/19415419/aab0aa2e-93aa-11e6-8d98-ea9e46297ed8.png)
上記の資料の形態の詳細ページにある画像ファイルへのリンク（スクリーン上は /carrier_types/2.download?size=thumb ）をたどると、Railsエラーになります。

![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/19415426/d017171c-93aa-11e6-924e-70fe4ef30d47.png)

**Comment by nabeta** [comment]
上記のコミットで修正しました。enju_libraryもgithub上のものを使用してください。

```
gem 'enju_library', github: 'next-l/enju_library', branch: '1.2'
gem 'enju_biblio', github: 'next-l/enju_biblio', branch: '1.2'
```

**Comment by masao** [comment]
#1244 のみ残っていますが、1.2.1リリースに伴い、いったんクローズします。
