### ISSUE TITLE
提案: 書誌・所蔵データをすべてJSONで持つ

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#525]
現在のenju_leafは、書誌・所蔵データはmanifestationsやitems, agentsなどの複数のテーブルに持たせていますが、これをJSONでまとめることはできないか、という実験的な提案です。PostgreSQLのJSON型カラムを使うことを想定しています。
http://www.postgresql.jp/document/9.3/html/datatype-json.html
- メリット
  - RDBから取り出した書誌・所蔵データのJSONをそのままElasticsearchに渡せるため、検索インデックスの作成や更新が速くなる
  - 書誌・所蔵データの項目を容易に追加できる
- デメリット
  - PostgreSQL 9.3以降でしか使えなくなる
  - 外部キー制約が使えなくなる
  - 書誌・所蔵の編集フォームに大改造が必要

**Comment by masao** [comment]
そこまでしてRDBを使う必要があるのだろうか…という気もしますが（Key-Valueストアで十分という印象）。いずれにしろ、これに全面的に乗るのは難しいかな、と思います。運用環境が限定的になることから、メイン（1.1, master）に取り込むのは難しいと思いますが、実験ブランチで試行してみることは反対しません。

**Comment by nabeta** [comment]
RDBを使うのは、貸出管理のためのトランザクション処理を必要とするためです。
もっとも、検索専用のサービスを外だしにするなら、それは関係なくなりますね。

**Comment by nabeta** [comment]
第34回開発ワークショップで以下のような意見が出ました。

* 状態遷移情報を持つ所蔵データを含めるのは難しいが、それらを持たない書誌データだけなら可能ではないか
* 書誌データだけの場合、書誌項目を増やせるというメリットが大きい
* 検索UIの変更案(#531)とも相性がよい
* まずは実験してみるのがよい

**Comment by nabeta** [comment]
これはEnjuとは別のプロジェクトで試したのですが、最初にデータを入れているうちはよいものの、後からデータベースのスキーマの変更を行おうとすると、とたんに作業が行いにくくなりました。ふつうのデータベースであれば、たとえば列の理ネームは`ALTER TABLE`だけで済むのに、JSONのみでデータを持つ方法だと、JSONを操作する関数を別途使わなければならなくなってしまいます。
https://stackoverflow.com/questions/42308764/postgresql-rename-attribute-in-jsonb-field

Enjuではこの方法は採用しないことにします。
