### ISSUE TITLE
デモサーバーを安定バージョンに戻す

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#527]
デモサーバー http://enju.next-l.jp/ は、デモ用途とし、基本的には安定バージョンとする

別途、開発サーバー http://dev.next-l.jp/
を用意しているので、そちらで、
新規機能の開発・確認は、1.1.x と 1.2.x どちらも、こちらの開発サーバーで、行う。

**Comment by nabeta** [comment]
以上の措置は1.1.0.rc17のリリース時に実施予定です。

**Comment by nabeta** [comment]
いずれも実施済みです。

**Comment by yegusa** [comment]
どちらも稼働しているようですので、クローズします。
今後もこの方針で、デモサーバーは安定板、開発サーバーで開発と一貫してやりましょう～。
