### ISSUE TITLE
検索結果の一覧の「編集」アイコンを「編集」にする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#528]
検索結果にでてくる「編集」アイコン
![image](https://cloud.githubusercontent.com/assets/1328499/5885863/58568ac4-a3be-11e4-9895-f49c35dcb7e8.png)

これを「編集」という文字列にする。
![image](https://cloud.githubusercontent.com/assets/1328499/5885871/79d5311e-a3be-11e4-86c1-c9bc98bfa9d8.png)

**Comment by nabeta** [comment]
上記のように画面になるように変更しました。これでよければcommitします。
http://enju.next-l.jp/manifestations?utf8=✓&query=&commit=検索

**Comment by yegusa** [comment]
確認しました。これでよいとおもいます。commitしちゃってください。commitしたらクローズしてください。

http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/5989380/58fc1604-a9c9-11e4-8d7f-ce53b7eeddea.png)

**Comment by yegusa** [comment]
rc17のデモサーバーで確認しましたので、クローズします。
![image](https://cloud.githubusercontent.com/assets/1328499/7201649/9c5ef07c-e544-11e4-8cd5-21c8e8c90c7c.png)
