### ISSUE TITLE
依存ライブラリの変更：認可管理：cancancan→pundit

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#529]
- [x] 開発
- [ ] テスト作成
- [ ] 確認

1.1.0までにmasterブランチからバックポートする。
テストを用意すること。spec/views/ 以下。

**Comment by nabeta** [comment]
先ほど全てのモジュールの1.2ブランチにおいて、punditへの移行作業を完了しました。

**Comment by yegusa** [comment]
#287 にも関連。

**Comment by yegusa** [comment]
@masao さんかどなたか、確認できるかた、確認してクローズお願い。

**Comment by yegusa** [comment]
メモ：
Librarian権限などの権限に応じてできること・できないことを管理している。

例えば、以下のようなかんじ。

* 利用者情報は誰がみれるか
* 購入リクエストは誰が見れるか

**Comment by yegusa** [comment]
現在のステータス：

- 私は確かめ方がわかりません。

**Comment by masao** [comment]
移行作業が完了してからだいぶ時間が経っていますし、特に問題も発生していないようですので、ひとまずクローズします。
