### ISSUE TITLE
バグ：書誌の編集で「識別子」を新しく追加すると、分類と件名が二重に登録される。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#534]
バグ：書誌の編集で「識別子」を新しく追加すると、追加はできるが、分類と件名が増える。
#509 に関連したissueです。

書誌詳細：修正前
http://enju.next-l.jp/manifestations/4931
![image](https://cloud.githubusercontent.com/assets/1328499/5887784/10828824-a427-11e4-9e9d-e97ed631763f.png)

書誌詳細：識別子：issn_l:1400000を追加した直後の画面、分類が増えている。
![image](https://cloud.githubusercontent.com/assets/1328499/5887786/27c346c2-a427-11e4-874b-a38a77b013b5.png)

**Comment by nabeta** [comment]
デモサーバに反映させて識別子の追加・更新・削除の操作を行い、正常に動作することを確認しました。もう一度試していただけますでしょうか。
http://enju.next-l.jp/manifestations/4925/edit

**Comment by yegusa** [comment]
確認しました。クローズします。
http://enju.next-l.jp/manifestations/4932

追加前
![image](https://cloud.githubusercontent.com/assets/1328499/5887835/2de8c07a-a429-11e4-9348-1e64655bf977.png)

追加後
![image](https://cloud.githubusercontent.com/assets/1328499/5887836/33874646-a429-11e4-9e3c-8494037b69a4.png)
