### ISSUE TITLE
バグ？シリーズ著者が書誌詳細に表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#541]
バグ？シリーズ著者が書誌詳細に表示されない

仕様かもしれませんが、気づいたので載せておきます。

http://enju.next-l.jp/manifestations/4937
![image](https://cloud.githubusercontent.com/assets/1328499/5989049/62b345ca-a9bd-11e4-9d93-78d910dd98a0.png)

![image](https://cloud.githubusercontent.com/assets/1328499/5989051/7553e8ec-a9bd-11e4-9dd6-bbbbb9265b57.png)

**Comment by nabeta** [comment]
これは表示場所をどうしようか、というところでほったらかしになっていました。
どう表示されるのがいいですかね。

**Comment by yegusa** [comment]
こんなイメージでどうでしょう。

![image](https://cloud.githubusercontent.com/assets/1328499/5991416/4838016c-aa31-11e4-834e-04b9085deb52.png)

**Comment by masao** [comment]
上で提案されている表示案になるように修正を加えました。確認願います。

**Comment by yegusa** [comment]
開発サーバーで確認しました。できることを確認しましたのでクローズします。

-----
ISBN: 9784894713017 のデータをインポートして、
http://dev.next-l.jp/manifestations/24403

次のシリーズ情報を追加：
プログラミング言語シリーズ プログラミングゲンゴシリーズ 2 情報, 太郎 1980-
Perlシリーズ パールシリーズ  6 小川，花子， 1983-

![image](https://cloud.githubusercontent.com/assets/1328499/9829389/4a6c58fa-593d-11e5-8d27-b96417fc239f.png)

以下のように、シリーズ著者が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/9829383/0f16725e-593d-11e5-8b0f-51d0770911fd.png)

確認した環境：
enju_leaf: 1.1.0.rc21
enju_circulation: 0.1.0.pre48
enju_flower: 0.1.0.pre23
enju_ndl: 0.1.0.pre37
enju_subject: 0.1.0.pre33
enju_oai: 0.1.0.pre19
enju_biblio: 0.1.0.pre69
rails_autolink: 1.1.6
enju_message: 0.1.14.pre25
ri_cal: 0.8.8
enju_event: 0.1.17.pre26
geocoder: 1.2.11
enju_library: 0.1.0.pre43
enju_manifestation_viewer: 0.1.0.pre19
