### ISSUE TITLE
バグ：資料の形態の編集 （貸出種別）：編集前のものと、編集後のものが登録される状態に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#542]
編集前のものと、編集後のものが登録される状態になる。
#509 に関連したissueです。

http://enju.next-l.jp/carrier_types/10
元々は、CD
![image](https://cloud.githubusercontent.com/assets/1328499/5989119/1e752470-a9c0-11e4-9108-cf7a0441384f.png)

CDを図書に変えて更新
![image](https://cloud.githubusercontent.com/assets/1328499/5989122/246bfa02-a9c0-11e4-9d6c-26073d98f6b1.png)

CDと図書になっている。
![image](https://cloud.githubusercontent.com/assets/1328499/5989125/3b854c7a-a9c0-11e4-9078-c3ed7ccdc644.png)

**Comment by nabeta** [comment]
修正しました。
http://enju.next-l.jp/carrier_types/10

**Comment by yegusa** [comment]
デモサーバーで確認したのでクローズします。

修正前
![image](https://cloud.githubusercontent.com/assets/1328499/5991427/809f3fb0-aa32-11e4-819d-5f499e75d6c4.png)

図書をCDに変えて更新
![image](https://cloud.githubusercontent.com/assets/1328499/5991429/8f8e80ee-aa32-11e4-9513-ef8e32f68148.png)

CDに変更された
![image](https://cloud.githubusercontent.com/assets/1328499/5991430/998c6c5a-aa32-11e4-84bb-2f8d088669f9.png)
