### ISSUE TITLE
バグ：資料の形態の削除 （貸出種別）：削除できない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#543]
エラーがでて削除できません。

#509 に関連したissueです。

http://enju.next-l.jp/carrier_types/11

元々は、CDが登録されている
![image](https://cloud.githubusercontent.com/assets/1328499/5989165/7692ff6e-a9c1-11e4-8850-d8febe17d046.png)

編集で削除をクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/5989168/8d19df6e-a9c1-11e4-8daa-7d0b9646a5c7.png)

更新をクリックする
![image](https://cloud.githubusercontent.com/assets/1328499/5989169/9a817fae-a9c1-11e4-9698-5f1f81bb2238.png)

エラーがでて削除できない
![image](https://cloud.githubusercontent.com/assets/1328499/5989170/a42f5a26-a9c1-11e4-8ad6-8eab00564d90.png)

**Comment by nabeta** [comment]
#542 とともに修正しています。デモサーバで削除を確認しました。
http://enju.next-l.jp/carrier_types/10

**Comment by yegusa** [comment]
デモサーバーで確認しましたのでクローズします。

http://enju.next-l.jp/carrier_types/10

CDが登録されている
![image](https://cloud.githubusercontent.com/assets/1328499/5992044/dedaa634-aa58-11e4-8b6a-9f767f109601.png)

削除をクリックして、更新
![image](https://cloud.githubusercontent.com/assets/1328499/5992048/e8244f42-aa58-11e4-94f3-8f8a7e3414ed.png)

削除された
![image](https://cloud.githubusercontent.com/assets/1328499/5992051/f0c2fd88-aa58-11e4-8194-25be6e384c32.png)
