### ISSUE TITLE
バグ？：きり図書館の所蔵が表示されません（検索結果一覧と書誌詳細）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#544]
#468 をチェックしようと思って、遭遇した現象です。
#468 とは別かもしれないので別issueとして立ち上げておきます。

たちばな図書館の本棚ときり図書館の本棚にとうろくした本が2冊ある書誌ですが、

たちばな図書館の本棚のものしか表示されません。
http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/5989454/2d3267fa-a9cc-11e4-89b5-a40b929eeb93.png)

ちなみに、書誌詳細でも表示されません。
http://enju.next-l.jp/manifestations/4942
![image](https://cloud.githubusercontent.com/assets/1328499/5989474/b141a97a-a9cc-11e4-8456-e49ec5715b19.png)

所蔵一覧では表示されます
http://enju.next-l.jp/items?manifestation_id=4942
![image](https://cloud.githubusercontent.com/assets/1328499/5989479/d212c7a6-a9cc-11e4-8bbb-f848dd939696.png)

**Comment by nabeta** [comment]
ログインしていない状態では2件表示されるので、ユーザごとの処理、具体的には #468 の影響によるものと思います。いったん変更を元に戻して確認します。

**Comment by nabeta** [comment]
@yegusa #468 のマイルストーンとしてrc18が割り当てられているため、これもrc18にしたほうがよいのではないでしょうか。

**Comment by yegusa** [comment]
あら、そうかそうですね。 rc18にしときました。

**Comment by yegusa** [comment]
#468 をクローズできたら、こちらもクローズできるはず。 #468 を先にやること。

**Comment by masao** [comment]
再現しないようなので、クローズします。
