### ISSUE TITLE
バグ？：NDLサーチ検索によるインポートでのタイトル「じゃらん」になる（「じゃらん 関東・東北」）（雑誌のインポート）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#546]
- [ ] 確認
- [ ] マニュアル修正 #1191 

じゃらん 関東・東北
http://enju.next-l.jp/manifestations/4922/edit
![image](https://cloud.githubusercontent.com/assets/1328499/6038023/d53fb56a-ac9c-11e4-8920-9ffa23393f6d.png)

雑誌のインポート対応はまだできていないのであれですが、
覚書としてissue登録しておきます。

参考：
http://iss.ndl.go.jp/books/R100000002-I000011225479-00
http://id.ndl.go.jp/bib/000011225479
http://www.jalan.net/jalan/doc/top/honsi/honsi_index.html

**Comment by masao** [comment]
なお、雑誌情報インポートのIssueは #72 です。
さきほど、雑誌取り込みの基本的な部分に対応するコード next-l/enju_ndl#16 を取り込みましたので、順次こちらへの対応も進められると思います。

**Comment by nabeta** [comment]
どうもありがとうございます。よさそうに思います。
先ほどデモサーバにも反映しました。

一点お願いですが、他のソースコードにあわせるため、インデントにはタブのかわりに半角スペース2つを使用していただけますでしょうか。

**Comment by masao** [comment]
本Issueに関してですが、「関東・東北」は dcndl:volumeTitle に記録されています。

http://www.ndl.go.jp/jp/aboutus/standards/meta.html
「DCNDL仕様書　第二部　Application Profile 」より：
> 使用法：
> 多巻もののタイトルをDC Title又はDCTERMS Titleに採用した場合、各巻のタイトルはここに収める。
> また、一つの逐次刊行物が部又は編に分かれて刊行される時、その部又は編に付けられたタイトルもここに収める。

後段の逐次刊行物の用法だと思われます。

**Comment by yegusa** [comment]
1.1.0.rc17の仮想マシンでやってみましたが、だめでした。

http://localhost:8080/manifestations/2/edit
![image](https://cloud.githubusercontent.com/assets/1328499/7201619/36f34c24-e544-11e4-82e5-57a6658a23ec.png)

**Comment by yegusa** [comment]
ああ、だめでしたというのじゃなくて、まだ、このタイトルの件はなにもやってないのですね。
* NCR で この「部編名	関東・東北」の扱いをどうするかを確かめる
* マッピングは、タイトルに入れ込むのか？ 部編名という新しいフィールドをつくるのか？　代替タイトルにいれるのか？あたりでしょうか？（今のところ案）

**Comment by yegusa** [comment]
ちなみにNDL-OPACでは「じゃらん. 関東・東北」ってなってるみたいです。

https://ndlopac.ndl.go.jp/F/5DHND8G78XX6FEIFVXRM5MP732XCD38JQUQV1S7J69EXST4VCB-20596?func=find-a&find_code=WTYP&request=%E9%9B%91%E8%AA%8C&request_op=AND&find_code=WRD&request=&request_op=AND&find_code=WTI&request=%E3%81%98%E3%82%83%E3%82%89%E3%82%93&request_op=AND&find_code=WAU&request=&request_op=AND&find_code=WPU&request=&request_op=AND&find_code=CALL&request=&request_op=AND&find_code=&request=&request_op=AND&find_code=&request=&request_op=AND&find_code=&request=&chk_bigram=on&adjacent=N&chk_fmt_SE=on&filter_code_4=WSL&filter_request_4=&filter_code_2=WYR&filter_request_2=&filter_code_3=WYR&filter_request_3=&filter_code_1=WLNT&filter_request_1=&x=107&y=13

**Comment by masao** [comment]
だいぶ前のIssueでもありますし、ひとまずは、 original_title として追加してみることにしました。ご確認ください。

**Comment by yegusa** [comment]
手元の仮想マシンで、タイトルに「関東 東北」がはいることを確認しました。のでクローズします。
マニュアルは後で修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/18812543/2b3960bc-8313-11e6-8e99-95855496b671.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18812549/65e1e892-8313-11e6-88df-a025220f6792.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18812558/a49bd0fc-8313-11e6-8834-a5d9d06e1571.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 dfc3604)
  * enju_circulation (0.2.0.beta.3)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3)
  * enju_library (0.2.0.beta.9)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
vagrant@vagrant-ubuntu-trusty-64:~/enju$
