### ISSUE TITLE
バグ：NDLサーチインポートでシリーズ著者がインポートされない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#547]

**Comment by masao** [comment]
https://github.com/next-l/enju_ndl/commit/9d975ded3f40574c0585f8a05fdce4b091971010 にて対応済み。要確認。

**Comment by yegusa** [comment]
仮想マシンで最新ソースでできることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/7489215/5b885802-f40f-11e4-8774-33a6bfb4ff12.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7489232/75996d8a-f40f-11e4-8e96-90381a9a3b50.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 f29f883)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 7949d16)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)
