### ISSUE TITLE
NDLサーチインポートにおける内容種別の対応を追加

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#548]
next-l/enju_ndl#15 における修正を取り込みます。

**Comment by nabeta** [comment]
上記の修正を含んだモジュールを enju_ndl-0.1.0.pre36 としてリリースしました。

**Comment by masao** [comment]
了解です。さすがにだいぶ前から動かしているので、要確認もなにもなさそうなので、ひとまずクローズしますね。
