### ISSUE TITLE
貸出をするとレンダリング中にエラーが発生

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#550]
「貸出資料の新規作成」で「上記の資料を貸し出す」をクリックするとエラーが発生します。
セットアップ漏れでしょうか？

対象バージョン： Next-L Enju Leaf 1.1.0.rc17 + Next-L Enju Flower 0.1.0.pre21

エラーメッセージの抜粋とエラー画面は以下のようになっています。

```
NoMethodError in Checkouts#index
Showing /home/nakamura.akifumi/app/enju_leaf_app/vendor/bundle/ruby/2.2.0/gems/enju_circulation-0.1.0.pre42/app/views/checkouts/_index_user.html.erb where line #27 raised:

undefined method `checkout_icalendar_token?' for #<User:0x007fd030dd1320>
```

![2015-02-27 14 01 30](https://cloud.githubusercontent.com/assets/1065528/6407733/4eb91dfc-be89-11e4-869c-0d8a4c4feef4.png)

**Comment by yegusa** [comment]
デモサーバーだと、その症状でませんね。

**Comment by nakamura-akifumi** [comment]
wiki のインストールマニュアルに沿って sqlite と postgresql で再度試してみましたが、同じでした。

環境は、linux (CentOS 7) で development / production ともにです。

（http://rails.tmpz84.info　で確認することが出来ます。）

**Comment by yegusa** [comment]
http://rails.tmpz84.info
アクセスできません。。。

@masao さんが、なんかあやしそうなところは見つけたといってました。

**Comment by nakamura-akifumi** [comment]
すみません、DNSの設定を忘れてました。今はアクセス出来るようになってます。
macでも試してみましたが、同じ症状です。

**Comment by yegusa** [comment]
私がやってみたら、We're sorry になりました。管理者ID(enjuadmin)だからか、ちょっと違うのかな？

![image](https://cloud.githubusercontent.com/assets/1328499/6424219/a73dc5be-bf37-11e4-8cfa-ddb94cd93c29.png)

**Comment by nakamura-akifumi** [comment]
図書館員権限で操作しても同様のエラーになりました。

**Comment by nabeta** [comment]
Gemfileのenju_circulationを以下のようにして試してください。

```ruby
gem 'enju_circulation', github: 'next-l/enju_circulation', branch: '1.1'
```

**Comment by nakamura-akifumi** [comment]
Gemfileを修正し試したところ、問題なく貸出できました。

**Comment by yegusa** [comment]
@nakamura-akifumi  さんが確認したとのことなので、クローズします。
