### ISSUE TITLE
enju_circulation #550 をリリースする。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#553]
#550 貸出ができないという致命的なバグなのでenju_circulationのモジュールだけでも、早々にリリースする。
Enju WS 2015-02-28にて。

**Comment by nabeta** [comment]
enju_circulation-0.1.0.pre43としてリリースしました。
https://rubygems.org/gems/enju_circulation/versions/0.1.0.pre43

**Comment by yegusa** [comment]
クローズします。
