### ISSUE TITLE
質問：VM版のモジュール追加について

### ISSUE THREAD

**Issue by meinherzjin** [next-l/enju_leaf#554]
おつかれさまです。
オープンソース図書システムを勉強している韓国のソフトウェアエンジニアです。
日本語が上手ではないですが、あらかじめ承知お願いします。

対処バージョン：Next-L Enju Leaf 1.1.0.rc16 64bit版(zipファイル) （VirtualBox用)
VirtualBox版のVMDKファイルを利用して、VMware vSphereで起動しています。

IP設定やWeb接続はうまくできました。
だが、「第5章 モジュールの追加」で進むことができない状況です。
（https://next-l.github.io/manual/enju_install_vm_5.html）

以下は私がやったステップです。

[Step]
1. sudo stop enju_leaf
1. enju/Gemfile に以下の一行を追加
   gem "enju_purchase_request", '~> 0.1.0.pre13'
2. bundle update
3. rake enju_purchase_request_engine:install:migrations

「結果」
rake aborted!
You have already activated rake 10.1.0, but your Gemfile requires rake 10.4.2. Prepending `bundle exec` to your command may solve this.
/var/lib/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:34:in `block in setup'
/var/lib/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/runtime.rb:19:in`setup'
/var/lib/gems/2.1.0/gems/bundler-1.7.4/lib/bundler.rb:121:in `setup'
/var/lib/gems/2.1.0/gems/bundler-1.7.4/lib/bundler/setup.rb:7:in`<top (required)>'
/home/vagrant/enju/config/boot.rb:4:in `<top (required)>'
/home/vagrant/enju/config/application.rb:1:in`<top (required)>'
/home/vagrant/enju/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

GOOGLEでエラーメッセージとして探してみても、よくわかりませんでした。
ここでどうすれば次に行けましょうか？
ぜひ、ご回答お願いいたします。

**Comment by nakamura-akifumi** [comment]
step3で

rake enju_purchase_request_engine:install:migrations

の代わりに

bundle exec rake enju_purchase_request_engine:install:migrations

と入力してみてください。

rake コマンドを実行するときに失敗する場合は、bundle exec rake ～ と実行するとエラーが解消する場合があります。

# 私よりも日本語は上手ですよ ...

**Comment by meinherzjin** [comment]
nakamura-akifumiさん//

教えてくださった方法で成功しました。
回答ありがとうございました！！
その以降のステップは問題ありませんでした。

しかし、これはちょっと別の件だと思いますが、
追加された「購入リクエスト」メニューで、リクエストを新規作成しようとすると

以下のエラーメッセージが出ます…T.T

-------------------------------------------------------
購入リクエストに3個のエラーが発生しました。
次の項目を確認してください。
タイトルを入力してください。
タイトルを入力してください。
Userは不正な値です。
-------------------------------------------------------

タイトルを英語、日本語、韓国語　どちらに入力してみても同じです。
特に他の設定を修正したりもしません。
Next-L Enju Leaf 1.1.0.rc17　バージョンと　enju_purchase_request RC13モジュールが
合わないのが原因なんでしょうか…

ユーザの権限は管理者でもユーザでもダメでした。

私と同じ問題があった方は助けてください。＾＾;

**Comment by yegusa** [comment]
@nabeta さん、わかります？

**Comment by meinherzjin** [comment]
production.log には以下のような内容がありました。


I, [2015-04-17T12:13:21.626053 #22767]  INFO -- : Started POST "/purchase_requests" for 127.0.0.1 at 2015-04-17 12:13:21 +0000
I, [2015-04-17T12:13:21.631214 #22767]  INFO -- : Processing by PurchaseRequestsController#create as HTML
I, [2015-04-17T12:13:21.631469 #22767]  INFO -- :   Parameters: {"utf8"=>"✓", "authenticity_token"=>"RmrIcnJ0WAMRn8xyIfyKT34EmcDo6+siZfhENqMJ0Ss=", "purchase_request"=>{"title"=>"Book Title", "author"=>"Test User", "publisher"=>"Test ", "isbn"=>"9791185014906", "pub_date"=>"2015-04-20", "price"=>"66600", "url"=>"http://www.yes24.com/24/Goods/17378537", "note"=>"Note"}, "commit"=>"등록한다"}
W, [2015-04-17T12:13:21.667266 #22767]  WARN -- : WARNING: Can't mass-assign protected attributes for PurchaseRequest: title, author, publisher, isbn, price, url, note, pub_date

W, [2015-04-17T12:13:21.727508 #22767]  WARN -- : WARNING: Can't mass-assign protected attributes for PurchaseRequest: title, author, publisher, isbn, price, url, note, pub_date

I, [2015-04-17T12:13:21.790087 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_purchase_request-0.1.0.pre13/app/views/purchase_requests/_new.html.erb (22.1ms)
I, [2015-04-17T12:13:21.790396 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_purchase_request-0.1.0.pre13/app/views/purchase_requests/new.html.erb within layouts/application (23.0ms)
I, [2015-04-17T12:13:21.796443 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_leaf-1.1.0.rc17/app/views/page/_include.html.erb (5.3ms)
I, [2015-04-17T12:13:21.799981 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_manifestation_viewer-0.1.0.pre17/app/views/manifestations/_google_book_thumbnail_header.html.erb (0.5ms)
I, [2015-04-17T12:13:21.827989 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_leaf-1.1.0.rc17/app/views/page/_select_locale.html.erb (0.2ms)
I, [2015-04-17T12:13:21.828335 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_leaf-1.1.0.rc17/app/views/page/_header.html.erb (27.9ms)
I, [2015-04-17T12:13:21.876483 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_leaf-1.1.0.rc17/app/views/page/_menu.html.erb (47.5ms)
I, [2015-04-17T12:13:21.879022 #22767]  INFO -- :   Rendered vendor/bundle/ruby/2.1.0/gems/enju_flower-0.1.0.pre21/app/views/page/_footer.html.erb (1.9ms)
I, [2015-04-17T12:13:21.907606 #22767]  INFO -- : Completed 200 OK in 276ms (Views: 93.5ms | ActiveRecord: 5.2ms | Solr: 18.6ms)

**Comment by nabeta** [comment]
この問題は以下のコミットで修正しており、0.1.0.pre14以降のリリースに反映されています。
https://github.com/next-l/enju_leaf/issues/649

ただ、2023年現在ではモジュールの追加はサポートしていないため、イシューとしてはクローズします。

@meinherzjin  長い間お返事をしておらず、たいへん失礼いたしました。申し訳ありません。
