### ISSUE TITLE
質問：表示言語追加について

### ISSUE THREAD

**Issue by meinherzjin** [next-l/enju_leaf#555]
こんにちは。質問ばかりでごめんなさい…

ホーム画面の「Other languages」をクリックした時、英語や日本語以外の言語を選べるようにしたいですが、どこを変更すればいいでしょうか？

表示されるメニューのリソースは以下のパスなどに言語ファイルを作って入れたら表示されることは
理解しています…
/home/vagrant/enju/vendor/bundle/ruby/2.1.0/gems/enju_xxxxxxxxx/config/locales

ここに合わないイシューであれば削除お願いします。

**Comment by nabeta** [comment]
> 表示されるメニューのリソースは以下のパスなどに言語ファイルを作って入れたら表示されることは
理解しています…
> /home/vagrant/enju/vendor/bundle/ruby/2.1.0/gems/enju_xxxxxxxxx/config/locales

その場所でもよいですが、モジュールがアップデートされるとファイルををコピーし直さなければならないので、 /home/vagrant/enju/config/locales/ 以下に言語ファイルを置くことをおすすめします。

> ホーム画面の「Other languages」をクリックした時、英語や日本語以外の言語を選べるようにしたいですが、どこを変更すればいいでしょうか？

1\. Enjuを停止します。
```sh
$ sudo stop enju_leaf
```
2\. 言語ファイルを作成し、config/locales/ 以下に保存します。韓国語の場合、"custom.ko.yml"のように、".ko.yml"で終わるファイル名にしてください。
3\. config/application.rb の以下の行を変更します。  
```ruby
# 変更前
config.i18n.default_locale = :ja
config.i18n.available_locales = [:en, :ja]
```
 ```ruby
# 変更後
config.i18n.default_locale = :ko
config.i18n.available_locales = [:ko, :en, :ja]
```
4\. HTMLのキャッシュを削除します。
```sh
$ rails c production
> Rails.cache.clear
> exit
```
5\. Enjuを起動します。
```sh
$ sudo start enju_leaf
```

もしわからなかったり、うまくいかなかったりしたら、お気軽におたずねください。

**Comment by meinherzjin** [comment]
ご回答本当にありがとうございます。

説明の通り韓国語もメニューに追加できました。
素晴らしいです。＾＾；

言語ファイルの場合、濃くモジュールのロケールファイル名が同じですが、
 /home/vagrant/enju/config/locales　このパスにどのような仕組みで入れたらいいのでしょうか？

たとえばtranslation_ja.ymlファイルはenju_libraryフォルダにも入ってますし、enju_eventフォルダにも入っているので…

**Comment by nabeta** [comment]
いくつか方法があります。

1. モジュールごとに別のファイル名をつける。 たとえば、enju_libraryのtranslation_ja.yml を enju_library.ko.yml という名前で、enju_eventのtranslation_ja.yml を enju_event.ko.yml という名前で config/locales/ にコピーする
2. 各モジュールのロケールファイルの中身をひとつのファイルに書く。たとえば、enju_libraryやenju_eventのtranslation_ja.yml の中身を、config/locales/translation_ko.yml というひとつのファイルにコピーする

**Comment by meinherzjin** [comment]
１の方法で適用できました。
リソースファイル名とは関係なく、中にある変数名でマッピングされるらしいですね

お忙しいところ、ご回答ありがとうございます。

**Comment by yegusa** [comment]
解決されたようですので、クローズしますね。
