### ISSUE TITLE
必須フィールドの目印が凡例と異なる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#560]
required フィールドの凡例とことなり、必須フィールドのマークが赤字になっていないのが長いこと気にはなっていたので、バグとしてあげておきます：

![20150402-enju-requierd](https://cloud.githubusercontent.com/assets/38825/6956321/31ad2286-d927-11e4-8931-2d845ed67302.png)

**Comment by masao** [comment]
一応、直してみましたが、かなりアドホックなので・・・アレです。
（日本語と英語の場合しか考慮してない）

素直に、class 属性をつけたほうがよいですね。きっと。念のため。

**Comment by nabeta** [comment]
これは[simple_form](https://github.com/plataformatec/simple_form)というライブラリに関係します。このライブラリには、ActiveRecordのモデルでvalidationが定義されていると、そのvalidationの対象の属性を入力するフォームに自動的にマークをつけてくれるという機能があります。ただ、名前に反していまいち見た目がカスタマイズしにくく、そのまま放置してしまっていました。
そもそもsimple_formを使い続けるかどうか、という点を考えさせてください。

**Comment by masao** [comment]
そもそもの問題は解決しているので、Issueを分けませんか？

**Comment by yegusa** [comment]
とりあえず、解決しているようなので、クローズします。simple_formの件は別issueにします。

**Comment by nabeta** [comment]
simple_form は属性名に config/locales/ 以下のロケールファイルを使用する仕様になっているようです。日本語のロケールファイルを修正し、属性名に日本語を使用しないようにしました。
