### ISSUE TITLE
質問:インポートファイルの上限

### ISSUE THREAD

**Issue by izuru** [next-l/enju_leaf#562]
資料のインポートファイルを10000件程度入れたら、大きすぎますよとエラーを返されました。1000件ですと大丈夫でした。上限はどの程度に設定してありますか？

**Comment by nabeta** [comment]
特に上限は設定していないです。表示されたエラーメッセージを教えていただけますでしょうか。

**Comment by izuru** [comment]
"413 Request Entity Too Large" ですね。アップロードするファイルサイズの上限でしょうか。

**Comment by nabeta** [comment]
そのエラーですと、Webサーバ側の上限に引っかかっているようです。
お使いの環境はNext-Lで提供している仮想マシンでしょうか？

**Comment by izuru** [comment]
そうですね。VirtualBoxで動かしています。

**Comment by masao** [comment]
#1021 でほぼ同様の質問が出た際に確認したところ、仮想マシンのデフォルト設定が 1MB 上限だったようですので、設定変更することで解決するようです。

**Comment by yegusa** [comment]
@izuru　さん、
解決方法は #1021 かマニュアル https://next-l.github.io/manual/enju_install_vm_11.html を参照ください。

**Comment by yegusa** [comment]
@izuru さんからのコメントありませんが、解決はしているはずなので、いったんはクローズします。
