### ISSUE TITLE
請求記号等の半角カナデータのインポートがうまくいかない

### ISSUE THREAD

**Issue by izuru** [next-l/enju_leaf#563]
標題のとおりですが、請求記号等を半角カナで入れている図書館はけっこうあると思います。これは、ラベル印字する時の横幅を節約するためなどの理由です。どうも、半角カナでインポートするとうまく反映されず、場合によっては、項目がずれて別の所蔵事項が入ってくることがあるようです。全角カナだとうまくインポートできました。

**Comment by izuru** [comment]
全てがうまくいっていないわけではなく、「M/726.1/ﾌｼﾏｷ｣などはうまく入っていますが、「/498.55/ﾀ」などは、「498.55/次の項目」といった形でインポートされます。

**Comment by izuru** [comment]
「/913.6/ｲｹﾀ」などはインポートされていますので、半角カナ1文字だとだめなのかな？

**Comment by yegusa** [comment]
これはなやましいですね。使いたくなる気持ちはわからなくもないですが。。。Enjuとしてどう対応するかは議論したいですね。私の個人的な意見としては、半角カタカナは使わない運用をしてただくのがいいんじゃないかなあと思います。

**Comment by nabeta** [comment]
@izuru インポート時の文字コードを教えていただけますか？

**Comment by yegusa** [comment]
ちなみに、文字コードを指定してインポートしてもだめですか？

**Comment by izuru** [comment]
文字コードはshift-jisです。文字コードを指定してインポートしたらうまくいきましたので、これは指定して運用すればいいかもしれません。

**Comment by yegusa** [comment]
そうですね。最低限、マニュアルあたりに、Q&Aとしてあるといいかんじでしょうか。

**Comment by nabeta** [comment]
ちなみに、システム内部ではすべてUTF-8として扱っています。Shift_JISで書かれたアップロード用ファイルは、UTF-8に変換されてインポートされます。

**Comment by yegusa** [comment]
とりあえず、文字コードを指定したらうまくいくようですので、クローズします。
