### ISSUE TITLE
要望：資料検索のメニューが欲しい

### ISSUE THREAD

**Issue by izuru** [next-l/enju_leaf#564]
資料検索は、一番上部の図書館名をクリックして、トップページに戻ってから行なうという理解でよいのでしょうか。「貸出・返却・予約」「資料の受入」の並びに資料検索もあった方がよいように思います。公共系のシステムですと、窓口業務と管理業務がまず分かれており、そのそれぞれに資料検索があるような。

**Comment by yegusa** [comment]
> 資料検索は、一番上部の図書館名をクリックして、トップページに戻ってから行なうという理解でよいのでしょうか。

そうですね。

> 「貸出・返却・予約」「資料の受入」の並びに資料検索もあった方がよいように思います。

a) 「貸出・返却・予約」「資料の受入」の両方に、資料検索がある
b) 「貸出・返却・予約」のみに、資料検索がある
c) 「資料の受入」のみに、資料検索がある 

ちなみに、a, b, c のどれがよさそうに思います？

**Comment by izuru** [comment]
利用者が使用するメニューで(も)あることを考えると、b でしょうか。

**Comment by masao** [comment]
メニューに追加してみました：
![image](https://cloud.githubusercontent.com/assets/38825/9173123/0ca0d990-3fb3-11e5-9b81-6172d32f2d51.png)
こんな感じかな。

**Comment by yegusa** [comment]
メニューの位置ですが、
- 一番下
- 3番目　（貸出、返却、資料の検索　の順）

あたりでどうでしょう。

**Comment by masao** [comment]
一番下に追加しました。

**Comment by yegusa** [comment]
一番したにあることを確認しました。
たどると、検索画面にいくことも確認しました。
ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10362794/a751d230-6deb-11e5-927b-392c8d9d850b.png)

http://localhost:8080/manifestations
![image](https://cloud.githubusercontent.com/assets/1328499/10362789/9ff6fd26-6deb-11e5-8ffd-b95a96107bd6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 574817f)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
