### ISSUE TITLE
要望：「条件を詳しく指定して検索」に分類(NDC)の項目が欲しい

### ISSUE THREAD

**Issue by izuru** [next-l/enju_leaf#565]
標記のとおりです。よく利用する検索項目ですので。

**Comment by izuru** [comment]
・業務では「本棚(所蔵場所)」「請求記号」「受入日」等でも検索します。
・資料の形態、所蔵図書館名は検索前にも絞り込みができるのが一般的です。
(別のissueで書いた方がよかったでしょうか)

**Comment by yegusa** [comment]
とりあえず、検索式（のコマンド）でできないか、調べて答えます。まあ、たしかに、入力フォームあったほうがよいような気もします。

**Comment by masao** [comment]
分類検索の検索式は、書誌詳細からリンクがついてるのでそれをご確認ください。

**Comment by izuru** [comment]
ちょっと慣れた利用者なら分類検索はするかな、とも思います。コミックを726.1で検索するなど。

**Comment by yegusa** [comment]
classification_sm:ndc9_673.3

こんなかんじの検索式ですね。
http://enju.next-l.jp/manifestations?query=classification_sm%3Andc9_673.3
![image](https://cloud.githubusercontent.com/assets/1328499/7171260/1f1d0844-e411-11e4-8fc6-606792a9503d.png)

**Comment by yegusa** [comment]
前方一致の例

classification_sm:ndc9_91*

http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=classification_sm%3Andc9_91*&commit=%E6%A4%9C%E7%B4%A2

![image](https://cloud.githubusercontent.com/assets/1328499/7171326/d1ab98c2-e411-11e4-8006-dd25fa6d9917.png)

**Comment by yegusa** [comment]
> ・業務では「本棚(所蔵場所)」「請求記号」「受入日」等でも検索します。

→ 別issue にしました

> ・資料の形態、所蔵図書館名は検索前にも絞り込みができるのが一般的です。
> (別のissueで書いた方がよかったでしょうか)

→　別issuにしました

開発作業、確認作業、もろもろ、別isseuの方がやりやすいので、別issueにしました。

**Comment by yegusa** [comment]
インタフェースを考えてみましたが、複数の分類がある場合はどうするのかなあ。検討必要かなと。

http://enju.next-l.jp/page/advanced_search

案1) 分類の種類ごと：
![image](https://cloud.githubusercontent.com/assets/1328499/7193832/e7a0dffa-e4e0-11e4-9d47-190f124ae400.png)

案2) まとめて検索：　（区別したい場合は "NDC:931" 等度検索する？）
![image](https://cloud.githubusercontent.com/assets/1328499/7193864/2e3a020c-e4e1-11e4-804c-03d3ab1f1bb6.png)

**Comment by izuru** [comment]
NDL-OPACの場合、NDCとNDLCは同じフォームで検索するようになっていたと思います。まああれは記法そのものが違うので、バッティングはしないのですが。

**Comment by nabeta** [comment]
> インタフェースを考えてみましたが、複数の分類がある場合はどうするのかなあ。検討必要かなと。

これも以下のようにドロップダウンメニューで指定できるようにするのはどうでしょうか。

```
分類: [NDC ▼] [          ]
```

**Comment by yegusa** [comment]
そうねえ。いいかも。

**Comment by izuru** [comment]
ドロップダウンメニューで指定はいいかと思います。検索項目の選択自体を全てドロップダウンメニューにしてあるものがよく見られます。(NDL-OPAC等)

**Comment by masao** [comment]
next-l/enju_biblio@3a3d9ca7cbeffa4ff199417e3f8f7fcd585b5ba9 にて機能を追加しました。

**Comment by yegusa** [comment]
前方一致検索なんですね。
まあ、自然でよいですよね。

仮想マシンで確認しました。できているとおもいますので、クローズします。

007 を入力しているところ
![image](https://cloud.githubusercontent.com/assets/1328499/9839703/bd465f62-5abc-11e5-920b-a01b6ddb0a30.png)

検索結果：007の前方一致検索になっている
![image](https://cloud.githubusercontent.com/assets/1328499/9839721/16eda458-5abd-11e5-8bb8-f010e22245e7.png)

完全一致検索をしたい場合：「classification_sm:ndc9_007」として、*をとって検索したところ
![image](https://cloud.githubusercontent.com/assets/1328499/9839732/32ed0f72-5abd-11e5-8287-392770615570.png)

スクリーンショットはとってませんが、以下についても確認しています。
- 書誌にNDCしか入力していない場合は、検索メニューが「NDC」しかないこと
についても確認しました。

DDCを入力した書誌があると、検索メニューに「DDC」が出てくる
![image](https://cloud.githubusercontent.com/assets/1328499/9839767/044064ac-5abe-11e5-9ccc-edeb17f7b19c.png)

DDCで検索したところ
![image](https://cloud.githubusercontent.com/assets/1328499/9839743/720d6634-5abd-11e5-8dea-3664869cc65c.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7b5fb10)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 40fc6a9)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
