### ISSUE TITLE
要望：検索された資料一覧の表示件数は10～100件程度で選択できる

### ISSUE THREAD

**Issue by izuru** [next-l/enju_leaf#566]
選択できるOPACが一般的なような気がします。NDL-OPACは、20、50、99の選択。

**Comment by yegusa** [comment]
これ、どういうときに、あるとうれしいなあと思われますか？→ @izuru さん。

**Comment by yegusa** [comment]
GUIはこんな感じかしら。
メニューで選ぶかんじ。

![image](https://cloud.githubusercontent.com/assets/1328499/7139576/058a1d50-e302-11e4-9257-3cbd69b5f5ee.png)

**Comment by izuru** [comment]
そうですね。わりとメニューで選ぶタイプのOPACが多いと思います。

**Comment by nabeta** [comment]
準備作業として、以下のコミットで、検索結果の表示数などの設定値をデータベース上に持てるようにしています。実際の検索動作は1.1.0.rc18で実装予定です。
https://github.com/next-l/enju_library/commit/6668d8df3af565fdeec4689c11401733fa17aadf

**Comment by yegusa** [comment]
いつの間にかできるようになってましたね。。。

https://github.com/next-l/enju_leaf/issues/570

↑で確認作業は終了していますのでクローズします。
