### ISSUE TITLE
要望：検索結果一覧に「分類」（リンクあり）が表示されて欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#569]
#567 から分岐したissueです。

**Comment by nabeta** [comment]
タイトルの横あたりに「NDC: 007」のように表示されていればよいでしょうか。
請求記号は所蔵情報に表示されています。「所蔵」リンクをクリックする・しないの問題はありますが。

**Comment by yegusa** [comment]
近々に（？）開発予定の別issue #31 で、以下のように、所蔵がデフォルトで1,2件表示されるのですが、
請求記号を表示したいというのでしたら、それで間に合いますよね？

![image](https://cloud.githubusercontent.com/assets/1328499/7170619/c6082262-e40a-11e4-8484-3df1646f5ec1.png)

**Comment by yegusa** [comment]
私も検索一覧に、分類があったほうがよいような気がします。
分類は書誌だし、請求記号は所蔵の情報なので、別issueにしますね。
こちらは、「分類」ということにしましょう。

**Comment by yegusa** [comment]
こんな感じ？（ちょっとカッコ悪いかも） →　@izuru さん。
![image](https://cloud.githubusercontent.com/assets/1328499/7171057/d3640288-e40e-11e4-9ce3-017be7b9da49.png)

Enju は書誌に複数の分類がつけられるので、そこをどう表示したもんかとは思いますね。

**Comment by izuru** [comment]
はい。これでもいいですが、書誌事項という意味では、著者、出版社の並びにあった方がよいでしょうか。

**Comment by yegusa** [comment]
そうしてみました。たしかに、よさそうですね。
![image](https://cloud.githubusercontent.com/assets/1328499/7193533/e237c29e-e4dc-11e4-992b-a992dbcc56b0.png)

**Comment by izuru** [comment]
あとは、このNDCも検索リンクになってますとより良いかと思います。

**Comment by yegusa** [comment]
> あとは、このNDCも検索リンクになってますとより良いかと思います。

たしかに～。NDC検索リンクにする件は、別issueにします（さっとできることかどうかわからないので）
じゃあ、ここは、リンクにしましょう。簡単にできそうなので、issueは分岐させません。

こんな感じですね。
![image](https://cloud.githubusercontent.com/assets/1328499/7213209/8834fc00-e5b1-11e4-9385-3dd72015f770.png)

**Comment by nabeta** [comment]
分類の表示を追加しました。
http://dev.next-l.jp/manifestations?commit=検索&query=&utf8=✓

**Comment by yegusa** [comment]
あ、すみません、セミコロンほしいです。
![image](https://cloud.githubusercontent.com/assets/1328499/7215295/00b23b34-e60c-11e4-8dc2-e914e1a5fee6.png)

**Comment by nabeta** [comment]
分類が表示されるときには、区切りとしてセミコロンを入れるようにしました。

**Comment by yegusa** [comment]
セミコロンの前には空白ないほうがいいとおもうけど。ま、いっか。
クローズします。
![image](https://cloud.githubusercontent.com/assets/1328499/7215609/7856978e-e61b-11e4-92a3-84734981f585.png)
