### ISSUE TITLE
要望：出版日(出版年)のソートは降順だけでなく昇順も選択できるようにして欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#570]
要望：出版日(出版年)のソートは降順だけでなく昇順も選択できるようにして欲しい
#567 から分岐したissueです。

イメージ：http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/7134222/a917f71c-e2d5-11e4-821e-b4b1a3a5a459.png)

**Comment by yegusa** [comment]
今後、ソート項目が増えてもやりやすいように、ソート順の選択は、メニュー選択がいいですね。
（他のissueで話題になりましたので、こちらにも書いておきます）

出版日（新しい順）
出版日（古い順）

![image](https://cloud.githubusercontent.com/assets/1328499/7170441/22274f8e-e409-11e4-988b-9f173b9345f7.png)

**Comment by nabeta** [comment]
並べ替え用のフォームを追加しました。出版年はデフォルトを降順（新しいもの順）にしたほうがよい気がしますが、現時点ではまだ昇順のままです。また、「作成時刻」というのは書誌の作成時刻のことです（1.1系ではラベルが「受入日」となっていますが、正確には書誌の作成時刻でソートしています）。

![fireshot capture 30 - - next-l enju leaf_ - http___dev next-l jp_manifestations](https://cloud.githubusercontent.com/assets/11428/12033637/6f869170-ae68-11e5-90eb-e51577990dc8.png)

**Comment by yegusa** [comment]
「検索」は「表示」のほうがよいかと。

あと、元々の私の提案でもあるように、メニューを1つ減らして、
項目と昇順かどうかを1回のメニュー操作で選べるようにしてほしいです。
（CiNiiでもそうしてますし）

あと、10件表示とかは左右逆のほうがいいかも。

@yegusa 案：
![image](https://cloud.githubusercontent.com/assets/1328499/12066242/1e88f3e6-b028-11e5-9445-a4fa0dc798a8.png)

* 出版日：新しい順
* 出版日：古い順
* タイトル：五十音順
* タイトル：五十音逆順
* 作成時刻：新しい順
* 作成時刻：古い順

↑　こんなかんじで。

参考：CiNii
![image](https://cloud.githubusercontent.com/assets/1328499/12066145/e64a47e8-b025-11e5-8f40-c1fa828975a9.png)

@nabeta 案
![image](https://cloud.githubusercontent.com/assets/1328499/12066298/f18ca404-b028-11e5-9612-7ff6c2e7de0e.png)

**Comment by masao** [comment]
「作成時刻」には違和感があります。何を作成したのかわからないので。
また、時刻に意味をもたせることはないと思うので、表示上は「書誌作成日」にしておきましょうか。
「書誌レコード作成日」または「レコード作成日」くらいでもよいかもしれませんが。

**Comment by yegusa** [comment]
わたしも「作成時刻」には違和感あったのですが、
いい案が浮かばなかったコメントしてなかったのですが、
「書誌作成日」　いいですね。

**Comment by masao** [comment]
ひとまず、「作成時刻」は「書誌作成日」に変更してみました。

**Comment by masao** [comment]
ひとまず、元の提案にあわせ、ソート順の選択フォームをひとつにまとめるように修正しました。
![enju_issues_570](https://cloud.githubusercontent.com/assets/38825/12529506/6b53f0be-c1fc-11e5-9c57-5b9a796232bf.png)

**Comment by yegusa** [comment]
* 提案した通りのメニューになっていることを確認しました。
* ソート順がメニューで指定したとおりにかわることを確認しました。
* 件数も指定したとおりの件数が表示されることを確認しました。

（ただし、件数はのメニューはつねに10件になってしまうようですこちらは
　別issueとしてあげます。）

![image](https://cloud.githubusercontent.com/assets/1328499/12554314/2e78f698-c3bf-11e5-94c0-bf64f44c1f9b.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12554338/4b3285f6-c3bf-11e5-91e9-00e60068f29b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 47e3a3a)
  * enju_circulation (0.2.0.beta.1 d2bbdb9)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 25c8ca5)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 b797995)
vagrant@vagrant-ubuntu-trusty-64:~/enju$

初期状態
![image](https://cloud.githubusercontent.com/assets/1328499/12554564/8469994e-c3c0-11e5-8143-0d95900d5f79.png)

20件、出版年の新しい順を選択　表示をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/12554609/ae296bc4-c3c0-11e5-9f1a-bd0956972d9c.png)

○20件表示される、　×メニューが10件表示になっている→20件表示になるべき
○出版年の新しいもの順に表示される、○メニューが出版年の新しいもの順になっている
![image](https://cloud.githubusercontent.com/assets/1328499/12554684/10f8d29e-c3c1-11e5-8f58-91649ebfa9e5.png)
