### ISSUE TITLE
質問：ローカルのみ環境への転換方法

### ISSUE THREAD

**Issue by meinherzjin** [next-l/enju_leaf#571]
おつかれさまです。

社内の環境で構築して使っています。
しかし、人々のIPによって外部に接続が可能である人もいるし、
ローカルのみ接続される方もいます。

この場合、外部接続に問題ないパソコンではページがうまく表示されますが、
ローカルのみの場合、ページロードにすごく時間が掛かります。

ほかのWebサーバも同じ現象がありますが、それはIndex.htmlファイルに接続IPを判別する部分を入れて、
ローカル専用IPの場合、インターネットに接続する部分(Google Mapへのクエリ)を削除したファイルをロードするようにしています。

えんじゅの場合はどこの部分を修正すればいいのでしょうか？

**Comment by nabeta** [comment]
既定では、Google Booksでの書影表示とGoogle Mapsでの地図の表示のため、GoogleのサーバにあるJavaScriptを読み込んでいます。これを読み込まないようにするには、次のふたつのファイルを修正する必要があります。

- enju_biblio: [app/views/layouts/manifestations.html.erb](https://github.com/next-l/enju_biblio/blob/1.1/app/views/layouts/manifestations.html.erb)
- enju_library: [app/views/libraries/_map.html.erb](https://github.com/next-l/enju_library/blob/1.1/app/views/libraries/_map.html.erb)

まず、このふたつのファイルをダウンロードし、Enjuをインストールしたディレクトリにコピーします。

```sh
$ cd your_enju
$ wget https://raw.githubusercontent.com/next-l/enju_biblio/1.1/app/views/layouts/manifestations.html.erb
$ mv manifestations.html.erb app/views/layouts/
$ wget https://raw.githubusercontent.com/next-l/enju_library/1.1/app/views/libraries/_map.html.erb
$ mkdir app/views/libraries
$ mv _map.html.erb app/views/libraries/
```

次に、ファイルを修正します。manifestations.html.erb の12行目を変更します。

```sh
$ vi app/views/layouts/manifestations.html.erb
```

 変更前:
```ruby
<%# book_jacket_header(@library_group.settings[:book_jacket_source]) %>
```

変更後:
```ruby
<%# book_jacket_header(@library_group.settings[:book_jacket_source]) %>
```

_map.html.erb は、1行目から25行目まで、全ての行をコメントアウト、または削除してください。

```sh
$ vi app/views/libraries/_map.html.erb
```

```ruby
<!-- 全ての行をコメントアウト、または削除 -->
```

コメントアウトしたあと、以下のようなHTMLを直接書いてもかまいません。

```ruby
<!--
<img src"//intranet.example.kr/map.png" width="300" height="300" alt="도서관" />
-->
```

この作業を実施すると、書誌情報のページの書影と、図書館のページのGoogle Mapsの地図が読み込まれなくなります。もしうまくいかなかったり、エラーになったりしたら、お気軽にお問い合わせください。

**Comment by nabeta** [comment]
ところで、このissueで気付いたのですが、特に説明なく外部への通信が発生するのは、今回のようなイントラネットでの運用の面でも、プライバシーの面でも、問題がありそうな気がします。既定でGoogleのJavaScriptの読み込みを無効にした上で、インストール直後の初期設定画面を作り、そこで読み込みを有効にするかどうかをユーザに選択させるようにするのがよいと思いました。これは後で別のissueとして作成します。

**Comment by yegusa** [comment]
@meinherzjin さん、いかがでしょうか？

**Comment by meinherzjin** [comment]
ご回答ありがとうございます。

テストサーバ、運用サーバ２台のサーバで確認しましたが、ファイルおよび設定を変更した上にもでホーム画面はページの表示が遅くなっています。

なお、 「PICK UP」の本イメージもGoogleからもって来ます。
http://books.google.com/books/content?id=FRqGAAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api


個人的にはGoogle BooksのPreview機能がもったいないので、可能であれば、
イントラネットユーザは「Google接続不可」、一般ユーザは「Google接続可能」のように
ユーザ権限で設定ができればと思います。＾＾

**Comment by nabeta** [comment]
@meinherzjin enju_leaf-1.1.0では、以下の設定を行うことで、Google Booksの利用を停止することができます。再起動は不要です。

```sh
$ cd path_to_enju
$ rails c production
> library = LibraryGroup.find(1)
> library.settings[:book_jacket_source] = nil
> library.save
> exit
```

Google Booksの利用を再開するときは、上記の実行例のうち、

```
> library.settings[:book_jacket_source] = nil
```

の部分を次のように変更して実行してください。

```
> library.settings[:book_jacket_source] = :google
```

お試しいただけますでしょうか。

なお、Google BooksのJavaScriptの読み込み処理は、以下で行っています。
https://github.com/next-l/enju_manifestation_viewer/blob/1.1/lib/enju_manifestation_viewer/book_jacket_helper.rb#L71-L79

**Comment by meinherzjin** [comment]
動作を確認しました。ありがとうございます。

[Version]
1.1.0

イシュークローズします。
