### ISSUE TITLE
要望：検索結果一覧に「請求記号」が表示されて欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#574]
#567 #569 から分岐したissueです。

**Comment by yegusa** [comment]
@izuru さん、こちらに移しましたのでよろしく。

**Comment by yegusa** [comment]
近々に（？）開発予定の別issue #31 で、以下のように、所蔵がデフォルトで1,2件表示されるのですが、
請求記号を表示したいというのでしたら、それで間に合いますよね？

![image](https://cloud.githubusercontent.com/assets/1328499/7170619/c6082262-e40a-11e4-8484-3df1646f5ec1.png)

**Comment by izuru** [comment]
この表示で、間に合います。

**Comment by yegusa** [comment]
では、クローズします。
