### ISSUE TITLE
要望：「条件を詳しく指定して検索」に「件名」の項目が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#575]
- [ ] マニュアル修正 #1248 

#565 から分岐したissueです。

**Comment by masao** [comment]
詳細検索に「件名」欄を追加しました。ご確認ください。
enju_leafとenju_biblioの両方を最新版にすることで対応になります。

**Comment by yegusa** [comment]
できていることをかくにんしましたのでクローズします

件名に入力しているところ
![next l enju leaf 10](https://cloud.githubusercontent.com/assets/1328499/26783434/1cf06b94-4a33-11e7-8946-250dd24a4a65.png)

検索されたところ
![next l enju leaf 11](https://cloud.githubusercontent.com/assets/1328499/26783468/4549fcb8-4a33-11e7-80a7-54a3914296d4.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)
