### ISSUE TITLE
要望：「条件を詳しく指定して検索」に「本棚」（所蔵場所）項目が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#576]
- [ ] マニュアル修正 #1248 

#565 から分岐したissueです。

業務で必要

**Comment by masao** [comment]
本棚検索を追加しました。業務用ということなので、図書館員権限を持っているユーザの時だけ有効です。

**Comment by masao** [comment]
ゲスト権限で詳細検索画面がエラーになるのを修正しました。確認願います。

**Comment by yegusa** [comment]
できていることを確認したのでクローズします。

指定せずに検索したところ　8件ヒット

![next l enju leaf 6](https://cloud.githubusercontent.com/assets/1328499/26783023/1b618e72-4a31-11e7-8458-63caffcd10ef.png)

本棚を指定して検索
![next l enju leaf 7](https://cloud.githubusercontent.com/assets/1328499/26783074/4732289a-4a31-11e7-98ec-ec6cf0225122.png)

指定した本棚の本だけがヒット
![next l enju leaf 8](https://cloud.githubusercontent.com/assets/1328499/26783106/6b9fa0f4-4a31-11e7-80c1-caca2cc37c20.png)


ゲストの時は、詳細検索で本棚が選べない
![next l enju leaf 9](https://cloud.githubusercontent.com/assets/1328499/26783130/9553eb1c-4a31-11e7-895f-bcaba68dbd9a.png)

vagrant@vagrant:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.2 4a9d34a)
  * enju_circulation (0.2.2 96d8be7)
  * enju_event (0.2.1)
  * enju_leaf (1.2.1)
  * enju_library (0.2.2)
  * enju_manifestation_viewer (0.2.1)
  * enju_message (0.2.1)
  * enju_ndl (0.2.1)
  * enju_seed (0.2.1)
  * enju_subject (0.2.1)

**Comment by t-machii** [comment]
本棚検索、業務用で、図書館員権限を持っているユーザの時だけ有効でとの事ですが、一般ユーザーにも使わせたいです。
ぜひ、よろしくお願い申し上げます。
