### ISSUE TITLE
要望：「条件を詳しく指定して検索」に「請求記号」項目が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#577]
#565 から分岐したissueです。
業務で必要

**Comment by yegusa** [comment]
このあたりの位置かな。
http://enju.next-l.jp/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/7193758/2e6384f2-e4e0-11e4-8af5-51aa183bd8cb.png)

**Comment by nabeta** [comment]
これは完全一致検索でよいでしょうか。内部的には 007|A|ア のような形式でデータを持っていますが、"007"でも"ア"でも検索できるようにとなると少し面倒です。

**Comment by yegusa** [comment]
どうして面倒なんですか？

**Comment by nabeta** [comment]
たとえば、「3段目がア」という検索式をどうSolrで実現するかが問題になります。

**Comment by yegusa** [comment]
ああ、そういう意味か。そこまではできなくていいでしょう。

普通に、以下のようなかんじで、部分一致、前方一致、後方一致ができればいいとおもいますけど？

* A  （Aを含む）
* 007|*　(007|から始まる）
* *|ア （|アで終わる）

**Comment by masao** [comment]
基本的に、前方一致だけを前提とするのでよさそうに思いますが、いかがでしょうか。

**Comment by masao** [comment]
前方一致検索を前提として実装しました。ご確認ください。

**Comment by yegusa** [comment]
できることを確認しましたのでクローズします。
たしかに前方一致でいいですね。

![image](https://cloud.githubusercontent.com/assets/1328499/7443859/7fba5aa4-f1a3-11e4-959b-ca3ab7995afd.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7443861/9cd28ef4-f1a3-11e4-967e-a5c19304d668.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 d1f79a2)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 0b1b30d)
  * enju_library (0.1.0.pre40 f24af1e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)

**Comment by masao** [comment]
ちなみに、この機能を使うにはSolrの再インデックスが必要です。
