### ISSUE TITLE
要望：「条件を詳しく指定して検索」に「受入日」項目が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#578]
#565 から分岐したissueです。
業務で必要

**Comment by nabeta** [comment]
「受入日」はすでに存在します。
http://enju.next-l.jp/page/advanced_search

**Comment by yegusa** [comment]
そうでしたね。

http://enju.next-l.jp/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/7172220/cb2a473e-e41e-11e4-8d6e-aac84806604e.png)

@izuru さん、これでよいですか？

**Comment by izuru** [comment]
ありましたね。失礼しました。
