### ISSUE TITLE
要望：「条件を詳しく指定して検索」に「所蔵図書館名」項目が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#580]
#565 から分岐したissueです。
検索前にも絞り込み欲しい（検索語のファセット絞り込みだけでなく）

**Comment by yegusa** [comment]
こんなかんじでしょうか？
http://enju.next-l.jp/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/7193701/7ae5ae50-e4df-11e4-93fd-1de6f65b57bb.png)

**Comment by izuru** [comment]
そうですね。図書、雑誌、AVとあるのがよくあるパターンかと。

**Comment by yegusa** [comment]
ああ、「図書、雑誌、AVとあるのがよくあるパターンかと。」これは、資料の種類のほうですね。

**Comment by izuru** [comment]
あ、すいません。図書館名はこれでいいと思います。全て選択みたいなチェックボックスがあるといいかもしれません。

**Comment by masao** [comment]
「全て選択」のようなリンクは実装できていませんが、それ以外は開発しました：
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/7439820/0b33ade2-f0c8-11e4-94f2-48b3a742585d.png)

ひょっとすると、ブックマーク資料用の「World Wide Web」図書館ははずしたほうがよいかも?

**Comment by yegusa** [comment]
出来ていることを確認したのでクローズします

![image](https://cloud.githubusercontent.com/assets/1328499/7443850/ca62ac9c-f1a2-11e4-912b-8480435ba900.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7443852/de2e7206-f1a2-11e4-9381-ba485ca166fc.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 d1f79a2)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 0b1b30d)
  * enju_library (0.1.0.pre40 f24af1e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)
