### ISSUE TITLE
NDLサーチからのインポートでNDC 8版への対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#581]
NDLサーチからのインポート時に、NDC9しか保存しないようになっていますが、90年代の書籍などでNDC8しか付いていないものがあるので、せっかくなので、これも保存してもよいのではないかと思いますが、いかがでしょうか。

**Comment by yegusa** [comment]
いいと思います！

**Comment by masao** [comment]
対応を追加しました。

**Comment by masao** [comment]
デモ画面を付けますと、以下のような感じです：

![20150418-enju_leaf_581_ 2 next l enju leaf](https://cloud.githubusercontent.com/assets/38825/7214558/c7a8a186-e5eb-11e4-9bfc-afae389d5d09.png)

**Comment by yegusa** [comment]
動いているところを確認しましたので、クローズします。
