### ISSUE TITLE
simple_form(フォームの凡例に使ってるライブラリ)を使い続けるかどうか検討する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#583]
#560 から派生したissueです。

https://github.com/next-l/enju_leaf/issues/560#issuecomment-93342511

> これはsimple_formというライブラリに関係します。このライブラリには、ActiveRecordのモデルでvalidationが定義されていると、そのvalidationの対象の属性を入力するフォームに自動的にマークをつけてくれるという機能があります。問題のフォームはこのライブラリを使用しているのですが、名前に反していまいち見た目がカスタマイズしにくく、> そのまま放置してしまっていました。
> そもそもsimple_formを使い続けるかどうか、という点を考えさせてください。

検討したら、 #584 のissueへ進みます。

1.1.0.rc18で発生したissueです。

**Comment by yegusa** [comment]
検討するのはいいですが、使わないとしたら、どういう方法が考えられますか？

**Comment by nabeta** [comment]
以下のPRで、simple_formを削除しました。
https://github.com/next-l/enju_leaf/pull/1717
