### ISSUE TITLE
プロキシ設定がなくてアクセスできない場合のエラーメッセージを出すように

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#585]
#116 から派生したissueです。

例えば、プロキシ設定がないと使えない環境にいて、プロキシ設定をしていないから
アクセスできなくてという場合に、We're sorry ではなく、
プロキシ設定に問題があることがわかるようなメッセージの画面にするということです。

**Comment by nabeta** [comment]
これは原因がプロキシかどうかの判別が難しいので、対応なしとさせてください。
