### ISSUE TITLE
solrの不具合の場合のエラー画面を表示するように（We're sorryではなく）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#587]
まだsolrが起動していないだけでも、We're sorry となるので、

検索サーバーに不具合があるようです。
検索サーバーの起動に時間がかかっている場合もこの画面がでます。
この場合は、少し時間を置いてアクセスすると解消される場合がありますのでお試しください。

こんな感じのエラーメッセージ画面がでると、いいなと思います。

**Comment by masao** [comment]
先ほど実装しておきました。確認をお願いします。

**Comment by masao** [comment]
さきほど1つテンプレートの追加忘れがありましたので、追加しておきました。

参考までに、画面例を以下に示します：
![we re sorry but something went wrong 500](https://cloud.githubusercontent.com/assets/38825/7557794/a8edbaa8-f7d2-11e4-981a-4a12c4508d38.png)

**Comment by yegusa** [comment]
@nabeta に開発サーバーのsolrを止めてもらって、確認してみました。

http://dev.next-l.jp/
![image](https://cloud.githubusercontent.com/assets/1328499/8266227/56d7dd52-175d-11e5-8c1f-eb209e79c7b5.png)

クローズします。
