### ISSUE TITLE
バグ：NDLサーチからインポートして作成した雑誌マスタ（書誌）が検索で表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#588]
検索されない：資料の受入→雑誌・定期刊行物
http://localhost:8080/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/7219929/39917d9e-e6f1-11e4-8c1f-aab7556581dd.png)

公式サイトからダウンロードした1.1.0.rc17でこの現象を確認しました。

インポートしたデータ：
![image](https://cloud.githubusercontent.com/assets/1328499/7219914/e680fd32-e6f0-11e4-9682-8e8be18cb0ed.png)

以下の雑誌：
http://iss.ndl.go.jp/books/R100000002-I000011225479-00

**Comment by nabeta** [comment]
修正しました。開発用サーバに反映済みです。

**Comment by yegusa** [comment]
開発用サーバーで試してみましたが、できませんでした。

![image](https://cloud.githubusercontent.com/assets/1328499/7485851/c11aaa3c-f3d6-11e4-9efa-9026a637837f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7485854/d07cc6f4-f3d6-11e4-8973-a0d4719dcd30.png)

http://dev.next-l.jp/manifestations?parent_id=4905
![image](https://cloud.githubusercontent.com/assets/1328499/7485861/e8878694-f3d6-11e4-9b52-73a41e9545a9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7485866/0b5a7fc8-f3d7-11e4-83af-993ee77227d2.png)

**Comment by yegusa** [comment]
手元の仮想マシンで、bundle update してたしかめたら、できましたので、クローズしますが。
開発サーバーでできないのはなんででしょうね？

![image](https://cloud.githubusercontent.com/assets/1328499/7485948/30eadfac-f3d8-11e4-93d1-6d5b13741ec6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7485952/35b3cda0-f3d8-11e4-9c27-92b28243ba07.png)

http://localhost:8080/manifestations?parent_id=4
![image](https://cloud.githubusercontent.com/assets/1328499/7485955/3a25bc86-f3d8-11e4-8a28-36a6f770ee5a.png)

http://localhost:8080/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/7485969/4e051b70-f3d8-11e4-9429-2f053ae367c8.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 a9efbc9)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 8691486)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)

**Comment by nabeta** [comment]
開発サーバのenju_biblioモジュールが、ローカルファイルを見るようになっていました。
githubを見るようにして再起動し、上記の書誌をインポートして、正常に表示されることを確認しました。
http://dev.next-l.jp/manifestations?parent_id=4908&query=

**Comment by yegusa** [comment]
「現代の図書館」をインポートしてみました。できることを確認しました。
http://dev.next-l.jp/manifestations?serial=true
![image](https://cloud.githubusercontent.com/assets/1328499/7488003/0fb131d0-f3fe-11e4-9a32-6526d2e4b430.png)
