### ISSUE TITLE
NDLサーチからのインポートで「シリーズ名よみ」が保存されない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#590]

**Comment by masao** [comment]
一通り実装したので、動作確認をお願いします。

**Comment by yegusa** [comment]
残っている作業は
@yegusa によって、 確認すること　（確認する方法は @masao に聞く）

**Comment by yegusa** [comment]
仮想マシンで、「シリーズ名のヨミ」が保存されることを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/7332233/c46c51f4-eb70-11e4-9494-e5d2fa8e963f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 4adbe7e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)
