### ISSUE TITLE
NDLサーチからのインポートでシリーズ情報が保存されない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#591]
1.1ブランチの最先端を使っていますが、標記のとおり、シリーズ情報が保存されない現象が発生しています。

・ローカルの仮想マシン環境
・Heroku環境

の双方で確認しました。

**Comment by masao** [comment]
デモサーバでは発生しないので、rc17リリース以降の問題かもしれません。

bundle list の結果を以下につけておきます：
```
Gems included by the bundle:
  * actionmailer (4.1.8)
  * actionpack (4.1.8)
  * actionview (4.1.8)
  * activemodel (4.1.8)
  * activerecord (4.1.8)
  * activesupport (4.1.8)
  * acts_as_list (0.6.0)
  * addressable (2.3.8)
  * arel (5.0.1.20140414130214)
  * attribute_normalizer (1.2.0)
  * awesome_nested_set (3.0.2)
  * aws-sdk (2.0.39)
  * aws-sdk-core (2.0.39)
  * aws-sdk-resources (2.0.39)
  * bcrypt (3.1.10)
  * builder (3.2.2)
  * bundler (1.9.2)
  * cancancan (1.10.1)
  * charlock_holmes (0.7.3)
  * chronic (0.10.2)
  * climate_control (0.0.3)
  * cocaine (0.5.7)
  * coffee-rails (4.0.1)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * dalli (2.7.4)
  * devise (3.4.1)
  * devise-encryptable (0.2.0)
  * dynamic_form (1.1.4)
  * enju_biblio (0.1.0.pre66 fb9d730)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre25 a7355c9)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 7003c97)
  * enju_loc (0.1.0.pre4 3bd9c81)
  * enju_manifestation_viewer (0.1.0.pre17 759d8e0)
  * enju_message (0.1.14.pre22 e08ce06)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_nii (0.1.0.pre12 a1a95d9)
  * enju_seed (0.1.1.pre13 dc220d2)
  * enju_subject (0.1.0.pre29 1ab4640)
  * erubis (2.7.0)
  * exception_notification (4.0.1)
  * exception_notification-rake (0.1.2)
  * execjs (2.5.2)
  * faraday (0.9.1)
  * foreigner (1.7.4)
  * foreman (0.78.0)
  * friendly_id (5.1.0)
  * geocoder (1.2.8)
  * highline (1.6.21)
  * hike (1.2.3)
  * i18n (0.7.0)
  * jbuilder (2.2.13)
  * jc-validates_timeliness (3.1.1)
  * jmespath (1.0.2)
  * jquery-rails (3.1.2)
  * jquery-ui-rails (4.2.1)
  * json (1.8.2)
  * kaminari (0.16.3)
  * library_stdnums (1.4.1)
  * lisbn (0.2.1)
  * mail (2.6.3)
  * marc (1.0.0)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.6.0)
  * mobylette (3.5)
  * mono_logger (1.1.0)
  * multi_json (1.11.0)
  * multipart-post (2.0.0)
  * nested_form (0.3.2)
  * nokogiri (1.6.6.2)
  * nori (2.5.0)
  * options (2.3.2)
  * orm_adapter (0.5.0)
  * paper_trail (3.0.7)
  * paperclip (4.2.1)
  * paperclip-meta (1.2.0)
  * pg (0.18.1)
  * pr_geohash (1.0.0)
  * progress_bar (1.0.3)
  * rack (1.5.2)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (4.1.8)
  * rails_autolink (1.1.6)
  * railties (4.1.8)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * redcarpet (3.2.3)
  * redis (3.2.1)
  * redis-actionpack (4.0.0)
  * redis-activesupport (4.0.0)
  * redis-namespace (1.5.2)
  * redis-rack (1.5.0)
  * redis-rails (4.0.0)
  * redis-store (1.1.4)
  * responders (1.1.2)
  * resque (1.25.2)
  * resque-scheduler (4.0.0)
  * resque_mailer (2.2.7)
  * ri_cal (0.8.8)
  * rsolr (1.0.12)
  * rufus-scheduler (3.1.1)
  * sass (3.2.19)
  * sass-rails (4.0.5)
  * scrub_rb (1.0.1)
  * sdoc (0.4.1)
  * settingslogic (2.0.9)
  * simple_form (3.1.0)
  * sinatra (1.4.6)
  * sitemap_generator (5.0.5)
  * spring (1.3.4)
  * sprockets (2.12.3)
  * sprockets-rails (2.2.4)
  * sqlite3 (1.3.10)
  * statesman (1.2.3)
  * sunspot (2.2.0)
  * sunspot_rails (2.2.0)
  * sunspot_solr (2.2.0)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * timeliness (0.3.7)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.1)
  * vegas (0.1.11)
  * warden (1.2.3)
  * whenever (0.9.4)
```

**Comment by yegusa** [comment]
rc17の仮想マシンで、最新のソースを見るようにGemfileを書き換えたのち、
bundle updateしたあとのEnjuで試してみたら、ちゃんとシリーズ情報はインポートされました。

bundle listの結果は以下のとおりです。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list
Gems included by the bundle:
  * actionmailer (4.2.0)
  * actionpack (4.2.0)
  * actionview (4.2.0)
  * activejob (4.2.0)
  * activemodel (4.2.0)
  * activerecord (4.2.0)
  * activesupport (4.2.0)
  * acts_as_list (0.6.0)
  * addressable (2.3.8)
  * arel (6.0.0)
  * attribute_normalizer (1.2.0)
  * awesome_nested_set (3.0.2)
  * aws-sdk (2.0.40)
  * aws-sdk-core (2.0.40)
  * aws-sdk-resources (2.0.40)
  * bcrypt (3.1.10)
  * binding_of_caller (0.7.2)
  * builder (3.2.2)
  * bundler (1.8.3)
  * byebug (4.0.5)
  * cancancan (1.10.1)
  * charlock_holmes (0.7.3)
  * chronic (0.10.2)
  * climate_control (0.0.3)
  * cocaine (0.5.7)
  * coffee-rails (4.1.0)
  * coffee-script (2.4.1)
  * coffee-script-source (1.9.1.1)
  * columnize (0.9.0)
  * dalli (2.7.4)
  * debug_inspector (0.0.2)
  * devise (3.4.1)
  * devise-encryptable (0.2.0)
  * dotenv (2.0.1)
  * dotenv-rails (2.0.1)
  * dynamic_form (1.1.4)
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)
  * erubis (2.7.0)
  * exception_notification (4.0.1)
  * exception_notification-rake (0.1.2)
  * execjs (2.5.2)
  * faraday (0.9.1)
  * foreman (0.78.0)
  * friendly_id (5.1.0)
  * geocoder (1.2.8)
  * globalid (0.3.5)
  * highline (1.6.21)
  * i18n (0.7.0)
  * jbuilder (2.2.13)
  * jc-validates_timeliness (3.1.1)
  * jmespath (1.0.2)
  * jquery-rails (4.0.3)
  * jquery-ui-rails (4.2.1)
  * json (1.8.2)
  * kaminari (0.16.3)
  * kgio (2.9.3)
  * library_stdnums (1.4.1)
  * lisbn (0.2.1)
  * loofah (2.0.1)
  * mail (2.6.3)
  * marc (1.0.0)
  * mime-types (2.4.3)
  * mini_portile (0.6.2)
  * minitest (5.6.0)
  * mobylette (3.5)
  * mono_logger (1.1.0)
  * multi_json (1.11.0)
  * multipart-post (2.0.0)
  * nested_form (0.3.2)
  * nokogiri (1.6.6.2)
  * non-stupid-digest-assets (1.0.4)
  * nori (2.5.0)
  * options (2.3.2)
  * orm_adapter (0.5.0)
  * paper_trail (3.0.7)
  * paperclip (4.2.1)
  * paperclip-meta (1.2.0)
  * pr_geohash (1.0.0)
  * progress_bar (1.0.3)
  * rack (1.6.0)
  * rack-protection (1.5.3)
  * rack-test (0.6.3)
  * rails (4.2.0)
  * rails-deprecated_sanitizer (1.0.3)
  * rails-dom-testing (1.0.6)
  * rails-html-sanitizer (1.0.2)
  * rails_autolink (1.1.6)
  * railties (4.2.0)
  * raindrops (0.13.0)
  * rake (10.4.2)
  * rdoc (4.2.0)
  * redcarpet (3.2.3)
  * redis (3.2.1)
  * redis-actionpack (4.0.0)
  * redis-activesupport (4.0.0)
  * redis-namespace (1.5.2)
  * redis-rack (1.5.0)
  * redis-rails (4.0.0)
  * redis-store (1.1.4)
  * responders (2.1.0)
  * resque (1.25.2)
  * resque-scheduler (4.0.0)
  * resque_mailer (2.2.7)
  * ri_cal (0.8.8)
  * rsolr (1.0.12)
  * rufus-scheduler (3.1.1)
  * sass (3.4.13)
  * sass-rails (5.0.3)
  * scrub_rb (1.0.1)
  * sdoc (0.4.1)
  * settingslogic (2.0.9)
  * simple_form (3.1.0)
  * sinatra (1.4.6)
  * sitemap_generator (5.0.5)
  * spring (1.3.4)
  * sprockets (3.0.2)
  * sprockets-rails (2.2.4)
  * sqlite3 (1.3.10)
  * statesman (1.2.3)
  * sunspot (2.2.0)
  * sunspot_rails (2.2.0)
  * sunspot_solr (2.1.1)
  * thor (0.19.1)
  * thread_safe (0.3.5)
  * tilt (1.4.1)
  * timeliness (0.3.7)
  * turbolinks (2.5.3)
  * tzinfo (1.2.2)
  * uglifier (2.7.1)
  * unf (0.1.4)
  * unf_ext (0.0.7.1)
  * unicorn (4.9.0)
  * vegas (0.1.11)
  * warden (1.2.3)
  * web-console (2.1.2)
  * whenever (0.9.4)

**Comment by masao** [comment]
#321 と同一の原因のようです。enju_ndlとenju_locのメソッド名の衝突です。
さきほど enju_loc 側を修正しました。

**Comment by masao** [comment]
さらに調べたところ enju_ndl と enju_loc の衝突だけでなく、enju_nii を含めたときに再現する現象であることが分かりました。
つまり、以下のようになります：
* enju_ndl => Ok
* enju_ndl + enju_loc => Ok
* enju_ndl + enju_nii => Ok
* enju_ndl + enju_loc + enju_nii => NG

**Comment by masao** [comment]
やはり enju_loc の修正で動作できるようになったことを確認しました。

**Comment by yegusa** [comment]
残っている作業：
@yegusa によって、この確認作業をする　（確認のやり方は @masao もしくは @nabeta に聞く）

**Comment by yegusa** [comment]
enju_loc がある状態で、シリーズ情報がインポートされることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/7332193/725244ac-eb6e-11e4-8dd2-bb09489c2b4a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 4adbe7e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)
