### ISSUE TITLE
書誌情報に対する添付ファイルを削除する機能を付ける

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#598]
現状、書誌情報全体を消さないと消えないようなので、削除する機能が必要だと思います。

**Comment by nabeta** [comment]
ファイル削除のチェックボックスを追加するPRを作成しました。開発サーバに反映済みです。
![image](https://user-images.githubusercontent.com/11428/163708705-9ac21c73-dc76-471f-905a-e48c3c9fdb73.png)
