### ISSUE TITLE
NoMethodError (undefined method `settings' for LibraryGroup) が出る

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#599]
rc18にあげたら標記のエラーが出るようになりました。

**Comment by masao** [comment]
解決できることを確認しました。

1. Github最新に全てのモジュールを上げる。
2. https://github.com/next-l/enju_leaf/wiki/Update にある手順を実行する
```
$ bundle update
$ rake railties:install:migrations
$ rake db:migrate RAILS_ENV=production
$ rake enju_leaf:upgrade RAILS_ENV=production
```

**Comment by yegusa** [comment]
確かめてみました。できることを確認しましたので、クローズします。

仮想マシンで、やってみました。

<pre>
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre43 528200b)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 611cafa)
  * enju_library (0.1.0.pre40 4adbe7e)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 1ab4640)
</pre>
