### ISSUE TITLE
開発版のマスターブランチでbundle installができない

### ISSUE THREAD

**Issue by himkt** [next-l/enju_leaf#602]
Could not find gem 'enju_biblio (~> 0.2.0.pre1) ruby' in git://github.com/next-l/enju_biblio.git (at master).
Source contains 'enju_biblio' at: 0.2.0.beta.1
となります.

gemfileのenju_biblioのところを0.2.0.pre1から0.2.0.beta.1にすれば解決でしょうか

**Comment by himkt** [comment]
他のモジュールも同様ですね

**Comment by nabeta** [comment]
はい、そうです。

**Comment by himkt** [comment]
foreman startで
LibraryGroup Load (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id",      1]]
Completed 404 Not Found in 31ms (ActiveRecord: 5.2ms)
ActiveRecord::RecordNotFound (Couldn't find LibraryGroup with 'id'=1):

というエラーが出ます。これはmigrateのミスですか?モジュールのターゲットを変えたからですか？

**Comment by nabeta** [comment]
library_groupsテーブルには必ずidが1のレコードが存在します。bundle updateだけではレコードは消えないので、データベースに何らかの不具合があります。他のテーブル（librariesなど）にはレコードがありますか？

**Comment by himkt** [comment]
空でした。この問題は僕の設定のミスでしょうか？それともバグでしょうか？

**Comment by nabeta** [comment]
もし新規でインストールした場合、バグの可能性が高いです。

**Comment by nabeta** [comment]
古いissueで、現バージョンと状況が変わっているため、closeします。
