### ISSUE TITLE
要望：「条件を詳しく指定して検索」の「所蔵図書館名」項目に「全て選択」、「全て解除」が欲しい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#603]
#580 要望：「条件を詳しく指定して検索」に「所蔵図書館名」項目が欲しい
から派生したissueです

**Comment by masao** [comment]
選択・解除のボタンを追加しました。ご確認ください。

**Comment by yegusa** [comment]
残作業：ボタンを一つにする方向に修正する。

**Comment by masao** [comment]
ボタンをひとつにするよう修正しました。確認願います。

**Comment by yegusa** [comment]
仮想マシンでできていることを確認しました。
クローズします。

ボタン名（日本語）：全て選択/解除
ボタン名（英語）：Check/Uncheck ALL　

1. 最初の画面（チェックなし）、ボタンをおす
http://localhost:8080/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/9834868/a4164eac-5a09-11e5-99ab-33cb25a91598.png)

2. チェックが全部入った状態で表示される、ボタンを押す
![image](https://cloud.githubusercontent.com/assets/1328499/9834882/d8e1ec86-5a09-11e5-8015-e19310bdacd8.png)

3. チェックが全部はずれた状態で表示される
![image](https://cloud.githubusercontent.com/assets/1328499/9834888/063962ae-5a0a-11e5-8928-688a3ac030a5.png)

英語の画面も確認しました
![image](https://cloud.githubusercontent.com/assets/1328499/9834900/6d4317e2-5a0a-11e5-95eb-430b4a96e19e.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bac371f)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_grid (0.0.1 44ea000)
  * enju_leaf (1.1.0.rc21 5deff09)
  * enju_library (0.1.0.pre43 c9a3d72)
  * enju_manifestation_viewer (0.1.0.pre19 3ca2bf8)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 0ee5429)
  * enju_subject (0.1.0.pre33)
