### ISSUE TITLE
利用者グループと貸出区分の関連付けができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#604]
http://enju.next-l.jp/user_groups/1/edit から「定期刊行物」に対する対応を追加登録して更新すると、「利用者グループは正常に更新されました。」とのメッセージが表示されるものの、登録内容が反映されていません。

Github先端版 + Heroku環境でも同様の現象を確認。

**Comment by masao** [comment]
#509 のチェック漏れのような感じですね。ひとまずユーザグループ編集画面での更新処理の修正をコミットしてみました。ご確認ください。

**Comment by yegusa** [comment]
仮想マシンで最新のものを取り込んで確認しました。（図書を追加してみました）
修正されていることを確認しましたので、クローズします。

http://localhost:8080/user_groups/2/edit
![image](https://cloud.githubusercontent.com/assets/1328499/7467343/9ef60e42-f331-11e4-88b3-aec8620387df.png)

http://localhost:8080/user_groups/2
![image](https://cloud.githubusercontent.com/assets/1328499/7467347/b0069210-f331-11e4-8c7d-579af3c101e0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 d0f88dc)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 f3cbcbb)
  * enju_library (0.1.0.pre40 49a5847)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)
