### ISSUE TITLE
要望：検索件数の上限を指定できるようにしたい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#605]
> また、検索件数の上限を指定できるようにしました。「図書館全体の設定」から「検索結果の最大件数」で指定します。0を指定すると上限なしになります。http://dev.next-l.jp/library_groups/1/edit
https://github.com/next-l/enju_leaf/issues/596#issuecomment-99072784
by @nabeta 

#596 から派生したissueです。

**Comment by nabeta** [comment]
これもあと何ができるようになっていればよいのかがわかりません。動作していないということでしょうか。

**Comment by yegusa** [comment]
> これもあと何ができるようになっていればよいのかがわかりません。動作していないということでしょうか。

今後のためにも、わかりやすくするために issueを分けただけです。
動作確認の結果もissueを分けたほうが、わかりやすく残せますしね。
動作確認まだだったし。

ところで、この機能、どうして実装したんですか？
Enju WS かなにかで要望でてましたっけ？

**Comment by yegusa** [comment]
3にしてみました。こちらは、問題なく動いていると思います。

![image](https://cloud.githubusercontent.com/assets/1328499/7487820/64b4d10e-f3fa-11e4-9084-5fd4e5938751.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7487821/86087ca2-f3fa-11e4-943f-70e315303876.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 a9efbc9)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 8691486)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)

ところで、一番最初は「空」なんですね。
これは「0」と同義だということでしょうか？
![image](https://cloud.githubusercontent.com/assets/1328499/7487816/3f81614a-f3fa-11e4-9a6e-0284d056bd91.png)

**Comment by yegusa** [comment]
0　に設定してみました。

「検索件数の上限を超えました。最初の17件を表示しています。」　
の文言はいらないのではないでしょうか？

上限が超えなかったときと同様に、この文言は表示しなくて良いのではないでしょうか？

![image](https://cloud.githubusercontent.com/assets/1328499/7487871/73ec3a4e-f3fb-11e4-9b9a-9f8a03a9478d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/7487883/9047ab06-f3fb-11e4-8663-422101a56d4f.png)

参考：上限を超えなかったときの表示（例：上限を1000に設定のため）
![image](https://cloud.githubusercontent.com/assets/1328499/7487915/2e8af20a-f3fc-11e4-80bb-231112ab948e.png)

**Comment by nabeta** [comment]
> ところで、一番最初は「空」なんですね。
> これは「0」と同義だということでしょうか？

とりあえずそうしていますが、アップデート用のスクリプトで適当な初期値（500など）を設定するつもりです。

**Comment by nabeta** [comment]
> 上限が超えなかったときと同様に、この文言は表示しなくて良いのではないでしょうか？

もともとそのように作ってあります。しかし、ここでの全件数の表示にはデータベース上の全件数を使用していたのですが、レコード削除時のエラーなどでデータベース上の全件数よりもSolr上の全件数が多くなっていると、このような現象が発生します。Solr上の全件数を使用するように変更しました。

**Comment by yegusa** [comment]
手元の仮想マシンでbundle updateして確認作業しています。

a) 0 と設定したとき　文言が表示されなくなることを確認しました
![image](https://cloud.githubusercontent.com/assets/1328499/7489348/ab61dd70-f410-11e4-85a2-75c38985e2f7.png)

b) 3と設定したとき　3件だけでてきていることを確認しました
![image](https://cloud.githubusercontent.com/assets/1328499/7489392/2df0cce2-f411-11e4-8d7b-f7620718d753.png)

b) 15と設定したとき 20件表示されます。 
![image](https://cloud.githubusercontent.com/assets/1328499/7489427/7bf30900-f411-11e4-8404-7eee80e37003.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 318c307)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 7949d16)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)

**Comment by nabeta** [comment]
cの例は対応が難しそうです。sunspotにはSQLのLIMITのような、検索結果の件数を制限する方法がないためです。

**Comment by yegusa** [comment]
c) の件、ま、いいことにしましょう。

ところで、なんで、この値設定する必要があるのか、根本的なところが分かっていないのですが。
少な目にすると結果がはやく返ってくるとか、なにかいいことがあるとか、
値を決めておかなければならない必然性があるのですか？
教えてもらえるとうれしいです。

**Comment by nabeta** [comment]
詳細画面での「次へ」「前へ」リンクを表示するために、昔は検索結果の全レコードIDをCookieに保存していました。このため、Cookieの容量の上限(4KB)に引っかからないように、検索結果の上限を設定する必要がありました。
http://dev.next-l.jp/manifestations/4911

現在はCookieではなく、HTML5のsessionStorageを使用しています。保存容量はブラウザによって5MBや10MBなどと異なりますが、いずれにしても上限が決まっているため、そのまま検索結果の上限を設定できるようにしています。

**Comment by yegusa** [comment]
りょうかいしました。機能も実現できているようですし、このissueはクローズします。
