### ISSUE TITLE
「モバイル画面を使用しないユーザエージェント」の使い方がわかりません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#606]
1.1.0.rc18　から新しくできた設定フォームのようですが、
使い方がわかりません。おしえてください。 → @nabeta 

最新版の画面：
http://localhost:8080/library_groups/1/edit
![image](https://cloud.githubusercontent.com/assets/1328499/7486363/39a0a580-f3df-11e4-9a21-36c54538f986.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 a9efbc9)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 8691486)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)

参考：1.1.0.rc17 の画面
http://enju.next-l.jp/library_groups/1/edit
![image](https://cloud.githubusercontent.com/assets/1328499/7486373/5b08e2b4-f3df-11e4-9b04-67221a55f769.png)

**Comment by nabeta** [comment]
これはスマートフォン用の画面を使用しないデバイスを指定するものです。
1.1系ではデバイスの判定にmobyletteというライブラリを使用しており、android, iphone, ipadを指定できるようになっています。変更の反映にはWebサーバの再起動が必要です。
https://github.com/tscolari/mobylette/blob/master/lib/mobylette/devices.rb#L7

1.2系ではbrowserというライブラリを使用しています。以下にあるブラウザやデバイスを指定できます。
https://github.com/fnando/browser#usage

**Comment by yegusa** [comment]
すみません、どういう機能かはなんとなくわかりましたが、
フォームにどう記述すればよいのかよくわかりません。

- 1.1系だとandroid, iphone, ipadの3つのみが指定できるようになっている。
- 1.2系だといろいろ指定できる
- つまり、1.1系と1.2系では書き方が変わる

という理解であってますか？

あと、1.2系のときの書き方が分かりません。iphoneとかが見当たらないような？

ところで、この機能どうして作ったのですか？Enju WSかなにかで話題にでましたっけ？

**Comment by nabeta** [comment]
> ところで、この機能どうして作ったのですか？Enju WSかなにかで話題にでましたっけ？

これは、設定内容を設定ファイル(config/application.yml)からデータベースに移動する作業の一環です。
https://github.com/next-l/enju_leaf/issues/516#issuecomment-71304971

**Comment by nabeta** [comment]
> という理解であってますか？

はい、そうです。

> あと、1.2系のときの書き方が分かりません。iphoneとかが見当たらないような？

書き方は未定ですが、以下にある名称を指定できるようにする予定です。
https://github.com/fnando/browser/blob/master/lib/browser.rb#L44

**Comment by yegusa** [comment]
書き方については、わかりました。
1.2系に本格的に移行したときにはできるようにすることにしましょう。

動作確認してみようと思って、

http://dev.next-l.jp/library_groups/1/edit

で、iphone を書いたり、消したりしてみて、

http://dev.next-l.jp/

にiphoneでアクセスしたり、検索したりしてみましたが、見栄えがかわりませんでした。
そういうものですか？

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/issues/606#issuecomment-99322405 に書いているように、（少なくとも1.1系では）Webサーバの再起動が必要です。

**Comment by nabeta** [comment]
先ほど開発用サーバのWebサーバを再起動し、 iphone が記入されている状態でiPhoneでアクセスし、デスクトップ用の画面が表示されることを確認しました。

**Comment by yegusa** [comment]
> #606 (comment) に書いているように、（少なくとも1.1系では）Webサーバの再起動が必要です。

え、そういう意味だったんですか。。。iPhoneを消したり、書いたりしたのを有効にするのに、Webサーバーの再起動を必要とするのかあ。

GUIで設定できるの紛らわしいような。。。せめて、「この設定はすぐに有効にはなりません。Webサーバを再起動時に有効になります」というポップアップを出すなど必要な気がします。

**Comment by nabeta** [comment]
さしあたりフォームに「Webサーバの再起動が必要です」と追加しました。
http://dev.next-l.jp/library_groups/1/edit

**Comment by yegusa** [comment]
かっこ悪いけど、しょうがないかな。
まあ、よいと思います。　
![image](https://cloud.githubusercontent.com/assets/1328499/7488924/982eef2c-f40b-11e4-86cf-e1196479fc66.png)

私もiPhoneでアクセスしてみて、普通の画面が見えることを確認しましたので、クローズします。

**Comment by nabeta** [comment]
この機能ですが、インストール用スクリプトがうまく動作しないことがわかりましたので（まだデータベースが作成されていないにもかかわらず、初期設定の値をデータベースから読み込もうとするため）、Web上からの編集機能は以下のコミットで削除しました。
https://github.com/next-l/enju_library/commit/d15624ab4f26e5eda303136fa5cf0f5ba7fab07e

かわりに環境変数 ENJU_SKIP_MOBILE_AGENTS を使用します。
https://github.com/next-l/enju_leaf/commit/0192caf10603ba8080c8fe10196d36232b076ba5#diff-a2a61e07fcf14d3a29f31cb6f39e4c2aR73

```sh
ENJU_SKIP_MOBILE_AGENTS=iphone
```

**Comment by yegusa** [comment]
メモ：デフォルトはipadだけが設定されている状態、区切り文字は、 , です。

Enju WS 20150531にて、iPhoneで開発用サーバーで確かめたところ、動くことを確認したので、クローズする。
