### ISSUE TITLE
画像ファイル登録のAmazon S3対応（heroku対応のため）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#607]
#513 と関連した issueです。

以下の機能などで使う。
http://dev.next-l.jp/manifestations/4902
![image](https://cloud.githubusercontent.com/assets/1328499/7488604/601c6ff0-f407-11e4-8474-81ccacd6ae99.png)

**Comment by nabeta** [comment]
画像ファイルや添付ファイルのリンクは拡張子が".download"となっていますが、S3を使用しているときにはS3のデータを、そうでないときはローカルのデータを読み込んで表示するようになっています。つまり、現在の上記の画面のリンクでは、S3を使用しているのかどうかは判別できません。
エクスポートの画面と同様、画像の詳細画面にS3へのリンクを表示するのがよいと思うのですが、いかがでしょうか。
http://dev.next-l.jp/picture_files/8

**Comment by yegusa** [comment]
s3のURLを見せるメリット/デメリットってなんでしょうかね。素のs3のURLが、見えるとセキュリティ的になんかなとかってことありますか？

**Comment by masao** [comment]
@nabeta さん、S3を使用しているかどうかを判別したいというIssueではなく、単に、S3をバックエンドにした状態でも登録できる機能が必要というだけでは？

**Comment by nabeta** [comment]
Enjuで使用するS3のバケットは非公開、つまり所有者しかアクセスできないようにしなければなりません（これはバケット作成時の既定値です）。利用者情報がこのバケットにエクスポートされるからです。
非公開のバケットにアクセスするときには、AWSのアクセスキーと有効期限、それにデジタル署名をパラメータに含めなければなりません。有効期限がついているとはいえ、これらが外部に見えるのは望ましくありません。
https://docs.aws.amazon.com/ja_jp/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth

**Comment by nabeta** [comment]
@masao 現時点で、 dev.next-l.jp はS3を使用する設定になっています。
なお、エクスポート先はS3、画像のアップロード先はローカルといったように、ファイルの保存先を混在させることはできません。

**Comment by yegusa** [comment]
> なお、エクスポート先はS3、画像のアップロード先はローカルといったように、ファイルの保存先を混在させることはできません。

そうでしたか。私は知りませんでした。なるほど。

> @masao 現時点で、 dev.next-l.jp はS3を使用する設定になっています。アップロードした画像はS3に保存されます。これをどうやって確認したいか、という問題だと思いました。

ああ、そういう意味ではなかったです。混在させるのができないのは知らなかったので。じゃあ、今、 dev.next-l.jp で、インポート、画像のアップロード、添付ファイルのアップロードができたら、それは、s3への設定がうまくいっていることが確認できたということになるのですね？

**Comment by yegusa** [comment]
画像を貼りこんでみました。

http://dev.next-l.jp/manifestations/4903
![image](https://cloud.githubusercontent.com/assets/1328499/7489647/0d7cc80a-f414-11e4-84d8-bdf6d66b5c6a.png)

**Comment by yegusa** [comment]
できるようになったので、こちらはクローズします。
