### ISSUE TITLE
インポートのAmazon S3対応（heroku対応のため）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#608]
#513 と関連した issueです。

**Comment by yegusa** [comment]
利用者のインポートを試してみました。

失敗となります。

http://dev.next-l.jp/user_import_files/31
![image](https://cloud.githubusercontent.com/assets/1328499/7489734/f526591e-f414-11e4-877a-6a1182259b80.png)

インポートしたデータ
<pre>
username	keyword_list	password
user1505061722	日本史//地理	golden
</pre>

**Comment by nabeta** [comment]
パスワードが短すぎるようです。8文字以上にしてください。

**Comment by yegusa** [comment]
っていうメッセージはこの画面で、出せないのですかね？

**Comment by yegusa** [comment]
利用者インポートができることは確認しました。
![image](https://cloud.githubusercontent.com/assets/1328499/7506052/bb59288e-f495-11e4-82d3-9f7b1d80cd89.png)

**Comment by yegusa** [comment]
ところでamason s3の生URLがでてますが、これは出ないように修正するんですよね？

**Comment by yegusa** [comment]
残っている確認作業：
* 書誌データのインポート
* 催しもののインポート

**Comment by nabeta** [comment]
> ところでamason s3の生URLがでてますが、これは出ないように修正するんですよね？

インポート用ファイルの表示で、S3のURLを表示しないように修正しました。開発サーバに反映済みです。

**Comment by yegusa** [comment]
書誌データのインポートができていることを確認しました

http://dev.next-l.jp/resource_import_files/155
![image](https://cloud.githubusercontent.com/assets/1328499/7536038/cff7532e-f5c6-11e4-8417-bb94670e208f.png)

**Comment by yegusa** [comment]
催し物のインポートもできることを確認しました。

http://dev.next-l.jp/event_import_files/13
![image](https://cloud.githubusercontent.com/assets/1328499/7536203/c0c44892-f5c8-11e4-861c-e3b021bb1d4b.png)

**Comment by yegusa** [comment]
全てを確認しましたので、クローズします。
