### ISSUE TITLE
特定のレコードの書誌をNDLサーチからインポートしようとするとWe're sorryとなる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#610]
例えば
http://iss.ndl.go.jp/books/R100000002-I000008276603-00

このレコードをNDLサーチからインポートしようとするとWe're sorry となります。
必ずどのレコードでもおきるのではなくて、いくつかの特定のレコードのみにおきます。

仮想マシンで、以下のbundle list の状況で発生することを確認しました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 a9efbc9)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 8691486)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)

log/production.log の一部は以下のとおり

> D, [2015-05-06T07:01:28.310715 #1357] DEBUG -- :   SOLR Request (5.1ms)  [ path=update parameters={} ]
> D, [2015-05-06T07:01:28.312032 #1357] DEBUG -- :    (0.4ms)  rollback transaction
> I, [2015-05-06T07:01:28.330785 #1357]  INFO -- : Completed 500 Internal Server Error in 2468ms
> F, [2015-05-06T07:01:28.335942 #1357] FATAL -- :
> NoMethodError (undefined method `index' for nil:NilClass):
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-a9efbc96913d/app/models/manifestation.rb:416:in `block in index_series_statement'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `map'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/relation/delegation.rb:46:in `map'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-a9efbc96913d/app/models/manifestation.rb:416:in `index_series_statement'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-a9efbc96913d/app/models/manifestation.rb:248:in `block in <class:Manifestation>'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_touch_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/callbacks.rb:296:in `touch'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:295:in `block in touch'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:347:in `block in with_transaction_returning_status'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:220:in `transaction'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:344:in `with_transaction_returning_status'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/transactions.rb:295:in `touch'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/no_touching.rb:49:in `touch'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/associations/builder/belongs_to.rb:92:in `touch_record'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/associations/builder/belongs_to.rb:103:in `block in add_touch_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `instance_exec'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:443:in `block in make_lambda'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:225:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:219:in `block in halting_and_conditional'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'

**Comment by nabeta** [comment]
#591 の修正による不具合でした。修正済みで、ローカル環境で動作を確認しています。

**Comment by yegusa** [comment]
bundle update して、できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/7489045/77feb97e-f40d-11e4-8488-e15be232622c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre66 f29f883)
  * enju_circulation (0.1.0.pre43 b6d1b12)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21 264a590)
  * enju_leaf (1.1.0.rc18 ae3932a)
  * enju_library (0.1.0.pre40 7949d16)
  * enju_loc (0.1.0.pre4 52be501)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35 7b1388e)
  * enju_subject (0.1.0.pre29 241b63a)
