### ISSUE TITLE
利用者グループと貸出区分の設定時の処理でタイムアウトエラーになる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#611]
利用者グループに対する貸出区分を設定する際、全所蔵レコードに対する貸出ルールの設定が行われます。
所蔵レコードが多い状態でこの設定を変更すると、そのままではタイムアウトエラーになってしまいます。

設計を見直すか、非同期処理化するか、検討が必要と思われます。

以下、南三陸町案件における @nabeta コメントの引用：
> 貸出ルール(LendingPolicy)は所蔵(Item)ごとに、利用者グループと貸出区分(UserGroupHasCheckoutType)をもとに作成するようになっているため、貸出区分を変更すると、全所蔵レコードに対して貸出ルールの再作成処理が走ります。このため、所蔵レコードが少ない仮想マシンでは動いても、南三陸町でエラーが発生するものと思われます。
> 本来は非同期で行うべき処理であり、修正が必要です。

**Comment by nabeta** [comment]
所蔵ごとの貸出ルールのレコードはあらかじめ全区分を作成するのではなく、最初の貸出時にその利用者の所属する利用者グループと貸出区分のみのルールを作成するようにしました。

**Comment by nabeta** [comment]
例外が必要になったら、新規で貸出区分を作ればよいのでは、という意見が第38回ワークショップで出た。

**Comment by yegusa** [comment]
最初の貸し出し時に作るってだけだと、全部つくるよりは少なくなるってだけですよね。まあ、やらないよりはましなきがしますが。。。

複本で、異なる貸出区分になるって例は、私の知ってるところでは、
- 旅行ガイドで、地域資料としての本は貸出不可、旅行の本としては貸出可（例：足立区立図書館の「足立本」）
- 冊子体目録で、レファレンスブックとしては貸出不可、報告書の一部としては貸出可

あたりかな。この場合は、別な貸出区分（レファレンスブックとか地域資料とか）でやるのがよさそうな気はします。

**Comment by yegusa** [comment]
開発サーバーで、所蔵が 2万件以上ある状況で
新しく、「テスト団体」という利用者グループを作って、
利用者グループ：「テスト団体」に対する貸出区分「図書」を設定してみたら、
タイムアウトせずにできました。クローズします。

http://dev.next-l.jp/user_groups/8/user_group_has_checkout_types/new
![2015-06-25-ka1](https://cloud.githubusercontent.com/assets/1328499/8370377/fea3633c-1c01-11e5-92ad-5ad940afdf3b.png)

http://dev.next-l.jp/user_groups/8
![2015-06-25-ka2](https://cloud.githubusercontent.com/assets/1328499/8370381/02e2a3ea-1c02-11e5-9b01-b5137576f813.png)

http://dev.next-l.jp/user_group_has_checkout_types
![2015-06-25-ka3](https://cloud.githubusercontent.com/assets/1328499/8370383/09f801a2-1c02-11e5-908d-857b915e86e5.png)
