### ISSUE TITLE
Rails 4.2.1においてWEBrickが反応しない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#613]
手元で development 環境で動作していてハマったのでご報告まで。

http://guides.rubyonrails.org/4_2_release_notes.html#default-host-for-rails-server
にある通り、Rails 4.2.1 以降では仮想マシン上で起動されたRailsサーバの起動方法を変更しないとアクセスできない状態になっています。起動方法は以下のように -b オプションを与えるだけですが。

```
rails s -b 0.0.0.0
```

ひょっとすると、production だと発生しないかも？　Rails 4.2.1対応の一環として要確認。

**Comment by nabeta** [comment]
production環境でも同様の変更が必要です。wikiの記述は修正しました。
https://github.com/next-l/enju_leaf/wiki/Install#enju-leafの初期設定

**Comment by masao** [comment]
配布している仮想マシンのほうは nginx のリバースプロキシを使うから大丈夫でしょうか？

**Comment by nabeta** [comment]
現在の仮想マシンではunicornを使用しており、この件の影響はありません。この設定変更は、Webrickだけで動かすときに必要です。

**Comment by masao** [comment]
とりあえず文書化もすんでいるので、完了です。
