### ISSUE TITLE
分類記号が登録されていない場合の区切り記号の表示を省略する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#615]
#569 で追加された検索結果一覧でのNDC記号ですが、NDCが登録されていない書誌行でも区切り記号（ ; ）が表示されるのがかっこわるいので、これを省略するようにしましょう。

**Comment by nabeta** [comment]
分類がない場合は、区切り文字を表示しないようにしました。
http://dev.next-l.jp/manifestations?utf8=✓&query=&commit=検索

**Comment by nakamura-akifumi** [comment]
修正されていることを確認しましたのでクローズします。
