### ISSUE TITLE
仮想マシン：共有フォルダ機能を切る

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#618]
vagrant共有フォルダ機能が有効になっていて警告が出るため、共有機能をきった状態の仮想マシンを作成する必要がある。

**Comment by nabeta** [comment]
仮想マシン用のVagrantfileを修正しました。
https://github.com/next-l/enju_leaf_vm/commit/da11eb84bcf3a28112ff676291b850e8b141acf8

**Comment by masao** [comment]
rc19で修正されていることを確認しました。クローズします。
