### ISSUE TITLE
各モデルの詳細表示で存在しないものを表示するとHTTPステータスコード500が帰る

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#620]
dev.next-l.jpにおいて、存在しないデータを詳細表示するとHTTPステータスコード500が帰る。
接続ユーザは、ライブラリ権限(tmpz84) です。

各url（モデル）とステータスは以下のとおり。

500になる。404にすべき。
http://dev.next-l.jp/identifier_types/(n)
http://dev.next-l.jp/message_templates/(n)
http://dev.next-l.jp/bookstores/(n)
http://dev.next-l.jp/budget_types/(n)
http://dev.next-l.jp/event_categories/(n)

502 （よくわからない）
http://dev.next-l.jp/bookstores/(n)

**Comment by nabeta** [comment]
開発サーバにrambulanceという、エラー画面をカスタマイズするgemを入れていたのですが、これの設定が不完全でした。gemを外しました。
https://github.com/yuki24/rambulance

**Comment by yegusa** [comment]
確認作業しようと思ったのですが、何が正解かわかりません。

http://dev.next-l.jp/identifier_types/100
![image](https://cloud.githubusercontent.com/assets/1328499/8370208/96d9660e-1bff-11e5-965a-dd598e6c247d.png)

↑こうなっていれば、想定通りの動き(404)だという理解であってますか？

**Comment by nabeta** [comment]
はい、そうです。

**Comment by yegusa** [comment]
チェックリスト：

![image](https://cloud.githubusercontent.com/assets/1328499/8370208/96d9660e-1bff-11e5-965a-dd598e6c247d.png)

↑と同様の画面になっていることを確認する。

500になる。404にすべき。

- [ ] http://dev.next-l.jp/identifier_types/100
- [ ] http://dev.next-l.jp/message_templates/100
- [ ] http://dev.next-l.jp/bookstores/100
- [ ] http://dev.next-l.jp/budget_types/100
- [ ] http://dev.next-l.jp/event_categories/100

502 （よくわからない）

- [ ] http://dev.next-l.jp/bookstores/100

**Comment by yegusa** [comment]
すべて確認したので、クローズします。
