### ISSUE TITLE
languageの詳細表示でエラーになる

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#621]
http://enju.next-l.jp/languages/2

**Comment by nabeta** [comment]
以下のコミットで修正しました。
https://github.com/next-l/enju_biblio/commit/cf59d4040bdbc0267dc201ba373d4b07c65f6196

開発版では修正済みです。
http://dev.next-l.jp/languages/2

**Comment by yegusa** [comment]
開発サーバーで表示されることを確認しました。のでクローズします。

http://dev.next-l.jp/languages/2
![image](https://cloud.githubusercontent.com/assets/1328499/8266195/0798d536-175b-11e5-9f6a-3d6b868ab8ba.png)
