### ISSUE TITLE
例外所蔵情報のレコード分だけをLending Policyに加える形にすること

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#622]
#611 からの派生。

理想的には、例外分のレコードだけを Lending Policy に加える形にするのがよい。
そのうち例外レコードだけを Lending Policy に持つように変更したい。 by @nabeta （2015年5月末；第38回開発ワークショップ）

**Comment by nabeta** [comment]
2.0系ではLendingPolicyモデルを削除しています。1冊ごとに貸出規則の例外を設定するかわりに、別途通常の貸出規則を設定することになります。
