### ISSUE TITLE
パスワード変更フォームの変更

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#625]
現在のパスワード変更フォームは独自に用意しているが、deviseが標準でフォームを用意しているため、そちらを使うように変更したい。以下のSolution 2を想定。
https://github.com/plataformatec/devise/wiki/How-To:-Allow-users-to-edit-their-password

**Comment by nabeta** [comment]
上記のSolution 2で実装済み。現在のパスワード編集フォームは、 app/views/devise/registrations/edit.html.erb を使用するようになっている。
https://github.com/next-l/enju_leaf/blob/master/app/views/devise/registrations/edit.html.erb

**Comment by yegusa** [comment]
いつのバージョンで，実行が完了したんですか？それを教えてください。一旦，オープンにもどします。

**Comment by nabeta** [comment]
@yegusa enju_leaf-1.2.2です。アップデート手順では以下の部分になります。
https://github.com/next-l/enju_leaf/wiki/Update#121%E3%81%8B%E3%82%89122%E3%81%B8%E3%81%AE%E3%82%A2%E3%83%83%E3%83%97%E3%83%87%E3%83%BC%E3%83%88%E6%89%8B%E9%A0%86

**Comment by yegusa** [comment]
確かめかたわからないので， @masao　さんよろしく。

**Comment by masao** [comment]
パスワード変更画面が動作することは確認しました。ひとまずクローズします。
