### ISSUE TITLE
検索結果UIの追加：書影のグリッド表示による表示モード

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#628]
#531 と関連して。
カーリル風の書影をグリッド表示させる表示UIがあると、複本が無いタイプの見栄えでよいように思います。

**Comment by masao** [comment]
実装は追加しましたので、確認をお願いします。
https://github.com/masao/enju_grid/tree/1.1
をモジュール読み込みすれば、使えます。

**Comment by nabeta** [comment]
手元の環境に組み込んでみました。通常の一覧形式と切り替えるリンクがあるとよいと思いました。

**Comment by masao** [comment]
@nabeta さんの要望は #853 に切り分けることにして、こちらはクローズしたいと思います。

**Comment by masao** [comment]
https://github.com/next-l/enju_grid にフォークされたのでクローズします。
