### ISSUE TITLE
バグ：書誌と所蔵のエクスポートがWe're sorryになる。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#629]
書誌と所蔵のエクスポートがWe're sorryになる。

http://dev.next-l.jp/resource_export_files/new

**Comment by nabeta** [comment]
修正しました。開発サーバに反映済みです。

**Comment by nakamura-akifumi** [comment]
確認しました。クローズします。

エビデンスは以下の画面キャプチャです。

![2015-06-20 15 48 09](https://cloud.githubusercontent.com/assets/1065528/8266325/db1b1ce0-1763-11e5-8883-37f41c60f22c.png)
