### ISSUE TITLE
1.0.2からの変更点を中心に（1.1.0リリースに向けての文書整備）

### ISSUE THREAD

**Issue by ineku** [next-l/enju_leaf#633]
1.0.2からの変更点
- データのインポート方法
- 操作上の違い
- 内部構造などについての解説

**Comment by yegusa** [comment]
#634 の調査で、1.0.2の利用者が出なかったので、もし、1.0.2の利用者がでてきたら、個別対応することとし、とくにドキュメントはひとまずつくらないこととする。

そのため、クローズする。
