### ISSUE TITLE
1.1.0リリースに向けて，1.0.2利用者の調査をした方がいいかも

### ISSUE THREAD

**Issue by ineku** [next-l/enju_leaf#634]

**Comment by yegusa** [comment]
#632 より、こちらを先にやる

**Comment by masao** [comment]
https://www.facebook.com/projectnextl/posts/864821700265640 にて利用調査アンケートを開始。MLでも広報済み。

**Comment by masao** [comment]
一応、〆切が来ました。アンケート回答は5件ですが、利用バージョンは以下の通りでした：
・Next-L Enju Leaf 1.1.0.rc19
・Next-L Enju Leaf 1.1.0.rc17
・Next-L Enju Leaf 1.1.0.rc16
・Next-L Enju Leaf 1.1.0.rc7から1.1.0.rc15
・Next-L Enju Leaf 1.1.0.rc20

**Comment by yegusa** [comment]
Enju WS 2015-09-12 の参加者で確認したので、クローズする。
