### ISSUE TITLE
利用者情報を別システムで管理できるようにする

### ISSUE THREAD

**Issue by ineku** [next-l/enju_leaf#636]
氏名をどうするかは検討

**Comment by ineku** [comment]
現実的にはカード忘れの場合と督促の場合か
セキュリティを考えれば，スタンドアロンで使える個人情報管理ツールがあれば良い

**Comment by daypla** [comment]
藤原です。こちらとりあえず既存のprofile, userモデルの既存スキーマ項目との対照エクセルです。国立国会図書館と横浜市立図書館の利用登録申請書の項目も中にリンクを張ってあります。
https://www.dropbox.com/s/al1fxkp7n8g5aaw/tempshare2015.09.12enju_github_issue636.xlsx?dl=0

**Comment by yegusa** [comment]
Excel 2010 で、デモサーバーへリンクするものをつくってみましたが、
ExcelのHYPERLINK関数を使って作ったリンクをたどると、
Enjuトップに飛ばされてしまいます。

作成したファイルは以下に置いています：
http://www.next-l.jp/?page=etc%5Ffiles&file=userinfo%5Flocalfile%5Fsample%2Exlsx&action=ATTACH

ちなみに、HTMLや、PDFに変換して使うとリンクをたどると、ちゃんと、利用者検索結果にたどりつくことはできるのですが。

**Comment by masao** [comment]
http://stackoverflow.com/questions/2653626/why-are-cookies-unrecognized-when-a-link-is-clicked-from-an-external-source-i-e にあるとおり、Microsoft Office系のツールはリンク先の取得時にCookieを有効にしていないそうなので、ログイン画面に戻されてしまうバグがあります。
ただし、上記サイトにも載っていますが、これに対応するための簡単な修正が出ているようです。
→ https://github.com/spilliton/fix_microsoft_links

Enjuアプリケーション側でGemfileの末尾に以下の1行を追加すると、Excel等からのリンクを受け付けてページ表示を行うことができるようです。
```
gem "fix_microsoft_links"
```

**Comment by yegusa** [comment]
すばらしい！できました。

これ、配布する仮想マシンのGemfileには設定しておきましょうよ。
デモサーバーも設定しておいてもらえるとうれしいです　→ @nabeta

**Comment by yegusa** [comment]
やり方：

### 0. Enju の設定（Excelファイルからのリンクに対応するために必要）

（1回だけ必要です）

    $ cd enju
    $ vi Gemfile
    
として、Gemfile の最後に以下の行を追加

   gem "fix_microsoft_links"

ファイルを保存

   $ bundle update
   $ sudo restart enju_leaf

として、Enjuを再起動。

### 1. 利用者情報のExcel ファイルを作ります。

例えば、Excelでこんなファイルをつくります

![image](https://cloud.githubusercontent.com/assets/1328499/9835655/54094690-5a30-11e5-8594-7f331723fdf9.png)

このファイルで、生年月日や住所などEnjuに入力していない情報で利用者の情報を検索して、本人確認のための利用者情報を調べることができますし、URLのリンクをたどれば、その利用者のページにたどりつけます。

サンプルファイルは、
http://www.next-l.jp/?page=etc%5Ffiles&file=userinfo%5Flocalfile%5Fsample%2Exlsx&action=ATTACH
にありますので、参考にしてください。

このExcelファイルにパスワードを掛けておけば、最低限のセキュリティは保てるかとおもいます。
もちろん、Access などほかのアプリケーションでもできます。

例えば、「ユーザ名」が 「u550001」 であれば、以下のようなURLを書けば
そのユーザ名の検索結果のページに行きます。「localhost:8080」のところは適宜、書き換えてください。
（例えば、デモサーバーであれば、 「enju.nex-l.jp」になります。）

    http://localhost:8080/profiles?query=username_s%3Au550001

このリンクをたどるとその「ユーザー名」で検索した結果にとびます

### 2. 該当利用者の検索結果（該当利用者の「利用者番号」のリンクをたどります。）

![image](https://cloud.githubusercontent.com/assets/1328499/9835672/d4c92222-5a31-11e5-84b9-7e2bded05e99.png)

### 3. 該当利用者のページ（貸出処理などへ進めます）

![image](https://cloud.githubusercontent.com/assets/1328499/9835682/44f45364-5a32-11e5-976c-7a523dc70d17.png)

↑で貸出リンクをクリックすると、貸出処理へ進められます。

**Comment by yegusa** [comment]
Excelでやることを推奨しているわけではありません。あくまでも、一例をしめしたという状況ですので、適宜、都合の良いツールを使っていただければとおもいます。
あと、サンプルに示したExcelファイルの個人情報は架空のものです。

**Comment by yegusa** [comment]
マニュアルのどっかに入れないとですね。

**Comment by masao** [comment]
利用者の詳細画面に直接飛べないと不便だと思うので、本体に手をいれて、

http://localhost:8080/profiles?username=u550001

といったURLを用意しておいて、直接に詳細画面に飛ぶようにしたほうがよいかと思います。

**Comment by yegusa** [comment]
私もそう思います。

**Comment by nabeta** [comment]
usernameパラメータに利用者のユーザ名が指定された場合、もしそのユーザ名が存在すれば、その利用者の詳細画面にリダイレクトするようにしました。
http://dev.next-l.jp/profiles?username=tmpz84name

存在しない場合は検索画面が表示されます。
http://dev.next-l.jp/profiles?username=nonexistent

**Comment by yegusa** [comment]
いいですね！
手元の仮想マシンでもできることを確かめました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7b5fb10)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 8acf4bc)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by yegusa** [comment]
やり方：

### 0. Enju の設定（Excelファイルからのリンクに対応するために必要）

（1回だけ必要です）

    $ cd enju
    $ vi Gemfile
    
として、Gemfile の最後に以下の行を追加

   gem "fix_microsoft_links"

ファイルを保存

   $ bundle update
   $ sudo restart enju_leaf

として、Enjuを再起動。

### 1. 利用者情報のExcel ファイルを作ります。

例えば、Excelでこんなファイルをつくります

![image](https://cloud.githubusercontent.com/assets/1328499/9841877/f91e6b78-5ae0-11e5-9de7-24267035ef81.png)

このファイルで、生年月日や住所などEnjuに入力していない情報で利用者の情報を検索して、本人確認のための利用者情報を調べることができますし、URLのリンクをたどれば、その利用者のページにたどりつけます。

サンプルファイルは、
http://www.next-l.jp/?page=etc%5Ffiles&file=userinfo%5Flocalfile%5Fsample%2Exlsx&action=ATTACH
にありますので、参考にしてください。

このExcelファイルにパスワードを掛けておけば、最低限のセキュリティは保てるかとおもいます。
もちろん、Access などほかのアプリケーションでもできます。

例えば、「ユーザ名」が 「u550001」 であれば、以下のようなURLを書けば
そのユーザ名の検索結果のページに行きます。「localhost:8080」のところは適宜、書き換えてください。
（例えば、デモサーバーであれば、 「enju.nex-l.jp」になります。）

    http://localhost:8080/profiles?username=u550001

このリンクをたどるとその「ユーザー名」の詳細画面にとびます

### 2. 作成したExcelファイルを使う

作成した、Excelファイルを使って、利用者の生年月日等で本人確認を行い、
ユーザ名を知ることができます。
そして、「リンク」列の当該「ユーザ名」のリンクをたどると、
その「ユーザー名」の詳細画面にとびます。

例えば、「ユーザ名」が 「u550001」 であれば、「リンク」列の

    http://localhost:8080/profiles?username=u550001

をクリックします

### 3. 該当利用者のページ（貸出処理などへ進めます）

![image](https://cloud.githubusercontent.com/assets/1328499/9835682/44f45364-5a32-11e5-976c-7a523dc70d17.png)

↑で貸出リンクをクリックすると、貸出処理へ進められます。

**Comment by nabeta** [comment]
> これ、配布する仮想マシンのGemfileには設定しておきましょうよ。
> デモサーバーも設定しておいてもらえるとうれしいです　→ @nabeta

デモサーバ・開発サーバ・仮想マシン作成用テンプレートとも、 fix_microsoft_links を使用するように設定しました。仮想マシン用テンプレートは以下を参照してください。
https://gist.github.com/nabeta/5357321#file-enju_leaf_template-rb-L19

**Comment by masao** [comment]
:+1:

**Comment by yegusa** [comment]
デモサーバーでもできることを確認しました。
あとの残り作業は、「マニュアル」に書くことですね。

**Comment by yegusa** [comment]
とありえず、マニュアルにも書きましたので、クローズします。
http://next-l.github.io/manual/enju_operation_3.html#section3-8

いや～、長かったですね～。
