### ISSUE TITLE
利用者のエクスポート画面でエラーになる

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#640]
http://enju.next-l.jp/user_export_files/new

**Comment by nabeta** [comment]
以下のコミットで修正済み。
https://github.com/next-l/enju_leaf/commit/353df56bd516e4d2b4ca8471dff18c6e84be0070

**Comment by yegusa** [comment]
We're sorry になるってことね。

http://enju.next-l.jp/user_export_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/8696401/f9b4a2e4-2b26-11e5-90d8-ccdd0844db91.png)

http://dev.next-l.jp/user_export_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/8696425/27d42654-2b27-11e5-93b6-02781d8e2acf.png)

開発サーバーでエラーにならないことを確認したのでクローズします。
