### ISSUE TITLE
分類の詳細表示画面でエラーになる

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#641]
http://enju.next-l.jp/classifications/1

**Comment by yegusa** [comment]
エラー = We're sorry になるってことですね。
原因はなんだったんですか？

**Comment by nabeta** [comment]
#178 の修正の際のものだと思われます。開発サーバでは修正済みです。
http://dev.next-l.jp/classifications/1

**Comment by yegusa** [comment]
memo OKなはず、あとでスクリーンショットをつけてクローズします。

**Comment by yegusa** [comment]
We're sorry にならないことを確認しましたのでクローズします。

http://dev.next-l.jp/classifications/1

![image](https://cloud.githubusercontent.com/assets/1328499/9024464/4e78f7ac-390b-11e5-949f-0d81df086944.png)
