### ISSUE TITLE
貸出区分のデータを削除し、該当の所蔵情報の詳細表示を試みるとエラーが発生しました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#642]
Next-L Enju 開発ワークショップ #38では大変お世話になりました。
ありがとうございました。

本日、貸出区分(checkout_types)のデータを削除し、
該当の所蔵情報(items)の詳細表示(showアクション)を試みるとエラーが発生しました。

エラーを確認した環境は

Next-L Enju Leaf 1.1.0.rc12 64bit版(zipファイル) （VirtualBox用）(2014年7月23日作成, 548MB, sha1sum: 78903abd5758e25fb6979abcc08a2571697789f5)

となります。

貸出区分を削除することは滅多にない行為だと思いますが、念のため、ご報告いたします。

**Comment by nabeta** [comment]
報告ありがとうございます。ひもづいている所蔵が存在する貸出区分は、削除できないようにする必要がありますね。

**Comment by harasugi** [comment]
ご返答のほど、ありがとうございます。
現在、next-l enjuの導入に向けてソースコードを読ませて頂いております。
大変読みやすく、自分の勉強にもなります。
こうした機会を与えて頂きまして大変感謝しています。

今後とも機会がありましたらよろしくお願いいたします。

**Comment by yegusa** [comment]
残り作業：
@nabeta さんが「ひもづいている所蔵が存在する貸出区分は、削除できないようにする」したので、チェックする。

**Comment by yegusa** [comment]
ひもづいている所蔵が存在していると、貸出区分の「削除」リンクが表示されておらず、削除できなくなっていることを確認しましたので、クローズします。

ひもづいている所蔵が存在しない貸出区分の場合
http://dev.next-l.jp/checkout_types
![image](https://cloud.githubusercontent.com/assets/1328499/9025002/72d18bf4-392a-11e5-946a-14ec37d4ff11.png)

DVDに紐付く所蔵を追加する
http://dev.next-l.jp/items/17408
![image](https://cloud.githubusercontent.com/assets/1328499/9025011/bd30383a-392a-11e5-8ad7-e4652d414b35.png)

ひもづいている所蔵が存在する貸出区分の場合
http://dev.next-l.jp/checkout_types
![image](https://cloud.githubusercontent.com/assets/1328499/9025003/7b0919cc-392a-11e5-903c-d08824cf8b1d.png)
