### ISSUE TITLE
Next-L Enju Leaf 1.1.0.rc19 64bit版においてポート8080を指定してアクセスするとcssが適用されませんでした。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#643]
Next-L Enju Leaf 1.1.0.rc19 64bit版においてポート番号に8080を指定してアクセスするとcssが適用されませんでした。スクリーンショットを添付します。

![201507021500](https://cloud.githubusercontent.com/assets/13130417/8471027/a717f052-20ce-11e5-8a54-027ad4ef68b9.png)

ポート番号の指定を省略すると動作デモと同様の画面表示になりました。

以上、ご報告いたします。

**Comment by yegusa** [comment]
@nabeta さん、わかります？

**Comment by nabeta** [comment]
これは、仮想マシンが動いているコンピュータと別のコンピュータからアクセスしていますでしょうか？

**Comment by harasugi** [comment]
ご返答のほど、ありがとうございます。
ご連絡が遅くなってしまい大変申し訳ございません。
仮想マシンが動作するコンピュータとアクセスするコンピュータは同一ですが、
ブリッジアダプターを利用していたため、別と認識されていました。

正常な動作だということを理解できました、この度はお騒がせしてしまい申し訳ございません。

ちなみに過去のリリースである
Next-L Enju Leaf 1.1.0.rc12 64bit版(zipファイル) （VirtualBox用）(2014年7月23日作成, 548MB, sha1sum: 78903abd5758e25fb6979abcc08a2571697789f5)
はブリッジアダプターを介してポート番号8080を指定しアクセスしてもCSSが適用されていました。

最新版では変更されたのだと理解しました。
