### ISSUE TITLE
Javaのバージョン (sunspot_solr)

### ISSUE THREAD

**Issue by himkt** [next-l/enju_leaf#644]
お疲れ様です。

https://github.com/next-l/enju_leaf/wiki/Install

では、Requirementで
Java SE1.7
を指定しています。

しかし、いつの間にか
https://github.com/sunspot/sunspot/tree/master/sunspot_solr/solr
でJava 1.7 or laterになっていました。

手元でビルドしてみましたが、Java 1.8.0_45がインストールされた計算機(OSX)で成功しました。

もしコア開発者な方々も再現できればwikiのRequirementを

Java SE 7

から

Java SE 7 or later

に修正して良いと思います。

**Comment by nabeta** [comment]
報告ありがとうございます。
現在のsunspot_solrは、masterブランチではJava8に対応したSolr 5.0が同梱されているようですが、この変更をとりこんだgemはまだリリースされていません。また、現在のsunspot_solrに同梱されているSolrは4.2.0で、Java8には正式に対応していません。ですので、新しいsunspot_solrがリリースされた後にこの修正を行うつもりです。

**Comment by himkt** [comment]
わかりました、ありがとうございます

**Comment by yegusa** [comment]
@masao 確認して、よければクローズおねがいします。

**Comment by masao** [comment]
第40回開発ワークショップでのメモ：まだ新しいバージョンのgemがリリースされていないので、リリース待ちの状態。

**Comment by nabeta** [comment]
先ほどリリースされたsunspot-solr-2.2.1では、同梱されているSolrが5.0.0に更新されていました。
https://github.com/sunspot/sunspot/tree/master/sunspot_solr/solr/server/solr-webapp/webapp/WEB-INF/lib

これからテストを行います。

**Comment by nabeta** [comment]
手元の環境でテストしてみましたが、設定ファイルに互換性がなく、修正を行う必要があります。以下が修正例です。
https://cwiki.apache.org/confluence/display/solr/Moving+to+the+New+solr.xml+Format

ただ、仮想マシンなどで使用しているsunspot_solrは、設定ファイルがなければSolrの起動時に作成してくれるので、アップデートの際は手動で修正するよりも、設定ファイルを一度捨てて作り直したほうが確実かもしれません。

**Comment by nabeta** [comment]
変更の影響が大きいので、sunspot_railsのバージョンを2.2.0に固定したenju_leaf-1.1.1をリリースしたいのですが、いかがでしょうか。2.2.1以降はenju_leaf-1.2系での対応ということで。

**Comment by yegusa** [comment]
@masao さん、いかがですか?

**Comment by masao** [comment]
1.1.1向けにバージョン固定する部分と新バージョン向けの対応確認は別の話なので、まずは別Issueに切り分けましょう。

**Comment by yegusa** [comment]
このisseueの問題自体は 1.1.0 でできてるもの?
@masao さん　マイルストーンの付与と確認（できればクローズ）よろしく～。

**Comment by nabeta** [comment]
> このisseueの問題自体は 1.1.0 でできてるもの?

enju_leaf-1.1.0でbundle updateを実行すると発生します。

**Comment by masao** [comment]
1.2.0にてsunspotのバージョンをあげるので、そこまでに確認しましょう。

**Comment by yegusa** [comment]
@masao さん、状況をおしえてください。いまいちよく分かってません。

**Comment by masao** [comment]
1.2系は、すでに Solr 5 以上を前提とする環境で動いていますので、提案の通り、インストール文書の記述を「Java SE 7以上」に変更しました。

参考までに、現在の手元の環境は以下のようなものです：

  * sunspot (2.2.5)
  * sunspot_rails (2.2.5)
  * sunspot_solr (2.2.5)

java version "1.8.0_74"
Java(TM) SE Runtime Environment (build 1.8.0_74-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.74-b02, mixed mode)
