### ISSUE TITLE
アプリケーションの起動 (foreman)

### ISSUE THREAD

**Issue by himkt** [next-l/enju_leaf#645]
お疲れ様です

https://github.com/next-l/enju_leaf/wiki/Install では、アプリケーション(your_enju)の起動を

```shell
foreman start
```

のコマンドで行っています。
しかし、
your_enju(enju_leaf?)のGemfileに

```
gem 'foreman'
```

という記述があるので、

```shell
bundle exec foreman start
```

に修正するべきではないでしょうか。

**Comment by nabeta** [comment]
提案のとおり修正しました。

**Comment by yegusa** [comment]
@masao 確認して、よければクローズおねがいします。

**Comment by masao** [comment]
修正を確認しましたので、クローズします。
