### ISSUE TITLE
小さな不具合を報告いたします。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#646]
度々失礼いたします。

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

1.
guest権限のユーザーでログインし書誌情報を参照するとサブメニューに「traslation missing」が表示されていました。
![06-07-2015 11 51 37](https://cloud.githubusercontent.com/assets/13130417/8515882/952fac70-23e6-11e5-9146-53d75993a554.png)

2.
資料検索画面にて「出版日」で絞り込みを行うとサブメニューに「この絞り込みを解除する」が表示されませんでした。

↓「出版日」での絞り込み前
![03-07-2015 14 35 31](https://cloud.githubusercontent.com/assets/13130417/8515905/d6a609c4-23e6-11e5-8b58-143024add6fe.png)

↓「出版日」での絞り込み後
![03-07-2015 14 35 39](https://cloud.githubusercontent.com/assets/13130417/8515907/d96ba966-23e6-11e5-8522-74e9aebdb1ba.png)

3.
利用者の新規作成画面において、予約語を指定したことによるエラーが表示される際、「User friendly」という文言が表示されました。
![06-07-2015 12 02 02](https://cloud.githubusercontent.com/assets/13130417/8515948/7f869ba8-23e7-11e5-87cc-7bb85251412d.png)

4.
検収の新規作成画面において、存在しない所蔵情報IDを指定した場合のエラーメッセージが「個別資料資料が見つかりませんでした。」と表示されました。
![06-07-2015 13 29 08](https://cloud.githubusercontent.com/assets/13130417/8515970/fa590ef6-23e7-11e5-8505-445ce774e116.png)

実運用上は全く問題はありませんが、一応報告いたします。
ご参考になれば幸いです。よろしくお願いいたします。

**Comment by harasugi** [comment]
追記です。

5.
パスワード再発行画面において、ログイン画面に遷移するリンクがふたつ表示されます。
![06-07-2015 16 57 18](https://cloud.githubusercontent.com/assets/13130417/8517919/50fc1fce-2400-11e5-918b-04bb1f86bac8.png)

よろしくお願いいたします。

**Comment by yegusa** [comment]
@harasugi　さんたくさん報告くださり助かります！

ひとつづつ、別のissueとして分割させてください。

**Comment by yegusa** [comment]
@nabeta このissueに関連して開発した形跡がありますが、何番の問題に対してですか？

**Comment by harasugi** [comment]
@yegusa 様

分割作業のほど、ありがとうございました！
お手数をお掛けしてしまい、申し訳ございませんでした。

>@nabeta このissueに関連して開発した形跡がありますが、何番の問題に対してですか？

@nabeta 様が対応して下さったのは次のissueとなります。

1.
guest権限のユーザーでログインし書誌情報を参照するとサブメニューに「traslation missing」が表示されていました。

よろしくお願いいたします。

**Comment by yegusa** [comment]
分割作業がすみましたので、こちらのissueはクローズします。

**Comment by harasugi** [comment]
いつもお世話になっています。
すべて迅速に対応して頂きまして、大変感謝しております！！

遠方のためワークショップへ足を運ぶことができず残念ですが、また近場で開催されるようなことがありましたら是非とも参加させて頂けたらと思います。今後ともよろしくお願いいたします。
