### ISSUE TITLE
librarian権限の利用者がadministratorにのみ参照権限を与えているadministrator権限の利用者を編集することが可能？

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#647]
Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において先ほど確認いたしました。

librarian権限の利用者がadministratorにのみ参照権限を与えているadministrator権限の利用者を編集することができました。ただ、削除を試みるとアクセスを拒否されました。

これは仕様なのでしょうか。
一応、ご報告いたします。

**Comment by yegusa** [comment]
@nabeta なにか開発した形跡がありますが、あとは確認のみということですか？

**Comment by nabeta** [comment]
はい、そうです。開発サーバに反映済みです。

**Comment by yegusa** [comment]
はい、確認してみます。

**Comment by yegusa** [comment]
librarian権限のユーザーは、administrator権限のユーザの編集や削除はできないです。
なので、本来は、利用者検索したときも、ヒットしないはず。

というわけで、まだできてないことがいろいろありますね→ @nabeta 
改修よろしく。 checkingを外しておきます。

administrator 参照のみ可のadministrator 権限のユーザー：yegusa
![image](https://cloud.githubusercontent.com/assets/1328499/9025033/1f962330-392c-11e5-9365-61bd063e1dc2.png)

librarian権限のユーザー：lib1
![image](https://cloud.githubusercontent.com/assets/1328499/9025041/8369aeea-392c-11e5-854a-e22303edb120.png)

administrator 権限のユーザー（yegusa）を、librarian権限ユーザのlib1が検索した場合：ヒットしないはず
![image](https://cloud.githubusercontent.com/assets/1328499/9025083/e52f4f48-392e-11e5-8f90-d9fc1fde5563.png)


user権限のユーザーをlibrarian権限ユーザのlib1が表示した場合：
![image](https://cloud.githubusercontent.com/assets/1328499/9025049/082374ea-392d-11e5-94e4-9df3011bf3a1.png)

administrator 権限のユーザー（yegusa）を、librarian権限ユーザのlib1が表示した場合：forbiddenになるはず
![image](https://cloud.githubusercontent.com/assets/1328499/9025054/5f6f891e-392d-11e5-8341-5208521d148a.png)

**Comment by masao** [comment]
上位レベルの権限を要求しているユーザの詳細画面そのものと編集画面へのアクセスも拒否するように変更しました。確認願います。

**Comment by nabeta** [comment]
:+1:

**Comment by yegusa** [comment]
このissueは確認事項がたくさんあって、確認しずらいので、複数のissueに分割させてください。

このissueでは、以下のみを対象とします。

librarian権限のユーザーがadministrator 権限・administratorのみ閲覧可のユーザーの
- [ ]  a) 「表示」画面を表示できてしまう　→　表示できない（アクセス不可）ように
- [ ]  b) 「編集」画面を表示できてしまう　→　表示できない（アクセス不可）ように
- [ ]  c)「編集」画面で、編集して、当該admin権限ユーザーの情報を変更できてしまう　→　編集できないように

librarian権限のユーザーがadministrator 権限・librarian以上閲覧可のユーザーの
- [ ]  d)「編集」画面を表示できてしまう　→　表示できない（アクセス不可）ように
- [ ]  e)「編集」画面で、編集して、当該admin権限ユーザーの情報を変更できてしまう　→　編集できないように

**Comment by yegusa** [comment]
以降、以下のユーザーをつかって確認していきます。

----

参考：ユーザー adminonly
![image](https://cloud.githubusercontent.com/assets/1328499/9287988/c851e7bc-436c-11e5-829e-900c1ff522b1.png)

----

参考：ユーザー enjuadmin 
![image](https://cloud.githubusercontent.com/assets/1328499/9287980/790996fa-436c-11e5-82c4-1fbdb06f4b01.png)

----

参考：ユーザー lib1 ( profiles/6 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287886/b8b03fc0-4367-11e5-8514-7866ed6e6062.png)

----

参考：ユーザー lib2 ( profiles/7 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287891/da216242-4367-11e5-877e-483edc0a4e1b.png)

**Comment by yegusa** [comment]
仮想マシンの以下のもので確認しました。 a) ～f) ができていることを確認しましたので、このissueは一旦クローズします。関連したものは派生issueとして別にたてます。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 86f1bab)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

### a) librarian権限のユーザー(lib1)がadministrator 権限・administratorのみ閲覧可のユーザー(adminonly)の「表示」画面を表示できてしまう　→　表示できない（アクセス不可）ように → OK


![image](https://cloud.githubusercontent.com/assets/1328499/9288016/af146666-436d-11e5-8296-d00f6dfe9ced.png)


###  b) librarian権限のユーザー(lib1)がadministrator 権限・administratorのみ閲覧可のユーザー(adminonly)の「編集」画面を表示できてしまう　→　表示できない（アクセス不可）ように → OK

![image](https://cloud.githubusercontent.com/assets/1328499/9288037/4bfd7a26-436e-11e5-83e6-9d5ac0b4ccff.png)


###  c)librarian権限のユーザー(lib1)がadministrator 権限・administratorのみ閲覧可のユーザー(adminonly)の「編集」画面で、編集して、当該admin権限ユーザーの情報を変更できてしまう　→　編集できないように → OK （そもそも編集画面にアクセスできないので編集できない）

###  d) librarian権限のユーザー(lib1)がadministrator 権限・librarian以上閲覧可のユーザー(enjuadmin)の「表示」画面を表示はできる　→　（一応確かめる）

![image](https://cloud.githubusercontent.com/assets/1328499/9288050/d4b59fce-436e-11e5-892d-f10b1e8c44f3.png)

###  e) librarian権限のユーザー(lib1)がadministrator 権限・librarian以上閲覧可のユーザー(enjuadmin)の「編集」画面を表示できてしまう　→　表示できない（アクセス不可）ように → OK

![image](https://cloud.githubusercontent.com/assets/1328499/9288069/7d033074-436f-11e5-83a9-d775ca383cfa.png)

### f) librarian権限のユーザー(lib1)がadministrator 権限・librarian以上閲覧可のユーザー(enjuadmin)の「編集」画面で、編集して、当該admin権限ユーザーの情報を変更できてしまう　→　編集できないように → OK（そもそも編集画面がアクセス拒否なので）

**Comment by yegusa** [comment]
https://github.com/next-l/enju_leaf/issues/647#issuecomment-131313304

の　e), f) が　NGになったので、リオープンします。

確認した環境
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
本件、開発側でもあまり文書化できていない権限の部分なので、
https://github.com/next-l/enju_leaf/wiki/FAQ 
に閲覧・編集とそれぞれの権限の関係を整理しました。あとでマニュアルにも同等の情報を入れることにします。

**Comment by yegusa** [comment]
手元の仮想マシンで、ちゃんとアクセス拒否されることを確認しました。のでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9291247/9c4dd6fc-43ef-11e5-8783-425596c8de5f.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by harasugi** [comment]
@yegusa様、@nabeta様、@masao様
この度はお手数をお掛けしました、ご対応のほど本当にありがとうございました。
それから権限の関係整理は大変参考になりました、心より感謝申し上げます。
