### ISSUE TITLE
要望貸出セッション作成時のinputタグに対するime-mode(css)指定に関して

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#648]
貸出セッション作成時のinputタグに対するime-mode(css)指定に関して、
利用者番号に対応するinputタグにはdiabledの指定がありますが、
所蔵情報IDに対応するinputタグにはime-modeの指定がありませんでした。

所蔵情報IDにもime-mode:disabled;あるいはime-mode:inactive;の指定があると
よいのではと思いましたので、ご連絡いたします。
ご参考にして頂けたら幸いです。

**Comment by yegusa** [comment]
@nabeta @masao これ、よくわからないのであとで教えてください。

**Comment by harasugi** [comment]
yegusa様

分かりづらくて申し訳ございません。

このコメントの意味するところは
利用者番号の入力は半角文字でしか入力できないよう指定されていますが、
所蔵情報IDの入力にはそのような指定はなく全角文字も入力できるようになっているので、
もし不都合が無ければ所蔵情報IDも半角文字でしか入力できないよう指定してはいかがでしょうかという提案となっています。

それから私のissueの分割作業のほど、ありがとうございました。
お手数をお掛けしました。

**Comment by nabeta** [comment]
> 所蔵情報IDにもime-mode:disabled;あるいはime-mode:inactive;の指定があると
> よいのではと思いましたので、ご連絡いたします。

この画面で入力するのはまず間違いなくバーコード番号なので、そのように修正するのがよさそうですね。

**Comment by nabeta** [comment]
デモサーバに反映しました。
http://dev.next-l.jp/baskets/new

**Comment by harasugi** [comment]
@nabeta 様
デモサーバにて動作確認をさせて頂きましたところ、自分の期待通りになっていました。
ご対応のほど、大変ありがとうございました。
