### ISSUE TITLE
バグ：購入リクエストのブックマークレットをつかうとWe're sorry になる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#649]
デモサーバにて確認

**Comment by yegusa** [comment]
@nabeta なにか開発したような形跡がありますが、これは、修正ずみで、あとは確認のみということですか？

**Comment by yegusa** [comment]
@nabeta 確認できるようにデモサーバーに、購入モジュール設定おねがいします。

**Comment by masao** [comment]
手元で動作確認しました。
http://next-l.github.io/manual/enju_install_vm_5.html#section5-1 のマニュアルに沿って
インストール設定したところ、特に問題なく動くことを確認しました。
いったんクローズしますね。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9153800/d301d4ae-3eaa-11e5-9a84-3797e030ce18.png)
