### ISSUE TITLE
「内容細目」を入れてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#650]
「内容細目」入れてほしい

例：
http://iss.ndl.go.jp/books/R100000002-I026194561-00

「部分タイトル」　となっているもの

**Comment by nabeta** [comment]
@yegusa #296 の内容で実装しているので、クローズでよいでしょうか。

**Comment by nabeta** [comment]
関連イシューがクローズされているため、こちらもクローズします。
