### ISSUE TITLE
請求記号によるワイルドカード検索が動作しない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#652]
call_number_sm:9* という検索語で、9から始まる請求記号一覧が取得できるはずだが、実際には取得できない。
http://enju.next-l.jp/manifestations?utf8=✓&query=call_number_sm%3A9*&commit=検索

**Comment by yegusa** [comment]
もうすこし原因追究がんばってみる。できればrc20でやりたい by @nabeta

**Comment by himkt** [comment]
請求記号のテーブルですが、文字列で全て一文字目は"\/"(バックスラッシュ)になっているように見えます。

http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=call_number_sm%3A%5C%2F9*&commit=%E6%A4%9C%E7%B4%A2

**Comment by yegusa** [comment]
@nabeta さん、上記のコメント確認してみてください。

**Comment by nabeta** [comment]
@himkt なるほど、そういうことだったのですね。ありがとうございます。
デモサーバでも開発サーバでも想定する動作になっているので、このissueは解決でよいと思います。
http://dev.next-l.jp/manifestations?utf8=✓&query=call_number_sm%3A1*&commit=検索

**Comment by yegusa** [comment]
よくわからないです。どういうこと？

**Comment by nabeta** [comment]
請求記号が9で始まっていると思っていたけれども、実際はスラッシュで始まっているので検索できなかった、ということです。
http://enju.next-l.jp/items/1285

**Comment by yegusa** [comment]
ああ、了解しました。問題はなかったのに、問題だと勘違いしちゃったということですね。
確認しましたので、クローズします。

メモ：強制的に前方一致検索にしてるんですね。（　「9」と入力すると　検索式では「9*」となるんですね。）

# 9から始まる請求記号を検索
http://enju.next-l.jp/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/9287666/e6b726f6-435b-11e5-85d8-d189e2a5c7d4.png)

http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&title=&creator=&publisher=&isbn=&issn=&call_number=9&item_identifier=&pub_date_from=&pub_date_to=&acquired_from=&acquired_to=&number_of_pages_at_least=&number_of_pages_at_most=&advanced_search=true&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/9287668/0b126826-435c-11e5-9f3f-60d1482ee702.png)

# /9 からはじまる請求記号のものを検索 

注：入力は 「\/9 」とする　（　/ はエスケープが必要なため）

http://enju.next-l.jp/page/advanced_search
![image](https://cloud.githubusercontent.com/assets/1328499/9287676/812675de-435c-11e5-9ff7-77cca7504853.png)

http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=&title=&creator=&publisher=&isbn=&issn=&call_number=%5C%2F9&item_identifier=&pub_date_from=&pub_date_to=&acquired_from=&acquired_to=&number_of_pages_at_least=&number_of_pages_at_most=&advanced_search=true&commit=%E6%A4%9C%E7%B4%A2\
![image](https://cloud.githubusercontent.com/assets/1328499/9287685/a28fbfa0-435c-11e5-85fc-3f8dd6383da6.png)
