### ISSUE TITLE
guest権限の利用者は予約が可能？しかし、guest権限の利用者はメール機能が利用できない？

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#653]
guest権限の利用者は自身で予約を行うことができませんが、librarian以上の権限の利用者が予約を代行することができます。
予約を行いましたら、逐次メールにて予約の状況が予約をした本人に届きますが、guest権限の利用者はメール機能を利用する権限が与えられていないようです。したがって、予約状況がどのようになったのかを知ることができないと思います。

以上、気になった点を報告いたします。

**Comment by nabeta** [comment]
図書館の利用者は、必ずUser以上の権限を持っている必要があります。そういう意味では、ユーザ情報の変更画面で、権限にGuestを設定できなくする必要がありますね。

**Comment by harasugi** [comment]
ご返答のほど、ありがとうございました。

>図書館の利用者は、必ずUser以上の権限を持っている必要があります。

このような仕様になっているのですね。

疑問に思ったことがありまして、質問させて頂けないでしょうか？
Guest権限はどのようなユーザーにどのようなタイミングで与えられるのでしょうか？また、Guest権限の範囲は資料を借りることができることのみが与えられるのでしょうか？

お手数をお掛けし申し訳ございませんが、ご返答頂けましたら大変嬉しく思います。
よろしくお願いいたします。

**Comment by yegusa** [comment]
Guest 権限というのは、ログインしないユーザー（ログインIDを持っていないユーザー）という整理です。ですので、検索ができるだけで、そのほかのすべての機能は使えない（借りることもできない）。つまり、ログインIDを持っている場合の権限はかならず、User、Librarian、Administrator になります。

> そういう意味では、ユーザ情報の変更画面で、権限にGuestを設定できなくする必要がありますね。

↑の修正が必要になりますね。

**Comment by harasugi** [comment]
yegusa様

早速のご回答のほど、詳しく説明して頂きまして大変ありがとうございまいた。
権限に関する理解を整理することができました。

**Comment by yegusa** [comment]
では、クローズしますね。
