### ISSUE TITLE
administrator以外の権限の利用者はメッセージを削除することができない？

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#654]
利用者は自身宛のメールしか参照できませんが、administrator以外の権限の利用者はその自身宛のメールを削除することができないようになっていました。「メッセージを削除する」ボタンを押下するとアクセス拒否されます。

気になりましたので、報告します。

**Comment by yegusa** [comment]
メッセージ機能ですね。
デモサーバーのほうでも同様の現象を確認しました。

enjutaro でログインして、メッセージ機能を使用。

http://enju.next-l.jp/messages で、一番上のメッセージを削除しようとするが
![2015-07-08-enjutaro1](https://cloud.githubusercontent.com/assets/1328499/8560897/27e7eb6e-2558-11e5-9c2b-41e9b824ec31.png)

http://enju.next-l.jp/messages/destroy_selected と表示されて
![2015-07-08-enjutaro2](https://cloud.githubusercontent.com/assets/1328499/8560899/2f0ac65a-2558-11e5-9721-620def4687f0.png)

http://enju.next-l.jp/messages 削除できない
![image](https://cloud.githubusercontent.com/assets/1328499/8560917/53931b8a-2558-11e5-975e-842c178dc421.png)

**Comment by yegusa** [comment]
そんなに難しくないので、修正予定です。 by @nabeta

**Comment by nabeta** [comment]
修正し、開発サーバに反映済みです。

**Comment by yegusa** [comment]
開発サーバーでためしてみました、We're sorry になりました。

![image](https://cloud.githubusercontent.com/assets/1328499/9288278/7c9cfc0a-4379-11e5-967d-54b1c63d1ccc.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9288281/9d59653c-4379-11e5-81c2-81c76fdad209.png)

**Comment by yegusa** [comment]
手元の仮想マシンでは、アクセスは拒否されましたになりました

![image](https://cloud.githubusercontent.com/assets/1328499/9288558/6237f1f4-4387-11e5-8134-b0b769c63854.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9288560/6f39b36a-4387-11e5-981c-734526237973.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 dde0110)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
next-l/enju_message@105a6703e3551930e44d1eae30a90a76ace64a88 にて修正しました。
再度、確認してみていただけますか。

**Comment by yegusa** [comment]
手元の仮想マシンで、できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9291208/293ee3f0-43ee-11e5-8304-2deaa6d95eb1.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by harasugi** [comment]
@yegusa様、@nabeta様、@masao様
この度はご対応して頂きまして大変ありがとうございました。
