### ISSUE TITLE
ユーザ情報の変更画面で、権限にGuestを設定できなくする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#655]
#653 から派生したissueです。

ユーザ情報の変更画面で、権限にGuestを設定できなくする。

http://enju.next-l.jp/profiles/112/edit （例：Enju_leaf 1.1.0.rc19　enjutaro ユーザー情報の変更画面）
![image](https://cloud.githubusercontent.com/assets/1328499/8560996/54891598-2559-11e5-869e-e5141cbffdf6.png)

参考：Guest権限とは？
Guest 権限は、ログインしないユーザー（ログインIDを持っていないユーザー）という整理です。ですので、検索ができるだけで、そのほかのすべての機能は使えない（借りることもできない）。つまり、ログインIDを持っている場合の権限はかならず、User、Librarian、Administrator になります。

**Comment by yegusa** [comment]
インタフェースを修正だけで、軽微なので修正予定

**Comment by masao** [comment]
Guest権限を選択できないように、表示UIを修正しました。
![image](https://cloud.githubusercontent.com/assets/38825/9159683/7171a2c8-3f68-11e5-8004-fa507ccd1725.png)

**Comment by yegusa** [comment]
手元の仮想マシンで動くことを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9162173/9e73ccf8-3f7f-11e5-8cd6-4f4cc787177c.png)

参考：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 c95a02d)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)
