### ISSUE TITLE
guest権限のユーザーでログインし書誌情報を参照するとサブメニューに「traslation missing」が表示

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#656]
#646 （ @harasugi より報告）から分割

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

1.
guest権限のユーザーでログインし書誌情報を参照するとサブメニューに「traslation missing」が表示されていました。
![06-07-2015 11 51 37](https://cloud.githubusercontent.com/assets/13130417/8515882/952fac70-23e6-11e5-9146-53d75993a554.png)

**Comment by nabeta** [comment]
以下のコミットで修正しています。開発サーバに反映済みです。
https://github.com/next-l/enju_circulation/commit/bd7af3d8033fffb28dcab3ca52c6d837defab657

**Comment by harasugi** [comment]
@nabeta 様
お手数をお掛けしました。
ご対応のほど、大変ありがとうございました。

**Comment by yegusa** [comment]
出来ていることを確認しましたので、クローズします。

ゲスト権限で guser を作成。　guser でログイン後、書誌詳細を閲覧したところ

http://dev.next-l.jp/manifestations/24400
![image](https://cloud.githubusercontent.com/assets/1328499/8696859/3bec63aa-2b2b-11e5-878a-418c0b20ea4d.png)

参考：：ログインせずに書誌詳細を閲覧したところ
http://dev.next-l.jp/manifestations/24400
![image](https://cloud.githubusercontent.com/assets/1328499/8696892/7928b282-2b2b-11e5-9e06-ffecfc6bae2d.png)

（guest 権限でログインできるユーザーがあるのがおかしいので、そういうユーザーが作れないようにする必要があるので、本来は、この操作はできないはず　関連： #655 ）
