### ISSUE TITLE
資料検索画面にて「出版日」で絞り込みを行うとサブメニューに「この絞り込みを解除する」が表示されません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#657]
#646 （ @harasugi より報告）から分割

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

2.
資料検索画面にて「出版日」で絞り込みを行うとサブメニューに「この絞り込みを解除する」が表示されませんでした。

↓「出版日」での絞り込み前
![03-07-2015 14 35 31](https://cloud.githubusercontent.com/assets/13130417/8515905/d6a609c4-23e6-11e5-8b58-143024add6fe.png)

↓「出版日」での絞り込み後
![03-07-2015 14 35 39](https://cloud.githubusercontent.com/assets/13130417/8515907/d96ba966-23e6-11e5-8522-74e9aebdb1ba.png)

**Comment by yegusa** [comment]
デモサーバーでためしてみました。再現しました。

例えば、 出版日の2010-2019をクリックして、出版日を絞り込む
![image](https://cloud.githubusercontent.com/assets/1328499/8747251/1e7a4a38-2ccc-11e5-92d2-a5332b189c1d.png)

本来なら、黄緑四角の位置に「この絞り込みを解除する」がでるはずだがでない

http://enju.next-l.jp/manifestations?commit=%E6%A4%9C%E7%B4%A2&pub_date_from=2010&pub_date_to=2019&query=&utf8=%E2%9C%93
![image](https://cloud.githubusercontent.com/assets/1328499/8747277/48d6769e-2ccc-11e5-83ef-f4029a0ef192.png)

**Comment by nabeta** [comment]
生成されるリンクのパラメータ名が誤っていました(pub_date_to -> pub_date_until)。
修正して開発サーバに反映させました。

**Comment by harasugi** [comment]
ご対応のほど、ありがとうございました。
出版日で絞り込みを行った際、「この絞り込みを解除する」が表示されたことを確認しました。

![next-l_enju_21-07-2015 10 43 56](https://cloud.githubusercontent.com/assets/13130417/8791420/7f2a31ce-2f95-11e5-8274-09b05ad1f5a9.png)

**Comment by yegusa** [comment]
@harasugi さんが確認してくれたのでOKなようですので、クローズします！
