### ISSUE TITLE
利用者の新規作成画面の、予約語指定時の際のエラーが変（「User friendly」が表示）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#658]
#646 （ @harasugi より報告）から分割

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

3.
利用者の新規作成画面において、予約語を指定したことによるエラーが表示される際、「User friendly」という文言が表示されました。
![06-07-2015 12 02 02](https://cloud.githubusercontent.com/assets/13130417/8515948/7f869ba8-23e7-11e5-87cc-7bb85251412d.png)

**Comment by yegusa** [comment]
私の手元の環境でも確認しました。
Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

の仮想マシンです。

http://localhost:8080/profiles/new　で、ユーザー名：admin を入れてユーザーを作ろうとした場合に、
adminは予約語のためエラーを出すのは正しい挙動ですが、
「User friendly は予約されています」というエラーメッセージはおかしいですね。

![image](https://cloud.githubusercontent.com/assets/1328499/8747371/40c04ede-2ccd-11e5-92b9-f37f347ef960.png)

**Comment by nabeta** [comment]
「ユーザ名は予約されています」に修正しました。開発サーバに反映済みです。

**Comment by nabeta** [comment]
なお、予約語は config/initializers/friendly_id.rb で指定されています。

```ruby
  config.reserved_words = %w(new edit index session login logout users admin
    stylesheets assets javascripts images)
```

**Comment by masao** [comment]
開発ワークショップ#40にて：メッセージは「このユーザ名は使用できません」としましょう。

**Comment by nabeta** [comment]
「ユーザ名は使用できません」としました。

<img width="500" alt="2015-08-01 14 16 58" src="https://cloud.githubusercontent.com/assets/11428/9020728/0ab48e18-3858-11e5-820a-ac056a64b14f.png">

**Comment by yegusa** [comment]
こちら、「このユーザ名は使用できません」となるように、もう少し頑張り中 by @nabeta

**Comment by masao** [comment]
メッセージファイルにて
```
      exclusion: ': この%{attribute}は使用できません。'
```
とすれば、一応は、「ユーザ名: このユーザ名は使用できません。」とのメッセージが作れますが、このへんで妥協しませんか。

**Comment by yegusa** [comment]
> 「ユーザ名: このユーザ名は使用できません。」

良いと思います！

**Comment by masao** [comment]
一応、変えてみました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9153830/86ef5800-3eac-11e5-8994-569242fd6920.png)
![profile enju library next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9153831/89a2be8e-3eac-11e5-898d-d142935abde1.png)

**Comment by yegusa** [comment]
手元の仮想マシンでGemfileを変更して、bundle update して試してみました。
問題ないと思いますので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9162550/294bcf96-3f81-11e5-8e97-f030ace4fd11.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9162587/5340c0a4-3f81-11e5-8063-33c3ae9b9de6.png)

参考：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 c95a02d)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by harasugi** [comment]
ソースコードのアップデート方法をまだ理解していないため確認ができておらず、大変申し訳無いのですが、この度はご対応のほど、大変ありがとうございました。
