### ISSUE TITLE
検収の新規作成画面のエラーメッセージの誤字（個別資料資料）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#659]
#646 （ @harasugi より報告）から分割

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

4.
検収の新規作成画面において、存在しない所蔵情報IDを指定した場合のエラーメッセージが「個別資料資料が見つかりませんでした。」と表示されました。
![06-07-2015 13 29 08](https://cloud.githubusercontent.com/assets/13130417/8515970/fa590ef6-23e7-11e5-8505-445ce774e116.png)

**Comment by yegusa** [comment]
デモサーバーでも現象を確認しました。

http://enju.next-l.jp/accepts/new
![image](https://cloud.githubusercontent.com/assets/1328499/8747475/67d4d94e-2cce-11e5-854f-06ce74ac73fa.png)

**Comment by nabeta** [comment]
開発サーバで修正しました。「個別資料が見つかりません」としています。

**Comment by harasugi** [comment]
ご対応のほど、ありがとうございます。
「個別資料が見つかりません。」と表示されていることを確認しました。

![next-l_enju_21-07-2015 10 39 59](https://cloud.githubusercontent.com/assets/13130417/8791380/ee4c76b2-2f94-11e5-9e70-cc062281c445.png)

**Comment by yegusa** [comment]
@harasugi さんによって確認されましたので、クローズします。
