### ISSUE TITLE
パスワード再発行画面において、ログイン画面に遷移するリンクがふたつ表示

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#660]
#646 （ @harasugi より報告）から分割

Next-L Enju Leaf 1.1.0.rc19 64bit版(zipファイル) （VirtualBox用）(2015年6月28日作成, 627MB, sha1sum: 671108c6bfa0d9d92ed850b87cc85ee53b83d4c1)

において動作確認をしていたところ、見つかった小さな不具合を報告します。

5.
パスワード再発行画面において、ログイン画面に遷移するリンクがふたつ表示されます。
![06-07-2015 16 57 18](https://cloud.githubusercontent.com/assets/13130417/8517919/50fc1fce-2400-11e5-918b-04bb1f86bac8.png)

**Comment by yegusa** [comment]
デモサーバーでも現象を確認しました。

http://enju.next-l.jp/accounts/password/new
![image](https://cloud.githubusercontent.com/assets/1328499/8747424/ea873e5a-2ccd-11e5-8a4e-f4353fecb433.png)

**Comment by nabeta** [comment]
開発サーバで修正しました。
http://dev.next-l.jp/accounts/password/new

**Comment by harasugi** [comment]
開発サーバにて修正されていることを確認しました。
ありがとうございます。

![next-l_enju_21-07-2015 10 36 56](https://cloud.githubusercontent.com/assets/13130417/8791349/8f8f6378-2f94-11e5-8e1c-f6094c6db410.png)

**Comment by yegusa** [comment]
@harasugi さんによって確認されましたのでクローズします。
