### ISSUE TITLE
デモサーバーに「Sign in with ORCID」リンクがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#661]
デモサーバーに「Sign in with ORCID」リンクがあります。
この機能は実験的なものと思われますので、削除ねがいます。
やるのであれば、開発サーバーのほうでお願いします。

http://enju.next-l.jp/accounts/sign_in
![image](https://cloud.githubusercontent.com/assets/1328499/8561355/4411635e-255f-11e5-810b-ea1b8da30786.png)

**Comment by nabeta** [comment]
削除しました。

**Comment by yegusa** [comment]
http://enju.next-l.jp/accounts/sign_in
![image](https://cloud.githubusercontent.com/assets/1328499/8696794/88af42b2-2b2a-11e5-8171-c1cb1f71a1be.png)

確認しました、クローズします。
