### ISSUE TITLE
デモサーバーのベンチマーク用の機能があるので削除する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#662]
デモサーバーに、
ベンチマーク用の機能（？）で、何秒かかったか表示されるアイコンがあります。

こちら、デモサーバーから消して、
やるなら、開発サーバーのほうに移してください。

![image](https://cloud.githubusercontent.com/assets/1328499/8561414/d90298ac-255f-11e5-8680-0548ddf684e0.png)

**Comment by nabeta** [comment]
開発サーバのみ表示するようにしました。
http://enju.next-l.jp
http://dev.next-l.jp

**Comment by yegusa** [comment]
確認しました。クローズします。
