### ISSUE TITLE
デモサーバにadminでログインできなくなっていました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#663]
デモサーバへ

ユーザー名: admin
パスワード: adminpassword

にてログインを試みると失敗します。
私の知っている範囲だと昨日の午前中から起こっているようです。
以上、ご報告いたします。

**Comment by nabeta** [comment]
修正しました。

**Comment by harasugi** [comment]
お手数をお掛けし申し訳ございませんでした。
ご対応のほど、ありがとうございました。
