### ISSUE TITLE
発行頻度テーブル(frequencies)のレコードを削除した際の挙動に関する報告

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#664]
お世話になります。
発行頻度テーブル(frequencies)のレコードを削除すると該当のレコードに紐づいていた所蔵情報の発行頻度が変化することを確認しました。

具体的には「不明・不定期刊」を削除すると該当の所蔵情報の発行頻度が「日刊」に変化しました。

以上、ご報告まで。

**Comment by nabeta** [comment]
紐付いている資料が存在しない場合にのみ、発行頻度を削除できるようにしました。
開発サーバに反映済みです。
http://dev.next-l.jp/frequencies

**Comment by harasugi** [comment]
@nabeta 様
開発サーバの動作確認をいたしました。
ご対応のほど、ありがとうございました。
