### ISSUE TITLE
メッセージ機能に関して、存在しない利用者を宛先に指定し送信を試みるとエラー画面が表示されました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#665]
お世話になっております。
メッセージ機能に関して、存在しない利用者を宛先に指定し送信を試みるとエラー画面が表示されました。

以上、ご報告まで。

**Comment by yegusa** [comment]
デモサーバーで現象を確認しました。

存在しないユーザー（mmm）へメッセージを送ろうとしているところ

http://enju.next-l.jp/messages/new
![image](https://cloud.githubusercontent.com/assets/1328499/8747568/50d263d2-2ccf-11e5-806d-8553883c45dd.png)

送信後のエラー http://enju.next-l.jp/messages
![image](https://cloud.githubusercontent.com/assets/1328499/8747586/76f5a1aa-2ccf-11e5-941c-7adbccbd240e.png)

**Comment by masao** [comment]
うーん、Railsエラーにはならなくなりましたが、エラーメッセージが不親切ですね。宛先に誤りがあることが分かるようにできませんかね。
![admin](https://cloud.githubusercontent.com/assets/38825/9021145/90167b5a-386e-11e5-9f3a-5c55354557ad.png)

**Comment by yegusa** [comment]
以下のメッセージはどうでしょう？　→ @nabeta 案から選ぶか、メッセージ案を提示してください。

a) 「ユーザ　mmm は存在しないユーザーです。」
b) 「宛先を確認してください。」
c) 「宛先に誤りがあります。宛先を確認してください。」

**Comment by masao** [comment]
標準のエラーメッセージ表示機能で、「宛て先を入力してください」と表示するところまでは確認しました：
![enjuadmin](https://cloud.githubusercontent.com/assets/38825/9153243/521e8028-3e85-11e5-9634-1d85edb95511.png)

**Comment by masao** [comment]
あ、空の場合だけでなく、宛て先の入力が間違っている場合でも同じメッセージでよいか、ご確認、コメントいただければと思います。
![enjuadmin](https://cloud.githubusercontent.com/assets/38825/9153652/5c84d68c-3ea0-11e5-8935-7aac797413e2.png)

**Comment by yegusa** [comment]
> あ、空の場合だけでなく、宛て先の入力が間違っている場合でも同じメッセージでよいか

空の場合で「宛先を入力してください」はよいですけど、
宛先が間違っている場合に「宛先を入力してください」はだめでしょう。

**Comment by masao** [comment]
宛て先が空の場合と間違っている場合とでメッセージを変えるようにしてみました。
間違っている場合は「宛て先は不正な値です」となります。
![enjuadmin](https://cloud.githubusercontent.com/assets/38825/9163410/c2e07712-3f84-11e5-994f-1d4b07459023.png)
![enjuadmin _2](https://cloud.githubusercontent.com/assets/38825/9163416/c95713da-3f84-11e5-91b9-b4e2082f9319.png)

**Comment by nabeta** [comment]
:+1:

**Comment by yegusa** [comment]
手元の環境で、たしかめてみましたが、メッセージを送信するとすると、
We're sorryとなりました。
Gemfileの書きかたがまずくて、最新版にできてないでしょうか？

agrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

ログの該当部分
15584a15585,15737
> I, [2015-08-15T09:19:05.457910 #1141]  INFO -- : Started POST "/messages" for 127.0.0.1 at 2015-08-15 09:19:05 +0000
> I, [2015-08-15T09:19:05.463140 #1141]  INFO -- : Processing by MessagesController#create as HTML
> I, [2015-08-15T09:19:05.463430 #1141]  INFO -- :   Parameters: {"utf8"=>"?", "authenticity_token"=>"Zi598p+i2GWSgheceJEMKj0ZRhRzbqbXWJm9oqlaDdleEmswz/lNj9CRsL2H5QvXHH0gAiJGhMXb71zrx/wsRQ==", "message"=>{"recipient"=>"", "subject"=>"", "body"=>"", "parent_id"=>""}, "commit"=>"メッセージを送信する"}
> D, [2015-08-15T09:19:05.473147 #1141] DEBUG -- :   [1m[35mUser Load (0.7ms)[0m  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
> D, [2015-08-15T09:19:05.478725 #1141] DEBUG -- :   [1m[36mLibraryGroup Load (0.5ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.479715 #1141] DEBUG -- : Cache read: available_languages
> D, [2015-08-15T09:19:05.481740 #1141] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-08-15T09:19:05.517294 #1141] DEBUG -- :   [1m[35mRole Load (1.0ms)[0m  SELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ?  ORDER BY roles.position LIMIT 1  [["user_id", 2]]
> D, [2015-08-15T09:19:05.519887 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.521896 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.523535 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.525518 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.527673 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.531284 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.535208 #1141] DEBUG -- :   [1m[36mCACHE (0.2ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.538452 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.555234 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.557301 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.559900 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.562383 #1141] DEBUG -- :   [1m[35mCACHE (0.1ms)[0m  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-08-15T09:19:05.564499 #1141] DEBUG -- :   [1m[36mCACHE (0.1ms)[0m  [1mSELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1[0m  [["id", 1]]
> D, [2015-08-15T09:19:05.582773 #1141] DEBUG -- :   [1m[35mMessage Load (0.8ms)[0m  SELECT  "messages".* FROM "messages" WHERE "messages"."id" IS NULL  ORDER BY "messages"."id" ASC LIMIT 1
> D, [2015-08-15T09:19:05.586669 #1141] DEBUG -- :   [1m[36mUser Load (0.4ms)[0m  [1mSELECT  "users".* FROM "users" WHERE "users"."username" = ?  ORDER BY "users"."id" ASC LIMIT 1[0m  [["username", ""]]
> D, [2015-08-15T09:19:05.588024 #1141] DEBUG -- :   [1m[35m (0.2ms)[0m  begin transaction
> D, [2015-08-15T09:19:05.595387 #1141] DEBUG -- :   [1m[36m (0.2ms)[0m  [1mrollback transaction[0m
> I, [2015-08-15T09:19:05.610479 #1141]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/gems/enju_message-0.1.14.pre24/app/views/messages/new.html.erb within layouts/messages (9.7ms)
> I, [2015-08-15T09:19:05.611422 #1141]  INFO -- : Completed 500 Internal Server Error in 147ms (ActiveRecord: 5.1ms)
> F, [2015-08-15T09:19:05.624169 #1141] FATAL -- : 
> ActionView::Template::Error (undefined method `username' for nil:NilClass):
>      7:       <%= f.error_notification -%>
>      8: 
>      9:       <div class="field">
>     10:         <label for="message_recepient"><%= t('message.recipient') -%>:</label>
>     11:         <%- if @message.recipient -%>
>     12:           <%= link_to @message.receiver.username, profile_path(@message.receiver) -%>
>     13:           <%= f.hidden_field :recipient, value: @message.recipient -%>
>   vendor/bundle/ruby/2.2.0/gems/enju_message-0.1.14.pre24/app/views/messages/new.html.erb:10:in `block in _vendor_bundle_ruby_______gems_enju_message________pre___app_views_messages_new_html_erb__2681866279116646116_87148760'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/capture_helper.rb:38:in `capture'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/form_helper.rb:444:in `form_for'
>   vendor/bundle/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
>   vendor/bundle/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
>   vendor/bundle/ruby/2.2.0/gems/simple_form-3.1.0/lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
>   vendor/bundle/ruby/2.2.0/gems/enju_message-0.1.14.pre24/app/views/messages/new.html.erb:6:in `_vendor_bundle_ruby_______gems_enju_message________pre___app_views_messages_new_html_erb__2681866279116646116_87148760'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
>   /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
>   vendor/bundle/ruby/2.2.0/gems/enju_message-0.1.14.pre24/app/controllers/messages_controller.rb:91:in `block (2 levels) in create'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
>   vendor/bundle/ruby/2.2.0/gems/enju_message-0.1.14.pre24/app/controllers/messages_controller.rb:86:in `create'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'
> 
>

**Comment by yegusa** [comment]
自己解決しました。 Gemfileにenju_messageの行を追加すればよかったんですね
> gem 'enju_message', github: "next-l/enju_message", branch: "1.1"

手元の仮想マシンで確認しました。よいと思います。

### 宛先を入力してないとき

![image](https://cloud.githubusercontent.com/assets/1328499/9288515/bbd6a2b2-4384-11e5-81b3-1c5dffed4a52.png)

(宛先は不正な値です　の行はいらない気もしますが、まあ、あっても害はないのでここままでもいいかな）

### 宛先が間違っているとき

![image](https://cloud.githubusercontent.com/assets/1328499/9288519/e09cd4ae-4384-11e5-9a89-86fcd2ffabbf.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by harasugi** [comment]
＠ yegusa様、@masao様、@nabeta様

この度はお手数をお掛けしました。
親切に対応して頂きまして大変ありがとうございました。
