### ISSUE TITLE
所定の条件を満たすと「資料の受入 > TSVファイルからのインポート」がエラーを返すようになります。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#667]
次の条件を満たすと「資料の受入 > TSVファイルからのインポート」がエラーを返すようになります。

条件：
図書館テーブルの初期レコードであるyoursを削除する。

原因：
nilがshelvesメソッドを呼んでしまうNoMethodErrorによる。

以上、ご報告まで。

**Comment by nabeta** [comment]
ログイン中のユーザの所属館に紐付く書棚を一覧に表示していたのですが、もし所属館が存在しない場合、すべての書棚を一覧に表示するように変更しました。デモサーバに反映済みです。
http://dev.next-l.jp/resource_import_files/new

**Comment by harasugi** [comment]
@nabeta 様
> ログイン中のユーザの所属館に紐付く書棚を一覧に表示していたのですが、
そのような仕組みになっていたのですね、変更作業のほど、お手数をお掛けしました。

この度はたくさんの報告をしたにも関わらず、対応して頂きまして大変ありがとうございます。

**Comment by yegusa** [comment]
> ログイン中のユーザの所属館に紐付く書棚を一覧に表示していたのですが、もし所属館が存在しない場合、すべての書棚を一覧に表示するように変更しました。デモサーバに反映済みです。

×書棚　○本棚
×デモサーバ　○開発サーバ
× もし所属館が存在しない場合  ○もし所属館の本棚が存在しない場合

ですよね？ →　@nabeta

**Comment by yegusa** [comment]
すみません、どのように修正されたか不明です。

もし、ログインユーザーの所属館の本棚がない場合
（takeuser は、竹園図書館に所属しており、竹園図書館には本棚がない状況）

デモサーバー http://enju.next-l.jp/resource_import_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/8696640/00f1c5ee-2b29-11e5-8a3a-d72cd5f9430f.png)

修正後であるはずの、開発サーバー http://dev.next-l.jp/resource_import_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/8696727/cf9a70ee-2b29-11e5-973f-3ab9f297e45d.png)

同じような状況に見えます。
修正されたのでしょうか？→ @nabeta

一応、リオープンします。

**Comment by nabeta** [comment]
> × もし所属館が存在しない場合 ○もし所属館の本棚が存在しない場合

いいえ、現状の実装は「もし所属館が存在しない場合」です。そもそも図書館からすべての本棚を削除できてしまうという、別の問題があると思います。

**Comment by yegusa** [comment]
図書館からすべての本棚を削除できてしまうという元の仕様のままとする（詳細は #671 へ）

 http://dev.next-l.jp/resource_import_files/new
この画面はこれでよいとして、こういう状態で「インポート開始」としたら、エラーが出るように、修正する。

**Comment by yegusa** [comment]
これ、もう、改修ずみ？ チェックするだけ？ → @nabeta

**Comment by nabeta** [comment]
改修済みで、デモサーバに反映済みです。

**Comment by yegusa** [comment]
開発サーバーで確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9288407/734217c4-4380-11e5-89a5-1d266a3e2ac6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9288413/9757e1b6-4380-11e5-80d4-c30a37309a0e.png)

**Comment by harasugi** [comment]
@nabeta様、@yegusa様、@masao様
この度はお手数をお掛けしました。
ご対応のほど、ありがとうございました。
