### ISSUE TITLE
TSVインポートされた所蔵情報が所蔵情報ID指定による検索でヒットしない

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#669]
確認したいことがあります。
閉架の本棚に紐づけられた所蔵情報はID指定による検索(条件を詳しく指定して検索画面において所蔵情報IDを指定した検索)では引っ掛かりませんでした。
こちらは仕様上そのようになっていると理解してよいでしょうか。

お手数をお掛けし申し訳ございませんが、ご回答頂けたら幸いです。
よろしくお願いいたします。

**Comment by nabeta** [comment]
そのような仕様にはなっていません。以下が開発サーバでの例で、個別資料IDがa00001の資料を「たちばな図書館」の「2階」（閉架）に登録しています。
http://dev.next-l.jp/manifestations?utf8=✓&query=&title=&creator=&publisher=&isbn=&issn=&call_number=&item_identifier=a00001&pub_date_from=&pub_date_to=&acquired_from=&acquired_to=&number_of_pages_at_least=&number_of_pages_at_most=&advanced_search=true&commit=検索

問題が発生しているのは複数の資料でしょうか？

**Comment by harasugi** [comment]
@nabeta 様
回答のほど、遅くなってしまい申し訳ございませんでした。
教えて頂いたURLから検索を行ったところ適切な結果を得ることができました。

ちなみに今回の件はデモサーバで確認したのですが、複数の資料ではありませんでした。
具体的にはこちらの資料です。
http://enju.next-l.jp/items/1317
関連する書誌情報のタイトル：図書館概論(http://enju.next-l.jp/manifestations/6005)
所蔵情報ID：301927174

「item_identifier_sm:301927174」で検索するとヒットしませんでした、不思議です。

**Comment by harasugi** [comment]
前回の自分のコメントで記述した「item_identifier_sm:301927174」で検索を掛けるとヒットするようになりました。ご対応頂けたのでしょうか、ありがとうございます。

しかし、次の資料(ID:301926994)を
http://enju.next-l.jp/items?utf8=%E2%9C%93&query=301926994&commit=%E6%A4%9C%E7%B4%A2&acquired_from=&acquired_until=

資料検索画面から検索しようとするとヒットしませんでした。
http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=item_identifier_sm%3A301926994&commit=%E6%A4%9C%E7%B4%A2

一応、ご報告いたします。

**Comment by yegusa** [comment]
確かにへんですね。
http://enju.next-l.jp/manifestations?utf8=%E2%9C%93&query=301926994&commit=%E6%A4%9C%E7%B4%A2

とするとヒットするのに。

インデックス作成まわりかどこかがおかしいのかも？

**Comment by masao** [comment]
所蔵情報をいま編集して更新しましたが、そうするとヒットするようになりました。
この所蔵情報は、TSVインポートで一括登録されたもののようですので、その場合にインデックスが作られないバグがあるような気がします。。

**Comment by harasugi** [comment]
@yegusa 様、@masao 様
いつもお世話になっております。
ご確認を行って頂きまして大変ありがとうございます。

>この所蔵情報は、TSVインポートで一括登録されたもののようですので、
>その場合にインデックスが作られないバグがあるような気がします。。

なるほど！だと思いました。

**Comment by masao** [comment]
少し時間が経ってしまいましたが、やはり、インポート所蔵情報の所蔵情報IDによる検索でヒットしないバグがあったようです。実装を修正しました。

**Comment by yegusa** [comment]
以下のファイルをインポートして、
<pre>
isbn	item_identifier
9784000069748	999001
9784894711396	999002
9784434048241	999003
</pre>

所蔵情報IDで検索したところヒットしましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10091629/e941c0d8-6378-11e5-98f7-5b7960898685.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)
