### ISSUE TITLE
書誌インポートのCiNii Books対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#67]
高久です。

CiNii Booksを通じた書誌インポート機能があるとうれしい場面は多いかと思います。
現行のNDLサーチで取り込めない範囲を補完できる可能性がありますし。
機能的には、NDLサーチ版と同等のもので良いと思います。

※なお、このリクエストにはCATP対応は含みません。

どうぞよろしくお願いします。

**Comment by masao** [comment]
インポートテストだけなら、基本的な部分は追加済みなので、いったんクローズしますかね。
https://github.com/next-l/enju_nii/blob/1.1/spec/models/cinii_book_spec.rb

**Comment by yegusa** [comment]
仮想マシンで確認しました。できることを確認しましたので、クローズします。
マニュアルも追記しておきました。

![image](https://cloud.githubusercontent.com/assets/1328499/10099182/250977fc-63c2-11e5-94a0-494caa593203.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by yegusa** [comment]
メモ：APIで取って来れないデータがあるので、いろいろ抜け（出版地、ページ数と大きさ、分類など）があるのはしょうがないですよね。
CiNii Books でブラウザで見れる分はAPIで提供してくれるといいんですけどねえ。
