### ISSUE TITLE
デモサーバーに同じユーザー名(ppp)がある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#670]
http://enju.next-l.jp/profiles?utf8=%E2%9C%93&query=ppp&commit=%E6%A4%9C%E7%B4%A2

![image](https://cloud.githubusercontent.com/assets/1328499/8747540/17b61206-2ccf-11e5-9f14-ac65f1bb0dfb.png)

**Comment by nabeta** [comment]
利用者情報は、UserモデルとProfileモデルに分けて持つようになっています。

- User: ユーザ名やパスワードなど、ログインに関する情報
- Profile: 氏名や所属館など、ログイン以外に関する情報

データベースにはこれらのモデルに対応するprofilesテーブルとusersテーブルがあり、profilesテーブルのuser_idカラムを使ってUserとProfileの関連を作成するようになっています。ProfileとUserは1対1で対応するので、このuser_idカラムはユニークであるべきですが、そうなっていませんでした。

新規作成時は重複したユーザ名の作成は現状でも拒否されるので、おそらく更新時にこのような状況になったと思われます。特にTSVファイルを用いたときの更新が怪しいです。

**Comment by nakamura-akifumi** [comment]
ファイルからの登録機能で、新規作成と更新で確認しました。
（devサーバにて確認）

クローズします。

![2015-08-01 16 48 12](https://cloud.githubusercontent.com/assets/1065528/9021119/23014578-386d-11e5-91a0-8858142e36d6.png)
