### ISSUE TITLE
図書館からすべての本棚を削除できてしまう

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#671]
インポート時に本棚が選択できない問題を防ぐため、最低ひとつの本棚を残すようにすべき。
https://github.com/next-l/enju_leaf/issues/667#issuecomment-121573270

**Comment by nabeta** [comment]
開発サーバに反映済みです。

**Comment by nabeta** [comment]
> インポート時に本棚が選択できない問題を防ぐため、最低ひとつの本棚を残すようにすべき。

これだと図書館が削除できなくなってしまう。

**Comment by yegusa** [comment]
なので、やはり、本棚のない図書館はOKということにする。→元に戻すことにする。　Enju WSの議論より。

**Comment by yegusa** [comment]
元にもどしてないので、いったん、 checking は外します。 @nabeta 元に戻すのよろしく。

**Comment by masao** [comment]
https://github.com/next-l/enju_library/commit/9eacedae282bc80d12f8d61c86a327c275226e95
にて既に対応済みのように見えます。動作確認しました。
Won't fix にてクローズしましょう。
