### ISSUE TITLE
利用者グループと貸出区分の関係の編集において各パラメータ値を空のまま登録しようとするとエラーになる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#676]
貸し出し数の上限などの数値入力欄で確認した。デモサーバ、開発サーバ両者で再現。
cf. http://enju.next-l.jp/user_group_has_checkout_types/1/edit

**Comment by nabeta** [comment]
0以上の数字の入力を必須としました。開発サーバに反映済みです。

<img width="500" alt="2015-08-01 16 43 45" src="https://cloud.githubusercontent.com/assets/11428/9021111/82cca282-386c-11e5-9400-2fead7aa9b77.png">

**Comment by masao** [comment]
ありがとうございます。確認しました。クローズしますね。
