### ISSUE TITLE
バグ：予約した資料について、貸出をしようとしてキャンセルしても予約一覧で「貸出済み」になってしまう

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#678]
利用者 666003 が、本 http://enju.next-l.jp/manifestations/6015 を予約する

http://enju.next-l.jp/reserves
![image](https://cloud.githubusercontent.com/assets/1328499/9021149/a7b0ac04-386e-11e5-83c5-4a7906fd92f0.png)

666003が上記の本を貸出しようとするが、貸出をやめる（「削除」する）
![image](https://cloud.githubusercontent.com/assets/1328499/9021164/2750bfda-386f-11e5-830b-73df01b8b39a.png)

本のステータスとしては、貸出というステータスになっていないが、
![image](https://cloud.githubusercontent.com/assets/1328499/9021166/4df5be7e-386f-11e5-9355-0ff08dbf52ca.png)

予約一覧では、「貸出済み」になっている
![image](https://cloud.githubusercontent.com/assets/1328499/9021167/7ee9ff86-386f-11e5-899e-e63febfabcfd.png)

**Comment by nabeta** [comment]
修正しました。開発サーバに反映済みです。

**Comment by yegusa** [comment]
開発サーバーで、できていることを確認したのでクローズします。

利用者 user0815（000101） が、本 http://dev.next-l.jp/manifestations/24400 (555001)を予約する

http://dev.next-l.jp/reserves

![image](https://cloud.githubusercontent.com/assets/1328499/9288353/7f9a5f7a-437d-11e5-992a-e35bf3dec961.png)


利用者 000101が上記の本を貸出しようとするが、貸出をやめる（「削除」する）
![image](https://cloud.githubusercontent.com/assets/1328499/9288357/c24c7f92-437d-11e5-8c5e-da001cfd8f32.png)


本のステータスとしては、貸出というステータスになっていないし、
![image](https://cloud.githubusercontent.com/assets/1328499/9288364/f3b0cc8c-437d-11e5-8d1c-f20d9413c002.png)


予約一覧では、「貸出済み」にもなっておらず、「受付済み」のままである
![image](https://cloud.githubusercontent.com/assets/1328499/9288366/0d88f404-437e-11e5-9a6a-d1c424ea0a7f.png)
