### ISSUE TITLE
開発サーバーが落ちてます

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#680]
開発サーバーにアクセスすると We're sorry となります。
http://dev.next-l.jp/

ログアウト　リンクをクリックしたら、We're sorry となるようになりました。
その後はトップへアクセスしても We're sorry に。

**Comment by nabeta** [comment]
enju_bookmarkモジュールに問題があるようで、いったん無効にしました。
原因は後で調べますが、現時点で開発サーバにはアクセスできるようになっていると思います。

**Comment by yegusa** [comment]
さっそくありがとうございます。動くことを確認しましたのでクローズします。
