### ISSUE TITLE
VM(Next-L Enju Leaf 1.1.0.rc19 64bit版)上にてrake db:seedを実行するとエラーになりました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#681]
いつもお世話になっております。
VM(Next-L Enju Leaf 1.1.0.rc19 64bit版)上にてrake db:seedを実行するとエラーになりました。
エラー内容は次となります。

rake aborted!
ActiveRecord::RecordInvalid: バリデーションに失敗しました。 ユーザ名はすでに存在します。, メールアドレスはすでに存在します。
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:79:in `raise_record_invalid'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/validations.rb:43:in `save!'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `block in save!'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:220:in `transaction'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/transactions.rb:291:in `save!'
/home/vagrant/enju/db/seeds.rb:40:in `<top (required)>'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:547:in `load_seed'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/tasks/database_tasks.rb:250:in `load_seed'
/home/vagrant/enju/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/databases.rake:180:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)

以上、ご報告いたします。

**Comment by nabeta** [comment]
公開されている仮想マシンでは、手動で rake db:seed を実行する必要はないはずなのですが、どのような場面で実行されたのでしょうか？
なお、rake db:seed はインストール時に rails g enju_leaf:quick_install の中で実行されます。

**Comment by harasugi** [comment]
@nabeta 様
>公開されている仮想マシンでは、手動で rake db:seed を実行する必要はないはずなのですが、
>どのような場面で実行されたのでしょうか？

実はVMから開発を進めたく、環境をproductionからdevelopmentへ移行しようとしていました。
rake db:seedはdevelopment環境用のDBを構築しようとした際に実行しました。

補足ですが、productionのDBをdevelopmentのDBに上書きすることでrake db:seedを実行しなくても稼働しました。
もしVMはdevelopmentで起動するようなものではないのなら、この度はお騒がせをしてしまい大変申し訳ございませんでした。

**Comment by nabeta** [comment]
ああ、そういうことですね。その場合ですと、以下のようにデータベースをコピーするのが確実です。

> 補足ですが、productionのDBをdevelopmentのDBに上書きすることでrake db:seedを実行しなくても稼働しました。

なお、仮想マシンの場合、具体的には以下のようになります。

```sh
$ cp db/production.sqlite3 db/development.sqlite3
```

PostgreSQLなどの場合、pg_dumpなどでバックアップを取ってからdevelopment用のデータベースにリストアすることになります。

**Comment by harasugi** [comment]
早速のご返答のほど、ありがとうございます！
DBのコピーの具体的手順を教えて頂きまして大変ありがとうございました。
Sqlite3のDBコピーはご紹介された方法の通りに実行しました。
PostgreSQLのDBのコピーはまだ実施したことがないため、大変参考になります！

**Comment by harasugi** [comment]
closed #681

**Comment by harasugi** [comment]
早速のご返答のほど、ありがとうございます！
DBのコピーの具体的手順を教えて頂きまして大変ありがとうございました。
Sqlite3のDBコピーはご紹介された方法の通りに実行しました。
PostgreSQLのDBのコピーはまだ実施したことがないため、大変参考になります！
