### ISSUE TITLE
librarian権限のユーザーでログインしたときにlibrarian権限のユーザーの編集画面へのアクセスが拒否される

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#685]
#647 を確認していて気づいたバグです。

librarian権限のユーザー(lib1)でログインしたときにlibrarian権限のユーザー(lib2)の編集画面へのアクセスが拒否される

![image](https://cloud.githubusercontent.com/assets/1328499/9287896/18c1bc54-4368-11e5-9424-a47ab05e847b.png)

参考：ユーザー lib1 ( profiles/6 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287886/b8b03fc0-4367-11e5-8514-7866ed6e6062.png)

参考：ユーザー lib2 ( profiles/7 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287891/da216242-4367-11e5-877e-483edc0a4e1b.png)

手元の仮想マシンで確認しました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju

enju_biblio (0.1.0.pre67)
enju_circulation (0.1.0.pre46)
enju_event (0.1.17.pre26)
enju_flower (0.1.0.pre22)
enju_leaf (1.1.0.rc20 86f1bab)
enju_library (0.1.0.pre42)
enju_manifestation_viewer (0.1.0.pre18)
enju_message (0.1.14.pre24)
enju_ndl (0.1.0.pre37)
enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
librarian権限のユーザー(lib1)でログインしたときにlibrarian権限のユーザー(lib2)の編集画面へのアクセスが拒否されないことを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9288137/9ce1dde8-4372-11e5-8a1e-dd1b80fc2e6e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9288149/eb327f5c-4372-11e5-9eac-56d4b47d06f6.png)

確認した環境：

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)
