### ISSUE TITLE
librarian権限のユーザーがlibrarian権限のユーザーを表示したときの右メニューに「編集」がでない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#686]
#647 を確認していて気づいたバグです。
( #685 とも関連しているかもです）

ibrarian権限のユーザー(lib1)がlibrarian権限のユーザー(lib2)を表示したときの右メニューに「編集」がでない

![image](https://cloud.githubusercontent.com/assets/1328499/9287916/85376108-4369-11e5-9d17-a8c4d2ab9d93.png)

参考：user 権限のユーザーの「表示」をしたところ
![image](https://cloud.githubusercontent.com/assets/1328499/9287908/0a2e1b5a-4369-11e5-9a5e-0afc8b249b0e.png)

参考：ユーザー lib1 ( profiles/6 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287886/b8b03fc0-4367-11e5-8514-7866ed6e6062.png)

参考：ユーザー lib2 ( profiles/7 )
![image](https://cloud.githubusercontent.com/assets/1328499/9287891/da216242-4367-11e5-877e-483edc0a4e1b.png)

手元の仮想マシンで確認しました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju

enju_biblio (0.1.0.pre67)
enju_circulation (0.1.0.pre46)
enju_event (0.1.17.pre26)
enju_flower (0.1.0.pre22)
enju_leaf (1.1.0.rc20 86f1bab)
enju_library (0.1.0.pre42)
enju_manifestation_viewer (0.1.0.pre18)
enju_message (0.1.14.pre24)
enju_ndl (0.1.0.pre37)
enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
#685 と同じ権限管理の問題だったので、 #685 の修正がうまくいっていれば、こちらもOkなはずです。確認願います。

**Comment by yegusa** [comment]
手元の仮想マシンで、「編集」リンクは出現し、「削除」リンクは出現しないことを確認しました。ので、クローズします。

注意：仕様上、librarian権限のユーザーはlibrarian権限以上のユーザーを編集することはできても、削除することはできないことになっている。

![image](https://cloud.githubusercontent.com/assets/1328499/9288171/44773020-4374-11e5-952d-49df7d7933ba.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)
