### ISSUE TITLE
librarian権限でログインしたときに、librarian権限のユーザーの編集画面で「削除」リンクが表示される

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#687]
librarian権限でログイン（ユーザー：lib1）したときに、librarian権限のユーザー(lib2)の編集画面で「削除」リンクが表示される

![image](https://cloud.githubusercontent.com/assets/1328499/9288154/39a9d6d0-4373-11e5-85cc-0a0ffb4470e9.png)

「削除」リンクをクリックしたあとに、「本当ですか」とポップアップがでて、OKとすると、
アクセスが拒否されました　という画面に遷移し、実際には削除できないので、
それほど致命的なバグではないが、気付いたので報告しておく。

注：仕様上、librarian権限のユーザーはlibrarian権限以上のユーザーを編集することはできても、削除することはできないことになっている。

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 7a8965c)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
修正を行いました。確認願います。

**Comment by yegusa** [comment]
手元の仮想マシンで、確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9288547/56efdeca-4386-11e5-89d0-b822f299bfc8.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 dde0110)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)
