### ISSUE TITLE
library権限のユーザーでログインした場合に、ユーザー権限を変更できてしまう

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#688]
仕様上は、library権限のユーザーでログインした場合に、ユーザー権限を変更できないはずなのに、変更できてしまう。

権限を　librarian を　administrator に選んで、更新
![image](https://cloud.githubusercontent.com/assets/1328499/9288566/194182b6-4388-11e5-9011-cc56fde13b08.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9288573/30a82342-4388-11e5-9d4d-afd33b9cbf19.png)

administrator に変更できてしまっている
![image](https://cloud.githubusercontent.com/assets/1328499/9288578/457aeee4-4388-11e5-815f-80ac9025d9a0.png)

確認した環境
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 dde0110)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by yegusa** [comment]
rc19ではおきてなかった現象のようです。rc19のデモサーバーではlibrarian権限では、権限を変更できませんので。

http://enju.next-l.jp/profiles/129/edit
![image](https://cloud.githubusercontent.com/assets/1328499/9288598/555fd63e-4389-11e5-9377-0c910029c887.png)

**Comment by masao** [comment]
#655 での修正で間違えてこの箇所を変更できるようにしてしまっていました。修正しなおしたので、確認願います。

**Comment by yegusa** [comment]
修正されていることを確認しましたので、クローズします。

User 権限のユーザーの編集画面
![image](https://cloud.githubusercontent.com/assets/1328499/9288881/f737300c-4397-11e5-8346-3bbfef056183.png)

Librarian 権限のユーザーの編集画面
![image](https://cloud.githubusercontent.com/assets/1328499/9288890/2c8172a4-4398-11e5-98ec-c2e837db1efd.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 b0fc359)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 cf4c00a)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)
