### ISSUE TITLE
アクセス不可の画面へ遷移する「利用者の一覧」の「編集」リンクを非表示にする（librarian権限でログインしたときに、administrator権限のユーザーの利用者「編集」のリンク）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#689]
「利用者の一覧」画面、librarian権限でログイン、

http://dev.next-l.jp/profiles 
![image](https://cloud.githubusercontent.com/assets/1328499/9291281/5ab94daa-43f1-11e5-94ef-ce48aebddbaf.png)

↑の画面で赤四角でかこんだ「編集」リンクをたどると、

![image](https://cloud.githubusercontent.com/assets/1328499/9291293/073eeac6-43f2-11e5-94ec-e5f5c78de3ba.png)

となり、アクセス不可の画面へ遷移する。　（アクセス不可の画面になるのは正しい動きです）

なので、アクセス不可になる「編集」リンク
（ここではadministrator権限のユーザーの編集リンク）については、
始めから「編集」リンクを表示しないようにするのが親切かと思います。

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

（ #647 から派生 ）

**Comment by nabeta** [comment]
修正し、デモサーバに反映済みです。

**Comment by yegusa** [comment]
> 修正し、デモサーバに反映済みです。

開発サーバーだよね？

手元の仮想マシンで、できることを確認しました。　ので、クローズします。
（これは、利用者番号が一桁はadministrator権限のユーザーにしてるので、「編集」リンクがないのが正しい）

![image](https://cloud.githubusercontent.com/assets/1328499/9333953/33e603ae-4607-11e5-814a-cb80e911cea3.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 5a4ea9f)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)
