### ISSUE TITLE
アクセス不可の画面へ遷移する「利用者の一覧」の「表示」リンク等に対する対応

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#690]
librarian権限でログイン、「利用者の一覧」を表示
![image](https://cloud.githubusercontent.com/assets/1328499/9291339/2e4c3f86-43f4-11e5-8fa2-04c25a3969b8.png)

administrator 参照権限　のユーザー（↑の画面の例だと、ユーザー：adminonly）の
「表示」リンクや、「利用者番号」のリンクをたどると
librarianログインユーザーだと、アクセス権限がないので、アクセス不可の画面に遷移します。
（アクセス不可の画面に遷移すること自体はただしい挙動です）

この場合、a)案かb)案にした方が親切かと思います。

a) 「表示」リンクと「利用者番号」のリンクを非表示にする
b) 利用者IDそのものの行を表示させないようにする

（#647 から派生）

**Comment by masao** [comment]
b)はだいたい実装できるのを確認したのですが、Solrインデックスに新しいフィールドを追加する必要があります。そこまですべきか、悩ましいです。。。

**Comment by masao** [comment]
参考までにb)実装を https://gist.github.com/masao/b59908fe87161929e957 に置いておきます。おそらく a) 案で実装したほうがよさそうなので、こちらは捨て置く予想。。。

**Comment by yegusa** [comment]
a) のほうがいいような気がしています。そういうユーザーがいる（存在はわかる）けど、詳細はみれないってのでいいのじゃないかなあと。あと、参照権限がadministrator になっていることはめったにないと思うので、これはまあ、あとまわしでもいいかなあと思っています。

**Comment by masao** [comment]
@nabeta さん、rc20で a) 案で実装されていますが、これ、もう一度議論していただけませんか？
cf. bb4defeead5a3465a67f14e6aec04e53eb6aed71

**Comment by nabeta** [comment]
書誌や所蔵がb案と同様の動作のため、利用者情報もb案にそろえるべきだと思います。

**Comment by masao** [comment]
なんとなくまぎれてしまいましたが、これで rc20 もリリースされていますので、このままの仕様でひとまず修正という形にしてしまいましょう。

**Comment by yegusa** [comment]
開発サーバーで確認したので、クローズします。

admin権限のみが参照できる「adminonly」ユーザーがあるとして、

librarianユーザーが表示しているところ：adminonly ユーザーが検索結果に表れない→OK
http://dev.next-l.jp/profiles?utf8=%E2%9C%93&query=adminonly&commit=%E6%A4%9C%E7%B4%A2

![image](https://cloud.githubusercontent.com/assets/1328499/9830574/ef16afdc-596e-11e5-959a-02e24f6f89ba.png)

admin ユーザーが表示しているところ：adminonlyユーザーが検索結果に表れる→OK
http://dev.next-l.jp/profiles?utf8=%E2%9C%93&query=adminonly&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/9830593/bfc6421e-596f-11e5-888d-adafc50291d0.png)


----
enju_biblio: 0.1.0.pre69
rails_autolink: 1.1.6
enju_message: 0.1.14.pre25
ri_cal: 0.8.8
enju_event: 0.1.17.pre26
geocoder: 1.2.11
enju_library: 0.1.0.pre43
enju_manifestation_viewer: 0.1.0.pre19
enju_leaf: 1.1.0.rc21
enju_circulation: 0.1.0.pre48
enju_flower: 0.1.0.pre23
enju_ndl: 0.1.0.pre37
enju_subject: 0.1.0.pre33
enju_oai: 0.1.0.pre19
