### ISSUE TITLE
シリーズ著者名がシリーズ情報詳細画面に表示されない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#692]
#541 の派生。シリーズ情報詳細画面にも載せておく必要がある。

![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9293296/a5af56be-4460-11e5-90e6-baa0d867b753.png)
1行を追加するだけと思われる。

**Comment by nabeta** [comment]
シリーズ著者名を表示するようにしました。
https://enju.next-l.jp/series_statements/979
![image](https://user-images.githubusercontent.com/11428/71306204-0b47d880-2421-11ea-9b96-14726c451eaa.png)

**Comment by masao** [comment]
表示されていることを確認しました。
