### ISSUE TITLE
件名を削除した際にtranslation missingが表示されました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#693]
いつもお世話になっております。
件名を削除した際にtranslation missingが表示されました。

![next-l_enju_18-08-2015 11 14 48](https://cloud.githubusercontent.com/assets/13130417/9320945/dc842260-459a-11e5-8be6-b50d399581ca.png)

![next-l_enju_18-08-2015 11 14 57](https://cloud.githubusercontent.com/assets/13130417/9320946/de66775e-459a-11e5-99a6-73b8e855e840.png)

以上、ご報告いたします。

**Comment by masao** [comment]
報告ありがとうございます。修正しました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9321335/01435576-45a0-11e5-92eb-150c147f455d.png)

**Comment by yegusa** [comment]
現象確認：
![image](https://cloud.githubusercontent.com/assets/1328499/9323484/2082f48e-45bc-11e5-9c7a-6c9bc919da18.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9323501/3fe8f1f2-45bc-11e5-950a-649810cc6ad9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32)

**Comment by masao** [comment]
enju_subjectモジュールを github 版の1.1ブランチ最新版に差し替えてから、確認いただければと思います。

**Comment by yegusa** [comment]
手元の仮想マシンでできることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9323575/f37e5694-45bc-11e5-81bd-5e42fe29bc09.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9323583/095ee14a-45bd-11e5-9159-741b73afa941.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 88d9341)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)

**Comment by harasugi** [comment]
@masao様
早速のご対応のほど、誠にありがとうございました。

@yegusa様
本来確認は私が行わなければならないにもかかわらず、実は最新ソース適用のやり方を
分かっておらず、代わりに行って頂きまして、いつも大変ありがとうございます。

**Comment by yegusa** [comment]
ちなみに今回は、

$ cd enju
$ vi Gemfile

として、　

 > gem 'enju_subject', '~> 0.1.0.pre29'

この行を以下のように修正して、

> #gem 'enju_subject', '~> 0.1.0.pre29'
> gem 'enju_subject', github: "next-l/enju_subject", branch: "1.1"

保存。

$ bundle update
$ sudo restart enju_leaf

として確かめました。
どこを修正したかによって、enju_subject の部分が、　enju_leaf になったりとありますので、
どれかわからなかったら、ここで聞けばよいかと思います。

あと、確かめたバージョン（？）をわかりやすくするために、私は以下のコマンドの結果も
なるべくつけるようにしています。

 $ bundle list | grep enju

**Comment by harasugi** [comment]
@yegusa 様
修正したソースの適用方法について親切に説明して頂きましてありがとうございます！
これから早速取り組んでみたいと思います。
バージョン表記は大切なことですよね、私も従わせて頂きます。

**Comment by harasugi** [comment]
@masao 様、@yegusa 様
私の環境でも適切に対応されたことを確認しました。
![next-l_enju_19-08-2015 11 17 52](https://cloud.githubusercontent.com/assets/13130417/9347422/25eda48e-4664-11e5-8889-1d644975efe7.png)

確認した環境は次となります。
  * enju_biblio (0.1.0.pre67)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc19)
  * enju_library (0.1.0.pre42)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)

この度はご対応のほど、ありがとうございました。
