### ISSUE TITLE
利用者アカウントをTSVからインポートする際、「作成」と「削除」は成功したのですが、更新(keyword_list)が失敗してしまいました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#695]
お世話になっております。
デモサーバにて確認しましたが、
利用者アカウントをTSVからインポートする際、
「作成」と「削除」は成功したのですが、「更新」が失敗してしまいました。

「更新」失敗時に画面に次の内容が表示されました。

>エラーメッセージ: line 2: wrong number of arguments (2 for 1)

「作成」と「更新」に利用したTSVは次となりますが、
このエラーメッセージには当てはまらないのではないかと思っています。

「作成」時：
create.txt
username	keyword_list
test0	create
test1	create
test2	create

「更新」時：
username	keyword_list
test0	update
test1	update
test2	update

もし他の理由でエラーとなっている場合、ご教示頂けたら嬉しく思います。
毎回お手数をお掛けし申し訳ございませんが、よろしくお願いいたします。

※補足ですが、この機能を利用して学校図書館の進級処理を行おうとしています。テキストファイルによって入学(登録)、クラス替え(更新)および卒業(削除)の処理ができるので大変便利に感じています。

**Comment by masao** [comment]
報告ありがとうございます。さきほど #699 とあわせ、keyword_listの更新ができるようにする修正を加えてみました。ご確認ください。

**Comment by yegusa** [comment]
```
username	 keyword_list
tsv1	english//red
tsv2	education
```

こういファイルでやってみましたが、
更新されませんでした。

![image](https://cloud.githubusercontent.com/assets/1328499/9350762/5f3fb338-468e-11e5-8175-662eea099f7e.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 1e77aee)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)

**Comment by yegusa** [comment]
すみません、ヘッダを書き間違えていました。
できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9353168/64684d44-46a1-11e5-899e-d5bd0c2a628b.png)

 bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 a6de6c2)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)
