### ISSUE TITLE
利用者アカウントのキーワードリストはシステム上どのように扱うのでしょうか？

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#696]
利用者アカウントのキーワードリストはシステム上どのように扱うのでしょうか？
検索に利用できるのではと思い「外国籍」という用語を加えてみましたが、
検索でヒットすることはありませんでした。ただし注記に加えると検索でヒットしました。

それから利用者アカウントの新規作成時にはキーワードリストが表示されず、
編集時に登録をしなければならないようになっていますが、何か意味があるのでしょうか？

お手数をお掛けし申し訳ございませんが、ご教示頂けたら幸いです。
よろしくお願いいたします。

**Comment by harasugi** [comment]
大変申し訳ございません、マニュアルを参照させて頂いたところ、
キーワードリストとは「利用者に対するSDIサービスなどのために登録できるキーワード」であると
記述があり、自己解決いたしました。
この度はお騒がせしてしまい大変申し訳ございませんでした。

**Comment by yegusa** [comment]
キーワードリストですが、ここに登録したからといって、SDIサービスができるようになっていないような気もするのですけどね。。。

マニュアルの分かりにくい位置（結構下のほう）に利用者情報の入力項目についての説明が
あるせいですよね。すみませんでした。マニュアルを修正したいと思います。

**Comment by harasugi** [comment]
@yegusa 様
マニュアルをまとめる作業は相当面倒な作業であるにも関わらず、
対応して頂きましてありがとうございます。

私的に@yegusa様が作成して下さったマニュアルは非常に読みやすく大いに活用させて頂いております！
