### ISSUE TITLE
利用者アカウントの「削除」を行うインポートによって資料を借りている利用者を削除できました。

### ISSUE THREAD

**Issue by harasugi** [next-l/enju_leaf#698]
通常運用では資料を借りている利用者は削除できないのですが、
利用者アカウントの「削除」を行うインポートによって資料を借りている利用者を削除できました。

利用者が削除されても該当の資料の状態は「貸出中」のままです。そして該当の資料の返却処理を
行おうとしてもできませんでした(該当の資料に結びつく利用者がいないためでしょうか)。

以上、ご報告いたします。

**Comment by harasugi** [comment]
それから大変申し訳ございません、デモサーバに本issue内容を試した結果が残ってしまっています。

貸出
http://enju.next-l.jp/checkouts/79

お手数をお掛けし申し訳ございませんが、削除して頂けましたらありがたく思います。
この度はデモサーバで試してしまい、誠に申し訳ございませんでした。

**Comment by yegusa** [comment]
@harasugi さん、デモサーバーはいろいろ触ってみるためにあるので、大丈夫ですよ～。気軽にお使いください！

**Comment by masao** [comment]
一応、貸し出し状態を確認して、未返却資料がある場合は削除しないように修正しました。
削除できなかった旨のエラーは表示しないため、そこは今後の課題としましょう。
たぶん #406 での機能拡張と同様にする必要アリ。

**Comment by yegusa** [comment]
できることを確認しましたので、クローズします。

以下、確認の詳細：

以下の tsv を作成し、TSVインポートで、利用者を「削除」指定してインポート開始すると
```
username
rmtest1
rmtest2
```

rmtest2 は1冊借りている本があるので、削除されていないが、rmtest1は削除された！

![image](https://cloud.githubusercontent.com/assets/1328499/9335650/358f53fa-4610-11e5-9348-7de68b9b6a76.png)

本も借りた状態がちゃんと残っている
![image](https://cloud.githubusercontent.com/assets/1328499/9335723/a8d3d246-4610-11e5-8963-ad703b1b7c39.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 278f9bf)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)
