### ISSUE TITLE
利用者情報の「注記 （note）」の「更新」をTSVインポートでやろうとしたが更新されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#699]
( #695 とも関連があるかもです）

例えば、利用者情報の「注記」を変更しようとして、以下のようなファイルでTSVファイルを作成したとします。

```
username	note
tsv1	2nd
tsv2	2nd
```

利用者のインポートで「更新」を選んで「インポートを開始」とやると
http://localhost:8080/user_import_files/new

![image](https://cloud.githubusercontent.com/assets/1328499/9334660/c8b22668-460a-11e5-9e7e-0d1246a4e17b.png)

「完了」となりますが http://localhost:8080/user_import_files

![image](https://cloud.githubusercontent.com/assets/1328499/9334703/fb3c51d0-460a-11e5-91f7-52613a054f83.png)

以下のように　「注記」は更新されていません。ただしくできていれば、 2nd になっているはずです。

http://localhost:8080/profiles/14/edit
![image](https://cloud.githubusercontent.com/assets/1328499/9334731/25fdc214-460b-11e5-9f27-33047fb9b221.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 5a4ea9f)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)

**Comment by yegusa** [comment]
注記だけではなく、同様も、他のものもためしてみました。
少なくとも、

- password
- full_name
- full_name_transcription
- user_number
- email

はためしてみたけど、注記のときと同様に、
ステータスとしては「完了」となるけれども、更新はされていませんでした。

**Comment by masao** [comment]
さきほど修正を加えました。ユーザ情報の部分の保存ができていませんでした。手元では動くようになったことを確認しました。

**Comment by yegusa** [comment]
とりあえず、「注記」項目のみをこのissueでチェックすることとします。
「注記」が更新されることを確認しました。
一旦クローズします。

https://github.com/next-l/enju_leaf/issues/699#issuecomment-132261225

のファイルでためしたところ、tsv1, tsv2ともに、注記が更新されることを確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/9348169/f36b8d14-466d-11e5-9a99-9d5e4fbd7962.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre67 fd360cc)
  * enju_circulation (0.1.0.pre46)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre22)
  * enju_leaf (1.1.0.rc20 4fc1e97)
  * enju_library (0.1.0.pre42 42800a4)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre24 105a670)
  * enju_ndl (0.1.0.pre37)
  * enju_subject (0.1.0.pre32 f4d7e07)
