### ISSUE TITLE
扱えるバーコードの種類について

### ISSUE THREAD

**Issue by metok999** [next-l/enju_leaf#703]
初めまして。個人所蔵の蔵書整理にenjuの導入を検討している者です。

新しくバーコードラベルを作ることになったのですが、
http://www.asahi-net.or.jp/~ax2s-kmtn/bcodes.html
バーコードにはいろんな規格があるようです。
一般的な図書館ラベルの規格はNW-7というものらしいのですが、

ネットで検索したところ、
「オープンソース統合図書館システム"Next-L Enju"とその機能」というタイトルのPDFファイルに、
「バーコードの規格は，CODE39(CC)モジュラス43に対応」
とあるのを見つけました。

enjuでは特定の規格に準拠しているというようなことはありますでしょうか。
どの規格でバーコードラベルを発注して良いかわからず困っております。
教えていただけると大変助かります。

**Comment by yegusa** [comment]
バーコードリーダーはお使いのPCで使えるものなら
特に指定はありません。
一般的なバーコードリーダーでよいかと思います。

例えば、以下のようなものです。

ビジコム バーコードリーダー 二アレンジCCD USB 白 BC-BR900L-W
http://www.amazon.co.jp/dp/B0089QUG6A/

**Comment by yegusa** [comment]
> enjuでは特定の規格に準拠しているというようなことはありますでしょうか。

特に決まっていませんので、お手持ちのバーコードリーダーがよみこめるバーコードの規格であればなんでもよいかとおもいます。

もちろん、NW-7でもよいです。

**Comment by metok999** [comment]
ありがとうございます！助かりました！
また今後も質問させていただくことがあると思いますが、よろしくお願いいたします。

**Comment by yegusa** [comment]
じゃ、解決ってことでクローズしますね～。
