### ISSUE TITLE
「リポジトリのコンテンツ」ではない資料がOAI-PMHのListRecordsで表示される

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#704]
たとえば、以下の資料は「リポジトリのコンテンツ」にチェックが入っていないにもかかわらず、
http://dev.next-l.jp/manifestations/7100/edit

ListRecordsのレスポンスに含まれている。
http://dev.next-l.jp/manifestations.oai?verb=ListRecords

なお、ListRecordsやListIdentifiersの対象となるかどうかは、Solrのインデックスで制御されている。
https://github.com/next-l/enju_biblio/blob/1.1/app/models/manifestation.rb#L145

**Comment by masao** [comment]
この仕様、必要ですか？

**Comment by masao** [comment]
そもそもNDLサーチ連携を考えると、リポジトリコンテンツだけをハーベスト対象にするかどうかは、単にSetSpecあたりで制御すればよいと思われますが、いかがでしょう。

**Comment by nabeta** [comment]
Setをどこで扱うかで困っています。以前はシリーズ情報で扱おうとしていましたが、複雑になるのでやめました。

**Comment by nabeta** [comment]
仕様変更は別途検討することにして、ひとまず修正しました。
http://dev.next-l.jp/manifestations.oai?verb=ListRecords

**Comment by masao** [comment]
さきほどの提案は、単に repository_contents が true になっている集合だけからなるSetを作ってみてはどうだろうと提案です。
この手のアドホックなSetをいくつも標準で持たせるかどうか、ということですね。
OAI-PMH仕様書を見る限りでは、Setは「図書館」または「本棚」レベルで対応させるのを想定しているようです。Enjuの場合は所蔵が無いとこの前提が効かないので難しいですね。。。

**Comment by masao** [comment]
とりあえず、この修正は元に戻して頂けますか？

**Comment by yegusa** [comment]
@nabeta さん、この修正は、元に戻していただけますか？
私もこの修正は、使い勝手が悪くなるだけだと思います。

> さきほどの提案は、単に repository_contents が true になっている集合だけからなるSetを作ってみてはどうだろうと提案です。

私も、　@masao さんの提案のほうが賛成です。

わざわざアドフォックな（？）「リポジトリのコンテンツ」というチェックがあるのですから
そういうSetをアドフォックに用意してもよいかとおもいますし、
それ以外のアドフォックでないSetは「図書館」または「本棚」レベルで対応するのが
良いかと思います。

そもそも、OAI-PMHは機関リポジトリのためにできたものではなく、
メタデータのハーベスティングのためのプロトコルですから、
多くのメタデータをもっていけるようになっているほうが筋がいいはず。
わざわざ持って行けないようにするほうがおかしいかなあと思います。

**Comment by nabeta** [comment]
これはひとまずこのまま修正させてください。仕様に難があるのはわかりますが、「リポジトリのコンテンツ」にチェックを入れても外してもOAI-PMHの対象になってしまうという、入力フォームの内容に反する現状の動作は、また別の意味で問題だと思います。

**Comment by yegusa** [comment]
> 「リポジトリのコンテンツ」にチェックを入れても外してもOAI-PMHの対象になってしまうという、入力フォームの内容に反する現状の動作は、また別の意味で問題だと思います。

どんな意味で問題でしょうか？
（入力項目あるけど、実質機能ないものなんていっぱいあるじゃん）

また、より問題が大きいという意味では、
OAI-PMHでデータがとれないデータができてしまう、現在の修正後のほうが問題だとおもいます。
修正前の方がまだましです。

OAI-PMHで提供されるメタデータが少なくなる（とれないものがある）問題の方が大きいとおもいます。

例えば、
Setでの実装が難しいというのでしたら、
OAI-PMHで提供するメタデータに一項目増やして「レポジトリのコンテンツ」にチェックがはいっているかどうかわかるようにしてみるという方法はどうでしょうか？

**Comment by yegusa** [comment]
あとは、ベースURLで区別する実装をくわえるのならいいかなあ。Setじゃなくても。

http://dev.next-l.jp/manifestations.ir?verb=ListRecords

というURL　（.ir　）だったら、「リポジトリのコンテンツ」にチェックが入っていないコンテンツは返さない

というふうに、OAI-PMH とはべつのURLにするのはありなきがします。

**Comment by nabeta** [comment]
> どんな意味で問題でしょうか？
> （入力項目あるけど、実質機能ないものなんていっぱいあるじゃん）

公開意図が選択できるように見えてそれが無視されるというのは、一種のセキュリティに関わる問題であり、影響が大きいと考えます。

あるいは、デフォルトで全件を対象にするかわりに、「リポジトリのコンテンツ」のチェックをフォームから削除するというのなら納得できます。いかがでしょうか。

**Comment by masao** [comment]
> あるいは、デフォルトで全件を対象にするかわりに、「リポジトリのコンテンツ」のチェックをフォームから削除するというのなら納得できます。いかがでしょうか。

こちらの実装のほうが納得がいきます。

**Comment by masao** [comment]
> 公開意図が選択できるように見えてそれが無視されるというのは、一種のセキュリティに関わる問題であり、影響が大きいと考えます。

これが公開意図を示すことはどこにも文書化されていません。たぶんそう考えている人はいないと思われます。なぜなら、書誌情報の公開意図は required_role で既に付与されてあり、 repository_content というフラグにも公開意図が内包されていることは明らかでないと思われます。さらに言えば、既にXML形式・JSON形式でのAPIとしては公開されてしまっているので、こちらも repository_content を見ていないのは何故？という話になると思われます。

**Comment by nabeta** [comment]
開発サーバで元に戻しました。
http://dev.next-l.jp/manifestations.oai?verb=ListRecords

フォームからも「リポジトリのコンテンツ」を削除しています。
http://dev.next-l.jp/manifestations/7100/edit

![fireshot capture - - test - next-l enju leaf - http___dev next-l jp_manifestations_7100_edit](https://cloud.githubusercontent.com/assets/11428/9404542/8cf35246-482b-11e5-95dc-833a820104f8.png)

**Comment by masao** [comment]
元に戻っていることを確認しました。クローズします。
