### ISSUE TITLE
書誌編集フォームから「リポジトリのコンテンツ」のチェックをはずす

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#705]
#704 の議論より

書誌編集フォームから「リポジトリのコンテンツ」のチェックをはずす

http://enju.next-l.jp/manifestations/6025/edit
![image](https://cloud.githubusercontent.com/assets/1328499/9404791/4686956e-482d-11e5-9674-7321baecd40b.png)

**Comment by yegusa** [comment]
既に開発済み　( https://github.com/next-l/enju_leaf/issues/704#issuecomment-133332609 )

**Comment by nabeta** [comment]
デモサーバにも反映させました。
http://enju.next-l.jp/manifestations/6025/edit

**Comment by yegusa** [comment]
デモサーバーは元に戻してください。
開発の確認用とには、開発サーバーを使ってください。

**Comment by nabeta** [comment]
開発サーバにスクリーンショットつきで反映済みと書いたのにデモサーバの画面が張ってあったので、こちらも反映をしてほしいのかと思いました。

**Comment by yegusa** [comment]
ああ、そうでしたか。
記録のためにもこのissueを立ち上げたので、記録のためにデモサーバーのスクリーンショット（チェックボックスがまだあるもの）をつけただけだったのです。

**Comment by masao** [comment]
確認しましたのでクローズします。
