### ISSUE TITLE
Administrator参照権限の書誌の詳細画面をLibrarian権限のユーザが閲覧できてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#707]
参照権限のない書誌詳細画面および編集画面を表示できているようです。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9423950/582749a2-4914-11e5-8332-7dcc4843ed7f.png)

```
  * enju_biblio (0.1.0.pre69 d80df87)
  * enju_bookmark (0.1.2.pre22 ca6d1ca)
  * enju_circulation (0.1.0.pre48 d5cb9aa)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 760a6ce)
  * enju_library (0.1.0.pre43 599d085)
  * enju_loc (0.1.0.pre5 34d20fb)
  * enju_manifestation_viewer (0.1.0.pre18)
  * enju_message (0.1.14.pre25 dddbf7d)
  * enju_ndl (0.1.0.pre37 26bfff6)
  * enju_nii (0.1.0.pre13 6811ab3)
  * enju_oai (0.1.0.pre19 fd6717e)
  * enju_purchase_request (0.1.0.pre14 0089532)
  * enju_subject (0.1.0.pre33 34bc87d)
```

**Comment by nabeta** [comment]
デモサーバに反映させました。以下の資料は参照権限をAdministratorにしています。
http://dev.next-l.jp/manifestations/4875

**Comment by yegusa** [comment]
Librarian権限の場合
http://dev.next-l.jp/manifestations/4875
をみにいくと、
http://dev.next-l.jp/ に移ります。

正しい挙動としては、 「403 forbidden」になるはずですよね。

Administrator の場合は、ちゃんとみれています。

![image](https://cloud.githubusercontent.com/assets/1328499/9830002/8b40692c-5959-11e5-805a-9bfeec41b6b0.png)

**Comment by yegusa** [comment]
仮想マシンで確認したのでクローズします。

librarian 権限のユーザー yegusalib でログインして、
administrator 権限でしか表示できないものを表示したときに、
アクセス拒否になりました。

![image](https://cloud.githubusercontent.com/assets/1328499/9830658/eda6080c-5971-11e5-8c1d-37b11a2dd6e1.png)

以下の環境で確認しました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bac371f)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_grid (0.0.1 44ea000)
  * enju_leaf (1.1.0.rc21 760a6ce)
  * enju_library (0.1.0.pre43)
  * enju_manifestation_viewer (0.1.0.pre19 3ca2bf8)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 0ee5429)
  * enju_subject (0.1.0.pre33)
