### ISSUE TITLE
ページ送りができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#709]
書誌一覧画面にて、次ページへ移動する [2] [3] [4] ... [最後] などのリンクをクリックしても、1から10件目までしか表示されない。

**Comment by masao** [comment]
enju_oaiを読み込んでいるときのみ発生している模様。page切り替え変数の衝突によると思われる。

**Comment by masao** [comment]
#594 案件！

**Comment by nakamura-akifumi** [comment]
正しくページ送りが出来ることを確認しました。

![2015-09-12 16 12 04](https://cloud.githubusercontent.com/assets/1065528/9830432/1a32880e-5969-11e5-9ace-9cf5332d408f.png)
