### ISSUE TITLE
OAI-PMHモジュールの仕様変更

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#710]
現状、ベースURLが /manifestations.oai となっているが、Controllerの切り分けが分かりづらくなっているため、別に切り出すこと。

> /oai?verb=Identify
> /oai?verb=ListRecords
> /oai?verb=GetRecord

となるようなURL設計に移行するとよさそう。

**Comment by nabeta** [comment]
「コントローラ名/メソッド名」というルールにしたいので、/oai/provider?verb=Identify というのでもよいでしょうか。

**Comment by masao** [comment]
よいように思います。

**Comment by nabeta** [comment]
OAI-PMH関係の処理をenju_oaiモジュールのoai_controller.rbに移動しました。
開発サーバにも反映済みです。
http://dev.next-l.jp/oai/provider.xml?verb=Identify

**Comment by nabeta** [comment]
現時点ではSetのサポートがなかったり、パラメータの解釈がいい加減（ListRecordsで本来必須のmetadataPrefixをチェックしていない）だったりするので、その点はご注意ください。

**Comment by masao** [comment]
https://junii2-validator.herokuapp.com/?url=http%3A%2F%2Fdev.next-l.jp%2Foai%2Fprovider.xml
http://validator.oaipmh.com/
などでチェックしましたが、問題ないようなのでクローズします。
残っているこまかい問題は別にIssueを立てましたので、そちらで。
