### ISSUE TITLE
書影等の設定フォームの追加

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#711]
rc20において書影等の設定を行う方式が変更になった（DB保存）が、これを編集するフォームがないので、追加すること。

**Comment by yegusa** [comment]
- 複数の書影サイトから選べられるようにしているが、まずは、googleのみ対応とする。
- 優先順位, 1,2,3 位と選べるようにするというアイデアもある。
- amazon は、APIキーを設定ファイルに登録することによってできるようになるかもだが、確認はしていないので、amazon対応は別issueとする。 #715 へ。

ここでは、googleの書影が設定できればOKということにする。

Enju WS で議論ずみ。

**Comment by yegusa** [comment]
現在、 amazon が メニューにはいってしまっているので、いったんはずし、googleだけにしておいてください
→ @nabeta 

![image](https://cloud.githubusercontent.com/assets/1328499/9830808/8ac28750-5977-11e5-8c03-6b6ce98fa65d.png)

**Comment by yegusa** [comment]
仮想マシンで、Google だけになっていることを確認しました。のでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9835292/fae26954-5a1e-11e5-94c7-8161ab4abf4b.png)

確認した環境は以下です。
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bac371f)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_grid (0.0.1 44ea000)
  * enju_leaf (1.1.0.rc21 f291a60)
  * enju_library (0.1.0.pre43 c9a3d72)
  * enju_manifestation_viewer (0.1.0.pre19 3ca2bf8)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 0ee5429)
  * enju_subject (0.1.0.pre33)
