### ISSUE TITLE
書影等の設定方法の文書化

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#712]
#711 からの派生。設定方法が変わったため、マニュアル・更新手順を文書化すること。

**Comment by yegusa** [comment]
前提：以前は、利用者がWebインタフェースで書影をダウンロードしてくるサービスを選択する画面はなかった。

マニュアル文案：

書影をダウンロードしてくるサービスを選択することができます（※現在は、GoogleBooksのみですが、将来的には、amazon.com、紀伊国屋書店等から選べるようにする予定です）

設定方法は、Administrator 権限でログインして、「図書館の管理」の「システムの設定」をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/9835310/0bcaf79e-5a20-11e5-95a0-a28443a0cca0.png)

「図書館全体の設定」をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/9835312/33be0f02-5a20-11e5-8725-8e6e5a3b71b4.png)

「編集」をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/9835316/5a63b8c8-5a20-11e5-90cc-2f282b9b20db.png)

書影をダウンロードしてくるサービス（例：「Google」）を選択（※現在は、GoogleBooksのみですが、将来的には、amazon.com、紀伊国屋書店等から選べるようにする予定です）し、更新をクリックします。
![image](https://cloud.githubusercontent.com/assets/1328499/9835324/bc4e26ea-5a20-11e5-92c2-8846107475eb.png)

**Comment by masao** [comment]
マニュアルとしては、良いのではないでしょうか。
あとは、これまでのバージョンからの設定変更、更新手順を文書化する必要がありますね。

**Comment by yegusa** [comment]
それは、 @nabeta しかわかりませんね。 @nabeta よろしく。

**Comment by yegusa** [comment]
残作業：
これまでのバージョンからの設定変更、更新手順を文書化　→ @nabeta

**Comment by nabeta** [comment]
1. メニューから「システムの設定」→「図書館全体の設定」→「編集」と進みます。
2. 書影の取得元が「Google」となっているのを確認し、「更新する」ボタンを押します。

この変更は、 enju_library-0.1.0.pre44 （現時点では未リリース）から適用されます。

**Comment by masao** [comment]
以前のバージョンの設定ファイルは完全に無視されるようになったのですよね？
更新手順ではその点を明記する必要があると思います。

**Comment by nabeta** [comment]
はい、config/application.ymlは全く使用されなくなりました。

**Comment by yegusa** [comment]
- [ ] wiki のほうは @masao が書く
- [ ] md のマニュアルの方は　@yegusa が書く

**Comment by yegusa** [comment]
https://next-l.github.io/manual/enju_setup_3.html#section3-1-1

「書影の取得元 ：書影を取得するサービス（例：「Google」）を選択します。（※現在は、GoogleBooksの みですが、将来的には、amazon.com、紀伊国屋書店等から選べるようにする予定です）」

と書いてありますので、「md マニュアル」のほうは完了です。

**Comment by masao** [comment]
https://github.com/next-l/enju_leaf/wiki/Update#updating-to-110 に追記しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。
