### ISSUE TITLE
開発サーバーのみ：アクセス不可なページにアクセスしたときにトップページに飛ばされる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#714]
例：

librarian権限のユーザーがログインしたときに、
librarian 権限ではみれないはずの書誌 （例えば： http://dev.next-l.jp/manifestations/4875　）
をアクセスしようとした場合に、
トップページに飛ばされてしまう。

本当なら、以下の画面になるはず：
![image](https://cloud.githubusercontent.com/assets/1328499/9830724/0a1183fc-5974-11e5-89bb-a2c57db8c736.png)

仮想マシンでは、ちゃんとこの画面になるので、開発サーバーのみの現象

**Comment by nabeta** [comment]
blacklightをインストールしたときに権限ルールのファイル app/models/ability.rb が作成されており、これが原因でトップページに遷移するようになっていました。削除すると正しく動作するようになりました。

**Comment by yegusa** [comment]
できることを確認したので、クローズします

![image](https://cloud.githubusercontent.com/assets/1328499/9834812/90286aee-5a07-11e5-98f1-f5e83bed1efb.png)
