### ISSUE TITLE
書影の取得元：版元ドットコム

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#717]
- [ ] 確認
- [ ] マニュアルの修正 #1191 

#713 からの派生。
詳細URL：http://www.hanmoto.com/hanmotocom-webapi

**Comment by masao** [comment]
ひとまず、版元ドットコムの書影を表示できるようにしました。確認願います。
なお、enju_library, enju_manifestation_viewer両モジュールの更新が必要です。
図書館全体の設定から「版元ドットコム」を選択しなおしてから実行してみてください。
![joshi wo kojirasete next l enju leaf](https://cloud.githubusercontent.com/assets/38825/19018703/1435f4e4-88a8-11e6-830e-fc2ab5274889.png)

**Comment by yegusa** [comment]
できることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/19018811/d5732892-88a9-11e6-9971-128546de070d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/19018815/2a52db78-88aa-11e6-96a1-1a0eb8bebd67.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 13bc871)
  * enju_circulation (0.2.0.beta.3 ff25d4a)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 7bbffc5)
  * enju_loc (0.2.0.beta.2 8261f80)
  * enju_manifestation_viewer (0.2.0.beta.3 8b60962)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2 122f967)
  * enju_nii (0.2.0.beta.2 0515196)
  * enju_oai (0.2.0.beta.3 c9faf19)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
