### ISSUE TITLE
利用者情報で「利用不可」のチェックが有効にならない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#718]
利用者情報の編集画面で、「利用不可」のチェックボックスにチェックを入れて保存しても、再度編集画面を開くとチェックが外れている。
http://dev.next-l.jp/profiles/126/edit

**Comment by yegusa** [comment]
なんか、デジャブ―っておもったら、 #485 とおなじですよね？1.1.0.rc17で修正したはずだけど、再発？テスト書いてなかったの？

**Comment by yegusa** [comment]
確かに、ダメですね。

利用者情報の編集画面で「利用不可」を入れて、更新を押そうとしているところ：
![image](https://cloud.githubusercontent.com/assets/1328499/9834793/d6595402-5a06-11e5-95a1-06decbfa375c.png)

その後、編集画面を見たところ：本来は「利用不可」にチェックが入っているはずが入っていない
![image](https://cloud.githubusercontent.com/assets/1328499/9834794/ee4ec614-5a06-11e5-8060-9fb9048a3187.png)

  * enju_biblio (0.1.0.pre69 bac371f)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_grid (0.0.1 44ea000)
  * enju_leaf (1.1.0.rc21 8ff3bc5)
  * enju_library (0.1.0.pre43 344d7a5)
  * enju_manifestation_viewer (0.1.0.pre19 3ca2bf8)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 0ee5429)
  * enju_subject (0.1.0.pre33)

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
#485 のときに、私が確認したバージョン後に開発したものでかつ、rc17のリリースに入れたものに入っていたバグのようですね （ @masao が確認してくれました） 。 例の、strong パラメーターまわりですね。。。

なので、 rc17のリリースバージョンで確かめたら、このバグありました。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre65)
  * enju_circulation (0.1.0.pre42)
  * enju_event (0.1.17.pre24)
  * enju_flower (0.1.0.pre21)
  * enju_leaf (1.1.0.rc17)
  * enju_library (0.1.0.pre40)
  * enju_manifestation_viewer (0.1.0.pre17)
  * enju_message (0.1.14.pre22)
  * enju_ndl (0.1.0.pre35)
  * enju_subject (0.1.0.pre29)

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。

利用不可にチェックを入れて更新とし、編集画面に再度行くとチェックが入っている
![image](https://cloud.githubusercontent.com/assets/1328499/9835280/4790a708-5a1e-11e5-8f2e-83ced3845df2.png)

逆に、チェックを外して、更新として、編集画面に再度行くと、るとチェックが外れているのも
確認しました。

確認した環境は、以下です。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bac371f)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_grid (0.0.1 44ea000)
  * enju_leaf (1.1.0.rc21 f291a60)
  * enju_library (0.1.0.pre43 c9a3d72)
  * enju_manifestation_viewer (0.1.0.pre19 3ca2bf8)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 0ee5429)
  * enju_subject (0.1.0.pre33)

**Comment by nabeta** [comment]
手元の環境、Travis CIともにテストが通っていませんので、reopenします。
https://travis-ci.org/next-l/enju_leaf/builds/80059530

**Comment by masao** [comment]
UserImportFileモデルで不整合が発生していたようですので、修正しました。

**Comment by nabeta** [comment]
テストが通ることを確認しました。
https://travis-ci.org/next-l/enju_leaf/builds/80061918

**Comment by yegusa** [comment]
じゃあ、クローズします。
