### ISSUE TITLE
モジュール結合テストを追加する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#719]
昨日の開発ワークショップでも話しましたが #709 のような種類の特定のモジュール間の依存関係によるバグを判別するため、一部のパターンだけでもテストを追加するとよいように思いました。

gemfiles/rails_4.2_oai.gemfile のようなファイルを追加して、追加モジュール分をテストできるようにしようかと思います（Railsなどとの組み合わせは最新版のみでよいかな、、、と）。

まずは、これまでのバグで発生していた分として以下を追加するとよいかなと思います：

enju_biblio <= enju_oai 追加
enju_ndl    <= enju_nii 追加
enju_ndl    <= enju_loc 追加

Ref. #591 #321

**Comment by masao** [comment]
とりあえず、上記で書いた enju_biblio と enju_ndl には結合テスト分を追加しました。
＃enju_locは先の修正後にリリースされていないので、必ずFailになると思いますが。。。

**Comment by yegusa** [comment]
残作業：
確認の仕方を @masao が @yegusa に教える
@yegusa がチェック

**Comment by yegusa** [comment]
よくわかりませんが、なんかできてるようなので、とりあえずクローズします。

https://travis-ci.org/next-l/enju_biblio/jobs/80826542

![image](https://cloud.githubusercontent.com/assets/1328499/9935405/5f50ab88-5d91-11e5-8b5e-8662c518f9da.png)
