### ISSUE TITLE
NDLサーチ検索インポート時の雑誌書誌対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#72]
高久です。

現在、NDLサーチからの検索インポート時に、雑誌書誌も取り込むことができますが、これについては、雑誌書誌として扱われていないようなので、雑誌扱いとして取り込むようにしたほうがよいように思います。

どうぞよろしくお願いします。

**Comment by masao** [comment]
本機能はおおむね1年前くらいに実装は終わっていますので、いったんクローズしましょうか。

**Comment by yegusa** [comment]
残作業：
チェックのみ

**Comment by yegusa** [comment]
雑誌の書誌の場合、雑誌としてインポートされることを確認しました。
一旦クローズします。


（ここでは情報知識学会誌のJP番号で検索）
![image](https://cloud.githubusercontent.com/assets/1328499/9954453/2a7693c6-5e24-11e5-8591-a1e460b4b9e7.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9954472/48fe67ec-5e24-11e5-9275-906a6e472ec6.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26 29feafd)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 18977d2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
