### ISSUE TITLE
書影がない場合の「緑色の？」を「no image」 画像に変える

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#720]
@ineku さんが no image 画像を作成してくれたので、差し替える。

（@nabeta さんがno image画像のファイルを持っている。）

**Comment by yegusa** [comment]
残作業
* [ ] @nabeta が画像の差し替えをやる
* [ ] だれかが確認する

**Comment by nabeta** [comment]
画像の差し替えを行いました。
http://dev.next-l.jp/manifestations/7100

**Comment by yegusa** [comment]
手元の仮想マシンでためしましたが、緑の?のままでした。
仮想マシンで確認するのはどうやればいいですか？

![image](https://cloud.githubusercontent.com/assets/1328499/10039174/5b4af4d0-620a-11e5-9765-152af596cc6c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 666e6eb)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by nabeta** [comment]
すみません、ひと手順必要です。以下のコマンドを実行したあと、Webサーバを再起動してください。

```sh
$ bundle exec rake assets:precompile
```

**Comment by yegusa** [comment]
手元の仮想マシンで、できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10045201/c27a84d2-623b-11e5-8221-cea174624e08.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 666e6eb)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
