### ISSUE TITLE
催し物情報の新規作成時に時刻表示がされない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#722]
催し物情報を新規作成した際に、時刻指定（たとえば 16:00-17:00 など）したにもかかわらず、作成完了画面に表示されない。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/9837709/35872252-5a83-11e5-99fa-cfb605359b81.png)

**Comment by yegusa** [comment]
仮想マシンで、できることを確認しましたので、クローズします。

作った直後：
![image](https://cloud.githubusercontent.com/assets/1328499/9868694/071d0348-5bb7-11e5-8aa4-7bfc23c0423c.png)

後から表示：
![image](https://cloud.githubusercontent.com/assets/1328499/9868710/27f4391a-5bb7-11e5-82dd-7bda7304a55b.png)

確認した環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 986851d)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26 29feafd)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
