### ISSUE TITLE
催し物情報の編集画面の日付表示がわかりづらい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#723]
催し物の開始/終了時刻の日付表示のフィールドが年月日の区別がないため、入力しづらい。
![next l enju leaf_edit](https://cloud.githubusercontent.com/assets/38825/9837754/78f1843c-5a84-11e5-8a21-c2d303fa9c72.png)

**Comment by nabeta** [comment]
年月日を文字で入れるのとは別に、Datepickerにしようかなとも思ったのですが、いかがでしょう？
https://jqueryui.com/datepicker/

**Comment by masao** [comment]
ありがとうございます。確かにそのあたりにしてみてもよいかもしれませんね。ローカライズしたりカレンダー入力のUIへの遷移が直感的になるかどうか、ちょっと工夫の必要はありそうですが。。。

**Comment by yegusa** [comment]
Datepickerは良いと思いますが、それは、別issueにして
（いろいろ検討することいりそうだし）、

1.1.0では

[2015▼]年　[10▼] 月 [ 02▼] 日 

でいいと思います。

**Comment by yegusa** [comment]
@nabeta , @masao とも話しましたが、

> 1.1.0では
>  [2015▼]年　[10▼] 月 [ 02▼] 日

としましょうとなりました。　

残作業：
*  「[2015▼]年　[10▼] 月 [ 02▼] 日」　と開発　→ @nabeta @masao 
* ↑の開発の確認

**Comment by yegusa** [comment]
なんか開発面倒そうなのね？

統計のところでも似たようなのがあるから、
とりあえず、1.1.0では、統計のに揃えるってのにしよう！ と　@masao と話し合いました。

つまり：「[2015▼]　[10月▼]  [ 02▼] 」　とすればよいかと。

例： http://enju.next-l.jp/manifestation_reserve_stats/new
![image](https://cloud.githubusercontent.com/assets/1328499/9937319/2ed4f630-5d9b-11e5-8daa-eb5fc19949a3.png)

**Comment by masao** [comment]
修正しました。
なお、上記で開発が面倒というのは、 datetime_select が十分な国際化表示に対応していないことにより、初期の修正希望を満たす実装を一から開発する必要がありそうであることによります。
日本語対応だけでよければ：  http://github.com/elm200/date_helper_ja があり。

**Comment by yegusa** [comment]
仮想マシンで、確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9979212/d6df308c-5f9b-11e5-98f7-9579287054b5.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 62a1628)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by yegusa** [comment]
マニュアルのスクリーンショットも更新しなきゃですね。
