### ISSUE TITLE
「メッセージに返信する」リンクをクリックしたら、アクセスが拒否（User→Administratorへのメッセージ返信）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#724]
一般利用者ユーザが、administrator 権限ユーザーにメッセージを返信しようと「メッセージに返信する」リンクをクリックしたら、アクセスが拒否されましたとなりました。

![image_initial_011](https://cloud.githubusercontent.com/assets/1328499/9840077/8322a7a0-5ac6-11e5-91fa-f2500de6590e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9840062/2365511e-5ac6-11e5-8fd4-451957de214b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7b5fb10)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 40fc6a9)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by yegusa** [comment]
a) 一般利用者からメッセージを返信するのは想定していない
b)  一般利用者からメッセージを返信するのは想定している

a)  or b) どちらでしょうか？ →　@nabeta

必要な作業：
a) の場合→「メッセージを返信する」のリンクを消す、マニュアルを修正する
b) の場合→「メッセージを返信する」のリンク先に行けるようにする

**Comment by masao** [comment]
なんとなく、a) な気がします。。。そもそもユーザ権限のアカウントは普通、相手のユーザ情報（閲覧権限がLibrarian以上）は見れないわけですから、メッセージは送れないと思うのが普通ですよね。どんなユーザがいるか、相手が自分が想定している送信先か分からない状態なのにメッセージをやり取りはできないはずので…。

もしも a) だった場合、「メッセージ」という双方向を含意している言葉で表現するのは混乱するので、「通知」とかそういう言葉で表現するように変更してしまったほうが良い気がします。

**Comment by yegusa** [comment]
> 「メッセージ」という双方向を含意している言葉

ってわけでもないかとおもうし、
メッセージという言葉を使わないのなら、
結構いろいろいじらないとだめだから（マニュアル含めて）、
 a) だとしても、1.1.0では「メッセージ」という文言のままでいいかと思います。

**Comment by nabeta** [comment]
> a) or b) どちらでしょうか？ →　@nabeta

aです。「メッセージを返信する」のリンクは削除します。

**Comment by yegusa** [comment]
残作業：
「メッセージを返信する」のリンクを消す→ @nabeta か　@masao よろしく
マニュアルを修正する　→　@yegusa

**Comment by masao** [comment]
修正しました。
ついでに、削除リンクが表示されていなかった問題も修正してあります。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9979246/858a07fa-5f9d-11e5-97b6-baf9cd8a355b.png)

agrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 62a1628)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
