### ISSUE TITLE
マニュアルの修正（再整備） for 1.1.0

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#725]
1.1.0リリースに向けて、良い機会ですので、マニュアルを再度閲読し、修正・追記すべき箇所のチェックを行ったほうが良いと思います。そこで以下にチェックリストを用意しますので、各自担当箇所を割り当てたりしながら、一通り見直してみるとよいかと思います。
＃修正・追記箇所があれば、直接に修正するなり、Issue登録するなりしてください。

http://next-l.github.io/manual/

* インストールマニュアル
  - [x] 第1章 Enju概要
  - [x] 第2章 Enjuを動作させる方法
  - [x] 第3章 動作環境の確認とVirtualBoxのインストール
  - [x] 第4章 Enjuのインストール
  - [x] 第5章 モジュールの追加
  - [x] 第6章 他のコンピュータからの利用設定
  - [x] 第7章 Enjuのアップデート
  - [x] 第8章 データのバックアップ
  - [x] 第9章 その他
  - [x] 第10章 トラブルシューティング
* 初期設定マニュアル
  - [x] 第1章 Enju概要
  - [x] 第2章 Enjuを利用する
  - [x] 第3章 図書館のシステム設定を行う
  - [x] 第4章 件名のシステム設定を行う
  - [x] 第5章 各種形態や状態等に関するシステム設定を行う
  - [x] 第6章 資料に関するシステム設定を行う
  - [x] 第7章 その他
* 運用マニュアル
 - [x] 第1章 Enju概要
 - [x] 第2章 Enjuを利用する
 - [ ] 第3章 利用者情報を管理する
 - [ ] 第4章 図書の受入をする　（4章冒頭の部分の修正も忘れずに）
 - [ ] 4-1 図書を発注する
 - [ ] 4-1-1 発注リストを作成する
 - [ ] 4-1-2 発注したい図書（購入リクエスト）を発注リストに登録する
 - [ ] 4-1-3 発注リストを印刷する
 - [ ] 4-2 図書を登録する
 - [x] 4-2-1 TSVファイルを読み込んで登録する
 - [x] 4-2-2 ISBNファイルを読み込んで登録する
 - [x] 4-2-3 ISBNコードを入力して1件ずつ登録する
 - [x] 4-2-4 NDLサーチを検索して1件ずつ登録する
 - [x] 4-2-5 米国議会図書館を検索して1件ずつ登録する
 - [x] 4-2-6 CiNii Booksを検索して1件ずつ登録する
 - [x] 4-2-7 手動で資料を登録する
 - [x] 4-2-8 図書の書誌を編集（修正）する
 - [ ] 4-2-9 TSVファイルの作り方（図書（書誌））
 - [ ] 4-3 所蔵情報を登録・一覧表示する
 - [ ] 4-3-1 所蔵情報を新規登録する
 - [ ] 4-3-2 すでに登録された所蔵情報を修正登録する （キーワードでなく、バーコードで検索とすること）
 - [ ] 4-3-3 所蔵情報を一覧表示する
 - [ ] 4-3-4 TSVファイルを読み込んで登録する
 - [ ] 4-3-5 TSVファイルを読み込んで更新する
 - [ ] 4-3-6 TSVファイルを読み込んで所蔵情報を他の書誌につけかえる
 - [ ] 4-3-7 TSVファイルを読み込んで削除する
 - [ ] 4-3-8 TSVファイルの作り方（所蔵情報）
 - [ ] 4-4 図書を検収する　 #867 #868 待ち
 - [x] 4-5 図書を除籍する
 - [ ] 4-6new 図書を製本する （追記したら、以降の節番号をずらす）
 - [x] 4-6 新着資料の一覧を表示する
 - [x] 4-7 画像を登録する
 - [x] 4-7-1 画像の登録
 - [x] 4-7-2 画像の一覧表示
 - [x] 4-8 書誌と所蔵のエクスポートをする
 - [x] 4-9 人物・団体情報を登録する
 - [x] 4-9-1 設定項目
 - [x] 4-9-2 設定方法
 - [ ] 第5章 雑誌の受入をする
 - [ ] 第6章 貸出・返却・予約を処理する
 - [ ] 第7章 休館日と催し物を登録する
 - [ ] 第8章 レファレンスを処理する
 - [ ] 第9章 資料を検索する
 - [ ] 第10章 蔵書点検機能を利用する
 - [ ] 第11章 統計機能を利用する
 - [x] 第12章 印刷その他の機能を利用する
* 利用者マニュアル
 - [x] 第1章 資料を検索する
 - [x] 第2章 ログイン/ログアウトする
 - [x] 第3章 パスワード/ユーザアカウント情報を変更する
 - [x] 第4章 資料を予約する
 - [x] 第5章 資料の貸出状況を確認する/貸出延長をする
 - [x] 第6章 新着資料を一覧する
 - [x] 第7章 メッセージを受信する
* Web APIマニュアル
 - [ ] 第1章 検索結果一覧を取得する
 - [ ] 1-1 TSV
 - [ ] 1-2 RDF
 - [ ] 1-3 RSS
 - [ ] 第2章 検索詳細を取得する
 - [ ] 2-1 TSV
 - [ ] 2-2 RDF
 - [ ] 2-3 RSS
 - [ ] 第3章 OpenSearch 
 - [ ] 第4章 OAI-PMH
 - [ ] 第5章  SRU

**Comment by yegusa** [comment]
提供しているWeb API （OAI-PMH含む）を説明する章がいりますね。

**Comment by yegusa** [comment]
「利用マニュアル」もしくは「利用者マニュアル」　という、一般ユーザーやログインしないユーザーむけのマニュアルがあってもいいかも。

**Comment by yegusa** [comment]
運用マニュアル12章は実質意味のないものだったので
（実装していない背ラベルとバーコード印刷、実装がびみょうなbookmark機能について）、
とりあえず、一旦、リンクを切りました。

**Comment by yegusa** [comment]
インストールマニュアルの「 第4章 Enjuのインストール」は
「1.1.0.rc7以前についてのコラムをできれば別ぺーじにしたい」のだけど、
まあ、最悪されてなくてもいいかなとおもうので、
そこは、未修整です。

**Comment by yegusa** [comment]
積み残し分 は 1.1.1 でやる #891 ことにして、いったんクローズします　by Enju WS 2015-11-15 の議論より。 
（どこまで済んでいたかの記録のため残しておきます）

**Comment by yegusa** [comment]
#975
