### ISSUE TITLE
マニュアルをバージョニングしたい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#726]
Enjuのマニュアルは現行1.1系の最新を基準としたひとつだけしか提供されていませんが、今後の 1.2 系の開発を考えるとあまりよいこととは思えないので、少し検討を要すると思います。

まずは大きくメジャーバージョン単位での情報をどのように記載しわけるか？

* a案) バージョンごとにディレクトリを切り分ける
  * http://next-l.github.com/manual/1.1/ （1.1系または最新stable?）
  * http://next-l.github.com/manual/1.2/ （1.2系）
  * http://next-l.github.com/manual/2.0/ （2.0系?）

* b案) もう一つ上のディレクトリ単位で切り分け
  * http://next-l.github.com/manual11/ （1.1系または最新stable?）
  * http://next-l.github.com/manual12/ （1.2系）
  * http://next-l.github.com/manual20/ （2.0系?）

いずれにしても、現行URLは、その時点の最新stableへのリダイレクトにでもすればよいかな、、、と。

実際の移行は 1.1.0 リリース後でもよいと思いますが、議論のたたき台にでもご検討ください。

**Comment by yegusa** [comment]
a案 でいいと思います。そろそろ1.2系のマニュアルを書きたいので、決めちゃってしまいましょう。

**Comment by scivola** [comment]
a案にもう一票。
マニュアル全体をつまむためのディレクトリーがないと何かと不便では。

**Comment by masao** [comment]
ひとまず a案にて 1.1 と 1.2 のバージョンを切り分けるよう、ディレクトリを追加しました。

**Comment by scivola** [comment]
マニュアルの全ページに，それがどのバージョンのものなのか書く必要があると思います。
検索エンジンから来る人もいるでしょうし。

最も単純な修正案として，ヘッダーの
「Documentation for Next-L Enju」
を
「Documentation for Next-L Enju 1.2」
のようにするのはどうでしょうか。

**Comment by masao** [comment]
@scivola さん、ありがとうございます。ご提案のとおり、ヘッダー内にバージョンを入れてみました。

**Comment by yegusa** [comment]
分かりやすくなったと思います。

https://next-l.github.io/manual/1.2/enju_operation_4.html
![image](https://cloud.githubusercontent.com/assets/1328499/12050692/40c4800c-af3c-11e5-944c-f33d1d52fb5d.png)

**Comment by yegusa** [comment]
これ、できましたよね。ひとまずクローズします。
