### ISSUE TITLE
図書館の地図が表示されません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#727]
- [x] マニュアル #1066 （修正必要なし）

![image](https://cloud.githubusercontent.com/assets/1328499/9844186/246cbabc-5afc-11e5-9454-bd8b29807aba.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7b5fb10)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 8acf4bc)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

ちなみに、デモサーバーや開発サーバーでは地図が表示されていることを確認ずみです。

http://enju.next-l.jp/libraries/kiri
![image](https://cloud.githubusercontent.com/assets/1328499/9844225/752b6af2-5afc-11e5-9cd3-aba5234bf311.png)

**Comment by yegusa** [comment]
http://localhost:8080/libraries/kiri
![image](https://cloud.githubusercontent.com/assets/1328499/9844315/1ba8c230-5afd-11e5-8cb0-db2a2ebbd9e6.png)

を表示したときのログ

<pre>
vagrant@vagrant-ubuntu-trusty-64:~/enju$ diff /tmp/log1.txt /tmp/log2.txt
33903a33904,33972
> I, [2015-09-14T07:21:43.143100 #1647]  INFO -- : Started GET "/libraries/kiri" for 127.0.0.1 at 2015-09-14 07:21:43 +0000
> I, [2015-09-14T07:21:43.146823 #1647]  INFO -- : Processing by LibrariesController#show as HTML
> I, [2015-09-14T07:21:43.147212 #1647]  INFO -- :   Parameters: {"id"=>"kiri"}
> D, [2015-09-14T07:21:43.151320 #1647] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
> D, [2015-09-14T07:21:43.154302 #1647] DEBUG -- :   LibraryGroup Load (0.4ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.156104 #1647] DEBUG -- : Cache read: available_languages
> D, [2015-09-14T07:21:43.157274 #1647] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-09-14T07:21:43.180991 #1647] DEBUG -- :   Library Load (0.5ms)  SELECT  "libraries".* FROM "libraries" WHERE "libraries"."name" = ?  ORDER BY libraries.position LIMIT 1  [["name", "kiri"]]
> D, [2015-09-14T07:21:43.188547 #1647] DEBUG -- :   Role Load (0.6ms)  SELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ? LIMIT 1  [["user_id", 2]]
> D, [2015-09-14T07:21:43.191146 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.192504 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.193722 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.195168 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.196520 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.201468 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.207638 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.209519 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.253943 #1647] DEBUG -- :   SOLR Request (26.8ms)  [ path=select parameters={fq: ["type:Event", "library_id_i:3"], sort: "start_at_d desc", start: 0, rows: 10, q: "*:*"} ]
> D, [2015-09-14T07:21:43.270952 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.272896 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.280389 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.287658 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.289397 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.335706 #1647] DEBUG -- :   Profile Exists (0.4ms)  SELECT  1 AS one FROM "profiles" INNER JOIN "users" ON "users"."id" = "profiles"."user_id" INNER JOIN "user_has_roles" ON "user_has_roles"."user_id" = "users"."id" INNER JOIN "roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "profiles"."library_id" = ? AND (roles.name = 'Administrator' OR roles.name = 'Librarian') LIMIT 1  [["library_id", 3]]
> D, [2015-09-14T07:21:43.346057 #1647] DEBUG -- :   Shelf Load (0.6ms)  SELECT "shelves".* FROM "shelves" WHERE "shelves"."library_id" = ?  [["library_id", 3]]
> D, [2015-09-14T07:21:43.355913 #1647] DEBUG -- :   PictureFile Load (0.6ms)  SELECT "picture_files".* FROM "picture_files" WHERE "picture_files"."picture_attachable_id" = ? AND "picture_files"."picture_attachable_type" = ?  ORDER BY picture_files.position  [["picture_attachable_id", 3], ["picture_attachable_type", "Shelf"]]
> I, [2015-09-14T07:21:43.362391 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_library-b78b6e23ef33/app/views/libraries/_calendar.html.erb (2.9ms)
> D, [2015-09-14T07:21:43.365313 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.367990 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.372312 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.375716 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.378051 #1647] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.399978 #1647] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.402306 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.405879 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.410025 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.412400 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.442037 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.443830 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.447402 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.449856 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.451401 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.495528 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.497424 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.501592 #1647] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.504949 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.507063 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> I, [2015-09-14T07:21:43.557460 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_library-b78b6e23ef33/app/views/libraries/show.html.erb within layouts/application (300.1ms)
> D, [2015-09-14T07:21:43.564931 #1647] DEBUG -- :   Color Load (0.5ms)  SELECT "colors".* FROM "colors" WHERE "colors"."library_group_id" = ?  [["library_group_id", 1]]
> I, [2015-09-14T07:21:43.566979 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-8acf4bc2cf24/app/views/page/_include.html.erb (8.5ms)
> D, [2015-09-14T07:21:43.568792 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> I, [2015-09-14T07:21:43.571550 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_manifestation_viewer-ca2952302b4e/app/views/manifestations/_google_book_thumbnail_header.html.erb (0.4ms)
> D, [2015-09-14T07:21:43.573970 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.577266 #1647] DEBUG -- :   CACHE (0.2ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.605496 #1647] DEBUG -- :   SOLR Request (22.5ms)  [ path=select parameters={fq: ["type:Message", "receiver_id_i:2", "is_read_b:false"], start: 0, rows: 30, q: "*:*"} ]
> D, [2015-09-14T07:21:43.632383 #1647] DEBUG -- :   SOLR Request (23.5ms)  [ path=select parameters={fq: ["type:Message", "receiver_id_i:2", "is_read_b:false"], start: 0, rows: 30, q: "*:*"} ]
> D, [2015-09-14T07:21:43.639221 #1647] DEBUG -- :   Language Load (1.0ms)  SELECT "languages"."id", "languages"."iso_639_1", "languages"."name", "languages"."native_name", "languages"."display_name", "languages"."position" FROM "languages" WHERE "languages"."iso_639_1" IN ('en', 'ja')  ORDER BY languages.position
> I, [2015-09-14T07:21:43.642610 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-8acf4bc2cf24/app/views/page/_select_locale.html.erb (6.0ms)
> I, [2015-09-14T07:21:43.643993 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-8acf4bc2cf24/app/views/page/_header.html.erb (70.6ms)
> D, [2015-09-14T07:21:43.661223 #1647] DEBUG -- :    (0.5ms)  SELECT COUNT(*) FROM "libraries" WHERE "libraries"."library_group_id" = ? AND (id != 1)  [["library_group_id", 1]]
> D, [2015-09-14T07:21:43.665749 #1647] DEBUG -- :   Library Load (0.4ms)  SELECT "libraries".* FROM "libraries" WHERE "libraries"."library_group_id" = ? AND (id != 1)  ORDER BY libraries.position  [["library_group_id", 1]]
> D, [2015-09-14T07:21:43.671818 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.674580 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.680009 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.682751 #1647] DEBUG -- :   CACHE (0.0ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-14T07:21:43.684760 #1647] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> I, [2015-09-14T07:21:43.745978 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-8acf4bc2cf24/app/views/page/_menu.html.erb (101.1ms)
> I, [2015-09-14T07:21:43.748885 #1647]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/gems/enju_flower-0.1.0.pre23/app/views/page/_footer.html.erb (1.9ms)
> I, [2015-09-14T07:21:43.750097 #1647]  INFO -- : Completed 200 OK in 603ms (Views: 440.6ms | ActiveRecord: 9.6ms | Solr: 72.8ms)
vagrant@vagrant-ubuntu-trusty-64:~/enju$

</pre>

**Comment by yegusa** [comment]
普通のプロキシを使わない環境でも地図がでなかったので、別の原因かと思われ。

**Comment by yegusa** [comment]
すみません、いろいろつついてたら表示されるようになりました。そして、この表示されないようになる再現条件がわからない。。。

**Comment by yegusa** [comment]
それほど問題にならなそうだし、とりあえず、1.1.0じゃなくて後にまわしましょう。

**Comment by nabeta** [comment]
プロキシ環境下で地図が表示されない現象を確認しました。設定ファイルの変更が必要です。
まず、以下のコマンドで設定ファイルを作成します。config/initializers/geocoder.rb というファイルが作成されます。

```sh
$ rails g geocoder:config
```

次に、 config/initializers/geocoder.rb を編集します。

```ruby
Geocoder.configure(
  # 以下の3行を追加
  lookup: :google,
  use_https: true,
  https_proxy: 'proxy.example.jp:3128' # プロキシサーバのホスト名とポート名を指定。"http://"を含めないこと
  # 中略
)
```

編集が終わったら、Webサーバを再起動します。
次に、図書館のページを開いて「編集」を選び、いったん住所を空にして保存します。
http://dev.next-l.jp/libraries/2

再度「編集」を選び、住所を入力して保存します。これで地図が表示されるはずです。

**Comment by nabeta** [comment]
設定ファイルはインストールスクリプトの中で作成するのがよさそうですね。

**Comment by yegusa** [comment]
あれ？そうなの？プロキシ環境でもできたような。。。とりあえず、私のほうでももういちど、プロキシ環境でみてみます。

**Comment by nabeta** [comment]
正確にいうと、librariesテーブルにlatitudeとlongitudeカラムがあり、この両カラムに値が入っていると、プロキシ環境下かどうかにかかわらず、地図が表示されます。
プロキシが関係するのは更新時です。この両カラムの値は、住所に変更があるとgeocoder gem（が呼び出すGoogle MapsのWebAPI）を用いて自動的に更新されますが、プロキシ環境下でプロキシの設定をしていないと両カラムの更新が失敗します（エラーにはなりません）。なお、このgemは環境変数http_proxyは参照しないようです。

インストール時の初期状態では、latitudeとlongitudeは空となっています。つまり、初期設定では地図は表示されず、自分で住所を入力してはじめて地図が表示されるようになります。

**Comment by nabeta** [comment]
インストールスクリプトで rails g geocoder:config を実行するようにしました。1.1.2と1.2.0の両方で作業済みです。1.1.1以前からのアップデートする場合は手動でこのコマンドを実行してください。

**Comment by yegusa** [comment]
わたしはプロキシ環境じゃなくなったので確認のしようがありません。
どなたかできるひと確かめてくれるとありがたいです。

**Comment by nabeta** [comment]
職場のプロキシ環境では表示できているので、ひとまずcloseします。
