### ISSUE TITLE
「資料の表示」で請求記号ラベルが表示される条件がわからない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#728]
-ログインしている
-図書館に請求記号ルールが設定されている
-当該資料の所蔵が登録されている
-当該資料の「請求記号」がルール通りに入力されている
-<s>当該資料の所蔵情報IDが入力されている</s>
-当該資料の所蔵のステータスが「作業中」でない（「在架（利用可能）」「貸出中」他にもある？）
-ログインしているユーザーの所属図書館のもののみ表示する（例：所属図書館Your library　だったらYour libraryのもののみ）

あたりが条件でしょうか？
私の認識はあっているでしょうか？
他に必要な条件はありますでしょうか？

----
参考：スクリーンショット

図書館に請求記号ルールが設定されている
![image](https://cloud.githubusercontent.com/assets/1328499/9844733/bea1373a-5b00-11e5-908f-1713e4bdd821.png)

ログインしているユーザーの所属図書館のもののみ表示する（例：所属図書館Your library）
![image](https://cloud.githubusercontent.com/assets/1328499/9844719/a7105178-5b00-11e5-8f33-1d85a711e607.png)

ログインしている、所蔵情報IDが入力されている、請求記号が入力されている、「在荷（利用可能）」
![image](https://cloud.githubusercontent.com/assets/1328499/9845364/431571f8-5b05-11e5-9763-034895daca68.png)

**Comment by nabeta** [comment]
所蔵情報IDはなくても表示されるはずです。

**Comment by yegusa** [comment]
所蔵情報IDがなかった場合は表示されないですけど？

じゃあ、所蔵情報IDがなかった場合は表示されないのは、バグなんですね？→ @nabeta

http://enju.next-l.jp/manifestations/6040
![image](https://cloud.githubusercontent.com/assets/1328499/9852664/70befa18-5b3a-11e5-9022-7ab8c5daff83.png)

**Comment by yegusa** [comment]
@nabeta に聞きました。

> じゃあ、所蔵情報IDがなかった場合に表示されないのは、バグなんですね？→ @nabeta

バグなんだそうです。

**Comment by yegusa** [comment]
バグの方は別 issue #735 にしました。
いったん、このisseuはクローズします。

**Comment by masao** [comment]
うーん、これ直そうかとおもってコードを読んでいるのですが、 item.for_checkout というスコープを使っているのですが、この条件には所蔵IDが入力されていることは条件になっているのですが。。。

https://github.com/next-l/enju_flower/blob/1.1/app/views/manifestations/show.html.erb#L37
https://github.com/next-l/enju_circulation/blob/1.1/lib/enju_circulation/item.rb#L30

昔から、所蔵IDが必要という仕様だったのではないでしょうか？

**Comment by yegusa** [comment]
ま、所蔵IDがあろうがなかろうが背ラベルは表示するって仕様に変えるってことでよいと思います。ので、 #735 のほうで、修正してください。
