### ISSUE TITLE
本棚の設定で「閉架」にチェックいれるとどうなるんですか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#729]

**Comment by nabeta** [comment]
現時点では本棚の一覧表示で「閉架」と表示されるだけです。貸出などには影響しません。

**Comment by yegusa** [comment]
何かの準備作業でしょうか？なぜ、このチェックをつけることにしたか教えてもらえるとうれしいです。

本棚の一覧表示で「閉架」と表示されるところ：
http://enju.next-l.jp/shelves
![image](https://cloud.githubusercontent.com/assets/1328499/9864962/5bdb3d32-5b8a-11e5-944e-b83fdf17d591.png)

**Comment by yegusa** [comment]
ま、いいや、ドキュメントにも書いたのでいったんクローズします。
