### ISSUE TITLE
書誌所蔵情報エクスポートにはヘッダ行が必要

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#730]
最新版の書誌所蔵情報のエクスポート機能にはヘッダ行がついてきませんが、どの列がどの項目なのか分からないので、利用のしようがないと思います。

**Comment by nabeta** [comment]
ひとまず開発サーバではヘッダを表示するようにしました。
http://dev.next-l.jp/resource_export_files/63

**Comment by yegusa** [comment]
残作業：確認のみ

**Comment by yegusa** [comment]
仮想環境でエクスポートを試してみましたが、「失敗」になりました。

![image](https://cloud.githubusercontent.com/assets/1328499/9923385/5bb3d8f4-5d2f-11e5-9c1f-1a4cdf729599.png)


以下、環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 986851d)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26 29feafd)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 b78b6e2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by masao** [comment]
詳細画面にエラーメッセージなど残っていませんか？

**Comment by yegusa** [comment]
詳細画面ってこれですよね？特にみあたらないですね。

![image](https://cloud.githubusercontent.com/assets/1328499/9925061/561ea4ac-5d41-11e5-8a42-1b827c050f9e.png)

**Comment by yegusa** [comment]
Resque の方のエラー
![image](https://cloud.githubusercontent.com/assets/1328499/9933537/6ff80a86-5d86-11e5-9246-57d7c7bd7125.png)

**Comment by yegusa** [comment]
詳細があったのでそれもつけときます

![image](https://cloud.githubusercontent.com/assets/1328499/9933656/4df0e97a-5d87-11e5-8486-84f8407bca95.png)

**Comment by masao** [comment]
修正を加えました。確認願います。

**Comment by yegusa** [comment]
仮想マシンでできることを確認しました。ので、クローズします。

ヘッダがあるかどうかをチェックするテストもつくってくれたのですね！さすがです。

![image](https://cloud.githubusercontent.com/assets/1328499/9934780/55839776-5d8e-11e5-962a-83c93a5a1b1c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/9934811/87209aa4-5d8e-11e5-8df0-c339680581fc.png)

チェックした環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26 29feafd)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 18977d2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
