### ISSUE TITLE
図書館詳細情報の表示でRailsエラーを発生

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#732]
#727 の調査中に発見したバグ。住所項目内の文字列がタブ文字を最初に含むと、詳細画面表示時にエラーが発生。
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/9853642/98b19b16-5b3f-11e5-823b-c43d7e55be82.png)

**Comment by yegusa** [comment]
残作業：
* [ ] 原因調査
* [ ] バグ修正
* [ ] 確認

**Comment by masao** [comment]
原因は確認しました。住所項目はいわっゆる Yaml 形式で言語ごとの表示切替できるようになるため、それを変換ライブラリに渡すようです。

たとえば、以下のような入力を期待しているようです：
```
ja: 茨城県つくば市
en: Tsukuba, Ibaraki
```

そのため、Yaml形式として不正になる文字列が来ると、全体がエラーで落ちるようです。
※少なくともエラーで落ちないようにする必要はありそうです。

**Comment by masao** [comment]
とりあえず、エラーにならないように修正しました。

**Comment by yegusa** [comment]
住所の冒頭にタブを入れてたしかめてみました。
図書館の表示で、住所の地図はでるが、住所の文字列の表示は空白になるんですね。
ま、とりあえず、ひとまず、1.1.0では、これでいいことにしますか。
ということで、クローズします。

住所の冒頭にタブを入れているところ：
![image](https://cloud.githubusercontent.com/assets/1328499/9935019/5c8521c4-5d8f-11e5-8cc4-c5d77c6f20c5.png)

図書館の表示でエラーはでない。ただし、住所が空白になる例：
![image](https://cloud.githubusercontent.com/assets/1328499/9935061/90e7f996-5d8f-11e5-9e83-b330228c484f.png)

チェックした環境：
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre47)
  * enju_event (0.1.17.pre26 29feafd)
  * enju_flower (0.1.0.pre23)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 18977d2)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
