### ISSUE TITLE
利用者グループ新規作成のデフォルト値を変えませんか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#733]
新規ユーザの有効日数 0 →　365
貸出期限の何日前に督促を送るか 7 → 3
貸出期限の何日後に督促を送るか 1 → 7

あたりかなあとおもいますが。
あれ、新規ユーザの有効日数　0　ってひょっとして、期限なしといういみですか？
それならそのままでもいいですが。

http://enju.next-l.jp/user_groups/new
![image](https://cloud.githubusercontent.com/assets/1328499/9866363/7c045244-5b9c-11e5-9d36-8c47a27a7db5.png)

**Comment by nabeta** [comment]
> あれ、新規ユーザの有効日数　0　ってひょっとして、期限なしといういみですか？

そうです。

そういえば、督促の通知処理はあるものの、期限切れが近いユーザへの処理はなにも作ってませんね。

**Comment by nabeta** [comment]
> あれ、新規ユーザの有効日数　0　ってひょっとして、期限なしといういみですか？
> それならそのままでもいいですが。

そういうことなので、このままwontfixでよいでしょうか。

**Comment by yegusa** [comment]
- <s>新規ユーザの有効日数 0 →　365</s>　　←こちらはwontfixで良いですが
- 貸出期限の何日前に督促を送るか 7 → 3　←　こちらは必要
- 貸出期限の何日後に督促を送るか 1 → 7　←　こちらは必要

ということで，残り二つの修正は必要なので，wontfix をとりました。

**Comment by nabeta** [comment]
> - 貸出期限の何日前に督促を送るか 7 → 3　←　こちらは必要
> - 貸出期限の何日後に督促を送るか 1 → 7　←　こちらは必要

それぞれインストール時の既定値を上記のとおり変更しました。ただし、すでにインストール済みのEnjuには反映されないので、手動で変更する必要があります。

**Comment by nabeta** [comment]
上記の修正ではなく、以下のように修正する必要がある。

- 新規グループの初期入力値は空でよい
- インストール時に最初に作られるユーザグループのデフォルト値は上記のように変更する

**Comment by nabeta** [comment]
> インストール時に最初に作られるユーザグループのデフォルト値は上記のように変更する

上記のように設定しました。新規インストール時の`rails g enju_leaf:seed`コマンドで実行されます。

**Comment by masao** [comment]
確認しましたが、初期値はすべて 0 になってしまっています。
![image](https://user-images.githubusercontent.com/38825/72199229-95adb600-347c-11ea-88bb-1e004fcddba2.png)

**Comment by nabeta** [comment]
現時点の1.3ブランチでは、新規インストール時には以下の設定を行うようになっています。

> 貸出期限の何日前に督促を送るか 7 → 3　←　こちらは必要
> 貸出期限の何日後に督促を送るか 1 → 7　←　こちらは必要

**Comment by masao** [comment]
変更したのを確認しました。
![image](https://user-images.githubusercontent.com/38825/87870150-77eb7b80-c9e0-11ea-9ce8-f9217f8c79ce.png)
