### ISSUE TITLE
所蔵情報IDがなかった場合に背ラベルが表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#735]
#728 からの派生です。

所蔵情報IDがなかった場合に背ラベルが表示されない。

http://enju.next-l.jp/manifestations/6040
![image](https://cloud.githubusercontent.com/assets/1328499/9852664/70befa18-5b3a-11e5-9022-7ab8c5daff83.png)

ちなみに背ラベルが表示されるための他の条件は満たしています。

* ログインしている
* 図書館に請求記号ルールが設定されている
* 当該資料の所蔵が登録されている
* 当該資料の「請求記号」がルール通りに入力されている
* 当該資料の所蔵のステータスが「作業中」でない（「在架（利用可能）」「貸出中」他にもある？）
* ログインしているユーザーの所属図書館のもののみ表示する（例：所属図書館Your library　だったらYour libraryのもののみ）

**Comment by yegusa** [comment]
残作業：
* [ ] 原因調査
* [ ] バグ修正
* [ ] 確認

**Comment by masao** [comment]
現状の請求記号ラベル表示のための条件をもう少し正確に書き直すと以下の通りです：

* ログインしている。
* 図書館に請求記号ルールが設定されている。
* 当該資料の所蔵が登録されている。
* 所蔵資料の「請求記号」がルール通りに入力されている。
* 所蔵資料の本棚が「World Wide Web」（ブックマーク用）以外である。
* 所蔵資料の所蔵のステータスが「作業中」「貸出中」「再配架待ち」のいずれか。
* 所蔵資料の利用制限が「返却不要」「長期期間貸出」「通常期間貸出」「短期期間貸出」「複製不可」「一夜貸出のみ」「貸出更新不可」「監督下でのみ利用可」「学期間の貸出」「利用者の署名が必要」のいずれか。
* ログインしているユーザーの所属図書館のもののみ表示する（例：所属図書館Your library　だったらYour libraryのもののみ）

**Comment by yegusa** [comment]
@masao さん、ありがとうございます！
こういうのを期待してました！　さすがです。
マニュアルにも反映させておきますね。

**Comment by masao** [comment]
修正を行いました。 enju_circulation と enju_flower の双方あわせて更新してテストしてみてください。

**Comment by yegusa** [comment]
所蔵情報IDがなくても背ラベルが表示されることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/9981507/4478ff7a-5ffa-11e5-8cf8-9b30730434e0.png)

確認した環境
vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 62a1628)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 b7403c1)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 ca29523)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
