### ISSUE TITLE
haika対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#736]
カーリル社の Haika に対応してみたい。
https://haika.io/

**Comment by nabeta** [comment]
ひとまずメールアドレスは登録しました。

**Comment by nabeta** [comment]
haikaっていまどういうステータスなんでしたっけ。GitHubではpublicなものはなさそうですが。
https://github.com/calil

**Comment by nabeta** [comment]
2020年時点でWebサイトにアクセスできない状態なので、closeします。
