### ISSUE TITLE
一般ユーザであっても購入リクエストの詳細画面から発注リストへの追加ボタンがついている

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#737]
リンク先に遷移するとアクセス拒否の画面になりますが、一般ユーザは発注業務はできないはずなので、発注リストへの追加リンクははずしたほうがよいと思います。

**Comment by masao** [comment]
画面例：
![next l enju leaf_2](https://cloud.githubusercontent.com/assets/38825/9979018/d7506142-5f8e-11e5-8684-a583ccc1949f.png)

**Comment by yegusa** [comment]
仮想マシンで確認しましたが、「発注リストに追加する」リンクがでます。

http://localhost:8080/purchase_requests/2
![image](https://cloud.githubusercontent.com/assets/1328499/10089376/9b2eebb6-635d-11e5-8bca-98cdcff0a54f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by yegusa** [comment]
テストつくりました？ → @nabeta

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
一般ユーザーでログインしたときは、発注リストリンクが表示されないことを確認しました。
ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10099580/d988146a-63c5-11e5-8351-aad2856f582c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 51bbb80)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)
