### ISSUE TITLE
統計メニューの注記欄は使っていないので削除する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#740]
統計ページに注記列があるが、特に設定・入力メニューは用意されていないので、削除してよいように思います。

![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10025513/a2d28200-6197-11e5-8e26-b020c791c386.png)

**Comment by nabeta** [comment]
なにか入れようとしたような気がするのですが、思い出せないので削除しておきます。

**Comment by nabeta** [comment]
開発サーバで削除しました。
http://dev.next-l.jp/page/statistics

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします。
![image](https://cloud.githubusercontent.com/assets/1328499/10051625/794dd0d0-625d-11e5-987d-0c8806c5d435.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 ef38a28)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
