### ISSUE TITLE
貸出統計を閲覧できてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#741]
非ログイン状態もしくは一般利用者としてログインした状態であっても、利用者別貸出統計の表示にて、他の利用者の貸出統計が閲覧できてしまう。図書館員以上の権限を要求すべき。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10026068/a18d4558-619a-11e5-8fba-5feebb51e067.png)
![image](https://cloud.githubusercontent.com/assets/38825/10026083/b7e4234e-619a-11e5-8a33-b936da22a6af.png)

**Comment by nabeta** [comment]
貸出と予約の統計にはLibrarian権限を必要とするようにしました。
http://dev.next-l.jp/user_checkout_stats
http://dev.next-l.jp/user_reserve_stats

**Comment by yegusa** [comment]
テストも作りましたか？ → @nabeta

**Comment by nabeta** [comment]
はい、上記コミットの詳細を参照してください。

**Comment by yegusa** [comment]
仮想マシンで確認しました。一般ユーザー権限でアクセス拒否されたのを確認しました。
ので、クローズします。
ゲストユーザーの場合は、ログインのページに飛ばされました。

http://localhost:8080/user_checkout_stats/1
![image](https://cloud.githubusercontent.com/assets/1328499/10051863/adb16782-625e-11e5-92f4-523dd22379c2.png)

http://localhost:8080/user_reserve_stats/1
![image](https://cloud.githubusercontent.com/assets/1328499/10051989/583b661c-625f-11e5-92fd-2ef0fca85820.png)

貸出資料別は見えていいのね。こっちはアクセス拒否にならずにみれました。
http://localhost:8080/manifestation_checkout_stats/1
http://localhost:8080/manifestation_reserve_stats/1

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 ef38a28)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by nabeta** [comment]
この修正を含めた enju_circulation モジュールは今日中にリリース予定です。
