### ISSUE TITLE
分類：「カテゴリー」を「分類記号」にしたい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#742]
http://enju.next-l.jp/classifications
![image](https://cloud.githubusercontent.com/assets/1328499/10040356/d499484a-6215-11e5-8f50-bef2b5a6a988.png)

* [ ] 一覧　http://dev.next-l.jp/classifications
* [ ] 編集 http://dev.next-l.jp/classifications/1/edit
* [ ] 新規 http://dev.next-l.jp/classifications/new
* [ ] 表示 http://dev.next-l.jp/classifications/1

**Comment by nabeta** [comment]
「分類記号」に変更しました。
http://dev.next-l.jp/classifications

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10089014/40b79c62-635a-11e5-947d-a41fdc0a4536.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10089029/5d6cd764-635a-11e5-889b-588fc48ef600.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10089041/7dd51318-635a-11e5-9832-bf07dcbe6815.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10089052/917a4708-635a-11e5-8f10-bfd5884738bd.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_subject (0.1.0.pre33 bf1ac84)
