### ISSUE TITLE
分類に「分類項目名」を入力できる・表示できるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#743]
* [x] 編集 http://dev.next-l.jp/classifications/1/edit

イメージ：
![image](https://cloud.githubusercontent.com/assets/1328499/10040475/0165f520-6217-11e5-8dd1-85db9c662c12.png)

* [x] 一覧　http://dev.next-l.jp/classifications
![image](https://cloud.githubusercontent.com/assets/1328499/10040416/777108fa-6216-11e5-8103-fb503fa902b9.png)

* [x] 新規 http://dev.next-l.jp/classifications/new
* [x] 表示 http://dev.next-l.jp/classifications/1

**Comment by nabeta** [comment]
「分類項目名」の英語での名称を教えてください。

**Comment by yegusa** [comment]
classification　label とか、 classification name とかかなあ。今、ちょと調べにくい環境にいるので、 @nabeta さんのほうでも調べてもらえると助かる。

**Comment by nabeta** [comment]
labelとします。

**Comment by nabeta** [comment]
分類項目名を入力できるようにしました。デモサーバに反映済みです。
http://dev.next-l.jp/classifications/1

データベースの変更が必要です。

```sh
$ rake enju_subject_engine:install:migrations
$ rake db:migrate RAILS_ENV=production
```

**Comment by yegusa** [comment]
できることを確認しましたので、クローズします。

編集 
![image](https://cloud.githubusercontent.com/assets/1328499/10100956/637a5796-63d0-11e5-9407-8cfa04a004d7.png)

一覧 #744 で一覧でURLが表示されるようにしていましたが、やめたんですね。
![image](https://cloud.githubusercontent.com/assets/1328499/10101024/dbf6f8e6-63d0-11e5-930a-34762193eb0b.png)

新規作成
![image](https://cloud.githubusercontent.com/assets/1328499/10101004/b9439980-63d0-11e5-9e24-571cf2fd98a8.png)

表示
![image](https://cloud.githubusercontent.com/assets/1328499/10100970/7cddcb00-63d0-11e5-93a1-f263683c2150.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 cc91c8d)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 e44b953)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)
