### ISSUE TITLE
分類に「URL」を入れられるようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#744]
* [x] 編集 http://dev.next-l.jp/classifications/1/edit
イメージ：
![image](https://cloud.githubusercontent.com/assets/1328499/10040773/909bf940-6219-11e5-896a-a26359bda621.png)

* [x] 一覧　http://dev.next-l.jp/classifications
* [x] 新規 http://dev.next-l.jp/classifications/new
* [x] 表示 http://dev.next-l.jp/classifications/1

**Comment by nabeta** [comment]
DDCなどの外部のURLを入れるのが目的でしょうか？

**Comment by yegusa** [comment]
LOD化している分類体系の場合に、当該分類記号をあらわすURLを入れられるといいかなというイメージです。

**Comment by nabeta** [comment]
表示・編集とも実装しました。以下のコマンドを実行したあと、Webサーバを再起動してください。

```sh
$ rake enju_subject_engine:install:migrations
$ rake db:migrate RAILS_ENV=production
```

開発サーバには反映済みです。
http://dev.next-l.jp/classifications/1/edit

**Comment by yegusa** [comment]
仮想マシンでできることを確認しましたのでクローズします。
（マニュアルはまだ反映させてません。）

![image](https://cloud.githubusercontent.com/assets/1328499/10088750/097618d4-6358-11e5-992e-8bcf6bde73f9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10088759/2a3e0f40-6358-11e5-925e-ca9b4349189c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10088879/0e881178-6359-11e5-9dca-03f8c5629503.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10088908/3db2470c-6359-11e5-8fcd-1d256e18fd1a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 212222f)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 4e93af0)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by yegusa** [comment]
メモ：　#743 の時点で、「一覧」にはURLは表示されなくなったもよう。
