### ISSUE TITLE
資料の形態の編集画面で「貸出種別」を「貸出区分」に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#745]
http://dev.next-l.jp/carrier_types/2/edit
![image](https://cloud.githubusercontent.com/assets/1328499/10046057/9bf35c7a-6241-11e5-8257-a59b0dabd64a.png)

注：表示画面では、「貸出区分」になっているので修正は不必要

http://dev.next-l.jp/carrier_types/2
![image](https://cloud.githubusercontent.com/assets/1328499/10046040/7e47c4ea-6241-11e5-9525-399832044607.png)

## Todo

* [x] バグ修正
* [x] 確認
* [x] マニュアル修正　
    * http://next-l.github.io/manual/enju_setup_5.html#cd
    * http://next-l.github.io/manual/enju_setup_5.html#cd-1

**Comment by yegusa** [comment]
マニュアル修正のコミットするときにログに書き忘れたけど、
https://github.com/next-l/manual/commit/56868ba130ff6afecce6ec65c3adc3351da14b30
文章の修正 ↑で、修正ずみです。

**Comment by nabeta** [comment]
修正しました。
http://dev.next-l.jp/carrier_types/2/edit

**Comment by yegusa** [comment]
仮想マシンで確認しました。
クローズします。

http://localhost:8080/carrier_types/2/edit
![image](https://cloud.githubusercontent.com/assets/1328499/10053615/139beaa0-6268-11e5-9c68-9b56e0d3801d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 96525c9)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
