### ISSUE TITLE
予約一覧画面を閲覧しようとするとRailsエラーになる

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#746]
1.1系の最新版です。おそらく #674 の修正の影響と思われる。
![action controller exception caught](https://cloud.githubusercontent.com/assets/38825/10046349/4094bc6e-6243-11e5-880b-30f8ae6ea408.png)

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
仮想マシンで、予約の一覧がでることを確認しましたので、クローズします。

http://localhost:8080/reserves
![image](https://cloud.githubusercontent.com/assets/1328499/10051761/236f0c14-625e-11e5-80d6-ac43138a43d2.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 ef38a28)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
