### ISSUE TITLE
資料の内容の種別の一覧の順序の矢印がないものがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#747]
http://localhost:8080/content_types

![image](https://cloud.githubusercontent.com/assets/1328499/10047391/ec94840e-6248-11e5-8cf5-af2a5a680f42.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 666e6eb)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

## Todo

* [x] テスト作成
* [x] バグ修正
* [x] 確認
* [x] マニュアル修正 http://next-l.github.io/manual/enju_setup_5.html#section-8

**Comment by masao** [comment]
他のものも含め、まとめて修正しました。

**Comment by yegusa** [comment]
仮想マシンで確認しました。
マニュアルも修正しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10052463/02934484-6262-11e5-9a50-967113f70f78.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 96525c9)
  * enju_circulation (0.1.0.pre48 ef38a28)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

**Comment by yegusa** [comment]
これが再発しましたので、リオープンします。

![image](https://cloud.githubusercontent.com/assets/1328499/10454385/573765d2-71ef-11e5-8650-91cc784c9932.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
あ、すみません、勘違いです。クローズします。。。
