### ISSUE TITLE
利用者のプロフィール編集へのリンクがありません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#75]
マニュアルには、利用者のプロフィールが編集できるような説明がありますが、そのようなリンクはありません。仕様変更があったのでしょうか？

マニュアル：3-4利用者のプロフィール情報を変更する
http://enju.github.com/manual/enju_operation.html#section-15

**Comment by masao** [comment]
このIssueの標記の目標は達成されているようなので、ひとまずクローズしませんか？

**Comment by nabeta** [comment]
私もクローズするのでよいと思います。

**Comment by yegusa** [comment]
じゃあ、いったんクローズします。

参考：　以下、関連issue について
* 利用者個人情報（プロフィール）は、プロフィール用の専用画面ではなく、直接、利用者編集画面で扱うようになった　参考 #441
* #78 enju_leaf に個人情報を登録できるようにする　として、関連別isssuあり
* #636 利用者情報を別システムで管理できるようにする で、代替手段も確保
