### ISSUE TITLE
言語の「ネイティブ名」ってどこで必要になるのですか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#750]
![image](https://cloud.githubusercontent.com/assets/1328499/10048729/47855860-624f-11e5-9bc4-b7c7820b0208.png)

**Comment by nabeta** [comment]
これは他のi18n用gemに項目をあわせていたためだったと思うのですが、今見ると見当たりませんね。記憶違いかなあ…。
https://github.com/svenfuchs/rails-i18n/blob/master/rails/locale/ja.yml

**Comment by nabeta** [comment]
もし「ネイティブ名」がセットされていた場合、画面上部の言語切り替えリンクに反映されます。

**Comment by yegusa** [comment]
表示名との使い分けを教えてください。

**Comment by nabeta** [comment]
「ネイティブ名」は図書館で変更しないもの（外部から正式な名称リストを取り込んで使用することを想定）、「表示名」は図書館で変更できるものという扱いです。また、書誌の編集画面に使用されるのは「表示名」です。

**Comment by yegusa** [comment]
デモサーバーで確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12229346/36e40fce-b88a-11e5-9af5-19a79d5ce335.png)

「ネイティブ名」がセットされていた場合、画面上部の言語切り替えリンクに反映：
![image](https://cloud.githubusercontent.com/assets/1328499/12229388/7cb23f9e-b88a-11e5-926a-cf9f783549ac.png)

書誌の編集画面に使用されるのは「表示名」
![image](https://cloud.githubusercontent.com/assets/1328499/12229421/c7486150-b88a-11e5-9bbc-173b2820239d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12229432/ea69e26c-b88a-11e5-8551-8cff6654b224.png)

enju_biblio: 0.1.2
enju_circulation: 0.1.1
enju_event: 0.1.18
enju_flower: 0.1.1
enju_leaf: 1.1.2
enju_library: 0.1.1
enju_manifestation_viewer: 0.1.1
enju_message: 0.1.15
enju_ndl: 0.1.1
enju_purchase_request: 0.1.1
enju_subject: 0.1.1
