### ISSUE TITLE
発行頻度の一覧の[削除]リンクがないものがある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#753]
http://localhost:8080/frequencies

![image](https://cloud.githubusercontent.com/assets/1328499/10049298/dd5cc984-6251-11e5-9100-feef4379f0fe.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9c03122)
  * enju_circulation (0.1.0.pre48 666e6eb)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)

#751 に関連

## Todo

* [x] テスト作成
* [x] バグ修正
* [x] 確認
* [x] マニュアル修正 http://next-l.github.io/manual/enju_setup_5.html#section-25

**Comment by masao** [comment]
現状、関連するManifestationがあるものについては削除禁止とする仕様になっていますね。

**Comment by yegusa** [comment]
仮想マシンで確認しました。
マニュアルに、削除リンクが出ない場合の理由について追記もしました。
ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10053297/41c921f6-6266-11e5-8fbd-b7d3130b3925.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 96525c9)
  * enju_circulation (0.1.0.pre48 ef38a28)
  * enju_event (0.1.17.pre26 7af0bba)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 a537d12)
  * enju_library (0.1.0.pre43 a92f1ef)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 1e2c426)
  * enju_subject (0.1.0.pre33)
