### ISSUE TITLE
ResourceSync対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#755]
OAI-PMH対応にめどがつきつつあるため、今度は次のプロトコル対応機能へ。。。

**Comment by nabeta** [comment]
おそらくsitemap_generatorを拡張することになると思います。以下のファイルが該当しそうです。
https://github.com/kjvarga/sitemap_generator/blob/master/lib/sitemap_generator/builder/sitemap_url.rb

**Comment by masao** [comment]
ResourceSync用のgemもリリースされてました（中身は見ていない）：
https://github.com/CDLUC3/resync

**Comment by nabeta** [comment]
現在の出力は以下。

- https://dev.next-l.jp/resourcesync/capabilitylist.xml
- https://dev.next-l.jp/resourcesync/resourcelist_index.xml
- https://dev.next-l.jp/resourcesync/changelist_index.xml

**Comment by nabeta** [comment]
resync gemはResourceSync 1.1に対応しておらず、changelistがうまく取得できないため、現時点ではforkしたバージョンを使用している。
https://github.com/nabeta/resync/tree/add-datetime

サーバ側では以下のコマンドで、<s>`public/resourcesync/`</s> `public/`以下にResourceSyncのXMLファイルを出力する。

- rake enju_leaf:resourcesync:capabilitylist
- rake enju_leaf:resourcesync:resourcelist
- rake enju_leaf:resourcesync:changelist[20220101] # 引数の日付以降に更新されたManifestationを出力

動作検証にはPythonで書かれたクライアントを使用している。
https://github.com/resync/resync

```sh
$ pip install resync
$ resync-sync https://dev.next-l.jp -b # 新規取得
$ resync-sync https://dev.next-l.jp -i # 差分取得
```
