### ISSUE TITLE
Sitemaps対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#756]
いわゆる検索エンジン（SEO）対応で欲しい機能のひとつ。
だいぶ昔から https://github.com/kjvarga/sitemap_generator は読み込んでいるようなので、文書化だけの問題かも!?

**Comment by nabeta** [comment]
Manifestationの情報があればよいですかね？

**Comment by masao** [comment]
はい、書誌の情報だけでひとまずはよいように思います。

**Comment by nabeta** [comment]
以下のコマンドを実行し、設定ファイル config/sitemap.rb を作成します。

```sh
$ bundle exec rake sitemap:install
```

config/sitemap.rb を編集します。

```ruby
# ホスト名を変更
SitemapGenerator::Sitemap.default_host = "http://enju.example.jp"

SitemapGenerator::Sitemap.create do
  # 中略
  # 以下の3行を追加
  Manifestation.find_each do |manifestation|
    add manifestation_path(manifestation), lastmod: manifestation.updated_at
  end
end
```

最後に、以下のコマンドでサイトマップを作成・更新します。ファイルは public/sitemap.xml.gz に作成されます。定期的にサイトマップを更新する場合、以下のコマンドをcronなどに登録してください。

```sh
$ bundle exec rake sitemap:create RAILS_ENV=production
```

サイトマップは以下のURLでアクセスできます。
http://dev.next-l.jp/sitemap.xml.gz

更新頻度(changefreq)などのオプションの指定方法は、sitemap_generator gemのマニュアルをごらんください。
https://github.com/kjvarga/sitemap_generator

**Comment by masao** [comment]
:+1:

**Comment by masao** [comment]
確認しました。クローズします。

**Comment by yegusa** [comment]
mdマニュアル は enju_install_vm_10.html を修正するとよさそう。
