### ISSUE TITLE
詳細検索で何も入力せずに検索しても分類検索がクエリに追加されてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#761]
#565 での機能追加時のバグと思われる。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10094097/735936d0-6396-11e5-9127-684170b5fa39.png)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします。

詳細検索で、なにもいれずに、[検索]ボタンをクリックしても、
ちゃんと、検索語には空白のままなのを確認しました。

http://localhost:8080/manifestations?utf8=%E2%9C%93&query=&title=&creator=&publisher=&isbn=&issn=&call_number=&item_identifier=&classification_type=1&classification=&pub_date_from=&pub_date_to=&acquired_from=&acquired_to=&number_of_pages_at_least=&number_of_pages_at_most=&advanced_search=true&commit=%E6%A4%9C%E7%B4%A2
![image](https://cloud.githubusercontent.com/assets/1328499/10094709/0b1011f4-639e-11e5-9286-abfbc026f8ca.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3faf44b)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)
