### ISSUE TITLE
OAI-PMH: ListIdentifiersにてmetadataPrefix属性を出力する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#762]
#710 から派生。

**Comment by nabeta** [comment]
現状でもいちおう反応はするようになっていませんか？ 細かいパラメータはともかく。
http://dev.next-l.jp/oai/provider.xml?verb=ListIdentifiers

**Comment by masao** [comment]
request要素のmetadataPrefixが示されていないので、そこを出力すればOkそうですね。

**Comment by nabeta** [comment]
metadataPrefixをレスポンスに含めるように修正しました。
https://dev.next-l.jp/oai/provider.xml?verb=ListIdentifiers&metadataPrefix=oai_dc
https://dev.next-l.jp/oai/provider.xml?verb=ListRecords&metadataPrefix=oai_dc

**Comment by masao** [comment]
修正を確認しました。クローズします。

**Comment by masao** [comment]
この件、マニュアルは不要と思います。

**Comment by yegusa** [comment]
了解！
