### ISSUE TITLE
OAI-PMH: Set機能について議論する

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#763]
Set定義がそもそも可能かどうかEnjuとしての仕様を議論する。
#710 から派生。

**Comment by nabeta** [comment]
素直に別のモデルを定義するのがよいと思います（SetとかCollectionとか）が、ひとつの書誌が複数のSetに含まれることってあるんでしょうか。

**Comment by nabeta** [comment]
https://github.com/next-l/enju_leaf/pull/1729 でOAI-PMHプロバイダの実装はruby-oaiを使用するように変更しているが、このgemはSetのサポートがいまいちとのこと。コードを見たところ、OAI-PMHの出力対象のモデルに対応するテーブル（Enjuの場合は`manifestations`テーブル）に`set`カラムが必要で、ひとつの書誌を複数のSetに含めることはできないと思われる。  
https://github.com/code4lib/ruby-oai/issues/67

**Comment by nabeta** [comment]
対応なしとしてクローズします。
