### ISSUE TITLE
OAI-PMH: Content-Typeをtext/xmlとする

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#764]
現在は application/xml となっている。
cf. https://www.openarchives.org/OAI/openarchivesprotocol.html#MIMETypes

**Comment by nabeta** [comment]
text/xmlで返すようにしました。mustならしょうがないですね。
http://dev.next-l.jp/oai/provider.xml?verb=ListIdentifiers

**Comment by masao** [comment]
さっそくありがとうございます。確認しました。クローズします。
