### ISSUE TITLE
OAI-PMH: ListRecordsでmetadataPrefix無指定の場合にエラーにする

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#765]
#710 からの派生。

**Comment by nabeta** [comment]
metadataPrefixがない場合、ListRecords・ListIdentifiers・GetRecordがエラーになるようにしました。
http://dev.next-l.jp/oai/provider.xml?verb=ListRecords
http://dev.next-l.jp/oai/provider.xml?verb=ListRecords&metadataPrefix=oai_dc
http://dev.next-l.jp/oai/provider.xml?verb=ListRecords&metadataPrefix=junii2

**Comment by masao** [comment]
http://dev.next-l.jp/oai/provider.xml?verb=GetRecord&identifier=oai:enju.next-l.jp:manifestations-4030 GetRecordのほうはエラーにならない状態ですね。

**Comment by nabeta** [comment]
GetRecordの処理が正しくなかったのを修正しました。
http://dev.next-l.jp/oai/provider.xml?verb=GetRecord&identifier=oai:enju.next-l.jp:manifestations-4030&metadataPrefix=oai_dc

**Comment by masao** [comment]
修正を確認しました。クローズします。
