### ISSUE TITLE
OAI-PMH: ListRecordsのresumptionToken対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#766]
- [ ] マニュアル修正 #1191

resumptionTokenに対応して保存すべきクエリ等を確認すること。
#710 からの派生。

**Comment by nabeta** [comment]
Solr 4.7から使用できるcursorMarkパラメータを使ったページネーションが使えるので、このパラメータをresemptionTokenとして使用する。
https://github.com/sunspot/sunspot#cursor-based-pagination

**Comment by nabeta** [comment]
> Solr 4.7からcursorMarkパラメータを使ったページネーションが使えるので、このパラメータをresemptionTokenとして使用する。

上記の実装を行いました。開発用サーバに反映済みです。
なお、sunspot_solrを使用する場合、2.2.2（Solr5.0.0同梱）以降が必要です。

**Comment by yegusa** [comment]
現在のステータス：

- 私は確かめ方がわかりません。

**Comment by nabeta** [comment]
テストを書く。

**Comment by masao** [comment]
確認してみましたが、resumptionTokenの呼び出しで badArgument のエラーを出してしまいますね。
https://www.openarchives.org/OAI/2.0/guidelines-harvester.htm#resumptionToken にある通り、必要なパラメータを保存しなくてはならないので、まだ resumptionToken パラメータの実装ができていない状態です。

**Comment by nabeta** [comment]
resumptionTokenをEnju側で覚えておく必要があるのですが、この実装が面倒です。
resumptionToken対応をやめるか、それともOAI-PMHそのもの対応をやめてResourceSyncに置き換えるかしたほうがよいかもしれません。

**Comment by nabeta** [comment]
OAI-PMHの実装は、oai gemを使って書き直すことにします。
https://github.com/code4lib/ruby-oai

**Comment by nabeta** [comment]
> OAI-PMHの実装は、oai gemを使って書き直すことにします。
https://enju.next-l.jp/oai?verb=ListRecords&metadataPrefix=dcndl

**Comment by nabeta** [comment]
完了しているため、クローズします。
