### ISSUE TITLE
要望：利用者情報のエクスポートにフルネーム、よみ、利用不可、参照権限などを出力するようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#768]
いくつか、エクスポートできないものがあります。
エクスポートできるようにしてほしいです。

* [x] full_name
* [x] full_name_transcription
* [x] locked
* [x] required_role

メモ：インポートにはあるけど、エクスポートに入らない項目： password, dummy

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3faf44b)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_oai (0.1.0.pre19 3608817)
  * enju_purchase_request (0.1.0.pre14 e882dbe)
  * enju_subject (0.1.0.pre33 bf1ac84)

**Comment by nabeta** [comment]
4項目を追加しました。
http://dev.next-l.jp/user_export_files

**Comment by yegusa** [comment]
仮想マシンでできることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10117126/90091010-6487-11e5-9acb-315b04418ded.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10117182/039f2306-6489-11e5-9568-ad396eafe152.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 6515583)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by yegusa** [comment]
マニュアルに、エクスポートする項目を追記しておきました。
