### ISSUE TITLE
すでに分類記号が登録されている分類をつけた書誌が作成できない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#769]
#758 の修正に起因するバグだと思われます。

一覧：　061 / UDC がある
![image](https://cloud.githubusercontent.com/assets/1328499/10101478/f692dea6-63d3-11e5-8037-3f61e46b86bb.png)

すでに、存在する分類（例　061 / UDC）の書誌を作ろうとして、
書誌がつくれなかった → NG
![image](https://cloud.githubusercontent.com/assets/1328499/10101565/6d8a0ebc-63d4-11e5-86be-203814c5e9c9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 eef0879)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 0a65823)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 9c7a2b1)

**Comment by yegusa** [comment]
（すみません、2こ目の書誌ができないのではなく、1こ目の書誌から作成できませんでした）

**Comment by nabeta** [comment]
#758 をいったん元に戻します。

**Comment by masao** [comment]
これ、1.1.0リリースした後にまわしませんか？ 影響範囲が大きそうなので。

**Comment by yegusa** [comment]
良いと思います。そうしましょう。

**Comment by masao** [comment]
この問題、当時のコードがもとにもどったことで現時点では再現しなくなっていますので、いったんクローズします。
