### ISSUE TITLE
貸出期限のicalendar url　の[リセット]ボタンをクリックしてもなにも起きません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#770]
貸出期限のicalendar url　の[リセット]ボタンをクリックしてもなにも起きません

![image](https://cloud.githubusercontent.com/assets/1328499/10115157/2fcc9002-643a-11e5-8309-16b507dec8b9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e15ebb7)
  * enju_circulation (0.1.0.pre48 912c42d)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5568542)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by nabeta** [comment]
修正しました。
http://dev.next-l.jp/my_account/edit

**Comment by yegusa** [comment]
できることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10117094/6ab49862-6486-11e5-8bc4-d27d7978785d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10117095/8102fa50-6486-11e5-9e74-1786e0d308f8.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10117097/98ca7618-6486-11e5-897d-747403050543.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 6515583)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)
