### ISSUE TITLE
利用者情報のエクスポートで「有効期限」（expired_at）が出力されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#772]
u550008 には有効期限が設定されている
![image](https://cloud.githubusercontent.com/assets/1328499/10117209/c20e95ec-6489-11e5-9145-79466293d4a1.png)

u550008の有効期限のセルが空になっている
![image](https://cloud.githubusercontent.com/assets/1328499/10117220/0fc7e608-648a-11e5-8684-1ed1106caf16.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 6515583)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by nabeta** [comment]
修正しました。開発サーバに反映済みです。
http://dev.next-l.jp/user_export_files/39

**Comment by yegusa** [comment]
仮想マシンでできることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10118169/053cf05c-64ad-11e5-88a2-408db0c15e86.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9e0b11c)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)
