### ISSUE TITLE
isbnだけが入ったTSVファイルを使って書誌のTSVインポートしても「ISBNインポートのリクエストの一覧」に表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#773]
例えば、以下のTSVファイルを、書誌と所蔵のインポートでインポートする。

<pre>
isbn
9784873114828
9784873115474
9784873113531
</pre>

書誌はインポートされる。
![image](https://cloud.githubusercontent.com/assets/1328499/10117660/8bfd85ac-6499-11e5-8b2d-d556abafd98b.png)

「ISBNインポートのリクエストの一覧」には、インポートされた書誌の結果が表示されない

「ISBNインポートのリクエストの一覧」　http://localhost:8080/import_requests
![image](https://cloud.githubusercontent.com/assets/1328499/10117643/265619b2-6499-11e5-963a-5e31b9875852.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 6515583)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by nabeta** [comment]
TSVでのインポートと「ISBNインポート」は別々に管理されているため、これは想定通りの動作です。

**Comment by yegusa** [comment]
じゃあ、マニュアルにかいてあることがまちがっているってこと？

http://next-l.github.io/manual/enju_operation_4.html#section4-2-2

**Comment by nabeta** [comment]
そうです。

**Comment by yegusa** [comment]
じゃあ、仕様をかえませんか？どれが、失敗しているかわからないと困ります。

**Comment by nabeta** [comment]
どの行が失敗したかは「資料インポートの結果」を参照してください。
http://dev.next-l.jp/resource_import_files/158

**Comment by yegusa** [comment]
一応、確認だけど、前からそういう仕様だった？rc9以降に変えた？ → @nabeta

**Comment by nabeta** [comment]
前からというか、最初からです。

**Comment by yegusa** [comment]
そうですか。じゃあなんで、そういうマニュアル書いたんだろ。ふしぎだなあ。まあ、わかりました、マニュアルのほうを書き換えます。

**Comment by yegusa** [comment]
マニュアルが間違っていたということなので、これは、バグじゃないということで、クローズします。

**Comment by yegusa** [comment]
> どの行が失敗したかは「資料インポートの結果」を参照してください。
> http://dev.next-l.jp/resource_import_files/158

これじゃあ、わからないよね？
http://dev.next-l.jp/resource_import_results?resource_import_file_id=158

こっちだよね？
