### ISSUE TITLE
提案：表の表示内容にもっと改善の余地あり（書誌と所蔵インポートの結果の一覧） 

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#776]
#156 と類似。

この表は、わかりずらい。

http://dev.next-l.jp/resource_import_results?resource_import_file_id=160
![image](https://cloud.githubusercontent.com/assets/1328499/10118526/18599246-64b5-11e5-9729-f277aa30960b.png)

こんな感じにできるといいなと思います。
![image](https://cloud.githubusercontent.com/assets/1328499/10118534/4c9bffe4-64b5-11e5-8558-357a2f267af8.png)

ちなみに、TSVの例は
<pre>
isbn
9784939076770
9780007264551
9784826901116
</pre>

9780007264551　は、NDLにない本で書誌インポートが失敗するものです。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5e3d293)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by masao** [comment]
https://github.com/next-l/enju_biblio/commit/fc5959b8537f8889987c12bd726e546007a528ed にて修正しました。
なお #156 と同様、行数表示は実際のファイル中の行数と異なる場合があります（一部を削除した場合など）。
また、上記で提案されていた成否ステータス列については、作成・更新・削除等のモードごとに切り分けて、それぞれの失敗状態を定義しなおす必要があり、その判定が難しいため、実装していません。

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします。
マニュアルのスクリーンショットも差し替えておきました。

成否ステータスについては別issueにして、1.1.0より上に送ります。

![image](https://cloud.githubusercontent.com/assets/1328499/10122382/98d2d2be-6552-11e5-8e73-42038ad7712e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 fc5959b)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e6b1415)
  * enju_library (0.1.0.pre44 536bd54)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
