### ISSUE TITLE
要望：所蔵情報の新規作成に「分類」を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#778]
イメージ：
![image](https://cloud.githubusercontent.com/assets/1328499/10120819/3436aa4e-650a-11e5-95c1-d2512d16a74d.png)

請求記号をつけるときに、あるととっても助かる。

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by nabeta** [comment]
所蔵の新規作成・編集時に分類を表示するようにしました。
http://dev.next-l.jp/items/new?manifestation_id=24403
http://dev.next-l.jp/items/17410/edit

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10121763/8bcc2960-6536-11e5-9ce4-2b94d01f0bfa.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 742ba09)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 692c70f)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
