### ISSUE TITLE
分類の「新規作成」と「編集」で、「分類の種類」を一番上にしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#780]
![image](https://cloud.githubusercontent.com/assets/1328499/10121216/7ec06b6a-651c-11e5-8b89-3a543bf03dd2.png)

注記の下にあると、存在を忘れるし、変なので。

* [x] 修正：新規作成画面
* [x] 確認：新規作成画面
* [x] 修正：編集画面
* [x] 確認：編集画面
* [x] マニュアルのスクリーンショット差し替え（新規作成画面のみ、編集画面の画像はない） http://next-l.github.io/manual/assets/images/image_initial_055.png

**Comment by nabeta** [comment]
移動しました。
http://dev.next-l.jp/classifications/new
http://dev.next-l.jp/classifications/3/edit

**Comment by yegusa** [comment]
仮想マシンで確認しました。
マニュアルも修正しました。
クローズします。

新規作成：
![image](https://cloud.githubusercontent.com/assets/1328499/10121750/0c659594-6536-11e5-9224-290bc748c1e2.png)

編集：
![image](https://cloud.githubusercontent.com/assets/1328499/10121752/1fa043de-6536-11e5-8ed3-4a7091819009.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 742ba09)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 692c70f)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
