### ISSUE TITLE
人物・団体の種類で消してはいけないものが消せてしまう

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#781]
* [x] 開発：人物・団体の種類で、消してはいけないものは消せないようにする（この種類をつかった人物・団体レコードがあるものは消してはいけない）
* [x] 開発：一覧：消せないものは[削除]リンクを表示させない
* [x] 確認
* [x] マニュアルの修正

人物・団体の種類として、つかっている種類（例：person）を消そうとしているところ：
![image](https://cloud.githubusercontent.com/assets/1328499/10121603/65e2a1a4-652f-11e5-8dcf-ce1f2b1e2927.png)

消せちゃった！
![image](https://cloud.githubusercontent.com/assets/1328499/10121606/81c9dafe-652f-11e5-8de6-57d0ebe34abf.png)

人物・団体の管理が We're sorry になるようになってしまう
http://localhost:8080/agents
![image](https://cloud.githubusercontent.com/assets/1328499/10121608/9b618728-652f-11e5-8b36-8e1c0b0b54f4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by nabeta** [comment]
すでに関連づけられている人物・団体がある場合、その種別を削除できないようにしました。
http://dev.next-l.jp/agent_types

**Comment by yegusa** [comment]
削除をためすのはできないのでやってないけど、ま、大丈夫だよね。
リンクがなくなっているのは確認しました。
マニュアルも修正しました。
ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10122236/c4f6bac8-654c-11e5-8aa1-e484e92d6667.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 1c640d3)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e6b1415)
  * enju_library (0.1.0.pre44 536bd54)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
