### ISSUE TITLE
人物・団体の種類の新規作成や編集に、「名前」に必須登録項目のマークがない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#782]
* [x] 開発：必須マークを新規画面につける
* [x] 確認：新規画面
* [x] 開発：必須マークを編集画面につける
* [x] 確認：編集画面
* [x] マニュアル：新規画面 スクリーンショット差し替え(編集画面はない） http://next-l.github.io/manual/assets/images/image_initial_agenttype_2.png

http://localhost:8080/agent_types
![image](https://cloud.githubusercontent.com/assets/1328499/10121626/aa47839a-6530-11e5-8d5d-a76a426c3e05.png)

（メモ：表示名は、入力してない場合は、自動的に名前から追記されるから、必須登録項目ではない）

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5ceb409)
  * enju_circulation (0.1.0.pre48 1900f92)
  * enju_event (0.1.17.pre26 924a638)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e796614)
  * enju_library (0.1.0.pre44 bc70658)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 2bbd088)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 fefd5fc)

**Comment by masao** [comment]
フォーム実装を修正しました。確認願います。

**Comment by yegusa** [comment]
「* 印のついている項目は入力が必須です。」

がほしいです。
http://localhost:8080/agent_types/new
![image](https://cloud.githubusercontent.com/assets/1328499/10135529/c9bbfd24-6629-11e5-94af-dfa7c442525c.png)


例：http://localhost:8080/shelves/new　
![image](https://cloud.githubusercontent.com/assets/1328499/10135514/944031c4-6629-11e5-95a1-6d39bb4016f3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7c95cca)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。マニュアルも修正しました。ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10139715/38a87504-663f-11e5-8f6a-55c4d84faa3c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10139745/5cb4d99c-663f-11e5-8be6-446328d8f495.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 324409d)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
