### ISSUE TITLE
人物・団体の　フルネーム代替）　→　フルネーム（代替）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#783]
* [x] 開発：編集画面
* [x] 確認　編集画面
* [x] マニュアル　編集画面
* [x] 開発：新規画面
* [x] 確認 新規画面
* [x] <s>マニュアル　新規画面</s> マニュアルに無かったため

![image](https://cloud.githubusercontent.com/assets/1328499/10121808/3552a7aa-6539-11e5-83ea-91da03125bbb.png)

**Comment by nabeta** [comment]
修正しました。
http://dev.next-l.jp/agents/3/edit

**Comment by yegusa** [comment]
仮想マシンで確認しました。マニュアルも修正しました。

![image](https://cloud.githubusercontent.com/assets/1328499/10122194/03275ca0-654b-11e5-9c02-f3968fd88aff.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10122196/271315a0-654b-11e5-8ff1-dfc8a20e3a7b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 1c640d3)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e6b1415)
  * enju_library (0.1.0.pre44 8327ed3)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
