### ISSUE TITLE
所蔵検索の受入日の指定で末尾指定が有効になっていない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#786]
受入日のおわり（「○○から××」の後者）を指定しても検索に反映されない。
http://enju.next-l.jp/items

**Comment by nabeta** [comment]
修正しました。パラメータ名が誤っていました。
http://dev.next-l.jp/items

また、同様の問題が詳細検索にも存在していました。あわせて修正してあります。
http://dev.next-l.jp/page/advanced_search

**Comment by yegusa** [comment]
仮想マシンでできていることを確認しました。
クローズします。

## 修正前：
2015-09-25 から　 2015-09-26 で検索する
![image](https://cloud.githubusercontent.com/assets/1328499/10122280/c21c17ec-654e-11e5-82fe-3469852af265.png)

2015-09-26 が消えている　→　NG
2件のみヒットするはず　→ 4件ヒットする(2015-09-27, 28 のものがヒットしている）　→　NG
![image](https://cloud.githubusercontent.com/assets/1328499/10122288/ec7e626a-654e-11e5-9b34-358300281bf5.png)

## 修正後

所蔵検索の検索結果
2015-09-26 が消えていない　→　OK
2015-09-25, 2015-09-26のみのものがヒットする（2015-09-27, 28 のものがヒットしていない。）　→　OK
![image](https://cloud.githubusercontent.com/assets/1328499/10122312/edf337c8-654f-11e5-845f-8222972bdb22.png)

詳細検索結果：
2015-09-25, 2015-09-26のみのものがヒットする（2015-09-27, 28 のものがヒットしていない。）　→　OK
![image](https://cloud.githubusercontent.com/assets/1328499/10122326/8551544c-6550-11e5-9432-c68d5615e8b2.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 1c640d3)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 e6b1415)
  * enju_library (0.1.0.pre44 536bd54)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
