### ISSUE TITLE
提案：書誌と所蔵のTSVインポートでの「削除」機能はなしにしてはどうか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#788]
基本、書誌や所蔵を大量に「削除」することってないような気がする。
結構、危険な機能だし、この機能はなしにしたらどうだろうか？

http://dev.next-l.jp/resource_import_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/10123478/6f4f61f0-6575-11e5-9445-81623977ec8f.png)

所蔵の大量の「除籍」はあるだろうけど、
これは、1冊づつ、ピッピと検収の逆バージョンをがあればよい気もするし、
更新機能で事足りるようなきがする。

と、 @masao さんと議論したので、忘れないうちに登録しておきます。

**Comment by yegusa** [comment]
#805 #806 のように、できないようなので、いっそのこと、[削除]機能は削除していいのでは？
とりあえず、1.1.0 では、　削除　ラジオボタンだけでも消しておくとか。

**Comment by yegusa** [comment]
除籍機能が充実してきたってのも理由の一つ。

**Comment by yegusa** [comment]
メモ：
* 書誌の削除は「manifestaion_id」ではできなかった #805
* 書誌の削除は「manifestation_identifier」ではできなかった #806
* 所蔵の削除は「item_id」ではできなかった。
* 所蔵の削除は「item_identifier」を使えばできた。

![image](https://cloud.githubusercontent.com/assets/1328499/10171840/15e3b44c-6717-11e5-928b-3cf8ca20a29c.png)

<pre>
item_identifier
123002
</pre>

を、TSVインポートの[削除]で、インポート

所蔵が削除できた。
![image](https://cloud.githubusercontent.com/assets/1328499/10171869/325413b0-6717-11e5-90fb-6bfd20c2e42c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by nabeta** [comment]
事故防止という意味では、「削除」を選択できるようにするのはよいと思います。

> とりあえず、1.1.0 では、　削除　ラジオボタンだけでも消しておくとか。

削除ボタンをコメントアウトしておき、どうしても実行したい場合は、Webブラウザの開発ツールでフォームをいじってボタンを有効にするのでよさそうです。

**Comment by yegusa** [comment]
出来ていることを確認しました。クローズします。

最初は削除ボタンない：
![image](https://cloud.githubusercontent.com/assets/1328499/10412134/12042296-6fb7-11e5-9c6d-7720f2a6314c.png)

Webブラウザの開発ツールでフォームをいじって、コメントをはずす
![image](https://cloud.githubusercontent.com/assets/1328499/10412142/5150bc5c-6fb7-11e5-85e6-3bf8f5a946c8.png)

削除ボタンがあらわれた！
![image](https://cloud.githubusercontent.com/assets/1328499/10412146/73194598-6fb7-11e5-8131-111a53a1bcb6.png)

削除実行
![image](https://cloud.githubusercontent.com/assets/1328499/10412122/c0e1e6aa-6fb6-11e5-9215-16b33a6a40e2.png)

  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
