### ISSUE TITLE
所蔵の編集画面：借りられている本を除籍できてしまう（借りた状態のまま、除籍処理されてしまう）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#790]
- [ ] 確認
- [ ] マニュアル修正 #1191 
#506 から派生したissueです。

借りた状態のまま、除籍処理されてしまう。
借りた状態のものは、「除籍」しようとしたら、
「この本は借りられています。返却処理をしてから除籍してください」
というようなエラーをだして、除籍できないようにするべき。

借りる前：
![image](https://cloud.githubusercontent.com/assets/1328499/10126479/702a2be2-65ce-11e5-8e36-fc860c722ef1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126739/bd0b1a08-65d2-11e5-9e96-1354ed2599ea.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126757/ebee4836-65d2-11e5-8053-b1c71046d18b.png)

借りた後：
http://dev.next-l.jp/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/10126710/390d22f0-65d2-11e5-8860-7662da76d5ef.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126530/15c08d80-65cf-11e5-8253-5a8ddb4c6534.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126724/6e5077c8-65d2-11e5-86ef-1ebb07e641b1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126786/1e41c326-65d3-11e5-9afe-922eb7380736.png)

除籍処理する
![image](https://cloud.githubusercontent.com/assets/1328499/10126840/bb59c8a2-65d3-11e5-959a-26b8fc0b0c92.png)

除籍処理した後
![image](https://cloud.githubusercontent.com/assets/1328499/10126847/d698813a-65d3-11e5-81c7-f09e64eb99d1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126855/f07ee3be-65d3-11e5-856b-eeaa6186ee8a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10126866/0f34de30-65d4-11e5-8a43-3c6b55430e9f.png)

開発サーバーで確認しました。 http://dev.next-l.jp/
enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by nabeta** [comment]
@yegusa 除籍メニューが別にできたので、この画面で「除籍済み」を選択できないようにするのがよいと思うのですが、いかがでしょうか。

**Comment by nabeta** [comment]
このケースは貸し出されたまま紛失->除籍、に相当しませんでしょうか。実際には返却されていないのに返却処理をするのは不自然だと思います。

**Comment by yegusa** [comment]
返却されたのに，返却処理されていなかった本という可能性もあるかと思います。

**Comment by nabeta** [comment]
予約されている場合は貸出状態に「除籍済み」を選択しようとするとエラーにするようにしました。
https://enju.next-l.jp/items/7443
<img width="518" alt="スクリーンショット 2019-12-22 1 10 13" src="https://user-images.githubusercontent.com/11428/71310469-dd31bb00-2457-11ea-9443-51f624bb9eb9.png">

**Comment by masao** [comment]
修正を確認しました。クローズします。

**Comment by yegusa** [comment]
マニュアル修正については https://github.com/next-l/enju_leaf/issues/791#issuecomment-821947041 を参照のこと
