### ISSUE TITLE
所蔵の編集画面：予約の「取置済み」の本を除籍できてしまう（予約の「取置済み」状態のまま、除籍処理されてしまう）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#791]
- [ ] 確認
- [ ] マニュアル修正 #1191 
#506 から派生したissueです。
#790 と類似です。

予約の「取置済み」状態のまま、所蔵情報の編集画面で、除籍処理されてしまう。
「取置済み」状態のものは、「除籍」しようとしたら、
「この本は予約の取置済み状態となっています。」
というようなエラーをだして、除籍できないようにするべき。

「取り置き」状態じゃなくて、在架「予約」の場合は、
書誌に予約がついているから、処理がむずかしそうだけど、
これも、できたら必要かも。
が、まずは、このissueでは、「取置済み」のみ対象とします。

取り置き済み資料
![image](https://cloud.githubusercontent.com/assets/1328499/10126964/c5b6b592-65d5-11e5-862f-ac7280190a2f.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10127687/43b9e792-65e1-11e5-82bf-23cde1a6dca6.png)

除籍できてしまう。
![image](https://cloud.githubusercontent.com/assets/1328499/10126974/f86e0152-65d5-11e5-8552-2ec75bc80e53.png)

予約状態のまま
![image](https://cloud.githubusercontent.com/assets/1328499/10126983/1d6f7f8a-65d6-11e5-9d80-31b0bf16ce08.png)

開発サーバーで確認しました。 http://dev.next-l.jp/
enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by nabeta** [comment]
> 「取り置き」状態じゃなくて、在架「予約」の場合は、
> 書誌に予約がついているから、処理がむずかしそうだけど、
> これも、できたら必要かも。

状態にかかわらず、完了していない予約がかかっていたら除籍不可でよい気がします。

**Comment by nabeta** [comment]
予約されている場合は貸出状態に「除籍済み」を選択しようとするとエラーにするようにしました。詳細は以下のissueのコメントを参照してください。
https://github.com/next-l/enju_leaf/issues/790#issuecomment-568192407

**Comment by masao** [comment]
取り置き済みになっている所蔵についても、除籍機能がうごいてしまいますね。
ちょっとまだバグが残っている状態のようです。

**Comment by yegusa** [comment]
@nabeta さんはテストを書いて、確認してみたが、再現できず。
@masao が再現する方法を提示する。　Enju WS 20200517より。

**Comment by masao** [comment]
再現手順：連続除籍機能を使った場合に除籍できてしまいます。

**Comment by nabeta** [comment]
以下のコミットで、「取り置き済み」を予約完了と扱っていたのを修正しました。
https://github.com/next-l/enju_circulation/commit/e80a70831cd8db65270128a913e5b8d4782646bd

以下の資料（所蔵番号1002）は取り置き状態になっています。
https://enju.next-l.jp/manifestations/12613

これを除籍しようとすると、以下のエラーになります。
![image](https://user-images.githubusercontent.com/11428/82138490-c7d08980-985b-11ea-8e56-e3977513d8f5.png)

**Comment by masao** [comment]
除籍処理できなくなったことを確認しました。クローズします。

**Comment by yegusa** [comment]
編集場所：

https://next-l.github.io/manual/1.3/enju_operation_4.html#section4-5

4-5-1 の4 のコラムを修正　（連続除籍について）
4-5-2　にコラムを↑のをまねて修正（所蔵の編集画面について）

**Comment by yegusa** [comment]
文言案「【Memo】次のようなエラーが出た場合は、「貸出中」や「取り置き中」などのように除籍してはいけない状態の場合は、除籍できないようになっています。」に修正。

**Comment by yegusa** [comment]
4-5-2 画像： https://user-images.githubusercontent.com/11428/71310469-dd31bb00-2457-11ea-9443-51f624bb9eb9.png
