### ISSUE TITLE
「資料の受入」メニューの「除籍」を削除して、「システムの設定」の「資料」に移動

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#792]
#506 からの派生です。

「資料の受入」メニューの「検収」の下に「除籍」があると、
検収と間違えて除籍しそうなので危険だし、
除籍はめったににないので、
「システムの設定」の「資料」に「除籍」へのリンクがあるのがいいと思います。

「資料の受入」メニューの「除籍」を削除：
![image](https://cloud.githubusercontent.com/assets/1328499/10127244/9e30a43e-65d9-11e5-8f06-0770fd866230.png)

イメージ（かわりに、「システムの設定」の「資料」に「除籍」へのリンクを）：
http://dev.next-l.jp/page/configuration
![image](https://cloud.githubusercontent.com/assets/1328499/10127276/fdfddb02-65d9-11e5-92b1-6e0314d73ad1.png)

enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10134151/b3a789dc-661e-11e5-8710-65b8578f5ee1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10134178/dbd1607c-661e-11e5-9faa-31b9c3fda7ff.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 fc5959b)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
