### ISSUE TITLE
除籍画面をつかって、予約取置済み資料が、除籍できてしまう（予約の「取置済み」状態のまま、除籍処理されてしまう）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#794]
- [ ] 確認
- [ ] マニュアル修正 #1191 
#506 からの派生で、 #791 と類似です。

取り置き済みの資料が：
![image](https://cloud.githubusercontent.com/assets/1328499/10127829/63399228-65e3-11e5-8a46-9e4b0c8c7e7f.png)

除籍機能で、除籍できてしまう　→ NG
http://dev.next-l.jp/withdraws/new
![image](https://cloud.githubusercontent.com/assets/1328499/10127842/9e4cbf0c-65e3-11e5-8e92-5181e78db906.png)

予約の情報も残ったまま　→ NG
![image](https://cloud.githubusercontent.com/assets/1328499/10127846/b1dd0fe0-65e3-11e5-8c1a-6b1733a37834.png)

開発サーバーで確認しました
enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by nabeta** [comment]
取り置き済みかどうかにかかわらず、予約がかかっている状態での除籍をできないようにしました。

**Comment by masao** [comment]
残念ながら、予約がかかった状態の資料を除籍することができました。
![image](https://user-images.githubusercontent.com/38825/63220742-f9cb9700-c1c8-11e9-810a-6202d4833bce.png)
![image](https://user-images.githubusercontent.com/38825/63220741-f59f7980-c1c8-11e9-85f1-4eebffa1c1db.png)

**Comment by nabeta** [comment]
予約がかかった資料を除籍できないようにしました。デモサーバに反映済みで、所蔵番号"098"で試してみてください。
https://enju.next-l.jp/items/7443
![image](https://user-images.githubusercontent.com/11428/71307000-86ae8780-242b-11ea-9f89-f6dcc6317c28.png)

**Comment by masao** [comment]
除籍できない制限がかかることを確認しました。クローズします。

**Comment by yegusa** [comment]
マニュアル修正については https://github.com/next-l/enju_leaf/issues/791#issuecomment-821947041 を参照のこと
