### ISSUE TITLE
除籍画面を使って、貸出中の資料が、除籍処理できてしまう（借りた状態のまま、除籍処理されてしまう）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#795]
- [x] 確認
- [ ] マニュアル修正 #1191

#506 からの派生で、 #790 と類似です。

貸出中の資料： 333001
![image](https://cloud.githubusercontent.com/assets/1328499/10127881/6337fcfa-65e4-11e5-8c13-77eea6656ad2.png)

除籍画面で除籍処理できちゃう  http://dev.next-l.jp/withdraws/new → NG
![image](https://cloud.githubusercontent.com/assets/1328499/10127888/890e0ac8-65e4-11e5-8150-92e72a6b6cce.png)

貸出状態が残っている→ NG
![image](https://cloud.githubusercontent.com/assets/1328499/10127894/afa79dfc-65e4-11e5-8e7f-ed0def15bd53.png)

開発サーバーで確認しました
enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by nabeta** [comment]
まずエラーにするようにしました。あとは「この資料は貸出中です」というエラーメッセージを追加します。

**Comment by yegusa** [comment]
手元の仮想マシンで確認しましたので、クローズします。
マニュアルはあとで修正します。

> あとは「この資料は貸出中です」というエラーメッセージを追加します。
はできてないですが、べつissue にします。

少なくとも、貸出中の資料は、エラーがでて、できないことを確認しましたので、
まあ、とりあえずクローズにします。

貸出中の 0001 を除籍しようとしたところエラーがでてできない： 
![image](https://cloud.githubusercontent.com/assets/1328499/18812806/8799da42-831a-11e6-8863-f27dd2ba6045.png)

参考：検索結果一覧
![image](https://cloud.githubusercontent.com/assets/1328499/18812774/03f4dffc-831a-11e6-9df6-8250b56f11e5.png)

貸出中でない資料を除籍はできる
![image](https://cloud.githubusercontent.com/assets/1328499/18812786/524c4e6a-831a-11e6-9b66-54f47db0fd2a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
