### ISSUE TITLE
「除籍の新規作成」画面の「戻る」がおかしい（「除籍の一覧」にすべき）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#797]
「除籍の新規作成」画面の「戻る」をたどると、
「除籍の一覧」にいくので、アンカーを「戻る」から「除籍の一覧」に変えるべき

http://localhost:8080/withdraws/new
![image](https://cloud.githubusercontent.com/assets/1328499/10130619/03acc24a-6605-11e5-989b-baa4acaed394.png)

http://localhost:8080/withdraws
![image](https://cloud.githubusercontent.com/assets/1328499/10130656/4009f668-6605-11e5-86b2-e92150cd7333.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 fc5959b)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 41bb292)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
この手のラベルはあちこちにありますね。。。

**Comment by yegusa** [comment]
ですねえ。でも、気づいたところからメモらないと忘れるので。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10168488/04c2c216-6708-11e5-9b52-57d1774a065d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 afe70bf)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
除籍の1.1.0のマニュアルはまだ整備していないので、そのときに、スクリーンショットを一緒に差し替える予定です。
