### ISSUE TITLE
「検収の新規作成」画面の「戻る」がおかしい（「検収の一覧」にすべき）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#798]
「検収の新規作成」画面の「戻る」をたどると、
「検収の一覧」にいくので、アンカーを「戻る」から「検収の一覧」に変えるべき

http://localhost:8080/accepts/new
![image](https://cloud.githubusercontent.com/assets/1328499/10130774/1e0b88be-6606-11e5-9066-fa934c99fec3.png)

http://localhost:8080/accepts
![image](https://cloud.githubusercontent.com/assets/1328499/10130794/2ff43788-6606-11e5-8653-7b3ce69d88a1.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 fc5959b)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 41bb292)
  * enju_library (0.1.0.pre44 36d8dae)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
修正しました。確認願います。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10166315/69b0d168-66fe-11e5-8a52-f4ab88e5808f.png)

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10166939/5509602e-6701-11e5-8751-ad004f0c572e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 60daeff)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 8c4d2c1)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
