### ISSUE TITLE
メールサーバの設定がない状態でパスワードを忘れましたか？を使うと、「検索サーバに不具合があるようです」が出る

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#799]
たぶん、何かの設定が必要かと思いますが、やり方がわかりません
- [x] 有効にする方法（メールサーバーの設定？など）の説明を教える　→ @nabeta 
- [x] ↑の確認
- [ ] マニュアル修正 #1191
- [x] 別issue #809 へ<s>検索サーバーに不具合があるのではないのでは？　→　エラーメッセージを変える</s>
- [x] 別issue #809 へ<s>↑の確認</s>

![image](https://cloud.githubusercontent.com/assets/1328499/10154386/9a0b7870-66a1-11e5-9c80-fdfe4ccfab86.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10154449/42026160-66a2-11e5-9b9d-8a06eccd2116.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10154432/1a0fb05e-66a2-11e5-92a3-7814e93e13ff.png)

参考：
利用者情報に登録されていないメールアドレスを入れた場合は、以下のメッセージになる。
（このメッセージもなんか変だとは思いますが）
![image](https://cloud.githubusercontent.com/assets/1328499/10154486/c4e30b48-66a2-11e5-82a6-c94cd9fb2cf2.png)

**Comment by masao** [comment]
手元では、このエラーは出ず、通常のログイン画面に戻って、「パスワードを再設定する手順についてのメールが数分のうちに届きます。」というメッセージになります。メールサーバの設定をしていないからメール届かないんだけど。。。

**Comment by yegusa** [comment]
ほほう！プロキシ環境だとちがうのかも！

**Comment by yegusa** [comment]
ログです

226294a226295,226334
> I, [2015-09-29T12:20:27.885810 #1145]  INFO -- : Started POST "/users/password" for 127.0.0.1 at 2015-09-29 12:20:27 +0000
> I, [2015-09-29T12:20:27.889308 #1145]  INFO -- : Processing by Devise::PasswordsController#create as HTML
> I, [2015-09-29T12:20:27.892399 #1145]  INFO -- :   Parameters: {"utf8"=>"?肴???"}henticity_token"=>"kwnwAub/7xC1CMjXgpI1L6Q65dmCbMn8ZpEi3oTO6dxT1IbDJw1Kmuwy4gVVLdCtCSLOJz9EA7e> D, [2015-09-29T12:20:27.898614 #1145] DEBUG -- :   LibraryGroup Load (1.3ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-29T12:20:27.899833 #1145] DEBUG -- : Cache read: available_languages
> D, [2015-09-29T12:20:27.901610 #1145] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-09-29T12:20:27.911463 #1145] DEBUG -- :   User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["email", "xxxx@xxxx.xx.jp"]]
> D, [2015-09-29T12:20:27.921422 #1145] DEBUG -- :   User Load (0.6ms)  SELECT  "users".* FROM "users" WHERE "users"."reset_password_token" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["reset_password_token", "4e92b6bc55415c25482400d02bd0842997efb96fc2ac1cb56c04959775ffb9fe"]]
> D, [2015-09-29T12:20:27.925969 #1145] DEBUG -- :    (0.3ms)  begin transaction
> D, [2015-09-29T12:20:27.936799 #1145] DEBUG -- :   Role Load (1.0ms)  SELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ? LIMIT 1  [["user_id", 16]]
> D, [2015-09-29T12:20:27.949300 #1145] DEBUG -- :   SQL (0.7ms)  UPDATE "users" SET "reset_password_token" = ?, "reset_password_sent_at" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["reset_password_token", "4e92b6bc55415c25482400d02bd0842997efb96fc2ac1cb56c04959775ffb9fe"], ["reset_password_sent_at", "2015-09-29 12:20:27.924223"], ["updated_at", "2015-09-29 12:20:27.942200"], ["id", 16]]
> D, [2015-09-29T12:20:27.961744 #1145] DEBUG -- :    (7.8ms)  commit transaction
> I, [2015-09-29T12:20:27.972197 #1145]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-9ad63879c233/app/views/devise/mailer/reset_password_instructions.html.erb (1.3ms)
> D, [2015-09-29T12:20:27.975198 #1145] DEBUG -- :
> Devise::Mailer#reset_password_instructions: processed outbound mail in 11.9ms
> I, [2015-09-29T12:20:27.993671 #1145]  INFO -- :
> Sent mail to xxxx@xxxx.xx.xx (17.8ms)
> D, [2015-09-29T12:20:27.994629 #1145] DEBUG -- : Date: Tue, 29 Sep 2015 12:20:27 +0000
> From: please-change-me-at-config-initializers-devise@example.com
> Reply-To: please-change-me-at-config-initializers-devise@example.com
> To: xxxx@xxxx.xx.xx
> Message-ID: <560a820befd27_479b8996c40090@vagrant-ubuntu-trusty-64.mail>
> Subject: Reset password instructions
> Mime-Version: 1.0
> Content-Type: text/html;
>  charset=UTF-8
> Content-Transfer-Encoding: 7bit
>
> <p>Hello xxxx@xxxx.xx.xx!</p>
>
> <p>Someone has requested a link to change your password, and you can do this through the link below.</p>
>
> <p><a href="http://localhost:3000/users/password/edit?reset_password_token=4e92b6bc55415c25482400d02bd0842997efb96fc2ac1cb56c04959775ffb9fe">Change my password</a></p>
>
> <p>If you didn't request this, please ignore this email.</p>
> <p>Your password won't change until you access the link above and create a new one.</p>
>
> F, [2015-09-29T12:20:27.995191 #1145] FATAL -- : please confirm that the Solr is running.
> I, [2015-09-29T12:20:27.999190 #1145]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_leaf-9ad63879c233/app/views/page/500_nosolr.html.erb (1.1ms)
> I, [2015-09-29T12:20:27.999857 #1145]  INFO -- : Completed 500 Internal Server Error in 107ms (Views: 3.3ms | ActiveRecord: 12.4ms | Solr: 0.0ms)
vagrant@vagrant-ubuntu-trusty-64:~/enju$

**Comment by nabeta** [comment]
メールサーバに通信できていないためにエラーになっていると思うのですが、現在のenju_leafでは、　Errno::ECONNREFUSEDエラーをSolr用のエラー画面表示メソッド(render_500_nosolr)で処理しています。Errno::ECONNREFUSEDエラーはSolrに限らず、外部のサービスに接続できなかったときに起こる一般的なエラーなので、まとめて「Solrのエラー」と表示するのは具合が悪そうです。
https://github.com/next-l/enju_leaf/blob/1.1/lib/enju_leaf/controller.rb#L13

**Comment by nabeta** [comment]
問題の解決とは直接関係しませんが、この手のカスタマイズされたエラー処理をモジュール内に記述すると、今回のようにデバッグが難しくなってしまいます。エラー処理のカスタマイズは、app/controllers/application_controller.rbなどに記述（もしくはインストールスクリプトで追加）し、必要に応じて各自で有効・無効を設定できるようにすべきだと思います。

**Comment by masao** [comment]
@nabeta さん指摘の件は #809 に切り分けました。こちらではパスワードリセット用のメール送信設定の問題を扱いましょう。

**Comment by nabeta** [comment]
以下を参考に、パスワードリセットのメールを非同期で送信するようにしました。
https://github.com/plataformatec/devise#activejob-integration

1.2系で試していただけますでしょうか。

**Comment by yegusa** [comment]
確かめ方がわかりません。

**Comment by nabeta** [comment]
どのサーバで確かめる予定ですか？（仮想マシン、開発サーバなど）

**Comment by yegusa** [comment]
仮想マシンでも、開発サーバでも確かめられればどっちでもいいですが。できれば仮想マシンかなあ。

**Comment by yegusa** [comment]
現在のステータス：

- 私は確かめ方がわかりません

**Comment by nabeta** [comment]
メールサーバの設定のマニュアルを書く。
https://next-l.github.io/manual/1.2/enju_install_vm_4.html#section4-4-3

**Comment by yegusa** [comment]
Todo: マニュアルは書かれたようですので、動かしてチェクする

**Comment by masao** [comment]
エラーが出なくなることを確認したのでクローズします。
