### ISSUE TITLE
パスワードの再発行の画面で、利用者情報に登録されていないメールアドレスを入れた場合のメッセージが変

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#800]
#799 からの派生です。

利用者情報に登録されていないメールアドレスを入れた場合のメッセージが変。
「利用者情報に登録されていないメールアドレスです」あたりでしょうか。

* [ ] メッセージを修正
* [ ] ↑の確認

![image](https://cloud.githubusercontent.com/assets/1328499/10154386/9a0b7870-66a1-11e5-9c80-fdfe4ccfab86.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10154449/42026160-66a2-11e5-9b9d-8a06eccd2116.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10154486/c4e30b48-66a2-11e5-82a6-c94cd9fb2cf2.png)

**Comment by masao** [comment]
翻訳メッセージがない状態だったようなので、追加しました。
「メールアドレスは登録されていません。」と表示されます。

**Comment by yegusa** [comment]
確認しました。
「利用者アカウント を保存するときに1個のエラーが発生しました:」って文言も変じゃないですか？
これは直せない？

![image](https://cloud.githubusercontent.com/assets/1328499/10301065/9770e954-6c39-11e5-85ab-b3f147af9da3.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 f1ee759)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 b5fe7fa)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
同じメッセージをパスワード変更画面でも使っています。それ以外では見当たらないようですので、どちらも齟齬がないメッセージでしたら変更可能かなと思います。
「利用者アカウントの情報にn個のエラーがあります」あたりでしょうか。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10337891/bf9a6af4-6d3d-11e5-8023-f5267ac1af72.png)

**Comment by yegusa** [comment]
それいいですね！いいと思います。

**Comment by masao** [comment]
変更しました。確認願います。

**Comment by yegusa** [comment]
いいですね！確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10343391/91cc31dc-6d58-11e5-81cd-a1f068aa039b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f4799e7)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
