### ISSUE TITLE
提案：「資料のインポート用ファイルの表示」と「資料インポートの結果の一覧」が一画面にあるとよいのでは

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#802]
TSVファイル全体のエラーが分かる画面（資料のインポート用ファイルの表示）
一行づつの結果が分かる画面（資料インポートの結果の一覧）が
一緒になっていると、ぱっとエラーやインポートできていない行などがわかって
とても便利だと思う。
（利用者、催し物のインポートも同様）

イメージ：
![image](https://cloud.githubusercontent.com/assets/1328499/10156835/b7a8e728-66bf-11e5-9169-5f6a4fd24518.png)

現在：　ここで、右メニューの「インポートの結果」をクリックすると
http://localhost:8080/resource_import_files/5
![image](https://cloud.githubusercontent.com/assets/1328499/10156869/26eb8d8e-66c0-11e5-873e-4d0d8d0f28eb.png)

「インポートの結果の一覧」がでてくる。
http://localhost:8080/resource_import_results?resource_import_file_id=5
![image](https://cloud.githubusercontent.com/assets/1328499/10156877/3b99636e-66c0-11e5-8310-ba19e72ef771.png)

**Comment by masao** [comment]
先にユーザ情報のインポートの部分を変更してみました。

**Comment by masao** [comment]
書誌・所蔵情報のインポート結果も一緒に表示するように変更しました。 enju_biblio モジュールを更新してください。

**Comment by yegusa** [comment]
確認しましたので、クローズします。

* 右メニューの「資料インポートの結果」を消した（同じ画面にするので）
* 右メニューに　Resqueを追加（他のにあわせて？）
* Content-Type はファイル名の横にカッコ書きで表示するようにした
* ファイルのハッシュは表示しないようにした（必要なさそうだから？）

という変更もしたんですね。

![image](https://cloud.githubusercontent.com/assets/1328499/10212620/c9964fd8-683c-11e5-81fe-e8894917852e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3047ed9)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 751e750)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
マニュアルのスクリーンショットの差し替えなどは、まだ、1.1.0の最終確認のときにまとめてやります。
