### ISSUE TITLE
書誌を更新したときに、インポートの結果になにもでません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#804]
以下のようなTSVファイルで更新としたときに、
<pre>
manifestation_id	note
32	zzz
</pre>

更新はちゃんとされています。

インポートの結果になにもでません
http://dev.next-l.jp/resource_import_results?resource_import_file_id=161
![image](https://cloud.githubusercontent.com/assets/1328499/10158021/0909d2f8-66ca-11e5-90d5-277689fcfd93.png)

enju_biblio: 0.1.0.pre69
enju_circulation: 0.1.0.pre48
enju_event: 0.1.17.pre26
enju_flower: 0.1.0.pre23
enju_leaf: 1.1.0.rc21
enju_library: 0.1.0.pre44
enju_manifestation_viewer: 0.1.0.pre19
enju_message: 0.1.14.pre25
enju_ndl: 0.1.0.pre37
enju_oai: 0.1.0.pre19
enju_subject: 0.1.0.pre33

**Comment by yegusa** [comment]
> ついでに、（新規作成時はあったのですが）、更新時には、資料インポートの結果の情報が保存されていなかったので、それを保存するように機能追加してあります。
https://github.com/next-l/enju_leaf/issues/472#issuecomment-144975356

**Comment by yegusa** [comment]
少なくとも、資料が表示されませんね。
![image](https://cloud.githubusercontent.com/assets/1328499/10250872/637d5854-6968-11e5-9cbf-89f76e2c7e00.png)

詳細の方には表示されますが。
![image](https://cloud.githubusercontent.com/assets/1328499/10250896/77ebd6a8-6968-11e5-995b-4822378d8a83.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 35b86f3)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
新規作成の時もできなくなってますね。
あと、所蔵もでした。
あと、新規作成では、一行目は、ヘッダがでる仕様になってます。そろえたほうがいいかなと。
![image](https://cloud.githubusercontent.com/assets/1328499/10251083/6656c0dc-6969-11e5-8595-6dba833e1f18.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10251096/85b20e14-6969-11e5-9e2f-297480bd8f54.png)

**Comment by masao** [comment]
修正しました。ヘッダも出すようにしました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10253189/f69d101c-6976-11e5-92e4-91a0fd3fb677.png)

**Comment by yegusa** [comment]
メモ：

$ hisotory

  473  bundle update
  474  sudo restart enju_leaf

この時点では、 

![image](https://cloud.githubusercontent.com/assets/1328499/10261035/570804c2-69c0-11e5-81ce-d0a9967cab11.png)

状態でしたが、

  475  ps aux|less
  476  redis-server
  477  less Procfile
  478  enju_leaf
  479  sudo stop enju_leaf
  480  ps aux|less
  481  sudo stop redis-server
  482  ps aux
  483  cd /etc/
  484  find . -type f|xargs grep enju
  485  less init/enju_leaf.conf
  486  less init/enju_leaf-resque.conf \
  487  less init/enju_leaf-resque-1.conf
  488  ls
  489  find . -type f|xargs grep enju
  490  cd
  491  cd enju/
  492  sudo stop enju_leaf-resque
  493  sudo start enju_leaf
  494  ps aux
  495  ps aux|less
  496  less Gemfile
  497  history
vagrant@vagrant-ubuntu-trusty-64:~/enju$

というコマンドをやったら、

![image](https://cloud.githubusercontent.com/assets/1328499/10261042/839e3ede-69c0-11e5-9574-f263b97c8b15.png)

と正しくできるようになりました。

$ sudo restart enju_leaf

だけだとうまく、反映されないときがあるんですね。
restart で、うまくいくことが大半だったので知りませんでした。
上でやったどれが有効にきいたのかはわかりませんが、
キーは、

  492  sudo stop enju_leaf-resque
  493  sudo start enju_leaf

↑あたり？

とりあえず共有しておきます。

**Comment by yegusa** [comment]
正しくできるようになったことを確認しましたので、クローズします。

更新
![image](https://cloud.githubusercontent.com/assets/1328499/10261174/85d40ce2-69c5-11e5-8476-27e143c917f5.png)

新規
![image](https://cloud.githubusercontent.com/assets/1328499/10261173/7da22b80-69c5-11e5-95d8-709972ffc63b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 9f33908)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
