### ISSUE TITLE
「資料インポートの結果の一覧」リンクのさきがWe're sorry に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#808]
http://localhost:8080/resource_import_results/35
![image](https://cloud.githubusercontent.com/assets/1328499/10169473/3308e994-670c-11e5-8b76-0bfc3000587b.png)

http://localhost:8080/resource_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/10169500/4f17fdd2-670c-11e5-9861-65538d83c5ee.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 afe70bf)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
log/production.log です。

220232a220233,220383
> I, [2015-09-29T15:45:36.038482 #2302]  INFO -- : Started GET "/resource_import_results" for 127.0.0.1 at 2015-09-29 15:45:36 +0000
> I, [2015-09-29T15:45:36.041110 #2302]  INFO -- : Processing by ResourceImportResultsController#index as HTML
> D, [2015-09-29T15:45:36.047475 #2302] DEBUG -- :   User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 15]]
> D, [2015-09-29T15:45:36.051671 #2302] DEBUG -- :   LibraryGroup Load (0.3ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-29T15:45:36.052975 #2302] DEBUG -- : Cache read: available_languages
> D, [2015-09-29T15:45:36.054711 #2302] DEBUG -- : Cache fetch_hit: available_languages
> D, [2015-09-29T15:45:36.103477 #2302] DEBUG -- :   Role Load (0.8ms)  SELECT  "roles".* FROM "roles" INNER JOIN "user_has_roles" ON "roles"."id" = "user_has_roles"."role_id" WHERE "user_has_roles"."user_id" = ? LIMIT 1  [["user_id", 15]]
> D, [2015-09-29T15:45:36.105762 #2302] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-29T15:45:36.108126 #2302] DEBUG -- :   CACHE (0.1ms)  SELECT  "library_groups".* FROM "library_groups" WHERE "library_groups"."id" = ? LIMIT 1  [["id", 1]]
> D, [2015-09-29T15:45:36.249882 #2302] DEBUG -- :   ResourceImportFile Load (0.9ms)  SELECT  "resource_import_files".* FROM "resource_import_files" WHERE "resource_import_files"."id" IS NULL  ORDER BY resource_import_files.id DESC LIMIT 1
> D, [2015-09-29T15:45:36.263764 #2302] DEBUG -- :   ResourceImportResult Load (1.1ms)  SELECT  "resource_import_results".* FROM "resource_import_results"  ORDER BY resource_import_results.id LIMIT 10 OFFSET 0
> D, [2015-09-29T15:45:36.280096 #2302] DEBUG -- :   ResourceImportFile Load (0.6ms)  SELECT  "resource_import_files".* FROM "resource_import_files" WHERE "resource_import_files"."id" = ?  ORDER BY resource_import_files.id DESC LIMIT 1  [["id", 1]]
> I, [2015-09-29T15:45:36.361782 #2302]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/views/resource_import_results/_list.html.erb (101.0ms)
> I, [2015-09-29T15:45:36.362295 #2302]  INFO -- :   Rendered vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/views/resource_import_results/index.html.erb within layouts/application (106.9ms)
> I, [2015-09-29T15:45:36.363325 #2302]  INFO -- : Completed 500 Internal Server Error in 322ms (ActiveRecord: 4.3ms)
> F, [2015-09-29T15:45:36.386732 #2302] FATAL -- :
> ActionView::Template::Error (undefined method `resource_import_file_name' for nil:NilClass):
>      9: <% @resource_import_results.each do |resource_import_result| %>
>     10:   <tr class="line<%= cycle("0", "1") -%>">
>     11:     <td>
>     12:       <%= link_to resource_import_result.resource_import_file.resource_import_file_name, resource_import_result.resource_import_file %>
>     13:       <br />
>     14:       <%=l resource_import_result.created_at %>
>     15:       <br />
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/views/resource_import_results/_list.html.erb:12:in `block in _vendor_bundle_ruby_______bundler_gems_enju_biblio_afe__bf_e_c__app_views_resource_import_results__list_html_erb___3991928004434322440_89386160'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/relation/delegation.rb:46:in `each'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/views/resource_import_results/_list.html.erb:9:in `_vendor_bundle_ruby_______bundler_gems_enju_biblio_afe__bf_e_c__app_views_resource_import_results__list_html_erb___3991928004434322440_89386160'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:339:in `render_partial'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:310:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/partial_renderer.rb:309:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:47:in `render_partial'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/helpers/rendering_helper.rb:35:in `render'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/views/resource_import_results/index.html.erb:7:in `_vendor_bundle_ruby_______bundler_gems_enju_biblio_afe__bf_e_c__app_views_resource_import_results_index_html_erb__4003032824928300286_61267260'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:145:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:333:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/template.rb:143:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/template_renderer.rb:14:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:42:in `render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/renderer/renderer.rb:23:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:100:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/streaming.rb:217:in `_render_template'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:83:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/renderers.rb:37:in `render_to_body'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/rendering.rb:25:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:16:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
>   /usr/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/core_ext/benchmark.rb:12:in `ms'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/sunspot_rails-2.2.0/lib/sunspot/rails/railties/controller_runtime.rb:15:in `cleanup_view_runtime'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:43:in `render'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/mime_responds.rb:215:in `respond_to'
>   vendor/bundle/ruby/2.2.0/bundler/gems/enju_biblio-afe70bf8e7c9/app/controllers/resource_import_results_controller.rb:13:in `index'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:198:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rendering.rb:10:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:115:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/callbacks.rb:19:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rescue.rb:29:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `block in instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:164:in `instrument'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/abstract_controller/base.rb:137:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionview-4.2.3/lib/action_view/rendering.rb:30:in `process'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:196:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_controller/metal.rb:237:in `block in action'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:45:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:43:in `block in serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `each'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/journey/router.rb:30:in `serve'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:821:in `call'
>   vendor/bundle/ruby/2.2.0/gems/fix_microsoft_links-0.1.4/lib/fix_microsoft_links.rb:18:in `call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
>   vendor/bundle/ruby/2.2.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:25:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/flash.rb:260:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/cookies.rb:560:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/query_cache.rb:36:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.3/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:84:in `run_callbacks'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
>   vendor/bundle/ruby/2.2.0/gems/request_store-1.2.0/lib/request_store/middleware.rb:8:in `call'
>   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
>   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
>   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
>   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580:in `process_client'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674:in `worker_loop'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529:in `spawn_missing_workers'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140:in `start'
>   vendor/bundle/ruby/2.2.0/gems/unicorn-4.9.0/bin/unicorn:126:in `<top (required)>'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `load'
>   vendor/bundle/ruby/2.2.0/bin/unicorn:23:in `<main>'

**Comment by nabeta** [comment]
インポート元のファイルを削除しましたでしょうか？

**Comment by nabeta** [comment]
ひとまず、元ファイルのレコードが削除されていてもエラーにはならないようにしました。

**Comment by yegusa** [comment]
> インポート元のファイルを削除しましたでしょうか？

↓の黄緑四角のID1～3のインポートファイルのタスク（？）を削除したかって意味なら YES
当該ID 12 のインポートタスク（？）を削除したかって意味なら NO

http://localhost:8080/resource_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/10169877/0f366792-670e-11e5-913f-bacf13669e35.png)

http://localhost:8080/resource_import_files/12
![image](https://cloud.githubusercontent.com/assets/1328499/10169907/26a5e1d2-670e-11e5-8f8e-923b8af7b40e.png)

http://localhost:8080/resource_import_results?resource_import_file_id=12
![image](https://cloud.githubusercontent.com/assets/1328499/10169936/433675fa-670e-11e5-8e9f-4da3eb604fd1.png)

http://localhost:8080/resource_import_results/35
![image](https://cloud.githubusercontent.com/assets/1328499/10169962/59bd6b4e-670e-11e5-857d-fb93cead3827.png)

http://localhost:8080/resource_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/10170056/72a7a368-670e-11e5-82c1-7e3d029ff1ce.png)

**Comment by yegusa** [comment]
あー、 a) ってことね？　過去の全部のをみてるのね。
だから、削除したら、We're sorry になると。

とりあえず、　このissueの主旨のものはWe're sorry にならなくなったので、クローズします。

http://localhost:8080/resource_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/10170495/1c1bff6a-6710-11e5-9f7a-2ec9ffd4788e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
