### ISSUE TITLE
Solr起動エラー表示がSolr以外のエラーでも表示されてしまう

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#809]
#799 からの派生。#587 で導入したエラー処理は一般的な接続エラー全般の例外を拾っているため、Solr以外の外部サービスに接続できかった場合のエラーも「検索サーバに接続できません」エラーとして表示されてしまう。

Ref: 
https://github.com/next-l/enju_leaf/issues/799#issuecomment-144091805
https://github.com/next-l/enju_leaf/issues/799#issuecomment-144090043

**Comment by nabeta** [comment]
メール送信時にErrno::ECONNREFUSEDを捕捉して別のエラーを出す、というのが解決策でしょうか。

**Comment by nabeta** [comment]
@masao こちら、現状でもSolrとSolr以外のエラーで区別ができず、Errno::ECONNREFUSEDエラーが全部「Solrの起動を確認してください」というエラー画面になります。これはそもそもエラー内容として誤っている上、区別する対応も難しいので、Solrの起動エラー時も通常のエラーを出すように戻させてください。

**Comment by masao** [comment]
はい、戻す方向で進めてよいとおもいます

**Comment by nabeta** [comment]
マージ済みのため、クローズします。
