### ISSUE TITLE
「資料インポートの結果の一覧」の[表示]リンクをたどるとWe're sorryに

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#810]
#808 からの派生です。
原因はおなじところからきていると思われる。

この[表示]リンクをたどると We're sorry になる。

http://localhost:8080/resource_import_results
![image](https://cloud.githubusercontent.com/assets/1328499/10170603/a9ef01ac-6710-11e5-97b9-a053d520c2ce.png)

TSVインポートのタスクを削除した結果の[表示]リンクをクリックすると起きる問題と思われる。
 （↓の黄緑四角のID1～3のインポートファイルのタスク（？）の結果の[表示]）

http://localhost:8080/resource_import_files
![image](https://cloud.githubusercontent.com/assets/1328499/10169877/0f366792-670e-11e5-913f-bacf13669e35.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
修正しました。
既に画面遷移の方針を変えている（#814）ので、あまり意味はないかもしれませんが、念のため。

**Comment by yegusa** [comment]
なんか、いろいろかっこ悪くて、直したいところがあるけど、
まあ、とりあえず、いいですよね。
すくなくとも We're sorry にならなくなることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10261280/b6a15898-69ca-11e5-8ebd-2d1feef6040b.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10261270/8f0fd048-69ca-11e5-85a6-afdf33cc7f61.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10261273/9dee8050-69ca-11e5-9461-e1dd34ba4e78.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5c30f86)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 644c3cb)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
