### ISSUE TITLE
書誌と所蔵のTSVエクスポートでmanifestation_identifierを出力してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#811]
所蔵との更新などで利用のニーズは高いと思う。

現在出力されている項目：

* manifestation_id
* original_title
* creator
* publisher
* pub_date
* price
* isbn
* iss_itemno
* issn
* issn_l
* jpno
* ncid
* item_identifier
* call_number
* item_price
* acquired_at
* bookstore
* budget_type
* circulation_status
* shelf
* library

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
できることを確認しました。
マニュアルも修正しました。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10369410/0b3c8334-6e15-11e5-89cb-46d499ecacda.png)

現在出力：
accepted_at
acquired_at
bookstore
budget_type
call_number
circulation_status
creator
isbn
iss_itemno
issn
issn_l
item_created_at
item_id
item_identifier
item_price
item_updated_at
jpno
lccn
library
manifestation_created_at
manifestation_id
manifestation_identifier
manifestation_price
manifestation_updated_at
ncid
original_title
pub_date
publisher
shelf

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c562fe6)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 574817f)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
