### ISSUE TITLE
CiNii書誌インポートの追加リンクをNDLサーチのに合わせる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#812]
* [x] 追加ボタンにする
* [x] 保存中ボタンを用意する
* [ ] 確認

![image](https://cloud.githubusercontent.com/assets/1328499/10181594/2cb13864-6755-11e5-8627-e9794831d34a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10181608/6245fe92-6755-11e5-8b5a-a4d8814884f4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 9ad6387)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。
（マニュアルはスクリーンショットなどないので、修正する箇所はないです）

![image](https://cloud.githubusercontent.com/assets/1328499/10261362/e91d705a-69ce-11e5-8a00-30d35c881a95.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5c30f86)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 644c3cb)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
