### ISSUE TITLE
米国議会図書館による書誌インポートの追加リンクをNDLのに合わせる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#813]
#812 と類似

* [x] 追加ボタンにする
* [x] 保存中ボタンを用意する
* [x] 確認する

![image](https://cloud.githubusercontent.com/assets/1328499/10181716/834edd42-6756-11e5-8789-a2d5bcc2957b.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10181713/77c642da-6756-11e5-85c4-bc90d5ae3f2f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bbb009a)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 dac45f4)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre4)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
変更しました。
ついでに、ページを開いたさいに検索フォームにフォーカスが出ていなかったので、そちらもNDLモジュールにあわせて修正しました。

**Comment by yegusa** [comment]
spss で検索したら、ぐるぐるまわって、最終的にはこんな画面になる。
とりあえず、報告。

![image](https://cloud.githubusercontent.com/assets/1328499/10192044/5503b1c0-67b4-11e5-83e1-c9290d9b7bc2.png)

**Comment by yegusa** [comment]
仮想マシンで確認しました。 クローズします。
#812 もよろしく！

（504がでるのはプロキシ環境のみですので、別にissueたてます。）

![image](https://cloud.githubusercontent.com/assets/1328499/10196944/5a0c157e-67d0-11e5-8dc8-a826f7ceafee.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3047ed9)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 751e750)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
