### ISSUE TITLE
提案：「利用者のインポート用ファイルの表示」と「利用者インポートの結果の」が一画面にあるとよいのでは

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#814]
#802 と類似

* [x] 開発
* [ ] 確認
 
![image](https://cloud.githubusercontent.com/assets/1328499/10196561/705cb326-67ce-11e5-9ccf-d90192500550.png)

**Comment by yegusa** [comment]
https://github.com/next-l/enju_leaf/issues/802#issuecomment-144285311

> 先にユーザ情報のインポートの部分を変更してみました。

とあるので、あとは確認のみ。

**Comment by yegusa** [comment]
id は表示するように戻してください。

![image](https://cloud.githubusercontent.com/assets/1328499/10212698/c47ec7d6-683d-11e5-8f90-a31fbd3b635a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3047ed9)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 751e750)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
Id表示を戻しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。

* 右メニューの「資料インポートの結果」を消した（同じ画面にするので）
* Content-Type はファイル名の横にカッコ書きで表示するようにした
* ファイルのハッシュは表示しないようにした（必要なさそうだから？）

という変更もしたんですね。

![image](https://cloud.githubusercontent.com/assets/1328499/10222032/cad6ce54-688c-11e5-963c-e14b20c0612e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)
