### ISSUE TITLE
提案：「催し物のインポート用ファイルの表示」と「催し物インポートの結果の」が一画面にあるとよいのでは

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#815]
#802 と類似
- [ ] 開発
- [ ] 確認

a) 
![image](https://cloud.githubusercontent.com/assets/1328499/10196737/50d821c4-67cf-11e5-841d-6f321aa8e774.png)

b) 
![image](https://cloud.githubusercontent.com/assets/1328499/10196749/61871fac-67cf-11e5-994a-5e061c62e0f2.png)

a) と b) を一画面にする。

**Comment by nabeta** [comment]
資料(next-l/enju_leaf#1080)・ユーザ(next-l/enju_leaf#1079)のインポートと同じ画面構成にしました。
https://enju.next-l.jp/event_import_results
<img width="931" alt="スクリーンショット 2019-12-22 18 25 02" src="https://user-images.githubusercontent.com/11428/71320114-3d713d00-24ea-11ea-8009-fc7a8c6612aa.png">

https://enju.next-l.jp/event_import_files/10
<img width="721" alt="スクリーンショット 2019-12-22 18 36 24" src="https://user-images.githubusercontent.com/11428/71320116-3d713d00-24ea-11ea-8379-ce8b8bbb0136.png">

**Comment by masao** [comment]
個別のインポート結果のTSV出力ですが、ヘッダ行が末尾に出力されてしまっているようです。
![image](https://user-images.githubusercontent.com/38825/74599593-f5c0f900-50c7-11ea-9bb7-fcc90581a8de.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
