### ISSUE TITLE
資料の受入→TSVファイルからのインポートの編集モード「関連を更新」のボタンを削除

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#817]
#119 からの派生です。

* [ ] ボタンの削除
* [ ] 確認
* [ ] マニュアルの更新

機能していないボタンのようですので、削除が必要かと思います。

http://localhost:8080/resource_import_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/10212537/c288192a-683b-11e5-99df-ecac21f6b4d9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3047ed9)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 751e750)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
コードを読んでみた限りでは、所蔵に対応する書誌を付け替えたいときに使う機能のようです。

**Comment by yegusa** [comment]
じゃあ、やっぱり、残しておきますか？

**Comment by yegusa** [comment]
詳細は、 #119 に書きましたが、動いているようですね。
というわけで、このissueはやらないことにして、クローズします。
