### ISSUE TITLE
提案：NDLサーチインポートの画面に同じキーワードでNDLサービスを探すリンクをつけてはいかが？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#818]
![image](https://cloud.githubusercontent.com/assets/1328499/10212863/3b1c1f9a-6840-11e5-96f5-897b8b922c52.png)

赤四角か、黄緑四角の位置に、

「同じ検索語でNDLサーチを検索した結果に移動する」

というようなリンクをつくって、
それをクリックすると、例えばこの例だと、以下が表示されるイメージ：
http://iss.ndl.go.jp/books?any=%E7%B5%B1%E8%A8%88&op_id=1&ar=4e1f

いっぱいヒットしすぎたときに、便利かなって。
思いついたので挙げておきます。

CiNii や、 LOCのも同様にできるね。

参考：http://iss.ndl.go.jp/books?any=%E7%B5%B1%E8%A8%88&op_id=1&ar=4e1f
![image](https://cloud.githubusercontent.com/assets/1328499/10212891/a75def3a-6840-11e5-82b2-e83b3cb3e0b8.png)

**Comment by masao** [comment]
提案の通り、リンクを加えてみました。
![ndl](https://cloud.githubusercontent.com/assets/38825/13421817/0d4023d0-dfd4-11e5-9163-6e6dd8c49aed.png)

**Comment by yegusa** [comment]
現在のステータス：

- 確認してクローズする（私でもできそう）

**Comment by yegusa** [comment]
できることを確認しましたのでクローズします。マニュアルは後で書きます。

![image](https://cloud.githubusercontent.com/assets/1328499/14765472/115350ea-0a1e-11e6-8bb6-4754f6448ab1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/14765474/2be0834c-0a1e-11e6-8e21-badd4b3a3036.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a366e5d)
  * enju_circulation (0.2.0.beta.1 b8a143d)
  * enju_event (0.2.0.beta.1 ab338e3)
  * enju_leaf (1.2.0.beta.1 d5e2c12)
  * enju_library (0.2.0.beta.1 bd46d17)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 afc79ce)
  * enju_ndl (0.2.0.beta.1 f142a0b)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 5d33e0a)

**Comment by yegusa** [comment]
マニュアルの修正しました。

4-2-4 NDLサーチを検索して1件ずつ登録する
https://next-l.github.io/manual/1.2/enju_operation_4.html#section4-2-4

の 3. のスクリーンショットを差し替え、
右メニューの「同じ検索語でNDLサーチを検索する」の説明を追加。
