### ISSUE TITLE
書誌と所蔵ののTSVエクスポートで、所蔵の作成日、更新日を出力してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#822]
* [x] 作成日
* [x] 更新日

確認したときに出力された項目：

manifestation_id
original_title
creator
publisher
pub_date
price
isbn
iss_itemno
issn
issn_l
jpno
lccn
ncid
item_identifier
call_number
item_price
acquired_at
bookstore
budget_type
circulation_status
shelf
library

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 bd58902)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 3047ed9)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 751e750)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
所蔵の更新日については、 #796 にも関係

**Comment by masao** [comment]
普通に考えるとRails上の属性（テーブル列名）としては created_at, updated_at なので、エクスポートデータの列名としては書誌と所蔵で別の名前にする必要がある。

a) いずれもモデル名を付けて区別する
* manifestation_created_at
* manifestation_updated_at
* item_created_at
* item_updated_at

b) 書誌と所蔵の片方だけモデル名を付けて区別する
* created_at （書誌データ分）
* updated_at （書誌データ分）
* item_created_at
* item_updated_at

**Comment by masao** [comment]
よく見ると price は b案ですね： price （書誌の定価）と item_price （購入価格） になっている。

**Comment by yegusa** [comment]
でも、 a 案がいい気がする。TSVインポートでは使わないしね。

**Comment by yegusa** [comment]
> よく見ると price は b案ですね： price （書誌の定価）と item_price （購入価格） になっている。

これ、まぎらわしいなあと思っていたのです。

**Comment by yegusa** [comment]
TSVインポートでは、 manifestation_price ってなってますね。

**Comment by masao** [comment]
うーん、ならば、エクスポートのほうも manifestation_price に変えますかねえ。エクスポートしたものをそのままインポートに使えないですし。。。

**Comment by masao** [comment]
もともとの改善案も a) 案でいいですかね。まぎらわしくないし。

**Comment by yegusa** [comment]
> もともとの改善案も a) 案でいいですかね。まぎらわしくないし。

はい。 a) 案でいきましょう。

> うーん、ならば、エクスポートのほうも manifestation_price に変えますかねえ。エクスポートしたものをそのままインポートに使えないですし。。。

ですね、エクスポートも、manifestation_price にしましょう。

**Comment by masao** [comment]
機能を追加しました。

**Comment by yegusa** [comment]
所蔵の作成日と更新日が出力されているのを確認しました。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10246477/ba93bfe6-694c-11e5-943d-a040b349646a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c848b5c)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 cf567bd)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by yegusa** [comment]
マニュアル修正済み
