### ISSUE TITLE
書誌詳細画面で、 .txt とすると、TSVエクスポートできるとうれしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#825]
http://localhost:8080/manifestations/56.txt

とやると、その画面の書誌と所蔵のTSVデータが表示される（ダウンロードできる）と
便利そうだな～と。

ジャストアイデアですが、わすれないように書いておきます。

**Comment by nabeta** [comment]
詳細画面にTSVへのリンクを追加しました。
http://dev.next-l.jp/manifestations/24403

**Comment by yegusa** [comment]
仮想マシンでできるようになったことを確認しましたので、クローズします。

http://localhost:8080/manifestations/82.txt
![image](https://cloud.githubusercontent.com/assets/1328499/10411873/ea25d484-6fae-11e5-97e8-55e452562fc8.png)

Excelに読み込んだところ
![image](https://cloud.githubusercontent.com/assets/1328499/10411876/f39c08d0-6fae-11e5-8237-7cbd0bdf2732.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
