### ISSUE TITLE
図書館詳細画面の職員一覧は閲覧制限すべき

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#826]
図書館詳細画面に職員タブがあるが、これが非ログイン状態でも閲覧できてしまうので、閲覧制限を加えたほうがよい。
http://enju.next-l.jp/libraries/kiri#tab2

* [ ] 開発
* [ ] 確認
* [ ] マニュアルスクリーンショット差し替え

cf. [FAQ: ユーザの参照権限](https://github.com/next-l/enju_leaf/wiki/FAQ#%E3%83%A6%E3%83%BC%E3%82%B6%E3%81%AE%E6%A8%A9%E9%99%90%E5%8F%82%E7%85%A7%E6%A8%A9%E9%99%90%E3%81%A8%E5%AE%9F%E9%9A%9B%E3%81%AB%E3%81%A7%E3%81%8D%E3%82%8B%E3%81%93%E3%81%A8%E3%81%AE%E9%96%A2%E4%BF%82%E3%81%8C%E3%82%8F%E3%81%8B%E3%82%8A%E3%81%BE%E3%81%9B%E3%82%93)

**Comment by nabeta** [comment]
開発サーバに反映済みです。
http://dev.next-l.jp/libraries/kiri#tab2

**Comment by masao** [comment]
確認しました。

一般ユーザに対しても閲覧不可にしたほうがよいと思われます。
あと、閲覧不可の場合はタブごと表示しないようにしたほうがまぎらわしくないので良いように思います。

**Comment by nabeta** [comment]
職員タブの表示はLibrarian権限を必要とするようにしました。
http://dev.next-l.jp/libraries/kiri

**Comment by masao** [comment]
確認しましたのでクローズします。

非ログインの場合：
![next l enju leaf_3](https://cloud.githubusercontent.com/assets/38825/10337646/2967599e-6d3c-11e5-9331-129f6ccc11e4.png)
一般ユーザの場合：
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10337668/4eb35bd0-6d3c-11e5-8bae-974e389bc017.png)
管理者の場合：
![next l enju leaf_2](https://cloud.githubusercontent.com/assets/38825/10337663/4394128a-6d3c-11e5-8218-1ffcc13c5bd7.png)
