### ISSUE TITLE
[戻る]リンクを消す：「ISBNインポートのリクエストの新規作成」

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#827]
http://localhost:8080/import_requests/new
![image](https://cloud.githubusercontent.com/assets/1328499/10266776/c609a29a-6ab0-11e5-96cd-dcac5509a2e5.png)

[ISBNインポートのリクエストの一覧] とおなじリンク先を示しているため、
重複するので[戻る]の方を消す必要あり

* [ ] 開発
* [ ] 確認
* [ ] マニュアルスクリーンショットの差し替え 　image_operation_108.png
* [ ] マニュアルスクリーンショットの差し替え 　image_operation_109_2.png

マニュアル該当箇所： http://next-l.github.io/manual/enju_operation_4.html#section4-2-3

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 5c30f86)
  * enju_circulation (0.1.0.pre48 f2990c3)
  * enju_event (0.1.17.pre26 c80072c)
  * enju_flower (0.1.0.pre23 d7be6c4)
  * enju_leaf (1.1.0.rc21 5518578)
  * enju_library (0.1.0.pre44 9da4893)
  * enju_loc (0.1.0.pre5 25731b9)
  * enju_manifestation_viewer (0.1.0.pre19 fd9f9a2)
  * enju_message (0.1.14.pre25 57ef135)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 644c3cb)
  * enju_oai (0.1.0.pre19 279fdcd)
  * enju_purchase_request (0.1.0.pre14 50ecdc2)
  * enju_subject (0.1.0.pre33 0870847)

**Comment by masao** [comment]
厳密に言うと、「戻る」リンクのほうは直前の遷移元のページへのリンクなので、重複ではないはず。
紛らわしいので消すのでもよいとは思いますが。。。

**Comment by yegusa** [comment]
あら、そうでしたか。じゃあ、とりあえず、なにもしなくていいです。なにもしないということで、クローズします。
（この[戻る]リンクいるかなあ？とはおもいますけど、
ある画面とない画面があったりして統一感ないし、
restなんだから、ブラウザの戻るでいいじゃんという気はする）
