### ISSUE TITLE
[資料を追加する] リンクを　[手動で資料を追加する]にする（「ISBNインポートのリクエストの新規作成」画面）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#828]
http://localhost:8080/import_requests/new
![image](https://cloud.githubusercontent.com/assets/1328499/10266788/da1a2876-6ab1-11e5-8dbb-d9def5ada7d5.png)

[資料を追加する] リンクを　[手動で資料を追加する]にする
（メニューの書き方と合わせる）

* [x] 開発
* [x] 確認
* [ ] マニュアルスクリーンショットの差し替え 　image_operation_108.png
* [ ] マニュアルスクリーンショットの差し替え 　image_operation_109_2.png

マニュアル該当箇所： http://next-l.github.io/manual/enju_operation_4.html#section4-2-3

参考：メニュー[手動で資料を追加する]
![image](https://cloud.githubusercontent.com/assets/1328499/10266792/0d9dd13e-6ab2-11e5-8c8b-f766dd21ef07.png)

**Comment by nabeta** [comment]
ラベルを「手動で資料を追加する」としました。
http://dev.next-l.jp/import_requests/new

**Comment by yegusa** [comment]
@nabeta さん、開発ありがとうございます。
開発おわたったらコメント書くのはいいかんじです。今後も継続よろしく。

開発終わったら、milestone 替えて、checking ラベルつけてくださいな。
コメントだけじゃチャックしわすれることあるんで。
よろしく～。

**Comment by yegusa** [comment]
確認しました。マニュアルはまだだけど、とりあえず、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10283563/0f8d3e8a-6bbb-11e5-9f46-28602993de8b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e2cbee5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 79cb7c2)
  * enju_library (0.1.0.pre44 b5fe7fa)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
マニュアルも更新しておきました。
