### ISSUE TITLE
LCインポートにおいてLCCN番号のインポートが完全一致になっていない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#830]
lccn=93028401 をインポートしようとすると

http://lccn.loc.gov/93028401 ではなく、
http://lccn.loc.gov/sv93028401 をインポートしてしまうバグがある。

**Comment by masao** [comment]
完全一致検索が効かないので、前方一致検索で実装するように変更しました。

**Comment by masao** [comment]
※インポート検索画面で 

```
bath.lccn=93028401
```

とすると、該当部分を検索することが出来ます。
確認願います。

**Comment by yegusa** [comment]
一応確認ですが、lccn だけは前方一致にということですか？

**Comment by masao** [comment]
はい、取り込み時の検索式を
```
bath.lccn=93028401
```
から
```
bath.lccn=^93028401
```
に変更して、前方一致とするように変更しました。

**Comment by yegusa** [comment]
できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10283781/24aaf798-6bbc-11e5-961d-045af8250e56.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10283820/566b0796-6bbc-11e5-9cd6-817c12230ab0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 e2cbee5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 79cb7c2)
  * enju_library (0.1.0.pre44 b5fe7fa)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
