### ISSUE TITLE
検索結果一覧の右メニューに「書き出し」リンクを追加してはどうか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#832]
### 書き出し
* TSVで表示
* JSONで表示
* RDFで表示
* XMLで表示
* MODSで表示
* SRU で表示

↓の赤四角のあたりに、↑を追加するかんじ。
![image](https://cloud.githubusercontent.com/assets/1328499/10305426/013896ae-6c5b-11e5-997b-584bbf507abe.png)

CiNii の例
![image](https://cloud.githubusercontent.com/assets/1328499/10305370/d2ecc770-6c5a-11e5-9aa5-b425f0723b35.png)

* [x] 書き出しタイトル
* [x] TSVで表示
* [ ] <s>JSONで表示</s> #855 の後に
* [x] RDFで表示
* [ ] <s>XMLで表示</s> #856 の後に
* [x] MODSで表示
* [ ] <s>SRU で表示</s> これは書き出しとも違うのでひとまずなしにします by @yegusa

**Comment by nabeta** [comment]
ひとまずRDF/XML, MODS, TSVを追加しました。
http://dev.next-l.jp/manifestations?utf8=✓&query=&commit=検索

**Comment by yegusa** [comment]
赤四角の位置に「書き出し」を追記願います。

![image](https://cloud.githubusercontent.com/assets/1328499/10412169/fe0bc388-6fb7-11e5-8a68-462f1743934f.png)

検索結果のフィード
![image](https://cloud.githubusercontent.com/assets/1328499/10412182/65029d5a-6fb8-11e5-8f55-690809689330.png)

RDF/XML
![image](https://cloud.githubusercontent.com/assets/1328499/10412195/d159c47e-6fb8-11e5-80cb-9fbcb7dd91f3.png)

MODS
![image](https://cloud.githubusercontent.com/assets/1328499/10412184/73592a18-6fb8-11e5-9ea3-694fd5356fde.png)

TSV
![image](https://cloud.githubusercontent.com/assets/1328499/10412189/83d5372e-6fb8-11e5-9dcb-bdbff6effbd2.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
「書き出し」としました。
http://dev.next-l.jp/manifestations?utf8=✓&query=&commit=検索

**Comment by yegusa** [comment]
書き出しになっていることは確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/10421816/df7f1012-70ea-11e5-86fa-f7801a48d75e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 549e848)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 48b4dbb)
  * enju_library (0.1.0.pre44 58b609e)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
@masao さんとも話し合いましたが、
#855 #856 ができたら、json, xml を追加するってことにしましょう。

ってことで、クローズします。

（本来なら、こんな状態なら、そもそも、json, xml をできないようにしておくべきだと個人的にはおもいますが）
