### ISSUE TITLE
資料詳細の右メニューに「書き出し」リンクを追加してはどうか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#833]
#832 と類似です。

### 書き出し

* JSONで表示
* RDFで表示
* XMLで表示
* MODSで表示

↓の赤四角のあたりに、↑を追加するかんじ。
![image](https://cloud.githubusercontent.com/assets/1328499/10305559/bec94f38-6c5b-11e5-9451-7f070088ac06.png)

CiNii の例
![image](https://cloud.githubusercontent.com/assets/1328499/10305370/d2ecc770-6c5a-11e5-9aa5-b425f0723b35.png)

* [x] 書き出しタイトル
* [x] TSVで表示
* [ ] JSONで表示
* [x] RDFで表示
* [ ] XMLで表示
* [x] MODSで表示

**Comment by nabeta** [comment]
書き出しリンクを追加しました。
http://dev.next-l.jp/manifestations/24409

ただ、現状ではJSONとXMLはRailsのto_jsonメソッドを単純に呼んでいるだけなので、一般ユーザに見せたくない項目も含まれているかもしれません。RDF/XMLとMODSだけにしたいのですが、いかがでしょうか。

**Comment by yegusa** [comment]
> ただ、現状ではJSONとXMLはRailsのto_jsonメソッドを単純に呼んでいるだけなので、一般ユーザに見せたくない項目も含まれているかもしれません。RDF/XMLとMODSだけにしたいのですが、いかがでしょうか。

いやです。JSONもXMLも欲しいです。
いままでだってあったんだし。（認知はされてなかっただろうけど）

あと、「エクスポート」を「書き出し」に変更願います。

**Comment by nabeta** [comment]
「書き出し」としました。
http://dev.next-l.jp/manifestations/24400

**Comment by yegusa** [comment]
書き出しになっていることは確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/10421856/0744c492-70ec-11e5-8fdd-8c3dae778868.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 549e848)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 48b4dbb)
  * enju_library (0.1.0.pre44 58b609e)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
@masao さんとも話し合いましたが、
#855 #856 ができたら、json, xml を追加するってことにしましょう。

ってことで、クローズします。

（本来なら、こんな状態なら、そもそも、json, xml をできないようにしておくべきだと個人的にはおもいますが）
