### ISSUE TITLE
検索結果一覧の.txt の最初の列と2列目の区切りが空白になっている

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#834]
他の列はタブなので、おかしいのでは？

http://localhost:8080/manifestations.txt?utf8=%E2%9C%93&query=&commit=%E6%A4%9C%E7%B4%A2
<pre>
manifestation_identifier  original_title	creator	publisher	isbn	pub_date	note
2524120 "How to lie with statistics"	Huff, Darrell.	Norton	["9780393310726"]	1993	
http://iss.ndl.go.jp/books/R100000002-I000007320885-00 "心理臨床大事典"	氏原, 寛, 1929-	培風館	["9784563056803"]	2004-04	
 "RailsによるアジャイルWebアプリケーション開発"			["9784274068669"]		特になし
 "「赤毛のアン」の秘密"			[]	2014	
 "村岡花子と赤毛のアンの世界"			[]	2013	
http://iss.ndl.go.jp/books/R100000002-I024314335-00 "オープンサイエンス革命"	Nielsen, Michael A, 1974-; 高橋, 洋, 1960-	紀伊國屋書店	["9784314011044"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024389775-00 "Yコンビネーター : シリコンバレー最強のスタートアップ養成スクール"	Stross, Randall E, 1954-; 滑川, 海彦, 1952-; 高橋, 信夫	日経BP社; 日経BPマーケティング	["9784822249465"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024460787-00 "書籍文化の未来 : 電子本か印刷本か"	赤木, 昭夫, 1932-	岩波書店	["9784002708737"]	2013-06	
http://iss.ndl.go.jp/books/R100000002-I024270759-00 "東日本大震災希望の種をまく人びと"	寺島, 英弥, 1957-	明石書店	["9784750337654"]	2013-03	
http://iss.ndl.go.jp/books/R100000002-I000011154026-00 "iPhone英語勉強法"	松本, 秀幸	日本実業出版社	["9784534048066"]	2011-03	

</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 f1ee759)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 b5fe7fa)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
直しました。
http://dev.next-l.jp/manifestations.txt

**Comment by yegusa** [comment]
ヘッダはタブになりましたが、2行目以下は空白のままです。

<pre>
manifestation_identifier	original_title	creator	publisher	isbn	pub_date	note
2524120 "How to lie with statistics"	Huff, Darrell.	Norton	["9780393310726"]	1993	
http://iss.ndl.go.jp/books/R100000002-I000007320885-00 "心理臨床大事典"	氏原, 寛, 1929-	培風館	["9784563056803"]	2004-04	
 "RailsによるアジャイルWebアプリケーション開発"			["9784274068669"]		特になし
 "「赤毛のアン」の秘密"			[]	2014	
 "村岡花子と赤毛のアンの世界"			[]	2013	
http://iss.ndl.go.jp/books/R100000002-I024314335-00 "オープンサイエンス革命"	Nielsen, Michael A, 1974-; 高橋, 洋, 1960-	紀伊國屋書店	["9784314011044"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024389775-00 "Yコンビネーター : シリコンバレー最強のスタートアップ養成スクール"	Stross, Randall E, 1954-; 滑川, 海彦, 1952-; 高橋, 信夫	日経BP社; 日経BPマーケティング	["9784822249465"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024460787-00 "書籍文化の未来 : 電子本か印刷本か"	赤木, 昭夫, 1932-	岩波書店	["9784002708737"]	2013-06	
http://iss.ndl.go.jp/books/R100000002-I024270759-00 "東日本大震災希望の種をまく人びと"	寺島, 英弥, 1957-	明石書店	["9784750337654"]	2013-03	
http://iss.ndl.go.jp/books/R100000002-I000011154026-00 "iPhone英語勉強法"	松本, 秀幸	日本実業出版社	["9784534048066"]	2011-03	
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2368f15)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
修正しました。
http://dev.next-l.jp/manifestations.txt

**Comment by yegusa** [comment]
できることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10327312/d83adf9c-6ce0-11e5-9832-ba6a674bf3d7.png)

<pre>
manifestation_identifier	original_title	creator	publisher	isbn	pub_date	note
http://iss.ndl.go.jp/books/R100000002-I000008558828-00	"ゼロからわかる確率・統計 : 100%文系の人のための数学読本"	深川, 和久, 1952-	ベレ出版	["9784860641535"]	2007-05	
2524120	"How to lie with statistics"	Huff, Darrell.	Norton	["9780393310726"]	1993	
http://iss.ndl.go.jp/books/R100000002-I000007320885-00	"心理臨床大事典"	氏原, 寛, 1929-	培風館	["9784563056803"]	2004-04	
	"RailsによるアジャイルWebアプリケーション開発"			["9784274068669"]		特になし
	"「赤毛のアン」の秘密"			[]	2014	
	"村岡花子と赤毛のアンの世界"			[]	2013	
http://iss.ndl.go.jp/books/R100000002-I024314335-00	"オープンサイエンス革命"	Nielsen, Michael A, 1974-; 高橋, 洋, 1960-	紀伊國屋書店	["9784314011044"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024389775-00	"Yコンビネーター : シリコンバレー最強のスタートアップ養成スクール"	Stross, Randall E, 1954-; 滑川, 海彦, 1952-; 高橋, 信夫	日経BP社; 日経BPマーケティング	["9784822249465"]	2013-04	
http://iss.ndl.go.jp/books/R100000002-I024460787-00	"書籍文化の未来 : 電子本か印刷本か"	赤木, 昭夫, 1932-	岩波書店	["9784002708737"]	2013-06	
http://iss.ndl.go.jp/books/R100000002-I024270759-00	"東日本大震災希望の種をまく人びと"	寺島, 英弥, 1957-	明石書店	["9784750337654"]	2013-03	
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
マニュアルも修正しておきました。
