### ISSUE TITLE
メールアドレスを登録している&メールサーバーを設定していると何が起きますか？

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#835]
パスワードを忘れたときにメールで仮パスワードを送る機能が使える

以外になにがありますか？
予約の取り置きのメールのお知らせがくるようになりますか？

その他なにがありますか？

マニュアルに書きたいので、教えてください。

**Comment by nabeta** [comment]
上記のふたつに加えて、以下の情報をメールで受け取ることができます。

- 書誌詳細（「書誌情報を電子メールで送信する」リンク）  
http://dev.next-l.jp/manifestations/24409
- インポート・エクスポート・利用統計の集計の完了通知

**Comment by yegusa** [comment]
ありがとうございます。マニュアルにも書きましたので、クローズします。

**Comment by yegusa** [comment]
> 予約の取り置きのメールのお知らせがくるようになりますか？

これ、うそですね。こないですね。
予約をしたというメールは来ましたが、とり置いたというメールは来ませんね。

issueに挙げておきます。
