### ISSUE TITLE
利用者権限でログインしたときに、関係のないメニューがでる「資料の受入」

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#836]
利用者権限でログインしたときに、関係のないメニューがでる「資料の受入」
![image](https://cloud.githubusercontent.com/assets/1328499/10336736/f609f5a8-6d35-11e5-8aa7-3f48d417a95c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
ここは、enju_bookmarkモジュールを読み込んでいるとブックマーク一覧へ遷移できるメニューになっているようです。これをどうするか要検討でしょうか。
![next l enju leaf_2](https://cloud.githubusercontent.com/assets/38825/10337429/792f88c2-6d3a-11e5-886d-4b07ccbfaa88.png)

**Comment by yegusa** [comment]
* 標準だと、「資料の受入」メニューは表示しない
* ブックマークモジュールをインストールしていたら、「資料の受入」がでてきて、「ブックマークの一覧」がでてくる

ようにすればいいのでは？

**Comment by masao** [comment]
とりあえずそうしてみましょうかね。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
出来ていることを確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10443487/be813cbc-7196-11e5-859a-27ed9e3cbe8b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
