### ISSUE TITLE
利用者権限でログインしたときに、関係のないメニューがでる「システムの設定」

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#837]
#836 と類似です。

利用者権限でログインしたときに、関係のないメニューがでる「システムの設定」

![image](https://cloud.githubusercontent.com/assets/1328499/10336790/4ced6aee-6d36-11e5-9f85-98ffd7c34e21.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f62e996)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
単純にタグのネストのミスマッチだったようです。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/10337265/92fdc6e8-6d39-11e5-9c96-ca84753e2c87.png)
空メニューがでるのは治しましたが。。。

**Comment by yegusa** [comment]
[アカウント]リンクあるから、[アカウント管理]って、いらないとおもうんですよね。
なので、[システム管理]メニューもいらないと思います。

**Comment by nabeta** [comment]
ユーザ権限でのログイン時や非ログイン時は「システム管理」メニューを表示しないようにしました。
http://dev.next-l.jp

**Comment by yegusa** [comment]
確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10412283/1ded5bc2-6fbc-11e5-82fc-7a795e067f38.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
