### ISSUE TITLE
Enju Leaf本体のインストール時のテンプレート取得でopensslのエラーが起きる（起きた）

### ISSUE THREAD

**Issue by adamasharpe** [next-l/enju_leaf#84]
Mac（Lion）でのインストールの際、
rails _3.2.14_ new your_enju -m https://gist.github.com/5357321.txt -d [データベースの種類]
で

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)

となりましたが、以下の

http://stackoverflow.com/questions/4528101/ssl-connect-returned-1-errno-0-state-sslv3-
read-server-certificate-b-certificat

から

brew install curl-ca-bundle
cp /usr/local/Cellar/curl-ca-bundle/1.87/share/ca-bundle.crt /usr/local/etc/openssl/cert.pem

で当該エラーは解消しました。（別のNokogiriのエラーに当たりましたが）
ご報告します。

**Comment by nabeta** [comment]
どこに追記したか思い出せません…が、現時点でHomebrewのcurl-ca-bundleパッケージは削除されています。かわりにopensslパッケージを使うようです。
https://github.com/Homebrew/legacy-homebrew/pull/28658

**Comment by nabeta** [comment]
古いissueのため、closeします。
