### ISSUE TITLE
予約の「受付済み」や「取置済み」に[削除]リンクが表示され削除できてしまう & [取消]リンクが表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#840]
![image](https://cloud.githubusercontent.com/assets/1328499/10339163/f1cabcd4-6d44-11e5-8844-f79136040953.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 59ae1b8)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
ちなみに、有効期限を設定すると、[削除]リンクが消えて、[取消]リンクがでるようです。

![image](https://cloud.githubusercontent.com/assets/1328499/10339389/fe74d932-6d45-11e5-8d9c-fcd194411198.png)

**Comment by masao** [comment]
#674 の修正の影響のようです。予約の有効期限日が入力されていない状態でも、予約受付中の状態とみなすように修正しました。

**Comment by yegusa** [comment]
早速ありがとうございます。
できることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10343191/a5b9e92e-6d57-11e5-956d-8bfd1ba2bfb9.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f4799e7)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
