### ISSUE TITLE
User権限でログインしたときの「貸出一覧」の右メニューの順序やレイアウトの変更を提案します

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#841]
予約ありのファセットの区切りがわかりにくいので、
以下のように、してはどうでしょうか？

イメージ：

* 図書: 2 / 10
* 予約

### 予約あり

* いいえ (3)
* この絞り込みを解除する

### 書き出し

* RSS 
* TSV 

![image](https://cloud.githubusercontent.com/assets/1328499/10342028/2f4ab0e8-6d52-11e5-846c-02f4f72bccc1.png)

**Comment by nabeta** [comment]
「書き出し」を追加しました。

**Comment by yegusa** [comment]
書き出しがつかされたのは確認しました。[予約]リンクの位置は変なままです。

![image](https://cloud.githubusercontent.com/assets/1328499/10461977/01912168-7217-11e5-962a-b6d210a26c64.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 e9145d5)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
予約リンクを移動しました。

**Comment by yegusa** [comment]
予約リンクが移動したのは確認しました。
「全ての貸出」という新しいリンクが出現していますが、これはなんですか？
付けた理由を教えて下さい。

![image](https://cloud.githubusercontent.com/assets/1328499/10472895/cb206bee-7260-11e5-8732-a2dc9b6e4b0c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 5e6e472)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
このリンクはLibrarian権限でのみ表示されるものですが、誤って一般ユーザでも表示されるようになっていました。修正済みです。

**Comment by yegusa** [comment]
確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10502269/3ac0928e-7325-11e5-9ce1-c8efd9effb4d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 dbb73a0)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
