### ISSUE TITLE
予約の「有効期限」を設定しないと、予約機能がもろもろおかしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#842]
#674 の影響と思われます。

たとえば、 #840 もそうですし、

以下もそうです。
たとえば、予約の有効期限を設定しないと、

![image](https://cloud.githubusercontent.com/assets/1328499/10342254/2e9c7aa4-6d53-11e5-8f62-ed650d0fea16.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10342276/44176768-6d53-11e5-8c75-ef597d0c6286.png)

↑が予約があるにもかかわらず、 「(0 人の予約待ち)」なっています。

有効期限を入れると「(1人の予約待ち)」になります。
![image](https://cloud.githubusercontent.com/assets/1328499/10342340/8b9203be-6d53-11e5-9fc5-a2225a6992ed.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10342318/72c58932-6d53-11e5-9fe5-109c255d33d2.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 68a51a9)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 59ae1b8)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
https://github.com/next-l/enju_circulation/commit/be93b7491c0d8515ec1e903e3785d14092169a9e の修正で直っていないか確認願います。 enju_circulation モジュールです。

**Comment by yegusa** [comment]
少なくとも指摘した現象については、できることを確認しましたので、いったんクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10343303/2c9e61cc-6d58-11e5-9403-9ac656a1579c.png)
![image](https://cloud.githubusercontent.com/assets/1328499/10343318/3f4bdfd4-6d58-11e5-979c-6f5b9b76348e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f4799e7)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
