### ISSUE TITLE
貸出履歴画面：予約されている資料があるのに、右のファセットに「予約あり」に「いいえ」しかない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#843]
ハリーポッターと炎のゴブレットは、予約されているが、右のファセットには「いいえ(3)」となっている。

![image](https://cloud.githubusercontent.com/assets/1328499/10343487/f2a908ea-6d58-11e5-8451-e5f2d7de213c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10343552/279c8b08-6d59-11e5-859c-9a623a98bac1.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f4799e7)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
#842 の影響を疑うのですが、一回 <code>rake environment sunspot:reindex</code> してみても同様の現象でしょうか。

**Comment by yegusa** [comment]
rake sunspot:reindex RAILS_ENV=production

とやったら、できました。ので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10356335/0750b038-6db1-11e5-8958-6fcd33592471.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10356360/540747ca-6db1-11e5-8086-40e583f74f27.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 f4799e7)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
