### ISSUE TITLE
書誌のエクスポートで分類情報（NDC）を出力したい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#844]
書誌情報のエクスポートでNDC出力できるとうれしいシーンは多いと思われます。

インポートにあわせて YAML 形式で classification 列に出力するか：
```
classification
{ ndc9: "334.1", ndc8: "330" }
```

または、各分類種別ごとに別の列に出力するか、要検討：
```
ndc9 \t ndc8 \t ddc
334.1 \t 330 \t N631
```

**Comment by yegusa** [comment]
両方ってのはだめ？

**Comment by nabeta** [comment]
インポート形式にあわせるべく、ひとまずYAMLで出力できるようにします。

**Comment by nabeta** [comment]
#1026 と重複でしょうか？

**Comment by yegusa** [comment]
重複だけど、YAML形式でやるっていってます。こっちでは。

**Comment by yegusa** [comment]
とりあえず、こっちは重複なのでクローズします。
