### ISSUE TITLE
書誌・所蔵のエクスポートで item_id を出力したい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#845]
manifestation_id は既にエクスポートされているので、こちらもあわせて出力できると助かります。

**Comment by yegusa** [comment]
（ #811 manifestation_identifier も出してほしい） にも関連しますね。

現在：
accepted_at
acquired_at
bookstore
budget_type
call_number
circulation_status
creator
isbn
iss_itemno
issn
issn_l
item_created_at
item_identifier
item_price
item_updated_at
jpno
lccn
library
manifestation_created_at
manifestation_id
manifestation_price
manifestation_updated_at
ncid
original_title
pub_date
publisher
shelf

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 3220ba5)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 574817f)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by masao** [comment]
item_id を追加しました。

**Comment by yegusa** [comment]
確認しました。マニュアルも追記しておきました。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10366957/915c0460-6e08-11e5-8321-04d1043fcca0.png)

accepted_at
acquired_at
bookstore
budget_type
call_number
circulation_status
creator
isbn
iss_itemno
issn
issn_l
item_created_at
item_id
item_identifier
item_price
item_updated_at
jpno
lccn
library
manifestation_created_at
manifestation_id
manifestation_price
manifestation_updated_at
ncid
original_title
pub_date
publisher
shelf

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 477fb84)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 050bfa3)
  * enju_leaf (1.1.0.rc21 574817f)
  * enju_library (0.1.0.pre44 6d34c18)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
ここまでくると、TSVファイルで完全なバックアップを作成できるようにしたいですね。
現状ではIDにシーケンス（連番）を使用している部分があるので、簡単にはいきませんが。
