### ISSUE TITLE
貸出の履歴をみたときに、予約のあるものは（n人の予約待ち）を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#848]
今は、右メニューのフィルタで、「はい」をリンクしないとどれに予約が入っているか分からないため。
赤四角あたりに

（n人の予約待ち）

を表示してほしい。
![image](https://cloud.githubusercontent.com/assets/1328499/10370784/741ec8de-6e1b-11e5-8751-d0db4b3f0ec8.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.0.pre69 c562fe6)
- enju_circulation (0.1.0.pre48 694fc72)
- enju_event (0.1.17.pre26 3f14e24)
- enju_flower (0.1.0.pre23 050bfa3)
- enju_leaf (1.1.0.rc21 574817f)
- enju_library (0.1.0.pre44 6d34c18)
- enju_loc (0.1.0.pre5 443805a)
- enju_manifestation_viewer (0.1.0.pre19 e76a52c)
- enju_message (0.1.14.pre25 155ea82)
- enju_ndl (0.1.0.pre37)
- enju_nii (0.1.0.pre13 ff350da)
- enju_oai (0.1.0.pre19 5c357c9)
- enju_purchase_request (0.1.0.pre14 dabe027)
- enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
「（n人の予約待ち）」を表示するようにしました。
https://enju.next-l.jp/checkouts?page=6

![image](https://user-images.githubusercontent.com/11428/71245513-3b777480-2358-11ea-9124-efcf809640b8.png)

**Comment by masao** [comment]
表示されるようになったことを確認しました。クローズします。
