### ISSUE TITLE
雑誌の各号の情報を新規作成する際には親書誌の情報をコピーしてほしい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#851]
雑誌の各号ごとの情報を新規作成する際に、著者や出版社、分類、ISSNといった共通する書誌情報はコピーしてくれると助かります。

現在は「原題」「タイトルのヨミ」だけがコピーされている状態です。

**Comment by masao** [comment]
著者、出版社あたりをコピーするようにしてみました。ご確認ください。
なお、識別子は単純にコピーできるものとそうでないものの切り分けが難しそうなので、見送りました。

**Comment by yegusa** [comment]
具体的にはどんな項目をコピーすることにしたのでしょうか?

* 件名
* 分類
* 出版者
* 著者

のほかにもありますか?

* 代替タイトル
* 責任表示
* 出版地
* 高さ
* 幅
* 奥行き
* 価格
* アクセスアドレス

あたりもコピーしてもいいかも?

![image](https://cloud.githubusercontent.com/assets/1328499/11993982/ec13aab2-aa7a-11e5-9a10-72d57ad06e94.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11993994/fffb0548-aa7a-11e5-888f-666b1fa6bab2.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994017/565259fa-aa7b-11e5-8769-be3cd503d216.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by masao** [comment]
コピーしてくる項目を提案部分＋言語、発行頻度まで増やしました。結局、コピーしてくる項目は以下のとおりです：

* 原題
* タイトルのヨミ
* 代替タイトル
* 責任表示
* 逐次刊行物フラグ
* 著者
* 協力者・編者
* 出版者
* 出版地
* 発行頻度
* 言語
* 件名
* 分類
* 高さ
* 幅
* 奥行き
* アクセスアドレス

**Comment by yegusa** [comment]
確認しました。「参照に必要な権限」を追加をお願いします。

----

* 原題
* タイトルのヨミ
* 代替タイトル
* 責任表示
* 逐次刊行物フラグ
* 著者
* 協力者・編者
* 出版者
* 出版地
* 発行頻度
* 言語
* 件名
* 分類
* 高さ
* 幅
* 奥行き
* 価格　←　なかったですが、こちらもコピーしてますよね
* アクセスアドレス
* 参照に必要な権限　←　こちらも追加したほうがよいと思いました。

![image](https://cloud.githubusercontent.com/assets/1328499/12005226/4c8bca70-abdc-11e5-84bb-f1d3cb193bdc.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12005223/2eb30982-abdc-11e5-965e-842bd024e624.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 b89ee3f)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by masao** [comment]
「参照に必要な権限」を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

* 原題
* タイトルのヨミ
* 代替タイトル
* 責任表示
* 逐次刊行物フラグ
* 著者
* 協力者・編者
* 出版者
* 出版地
* 発行頻度
* 言語
* 件名
* 分類
* 高さ
* 幅
* 奥行き
* 価格
* アクセスアドレス
* 参照に必要な権限

![image](https://cloud.githubusercontent.com/assets/1328499/12005313/42982fee-abe2-11e5-9526-b0f9898071a0.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12005323/8e135728-abe2-11e5-94af-0e31b5e71548.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0948f53)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
