### ISSUE TITLE
リリース時点での、どのモジュールをつかっていたかをドキュメントを書くこと

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#852]
覚書です。書いておきます。

#847 対策です。

**Comment by yegusa** [comment]
※これは、リリース後（もしくは直前）に、どのモジュールをつかっているかの記録をとってドキュメントを書くひつようがあるので、今はできません。枠をつくっておくことはできる。

**Comment by yegusa** [comment]
とりあえず、現時点（2015-11-11 16:15）での デモサーバーの情報です。

Ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
Environment: production
Gems:
actionmailer: 4.2.4
actionpack: 4.2.4
actionview: 4.2.4
activejob: 4.2.4
activemodel: 4.2.4
activerecord: 4.2.4
activesupport: 4.2.4
acts_as_list: 0.7.2
addressable: 2.3.8
airbrake: 4.3.3
arel: 6.0.3
attribute_normalizer: 1.2.0
awesome_nested_set: 3.0.2
aws-sdk: 2.1.36
aws-sdk-core: 2.1.36
aws-sdk-resources: 2.1.36
bcrypt: 3.1.10
binding_of_caller: 0.7.2
builder: 3.2.2
bullet: 4.14.10
bundler: 1.7.10
byebug: 8.1.0
cancancan: 1.13.1
charlock_holmes: 0.7.3
chronic: 0.10.2
climate_control: 0.0.3
cocaine: 0.5.7
coffee-rails: 4.1.0
coffee-script: 2.4.1
coffee-script-source: 1.9.1.1
dalli: 2.7.4
debug_inspector: 0.0.2
devise: 3.5.2
devise-encryptable: 0.2.0
dynamic_form: 1.1.4
enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.0
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0
erubis: 2.7.0
execjs: 2.6.0
faraday: 0.9.2
fix_microsoft_links: 0.1.4
foreman: 0.78.0
friendly_id: 5.1.0
geocoder: 1.2.12
globalid: 0.3.6
hashie: 3.4.3
highline: 1.7.8
i18n: 0.7.0
immigrant: 0.3.4
jbuilder: 2.3.2
jc-validates_timeliness: 3.1.1
jmespath: 1.1.3
jquery-rails: 4.0.5
jquery-ui-rails: 4.2.1
json: 1.8.3
jwt: 1.5.2
kaminari: 0.16.3
kgio: 2.10.0
kramdown: 1.9.0
library_stdnums: 1.4.1
lisbn: 0.2.2
loofah: 2.0.3
mail: 2.6.3
marc: 1.0.0
mime-types: 2.6.2
mimemagic: 0.3.0
mini_portile: 0.6.2
minitest: 5.8.2
mobylette: 3.5
mono_logger: 1.1.0
multi_json: 1.11.2
multi_xml: 0.5.5
multipart-post: 2.0.0
nested_form: 0.3.2
nokogiri: 1.6.6.2
non-stupid-digest-assets: 1.0.5
nori: 2.6.0
oauth2: 1.0.0
omniauth: 1.2.2
omniauth-oauth2: 1.3.1
omniauth-orcid: 1.0.30
options: 2.3.2
orm_adapter: 0.5.0
paper_trail: 4.0.0
paperclip: 4.3.1
paperclip-meta: 1.2.0
pg: 0.18.3
pr_geohash: 1.0.0
progress_bar: 1.0.5
rack: 1.6.4
rack-protection: 1.5.3
rack-test: 0.6.3
rails: 4.2.4
rails-deprecated_sanitizer: 1.0.3
rails-dom-testing: 1.0.7
rails-html-sanitizer: 1.0.2
rails_autolink: 1.1.6
railties: 4.2.4
raindrops: 0.15.0
rake: 10.4.2
rdoc: 4.2.0
redis: 3.2.1
redis-actionpack: 4.0.1
redis-activesupport: 4.1.5
redis-namespace: 1.5.2
redis-rack: 1.5.0
redis-rails: 4.0.0
redis-store: 1.1.7
request_store: 1.2.0
responders: 2.1.0
resque: 1.25.2
resque-scheduler: 4.0.0
resque_mailer: 2.2.7
ri_cal: 0.8.8
rsolr: 1.0.13
rufus-scheduler: 3.1.8
sass: 3.4.19
sass-rails: 5.0.4
scrub_rb: 1.0.1
sdoc: 0.4.1
simple_form: 3.2.0
sinatra: 1.4.6
sitemap_generator: 5.1.0
slack-notifier: 1.4.0
spring: 1.4.1
sprockets: 3.4.0
sprockets-rails: 2.3.3
statesman: 1.3.1
sunspot: 2.2.0
sunspot_rails: 2.2.0
sunspot_solr: 2.2.0
thor: 0.19.1
thread_safe: 0.3.5
tilt: 2.0.1
timeliness: 0.3.7
turbolinks: 2.5.3
tzinfo: 1.2.2
uglifier: 2.7.2
unf: 0.1.4
unf_ext: 0.0.7.1
unicorn: 5.0.0
uniform_notifier: 1.9.0
vegas: 0.1.11
warden: 1.2.3
web-console: 2.2.1
whenever: 0.9.4
Languages:
en: English
de: German
ja: 日本語 (既定の言語)
es: Spanish

**Comment by yegusa** [comment]
これどこにどう書いて保存しておこうか。ここに書いてあるので良しとする?

**Comment by nabeta** [comment]
デモサーバにあるのは監視用のgem（airbrakeなど）が入っているので、1.1.0の仮想マシンのものを使ったほうが正確だと思います。

**Comment by yegusa** [comment]
ここに書いてあるということでOKにする by Enju WS2015-11-15 の議論より。

**Comment by yegusa** [comment]
1.1.0の仮想マシン http://www.next-l.jp/download/vm/enju_leaf_1.1.0.virtualbox.zip の

「システムの基本的な情報の表示」
http://localhost:8080/page/system_information

Ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux-gnu]
Environment: production
Gems:
actionmailer: 4.2.4
actionpack: 4.2.4
actionview: 4.2.4
activejob: 4.2.4
activemodel: 4.2.4
activerecord: 4.2.4
activesupport: 4.2.4
acts_as_list: 0.7.2
addressable: 2.3.8
arel: 6.0.3
attribute_normalizer: 1.2.0
awesome_nested_set: 3.0.2
aws-sdk: 2.1.36
aws-sdk-core: 2.1.36
aws-sdk-resources: 2.1.36
bcrypt: 3.1.10
binding_of_caller: 0.7.2
builder: 3.2.2
bundler: 1.10.6
byebug: 8.1.0
cancancan: 1.13.1
charlock_holmes: 0.7.3
chronic: 0.10.2
climate_control: 0.0.3
cocaine: 0.5.7
coffee-rails: 4.1.0
coffee-script: 2.4.1
coffee-script-source: 1.9.1.1
dalli: 2.7.4
debug_inspector: 0.0.2
devise: 3.5.2
devise-encryptable: 0.2.0
dotenv: 2.0.2
dotenv-rails: 2.0.2
dynamic_form: 1.1.4
enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.0
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_subject: 0.1.0
erubis: 2.7.0
exception_notification: 4.1.1
exception_notification-rake: 0.2.1
execjs: 2.6.0
faraday: 0.9.2
fix_microsoft_links: 0.1.4
foreman: 0.78.0
friendly_id: 5.1.0
geocoder: 1.2.12
globalid: 0.3.6
highline: 1.7.8
i18n: 0.7.0
jbuilder: 2.3.2
jc-validates_timeliness: 3.1.1
jmespath: 1.1.3
jquery-rails: 4.0.5
jquery-ui-rails: 4.2.1
json: 1.8.3
kaminari: 0.16.3
kgio: 2.10.0
kramdown: 1.9.0
library_stdnums: 1.4.1
lisbn: 0.2.2
loofah: 2.0.3
mail: 2.6.3
marc: 1.0.0
mime-types: 2.6.2
mimemagic: 0.3.0
mini_portile: 0.6.2
minitest: 5.8.2
mobylette: 3.5
mono_logger: 1.1.0
multi_json: 1.11.2
multipart-post: 2.0.0
nested_form: 0.3.2
nokogiri: 1.6.6.2
non-stupid-digest-assets: 1.0.5
nori: 2.6.0
options: 2.3.2
orm_adapter: 0.5.0
paper_trail: 4.0.0
paperclip: 4.3.1
paperclip-meta: 1.2.0
pr_geohash: 1.0.0
progress_bar: 1.0.5
rack: 1.6.4
rack-protection: 1.5.3
rack-test: 0.6.3
rails: 4.2.4
rails-deprecated_sanitizer: 1.0.3
rails-dom-testing: 1.0.7
rails-html-sanitizer: 1.0.2
rails_autolink: 1.1.6
railties: 4.2.4
raindrops: 0.15.0
rake: 10.4.2
rdoc: 4.2.0
redis: 3.2.1
redis-actionpack: 4.0.1
redis-activesupport: 4.1.5
redis-namespace: 1.5.2
redis-rack: 1.5.0
redis-rails: 4.0.0
redis-store: 1.1.7
request_store: 1.2.0
responders: 2.1.0
resque: 1.25.2
resque-scheduler: 4.0.0
resque_mailer: 2.2.7
ri_cal: 0.8.8
rsolr: 1.0.13
rufus-scheduler: 3.1.8
sass: 3.4.19
sass-rails: 5.0.4
scrub_rb: 1.0.1
sdoc: 0.4.1
simple_form: 3.2.0
sinatra: 1.4.6
sitemap_generator: 5.1.0
spring: 1.4.1
sprockets: 3.4.0
sprockets-rails: 2.3.3
sqlite3: 1.3.11
statesman: 1.3.1
sunspot: 2.2.0
sunspot_rails: 2.2.0
sunspot_solr: 2.2.0
thor: 0.19.1
thread_safe: 0.3.5
tilt: 2.0.1
timeliness: 0.3.7
turbolinks: 2.5.3
tzinfo: 1.2.2
uglifier: 2.7.2
unf: 0.1.4
unf_ext: 0.0.7.1
unicorn: 5.0.0
vegas: 0.1.11
warden: 1.2.3
web-console: 2.2.1
whenever: 0.9.4
Languages:
en: English
ja: 日本語 (既定の言語)

**Comment by yegusa** [comment]
ということでクローズします。
