### ISSUE TITLE
書誌詳細画面の .txt としてTSVエクスポートされるものと、全件TSVエクスポートを揃える

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#854]
- [x] a) 出力される項目が違う
- [x] b) isbn の書式が違う　

#857 と類似

a) ["9784860641573"]、2つ以上あるときは、["9784860641573", "9784860641931"]
b)9784860641573、2つ以上あるときは、一つだけ出力

私は、 
一つのとき：9784860641573
2つのとき：9784860641573//9784860641931

となっているのがいいのじゃないかと思います。

a) 書誌詳細画面の .txt としてTSVエクスポートされるもの：
manifestation_identifier
original_title
creator
publisher
isbn
pub_date
note

b) 全件TSVエクスポート：
manifestation_id
original_title
creator
publisher
pub_date
manifestation_price
manifestation_created_at
manifestation_updated_at
manifestation_identifier
isbn
iss_itemno
issn
issn_l
jpno
lccn
ncid
item_id
item_identifier
call_number
item_price
acquired_at
accepted_at
bookstore
budget_type
circulation_status
shelf
library
item_created_at
item_updated_at

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
Manifestation#to_csv を呼ぶようにしました。詳細は https://github.com/next-l/enju_leaf/issues/857#issuecomment-168375016 をごらんください。
開発サーバに反映済みです。
http://dev.next-l.jp/manifestations/24422.txt

**Comment by yegusa** [comment]
a) 出力される項目が違う
 
↑をチェックしました。同じになっていることを確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/12078032/48091d9a-b244-11e5-91f9-48c8a2188c9c.png)


ダウンロードしたファイル：
<pre>
manifestation_id	original_title	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	note	isbn	issn	jpno	doi	iss_itemno	lccn	issn_l	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:clno	item_id	item_identifier	call_number	item_price	acquired_at	accepted_at	bookstore	budget_type	circulation_status	shelf	library	item_created_at	item_updated_at
42	基礎からわかる情報リテラシー : コンピュータ・インターネットと付き合う基礎知識	奥村, 晴彦 	奥村, 晴彦 （著）	技術評論社	2014-02	奥村晴彦 著	1480	2015-12-26 17:54:55 +0900	2016-01-03 15:37:47 +0900	http://iss.ndl.go.jp/books/R100000002-I025107686-00	http://sample.jp/zzz.html	注記・・・	9784774162133		22349643		R100000002-I025107686-00			""	aaa//bbb	ccc	""	007//007.58	""	K|a|b	41	1987501	K062||4	1900	2015-01-10 00:00:00 +0900		あさま書店	siryohi	Available On Shelf	first_shelf	yours	2016-01-03 15:37:47 +0900	2016-01-03 15:37:47 +0900
</pre>

参考： 全体をエクスポートしたものから、42だけを抜き出したもの
<pre>
manifestation_id	original_title	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	note	isbn	issn	jpno	doi	iss_itemno	lccn	issn_l	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:clno	item_id	item_identifier	call_number	item_price	acquired_at	accepted_at	bookstore	budget_type	circulation_status	shelf	library	item_created_at	item_updated_at
42	基礎からわかる情報リテラシー : コンピュータ・インターネットと付き合う基礎知識	奥村, 晴彦 	奥村, 晴彦 （著）	技術評論社	2014-02	奥村晴彦 著	1480	2015-12-26 17:54:55 +0900	2016-01-03 15:37:47 +0900	http://iss.ndl.go.jp/books/R100000002-I025107686-00	http://sample.jp/zzz.html	注記・・・	9784774162133		22349643		R100000002-I025107686-00			""	aaa//bbb	ccc	""	007//007.58	""	K|a|b	41	1987501	K062||4	1900	2015-01-10 00:00:00 +0900		あさま書店	siryohi	Available On Shelf	first_shelf	yours	2016-01-03 15:37:47 +0900	2016-01-03 15:37:47 +0900
</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e40e80e)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)

**Comment by yegusa** [comment]
TSV全エクスポートでも、1件だけでも、isbnが複数登録されている場合、
一つしか表示されないことを確認しました（こちらは別 issue #1099 になっている）。

まあ、TSV全エクスポートでも、1件エクスポートも、
そろっていることは確認したので、このisseuはクローズします。

参考：縦と横を逆にしました。
![image](https://cloud.githubusercontent.com/assets/1328499/12078142/911b8e9a-b24a-11e5-941e-c10413164800.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju

enju_biblio (0.2.0.beta.1 e40e80e)
enju_circulation (0.2.0.beta.1 801ca1f)
enju_event (0.2.0.beta.1 1483293)
enju_leaf (1.2.0.beta.1 ac6500e)
enju_library (0.2.0.beta.1 d6e53e6)
enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
enju_message (0.2.0.beta.1 a62b817)
enju_ndl (0.2.0.beta.1 ce80288)
enju_purchase_request (0.2.0.beta.1 ab17d9f)
enju_subject (0.2.0.beta.1 237251b)
