### ISSUE TITLE
書誌詳細の XMLを精査してまともなものにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#856]
#833 の派生です。

**Comment by nabeta** [comment]
1.4系では、XML出力のテンプレートは以下のファイルになる。
- MODS: https://github.com/next-l/enju_leaf/blob/main/app/views/manifestations/_show.mods.builder
- RDF/XML: https://github.com/next-l/enju_leaf/blob/main/app/views/manifestations/_show.rdf.builder

**Comment by nabeta** [comment]
#1340 のJPCOARフォーマット出力として扱います。
