### ISSUE TITLE
検索結果一覧の.txt としてTSVエクスポートされるものと、全件TSVエクスポートを揃える

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#857]
#854 と類似です。

* 出力される項目が違う
* isbn の書式が違う　

a) ["9784860641573"]、2つ以上あるときは、["9784860641573", "9784860641931"]
b)9784860641573、2つ以上あるときは、一つだけ出力

私は、 
一つのとき：9784860641573
2つのとき：9784860641573//9784860641931

となっているのがいいのじゃないかと思います。

a) 検索結果一覧の .txt としてTSVエクスポートされるもの：
manifestation_identifier
original_title
creator
publisher
isbn
pub_date
note

b) 全件TSVエクスポート：
manifestation_id
original_title
creator
publisher
pub_date
manifestation_price
manifestation_created_at
manifestation_updated_at
manifestation_identifier
isbn
iss_itemno
issn
issn_l
jpno
lccn
ncid
item_id
item_identifier
call_number
item_price
acquired_at
accepted_at
bookstore
budget_type
circulation_status
shelf
library
item_created_at
item_updated_at

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 2f1b3b2)
  * enju_circulation (0.1.0.pre48 694fc72)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 bf9c5e2)
  * enju_library (0.1.0.pre44 6199627)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
以下のコミットで、一覧画面のTSVファイルと全件エクスポート時のTSVファイルの内容をそろえるようにしました。
https://github.com/next-l/enju_biblio/commit/912675fee35a0a65e0a88d726f6e86b942d3ee68

Manifestation.csv_header（ヘッダ出力）とManifestation#to_csv（個々の書誌のTSV出力。区切り文字はcol_sepオプションで指定可能）というメソッドを追加し、一覧画面と全件エクスポートの両方で呼ぶようにしています。

**Comment by yegusa** [comment]
検索結果一覧の.txt としてTSVエクスポートされるものと、全件TSVエクスポートの項目がそろっていることを
確認しました。
isbn の出力方法については別issue #1099 でやることにして、クローズする。

検索結果一覧のTSVファイル：
<pre>
manifestation_id	original_title	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	note	isbn	issn	jpno	doi	iss_itemno	lccn	issn_l	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:clno	item_id	item_identifier	call_number	item_price	acquired_at	accepted_at	bookstore	budget_type	circulation_status	shelf	library	item_created_at	item_updated_at
51	件名テスト4							2016-01-01 13:11:32 +0900	2016-01-01 13:11:33 +0900											""	ウェブアプリケーション//インターネット	""	Internet			
50	件名テスト3							2016-01-01 13:11:31 +0900	2016-01-01 13:11:31 +0900											""	ウェブアプリケーション	""	Internet			
49	件名テスト2							2016-01-01 13:11:29 +0900	2016-01-01 13:11:30 +0900											""	ウェブアプリケーション//インターネット	""	""			
48	件名テスト1							2016-01-01 13:11:27 +0900	2016-01-01 13:11:28 +0900											""	ウェブアプリケーション	""	""			
47	分類4							2016-01-01 12:39:44 +0900	2016-01-01 13:07:21 +0900											""	ウェブアプリケーション//インターネット	""	Internet	215	""	AZ-464//AZ-418
46	分類3							2016-01-01 12:39:41 +0900	2016-01-01 13:07:19 +0900											""	ウェブアプリケーション	""	Internet	215	""	AZ-464
45	分類2							2016-01-01 12:39:39 +0900	2016-01-01 13:07:18 +0900											""	ウェブアプリケーション//インターネット	""	""	""	""	AZ-464//AZ-418
44	分類1							2016-01-01 12:39:33 +0900	2016-01-01 13:07:16 +0900											""	ウェブアプリケーション	""	""	008//008.58	""	""
42	基礎からわかる情報リテラシー : コンピュータ・インターネットと付き合う基礎知識	奥村, 晴彦 	奥村, 晴彦 （著）	技術評論社	2014-02	奥村晴彦 著	1480	2015-12-26 17:54:55 +0900	2016-01-03 18:11:59 +0900	http://iss.ndl.go.jp/books/R100000002-I025107686-00	http://sample.jp/zzz.html	注記・・・	9784774162133		22349643		R100000002-I025107686-00			""	aaa//bbb	ccc	""	007//007.58	""	K|a|b	41	1987501	K062||4	1900	2015-01-10 00:00:00 +0900		あさま書店	siryohi	Available On Shelf	first_shelf	yours	2016-01-03 15:37:47 +0900	2016-01-03 15:37:47 +0900
41	はじめてのPerl/CGIプログラミング : Linux/Windows対応	玉川, 純, 1973-		秀和システム	2005-12	玉川純 著	2600	2015-12-26 17:51:17 +0900	2015-12-26 17:51:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000008025272-00			9784798012032		20953804		R100000002-I000008025272-00			""	インターネット//プログラミング (コンピュータ)	""	""	547.483	""	""
</pre>


全エクスポート：
<pre>
manifestation_id	original_title	creator	contributor	publisher	pub_date	statement_of_responsibility	manifestation_price	manifestation_created_at	manifestation_updated_at	manifestation_identifier	access_address	note	isbn	issn	jpno	doi	iss_itemno	lccn	issn_l	subject:unknown	subject:ndlsh	subject:bsh	subject:lcsh	classification:ndc9	classification:ddc	classification:clno	item_id	item_identifier	call_number	item_price	acquired_at	accepted_at	bookstore	budget_type	circulation_status	shelf	library	item_created_at	item_updated_at
1	はじめてのRuby on Rails : 話題の「Webアプリケーション・フレームワーク」が使える! : instant rails	清水, 美樹		工学社	2006-08	清水美樹 著	2300	2015-11-29 12:05:32 +0900	2015-12-14 23:50:35 +0900	http://iss.ndl.go.jp/books/R100000002-I000008276603-00			9784777512324		21095296		R100000002-I000008276603-00							547.483	""	""	5	909093							Available On Shelf	first_shelf	yours	2015-12-06 17:40:43 +0900	2015-12-06 17:41:07 +0900
2	レッスン	Pearson, Carol Lynn//灰島, かり, 1950-//ささめや, ゆき, 1943-		平凡社	2002-12	キャロル・リン・ピアソン 文; 灰島かり 訳; ささめやゆき 画	1400	2015-11-29 12:08:23 +0900	2015-12-24 00:03:12 +0900	http://iss.ndl.go.jp/books/R100000002-I000004040061-00			9784582831351		20364486		R100000002-I000004040061-00							933.7	""	""	2	300002							On Loan	first_shelf	yours	2015-12-05 12:36:28 +0900	2015-12-05 12:37:52 +0900
3	Rails of Ruby on Rails : Case of Locusandwonders.com	清水, 智雄//Plan de Sens		毎日コミュニケーションズ	2008-05	Plan de Sens, 清水智雄 著	3200	2015-12-05 12:34:42 +0900	2015-12-06 17:33:23 +0900	http://iss.ndl.go.jp/books/R100000002-I000009366581-00			9784839922214		21434454		R100000002-I000009366581-00							547.483	""	""	1	300001							Available On Shelf	first_shelf	yours	2015-12-05 12:35:12 +0900	2015-12-06 17:33:23 +0900
4	はじめてのRuby on Rails2 : 最新の「Webアプリケーション・フレームワーク」が使える!	清水, 美樹		工学社	2008-04	清水美樹 著	2300	2015-12-05 12:49:32 +0900	2015-12-21 00:49:53 +0900	http://iss.ndl.go.jp/books/R100000002-I000009331867-00			9784777513536		21407507		R100000002-I000009331867-00							547.483	""	""	3	300003							On Loan	first_shelf	yours	2015-12-05 12:50:01 +0900	2015-12-15 15:28:51 +0900
5	Ruby on Rails環境構築ガイド : ソース管理から公開までを徹底解説 : 定番ツールを使いこなして今日から即戦力!	黒田, 努		インプレスジャパン//インプレスコミュニケーションズ	2013-03	黒田努 著	2800	2015-12-06 12:30:03 +0900	2015-12-09 12:32:14 +0900	http://iss.ndl.go.jp/books/R100000002-I024310898-00			9784844333753		22220800		R100000002-I024310898-00							547.483	""	""	4	909092							On Loan	first_shelf	yours	2015-12-06 17:33:57 +0900	2015-12-06 17:34:13 +0900
6	図書館情報資源概論	伊藤, 民雄, 1967-//大串, 夏身, 1948-//金沢, みどり, 1959-		学文社	2012-09	伊藤民雄 著	1800	2015-12-07 19:10:32 +0900	2015-12-12 00:53:08 +0900	http://iss.ndl.go.jp/books/R100000002-I023951143-00			9784762023040		22156874		R100000002-I023951143-00			""	図書館資料	""	""	014.1	""	""	7	808080							Available On Shelf	first_shelf	yours	2015-12-11 01:45:48 +0900	2015-12-12 00:53:08 +0900
7	Ajax on Rails : build dynamic Web applications with Ruby	Raymond, Scott//牧野, 聡		オライリー・ジャパン//オーム社	2007-07	Scott Raymond 著; 牧野聡 訳	2800	2015-12-09 12:32:04 +0900	2015-12-15 18:38:57 +0900	http://iss.ndl.go.jp/books/R100000002-I000008739626-00			9784873113326		21270091		R100000002-I000008739626-00							547.483	""	""	6	909095	547|レ|1						Available On Shelf	first_shelf	yours	2015-12-09 12:32:40 +0900	2015-12-15 18:38:57 +0900
8	ハリー・ポッターと賢者の石	Rowling, J. K, 1965-//松岡, 佑子		静山社	2003-11	J.K.ローリング 作; 松岡佑子 訳	950	2015-12-12 10:23:49 +0900	2016-01-02 01:42:42 +0900	http://iss.ndl.go.jp/books/R100000002-I000004262945-00			9784915512490		20497459		R100000002-I000004262945-00							933.7	""	""	8	700001							Available On Shelf	first_shelf	yours	2015-12-12 10:24:42 +0900	2015-12-12 10:53:05 +0900
9	わたしをみつけて	中脇, 初枝, 1974-		ポプラ社	2015-06	中脇初枝 [著]	600	2015-12-14 17:00:31 +0900	2015-12-15 23:53:57 +0900	http://iss.ndl.go.jp/books/R100000002-I026397196-00			9784591145579		22575236		R100000002-I026397196-00							913.6	""	""	9	491001							Available On Shelf	first_shelf	yours	2015-12-14 17:01:02 +0900	2015-12-15 23:53:57 +0900
10	ハリー・ポッターと不死鳥の騎士団	Rowling, J. K, 1965-//松岡, 佑子//Schlesinger, Dan, 1955-		静山社	2008-03	J.K.ローリング 作; 松岡佑子 訳; ダン・シュレシンジャー 画		2015-12-14 23:48:36 +0900	2015-12-15 18:40:13 +0900	http://iss.ndl.go.jp/books/R100000002-I000009302751-00			9784915512674		21388695		R100000002-I000009302751-00							933.7	""	""	10	303001							Available On Shelf	first_shelf	yours	2015-12-14 23:49:24 +0900	2015-12-14 23:49:24 +0900
11	RailsによるアジャイルWebアプリケーション開発	Ruby, Sam//Thomas, David, 1956-//Hansson, David Heinemeier//前田, 修吾, 1975-		オーム社	2009-11	Sam Ruby, Dave Thomas, David Heinemeier Hansson 共著; 前田修吾 監訳	4200	2015-12-15 15:32:08 +0900	2015-12-21 00:49:02 +0900	http://iss.ndl.go.jp/books/R100000002-I000010635637-00			9784274067853		21692769		R100000002-I000010635637-00							547.483	""	""	11	303002							On Loan	first_shelf	yours	2015-12-15 15:32:47 +0900	2015-12-15 15:51:38 +0900
12	絵入家名尽					""		2015-12-16 12:38:03 +0900	2015-12-16 12:38:19 +0900		""	皇都　清水屋次兵衛発行　5丁　18cm　和															12		K062||4						In Process	first_shelf	yours	2015-12-16 12:38:19 +0900	2015-12-16 12:38:19 +0900
13	ザ・ギバー : 記憶を伝える者	Lowry, Lois, 1937-//掛川, 恭子, 1936-		講談社	1995-09	ロイス・ローリー 作; 掛川恭子 訳	1400	2015-12-19 10:45:58 +0900	2015-12-20 01:05:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000002431403-00			9784062616522		95077024		R100000002-I000002431403-00							933	""	""	13	765001							Available On Shelf	first_shelf	yours	2015-12-19 10:46:43 +0900	2015-12-20 00:57:22 +0900
13	ザ・ギバー : 記憶を伝える者	Lowry, Lois, 1937-//掛川, 恭子, 1936-		講談社	1995-09	ロイス・ローリー 作; 掛川恭子 訳	1400	2015-12-19 10:45:58 +0900	2015-12-20 01:05:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000002431403-00			9784062616522		95077024		R100000002-I000002431403-00							933	""	""	14	321001							Available On Shelf	first_shelf	yours	2015-12-20 01:02:10 +0900	2015-12-20 01:02:10 +0900
13	ザ・ギバー : 記憶を伝える者	Lowry, Lois, 1937-//掛川, 恭子, 1936-		講談社	1995-09	ロイス・ローリー 作; 掛川恭子 訳	1400	2015-12-19 10:45:58 +0900	2015-12-20 01:05:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000002431403-00			9784062616522		95077024		R100000002-I000002431403-00							933	""	""	15	321005							Available On Shelf	first_shelf	yours	2015-12-20 01:02:34 +0900	2015-12-20 01:02:34 +0900
13	ザ・ギバー : 記憶を伝える者	Lowry, Lois, 1937-//掛川, 恭子, 1936-		講談社	1995-09	ロイス・ローリー 作; 掛川恭子 訳	1400	2015-12-19 10:45:58 +0900	2015-12-20 01:05:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000002431403-00			9784062616522		95077024		R100000002-I000002431403-00							933	""	""	16	693094							Available On Shelf	first_shelf	yours	2015-12-20 01:03:36 +0900	2015-12-20 01:03:36 +0900
13	ザ・ギバー : 記憶を伝える者	Lowry, Lois, 1937-//掛川, 恭子, 1936-		講談社	1995-09	ロイス・ローリー 作; 掛川恭子 訳	1400	2015-12-19 10:45:58 +0900	2015-12-20 01:05:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000002431403-00			9784062616522		95077024		R100000002-I000002431403-00							933	""	""	17								In Process	first_shelf	yours	2015-12-20 01:05:24 +0900	2015-12-20 01:05:24 +0900
14	ふたりの星	Lowry, Lois, 1937-//掛川, 恭子, 1936-//うらべ, ちえこ, 1959-		講談社	1992-01	ロイス=ローリー 作; 掛川恭子, 卜部千恵子 共訳; 津尾美智子 絵	1350	2015-12-20 10:30:50 +0900	2015-12-20 10:50:55 +0900	http://iss.ndl.go.jp/books/R100000002-I000002158288-00			9784061947207		92021073		R100000002-I000002158288-00							933	""	""	18	887001							Available On Shelf	first_shelf	yours	2015-12-20 10:31:16 +0900	2015-12-20 10:50:55 +0900
14	ふたりの星	Lowry, Lois, 1937-//掛川, 恭子, 1936-//うらべ, ちえこ, 1959-		講談社	1992-01	ロイス=ローリー 作; 掛川恭子, 卜部千恵子 共訳; 津尾美智子 絵	1350	2015-12-20 10:30:50 +0900	2015-12-20 10:50:55 +0900	http://iss.ndl.go.jp/books/R100000002-I000002158288-00			9784061947207		92021073		R100000002-I000002158288-00							933	""	""	19	887002							Available On Shelf	first_shelf	yours	2015-12-20 10:31:46 +0900	2015-12-20 10:50:55 +0900
15	テスト					""		2015-12-20 12:57:51 +0900	2015-12-20 12:57:51 +0900		""	""														
16	ギャザリング・ブルー : 青を蒐める者	Lowry, Lois, 1937-//島津, やよい		新評論	2013-03	ロイス・ローリー [著]; 島津やよい 訳	1500	2015-12-20 13:22:41 +0900	2015-12-22 15:22:26 +0900	http://iss.ndl.go.jp/books/R100000002-I024317835-00			9784794809308		22221712		R100000002-I024317835-00							933.7	""	""	20	894001							Available On Shelf	first_shelf	yours	2015-12-20 13:23:21 +0900	2015-12-22 15:22:26 +0900
17	サイレントボーイ	Lowry, Lois, 1937-//中村, 浩美, 1965-		アンドリュース・プレス	2003-12	ロイス・ローリー 著; 中村浩美 訳	1600	2015-12-20 17:57:22 +0900	2015-12-20 18:07:53 +0900	http://iss.ndl.go.jp/books/R100000002-I000007401522-00			9784901868105		20611521		R100000002-I000007401522-00							933.7	""	""	21	704001							Available On Shelf	first_shelf	yours	2015-12-20 18:07:52 +0900	2015-12-20 18:07:52 +0900
18	メッセンジャー : 緑の森の使者	Lowry, Lois, 1937-//島津, やよい		新評論	2014-09	ロイス・ローリー [著]; 島津やよい 訳	1500	2015-12-20 19:46:33 +0900	2015-12-22 18:33:18 +0900	http://iss.ndl.go.jp/books/R100000002-I025741509-00			9784794809773		22464008		R100000002-I025741509-00							933.7	""	""	36	4567423	933.7|ロ|1						Available On Shelf	first_shelf	yours	2015-12-22 18:33:18 +0900	2015-12-22 18:33:18 +0900
19	ドリーム・ギバー : 夢紡ぐ精霊たち	Lowry, Lois, 1937-//西川, 美樹		金の星社	2008-12	ロイス・ローリー 作; 西川美樹 訳	1300	2015-12-20 21:51:23 +0900	2015-12-20 21:52:27 +0900	http://iss.ndl.go.jp/books/R100000002-I000009934345-00			9784323063263		21523690		R100000002-I000009934345-00							933.7	""	""	22	609001							Removed	first_shelf	yours	2015-12-20 21:51:52 +0900	2015-12-20 21:52:27 +0900
20	Webの創成 : World Wide Webはいかにして生まれどこに向かうのか	Berners-Lee, Tim//高橋, 徹, 1941-		毎日コミュニケーションズ	2001-09	ティム・バーナーズ=リー 著; 高橋徹 監訳	2400	2015-12-20 22:12:57 +0900	2015-12-21 00:05:10 +0900	http://iss.ndl.go.jp/books/R100000002-I000003018903-00			9784839902872		20199781		R100000002-I000003018903-00			""	ハイパーテキスト	""	""	547.483	""	""	26	554004	547.483|テ						Available On Shelf	first_shelf	yours	2015-12-20 22:36:08 +0900	2015-12-20 22:36:10 +0900
20	Webの創成 : World Wide Webはいかにして生まれどこに向かうのか	Berners-Lee, Tim//高橋, 徹, 1941-		毎日コミュニケーションズ	2001-09	ティム・バーナーズ=リー 著; 高橋徹 監訳	2400	2015-12-20 22:12:57 +0900	2015-12-21 00:05:10 +0900	http://iss.ndl.go.jp/books/R100000002-I000003018903-00			9784839902872		20199781		R100000002-I000003018903-00			""	ハイパーテキスト	""	""	547.483	""	""	29	554101	547.483|テaa						Available On Shelf	first_shelf	yours	2015-12-20 23:01:38 +0900	2015-12-20 23:01:41 +0900
21	インストラクショナルデザイン : 教師のためのルールブック	島宗, 理, 1964-		米田出版//産業図書	2004-11	島宗理 著	2000	2015-12-20 22:13:31 +0900	2016-01-02 01:49:47 +0900	http://iss.ndl.go.jp/books/R100000002-I000007549561-00			9784946553196		20704968		R100000002-I000007549561-00			""	学習指導	""	""	375.1	""	""	24	554002	547.483|aヤ						Available On Shelf	first_shelf	yours	2015-12-20 22:26:48 +0900	2016-01-02 01:49:47 +0900
21	インストラクショナルデザイン : 教師のためのルールブック	島宗, 理, 1964-		米田出版//産業図書	2004-11	島宗理 著	2000	2015-12-20 22:13:31 +0900	2016-01-02 01:49:47 +0900	http://iss.ndl.go.jp/books/R100000002-I000007549561-00			9784946553196		20704968		R100000002-I000007549561-00			""	学習指導	""	""	375.1	""	""	28	554006	375.1|シ						Available On Shelf	first_shelf	yours	2015-12-20 22:36:11 +0900	2015-12-20 22:36:11 +0900
21	インストラクショナルデザイン : 教師のためのルールブック	島宗, 理, 1964-		米田出版//産業図書	2004-11	島宗理 著	2000	2015-12-20 22:13:31 +0900	2016-01-02 01:49:47 +0900	http://iss.ndl.go.jp/books/R100000002-I000007549561-00			9784946553196		20704968		R100000002-I000007549561-00			""	学習指導	""	""	375.1	""	""	31	554103	375.1|シcc						Available On Shelf	first_shelf	yours	2015-12-20 23:01:46 +0900	2015-12-20 23:01:48 +0900
22	Webを支える技術 : HTTP、URI、HTML、そしてREST	山本, 陽平, 1975-		技術評論社	2010-05	山本陽平 著	2570	2015-12-20 22:14:01 +0900	2015-12-26 17:51:21 +0900	http://iss.ndl.go.jp/books/R100000002-I000010835920-00			9784774142043		21752283		R100000002-I000010835920-00							547.483	""	""	25	554003	375.1|aシ						Available On Shelf	first_shelf	yours	2015-12-20 22:26:49 +0900	2015-12-21 00:02:43 +0900
22	Webを支える技術 : HTTP、URI、HTML、そしてREST	山本, 陽平, 1975-		技術評論社	2010-05	山本陽平 著	2570	2015-12-20 22:14:01 +0900	2015-12-26 17:51:21 +0900	http://iss.ndl.go.jp/books/R100000002-I000010835920-00			9784774142043		21752283		R100000002-I000010835920-00							547.483	""	""	27	554005	547.483|ヤ						Available On Shelf	first_shelf	yours	2015-12-20 22:36:10 +0900	2015-12-20 22:36:11 +0900
22	Webを支える技術 : HTTP、URI、HTML、そしてREST	山本, 陽平, 1975-		技術評論社	2010-05	山本陽平 著	2570	2015-12-20 22:14:01 +0900	2015-12-26 17:51:21 +0900	http://iss.ndl.go.jp/books/R100000002-I000010835920-00			9784774142043		21752283		R100000002-I000010835920-00							547.483	""	""	30	554102	547.483|ヤbb						Available On Shelf	first_shelf	yours	2015-12-20 23:01:42 +0900	2015-12-20 23:01:45 +0900
23	情報管理	科学技術振興機構//科学技術振興事業団//日本科学技術情報センター		科学技術振興機構	1963-	科学技術振興機構 編		2015-12-21 00:17:37 +0900	2015-12-21 00:19:09 +0900	http://iss.ndl.go.jp/books/R100000002-I000000011522-00	""	備考		00217298	00011604		R100000002-I000000011522-00		00217298							
24	Ruby on RailsによるWebアプリケーション・スーパーサンプル	久保秋, 真//後藤, 修一//中村, 真一郎, pub.2008		ソフトバンククリエイティブ	2008-04	久保秋真, 後藤修一, 中村真一郎 著	3200	2015-12-21 00:48:56 +0900	2015-12-26 03:14:48 +0900	http://iss.ndl.go.jp/books/R100000002-I000009313948-00			9784797341881		21405487		R100000002-I000009313948-00							547.483	""	""	32	444001							Available On Shelf	seihon	yours	2015-12-21 00:49:25 +0900	2015-12-26 03:14:48 +0900
25	はじめてのGrails : 「Ruby on Rails」風の「フレームワーク」をJavaで使いこなす!	清水, 美樹	架空編者	工学社	2009-11	清水美樹 著	2300	2015-12-21 00:49:49 +0900	2015-12-26 17:51:21 +0900	http://iss.ndl.go.jp/books/R100000002-I000010622509-00	""	""	9784777514847		21683240		R100000002-I000010622509-00							547.483	""	""
26	情報の科学と技術					""		2015-12-21 17:44:56 +0900	2015-12-21 17:44:57 +0900		""	""														
27	情報の科学と技術					""		2015-12-21 17:50:28 +0900	2015-12-22 13:58:45 +0900		""	""															34	5678931	Z104|a|1						Available On Shelf	seihon	yours	2015-12-21 17:52:57 +0900	2015-12-22 13:58:45 +0900
28	情報の科学と技術					""		2015-12-21 17:55:08 +0900	2015-12-22 13:56:59 +0900		""	""															35	55667784	Z104|a|2						Available On Shelf	seihon	yours	2015-12-21 17:55:35 +0900	2015-12-22 13:56:59 +0900
29	情報処理 : 情報処理学会誌 : IPSJ magazine	情報処理学会		情報処理学会//オーム社	1960-	""		2015-12-21 19:38:48 +0900	2015-12-21 19:38:56 +0900	http://iss.ndl.go.jp/books/R100000002-I000000011527-00				04478053	00011609		R100000002-I000000011527-00		04478053							
30	Rubyで作るWebアプリケーション入門 : プログラムの基礎からCGI、Web API、Ruby on Railsまでアプリケーション作成の基本を学ぶ	武井, 一巳, 1955-		メディア・テック出版	2007-08	武井一巳 著	2180	2015-12-22 19:50:43 +0900	2015-12-27 23:01:23 +0900	http://iss.ndl.go.jp/books/R100000002-I000009264963-00	""	注記になにかいれてみた	9784896273533		21377071		R100000002-I000009264963-00							547.483	""	""
31	専門図書館			専門図書館協議会		""		2015-12-24 18:44:27 +0900	2015-12-24 18:44:37 +0900	http://iss.ndl.go.jp/books/R100000002-I000000013751-00				03850188	00013847		R100000002-I000000013751-00		03850188							
32	雑誌テスト					""		2015-12-24 19:24:29 +0900	2015-12-24 19:26:50 +0900		""	""														
33	なにか架空の雑誌	へのへのもへじ	某某委員会	ありあり出版	2011	どこそこ委員会（編）	1900	2015-12-24 20:10:21 +0900	2015-12-26 14:22:17 +0900	567890	http://sample.jp/	注記は?		00279153						""	図書館	""	""	007	""	""
34	テスト					""		2015-12-24 21:04:57 +0900	2015-12-24 21:04:57 +0900		""	""												007.23	""	""
35	ハンガー・ゲーム	Collins, Suzanne//河井, 直子		メディアファクトリー	2009-10	スーザン・コリンズ 著; 河井直子 訳	1800	2015-12-25 13:31:41 +0900	2015-12-26 01:27:57 +0900	http://iss.ndl.go.jp/books/R100000002-I000010857500-00	http://sample.jp/zzz.html	""	9784840130639		21753740		R100000002-I000010857500-00							933.7	""	""	37	888701	933|コ|1						On Loan	first_shelf	yours	2015-12-25 13:32:32 +0900	2015-12-25 13:32:59 +0900
36	広辞苑					""		2015-12-26 13:18:03 +0900	2015-12-26 13:18:03 +0900		""	""	9784000801218													
37	雑誌に識別子が登録できるか					""		2015-12-26 13:19:33 +0900	2015-12-26 13:21:32 +0900		""	""		00279153												
38	クィディッチ今昔	Rowling, J. K, 1965-//松岡, 佑子		静山社	2014-03	J.K.ローリング 作; 松岡佑子 訳	620	2015-12-26 15:22:30 +0900	2015-12-26 15:39:14 +0900	http://iss.ndl.go.jp/books/R100000002-I025292085-00			9784863892514		22375950		R100000002-I025292085-00							933.7	""	""	38	986001							On Loan	first_shelf	yours	2015-12-26 15:25:23 +0900	2015-12-26 15:39:14 +0900
39	ハリー・ポッターと謎のプリンス	Rowling, J. K, 1965-//松岡, 佑子//Schlesinger, Dan, 1955-		静山社	2010-03	J.K.ローリング 作; 松岡佑子 訳; ダン・シュレシンジャー 画		2015-12-26 15:23:34 +0900	2015-12-26 15:28:59 +0900	http://iss.ndl.go.jp/books/R100000002-I000010816007-00			9784863890435		21729541		R100000002-I000010816007-00							933.7	""	""	39	986002							On Loan	first_shelf	yours	2015-12-26 15:25:52 +0900	2015-12-26 15:28:59 +0900
40	ハリー・ポッターと謎のプリンス	Rowling, J. K, 1965-//松岡, 佑子//Schlesinger, Dan, 1955-		静山社	2010-03	J.K.ローリング 作; 松岡佑子 訳; ダン・シュレシンジャー 画		2015-12-26 15:24:08 +0900	2015-12-26 15:26:19 +0900	http://iss.ndl.go.jp/books/R100000002-I000010816152-00			9784863890442		21729546		R100000002-I000010816152-00							933.7	""	""	40	986003							Available On Shelf	first_shelf	yours	2015-12-26 15:26:19 +0900	2015-12-26 15:26:19 +0900
41	はじめてのPerl/CGIプログラミング : Linux/Windows対応	玉川, 純, 1973-		秀和システム	2005-12	玉川純 著	2600	2015-12-26 17:51:17 +0900	2015-12-26 17:51:24 +0900	http://iss.ndl.go.jp/books/R100000002-I000008025272-00			9784798012032		20953804		R100000002-I000008025272-00			""	インターネット//プログラミング (コンピュータ)	""	""	547.483	""	""
42	基礎からわかる情報リテラシー : コンピュータ・インターネットと付き合う基礎知識	奥村, 晴彦 	奥村, 晴彦 （著）	技術評論社	2014-02	奥村晴彦 著	1480	2015-12-26 17:54:55 +0900	2016-01-03 18:11:59 +0900	http://iss.ndl.go.jp/books/R100000002-I025107686-00	http://sample.jp/zzz.html	注記・・・	9784774162133		22349643		R100000002-I025107686-00			""	aaa//bbb	ccc	""	007//007.58	""	K|a|b	41	1987501	K062||4	1900	2015-01-10 00:00:00 +0900		あさま書店	siryohi	Available On Shelf	first_shelf	yours	2016-01-03 15:37:47 +0900	2016-01-03 15:37:47 +0900
43	(adminのみ表示テスト）RailsによるアジャイルWebアプリケーション開発	Ruby, Sam//Thomas, David, 1956-//Hansson, David Heinemeier//前田, 修吾, 1975-		オーム社	2011-11	Sam Ruby, Dave Thomas, David Heinemeier Hansson 共著; 前田修吾 監訳	3200	2015-12-27 23:01:16 +0900	2015-12-27 23:01:56 +0900	http://iss.ndl.go.jp/books/R100000002-I023160370-00	""	""	9784274068669		22029781		R100000002-I023160370-00			""	ウェブアプリケーション	""	""	547.483	""	""
44	分類1							2016-01-01 12:39:33 +0900	2016-01-01 13:07:16 +0900											""	ウェブアプリケーション	""	""	008//008.58	""	""
45	分類2							2016-01-01 12:39:39 +0900	2016-01-01 13:07:18 +0900											""	ウェブアプリケーション//インターネット	""	""	""	""	AZ-464//AZ-418
46	分類3							2016-01-01 12:39:41 +0900	2016-01-01 13:07:19 +0900											""	ウェブアプリケーション	""	Internet	215	""	AZ-464
47	分類4							2016-01-01 12:39:44 +0900	2016-01-01 13:07:21 +0900											""	ウェブアプリケーション//インターネット	""	Internet	215	""	AZ-464//AZ-418
48	件名テスト1							2016-01-01 13:11:27 +0900	2016-01-01 13:11:28 +0900											""	ウェブアプリケーション	""	""			
49	件名テスト2							2016-01-01 13:11:29 +0900	2016-01-01 13:11:30 +0900											""	ウェブアプリケーション//インターネット	""	""			
50	件名テスト3							2016-01-01 13:11:31 +0900	2016-01-01 13:11:31 +0900											""	ウェブアプリケーション	""	Internet			
51	件名テスト4							2016-01-01 13:11:32 +0900	2016-01-01 13:11:33 +0900											""	ウェブアプリケーション//インターネット	""	Internet			

</pre>

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 e40e80e)
  * enju_circulation (0.2.0.beta.1 801ca1f)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 a62b817)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
