### ISSUE TITLE
「除籍」を「連続除籍」にしてはどうか？＋冒頭に説明を追加

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#858]
http://localhost:8080/withdraws

この「除籍の一覧」は、この除籍の機能をつかって除籍にした一覧で、
「除籍」状態になっているものの一覧ではないので、まぎらわしです。
そこで「除籍」を「連続除籍」という名前にしてはどうでしょうか？

そして、下の図の黄緑四角のあたりに、
説明書きと、「除籍済み」状態になっているものの一覧へのリンクをつけてあげると
紛らわしくなくてよいとおもいます。

例えば、以下のような文章を挿入しておくとよいとおもいます。

ここは、「連続除籍」機能でバーコードを読んで実行したものが一覧されています。
所蔵情報の編集で「除籍済み」にしたものや書誌・所蔵のインポート機能で「除籍済み」にしたものなどは含まれていません。
除籍をしたもの全てを一覧するには、<a href="http://localhost:8080/items?circulation_status=Removed">除籍済み所蔵の一覧</a>を参照してください。

http://localhost:8080/withdraws
![image](https://cloud.githubusercontent.com/assets/1328499/10414573/05c71498-7016-11e5-8995-66dcf730e5ff.png)

http://localhost:8080/withdraws/new
![image](https://cloud.githubusercontent.com/assets/1328499/10414575/2201c8ce-7016-11e5-8625-80acd70f62e9.png)

http://localhost:8080/page/configuration
![image](https://cloud.githubusercontent.com/assets/1328499/10414578/37e9eefa-7016-11e5-96ca-aa02814d1742.png)

**Comment by masao** [comment]
ラベルは変えてみました。

**Comment by masao** [comment]
英語をどうするかねえ…。

**Comment by yegusa** [comment]
consecutively　とか successive とか sequential あたり？

**Comment by masao** [comment]
英語ラベル： Bulk Withdraw
英語文例：
Listing Withdraw shows the items marked as removed by using this function. Items marked removed by other editing functions are not listed. Please go to the Listing Items for all the items removed.

あたりかでしょうか。。。

**Comment by yegusa** [comment]
英語についてはお任せします→ @masao 

連続除籍になっていることを確認しました。
説明書きについては、ちょっとカッコ悪いので、右メニューに「除籍済みの一覧」をつけることで
代用するのでよいかなと思い始めました。そちらは別issue #859 にしておきます。

![image](https://cloud.githubusercontent.com/assets/1328499/10420630/301445b4-70d3-11e5-9d7f-a7f859745f2a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10420639/4eccc9fe-70d3-11e5-89bf-a00244eacd5a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10420624/17376788-70d3-11e5-85fd-740a299bcf70.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 d79b3f8)
  * enju_circulation (0.1.0.pre48 549e848)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 a7dcb40)
  * enju_leaf (1.1.0.rc21 48b4dbb)
  * enju_library (0.1.0.pre44 58b609e)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
残っているのは、英語のラベルを変えることです。

* [ ] 開発（英語のほうのラベル）
* [ ] 確認

**Comment by masao** [comment]
英語のほうも変えました。
https://github.com/next-l/enju_library/commit/09269a0fce6d48eadbf3b977aa4e79e13a6ac3bc

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10443553/613e32e8-7197-11e5-85d3-a8d890beebf6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10443531/4b3f328a-7197-11e5-9fe3-f114332c91a5.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10443521/29e562bc-7197-11e5-8992-801fb7f6f593.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
