### ISSUE TITLE
「除籍済みの一覧」へのリンクを右メニューに付けてほしい（連続除籍の「新規」と「一覧」画面）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#859]
#858 から派生です。

* アンカー名： 除籍済みの一覧
* リンク先： http://localhost:8080/items?circulation_status=Removed

### 新規作成の画面 http://localhost:8080/withdraws/new
![image](https://cloud.githubusercontent.com/assets/1328499/10420549/469cd8b6-70d1-11e5-8020-4f7e7f49b0d0.png)

### 一覧の画面 http://localhost:8080/withdraws
![image](https://cloud.githubusercontent.com/assets/1328499/10420532/fe29e614-70d0-11e5-8495-262949613a87.png)

### 除籍済みの一覧をクリックした先 http://localhost:8080/items?circulation_status=Removed
![image](https://cloud.githubusercontent.com/assets/1328499/10420590/696802ca-70d2-11e5-8a66-368302fda59f.png)

**Comment by masao** [comment]
追加してみました。

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10443603/bbd7b026-7197-11e5-8724-c4eeb84da39d.png)
![image](https://cloud.githubusercontent.com/assets/1328499/10443615/e52fed6c-7197-11e5-9ace-d69d7e2fa34c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10443612/dc01df7a-7197-11e5-98cf-70891ae77bd0.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
