### ISSUE TITLE
「連続除籍」したときに、利用制限が「通常期間貸出」のままです

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#860]
貸出不可になっているべきです。

![image](https://cloud.githubusercontent.com/assets/1328499/10444076/f789a0ca-719c-11e5-9856-f1ecda8bdc20.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
メモ：マニュアルは、ブラウザの開発ツールを使って修正して、バグが修正された前提の画面をすでに差し込んでありますので、マニュアル修正はないです。なので、必ず修正お願いします！

**Comment by nabeta** [comment]
修正しました。

**Comment by yegusa** [comment]
「貸出不可」にはなるようになりましたが、
今度は、「除籍済み」ならなくなりました。

![image](https://cloud.githubusercontent.com/assets/1328499/10461519/abdaf624-7214-11e5-83b2-b1a00dca4463.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10461589/f7663ea0-7214-11e5-95fb-d042af5d97eb.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 e9145d5)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
あれ、テストは通るのですが。ともかく、貸出状態の変更を修正しました。

**Comment by yegusa** [comment]
じゃあ、テストが足りなかったんでしょう。合わせて、テストは修正しましたでしょうか？
できることを確認しましたのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10473049/c837a5a4-7261-11e5-8e3e-5b034cc27294.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10473053/d11b833e-7261-11e5-96a4-7b691cc4e288.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 5e6e472)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
