### ISSUE TITLE
「連続除籍」したレコードのファセットでの値は「在架（利用可能）」のままです

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#861]
例： 888101 を連続除籍機能で除籍したあとに、所蔵情報の一覧で 88101 を検索したところ
![image](https://cloud.githubusercontent.com/assets/1328499/10444804/299a4094-71a5-11e5-90d2-cb6766f983d7.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 c74c6a3)
  * enju_circulation (0.1.0.pre48 f68abca)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
Solrのインデックスを更新するようにしました。

**Comment by yegusa** [comment]
できるようになったことを確認したのでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10457478/7c98e32a-7201-11e5-8ad1-c0c7478b4a12.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7f7c996)
  * enju_circulation (0.1.0.pre48 013fa10)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
