### ISSUE TITLE
「所蔵情報の表示」で「貸出規則」というなにも表示されない項目がある

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#862]
![image](https://cloud.githubusercontent.com/assets/1328499/10445806/5eafed44-71b2-11e5-9b95-018bfbcede5a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.0.pre69 c74c6a3)
- enju_circulation (0.1.0.pre48 f68abca)
- enju_event (0.1.17.pre26 3f14e24)
- enju_flower (0.1.0.pre23 d42b99d)
- enju_leaf (1.1.0.rc21 10d824b)
- enju_library (0.1.0.pre44 991cee9)
- enju_loc (0.1.0.pre5 443805a)
- enju_manifestation_viewer (0.1.0.pre19 e76a52c)
- enju_message (0.1.14.pre25 155ea82)
- enju_ndl (0.1.0.pre37)
- enju_nii (0.1.0.pre13 ff350da)
- enju_oai (0.1.0.pre19 5c357c9)
- enju_purchase_request (0.1.0.pre14 dabe027)
- enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
項目を非表示としました。

![image](https://user-images.githubusercontent.com/11428/56986870-e7e8c880-6bc6-11e9-8320-0446bbda25f5.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/57978254-702ef080-7a44-11e9-9c6a-033c3a8229a8.png)

**Comment by yegusa** [comment]
所蔵の作成のマニュアルの画像は差し替えた。
除籍や検定の画像は差し替えていないが良いことにする。
