### ISSUE TITLE
TSVインポートで所蔵情報の更新をやると「請求記号」が消えてしまう

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#863]
### 元々：
![image](https://cloud.githubusercontent.com/assets/1328499/10445868/42be8f7c-71b3-11e5-9242-3b40838f298b.png)

### TSVインポートで所蔵情報の更新をやる

<pre>
item_identifier	use_restriction	circulation_status
888201	Not For Loan	Removed
</pre>

### 結果：請求記号が消えてしまう。

![image](https://cloud.githubusercontent.com/assets/1328499/10445882/6fc7e9d2-71b3-11e5-81d6-4da01b1861d0.png)

**Comment by nabeta** [comment]
修正しました。

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/10461850/5749d8e4-7216-11e5-8680-7b52a21e0683.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10461856/602293c0-7216-11e5-8128-19489d07fff7.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 8fb56f6)
  * enju_circulation (0.1.0.pre48 e9145d5)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 69a2ba3)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)
