### ISSUE TITLE
製本所蔵情報IDでも検索できるようにしてほしい（これは図書対象ということにします）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#864]
製本後の所蔵情報ID 9999001
![image](https://cloud.githubusercontent.com/assets/1328499/10447278/2418f55c-71be-11e5-9ebe-15c2f7c0a864.png)

製本後の所蔵情報ID 9999001　で検索してもヒットしない
![image](https://cloud.githubusercontent.com/assets/1328499/10447266/089d427e-71be-11e5-9b8a-887d833d5b79.png)

**Comment by yegusa** [comment]
雑誌は、取り扱いが違うから、所蔵情報で検索してもヒットしないのか。
元々。

例：所蔵情報IDで検索したところ
![image](https://cloud.githubusercontent.com/assets/1328499/10447514/ebeccb7a-71bf-11e5-898f-6392c16a499d.png)

**Comment by nabeta** [comment]
インデックスに追加するようにしました。以下のコマンドによるインデックスの再作成が必要です。

```sh
$ rake sunspot:reindex RAILS_ENV=production
```

**Comment by yegusa** [comment]
雑誌あつかにになっていない普通の本は検索できるようになっていることを確認しました。
しかし、これだけだと、あんまし意味ないのよね。雑誌ができないと。。。
どうするのがよいのでしょうかね？

![image](https://cloud.githubusercontent.com/assets/1328499/10456281/81c0ea42-71fb-11e5-9d0e-13dd674de6e9.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10456312/a92cac56-71fb-11e5-9c58-6bf0b71fa02b.png)

![image](https://cloud.githubusercontent.com/assets/1328499/10456325/befa2b4e-71fb-11e5-98d4-cbf4dd5793b4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7f7c996)
  * enju_circulation (0.1.0.pre48 013fa10)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by yegusa** [comment]
というわけで、これは　図書対象のというにして、いったんクローズします。
