### ISSUE TITLE
予約リンクの出現する条件を詳細に教えてください

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#867]
（すみません、どこかで教えてもらった気もしますが、みつけられません）

マニュアルに書きたいのでおしえてください。
（いま、user権限でログインしたら表示されなくてじみに困っています）

**Comment by nabeta** [comment]
処理は以下の部分です。
https://github.com/next-l/enju_circulation/blob/1.1/lib/enju_circulation/manifestation.rb#L31

チェックするのは以下の3点です。

1. 所蔵の貸出状態が「在架」になっているかどうか
2. ユーザの権限が図書館員か一般利用者か
3. 一般利用者の場合、「対象の資料の所蔵数」と「所蔵数 - そのユーザの延滞冊数」が等しいか

…と書いたのですが、3番がどういう意図でこうなっているのか、自分でもよくわかりません。

**Comment by yegusa** [comment]
確かに、 3番は意味不明ですね。。。

**Comment by nabeta** [comment]
おそらく「延滞していたら予約ができない」ようにしたかったのだと思いますが、こういうのは一般的なんでしょうかね。オプションで選択できるようにするのがいいような気がするのですが。

**Comment by yegusa** [comment]
そのルールではあるのに、予約がでないのがあるのですよねえ。んー、他になにかなんかあるんだと思うのですが。

**Comment by yegusa** [comment]
バグのほうは別のissue #868 にあげているので、こっちはひとまずクローズします。
