### ISSUE TITLE
User権限でログインしたときに「予約」リンクがでません。

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#868]
- [ ] 確認
- [ ] マニュアル修正 #1191
#867 にも関連しますが、バグかもしれないのでこちらでも。
### user　だと予約リンクがでない

つくったばかりのユーザーなので、貸出なにもしていない（つまり、延滞などはしていない）
![image](https://cloud.githubusercontent.com/assets/1328499/10448866/b1989a70-71ca-11e5-82ad-8386049946e4.png)

　ちなみに、同じユーザーをlibrarian 権限に変更すると

![image](https://cloud.githubusercontent.com/assets/1328499/10448961/686fecee-71cb-11e5-973a-c38fc7bbcda8.png)

でるようになる
![image](https://cloud.githubusercontent.com/assets/1328499/10448910/0211663a-71cb-11e5-9888-2ee3fb0e0519.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.0.pre69 c74c6a3)
- enju_circulation (0.1.0.pre48 f68abca)
- enju_event (0.1.17.pre26 3f14e24)
- enju_flower (0.1.0.pre23 d42b99d)
- enju_leaf (1.1.0.rc21 10d824b)
- enju_library (0.1.0.pre44 991cee9)
- enju_loc (0.1.0.pre5 443805a)
- enju_manifestation_viewer (0.1.0.pre19 e76a52c)
- enju_message (0.1.14.pre25 155ea82)
- enju_ndl (0.1.0.pre37)
- enju_nii (0.1.0.pre13 ff350da)
- enju_oai (0.1.0.pre19 5c357c9)
- enju_purchase_request (0.1.0.pre14 dabe027)
- enju_subject (0.1.0.pre33 30d8b0f)
- [ ] http://next-l.github.io/manual/assets/images/image_operation_accept_5.png を差し替える。

**Comment by yegusa** [comment]
出てるものもあるので、なにが問題なのか。。。。

![image](https://cloud.githubusercontent.com/assets/1328499/10449154/a02478e8-71cc-11e5-9bf2-78558574964a.png)

**Comment by yegusa** [comment]
666101のほうは、
所蔵の「注記」になんかてきとうにかいて書いて、[更新]ってやったら「予約」がでてくるようになった！
888301 はどうやってつくったかなあ。普通につくったとおもうのだけどなあ。

![image](https://cloud.githubusercontent.com/assets/1328499/10458123/3e7b2e60-7204-11e5-9b2f-811bbd1201ea.png)

**Comment by yegusa** [comment]
@masao さんによると、キャッシュまわりがあやしいとのこと。
@masao さん、詳細よろしく。

**Comment by yegusa** [comment]
キャッシュまわりは、1.1.0だと厳しいかな。そのコメントと milestone　の（必要なら）変更も含めて、 @masao さんよろしく。

**Comment by masao** [comment]
テストコードを途中まで書いたのですが、原因特定まで行っていませんので、マイルストーンを延長させてください。先送りしましょう。

**Comment by yegusa** [comment]
了解です。

**Comment by nabeta** [comment]
@yegusa 1.4系では、ローカルの開発環境・デモサーバとも不具合が再現しない状態です。

**Comment by masao** [comment]
いずれにしても再現ができていないようなので、ひとまずクローズしましょう
