### ISSUE TITLE
画像ファイルの編集画面を画像ファイルだけ修正できるようにする

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#869]
Rails のデフォルトまんまな風味で、これ、修正して更新する　とやるとまずいことがおきそうな
雰囲気がしている。

http://localhost:8080/picture_files/1/edit
![image](https://cloud.githubusercontent.com/assets/1328499/10452965/9ef03748-71e3-11e5-95bc-c8ce70a38f04.png)

てか、この編集画面いる？

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.0.pre69 c74c6a3)
- enju_circulation (0.1.0.pre48 f68abca)
- enju_event (0.1.17.pre26 3f14e24)
- enju_flower (0.1.0.pre23 d42b99d)
- enju_leaf (1.1.0.rc21 10d824b)
- enju_library (0.1.0.pre44 991cee9)
- enju_loc (0.1.0.pre5 443805a)
- enju_manifestation_viewer (0.1.0.pre19 e76a52c)
- enju_message (0.1.14.pre25 155ea82)
- enju_ndl (0.1.0.pre37)
- enju_nii (0.1.0.pre13 ff350da)
- enju_oai (0.1.0.pre19 5c357c9)
- enju_purchase_request (0.1.0.pre14 dabe027)
- enju_subject (0.1.0.pre33 30d8b0f)

Todo:
- [ ] 開発：編集画面にアクセス不可にする http://localhost:8080/picture_files/1/edit
- [ ] ↑確かめる
- [ ] 画像ファイルの一覧 の [編集] リンクを消す http://localhost:8080/picture_files　
- [ ] ↑確かめる
- [ ] 画像ファイルの表示の [編集] リンクを消すhttp://localhost:8080/picture_files/1
- [ ] ↑確かめる
- [ ] マニュアルの修正

**Comment by nabeta** [comment]
> てか、この編集画面いる？

いらないです。アクセスできないようにしておきます。

**Comment by yegusa** [comment]
アクセスできないようにしたら、ここでコメントで教えてください。よろしく～。

**Comment by yegusa** [comment]
編集画面そのものをアクセスできないようにすることに方針転換ですね。

**Comment by yegusa** [comment]
現状メモ：
http://localhost:8080/picture_files/1/edit
![image](https://cloud.githubusercontent.com/assets/1328499/10457223/511c5a20-7200-11e5-976f-da363dd98921.png)

http://localhost:8080/picture_files/1
![image](https://cloud.githubusercontent.com/assets/1328499/10457240/66df757c-7200-11e5-9bb2-3326eae8d10d.png)

http://localhost:8080/picture_files?manifestation_id=8
![image](https://cloud.githubusercontent.com/assets/1328499/10457258/79b93ea8-7200-11e5-84cc-155c9f4fda89.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre69 7f7c996)
  * enju_circulation (0.1.0.pre48 013fa10)
  * enju_event (0.1.17.pre26 3f14e24)
  * enju_flower (0.1.0.pre23 d42b99d)
  * enju_leaf (1.1.0.rc21 10d824b)
  * enju_library (0.1.0.pre44 991cee9)
  * enju_loc (0.1.0.pre5 443805a)
  * enju_manifestation_viewer (0.1.0.pre19 e76a52c)
  * enju_message (0.1.14.pre25 155ea82)
  * enju_ndl (0.1.0.pre37)
  * enju_nii (0.1.0.pre13 ff350da)
  * enju_oai (0.1.0.pre19 5c357c9)
  * enju_purchase_request (0.1.0.pre14 dabe027)
  * enju_subject (0.1.0.pre33 30d8b0f)

**Comment by nabeta** [comment]
やっぱり画像だけでも差し替えられるようになっていたほうがいいかなあ、と思います。
フォームには画像のアップロードボタンのみが残る感じです。

**Comment by yegusa** [comment]
@nabeta さん、イメージがわきません、画面案よろしく。

**Comment by nabeta** [comment]
以下のような感じです。現在の画像も編集画面に表示したほうがよいかもしれません。
https://enju.next-l.jp/picture_files/6/edit
<img width="300" alt="スクリーンショット 2019-05-01 13 43 55" src="https://user-images.githubusercontent.com/11428/57005945-3d4cc600-6c17-11e9-854c-27e1d7754ec9.png">

**Comment by nabeta** [comment]
以下のように、編集画面に現在の画像のプレビューを表示するようにしました。
https://enju.next-l.jp/picture_files/6/edit

![image](https://user-images.githubusercontent.com/11428/80271375-a7009280-86fa-11ea-8d2d-0bcdb2aff7ff.png)

本当はフォームでファイルを選択したときに、新しい画像に差し替わるといいのですが、そこまでは実施していません。

**Comment by masao** [comment]
画像ファイルの編集画面から画像を更新できるようになったことを確認しました。
