### ISSUE TITLE
ISBNインポートで版情報の取り込みができない

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#874]
http://iss.ndl.go.jp/books/R100000002-I025107686-00 を取り込んだ際に版情報（改訂第2版）が取り込まれず。

**Comment by masao** [comment]
版項目を取り込むように修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12005779/ed22f2ca-abf9-11e5-97d6-39afbf54ad0c.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12005774/e4c30db8-abf9-11e5-8cb4-8a80fd735238.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 0948f53)
  * enju_circulation (0.2.0.beta.1 4fb098c)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 e2d900e)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 2253b1a)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
