### ISSUE TITLE
「協力者・編者」が登録されている書誌を削除できない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#875]
http://dev.next-l.jp/manifestations/24420

ログには以下のエラーが出る。

```
ActiveRecord::StaleObjectError (Attempted to destroy a stale object: Manifestation):
  vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.1/lib/active_record/locking/optimistic.rb:118:in `destroy_row'
```

**Comment by nabeta** [comment]
開発サーバには修正を反映済みです。

**Comment by yegusa** [comment]
確認しましたのでクローズします。

協力者がいる書誌　を削除しようとしている
http://localhost:8080/manifestations/113
![image](https://cloud.githubusercontent.com/assets/1328499/11058792/966f38ea-8795-11e5-9cd5-39c26e97f06e.png)

削除されました
![image](https://cloud.githubusercontent.com/assets/1328499/11058817/be4ac4b0-8795-11e5-8f4c-1146f384b801.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre71 a1acf61)
  * enju_circulation (0.1.0.pre49 56b552c)
  * enju_event (0.1.17.pre27 696d92a)
  * enju_flower (0.1.0.pre24 e40ab27)
  * enju_leaf (1.1.0.rc22 b3965e5)
  * enju_library (0.1.0.pre45 6b344b3)
  * enju_loc (0.1.0.pre5 8e78c85)
  * enju_manifestation_viewer (0.1.0.pre19 65bc8b9)
  * enju_message (0.1.14.pre26 be82ed6)
  * enju_ndl (0.1.0.pre38)
  * enju_nii (0.1.0.pre14 18c57a7)
  * enju_oai (0.1.0.pre20 802911d)
  * enju_purchase_request (0.1.0.pre15 2cd3147)
  * enju_subject (0.1.0.pre34 dee91b1)
