### ISSUE TITLE
書誌情報にこれまでの貸出回数（累計）を表示して欲しい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#877]
- [ ] #1248 マニュアル修正

公共図書館において、除籍する際の判断等のために重要（南三陸からの要望あり）。

**Comment by nabeta** [comment]
詳細画面（Librarian権限時）とエクスポートされるTSVにあればよいでしょうか。

**Comment by masao** [comment]
はい、それでよいように思います。

**Comment by masao** [comment]
南三陸町から改めて要望あり。

**Comment by masao** [comment]
https://github.com/next-l/enju_biblio/commit/0a259aa10604d978863ac47e05aecc8d97383cd0 にて実装しました。確認願います。

**Comment by yegusa** [comment]
できることを確認したので、クローズします。
マニュアルはあとで修正します。
エクスポートについては別issueにします。

詳細画面を表示：貸出回数が表示されている
![image](https://cloud.githubusercontent.com/assets/1328499/22394437/8062e140-e564-11e6-8548-47626f5391e5.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0 002806a)
  * enju_bookmark (0.2.0)
  * enju_circulation (0.2.0 9daf9cb)
  * enju_event (0.2.0)
  * enju_leaf (1.2.0 a25e1bf)
  * enju_library (0.2.1 c75a94a)
  * enju_loc (0.2.0 071f2b3)
  * enju_manifestation_viewer (0.2.0 f1fddb6)
  * enju_message (0.2.0)
  * enju_ndl (0.2.0 da6beb7)
  * enju_nii (0.2.0 03c3dc4)
  * enju_oai (0.2.0 6e5cd6d)
  * enju_purchase_request (0.2.0)
  * enju_seed (0.2.0)
  * enju_subject (0.2.0)
