### ISSUE TITLE
利用者詳細ページにおける貸出情報は新しいものを上に出して欲しい

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#878]
現在は古いものから順に表示されるため、最新の貸出情報を見るには最後のページに移る必要がある。クリックが多くなるのでカウンターでの問い合わせ作業に手間が多い（南三陸からの要望）。

**Comment by yegusa** [comment]
以前は新しいものからでていたはず by 南三陸町　とのこと。
どっかで変わったようです。

**Comment by masao** [comment]
enju_circulation側でデフォルトソート順を修正しました。確認願います。

**Comment by nabeta** [comment]
@yegusa 利用者詳細画面での貸出情報は以下で取得しているのですが、表示順序は特に指定していませんでした。つまり、以前はたまたま新しい順に表示されていたようです。
https://github.com/next-l/enju_leaf/blob/1.1/app/views/profiles/show.html.erb#L28

@masao default_scopeは思わぬ副作用が発生する場合があるので（以下を参照）、貸出一覧の取得時、つまり上記の行で明示的に順番を指定するように変更させていただけますか。
http://qiita.com/yusabana/items/f0b3a80111d6bd4ec8b0

**Comment by masao** [comment]
@nabeta そうですね。確かに副作用が既にありました。。。

**Comment by nabeta** [comment]
開発サーバに修正を反映しましたので、確認していただけますでしょうか。

**Comment by yegusa** [comment]
新しいものが一番上にあることを確認しましたので、
一旦クローズします。

http://localhost:8080/profiles/19
![image](https://cloud.githubusercontent.com/assets/1328499/11058652/8f018faa-8794-11e5-8cae-b898a40924c4.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.0.pre71 a1acf61)
  * enju_circulation (0.1.0.pre49 56b552c)
  * enju_event (0.1.17.pre27 696d92a)
  * enju_flower (0.1.0.pre24 e40ab27)
  * enju_leaf (1.1.0.rc22 b3965e5)
  * enju_library (0.1.0.pre45 6b344b3)
  * enju_loc (0.1.0.pre5 8e78c85)
  * enju_manifestation_viewer (0.1.0.pre19 65bc8b9)
  * enju_message (0.1.14.pre26 be82ed6)
  * enju_ndl (0.1.0.pre38)
  * enju_nii (0.1.0.pre14 18c57a7)
  * enju_oai (0.1.0.pre20 802911d)
  * enju_purchase_request (0.1.0.pre15 2cd3147)
  * enju_subject (0.1.0.pre34 dee91b1)
