### ISSUE TITLE
書誌ファイルのインポートができない

### ISSUE THREAD

**Issue by takes2** [next-l/enju_leaf#88]
インストール手順通り行いましたが、
TSVファイルで書誌データのインポートをしようとしていますが、
1.1.rc7でも1.20 devでも
rake aborted!
Don't know how to build task 'enju:import:files'
とログに出ており、インポートができません。

設定を確認すべき点を教えていただけますでしょうか。

**Comment by nabeta** [comment]
古いイシューのため、クローズします。
