### ISSUE TITLE
検索の異体字対応

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#880]
誤解かもしれませんが，えんじゅ図書館のデモを見ると，漢字の異体字を同一視して検索する機能が無さそうです。
「内田百閒／百間」「森鷗外／鴎外」の類いは，どちらの表記も書誌情報としてふつうに存在するので，この機能が無いとつらいと思います。

どの字とどの字を異体字とみなすかは，突き詰めると難しいですが（サイ藤さんの斉／斎は本来別字；著／着やレン合艦隊の聯／連，はたまた中文簡体字の机／機はどうするのかとか），とりあえずさっくりと普通の異体字表に従ってみるのはどうでしょうか。
あるいは，そこに斉／齊／斎／齋などは異体字扱いにしてしまうなどの若干の修正を加えるとか。

**Comment by nabeta** [comment]
異体字はEnju本体ではなく、検索サーバで使用しているSolrで扱うことを想定しています。以下の記事が参考になると思います。
http://www.zuki-ebetsu.jp/blog/2009/03/23/1237775605/

現状では、このマッピング表を自分で作成するか、できあいの表をもらってきて使用することになります。Enjuでの設定方法はどこかに書いたほうがよいですね。

**Comment by scivola** [comment]
分りました。（って，よく分っていませんけど）

リンク先を拝見して，やり方を↓こんなふうに推測しましたが，だいたい合っていますでしょうか。

1. まず，どこかから異体字データを拾ってくる。例えば，[漢字データベースプロジェクト](http://kanji-database.sourceforge.net/) の [variants.txt](http://kanji-database.sourceforge.net/variants/variants.txt)
1. 必要なら修正（別ファイルも可）
1. そこから，Solr のマッピングファイル形式のテキストファイル（"嶋" => "島" とかが改行区切りで並んだもの？）を作る。
1. enju_leaf のしかるべきところに入れる（場所は lib/generators/enju_leaf/setup/templates/solr/conf でしょうか？）
1. lib/generators/enju_leaf/setup/templates/solr/conf/schema.xml の fieldType[name="text"]/analyzer の下に charFilter  要素を置く。
1. charFilter  の書き方は <charFilter class="solr.MappingCharFilterFactory" mapping="マッピングファイル名"/>
1. ファイル名はカンマ区切りで併記可

enju_leaf 本体にせめてサンプルファイルだけでも入っていると嬉しいような気がします。

**Comment by nabeta** [comment]
> 4. enju_leaf のしかるべきところに入れる（場所は lib/generators/enju_leaf/setup/templates/solr/conf でしょうか？

通常のインストール手順の場合、Enjuをインストールしたディレクトリにsolr/confディレクトリができますので、そこに保存することになります。

> 5. lib/generators/enju_leaf/setup/templates/solr/conf/schema.xml の fieldType[name="text"]/analyzer の下に charFilter 要素を置く。

これも同じく、Enjuをインストールしたディレクトリにsolr/confディレクトリができますので、その中にあるschema.xmlを編集します。

**Comment by scivola** [comment]
ありがとうございました。あとで試してみます。
デモサイト（[http://enju.next-l.jp/](http://enju.next-l.jp/)）にも設定されているといいかなと思いました。
私のように「Enju の実力やいかに」と思ってデモを試して，「ダメじゃん」と勘違いする人が少なくないと思うからです。

**Comment by scivola** [comment]
試してみたらできました。
マッピングファイルを置いて schema.xml を編集したあと，Solr に何か難しいことをしないといけないのかと思ったら，VirtualBox の仮想マシンを再起動するだけで効きました。

あとはインストールマニュアルに手順を追加すればいいと思いますが，原案を書きましょうか？

**Comment by masao** [comment]
:+1: 素晴らしいです。お願いできると大変助かります！

**Comment by scivola** [comment]
マニュアルへの追記は，原稿案を書いて next-l/manual のほうに issue を立てましたので，こちらはクローズしていただいていいかと思います。
https://github.com/next-l/manual/issues/64

**Comment by yegusa** [comment]
では、こちらはクローズします。

**Comment by scivola** [comment]
クローズされているはずなのでします。
