### ISSUE TITLE
ISBN 表示にハイフンを

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#881]
manifestations/:id の表示で，「識別子」のところの ISBN の表示が

> ISBN: 9784860643638 

のようにハイフン抜きなのですが，これは人間にはかなり辛いです。

Enju で使用している lisbn gem には，ずばり `Lisbn#isbn_with_dash` メソッドがあるので，これを使えばいいのではないでしょうか。

もちろん，いつどんな ISBN が来ても分割ができるためには，常に International ISBN Agency が公表する最新の ISBN Ranges データを保持する必要がありますが（lisbn の [readme](https://github.com/ragalie/lisbn) の「Updating」に従う）。

- [ ] 確認
- [ ] マニュアル記述

**Comment by nabeta** [comment]
たしかにそのほうがいいかなあと思うのですが、ほかの方はいかがでしょう？

**Comment by yegusa** [comment]
ハイフン有　で表示するので、よいとおもいますよ。

enju でハイフン有で検索してもヒットするんですよね?

**Comment by masao** [comment]
わたしも表示そのものはよいように思います。
ただ、検索のほうとあわせる必要がありそうなので、ハイフンの有無の両方をインデクシングに入れておくとよいように思います。

**Comment by nabeta** [comment]
ISBNにハイフンを表示するようにしました。開発サーバに反映済みです。
http://dev.next-l.jp/manifestations/24422

**Comment by nabeta** [comment]
ちなみに、でたらめなISBNを入れても、エラーにはならないようです。

```ruby
irb(main):002:0> Lisbn.new('34545254543534').isbn_with_dash
=> "3454525454353-4"
```

**Comment by scivola** [comment]
ISBN として正しくない 13 桁数字列でインスタンスが作れてしまうのは，`Lisbn#valid?` で検証ができるようにするためではないでしょうか。

```rb
 Lisbn.new("34545254543534").valid? #=> false
```

Enju では正しくない ISBN 文字列は library_stdnums gem の `StdNum::ISBN.valid?` で検証してデータベースには格納されないようになっているわけですよね？

なお，ISBN Ranges データを定期的に更新しなければなりません。
そのための Rake タスク（か何か）があるべきだし，運用マニュアルにも更新方法を記述すべきかと思います。

**Comment by tzhaya** [comment]
チェックデジットの不正などで「正しくない」ISBNであっても、資料現物にそう書かれている以上は検索のキーとなる可能性があるので、何らかの形で残した方がよいかと思います。
NACSIS-CATでは正しいものをISBNに、目録対象資料にかかわる取消/無効ISBNはXISBNに格納しています。
http://catdoc.nii.ac.jp/MAN2/CM/2_1_14.html

**Comment by yegusa** [comment]
> NACSIS-CATでは正しいものをISBNに、目録対象資料にかかわる取消/無効ISBNはXISBNに格納しています。

こういう感じで残せるのがベターですね。

**Comment by scivola** [comment]
13桁切り替えのとき，頭に「978-」を付ければよいと誤解した出版社と「そんな ISBN を印刷するわけにいかない」とする印刷会社がやりあう現場を知っています。
この時期（2006〜2007 年）の ISBN は怪しいです。
それと書籍JANコードが1990年に制定され普及するまでは，ISBN はおそらく目視で校正するだけが普通だったので，けっこう間違いがあったのではないでしょうか。
books.or.jp でいくつか不正な ISBN を見つけたことがあります。

このチケット，私が起票者ですが，閉じてよいのか分からないのでコアの方がたお願いします。

**Comment by masao** [comment]
うーん、以前のバージョン（2年くらい前）では wrong_isbn というフィールドをManifestationに持たせていたんですが。。。
cf. https://github.com/next-l/enju_biblio/blob/v0.1.0.pre37/app/models/manifestation.rb
識別子Identifierモデルに移行したタイミングで消したのですね。。。

**Comment by nabeta** [comment]
そもそもISBNやらDOIやら、バリデーションの規則が異なる識別子を、全部Identifierモデル（とidentifiersテーブル）で扱おうとしているのが間違いで（自分がやったんですが）、かえってモデルが複雑になってしまい、wrong_isbnの扱いのような抜けが出てきてしまっています。ISBNはISBN、DOIはDOIで別モデル（別テーブル）を用意したほうがよさそうです。

**Comment by nabeta** [comment]
ひとまず表示と検索はできているので、このissueはcloseしてもよいと思います。モデル分割とISBNの誤りの扱いは別件としましょう。

**Comment by yegusa** [comment]
とりあえず、issueを立てておきました。
こちらは、「ハイフンで表示」についてのみとしましょう。
開発はできているみたいなので、あとはできていることを確認できたらクローズしていいですね。

**Comment by yegusa** [comment]
ハイフン付きで表示されることを確認しましたのでクローズします。
（マニュアルは後で修正します（ま、細かいところだからしないかも））

○　ハイフン付きで表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11994178/a1e9bbea-aa7d-11e5-81c1-da7f544ab25a.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
