### ISSUE TITLE
書誌詳細ページにてJavaScriptエラー

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#883]
検索結果以外を経由してページ表示した際に、JavaScriptエラーが出ます。
おそらく「前へ」「次へ」のリンクをとってくるところで出ているものと思われます。

デモサーバ、開発サーバの双方で確認しました（下記は開発サーバでの例）。
![image](https://cloud.githubusercontent.com/assets/38825/10989693/11f50770-848e-11e5-9c61-b33780869a33.png)

**Comment by nabeta** [comment]
デモサーバで修正を反映しましたので、もう一度確認していただけますでしょうか。

**Comment by masao** [comment]
![image](https://cloud.githubusercontent.com/assets/38825/11035646/07953d9e-8737-11e5-8001-167012af7106.png)
なおっていないようです。

**Comment by nabeta** [comment]
手元の環境では再現しません。以下はOSXとChromeで、キャッシュを削除して再度読み込んだ画面です。

![2015-11-10 1 56 56](https://cloud.githubusercontent.com/assets/11428/11040193/67e97c16-874e-11e5-8b5b-5920b2a45d3c.png)

**Comment by masao** [comment]
@nabeta さんが見ている画面はエラー画面と違うようです。
要はsessionStorageに情報が保存されており、かつ、その情報の中に当該IDが保存されていない状態でエラーが出ます。

**Comment by nabeta** [comment]
再現手順を示していただけますでしょうか。

**Comment by yegusa** [comment]
@masao さん　よろしく。

**Comment by masao** [comment]
再現手順：

1. トップページから「test」で検索する（これでsessionStorageに検索結果情報が保存される）
    http://dev.next-l.jp/manifestations?query=test
2. 検索結果とは無関係のページに移動する
    http://dev.next-l.jp/manifestations/24422

以上です。

**Comment by nabeta** [comment]
OSXのSafari, Firefox, Chromeで試したのですが、やはり再現しません。

> 検索結果とは無関係のページに移動する

これは直接URLをアドレス欄に入れていますか？

**Comment by masao** [comment]
> これは直接URLをアドレス欄に入れていますか？
はい。

**Comment by masao** [comment]
とりあえずエラーが出ないように修正しました。

**Comment by yegusa** [comment]
とりあえず、原因不明ですが、まあ、いいことにしていったんクローズしましょう。
また起きたらリオープンしましょう。


ハリー　で検索　4件ヒット
![image](https://cloud.githubusercontent.com/assets/1328499/12069735/3f6fdee0-b08b-11e5-8ae9-62268f6482ff.png)

ブラウザのアドレス欄に直接URLをコピペして
![image](https://cloud.githubusercontent.com/assets/1328499/12069741/ccf66392-b08b-11e5-910f-68421bd06128.png)

関係ない資料の詳細を表示
![image](https://cloud.githubusercontent.com/assets/1328499/12069743/f3f50872-b08b-11e5-8211-a4032e037a1e.png)

特にエラーはでてない模様
![image](https://cloud.githubusercontent.com/assets/1328499/12069747/4b21ff42-b08c-11e5-8397-06e15d477e27.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 9ebdf6f)
  * enju_circulation (0.2.0.beta.1 7994f3b)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 ac6500e)
  * enju_library (0.2.0.beta.1 d6e53e6)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.2.0.beta.1 ab17d9f)
  * enju_subject (0.2.0.beta.1 237251b)
