### ISSUE TITLE
NDLサーチ検索によるインポートで失敗する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#884]
NDL サーチ検索によるインポートで失敗するケースがあるようです。

http://enju.next-l.jp/
において，「NDL サーチ検索によるインポート」から「圕」で検索すると，いくつか出てきますが，その中の「圕用品研究」の「追加」ボタンを押すと，しばらくして

> We're sorry, but something went wrong.

の画面になります。どこかの過程で失敗しているようです。
再び「NDL サーチ検索によるインポート」から「圕」で検索すると，先ほどの「圕用品研究」が「登録済み」になっているのですが，その [リンク](http://enju.next-l.jp/manifestations?parent_id=6133) をクリックすると，

> We're sorry, but something went wrong.

の画面になります。

同じことを手許の環境でやってみました。Next-L Enju Leaf 1.1.0.rc20 です。
「圕用品研究」の「追加」ボタンを押すと，今度は「資料は正常に作成されました。」となるものの，「
資料が見つかりませんでした。」と出ます。
この画面を添付します。
![ndl-failed](https://cloud.githubusercontent.com/assets/294125/11081417/d485cbce-885f-11e5-985c-a78f20d15732.png)

そして，「新着情報」などを見ても「圕用品研究」は無いので，やはり登録できていないようです。

**Comment by nabeta** [comment]
> We're sorry, but something went wrong.
> の画面になります。どこかの過程で失敗しているようです。

エラー画面になる問題は以下のコミットで修正し、enju_biblio-0.1.1としてリリースしています。デモサーバでもう一度確認していただけますでしょうか。
https://github.com/next-l/enju_biblio/commit/f9292b5391aaf9de4a49256d5555238eea6fb3ab

**Comment by scivola** [comment]
http://enju.next-l.jp/
にて，いったん「圕用品研究」を削除し，改めて最初に書いた手順で登録してみました。
今度はエラーが出ませんでしたが，結果は

> 同じことを手許の環境でやってみました。Next-L Enju Leaf 1.1.0.rc20 です。

で書いたとの同じになりました。つまり，登録後の画面に「資料が見つかりませんでした」が出ます。
そして新着情報にも載りません。

**Comment by masao** [comment]
http://iss.ndl.go.jp/books/R100000002-I000000074695-00
これは雑誌書誌を登録していますので、雑誌書誌の仕様としてこのような挙動になります。
つまり、雑誌は、まず雑誌の親書誌を登録し、さらに、各号単位の書誌を登録する必要があります。

ここで紛らわしいのですが、親書誌だけが登録された状態ですと、親の雑誌全体の書誌ページでは各号単位の一覧ができないので、「資料が見つかりませんでした」との表示が出ます。
http://next-l.github.io/manual/enju_operation_5.html#section-9

しかし、新着情報で、親の雑誌書誌が検索でヒットしないのはバグな気がしますね。

**Comment by scivola** [comment]
理解するのにだいぶかかりました。
私がやった操作だと，『圕用品研究』という雑誌は登録される（された）けれども，その雑誌の各号は 1 点も登録されていないので，「資料が見つかりませんでした」が出るのは正常である，という意味ですね？　なるほど。

で，新着情報に雑誌の情報がでないのはバグなのかどうか，と。バグなのであればまだクローズできないわけですね。
それと，NDLサーチ検索によるインポートで雑誌の一つの号を入れることはできないのでしょうか？

**Comment by nabeta** [comment]
> 私がやった操作だと，『圕用品研究』という雑誌は登録される（された）けれども，その雑誌の各号は 1 点も登録されていないので，「資料が見つかりませんでした」が出るのは正常である，という意味ですね？

そうなります。これはあまりよくないメッセージなので、「資料がまだ登録されていません」とするのはどうでしょうか。

**Comment by scivola** [comment]
#1058 があるので，こちらはクローズしますね。（いいんですよね？）

**Comment by yegusa** [comment]
はい、クローズでよいです。ありがとうございます→ @scivola
