### ISSUE TITLE
README.rdoc でコンフリクト

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#885]
README.rdoc で Git の conflict が解消されていないようです。

**Comment by yegusa** [comment]
@nabeta これは、1.1.0 に入れました?
入れてない?

適切な milstoneをつけてください　-> @nabeta

**Comment by nabeta** [comment]
これはmasterブランチのみの問題で、現在のリリース系列の1.1ブランチには影響しません。

**Comment by nabeta** [comment]
現時点では解決しているのでcloseします。
