### ISSUE TITLE
書影があるはずなのに表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#886]
いつのころからか、書影があるはずなのに表示されないものある現象が出てきたような?
デモサーバーで確認しました。

http://enju.next-l.jp/manifestations/6148
![image](https://cloud.githubusercontent.com/assets/1328499/11085878/8f8cc0d6-884b-11e5-8668-f7dbeefa8bbf.png)

例：http://ci.nii.ac.jp/ncid/BB02337287
![image](https://cloud.githubusercontent.com/assets/1328499/11085872/80403540-884b-11e5-9e71-664e73421ecd.png)

システム情報：
enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.0
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0
erubis: 2.7.0
execjs: 2.6.0
faraday: 0.9.2

**Comment by nabeta** [comment]
Google BooksのAPIのドキュメントでは、パラメータ名が"isbn"となっているのですが、
https://developers.google.com/books/docs/v1/using#PerformingSearch

実際にはそれではヒットしません。一方、パラメータ名を"isbn13"にするとヒットします。
https://www.googleapis.com/books/v1/volumes?q=isbn:9784048688635
https://www.googleapis.com/books/v1/volumes?q=isbn13:9784048688635

書影表示の部分は最近はいじっていないので、Google側の仕様が変わったのかもしれませんが、実際にそうなのかは確認できていません。ともかく、動作するようにパラメータ名を修正しますかね。

**Comment by nabeta** [comment]
念のためですが、10桁のISBNでもパラメータが"isbn"ではヒットせず、"isbn13"でヒットします。
https://www.googleapis.com/books/v1/volumes?q=isbn:4048676946
https://www.googleapis.com/books/v1/volumes?q=isbn13:4048676946

**Comment by masao** [comment]
これ、わたしも総合展のポスターをつくろうとして気付いたのですが、Google側の問題なので、対応のしようがないですね。
なお、isbn13パラメータはどこかに文書化されていますか？
上の例ではそもそも別の書誌がヒットしてしまっているのでダメな気がします。
Amazon書影を試そうかなあ。。。

**Comment by nabeta** [comment]
あ、たしかに別の書誌ですね。
isbn13は適当にやったらヒットしたというもので、文書化されていません。

**Comment by masao** [comment]
はい、わたしも ISBN: とかいろいろ試したんですがダメで、これはお手上げに近いです。。。
ひょっとしたら API Key付きでアクセスしたら、、、みたいなことしか思いつきません。

**Comment by scivola** [comment]
API がどうこうでなくて，単に書誌情報が取れる本と取れない本がある，という話である可能性はないでしょうか？

仕様書どおりの

https://www.googleapis.com/books/v1/volumes?q=isbn:XXXXXXXXXXXXX

の形式で，実在するいろんな書籍の ISBN を入れてみると，出たり出なかったりします。
書誌情報が得られた本の ISBN を使って，デモサーバーの資料受入で ISBN 使って登録してみたら，ちゃんと書影も表示されました。

http://enju.next-l.jp/manifestations/6155

**Comment by yegusa** [comment]
@scivola さん　以前は書影がとれていた isbn の本も取れなくなっているので「単に書誌情報が取れる本と取れない本がある」というわけではないようです。

**Comment by scivola** [comment]
@yegusa さん，そうですね。
しかも，一つ上のコメントに書いた「書誌情報が得られる本」も，いまやってみるとダメです。
本によって違うのではなく，そのときどきで違うのですね。

やはり authorizing の関係でしょうか。
↓このへんに何か（英語ろくに読めません）
https://developers.google.com/books/docs/v1/using#auth

**Comment by masao** [comment]
http://enju.next-l.jp/manifestations/6148
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11991773/9ff78770-aa61-11e5-93ed-2bdb75a6be1a.png)
いま見たら、同じ書籍ですが、書影がでるようになっていますね。一時的にGoogle Books APIの調子が悪い時期があるといった状況のようにみえますので、ひとまず wontfix でクローズしたいと思います。
