### ISSUE TITLE
5分毎ぐらいにソフトが停止します

### ISSUE THREAD

**Issue by mameha** [next-l/enju_leaf#887]
現在1.1.0.rc8を使用しています。
Windows 7でのインストールです。

2014年1月から最近まであまり問題なく使用しましたが、最近問題が発生しています。
5分毎ぐらいにソフトが停止します。

問題を解決する方法が考えられますか？

または、最新版に更新するほうが良いですか？
このページを読みましたが、「1.1.0.rc8ｰ>最新版」を更新するのに具体意的にどのステップをやるべきのは混乱しています。
https://github.com/next-l/enju_leaf/wiki/Update

何か手伝いして頂いたら非常にありがたいです。

**Comment by nabeta** [comment]
ログにはなにかエラーが出ていますか？
インストールしたディレクトリの log/production.log がログのファイルです。

1.1.0rc8から1.1.0のアップデートは手順を確認しますので、しばらくお待ちください。

**Comment by mameha** [comment]
返事まことにありがとうございます。

図書パソコンは学校にあるので月曜日にログを確認します。

**Comment by mameha** [comment]
ログの最後のほうを見たがあまり問題なさそうでした。

ただ、同じDirectoryでこのようなファイルがいっぱいあります：
sunspot-solr-production.log.88
sunspot-solr-production.log.88.lck
sunspot-solr-production.log.87
sunspot-solr-production.log.87.lck

![Log Directory](https://goo.gl/photos/v6p9vHHzTkSahFAz5)
https://goo.gl/photos/v6p9vHHzTkSahFAz5

[sunspot-solr-production.log.88]の中身はこれです：

```
Nov 14, 2015 9:35:01 PM org.apache.solr.core.Config getLuceneVersion
WARNING: the luceneMatchVersion is not specified, defaulting to LUCENE_24 emulation. You should at some point declare and reindex to at least 3.0, because 2.4 emulation is deprecated and will be removed in 4.0. This parameter will be mandatory in 4.0.
Nov 14, 2015 9:35:01 PM org.apache.solr.core.SolrConfig <init>
WARNING: Deprecated syntax found. <highlighting/> should move to <searchComponent/>
Nov 14, 2015 9:35:01 PM org.apache.solr.analysis.BaseTokenStreamFactory assureMatchVersion
WARNING: StandardTokenizerFactory is using deprecated LUCENE_24 emulation. You should at some point declare and reindex to at least 3.0, because 2.x emulation is deprecated and will be removed in 4.0
Nov 14, 2015 9:35:01 PM org.apache.solr.analysis.BaseTokenStreamFactory assureMatchVersion
WARNING: StandardFilterFactory is using deprecated LUCENE_24 emulation. You should at some point declare and reindex to at least 3.0, because 2.x emulation is deprecated and will be removed in 4.0
Nov 14, 2015 9:35:01 PM org.apache.solr.analysis.BaseTokenStreamFactory assureMatchVersion
WARNING: LowerCaseFilterFactory is using deprecated LUCENE_24 emulation. You should at some point declare and reindex to at least 3.0, because 2.x emulation is deprecated and will be removed in 4.0
Nov 14, 2015 9:35:01 PM org.apache.solr.request.XSLTResponseWriter <init>
WARNING: org.apache.solr.request.XSLTResponseWriter is deprecated. Please use the corresponding class in org.apache.solr.response
Nov 14, 2015 9:35:02 PM org.apache.solr.handler.component.SpellCheckComponent inform
WARNING: No queryConverter defined, using default converter
```

**Comment by mameha** [comment]
ところで、図書ユーザが間違ってmemcached、redis-server、foregoのWindowを閉じた可能性があります。

理想的にその三つのプロセスをユーザに閉じられないように起動したいです。

**Comment by nabeta** [comment]
ログには特に問題がなさそうですね。5分ごとということで、cronの設定とも思ったのですが、Windows環境なので違いそうですね。

「停止」というのは、サーバの反応がなくなる状態でしょうか。それとも、画面にエラーが出ていますでしょうか。
また、停止した後は手動で再起動しているのでしょうか。

**Comment by nabeta** [comment]
1.1.0rc7〜rc17から1.1.1のアップデートの手順をまとめました。バックアップを取った上で以下を試してみてください。
https://github.com/next-l/enju_leaf/wiki/Update

**Comment by mameha** [comment]
まことにありがとうございます！
アップデートをやってみます。

**Comment by nabeta** [comment]
過去のissueのため、クローズします。
