### ISSUE TITLE
Dockerイメージを作成する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#888]
手軽にEnjuを試すための環境として。

**Comment by yegusa** [comment]
何のことかよくわかりませんので、説明よろしく。WSでもよいので。

**Comment by masao** [comment]
参考： https://hub.docker.com/r/tuyoshia/enju/

**Comment by tfjwr** [comment]
docker hubの方にもコメントを入れましたが、docker run 時にpostgresqlのパーミッションが通らない場合は、下記のリンク先に説明があるようにdockerが使っているAUFSというファイルシステムサービスのバグが関係するようです。
https://github.com/nimiq/docker-postgresql93/issues/2#issuecomment-218165914
あくまでテスト用途ですが、示されている方法でposgreqlの起動が上手くいきました。
解決方法＞mkdir /etc/ssl/private-copy; mv /etc/ssl/private/* /etc/ssl/private-copy/; rm -r /etc/ssl/private; mv /etc/ssl/private-copy /etc/ssl/private; chmod -R 0700 /etc/ssl/private; chown -R postgres /etc/ssl/private

こちらの環境でそのまま試した際：
vagrant@ubuntu-14:~/4_docker_proj$ sudo docker run -it -p 3000:3000 -e "TZ=JST" --name enju1 tuyoshia/enju:1.1
[....] Starting PostgreSQL 9.4 database server: main[....] Removed stale pid file. The PostgreSQL server failed to start. Please check the log output: 2016-07-29 05:37:38 UTC [25-1] FATAL: c[FAILnot access private key file "/etc/ssl/private/ssl-cert-snakeoil.key": Permission denied ... failed!

修正後：
vagrant@ubuntu-14:~$ sudo docker ps -a -n=3                                                                                                                                                   
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
091a00ec939d        tuyoshia/enju:1.1   "/bin/sh -c /my_enju/"   18 minutes ago      Exited (1) 18 minutes ago                       enju1
852fa0a2dfac        tuyoshia/enju:1.1   "/bin/bash"              3 hours ago         Exited (0) 20 minutes ago                       enju_arigasan3
aa814c1a9ec3        tuyoshia/enju:1.1   "/bin/bash"              5 hours ago         Exited (1) 3 hours ago                          enju_arigasan2
vagrant@ubuntu-14:~$ sudo docker start enju_arigasan3                                                                                                                                         
enju_arigasan3
vagrant@ubuntu-14:~$ sudo docker attach enju_arigasan3
root@852fa0a2dfac:/my_enju#                                                                                                                                                                   
root@852fa0a2dfac:/my_enju# ps aux                                                                                                                                                            
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.1  20248  1908 ?        Ss   05:57   0:00 /bin/bash
root         5  0.0  0.1  17492  1136 ?        R+   05:57   0:00 ps aux
root@852fa0a2dfac:/my_enju# cat enjustart.sh                                                                                                                                                  
#!/bin/sh
/etc/init.d/postgresql start
/etc/init.d/memcached start
/etc/init.d/redis-server start
foreman start
root@852fa0a2dfac:/my_enju# sh enjustart.sh
[ ok ] Starting PostgreSQL 9.4 database server: main.
Starting memcached: memcached.
Starting redis-server: redis-server.
05:59:55 solr.1   | started with pid 84
05:59:55 resque.1 | started with pid 85
05:59:55 web.1    | started with pid 86
中略
06:00:18 web.1    | [2016-07-29 06:00:18] INFO  WEBrick 1.3.1
06:00:18 web.1    | [2016-07-29 06:00:18] INFO  ruby 2.1.5 (2014-11-13) [x86_64-linux-gnu]
06:00:18 web.1    | [2016-07-29 06:00:18] INFO  WEBrick::HTTPServer#start: pid=86 port=3000
06:00:19 solr.1   | 2016-07-29 15:00:19.221:INFO:oejs.AbstractConnector:Started SocketConnector@0.0.0.0:8983

**Comment by tfjwr** [comment]
＞修正したコンテナからimageも作成できるはずなので、追ってそれも試してみます
こちら作成し、dockerhubにpush、さらに pullして起動を確認しました。
https://hub.docker.com/r/daypla/enju-leaf-tuyoshia-debian-jessie-rev/

**Comment by nabeta** [comment]
以下に設定記事が掲載されています。
http://qiita.com/orangain/items/400f3ba7d5df6dec72c3

**Comment by nabeta** [comment]
docker-composeを用いたバージョンを作成しました。
https://github.com/next-l/enju_leaf_docker

Docker Hubのページは以下になります。
https://hub.docker.com/r/projectnextl/enju_leaf

**Comment by nabeta** [comment]
現状では、Production環境でも動作するようにしています。ただし、まだ作り直しを頻繁に行っているため、開発用途でのみ使用してください。

**Comment by nabeta** [comment]
1.4系はDockerで動作させることを前提としており、現時点でmainブランチはそのように設定されていますので、クローズします。

**Comment by nabeta** [comment]
2022年4月時点では、DockerイメージはGitHub Actionsを使って作成している。
https://github.com/next-l/enju_leaf/blob/main/.github/workflows/docker-image.yml

公開先はGitHub Container Registryを使用している。
https://github.com/next-l/enju_leaf/pkgs/container/enju_leaf
