### ISSUE TITLE
Ruby 1.9.3でテストが通らない

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#893]
tinsというgemでエラーが出ている。このgemはtest環境だけで読み込まれている。

```sh
$ bundle exec rake db:migrate
rake aborted!
SyntaxError: /home/travis/build/next-l/enju_circulation/gemfiles/vendor/bundle/ruby/1.9.1/gems/tins-1.5.4/lib/tins/method_description.rb:3: syntax error, unexpected tLABEL, expecting ')'
    def description(style: :namespace)
                          ^
/home/travis/build/next-l/enju_circulation/gemfiles/vendor/bundle/ruby/1.9.1/gems/tins-1.5.4/lib/tins/method_description.rb:4: unknown type of %string
      valid_styles = %i[ namespace name parameters ]
```

**Comment by nabeta** [comment]
このgemはterm-ansicolor gemによってインストールされる。また、term-ansicolorはcoveralls gemによってインストールされる。

**Comment by yegusa** [comment]
これ、1.1.1.1 ? Ruby 1.9.3 対応なら。

**Comment by nabeta** [comment]
coveralls gemに修正が入り、Ruby 1.9.3でも再度テストが通るようになりました。
https://github.com/lemurheavy/coveralls-ruby/commit/37ca236fba0d55644db0917e3ff4400852dc531a

**Comment by yegusa** [comment]
誰か、私の質問に答えて～

> これ、1.1.1.1 ? Ruby 1.9.3 対応なら。

**Comment by masao** [comment]
マイルストーンを 1.1.1 に移しました。

**Comment by yegusa** [comment]
@masao さん、確認よろしく。

**Comment by masao** [comment]
https://travis-ci.org/next-l/enju_leaf/builds/95031414 でテストが通っていることを確認しました。クローズします。
