### ISSUE TITLE
Next-L プロジェクトサイトを整理する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#896]
ここに issue を立てるのが不適当でしたらご指導お願いします。

Next-L プロジェクトサイトのトップページの「プロジェクトに参加する」に

> 随時ミーティングを行っています。「お知らせ」ならびに「ミーティング議事録」をごらんください。

とあり，この「ミーティング議事録」に飛ぶと，2012年までの情報しかありません。これを見て「Next-L の開発は終わったのか」と勘違いする人がいると思います。

「お知らせ」のページには，確かに

> 最新のお知らせ
> Project Next-Lのfacebookのページでご覧ください。

とあるのですが，これだけでは，お知らせ機能がこのページから Facebook へ **移管した** ことが一目では分かりづらいように思います。

「移しました」とかなんとか，そのような言葉を入れるといいのではないでしょうか。

（→　ここまではこの issue の対象とします　　by @yegusa ）

----

[Next-L Enju のページ](http://www.next-l.jp/?page=Next-L+Enju) がやや古いようです。というか，トップページとかなり重複しています。

 （→　別 issue  #902 に移しました　by @yegusa　）

----

また，このページに「Next-L Enju Leaf は，図書館業務機能を担当する Enju Leaf と OPACなどを担当する Enju Flowerの統合版となっています。」とありますが，意味がよく分かりませんでした。
「Leaf は Leaf と Flower の統合版」のように読めます。無限ループに陥りそうです。

（→ 別 issue  #903 に移しました　by @yegusa　）

----

それから，そこからたどれる [スケジュール](http://www.next-l.jp/?page=%A5%B9%A5%B1%A5%B8%A5%E5%A1%BC%A5%EB) を見ると，2011年5月にVer1.1公開予定，で終わっています。

（→ これはこのissueの対処とします　 by @yegusa ）

**Comment by yegusa** [comment]
@scivola  さん、ご指摘ありがとうございます！

お知らせの部分に、FBの画面を埋め込むようにしたり、
ミーティング議事録から「開発ワークショップ」の開催一覧へのリンク＋毎月開催を追加したりなど、
少し直してみました。

これで、開発が止まっているようなかんじがするのはだいぶ緩和されたかと思います。

Leaf の説明は @nabeta さん、修正お願いします。

あと、 @scivola  さん、Next-L の公式ページもアカウントを作成したら修正可能ですので、
直接修正するようにすることも可能ですので、検討いただけると助かります。

**Comment by nabeta** [comment]
このスケジュールのページは実態を全く反映していないので、削除するか、大きく「無効」と書くかしたほうがよいかもしれません。
http://www.next-l.jp/?page=%A5%B9%A5%B1%A5%B8%A5%E5%A1%BC%A5%EB

**Comment by scivola** [comment]
@yegusa さん，アカウントを持っても私の判断で修正できそうな箇所が見当たりませんが，どうやったら作成できるのでしょうか。

@nabeta さん，このスケジュールページは削除，に1票入れます。
スケジュールは未来のことだからです（ロードマップ？）
ヒストリー（いつどのバージョンが公開されたか）のページはあってもいいかもしれません。

**Comment by yegusa** [comment]
公式サイトのメンテナンスは有志が、個々の判断で適宜行っていますので、
 @scivola さんの判断で適宜修正してもらって大丈夫ですので、
もしよろしかったら編集ください。
（もちろん、大きな変更や、影響の大きい変更はここのissue等へ相談してもらえると嬉しいです）

以下はやり方です。

## ログインアカウントの作り方

Webサイトの一番下に、

![image](https://cloud.githubusercontent.com/assets/1328499/11256333/9ed44340-8e8e-11e5-8b49-d9c5a582f2fb.png)

↑のマークがありますので、こちらをクリックするとログイン画面が出てきます。
このログイン画面に「新しくユーザ情報を登録」というリンクがありますので
そこをたどっった先でNext-L 公式サイトの編集のためのログインアカウントを作成できます。

## ログインとページの編集

Webサイトの一番下の、

![image](https://cloud.githubusercontent.com/assets/1328499/11256333/9ed44340-8e8e-11e5-8b49-d9c5a582f2fb.png)

↑のマークをクリックして、作成したログインアカウントを使って、ログインすると、
ページの一番下に編集のためのメニューがでますので、
そのメニューを使って編集できるようになります。

**Comment by yegusa** [comment]
このissue に、複数のことがあって、対応とチェックが難しそうだったので、いくつか他のissue にわけました。

**Comment by yegusa** [comment]
Next-L の「スケジュール」のページ http://www.next-l.jp/?page=%A5%B9%A5%B1%A5%B8%A5%E5%A1%BC%A5%EB には、

2012年03月24日時点でそういう公開スケジュールだったとう事実を書いて、
最新については、 GithubのRoadmapへのリンク b) https://github.com/next-l/enju_leaf/wiki/Roadmap
を追加しました。

また、Enju のページ　c) http://www.next-l.jp/?page=Next-L+Enju の「スケジュール」は、

Next-L の a) のページへのリンクを、Githubの　Roadmap へのリンクにしました。
（ a) のページへのリンクはコメントアウトとして残してはあります、ま、どこからもリンク張られてないので
実質意味ないのですが、記録のため、なるべく削除はしたくないので）

いかがでしょう?

**Comment by yegusa** [comment]
ひととおり指摘された部分は修正できたかと思います。
@scivola  さん、確認してもらえますか?

**Comment by scivola** [comment]
確認しました。いいと思います。
（スケジュールのページの末尾の二館は現在は非 Enju でしょうか？）

さきほどサイトマップのページから「スケジュール」を削除しました。

古いページを残すことについては，サイト内検索や外部の検索エンジン経由で見えちゃうという点が若干ひっかかりますが，「記録のためなるべく削除しない」とのことですので，異存ありません。
クローズしてください。
