### ISSUE TITLE
「質問」購入リクエストがほかの管理者に見えないようです。

### ISSUE THREAD

**Issue by meinherzjin** [next-l/enju_leaf#898]
1.1.0 VM バージョンに enju_purchase_request 0.1.0 モジュールを追加しました。
モジュールの追加は問題ありませんでした。

以下の説明を読みながらいろいろ操作してみました。
http://next-l.github.io/manual/enju_operation_4.html

１）購入リクエストは作成した自分だけ見えるのがスペックでしょうか？（＝ほしい物リスト?）
　　それなら一般ユーザの購入リクエストは不可能でしょうか？

２）LibraianAが作った発注リストは管理者Bにも見えます。ただ、購入リクエストの一覧をクリックするとLibraianAが作成した購入リクエスト項目は管理者Bに見えません。

システムの問題なのでしょうか？あるいはスペックですか？

**Comment by yegusa** [comment]
まだ、動作確認をしていないのですが、

> １）購入リクエストは作成した自分だけ見えるのがスペックでしょうか？（＝ほしい物リスト?）
　　それなら一般ユーザの購入リクエストは不可能でしょうか？

一般ユーザーの購入リクエストはできるような仕様です。
購入リクエストは、User 権限であれば、自分のもののみがみえる。
Librarian権限以上であれば、全員分のが見えるというのが仕様です。

> ２）LibraianAが作った発注リストは管理者Bにも見えます。ただ、購入リクエストの一覧をクリックするとLibraianAが作成した購入リクエスト項目は管理者Bに見えません。

であるならば、それはバグかと。

動作確認後また書きます。

**Comment by yegusa** [comment]
バグですね。

Enju Leaf 1.1.0 だと、確かに、他のユーザーの購入リクエストが
一覧表示されないバグがありますね。
確認しました。

user02が登録した購入リクエストがある
http://localhost:8080/purchase_requests/1
（librarian でログインしても、購入リクエストの詳細は見れるし、
発注リストに追加もできる）
![image](https://cloud.githubusercontent.com/assets/1328499/11452623/0464b6a4-9632-11e5-976e-9f24e0c7bdee.png)

librarianでログインして、購入リクエストの一覧表示
user02の購入リクエスト分（英語の多読方法）が表示されていない
http://localhost:8080/purchase_requests

![image2](https://cloud.githubusercontent.com/assets/1328499/11452625/0a490a20-9632-11e5-93e7-05409eefff88.png)

librarianでログインして、発注リストでの購入リクエスト一覧の表示
user02の購入リクエスト分（英語の多読方法）が表示されていない
http://localhost:8080/purchase_requests?order_list_id=1

![image3](https://cloud.githubusercontent.com/assets/1328499/11452627/111a90d0-9632-11e5-8f9d-8d74b4917496.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
#324 ですでに報告していたバグでした。こっちは重複するのでクローズしておきます。

**Comment by yegusa** [comment]
@meinherzjin さん、すみません、enju_purchase_request　：このモジュールは、現在、まともに使えない中途半端な状態のようです。
