### ISSUE TITLE
Next-L 公式サイトの Enju Leaf とEnju Flowerの説明を修正する

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#903]
#896 からの派生です。

> また，このページに「Next-L Enju Leaf は，図書館業務機能を担当する Enju Leaf と OPACなどを担当する Enju Flowerの統合版となっています。」とありますが，意味がよく分かりませんでした。
> 「Leaf は Leaf と Flower の統合版」のように読めます。無限ループに陥りそうです。
> by @scivola さんより

**Comment by nabeta** [comment]
```
Next-L Enju Leaf は、図書館の業務機能や蔵書検索機能を提供するシステムです。
```

としました。

**Comment by scivola** [comment]
業務機能というのがよく分からないです（が，私が分からなくても図書館の人が分かってればいいのかな）。

それと，Flower の説明がどこかに無くていいでしょうか。

**Comment by nabeta** [comment]
> それと，Flower の説明がどこかに無くていいでしょうか。

@scivola すでにモジュールとしてはメンテナンスしておらず、記述なしとしています。

**Comment by nabeta** [comment]
> 業務機能というのがよく分からないです

「図書館の業務機能（受入・貸出管理など）」としました。

**Comment by scivola** [comment]
「業務機能」が何を指すのか明瞭になりましたし，この issue は close でよさそうに思います。
（長らく離れていたので，メンションがあってちょっとびっくり）
