### ISSUE TITLE
旧サイト（？）のページを削除

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#906]
Google 検索で，www.next-l.jp 内にデザインの古いページを見つけました。

http://www.next-l.jp/schedule.html
http://www.next-l.jp/term.html
http://www.next-l.jp/archive.html

これらはもう削除していいのではないでしょうか。

**Comment by masao** [comment]
ありがとうございます。そうですね、歴史的な文書でメンテしていないようなので、消しておきました。
