### ISSUE TITLE
マニュアルの検索フォームを追加する

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#908]
#907 で「今どういう用語を使っているのだろう」と思ったときに、マニュアル内の検索機能がないことに気付きました。手っ取り早くGoogleの検索フォームを追加するのでいいと思うのですが、いかがでしょうか。
http://next-l.github.io/manual/

**Comment by yegusa** [comment]
いいと思います。よろしくお願いします。

**Comment by nabeta** [comment]
追加してみました。
https://next-l.github.io/manual/

**Comment by yegusa** [comment]
ありがとう。
タイトル「マニュアル一覧」の下検索窓がについてるのはあれだけど、検索が動くことは確認しました。

**Comment by nabeta** [comment]
本当はヘッダ部分に入れたかったのですが、やり方がよくわかりませんでした。

**Comment by yegusa** [comment]
とりあえず、タイトルを修正しておきました。
ヘッダにいれるのは別のissueにしてこっちはとりあえずクローズしましょう。
