### ISSUE TITLE
依存ライブラリの変更：検索：sunspot 2.2.0 / Solr 4.x→sunspot 2.2.1 / Solr 5.x

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#912]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
1.2ブランチで移行済みです。基本的にSolrは設定ファイルとインデックスを作り直す必要があります。
https://github.com/next-l/enju_leaf/issues/936#issuecomment-162270875

**Comment by masao** [comment]
1.1.1以降の環境から更新すると、更新手順にSolrのバージョン指定をはずすように以下の修正が必要になりそうです：

1.1系： ``gem "sunspot_solr", "2.2.0"``
→ 1.2系： ``gem "sunspot_solr", "~> 2.2"``

**Comment by nabeta** [comment]
sunspot_solrは2.2.2以上2.3以下を使用するように追記しました。
https://github.com/next-l/enju_leaf/wiki/Update-to-1.2

**Comment by yegusa** [comment]
現在のステータス：

- 私はどうやって確認していいかわかりません。

**Comment by masao** [comment]
1.1系ではいろいろと問題がありましたが、1.2系に関しては、sunspot 2.2以降かつSolr 5系列で動いているようですので、いったんクローズします。
