### ISSUE TITLE
依存ライブラリの変更：非同期処理：resqueのみ→ActiveJobで対応するライブラリ

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#914]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
現時点で1.2ブランチはResqueを直接使用せず、ActiveJobを使用するようにしています。
https://github.com/next-l/enju_leaf/commit/d5188d881f3b47aaa980109679b16e984070d6dd

設定方法はこれから記述します。

**Comment by nabeta** [comment]
config/application.rb を以下のとおり変更してください。

```ruby
    # 以下の1行を追加
    config.active_job.queue_adapter = :resque

  end
end
```

**Comment by yegusa** [comment]
現在のステータス：

- 私はどうやって確認していいかわかりません

**Comment by masao** [comment]
こちらもひとまずコードは移行されているようですし、問題は起きていないようですので、クローズします。
