### ISSUE TITLE
依存ライブラリの変更：ファイルアップロード：paperclip→refile（余裕があれば）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#915]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
実装自体はmasterブランチで完了しています。すでにアップロードされたファイルの移行方法を記述する必要があります。

**Comment by nabeta** [comment]
ファイルの移行方法が未定のため、1.2系での移行は見送りたいと思います。

**Comment by nabeta** [comment]
現在はActive Storageへの移行を想定しています。 #1436
