### ISSUE TITLE
依存ライブラリの変更：モバイル画面振り分け：mobylette→browser + Rails本体で対応 (Action Pack Variants)

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#916]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
以下のコミットまでで実装済みです。また、開発サーバに反映済みです。
https://github.com/next-l/enju_leaf/commit/db487c6dfb49bb6c506cac7370c139eba36a19e5

**Comment by yegusa** [comment]
現在のステータス：

- 私はどうやってチェックしていいかわかりません。

**Comment by masao** [comment]
現状、特に問題は起きていないようですので、いったんクローズします。
