### ISSUE TITLE
依存ライブラリの変更：パラメータ受け取り：protected_attributes→Rails本体で対応 (strong_parameters)

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#917]
#287からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by yegusa** [comment]
> strong_parameters に移行(1.1.0.rc17) 
> 参考：Roadmap
> https://github.com/next-l/enju_leaf/wiki/Roadmap

って記述があるってことは、 1.1.0.rc17 で完了済みって理解であってるかしら?なら、milestone を　1.1.0.rc17にしてクローズしてよい?

**Comment by nabeta** [comment]
はい、1.1.0.rc17で作業済みです。

**Comment by yegusa** [comment]
じゃあ、1.1.0.rc17でクローズします。
