### ISSUE TITLE
依存ライブラリの変更：設定ファイル管理：settingslogic→dotenv-rails

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#918]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
1.1.0までで作業済みです。

**Comment by yegusa** [comment]
じゃあ、1.1.0としてクローズします。
