### ISSUE TITLE
依存ライブラリの変更：ダミーパッケージ：enju_seed→使用せず

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#919]
#287 からの派生です。

1.1から1.2の依存ライブラリの変更

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
1.1.0までで作業済みです。

**Comment by yegusa** [comment]
じゃあ、1.1.0でクローズします。

**Comment by yegusa** [comment]
> 1.1.0までで作業済みです。

Roadmapには、1.1.0ではenju_seedってありますけど?

ちなみに、 のどこかの時点　1.1.0.rc??　からってこと?
