### ISSUE TITLE
依存ライブラリの変更：認証管理：devise→omniauth-identity?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#920]
#287 からの派生です。

依存ライブラリ変更の検討中です。
ただし、いくつか問題があるため、具体的な移行時期等の目途はたっていません。

> 認証用ライブラリについては、以前の開発ワークショップでomniauth-identityへの移行を提案し、実際に動作するところまでは作ったのですが、
> 
> パスワードの互換性がない（移行しようと思えばできるようですが）
> ドキュメントが少ない
> という問題があるため、当面は移行を見送りたいと思います。
> https://github.com/next-l/enju_leaf/issues/287#issuecomment-103464224 by @nabeta

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
これは作業を行いません。移行が必要になったら新規にissueを立てます。

**Comment by yegusa** [comment]
するかも、時期検討というよりは、ゼロベースってことですね。じゃあ、これはクローズします。
