### ISSUE TITLE
依存ライブラリの変更：Bootstrap化

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#921]
#287 からの派生です。

依存ライブラリの変更として、現在検討中です。

参考：Roadmap
https://github.com/next-l/enju_leaf/wiki/Roadmap

**Comment by nabeta** [comment]
Bootstrap4でモックを作ってみる。

- [ ] トップページ
- [ ] 資料一覧
- [ ] 資料詳細

メニューの表示をどうしよう？

**Comment by nabeta** [comment]
#258 と重複のため、closeします。
