### ISSUE TITLE
sunspot_solr 2.2.1非互換での1.1対応

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#923]
#644 からの派生。sunspot_solr 2.2.1から設定ファイルに非互換の箇所があるとのこと。
1.1系列での対応はこちらで。

**Comment by nabeta** [comment]
1.1系のgemspecで、sunspot_rails-2.2.0とsunspot_solr-2.2.0に固定しています。
https://github.com/next-l/enju_leaf/blob/1.1/enju_leaf.gemspec#L33
https://github.com/next-l/enju_leaf/blob/1.1/enju_leaf.gemspec#L58

**Comment by yegusa** [comment]
@masao さん、確認お願いします。

**Comment by masao** [comment]
更新手順の文書化が必要です。現在執筆中。

**Comment by nabeta** [comment]
enju_leafはsunspot_solrへの実行時の依存関係を設定していないので、以下のように手作業でGemfileに依存関係を設定する必要があります。
https://github.com/next-l/enju_leaf/wiki/Update#updating-to-110--111

**Comment by masao** [comment]
確認しました。クローズします。

**Comment by tfjwr** [comment]
新規インストールの場合ですが、wikiの手順で、
https://github.com/next-l/enju_leaf/wiki/Install のenju leaf本体のインストールに沿ってインストールするとsunspot_solr-2.2.2が入ってしまい非互換のため上手くいきません。

$ rails new your_enju -m https://gist.github.com/5357321.txt -d データベース --skip-bundle
の
◆https://gist.github.com/5357321.txtにあるgem 'sunspot_solr', '~> 2.2'も 2.2.0に固定するとよいのではないでしょうか？


そのままインストールするとenju_leafのインストールスクリプトを実行時にsunspot関連でつまづき以下のように終わります：
Errno::ESRCH: No such process
/home/vagrant/1_enju_projects/enju_newinstall_test/vendor/bundle/ruby/2.1.0/gems/sunspot_solr-2.2.2/lib/sunspot/solr/server.rb:115:in `kill'
/home/vagrant/1_enju_projects/enju_newinstall_test/vendor/bundle/ruby/2.1.0/gems/sunspot_solr-2.2.2/lib/sunspot/solr/server.rb:115:in `stop'
/home/vagrant/1_enju_projects/enju_newinstall_test/vendor/bundle/ruby/2.1.0/gems/sunspot_solr-2.2.2/lib/sunspot/solr/tasks.rb:21:in `block (3 levels) in <top (required)>'
Tasks: TOP => sunspot:solr:stop
(See full trace by running task with --trace)
~/1_enju_projects/enju_newinstall_test$


bundle install 前にGemfile内でgem 'sunspot_solr', '2.2.0'と固定したところ以下のように上手くいきました。
Copying /home/vagrant/1_enju_projects/enju_newinstall_test/vendor/bundle/ruby/2.1.0/gems/sunspot_solr-2.2.0/solr/solr/solr.xml => /home/vagrant/1_enju_projects/enju_newinstall_test/solr
Successfully started Solr ...
        rake  environment sunspot:reindex
        rake  sunspot:solr:stop
Successfully stopped Solr ...

**Comment by nabeta** [comment]
報告ありがとうございます。1.1系のインストール用のテンプレートで、sunspot_solrを2.2.0に固定しました。
https://gist.github.com/nabeta/5357321

**Comment by yegusa** [comment]
もう一回、確認よろしく　→ @masao

**Comment by masao** [comment]
修正がはいったので、1.1系の新規インストールでも問題なさそうです。クローズします。
