### ISSUE TITLE
一般ユーザーの購入リクエストの表示に「発注リスト」と「発注時刻」が表示される

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#926]
一般ユーザーの場合は表示されるとおかしいので、削除すべき。

http://localhost:8080/purchase_requests/1
![image](https://cloud.githubusercontent.com/assets/1328499/11457131/2f1a26c4-96e4-11e5-846d-cdb720e23727.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  \* enju_biblio (0.1.1)
- enju_circulation (0.1.0)
- enju_event (0.1.17)
- enju_flower (0.1.0)
- enju_leaf (1.1.0)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0)
- enju_subject (0.1.0)

**Comment by nabeta** [comment]
これは修正済みで、enju_purchase_request-0.3.2に含める予定です。

**Comment by masao** [comment]
修正を確認しました。クローズします。
