### ISSUE TITLE
バグ：librarian権限以上のログインユーザの発注リストの購入一覧に自身の登録した購入リクエストしか表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#927]
#324 と類似です。

特定の発注リストの購入リクエスト一覧に
他者の登録した購入リクエスト分が表示されません。

2件の購入リクエストが当該発注リストに登録されていますが、
0件となっています。

- [ ] 確認
- [ ] マニュアル修正

http://localhost:8080/purchase_requests?order_list_id=1
![image](https://cloud.githubusercontent.com/assets/1328499/11457166/5109a556-96e5-11e5-83c8-1b23a046720a.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11457179/9e02f998-96e5-11e5-8013-d73a854df73e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11457185/b1ed9f9e-96e5-11e5-811c-641db2580f30.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
Librarian権限以上でログインしている場合、すべての購入リクエストを表示するようにしました。1.1.2/1.2.0で反映されます。
http://dev.next-l.jp/purchase_requests?order_list_id=1

**Comment by yegusa** [comment]
他のユーザーの購入リクエストが表示されていることを確認しました。
マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/11994125/11203a58-aa7d-11e5-82d7-76b5b49d7e74.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994132/2af7e692-aa7d-11e5-904b-c839d276b94e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
