### ISSUE TITLE
利用者の新規登録で登録した「図書館」は何のメリットがありますか?

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#928]
利用者情報の登録のマニュアルを書いています。

利用者の新規登録で登録した「図書館」は何のメリットがありますか?

**Comment by masao** [comment]
一般ユーザ権限では、いまのところ、ほとんど使われていません。書誌詳細で所蔵ラベル表示を行うかどうかくらい。
図書館員権限ですと、書誌・所蔵・イベント・利用者情報等のインポートファイルのデフォルト所属図書館の指定に使えるようですが。

**Comment by yegusa** [comment]
ありがとうございます。助かります。 
マニュアルに書けます（ #891 ）

**Comment by yegusa** [comment]
マニュアルに追記しておきました。
