### ISSUE TITLE
一般ユーザーでログインした時に、利用者情報の編集で（×「図書館」が入力できない）「図書館」「利用者グループ」「参照に必要な権限」が表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#929]
#928 にも関連します。

一般ユーザーで自身の「図書館」が<s>選択できません。</s>表示されません。

http://localhost:8080/my_account/edit
![image](https://cloud.githubusercontent.com/assets/1328499/11500082/2e32d9d2-986e-11e5-9c1b-6d5e8c1566c8.png)

librarian のとき
![image](https://cloud.githubusercontent.com/assets/1328499/11500167/a32216f4-986e-11e5-9ef4-4aa25c937e74.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
もともと自分の所属館は変更できないようになっていますが、表示されていないのはバグです。
開発サーバで修正しました。
http://dev.next-l.jp/my_account/edit

**Comment by masao** [comment]
1.2系での修正を確認したのでクローズします。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11765058/33d3bba0-a18c-11e5-96b1-8044c4b5fc22.png)

```
$ bundle list|grep enju
  * enju_biblio (0.2.0.beta.1 ab7193b)
  * enju_circulation (0.2.0.beta.1 eec63c0)
  * enju_event (0.2.0.beta.1 78964ad)
  * enju_leaf (1.2.0.beta.1 da6b411)
  * enju_library (0.2.0.beta.1 1bf907d)
  * enju_loc (0.2.0.beta.1 47d9feb)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 d4cf15a)
  * enju_ndl (0.2.0.beta.1 968b3e2)
  * enju_nii (0.2.0.beta.1 71053eb)
  * enju_oai (0.2.0.beta.1 9e2a6b6)
  * enju_purchase_request (0.1.0 5c7e517)
  * enju_subject (0.2.0.beta.1 78df20e)
```
