### ISSUE TITLE
利用者アカウントの表示の右メニューのアンカー名「貸出」「予約」「購入力リクエスト」に「の一覧」を付けてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#930]
利用者アカウントの表示の右メニューの「貸出」「予約」「購入リクエスト」の遷移先が
それぞれで、「貸出の一覧」「予約の一覧」「購入リクエストの一覧」です。

「貸出」「予約」「購入リクエスト」ではわかりにくいので、
それぞれ、「貸出の一覧」「予約の一覧」「購入リクエストの一覧」と変更して欲しい。

http://localhost:8080/profiles/3
![image](https://cloud.githubusercontent.com/assets/1328499/11605927/a689483c-9b50-11e5-86b4-8438db9eb027.png)

ToDo
- [ ] 貸出の一覧
- [ ] 予約の一覧
- [ ] 購入リクエストの一覧
- [ ] マニュアル修正

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
「一覧」を追加しました。1.1系、1.2系の両方で作業済みです。
http://dev.next-l.jp/profiles/132

**Comment by yegusa** [comment]
1.1.2 用に新しいissue を立てました。こっちは 1.2.0用にしましょう。

**Comment by masao** [comment]
修正を確認したのでクローズします。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11765088/d8759b1a-a18c-11e5-9654-39c16147ba54.png)
