### ISSUE TITLE
利用者アカウントの表示の右メニューに「貸出資料の新規作成」リンクを追加してほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#931]
ToDo
- [x] 開発
- [x] 確認
- [ ] マニュアル修正

利用者アカウントの表示画面のイメージ
![image](https://cloud.githubusercontent.com/assets/1328499/11605976/b06c17c4-9b52-11e5-9251-e5afaba0dad8.png)

当該利用者の貸出資料の新規作成画面へ
![image](https://cloud.githubusercontent.com/assets/1328499/11605950/d9078796-9b51-11e5-8af0-5e7c778195af.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
貸出時に貸出セッション情報(Basket)を作成する必要があるため、直接貸出画面に遷移するのは少し難しそうです。以下の画面であらかじめ利用者番号が入っている状態に遷移するのでいいでしょうか。
http://dev.next-l.jp/baskets/new

**Comment by yegusa** [comment]
> 以下の画面であらかじめ利用者番号が入っている状態に遷移するのでいいでしょうか。

いいと思いますよ。

**Comment by nabeta** [comment]
利用者番号が設定されている場合に、貸出時の利用者番号入力ページへのリンクを表示するようにしました。
http://dev.next-l.jp/profiles/131

**Comment by yegusa** [comment]
動くことを確認しました。（マニュアルは後で書きます）
クローズします。

### 貸出の新規作成をたどる
http://localhost:8080/profiles/24
![image](https://cloud.githubusercontent.com/assets/1328499/11993872/5b775b58-aa79-11e5-9457-808663446b4d.png)

### 当該利用者の利用者番号がはいった貸出の新規作成にとぶ
![image](https://cloud.githubusercontent.com/assets/1328499/11993867/4894e262-aa79-11e5-8fb5-93dd682357dc.png)

### 利用者番号がないときはリンクが表示されない
http://localhost:8080/profiles/14
![image](https://cloud.githubusercontent.com/assets/1328499/11993877/76d5833e-aa79-11e5-81ff-3250ab5ffb17.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
