### ISSUE TITLE
利用者の新規作成の右メニューの「インポート」を「利用者のインポート用ファイルの新規作成」に

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#932]
- [ ] 確認
- [ ] マニュアル修正 #1191 

利用者の新規作成の右メニューの「インポート」を「利用者のインポート用ファイルの新規作成」に
（インポートだとわかりにくいので、遷移先が明確になるように変更してほしい。）

利用者の新規作成 http://localhost:8080/profiles/new
![image](https://cloud.githubusercontent.com/assets/1328499/11607015/b1c92388-9b79-11e5-9f9f-e505b9edc2b1.png)

参考：遷移先　http://localhost:8080/user_import_files/new
![image](https://cloud.githubusercontent.com/assets/1328499/11607022/f56932cc-9b79-11e5-8745-0e36ad4be1c4.png)

Todo:
- [ ] 開発
- [ ] 確認
- [ ] マニュアル修正

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
ラベルを修正しました。

![2016-08-20 14 17 13](https://cloud.githubusercontent.com/assets/11428/17829165/db6e158a-66e0-11e6-95a0-11e2e6fa4bb9.png)

**Comment by masao** [comment]
修正を確認しました。クローズします。
