### ISSUE TITLE
依存ライブラリの変更：フォームの動的追加：nested_form -> cocoon

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#934]
nested_formは開発が止まっているため、cocoonに移行。
https://github.com/nathanvda/cocoon

masterブランチ・1.2ブランチですでに作業済み。

**Comment by masao** [comment]
簡単に動作確認をした範囲では特に問題ないようです。クローズします。

**Comment by masao** [comment]
/user_groups/new にてまだ古いフォーム記述が残っていて、Railsエラーになるようなので、再オープンします。

cf. http://dev.next-l.jp/user_groups/new

**Comment by nabeta** [comment]
修正し、開発サーバに反映済みです。

**Comment by masao** [comment]
修正を確認しましたので、クローズします。
