### ISSUE TITLE
書誌情報の新規入力時に著者名の自動補完

### ISSUE THREAD

**Issue by nabeta** [next-l/enju_leaf#935]
- [ ] マニュアル修正 #1191

著者名を入力する際、すでに入力済みのAgentから氏名を補完する機能を追加する。
http://dev.next-l.jp/manifestations/new

最初の実装を以下で実施。
https://github.com/next-l/enju_biblio/commit/3afe586372c5b933124c58010ee072213bf8f30f

現時点では補完はフルネームの前方一致。

**Comment by masao** [comment]
自動補完されるものの、別のAgentとなるのでは補完の意味が薄そうな気がします。。。
補完機能で選択したものは、同じIDのものを使うようにしたほうが良いと思います。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/11612597/40b43cac-9c44-11e5-88d0-578bfc23ceef.png)

**Comment by masao** [comment]
@nabeta 先にコメントした問題は解消されているように見えますが、この件、何か問題残っていますか？

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。特に問題ないようですので、いったんクローズします。
マニュアルはあとで修正します。

> 補完機能で選択したものは、同じIDのものを使うようにしたほうが良いと思います。
↑となっていることを確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/18813117/1ace7ce4-8327-11e6-9f35-5a0314f2c887.png)

![image](https://cloud.githubusercontent.com/assets/1328499/18813115/12d1aac0-8327-11e6-94b4-100fe41a9a57.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
