### ISSUE TITLE
ログイン画面でのメッセージが多言語に対応していない

### ISSUE THREAD

**Issue by nakamura-akifumi** [next-l/enju_leaf#938]
図書館全体の設定で「ログイン画面でのメッセージ」を以下のように設定しても
ログイン時のメッセージが言語にあったもので表示されず、設定値そのものが表示されてしまう。

例：
設定値
![default](https://cloud.githubusercontent.com/assets/1065528/11611484/d3c54cce-9c13-11e5-8bb8-07875dfd714a.png)

ログイン画面
![next-l enju leaf 1](https://cloud.githubusercontent.com/assets/1065528/11611492/2bc83292-9c14-11e5-91a7-c16632593a8f.gif)

**Comment by nabeta** [comment]
調べたところ、「ログイン画面でのメッセージ」はもともと多言語表記に対応していません。ちなみに中身はMarkdownで書けます。

**Comment by yegusa** [comment]
多言語に対応したいというのがこのissueの主旨です。どうやったら多言語に対応できますか?
→ @nabeta

**Comment by nabeta** [comment]
#988 の変更で、ログイン画面のメッセージも同様に編集できるようにしています。

**Comment by yegusa** [comment]
開発サーバーで確かめました。多言語対応になってません

![image](https://cloud.githubusercontent.com/assets/1328499/11774992/5bf5a218-a27e-11e5-8df5-cf9f80b687fd.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11774980/38c6766e-a27e-11e5-9056-04a6ee3f4384.png)


enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.1
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0

**Comment by yegusa** [comment]
開発サーバーで、各言語インタフェースにしたうえで、編集したものが反映されることを確認

![image](https://cloud.githubusercontent.com/assets/1328499/11775409/e783273a-a281-11e5-82cf-e89945a8ed09.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11775430/1d873844-a282-11e5-9dd6-3a910c03e3a0.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11775417/f835a526-a281-11e5-994d-ea77547f9bd1.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11775421/0ba9e702-a282-11e5-9b99-e39a256dbd37.png)

enju_biblio: 0.1.1
enju_circulation: 0.1.0
enju_event: 0.1.17
enju_flower: 0.1.0
enju_leaf: 1.1.1
enju_library: 0.1.0
enju_manifestation_viewer: 0.1.0
enju_message: 0.1.14
enju_ndl: 0.1.0
enju_purchase_request: 0.1.0
enju_subject: 0.1.0

**Comment by yegusa** [comment]
#988 で　一画面で多言語入力する方法を模索するとのこと　by @nabeta 

なのでこれもいったんcheckingから外します。
#988 とそろえてやるといいのではと思います。

**Comment by yegusa** [comment]
ログインメッセージが多言語対応していることを確認しました。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/12009453/13b44fee-acbb-11e5-85a2-85abe1aed6b5.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12009454/28856458-acbb-11e5-832b-4b54a64fcbc6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12009455/39109c48-acbb-11e5-8cd8-27a773eab373.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 6cf1bd7)
  * enju_circulation (0.2.0.beta.1 db02222)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 0882d26)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)
