### ISSUE TITLE
外部検索エンジンへのリンクの設定を標準でいれておきたい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#941]
マニュアルの

3-12 検索エンジンを設定する
http://next-l.github.io/manual/enju_setup_3.html#section3-12

にある設定をあらかじめした状態にする。

•名前: NDL Search •URL: http://iss.ndl.go.jp/
•ベースURL: http://iss.ndl.go.jp/books
•HTTPメソッド: get
•クエリパラメータ: any

•名前: amazon.co.jp •URL: http://www.amazon.co.jp/
•ベースURL: http://www.amazon.co.jp/s?
•HTTPメソッド: get
•クエリパラメータ: field-keywords
•追加のパラメータ: url=search-alias=aps

•名前: CiNii Books •URL: http://ci.nii.ac.jp/books/
•ベースURL: http://ci.nii.ac.jp/books/opensearch/search
•HTTPメソッド: get
•クエリパラメータ: q
•追加のパラメータ: format=html

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.0)
- enju_event (0.1.17)
- enju_flower (0.1.0)
- enju_leaf (1.1.0)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0)
- enju_subject (0.1.0)

**Comment by kouamano** [comment]
googleの設定
- 名前: google
- URL: https://www.google.co.jp/
- ベースURL: https://www.google.co.jp/search
- HTTPメソッド: get
- クエリパラメータ: q
- 追加のパラメータ:
- 注記:

**Comment by kouamano** [comment]
duckduckgoの設定

- 名前: duckduckgo
- URL: https://duckduckgo.com/
- ベースURL: https://duckduckgo.com/?
- HTTPメソッド: get
- クエリパラメータ: q
- 追加のパラメータ:
- 注記:

**Comment by nabeta** [comment]
2.0系以上でのインストール時に、NDLサーチをデフォルトで設定するようにしました。

**Comment by masao** [comment]
デフォルトでNDLサーチが動いていることを確認しました。クローズします。
![image](https://user-images.githubusercontent.com/38825/174467461-2d67782e-10b0-4b45-85f6-5798a5897737.png)
