### ISSUE TITLE
バグ：貸出・予約・返却→貸出履歴の画面で「返却済み」のレコードが表示されない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#951]
仮想マシンと、デモサーバーで確認しました。

仮想マシンでは、その現象を確認した後、リインデックスしたり等してたら直った（直ったときの再現方法は不明）。

返却済みがあるはずなのに、貸出中のものしか表示されてない

http://enju.next-l.jp/checkouts
![image](https://cloud.githubusercontent.com/assets/1328499/11612595/2d324e8a-9c44-11e5-9cfb-b8c5adf5c24b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
Librarian権限以上でログインしたときは、返却済みの資料も貸出一覧に表示するようにしました。1.1.2/1.2.0で反映済みです。
http://dev.next-l.jp/checkouts

**Comment by yegusa** [comment]
これ、再現方法がわかりました。

* ログインした本人の利用者情報で、「貸出の履歴を保存する」をチェックしていないと、この画面でも表示されない。
* 逆に言うと、ログインした本人の利用者情報で、「貸出の履歴を保存する」をチェックすると、この画面で返却済みが表示される

ということだったんですね。
それを直したということですね?　どういうロジックにしたのですか? →　@nabeta

**Comment by yegusa** [comment]
確認しましたのでクローズします。
マニュアルはあとで確認します。

貸出履歴が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11994786/118e45ec-aa88-11e5-8dfe-4ebfa95ef103.png)

前提：ログイン本人は貸出履歴にチェックをいれていない
![image](https://cloud.githubusercontent.com/assets/1328499/11994791/22abfab8-aa88-11e5-8de0-09a8804f20b1.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
