### ISSUE TITLE
催し物の詳細表示の右メニュー「削除」リンクを追加

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#954]
- [x] 確認
- [ ] マニュアル #1066 

http://localhost:8080/events/1
![image](https://cloud.githubusercontent.com/assets/1328499/11614084/94750520-9c7a-11e5-8dec-ff391a47390c.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
追加しました。
http://dev.next-l.jp/events/6

**Comment by yegusa** [comment]
これ、1.1.2 にも追加してるよね?

**Comment by masao** [comment]
> これ、1.1.2 にも追加してるよね（1.1.2にはしなくてよかったのに・・・・。まあ、いいけど）?

うーん、複数マイルストーンは追加できないので、別Issue立てますか？

**Comment by yegusa** [comment]
別issueたてときます。

**Comment by yegusa** [comment]
こっちは、1.2.0用に。　#958 は　1.1.2用にします。

**Comment by yegusa** [comment]
確認しましたのでクローズします。マニュアルは後で書きます。

![image](https://cloud.githubusercontent.com/assets/1328499/11994619/3389b076-aa85-11e5-88e1-08c34d1c568b.png)

削除されることも確認しました。
