### ISSUE TITLE
バグ：利用者別貸出統計で「完了」にならない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#955]
すっぴんの仮想マシン Leaf 1.1.0でおきました。

http://localhost:8080/user_checkout_stats
![image](https://cloud.githubusercontent.com/assets/1328499/11622953/c00f640e-9d0c-11e5-9c52-bbec25c1f6af.png)

- [x] 確認
- [ ] マニュアル修正

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
Resque の画面です

![image](https://cloud.githubusercontent.com/assets/1328499/11623044/7bb36494-9d0d-11e5-8fdc-4737e1909ed6.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11623061/92c075b4-9d0d-11e5-86e1-e78f23ef9abf.png)

**Comment by yegusa** [comment]
資料別貸出統計の一覧　は　完了となることを確認済みです。
http://localhost:8080/manifestation_checkout_stats
![image](https://cloud.githubusercontent.com/assets/1328499/11623465/6de8d9ea-9d10-11e5-84f8-f435031e209a.png)

**Comment by nabeta** [comment]
非同期処理用のジョブ名が異なっていました。Gemfileでenju_circulationにgithubリポジトリを使用する設定を追加して、再度試していただけますか。

```ruby
gem 'enju_circulation', github: 'next-l/enju_circulation', branch: '1.1'
```

**Comment by yegusa** [comment]
仮想マシンで試しました
できていることを確認しました。ので、クローズします。
（マニュアルはあとで修正します）

![image](https://cloud.githubusercontent.com/assets/1328499/11651081/6692ee12-9dd1-11e5-80f0-0d4e9fd4b811.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 862875d)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアル修正ずみ。
