### ISSUE TITLE
バグ：利用者別予約統計の一覧で「完了」とならない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#956]
#955　と同様です。

http://localhost:8080/user_reserve_stats
![image](https://cloud.githubusercontent.com/assets/1328499/11623336/90b7335a-9d0f-11e5-81c6-52ba11598ae2.png)

- [ ] 確認
- [ ] マニュアル修正

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
#955 と同じ原因です。

**Comment by yegusa** [comment]
仮想マシンで確認しました。クローズします（マニュアルは後で書きます）

![image](https://cloud.githubusercontent.com/assets/1328499/11651143/eae7a7f2-9dd1-11e5-83ee-a111a5f46a84.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 862875d)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアル修正ずみ。
