### ISSUE TITLE
バグ：資料別予約統計の一覧で「完了」ならない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#957]
#955 と同様です

http://localhost:8080/manifestation_reserve_stats
![image](https://cloud.githubusercontent.com/assets/1328499/11623372/d1bd2102-9d0f-11e5-87a3-72893a54a86c.png)

- [ ] 確認
- [ ] マニュアル修正

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
#955 と同じ原因です。

**Comment by yegusa** [comment]
できることを確認しました。クローズします（マニュアルはあとで書きます）

![image](https://cloud.githubusercontent.com/assets/1328499/11651183/43687c58-9dd2-11e5-896c-9dd6657aeeac.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju                  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 862875d)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアル修正ずみ。
