### ISSUE TITLE
図書館の地図が表示されません　1.1.2用

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#963]
#727 と同じです。　milestone管理の関係上追加。

- [ ] 確認
- [x] マニュアル修正

**Comment by yegusa** [comment]
確認はすんでいませんが、先行してマニュアルだけは修正しておきました。

**Comment by yegusa** [comment]
現在のステータス：

- プロキシ環境でしかチェックできないので、江草はできない
- だれかプロキシ環境の人チェックしてほしい。

**Comment by nabeta** [comment]
職場のプロキシ環境では表示できているので、ひとまずcloseします。
