### ISSUE TITLE
バグ：ログインしないでカレンダー表示すると「操作を進めるには、図書館員としてログインする必要があります。ログイン」

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#964]
- [x] 確認
- [ ] マニュアル #1066 

1.1系の仮想マシンで現象を確認しました。1.2系では確かめていません。

「操作を進めるには、図書館員としてログインする必要があります。ログイン」
このメッセージいらないとおもいます。

表示するだけだと別にログインしなくてもいいわけですし。

![image](https://cloud.githubusercontent.com/assets/1328499/11688055/8a73a1d0-9ecd-11e5-915a-2aa95c907335.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 8f39fa0)
  * enju_event (0.1.17 215e90a)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 ca5d072)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
リンクを削除しました。
http://dev.next-l.jp/events

**Comment by yegusa** [comment]
確認しました。クローズします。（マニュアルはあとで書きます）

![image](https://cloud.githubusercontent.com/assets/1328499/11994397/e1e9b3fa-aa80-11e5-994b-87f1202916d1.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
