### ISSUE TITLE
デモサーバーでadminにログインできません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#969]
http://enju.next-l.jp/users/sign_in
![image](https://cloud.githubusercontent.com/assets/1328499/11704345/61196d80-9f2a-11e5-9b51-6a27924869b2.png)

**Comment by yegusa** [comment]
修正できるかた、至急対応おねがいします!

**Comment by masao** [comment]
デモサーバ上で直接 @nabeta さんに直していただくよりほかなさそうです。。。

**Comment by yegusa** [comment]
何か、admin ユーザーが削除されたっぽい気がします。

**Comment by yegusa** [comment]
すみません、削除されてはないかも。思い違いかも。

**Comment by yegusa** [comment]
（こういう時のために、自分がログインできるadministratorアカウント作っとかないとだめですね）

**Comment by nabeta** [comment]
パスワードをリセットしました。

なお、以下はコンソールからユーザnabetaのパスワードをnewpasswordに設定する例です。

```sh
$ rails c production
> u = User.where(id: 'nabeta').first
> u.password = 'newpassword'
> u.save
> exit
```

**Comment by yegusa** [comment]
早速ありがとうございます。ログインできることを確認しました。のでクローズします。

**Comment by masao** [comment]
うーん、再度同じ現象が発生しています。。。

**Comment by yegusa** [comment]
こんなこともあろうかと、私がはいれるadmin権限アカウント作っておきました。
で、ログインして、直しておきました。

**Comment by masao** [comment]
:+1:
