### ISSUE TITLE
バグ：パスワード変更へのリンクがありません

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#971]
仮想マシンで確認しました。
（1.1.0のと見比べると、あと、「戻る」ってリンクも増えてますね）

- [x] 開発
- [x] 確認
- [x] マニュアル修正 #891

http://localhost:8080/my_account
![image](https://cloud.githubusercontent.com/assets/1328499/11706311/ca8ebfe4-9f3a-11e5-958e-4eb4dfa492d4.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 8f39fa0)
  * enju_event (0.1.17 215e90a)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 ca5d072)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

----

### 参考：　1.1.0 の同じ画面
![image](https://cloud.githubusercontent.com/assets/1328499/11706490/82e0cb86-9f3c-11e5-806b-76be9ff14c92.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0)
  * enju_event (0.1.17)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.0)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
app/views/my_accounts/show.html.erb を参照しなければならないはずですが、
app/views/profiles/show.html.erb を参照していますね。ちょっと調べます。

**Comment by nabeta** [comment]
ちなみに、enju_leaf-1.1.1では正常です。
http://enju.next-l.jp/my_account

**Comment by yegusa** [comment]
まだこのバグが修正されていないが先行してブラウザの開発機能をつかって、パスワード変更のリンクを追加することでマニュアルの修正済み。

**Comment by nabeta** [comment]
1.1系・1.2系とも修正しました。開発サーバに反映済みです。
http://dev.next-l.jp/my_account

**Comment by yegusa** [comment]
確認しました。のでクローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/11773919/613e8c68-a273-11e5-8455-58197f3e2e13.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11773942/a1b4d0d6-a273-11e5-85d9-8bb92323fa9b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)
