### ISSUE TITLE
書影に border を付ける

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#972]
![border-of-book-jacket](https://cloud.githubusercontent.com/assets/294125/11708230/58d07c56-9f50-11e5-8b66-0da81fedc213.png)
添付画像のように，書影には border を付けたほうがよいかと思います。

```css
border: 1px solid rgba(0, 0, 0, 0.25);
```

このくらいの色なら書影画像が白だったり濃い色だったりしてもさほど違和感ないと思います。

箇所ですが，ピックアップや manifestation#show に出てくる書影のセレクターは

```css
div.book_jacket img
```

でいいようです。

[enju_leaf/app/assets/stylesheets/enju.css](https://github.com/next-l/enju_leaf/blob/master/app/assets/stylesheets/enju.css) にはそれはありませんが，`div.book_jacket` なら [529 行目](https://github.com/next-l/enju_leaf/blob/master/app/assets/stylesheets/enju.css#L529) にあります。

なお，これとは別に [132 行目](https://github.com/next-l/enju_leaf/blob/master/app/assets/stylesheets/enju.css#L132) に

```css
img.book_jacket{
  border: 1px solid;
}
```

があるので，これを修正して，ビューのテンプレートで `img` に `book_jacket` クラスを付けるのがスジなのかもしれません。

**Comment by nabeta** [comment]
追加しました。
http://dev.next-l.jp/manifestations/4901

**Comment by masao** [comment]
http://dev.next-l.jp/manifestations/24424 のようなGoogleプレビューのボタンにもボーダーをつけてしまうのは避けたほうがよいかと。

**Comment by scivola** [comment]
とすると，やはり `img.book_jacket` を生かす方向がいいのではないでしょうか。

**Comment by masao** [comment]
class指定を変更して、プレビューボタンには border が付かないように変更しました。
![statistics hacks next l enju leaf](https://cloud.githubusercontent.com/assets/38825/12528610/1d28e7f4-c1df-11e5-81f5-f0ab4bd130a0.png)

**Comment by scivola** [comment]
http://dev.next-l.jp/ にはまだ反映されていないと思いますが，キャプチャーで分かるので閉めちゃっていいですね？

**Comment by nabeta** [comment]
開発サーバにも反映させました。

**Comment by yegusa** [comment]
記録のため追記：
![image](https://cloud.githubusercontent.com/assets/1328499/12554043/0663ac12-c3be-11e5-81ba-09d789bcba3b.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 47e3a3a)
  * enju_circulation (0.2.0.beta.1 d2bbdb9)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 25c8ca5)
  * enju_library (0.2.0.beta.1 30a5029)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 b797995)
