### ISSUE TITLE
バグ：マニュアルの手元の作業ファイルのリロードが遅すぎる

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#973]
Enjuのマニュアル作成しているときに、「$ jekyll build」して
手元の html ファイルを　ブラウザで見ようとすると
（リ）ロードに 30秒以上かかり、マニュアル作成に支障をきたしています。
ブラウザの種類に関係なく起こっているようです。
（多少の速さの違いはあるようなないような）

ローカルでみているのになんでそんなに遅いのか不思議でしょうがないのですが。。。
調べてもよくわからず。
（ネットから切り離すとかえって早くなるような??）

どなたか助けてください。
かなり切実です。

**Comment by scivola** [comment]
jekyll serve とかじゃなくて，build して生成した HTML ファイルをブラウザーにドロップしたりして見ても遅いってことですね？

**Comment by yegusa** [comment]
「 HTML ファイルをブラウザーにドロップしたりして見ても遅い」 → そうです。

**Comment by yegusa** [comment]
jekyll serve　ってコマンド知りませんでした!

なんと、これつかって、ローカルのWebサーバーで見れば、
いくぶん早く見れました!

ありがとうございます!　→ @scivola さん。

**Comment by yegusa** [comment]
手元の仮想マシン上で jekyll serve って、やってできるような環境を整えたところ、
かなり普通の速度でリロードの結果が表示されるようになりました。
（これまではwindows上のcygwinでやってた）

というわけで、もともとの理由の解決方法は分かりませんが、
やりたいこと（手元のhtmlの見栄えを確認するのにリロードに時間がかからないようにしたい）は
実現できたのでクローズします。

お騒がせしました!
