### ISSUE TITLE
本体サイトのマニュアル一覧を訂正する

### ISSUE THREAD

**Issue by scivola** [next-l/enju_leaf#974]
「[図書館員向けのマニュアル](http://www.next-l.jp/?page=manual#p1)」は項目名をリンク先に合わせて訂正したのですが，あと「利用者マニュアル」と「Web APIマニュアル」を追加しなければなりません。

どこに追加すればよいのか分からなかったので，お願いします。
周辺の文言も現状に照らしてご確認をお願いします。

**Comment by yegusa** [comment]
> 「図書館員向けのマニュアル」は項目名をリンク先に合わせて訂正したのですが，

初期設定マニュアルは VirtualBoxとは関係なかったので、本体の方とも合わせて削除しました

> あと「利用者マニュアル」と「Web APIマニュアル」を追加しなければなりません。

追加しました。

> 周辺の文言も現状に照らしてご確認をお願いします。
> どこに追加すればよいのか分からなかったので，お願いします。

一通り確認して修正しました（というかほかはそんなに修正箇所がなかった）。

**Comment by scivola** [comment]
ありがとうございました。では閉じちゃっていいですよね？

**Comment by yegusa** [comment]
はい。Webサイトがだんだん良くなっていってうれしいです。
