### ISSUE TITLE
貸出セッションの新規作成の右メニューの[返却]を[返却の新規作成]に変える

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#979]
- [x] 確認
- [ ] マニュアル #1066 

返却の新規作成の右メニューともそろうし、
そのほうが明確になっていてわかりやすいので
そうしたほうがよいと思います。

貸出セッションの新規作成の画面、右メニューの[返却]をクリックする
http://localhost:8080/baskets/new
![image](https://cloud.githubusercontent.com/assets/1328499/11737857/adfcce7a-a020-11e5-9006-ed050134ada9.png)

返却の新規作成　が表示される
http://localhost:8080/checkins/new
![image](https://cloud.githubusercontent.com/assets/1328499/11737865/ba84a726-a020-11e5-981d-413666bdc36b.png)

**Comment by nabeta** [comment]
1.2系で「返却の新規作成」としました。
http://dev.next-l.jp/baskets/new
<img width="924" alt="2015-12-14 0 22 00" src="https://cloud.githubusercontent.com/assets/11428/11767711/beaf6cee-a1f8-11e5-8ca8-6ece2036dd38.png">

**Comment by yegusa** [comment]
出来ていることを確認しました。マニュアルは後で書きます。
クローズします。

http://localhost:8080/baskets/new
![image](https://cloud.githubusercontent.com/assets/1328499/11994593/b94bfb8e-aa84-11e5-8a23-18a41a6d8039.png)

http://localhost:8080/checkins/new
![image](https://cloud.githubusercontent.com/assets/1328499/11994598/d1929a22-aa84-11e5-8f3f-d84239e5914e.png)
