### ISSUE TITLE
貸出資料の新規作成から利用者番号を入れたあとの画面の利用者情報の表示の工夫

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#980]
- [ ] 確認
- [ ] マニュアル修正 #1191 

現状だと

* 利用者番号がわからない
* 右メニューの一番上のリンクが謎にみえる（ユーザー名だということがわかりにくい）

という問題があるとおもいます。

例えばこんな感じにしてはどうでしょうか?
どちらもリンク先は、当該利用者の利用者情報のページに遷移します。

### 提案： 右メニューに利用者番号のリンクを追加する。利用者番号、ユーザ名のラベルを付ける
![image](https://cloud.githubusercontent.com/assets/1328499/11737976/dfe46672-a021-11e5-8222-4c292b828492.png)

----
### 現状　1.1.2beta

貸出セッションの新規作成画面で[利用者番号]を入力して[読み込み]
http://localhost:8080/baskets/new
![image](https://cloud.githubusercontent.com/assets/1328499/11737934/7a09b5be-a021-11e5-9a2c-43ecb2da9802.png)

貸出資料の新規作成の画面
http://localhost:8080/checked_items/new?basket_id=30
![image](https://cloud.githubusercontent.com/assets/1328499/11737925/57a2ccf4-a021-11e5-9571-5af4abeb4e49.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 8f39fa0)
  * enju_event (0.1.17 215e90a)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 ca5d072)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by masao** [comment]
いずれも表示するように修正しました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/17838363/b30855ac-6806-11e6-9598-b022925d9091.png)

**Comment by yegusa** [comment]
手元の仮想マシンで確認しました。マニュアルはあとで修正します。
クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/18812977/4ed90df6-8322-11e6-9163-7b3b865501d6.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.4 634889b)
  * enju_circulation (0.2.0.beta.3 933fcb1)
  * enju_event (0.2.0.beta.3)
  * enju_leaf (1.2.0.beta.3 2b5e223)
  * enju_library (0.2.0.beta.9 b115342)
  * enju_loc (0.2.0.beta.2)
  * enju_manifestation_viewer (0.2.0.beta.3)
  * enju_message (0.2.0.beta.4)
  * enju_ndl (0.2.0.beta.2)
  * enju_nii (0.2.0.beta.2)
  * enju_seed (0.2.0.beta.6)
  * enju_subject (0.2.0.beta.4)
