### ISSUE TITLE
貸出履歴の「返却期限」の「日」に改行がはいらないようにしてほしい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#981]
貸出履歴の「返却期限」が

<pre>
2016年01月0
4日 
</pre>

というふうにへんなところで改行されていて、「日」が非常にわかりにくい。
一行で「2016年01月04日」となるようにするか
せめて

<pre>
2016年
01月04日
</pre>

となるようにしてほしい。

貸出履歴
![image](https://cloud.githubusercontent.com/assets/1328499/11738052/83317d06-a022-11e5-90ef-80a9955c7e8e.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
- enju_biblio (0.1.1)
- enju_circulation (0.1.0 8f39fa0)
- enju_event (0.1.17 215e90a)
- enju_flower (0.1.0)
- enju_leaf (1.1.1 ca5d072)
- enju_library (0.1.0)
- enju_manifestation_viewer (0.1.0)
- enju_message (0.1.14)
- enju_ndl (0.1.0)
- enju_purchase_request (0.1.0 78c4280)
- enju_subject (0.1.0)

**Comment by masao** [comment]
これは昔からのEnjuの問題で、わたしもこれは不自然でよくないと思います。

以下の td 全体に word-break: break-all の設定を外したほうが良いと思います。
https://github.com/next-l/enju_leaf/blob/1.2/app/assets/stylesheets/enju.css#L240 

いかがでしょうか。

**Comment by scivola** [comment]
賛成。どちらかというと break-all のほうが特殊ケースだと思いますので，break-all にしたい箇所用のクラスを一つ作っておけばいいのではないでしょうか。

もっとも td の work-break: break-all を外しただけだと

```
2016年01月04
日
```

のケースが出てくるわけで，このチケットが要求している解決状態は微妙に満たしませんが。

**Comment by nabeta** [comment]
> もっとも td の work-break: break-all を外しただけだと

@scivola さんがが指摘されているとおり、これだけでは解決しないので、単に折り返しをしないようにするよりも、3列目と4列目を統合したほうがよい気がします。

**Comment by nabeta** [comment]
3列目と4列目を統合した画面を作ってみました。よさそうに見えます。

![image](https://user-images.githubusercontent.com/11428/57979457-d887cd00-7a58-11e9-8b1c-ba365c3d0ab6.png)

**Comment by nabeta** [comment]
この修正は1.3.3に含まれていますので、クローズします。
