### ISSUE TITLE
フッタの内容の変更方法を教えてほしい（マニュアルに書きたい）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#987]
フッタに、図書館の住所などを表示したいなどはよくあるとおもいます。

変更方法を知りたいです。
マニュアルに書きたいです。

**Comment by nabeta** [comment]
1.1系でのやり方です。

1. 以下のファイルをダウンロードし、中身を編集します。
https://raw.githubusercontent.com/next-l/enju_leaf/1.1/app/views/page/_footer.html.erb

2. インストールしてあるEnjuに app/views/page ディレクトリを作成します。    
    ```sh
$ mkdir -p app/views/page
```

3. 1のファイルを2で作成したディレクトリにコピーし、Enjuを再起動します。

**Comment by nabeta** [comment]
住所や電話番号だけでよければ、図書館の設定に入力してある情報を表示するのがよい気がしますが、ほかに書きたくなる情報にはなにがありますでしょうか。

**Comment by yegusa** [comment]
他にも変えたいということがあるようですので。分館の在り処とか、開館時間とか、まあいろいろあるみたい。
あとは、すでにある情報をけずりたいとか。

**Comment by nabeta** [comment]
ログイン画面のメッセージのように、Markdownで書けるようになっているとよいかもしれませんね。

**Comment by yegusa** [comment]
> ログイン画面のメッセージのように、Markdownで書けるようになっているとよいかもしれませんね。

そうですね。

**Comment by yegusa** [comment]
できることを確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/11774027/6c0941f0-a274-11e5-9d99-cf0fd6795113.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by yegusa** [comment]
マニュアルに追記しました。のでクローズします。

**Comment by yegusa** [comment]
3-1-3 フッタの内容を変更する
https://next-l.github.io/manual/1.1/enju_setup_3.html#sction3-1-3

↑追加したマニュアルはこれです。
