### ISSUE TITLE
フッタをmarkdownで編集できるようにしてほしい（多言語対応ありに）

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#988]
- [x] マニュアル #1066  (開発に先行してマニュアルは直してあります）

#987 からの派生です。

フッタを編集したいというニーズがあるからです。

* デフォルトのフッタのリンク等を削除したい
* 図書館名や図書館の住所、開館時間などさまざまな情報追加したい

など。

**Comment by nabeta** [comment]
1.2系でフッターの編集機能を追加しました。ライブラリとデータベースの更新が必要です。

```sh
$ bundle update
$ bundle exec rake railties:install:migrations
$ bundle exec rake db:migrate RAILS_ENV=production
```

「図書館全体の設定」の「フッターのメッセージ」で編集ができます。
http://dev.next-l.jp/library_groups/1/edit

各言語ごとの編集は、ヘッダーにある「Other languages」で切り替えて行います。複数言語のメッセージを同じ画面で編集できるかどうかは未検証です。
http://dev.next-l.jp/library_groups/1/edit?locale=en

多言語対応の編集機能には、globalize gemを使用しています。
https://github.com/globalize/globalize

**Comment by nabeta** [comment]
現時点では、既存のフッターは編集対象外でそのまま表示されます。移行スクリプトでデータベースに中身を移動できるかどうか検討中です。

**Comment by yegusa** [comment]
開発サーバーで確かめました。

#938 で多言語対応しているかのように書いていますが、

多言語対応してません。

![image](https://cloud.githubusercontent.com/assets/1328499/11774905/68d3effe-a27d-11e5-86a5-cc00b4dd44fe.png)

enju_biblio: 0.2.0.beta.1
enju_circulation: 0.2.0.beta.1
enju_event: 0.2.0.beta.1
enju_leaf: 1.2.0.beta.1
enju_library: 0.2.0.beta.1
enju_manifestation_viewer: 0.2.0.beta.1
enju_message: 0.2.0.beta.1
enju_ndl: 0.2.0.beta.1
enju_oai: 0.2.0.beta.1
enju_orcid: 0.0.1
enju_purchase_request: 0.1.0
enju_root: 0.0.1
enju_subject: 0.2.0.beta.1
equivalent-xml: 0.6.0
erubis: 2.7.0

**Comment by yegusa** [comment]
あああ、そういうことか。他の多言語対応と挙動がちがうのね。
ja: や en:　で分けるのでなくて、各言語に切り替えた編集フォームで書いた内容が
反映されるのね。挙動はわかりました。

でも、ほかと違うから、この仕様はどうなんだろう。。。

English
![image](https://cloud.githubusercontent.com/assets/1328499/11775320/2ee38d46-a281-11e5-892f-7d129eb097f9.png)

日本語
![image](https://cloud.githubusercontent.com/assets/1328499/11775359/776016f2-a281-11e5-8ab4-c9659f8570db.png)

**Comment by nabeta** [comment]
> でも、ほかと違うから、この仕様はどうなんだろう。。。

1画面で処理できたほうがよいかと思うのですが、そろえたほうがいいですかね？
今までのようにYAMLっぽい書き方だと、図書館の名称のように1行ならいいのですが、Markdownで複数行書けるようにすると、改行の処理がめんどくさそうです。

**Comment by yegusa** [comment]
例えば、こんなかんじでラベルに書いてあるとまだましかも。
マニュアルで説明するとして。

![image](https://cloud.githubusercontent.com/assets/1328499/11776835/8f958584-a28d-11e5-8909-739f742bae4e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11776877/cbbf0166-a28d-11e5-8d97-c23d65ca8e0a.png)

**Comment by yegusa** [comment]
あとは書誌データの入力の「識別子」とかでやっているように、フォームを追加できるようにするとか。

![image](https://cloud.githubusercontent.com/assets/1328499/11776959/6fdd665c-a28e-11e5-8c7e-8b720d89c188.png)

**Comment by scivola** [comment]
やり方が揃ってたほうがいいと思いますし，翻訳する人と Enju の管理操作をする人はたいてい違うと思うので，X 語のフッターを入れるために画面全体が X 語になるのはちょっとどうかな，と思いました。

**Comment by nabeta** [comment]
とりあえず、複数言語を同じ画面で編集できるかどうかをもう少し調べてみます。

**Comment by masao** [comment]
ひとまず1画面で設定言語分をまとめて編集できるようにしてみました。
![next l enju leaf](https://cloud.githubusercontent.com/assets/38825/12006708/dd801192-ac24-11e5-9d6b-48c6b8d99ada.png)

**Comment by nabeta** [comment]
ありがとうございます。globalize-accessorsというgemがあるのですね。
https://github.com/globalize/globalize-accessors

一画面で複数言語の編集ができるようになると、編集後の表示画面も複数言語を表示したほうがよいかもしれません。
http://dev.next-l.jp/library_groups/1

**Comment by yegusa** [comment]
できることを、確認しました。

![image](https://cloud.githubusercontent.com/assets/1328499/12009393/877e0a08-acb8-11e5-8fc5-a07e1edf5c8d.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12009376/282e024c-acb8-11e5-8dcd-b9799d95d285.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12009383/53a7234a-acb8-11e5-8fd2-29fa33fc5887.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 6cf1bd7)
  * enju_circulation (0.2.0.beta.1 db02222)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 0a9aed9)
  * enju_library (0.2.0.beta.1 0882d26)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 498ec1d)
  * enju_ndl (0.2.0.beta.1 ce80288)
  * enju_purchase_request (0.1.0 c3600e2)
  * enju_subject (0.2.0.beta.1 49905da)

**Comment by yegusa** [comment]
> 現時点では、既存のフッターは編集対象外でそのまま表示されます。移行スクリプトでデータベースに中身を移動できるかどうか検討中です。
https://github.com/next-l/enju_leaf/issues/988#issuecomment-164235799

現行のフッターは、デフォルトデータとして入れてしまっておいて、
現行のフッターもこみでいじれるようにすればいいのでは?

移行スクリプトでは、とくになにもせず、
移行マニュアルに、もし、フッターをカスタマイズしていた場合は
移行スクリプトでは移行されないので
自分で設定しなおす必要があると書いておくというのはどうでしょう?

**Comment by yegusa** [comment]
Todo: @nabeta ↑のコメントの反応よろしく。なにをやるのか、どうやるのか、など。

**Comment by yegusa** [comment]
先行してマニュアルは修正してありますので、開発よろしく！

**Comment by yegusa** [comment]
#1143 もついでにするとよい感じだと思う。

**Comment by masao** [comment]
デフォルトのフッタを空にして、初期データとしても現状のフッターを投入するように変えました。

**Comment by masao** [comment]
デフォルトのフッタは下記のようなものとして初期データに変換して投入するようにしてあります：

【日本語用】
```markdown
[Next-L Enju Leaf __VERSION__](https://github.com/next-l/enju_leaf), オープンソース統合図書館システム | [このシステムについて](/page/about) | [不具合を報告する](https://github.com/next-l/enju_leaf/issues) | [マニュアル](http://next-l.github.io/manual/)<br/>
Developed by [Kosuke Tanabe](https://github.com/nabeta) and [Project Next-L](http://next-l.jp).
```

【英語用】
```markdown
[Next-L Enju Leaf __VERSION__](https://github.com/next-l/enju_leaf), an open source integrated library system | [About this system](/page/about) | [Report bugs](https://github.com/next-l/enju_leaf/issues) | [Manual](http://next-l.github.io/manual/)<br/>
Developed by [Kosuke Tanabe](https://github.com/nabeta) and [Project Next-L](http://next-l.jp).
```

**Comment by yegusa** [comment]
できていることを確認したので、クローズします。

![image](https://cloud.githubusercontent.com/assets/1328499/13250760/0b68fc5e-da6f-11e5-903a-888dc67d7114.png)

![image](https://cloud.githubusercontent.com/assets/1328499/13250770/2249dbaa-da6f-11e5-8c4d-2446022f8942.png)

![image](https://cloud.githubusercontent.com/assets/1328499/13250785/34bff0a8-da6f-11e5-92ef-5b7e2727df10.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 a8fc822)
  * enju_circulation (0.2.0.beta.1 2a3c92e)
  * enju_event (0.2.0.beta.1 1483293)
  * enju_leaf (1.2.0.beta.1 caf679d)
  * enju_library (0.2.0.beta.1 1805417)
  * enju_manifestation_viewer (0.2.0.beta.1 ce471f1)
  * enju_message (0.2.0.beta.1 b71506b)
  * enju_ndl (0.2.0.beta.1 8eac8b2)
  * enju_purchase_request (0.2.0.beta.1 9065073)
  * enju_subject (0.2.0.beta.1 9f89fe6)
