### ISSUE TITLE
ほんとうですか? に代わるメッセージラベル

### ISSUE THREAD

**Issue by masao** [next-l/enju_leaf#991]
削除実行時などに表示されるダイアログ「ほんとうですか?」とのメッセージは英語メッセージ "Are you sure?" の直訳だが、現場の担当者から違和感を感じるとのコメントをもらっている。全部がひらがなで表示されるのもあいまって不自然と感じるようです。

「本当に実行してもよろしいですか?」くらいに変更したほうがよいように思われます。

![image](https://cloud.githubusercontent.com/assets/38825/11765234/bac74406-a191-11e5-9618-14ac88bef1f7.png)

**Comment by nabeta** [comment]
よいと思います。ほかの方はいかがでしょう？

**Comment by nakamura-akifumi** [comment]
私も良いと思います。

**Comment by yegusa** [comment]
私も良いと思います。

**Comment by nabeta** [comment]
1.2系で「本当に実行してもよろしいですか？」としました。

**Comment by yegusa** [comment]
確認しました。マニュアルはまた後で修正します ( #1066 ) 。

![image](https://cloud.githubusercontent.com/assets/1328499/11994422/69f2432a-aa81-11e5-8f58-049534dd834e.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994428/7f2d8ff6-aa81-11e5-8669-cd79dd387fbf.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
