### ISSUE TITLE
マニュアルの検索フォームをヘッダに入れたい

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#992]
#908 からの派生です。

今は、トップページにあるだけですが、できれば、すべてのページにでるように
ヘッダにいれたいです。
下図の赤四角あたりに。

やり方が分からないので、どなたかやってくれるとうれしいです。

https://next-l.github.io/manual/
![image](https://cloud.githubusercontent.com/assets/1328499/11771659/ba0bc9f4-a256-11e5-964d-024d19e7ac1b.png)

**Comment by scivola** [comment]
jekyll が動作する環境を作ってないので手許で試せませんが，画面全体のレイアウトは

https://github.com/next-l/manual/blob/gh-pages/_includes/themes/twitter/default.html

だと思うので，これの [ul.nav の末尾](https://github.com/next-l/manual/blob/gh-pages/_includes/themes/twitter/default.html#L44) あたりに入れればいいんじゃないでしょうか。
（良い感じに入れるにはスタイルとかいじらないといけなさそうですが）

それと，別 issue のほうがいいかもしれませんが，見た目が変です。入れ子みたいになっています。Google が用意したスタイルと Bootstrap による input のスタイルが両方効いているみたいです。

**Comment by masao** [comment]
マニュアルの改訂にあわせて検索フォームの場所をヘッダに移動してみました。

**Comment by yegusa** [comment]
いいですね!

できたのを確認しましたのでクローズします。

https://next-l.github.io/manual/1.2/
![image](https://cloud.githubusercontent.com/assets/1328499/12050665/de32315a-af3b-11e5-8473-e5fdf93314fa.png)
