### ISSUE TITLE
[貸出の表示] 画面の右メニューの[戻る]リンクが戻るになっていない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#995]
[貸出・返却・予約]の[貸出履歴]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11775876/fcaab606-a285-11e5-8303-e91d1a4b6e16.png)

[貸出期間の延長]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11775757/e20b7d2c-a284-11e5-9f1e-45d3103f13dd.png)

[表示]をクリック　
![image](https://cloud.githubusercontent.com/assets/1328499/11775743/af206468-a284-11e5-8429-dd4420832f7d.png)

[貸出の表示] が表示される 右メニューの[戻る]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11776647/18543f5c-a28c-11e5-8ffa-f0d560114a63.png)

×当該利用者の貸出履歴のみが表示される　→　戻った画面（ここでは　「貸出の編集」画面にならないとおかしい
![image](https://cloud.githubusercontent.com/assets/1328499/11775868/e06a9e8e-a285-11e5-9ed2-804a2188203f.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
「戻る」リンクについて、Webブラウザの「戻る」ボタンと同じ動作をするようにしました。
http://dev.next-l.jp/checkouts/52

**Comment by yegusa** [comment]
「戻る」の動作をするようになったのでクローズします。マニュアルはあとで修正します。

右メニューは改善の余地があると思いますが、それはまた別issueにします。

![image](https://cloud.githubusercontent.com/assets/1328499/12000402/47deb2ee-ab19-11e5-8485-c33f99b8eab7.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12000410/6b578502-ab19-11e5-9ebf-a8e32f75c145.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12000416/83dc10a2-ab19-11e5-9d3d-aec216dd5ef4.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12000419/942b9766-ab19-11e5-89d9-62589958c17d.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 7ca6e04)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 b6ba55b)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
