### ISSUE TITLE
[貸出の編集] 画面の右メニューの[戻る]リンクが戻るになっていない

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#996]
[貸出・返却・予約]の[貸出履歴]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11775876/fcaab606-a285-11e5-8303-e91d1a4b6e16.png)

[貸出期間の延長]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11775757/e20b7d2c-a284-11e5-9f1e-45d3103f13dd.png)

[戻る]をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11776007/2a5dfcf6-a287-11e5-8ddb-74578181e074.png)

×当該利用者の貸出履歴のみが表示される　ここでは全員分の貸出履歴がでないとおかしい
![image](https://cloud.githubusercontent.com/assets/1328499/11776020/398fd35c-a287-11e5-95e9-e13dfb5cd373.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

**Comment by nabeta** [comment]
「戻る」リンクについて、Webブラウザの「戻る」ボタンと同じ動作をするようにしました。
http://dev.next-l.jp/checkouts/52

**Comment by yegusa** [comment]
うーん、それならブラウザの戻る使えばいいんじゃない?
まあ、いいかなあ。

皆さん、どう思います?

**Comment by yegusa** [comment]
ま、いいや、戻るとして動くようになったので、いったんはクローズして、
右メニューの工夫については、別issueとしてたてます。
マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/12000355/51c4abd4-ab18-11e5-9c7b-e90f934fc0d7.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12000362/639b7ac2-ab18-11e5-9faf-9f4921513593.png)

![image](https://cloud.githubusercontent.com/assets/1328499/12000371/90699bc4-ab18-11e5-8127-94df310f4ada.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 7ca6e04)
  * enju_circulation (0.2.0.beta.1 b41b3ba)
  * enju_event (0.2.0.beta.1 3ecd86c)
  * enju_leaf (1.2.0.beta.1 b6ba55b)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 dc4d4cb)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 8f66dba)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
