### ISSUE TITLE
予約の新規作成の次の「予約の表示」画面の右メニュー[戻る]は[予約の一覧]にするべき

### ISSUE THREAD

**Issue by yegusa** [next-l/enju_leaf#997]
予約の新規作成画面の次の画面で、戻るリンクをクリックしたら、予約の一覧に行くので、
×　[戻る]リンク　→　○ [予約の一覧]  　とすべき

（新規作成画面に戻るのはおかしいので）

予約の新規作成画面で、利用者番号を入力し、[登録する]
![image](https://cloud.githubusercontent.com/assets/1328499/11782880/259259ee-a2b7-11e5-9c90-162b57690835.png)

×　[戻る]リンク　→　○ [予約の一覧]  をクリック
![image](https://cloud.githubusercontent.com/assets/1328499/11782754/56329a2e-a2b6-11e5-8090-ebcd6639b872.png)

予約の一覧が表示される
![image](https://cloud.githubusercontent.com/assets/1328499/11782772/83341e8a-a2b6-11e5-896e-04abf8a534d7.png)

vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.1.1)
  * enju_circulation (0.1.0 afc4ce5)
  * enju_event (0.1.17 f886ee3)
  * enju_flower (0.1.0)
  * enju_leaf (1.1.1 917e0e9)
  * enju_library (0.1.0)
  * enju_manifestation_viewer (0.1.0)
  * enju_message (0.1.14)
  * enju_ndl (0.1.0)
  * enju_purchase_request (0.1.0 78c4280)
  * enju_subject (0.1.0)

- [ ] 確認
- [ ] マニュアル

**Comment by nabeta** [comment]
「予約の一覧」に修正しました。
http://dev.next-l.jp/reserves/16

**Comment by yegusa** [comment]
予約の一覧になっていること、たどると予約の一覧が表示されることを確認しました。
クローズします。　マニュアルはあとで修正します。

![image](https://cloud.githubusercontent.com/assets/1328499/11994727/f05958ae-aa86-11e5-94b9-770a93ff6c90.png)

![image](https://cloud.githubusercontent.com/assets/1328499/11994733/fe3936ce-aa86-11e5-8649-e7b02f43d4c3.png)


vagrant@vagrant-ubuntu-trusty-64:~/enju$ bundle list | grep enju
  * enju_biblio (0.2.0.beta.1 72bb20f)
  * enju_circulation (0.2.0.beta.1 b80b167)
  * enju_event (0.2.0.beta.1 3b55f7f)
  * enju_leaf (1.2.0.beta.1 8103d3d)
  * enju_library (0.2.0.beta.1 9588750)
  * enju_manifestation_viewer (0.2.0.beta.1 948d435)
  * enju_message (0.2.0.beta.1 7b9d120)
  * enju_ndl (0.2.0.beta.1 ff17c0f)
  * enju_purchase_request (0.1.0 bc500c6)
  * enju_subject (0.2.0.beta.1 49905da)
